### ISSUE TITLE
multi-language support

### ISSUE THREAD

**Issue by CarlosJimenez** [nolimits4web/Framework7#100]
Hi Vladimir

In my app, all language support was implemented in Server using accept-language http header. I used node.js and i18n-2 module. 

On iPhone works fine. If you change the device language, the accept-language of Safari is ok.

Unfortunately, in Android (tested on 4.4.4 Nexus 5) the accept-language seems to be hardcoded in Google Chrome, independently of language of device. I only have an alternative, using javascript navigator.language and moving all multi-language support to the client side.

Do you have plans to support several languages in Framework 7?

NOTE: Firefox in Android works fine, fills accept-language ok.

**Comment by murliatdure** [comment]
:+1: 
I tried with i18next libraries.. It rocks without any problems.

**Comment by arvi** [comment]
Sharing how I did it for future reference and also to help others since I can't see any well documented regarding this concern:

```javascript
$$(document).on('DOMContentLoaded', function() {
	i18next
		.use(window.i18nextXHRBackend)
		.init({
			 "debug": true,
			  "lng": 'en', //set to dynamic e.g detect via cookie
			  "fallbackLng": 'en',
			 "backend": {
			    "loadPath": "assets/locales/{{lng}}/{{ns}}.json"
			  }
		}, function (err, t) {

			if(err) {
				console.log('[error] translation: '+ err);
			} else {
				//initialize Framework7 (https://framework7.io/docs/init-app.html)
			}
		}
	);
});
```

You must include the ff: libraries e.g via bower or npm (I did mine via bower):

- https://github.com/i18next/i18next 
- https://github.com/i18next/i18next-xhr-backend

**Comment by ZanderBrown** [comment]
so this is resolved?
