### ISSUE TITLE
Default not styled html select doesn't work.

### ISSUE THREAD

**Issue by GitUnLi** [nolimits4web/Framework7#1001]
Anyone else has this problem that select doesnt work ?
I made select like this.
`<select id="random-select" onchange="myomyo();">
                                <option id="1">1</option>
                                <option id="2">2</option>
                                <option id="3">3</option>
                                <option id="4">4</option>
                                <option id="5">5</option>
                                <option id="6">6</option>
                            </select>`

And jquery like this 
`$('#random-select').change(function(){
    alert($(this).val());
})`

And problem is that sometimes i need to tap select twice to fire this event.

**Comment by nolimits4web** [comment]
ALready fixed in dev
