### ISSUE TITLE
Sidepanel stuck on swipe

### ISSUE THREAD

**Issue by WouterBothoff** [nolimits4web/Framework7#1009]
When you swipe the sidepanel open just al little bit, hold it with your finger and click on a menu item to go to another page then the sidepanel is stuck (
I can reproduce this issue easily on my iPhone every single time, can this be fixed please?

**Comment by ZanderBrown** [comment]
Can you provide a working demonstration of the issue?

**Comment by valnub** [comment]
No response, closing.
