### ISSUE TITLE
Cannot set property 'f7View'

### ISSUE THREAD

**Issue by muthuveerappan** [nolimits4web/Framework7#1010]
Hi, I am getting the below ... 

framework7.js:247 Uncaught TypeError: Cannot set property 'f7View' of undefinedp @ framework7.js:247i.addView @ framework7.js:777(anonymous function) @ kitchen-sink.js:15

How can i resolve this ..

Thanks and Regards.,
Muthuveerappan

**Comment by jdf221** [comment]
Can you post the code you are using for adding the view? I get that error when I try to add a view using a non-existent element.

(Should be something like `app.addView(".view-main")`)

**Comment by muthuveerappan** [comment]
I am actually using the example as below .,

*my html page has *

<script type="text/javascript" src="js/framework7.min.js"></script>
<script type="text/javascript" src="js/kitchen-sink.js"></script>

*the content of kitchen-sink.js has the below *

// Init App
var myApp = new Framework7({
    modalTitle: 'OneGBU',
    // Enable Material theme
    material: true,
});

// Expose Internal DOM library
var $$ = Dom7;

// Add main view
var mainView = myApp.addView('.view-main', {
});
// Add another view, which is in right panel
var rightView = myApp.addView('.view-right', {
});



Do we need to do something extra ? Or am i missing something...


Regards.,
Muthuveerappan

**Comment by chalchis** [comment]
I just use this and start work

myapp.js
```
// Init App
//var myApp = new Framework7();
var myApp = new Framework7({   
    // Enable Material theme    
    material: true,
    animateNavBackIcon:true,
    cache: false       
});

// Expose Internal DOM library
var $$ = Dom7,
    vista_actual = '',    
    item_desmateria = '';//desc de la materia al crear nuevas evaluaciones antes de registrar    

// Add main view
var mainView = myApp.addView('.view-main', {
    // Because we use fixed-through navbar we can enable dynamic navbar
	dynamicNavbar: false,
    // Enable Dom Cache so we can use all inline pages
    domCache: false   
});

/***************************************************
      
***************************************************/
// Show/hide preloader for remote ajax loaded pages
// Probably should be removed on a production/local app
$$(document).on('ajaxStart', function (e) 
{    
	//mostrar loading
    myApp.showPreloader('Cargando...');
});

/***************************************************
      
***************************************************/

//al terminar una solicitud
$$(document).on('ajaxComplete', function (e) 
{	
	//ocultar loading   
    myApp.hidePreloader();  

  	try
	{
		//convertir en json
	  	var jsonObject = JSON.parse(e.detail.xhr.responseText);	  	

	  	//verficamos
	  	if (jsonObject.proceso_respuesta == undefined)
	  	{
	  		//dialogo
	  		myApp.alert(jsonObject.mensaje_respuesta, '<i class="fa fa-exclamation-triangle" style="font-size:30px" aria-hidden="true"></i> Error');
		}	  		
	}
	catch(e)
	{
		//si entra aqui es que se esta mostrando la vista correctamente
	 	return 'html';
	}
});

```

html

``
 <link rel="stylesheet" href="/js/scripts_mobile/css/framework7.material.css">
    <link rel="stylesheet" href="/js/scripts_mobile/css/framework7.material.colors.css">
    <link rel="stylesheet" href="/js/scripts_mobile/css//kitchen-sink.css">
<body>
.
.
.
 <script type="text/javascript" src="/js/scripts_mobile/js/framework7.js"></script>
    <script type="text/javascript" src="/js/lib/knob/knob.min.js"></script>
    <script type="text/javascript" src="/js/scripts_mobile/js/myapp_app.js"></script>
</body
``

**Comment by muthuveerappan** [comment]
thanks, will try and get back ...

**Comment by jdf221** [comment]
If that doesn't work try running `Dom7(".view-main")` and `Dom7(".view-right")` in console on the page and post what the results are. 

Should be something like this:

    Dom7 {0: div.view.view-main, length: 1}
    Dom7 {0: div.view.view-right, length: 1}

If it doesn't look like that be sure your main view actually has the "view-main" class and the right view has the `view-right` class.

**Comment by yarnball** [comment]
I am also having this issue. 

I am trying to use it with my React app. I imported the css and js script files in the index.html like so:

```<link rel="stylesheet" href=/framework7/css/framework7.ios.css>
<link rel="stylesheet" href=/framework7/css/framework7.ios.colors.min.css>
<!-- <link rel=stylesheet href=/index.css> -->
<div id=app></div>
<script src="/bundle.js"></script>

   <!-- Path to Framework7 Library JS-->
    <script type="text/javascript" src="framework7/js/framework7.min.js"></script>
    <!-- Path to your app js-->
    <script type="text/javascript" src="framework7/js/my-app.js"></script>```

**Comment by valnub** [comment]
@muthuveerappan Did chalchis' solution work for you?

**Comment by nolimits4web** [comment]
Ok, issue is definitely when you try to init View which is NOT in the DOM, so double check it

**Comment by durgeshsatyam** [comment]
hey I had the same issue with the
var mainView = myApp.addView('.view-main', {
});

and what solved my problem is that I just added the CSS class view-main in my index.html file at the index.html in the main div (just after body tag).
thanks

**Comment by China77** [comment]
var mainView = myApp.addView('.view-main');  addView is not a function

**Comment by nelson2002** [comment]
Hi everybody!
Does anybody now why I have this error: 
Uncaught TypeError: myApp.addView is not a function

I do everything as Getting Started With Framework7

**Comment by tvvignesh** [comment]
@nolimits4web Starting off with framework 7. I run into this error: myApp.addView is not a function

Reviewed each and every step and it seems to be correct. Btw, I looked into the source code, I dont see an addview function in your library. Am I doing something wrong?

**Comment by tvvignesh** [comment]
Never mind, just saw your blog post: https://blog.framework7.io/mastering-v2-router-958ea2dbd24f
