### ISSUE TITLE
need Exclude Hide Bars (Navbar and Toolbar) On Scroll 

### ISSUE THREAD

**Issue by evolutionjay** [nolimits4web/Framework7#1015]
need Exclude Hide Bars (Navbar and Toolbar) On Scroll  Option
like this
![image](https://cloud.githubusercontent.com/assets/4468540/15845742/976f956a-2ca8-11e6-9729-ced63f1d1cd2.png)

**Comment by ZanderBrown** [comment]
Could you elaborate please?

**Comment by valnub** [comment]
Question unprecise, no reponse since 1 year. Closing.
