### ISSUE TITLE
first scrolling cause blank screen on iOS, after about 5 seconds scrolling normally

### ISSUE THREAD

**Issue by zhoubhin** [nolimits4web/Framework7#1017]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Framework7 Version: 1.2.0
- Platform and Target: iPhone via iOS 9, Android devices via Android 4.4

When i try to scroll screen on iOS device,then blank screen appear, on Android devices scrolling is exactly normal

**Comment by ZanderBrown** [comment]
Could you provide a screenshot and working demonstration please?

**Comment by valnub** [comment]
Closed due to no response after more than 2 months.

**Comment by zhoubhin** [comment]
I have solved this problem.

**Comment by redders166** [comment]
Hi, i am experiencing the exact same issue, @zhoubhin can you let me know what you did to solve this?
