### ISSUE TITLE
In documentation, please change any "ajax-submit-change" to "ajax-submit-onchange"

### ISSUE THREAD

**Issue by habemusne** [nolimits4web/Framework7#1020]
The  "ajax-submit-change" functionality in Form section does not work.

I went through the js source code and I can't find the keyword "ajax-submit-change". Instead, there is "ajax-submit-onchange". The documentation for Form  --> Ajax Form Submit is now misleading here.

**Comment by nolimits4web** [comment]
There is no anything about "ajax-submit-change" in docs at http://framework7.io/docs/form-ajax-submit.html
