### ISSUE TITLE
HTML files gathered in a folder

### ISSUE THREAD

**Issue by farskid** [nolimits4web/Framework7#1023]
Currently Framework7 looks for HTML files inside root directory of project, is there any support for a situation such as putting all HTML files in a separate Folder??

**Comment by ZanderBrown** [comment]
yes just link to myfolder/mypage.html instead of mypage.html

**Comment by farskid** [comment]
There is no configure to point to the folder. How should it be done??

**Comment by nolimits4web** [comment]
It depends on your server-side routing, not related to F7
