### ISSUE TITLE
Problems with virtual DOM

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#1026]
This is a (multiple allowed):
- [x] bug
- [x] enhancement

<img width="1037" alt="screen shot 2016-06-18 at 10 49 58 pm" src="https://cloud.githubusercontent.com/assets/5016637/16174929/1d2c306a-35a9-11e6-828a-14f25aec74ef.png">
# Bug

I am trying to use donejs to create a framwork7 app. donejs uses server side rendering using a lightweight virtual dom. For some reason, it doesn't like querySelectorAll().
# Enhancement

Because donejs doesn't have problems with jQuery, I was wondering if it was possible to make a build option that replaced the DOM7 tools with jQuery?

**Comment by ZanderBrown** [comment]
I'm pretty sure this is a donejs bug rather than F7
