### ISSUE TITLE
Material View poor Tab Bar rendering

### ISSUE THREAD

**Issue by atsepkov** [nolimits4web/Framework7#1029]
### This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Framework7 Version:
  ▶ bower info framework7
  bower cached        https://github.com/nolimits4web/Framework7.git#1.4.2
- Platform and Target: CORDOVA/ANDROID
### What you did

Took your tab-bar template (http://framework7.io/examples/) and used it as a base for the app
### Expected Behavior

Content on the page is offset to not overlap with the tabs above it.
### Actual Behavior

![screen shot 2016-06-22 at 12 54 05 pm](https://cloud.githubusercontent.com/assets/2549997/16275669/fe60ded8-3878-11e6-928b-f59daf969d1f.png)

As you can see from the screenshot, the tab bar completely obstructs the title and the content. On iOS this isn't an issue because tab bar renders on the bottom.

**Comment by atsepkov** [comment]
On a related note, this tab bar on Android looks almost identical to a nav bar, yet iOS ones are distinct. Material design guidelines allow for a similar nav bar on Android as well, see here: https://material.google.com/components/tabs.html#tabs-usage. Note the use of images, is this something that can be added to Android version?

**Comment by valnub** [comment]
It works fine in the Kitchen Sink example, there is probably an error in your code.

Can you provide some runnable example?

You can use one of these templates for that:

- iOS [JSFiddle](https://jsfiddle.net/mvs820k0/)/[Codepen](https://codepen.io/nolimits4web/pen/vXmmgG)
- Material [JSFiddle](https://jsfiddle.net/u8a87yd2/2/)/[Codepen](https://codepen.io/nolimits4web/pen/pEPPPK)
