### ISSUE TITLE
Close smart select in picker with JavaScript

### ISSUE THREAD

**Issue by Armandoc6** [nolimits4web/Framework7#1031]
Hi everyone!
I'm developing my first app for Android using Framework7 and I'm trying to close a smart select with javascript.
On the website i saw a method for open smart select with js:
`myApp.smartSelectOpen(smartSelect)`

Is there something similar for close?
I also tried to trigger a click event on "close-picker" (`$(".close-picker:eq(0)").trigger("click")`) but this is not working while `alert($(".close-picker:eq(0)").html())` is working.

Thanks and sorry for my bad english :(

**Comment by chalchis** [comment]
indicate this property
data-back-on-select="true"

 
    <li><a href="#" class="item-link smart-select" data-back-on-select="true">
.
.
.

**Comment by Armandoc6** [comment]
Thanks. This works but what I really need is that if the back button on android is clicked and the smart select is visible then close the smart select. I can override the backbutton event and check if smart-select is visible but i can't close it

**Comment by chalchis** [comment]
you can show screenshoot

**Comment by Armandoc6** [comment]
Sorry for the late response :(
So, I'm in this situation.
I want that if the user press the android back button, then the smart select will close.
![screenshot_20160627-084223](https://cloud.githubusercontent.com/assets/11063824/16371246/99ce179e-3c45-11e6-8af5-b0fa81e77a17.png)

**Comment by Junior-Costa** [comment]
Try: mainView.router.back()

**Comment by ZanderBrown** [comment]
that will take the user back a page. not what was asked for

**Comment by Junior-Costa** [comment]
Well, i had the same issue: close openned smartSelect using android back button, and i solved like that. I dont used picker but searchbar and worked very well.

**Comment by ZanderBrown** [comment]
yeah because you probably had smartSelect as a page so going back would close it

**Comment by sfontana7** [comment]
What about something like this:

if ($('.smart-select-picker.modal-in').length > 0) {
     myApp.closeModal('.smart-select-picker.modal-in');
}

**Comment by jensbits** [comment]
@sfontana7 I tried everything mentioned above before finding this thread and your solution was the only thing that worked for me.
