### ISSUE TITLE
formFromJSON problem with single Smart Select

### ISSUE THREAD

**Issue by tinyCoder32** [nolimits4web/Framework7#1032]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
### What you did

use formFromJSON to fill my form which has a single Smart Select box.
### Expected Behavior

to select the `<option>` and change the `<div class="item-after"></div>` value to the selected item too.
### Actual Behavior

the  `<option>`is being selected when i open the Smart Select box, but the `<div class="item-after"></div>` value is still holding the old default selected `<option>`.

is there any quick fix please? or am i missing something?

Thanks.

**Comment by nolimits4web** [comment]
Already fixed in dev
