### ISSUE TITLE
preprocess before ajax load (override page load method)

### ISSUE THREAD

**Issue by vontio** [nolimits4web/Framework7#1036]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [x] feature-discussion (RFC)
- Framework7 Version: 1.4.0
- Platform and Target: CORDOVA,ANDROID
### What you did

All my pages are embed in js. Don't need ajax anymore.
I setup a preprocess function on Application, BUT it called after ajax complete.
### Expected Behavior

split preprocess into two parts, before load, after load
So we can override load method, or only do content filter.
### Actual Behavior

preprocess is called after ajax complete.

**Comment by ZanderBrown** [comment]
Template7 would be more appropriate i belive
