### ISSUE TITLE
Form ajax submit should have a another behavior like link ajax load page 

### ISSUE THREAD

**Issue by bastengao** [nolimits4web/Framework7#1038]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [ ] feature-discussion (RFC)
- Framework7 Version: 1.4.2
- Platform and Target: IOS, ANDROID.
### What you did

I have a form with class "ajax-submit". When submit the server will return html content (well formed page structure). 
### Expected Behavior

When submit, the view will be replaced with response html content.
### Actual Behavior

when submit, it only send ajax request then do nothing, but not replace the view with response content.

So I hack by myself.

``` javascript
$$('#form').on('submitted', function (e) {
     mainView.router.load({url: e.detail.responseURL, content: e.detail.data});
});
```

**Comment by ZanderBrown** [comment]
The correct event to listen for is `form:success`
