### ISSUE TITLE
need i18n 

### ISSUE THREAD

**Issue by evolutionjay** [nolimits4web/Framework7#1041]
This is a (multiple allowed):
- [ ] bug
- [ ] enhancement
- [x] feature-discussion (RFC)
- Framework7 Version: 1.4.2.
- Platform and Target: ALL, Document API
### Translation

some one want to translation the Framework7 API document to local language？ How to？

**Comment by centrual** [comment]
There is one tutorial i saw:
http://ekhlakov.blogspot.com.tr/2015/05/phonegap.html

**Comment by ZanderBrown** [comment]
This is out of F7's scope
