### ISSUE TITLE
pageInit callback not called when cached page load from url

### ISSUE THREAD

**Issue by bingzheyuan** [nolimits4web/Framework7#1042]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v 1.4.2.
* Platform and Target: desktop chrome v52 64bit simulated iphone 6

### What you did
I have domCache enabled
```javascript
var mainView = myApp.addView('.view-main', {
    domCache: true //enable inline pages
});
```
and dom is something like
```html
 <div class="pages">
          <!-- Home page -->
          <div class="page" data-page="index">
            <div class="page-content">
              <p>Home page</p>
            </div>
          </div>
 
          <!-- About page -->
          <div class="page cached" data-page="about">
            <div class="page-content">
              <p>About page</p>
            </div>
          </div>
</div>
```
then in url i type
```
http://localhost/myapp/#!/#about
```
so that i can get to about page directly, as expected, about page shows up.

### Expected Behavior
```javascript
myApp.onPageInit("about",function(page){
   // code here should be executed
})
```

### Actual Behavior
Code not executed.
I also enable a plugin which has a hook to `pageInit` event, it shows the pageInit has been called for page "about". However the `onPageInit` callback is not called.

**Comment by nolimits4web** [comment]
The callback was called at page initialization on app load/init because this page already in was in DOM. Just hook to `pageReinit` event instead here
