### ISSUE TITLE
Page Animations stuck on Chrome Canary 54.0.2787.0

### ISSUE THREAD

**Issue by thomasf1** [nolimits4web/Framework7#1048]
In the latest Chrome Canary (Version 54.0.2787.0 canary (64-bit)) the page transition animations don´t work. (Can also be experienced on http://framework7.io/

It might be something that will get fixed in Chrome, but I guess it´s good to have a heads up...

**Comment by valnub** [comment]
See https://muut.com/framework7#!/framework7/questions:subnav-bar-material-design

**Comment by valnub** [comment]
Hi, thanks for reporting.

Are you refering to Desktop or Mobile Chrome?

Window or Mac?

**Comment by nolimits4web** [comment]
Thanks! Ok, now it looks like it is everything ok in same stable branch versionThanks! Ok, now it looks like it is everything ok in same stable branch version
