### ISSUE TITLE
Show/Hide indicators should be singleton

### ISSUE THREAD

**Issue by farskid** [nolimits4web/Framework7#1049]
Two methods on an instance of Framework7 are `showIndicator()` and `hideIndicator()`. These two are surprisingly not implemented as singleton resulting in multiple instances of loadings on top of each other.
Is it implemented like so intentionally or should be fixed??
###### Note
This is important when global `onAjaxStart` and `onAjaxComplete` config properties have been passed to the instance and also some manual show/hide methods have been called through different segments of application.

**Comment by valnub** [comment]
Good point
