### ISSUE TITLE
the abnormal  when route is set false

### ISSUE THREAD

**Issue by ijry** [nolimits4web/Framework7#1050]
the tab become abnormal  when route is set false

**Comment by ijry** [comment]
i  fixed user this code
$(document).on('click', 'a.tab-link', function(e) {
       e.preventDefault();
 });

**Comment by ijry** [comment]
it seems a bug caused by html #

**Comment by valnub** [comment]
What?

**Comment by ijry** [comment]
if router(ajax page) is closed,than  tabs will not work!!!

发自我的 iPhone

**Comment by valnub** [comment]
What do you mean by "router closed"?

Can you provide some code example?

**Comment by ijry** [comment]
it means i config like this 
ajaxLinks: '.smart-select'  
then a page has tabs will not work.
发自我的 iPhone

**Comment by ijry** [comment]
I use this code to fix it temprorary:

$(document).on('click', 'a.tab-link', function(e) {

       e.preventDefault();

});

发自我的 iPhone

**Comment by ZanderBrown** [comment]
This was never fully explain and appears to be resolved
