### ISSUE TITLE
Modal popover not removing active-state class after closing on iPad

### ISSUE THREAD

**Issue by jascolley** [nolimits4web/Framework7#1052]
After closing the popover on iPad and then relaunching it by clicking the link it appears that the active-state class is not being removed from the clicked link within popover. I just have a basic popover that displays a list of items. If I click an item it closes the modal (because I have the close-popover class on each item). However, as soon as I click the link to show the popover again any item previously tapped still has it's active-state class applied. It works fine in Chrome, just not on iPad in mobile Safari.

**Comment by valnub** [comment]
Can someone confirm this? I have no iPad :D

**Comment by ZanderBrown** [comment]
Can @nolimits4web, @macdonst or anyone else investigate this?

Could @jascolley provide a CodePen / jsFiddle reproducing the issue?

**Comment by jascolley** [comment]
This is not an issue. Sorry for the delayed response. It turned out this just had to do with the way we were rendering modals and popovers in React. Once we started using react-portal to render our popovers we no longer experienced any issues. I simply forgot to close this issue. I apologize!
