### ISSUE TITLE
mainView.router.loadPage do not work on Windows 8.1

### ISSUE THREAD

**Issue by HigorSilvaRosa** [nolimits4web/Framework7#1053]
This is a (multiple allowed):
- Framework7 Version: 1.4.2.
- Platform and Target: Windows (Cordova).

Im trying to redirect my main view to a page. Im using this line of code:

`mainView.router.loadPage("home.html");`

I also have tried to use this version:

`mainView.router.load({ url: "home.html"});`

I just want redirect my user to another page via JavaScript.

The problem is that my application crashes and close. Everything works on Android, but on Windows a have this issue. Does someone know how can I solve that?

Thank you!

**Comment by HigorSilvaRosa** [comment]
The problem was not related not "mainView.router.loadPage".

**Comment by aweoluwafemi** [comment]
Hi HigorSilvaRosa, Have you been able to solve this? encountered the same issue myself, havent gotten any solution.

**Comment by valnub** [comment]
@HigorSilvaRosa Does the issue still exist after latest Cordova updates?

**Comment by ZanderBrown** [comment]
This seems to be resolved
