### ISSUE TITLE
pushState hash navigation is only work in main view

### ISSUE THREAD

**Issue by hearain** [nolimits4web/Framework7#1054]
I have more than one view in a page , for example use tab view , pushState hash navigation is only work in main view, I can't set multi main view , so is there some way to set main view dynamically, or is there some right way to solve the problem?

**Comment by areyouse7en** [comment]
I got the same problem

**Comment by ZanderBrown** [comment]
if you read the docs you will see it's only supported for main view. I guess if you did some weird '.view-main' toggling you might get somewhere

**Comment by yezongyang** [comment]
I got the same problem for multi view

**Comment by ZanderBrown** [comment]
Well how do you suggest f7 works out what view the address should be loaded  into?

Unless someone has a very good, user-friendly idea:

> It's not a bug. It's a feature

**Comment by yezongyang** [comment]
[https://github.com/nolimits4web/Framework7/issues/802](url)

**Comment by iHackify** [comment]
here use this code

```
$$('.tab-link').on('click', function() {
    var currentMainView = $$('.view-main');
    var newMainViewLink = $$(this).attr('href');
    var newMainViewSelector = $$('#'+newMainViewLink);
    currentMainView.removeClass('view-main');
    newMainviewSelector.addClass('view-main');
}
```

i just did that off the top of my head so i hope it works

**Comment by valnub** [comment]
@hearain @areyouse7en @yezongyang Does this fix your issue?

**Comment by iHackify** [comment]
@valnub it fixed mine and i can do a quick video test if u like

**Comment by valnub** [comment]
Nah, if it fixed the problem, it's ok ;-)

**Comment by iHackify** [comment]
oh ok

**Comment by valnub** [comment]
Closed due to no reaction
