### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by snowbreeze** [nolimits4web/Framework7#1059]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: Framework7-1.4.2
* Platform and Target: MAC

### What you did
Download Framework7-1.4.2 from git
Extract
npm install
gulp

### Expected Behavior
The basic app as showin in the demo should come up

### Actual Behavior
A broken app is coming

![screen shot 2016-07-11 at 1 16 09 pm](https://cloud.githubusercontent.com/assets/8898721/16723289/ac874fb6-4769-11e6-8c51-e05c998f1ce6.png)

**Comment by FrankWiebe** [comment]
I had the same issue. I fixed it by renamed the "dist" folder to "build"

**Comment by valnub** [comment]
You need to build the styles first. This fixed the issue for me:

```
$ gulp styles-ios
$ gulp styles-material
$ gulp
```
