### ISSUE TITLE
JavaScript error: framework7.js:12067: SyntaxError: DOM Exception 12: An invalid or illegal string was specified.

### ISSUE THREAD

**Issue by myu** [nolimits4web/Framework7#1063]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement

* Framework7 Version: Framework7 1.4.2
* Platform and Target: CORDOVA, IOS.

### What you did
I  submit register form in a register page, and load user page, but just this moment,   Xcode console show this message，and aways stay at register page，the Preloader show all the time:
JavaScript error: framework7.js:12067: SyntaxError: DOM Exception 12: An invalid or illegal string was specified.

**Comment by ZanderBrown** [comment]
looking at the error I ask: what string was specified.

**Comment by nolimits4web** [comment]
Closing as no further discussion
