### ISSUE TITLE
app.showTab can not load new page url

### ISSUE THREAD

**Issue by shenglingshi** [nolimits4web/Framework7#1065]
I'm use  tabbar in toolbar and use through layout,when I use tab-link and target a new page url.Framework7 don't load new page.
So I edit source file and modify app.showTab function.
so now,framework7 can load new page.I think framework developers love it and i hope Vladimir Kharlampidi can accept it.
`//If link a new page
        	if(tab.indexOf('.html')>0){
        		
        		//Get view to load new page
        		var viewName=$(tabLink).attr('data-view');
        		if(viewName){
        			//use target view load new page
        			var targetView = $$(viewName);
        			if(targetView.length>0){
        				var view=targetView[0].f7View;
        				if(view!=undefined){
        					view.router.load({
        						url:tab
        					});
        				}
        			}
        		}
        		else{
        			//use main view load new page
        			for (var i = 0; i < app.views.length; i ++) {
					  var view = app.views[i];
					  if (view.main){
					  	view.router.load({
					  		url:tab
					  	});
					  }
					}
        		}
        		
        		return;
        	}`

**Comment by ZanderBrown** [comment]
that isn't really the point of tabs
