### ISSUE TITLE
help with loading the content

### ISSUE THREAD

**Issue by henriqueweiand** [nolimits4web/Framework7#1068]
Hello,
I need some help with loading dynamic contents to the app pages. I'm working as follows:

```
myApp.onPageBeforeInit('eventos', function(page) {

$.ajax({
            url         : config.domain+'Evento/get/all',
            data        : {},
            method      : 'POST',
            success: function(data){
                $$(page.container).html(renderPage(page.container, {'eventos': data.response}));
            }
        }).fail(function (jqXHR, textStatus) {
            console.log('erro ajax');
        });

});
```

However well the content of the page is displayed with the condidições mustachejs (very similar to template7 lib) and after a few seconds renders.
I believe that this occurs because the request time to return the server costs some time until he returns to then render. I need to render and then preferably be displayed...

Any tips for this process?

**Comment by henriqueweiand** [comment]
I believe I have found something that can help me, however still can not implement properly.

```
var myApp = new Framework7({
    preprocess: function (content, url, next) {

        if (url === 'templates/eventos/eventos.html') {

            $.ajax({
                url         : config.domain+'Evento/get/all',
                data        : {},
                method      : 'POST',
                success: function(data){
                    next(renderPage(content, {'eventos': dataReponse.response}));
                }
            }).fail(function (jqXHR, textStatus) {
                console.log('erro ajax');
            });

        }
    },
    modalTitle  : config.title,
    init        : false,
    material    : true,
    pushState   : true
});
```

When using this way I believe it was to work ... However the page does not load.

**Comment by henriqueweiand** [comment]
My function rendering was in error ...: P

I managed to solve even using preprocess. I do not know if it's the right way, but it worked ... If anyone has any other ideas more pretica and usual for this process, I'm open to suggestions

**Comment by chalchis** [comment]
Are you trying to call a page in another domain or the same domain?

**Comment by henriqueweiand** [comment]
is other domain, but add on php header for allow for all

**Comment by henriqueweiand** [comment]
is work with preprocess, but

**Comment by chalchis** [comment]
```
$$(document).on('click', '.popup-link', function(e)
{
    e.preventDefault();
    $$.get($$(this).attr('href'), function (content)
    {
        myApp.popup('<div class="popup popup-services">' + content + '</div>');
    });
});
```

**Comment by valnub** [comment]
Hi, do you still have this issue or can it be closed?
