### ISSUE TITLE
Swipeout button disappears when used in side panel

### ISSUE THREAD

**Issue by jvence** [nolimits4web/Framework7#1069]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.4.2
* Platform and Target: ALL

### What you did
Added a swipeout in a side panel

### Expected Behavior
Swipeout buttons should appear on screen

### Actual Behavior
Button disappears from screen 

This is probably due to the fact that it is expected a parent that takes up 100% width

**Comment by valnub** [comment]
What is a "swipeout"?

Can you please post a jsfiddle or codepen example so we can reproduce this issue? Thanks.

- http://www.jsfiddle.net
- http://www.codepen.io

**Comment by ZanderBrown** [comment]
http://framework7.io/docs/swipeout.html <- swipeouts

**Comment by valnub** [comment]
Ah, thanks @ZanderBrown :-)

**Comment by valnub** [comment]
I cannot reproduce the issue: https://jsfiddle.net/valmar/hxuj7bt4/

Seems to work fine for me.
