### ISSUE TITLE
smart select does not update title when value of select change dynamiclly 

### ISSUE THREAD

**Issue by hamedmohammadi** [nolimits4web/Framework7#1070]
but when you open the popup the correct value is selected i saw the library but i can't find any helpfull function to refresh view

**Comment by chalchis** [comment]
show screen please!

**Comment by ZanderBrown** [comment]
I'm guessing you mean changed through JS? That wouldn't change the title because the click handler won't be run because their wasn't a click

**Comment by valnub** [comment]
Closed due to no response

**Comment by ZanderBrown** [comment]
Related to #910
