### ISSUE TITLE
autocomplete component check the value

### ISSUE THREAD

**Issue by shenglingshi** [nolimits4web/Framework7#1072]
in the handleDropdownClick function,there have a line code below

```
for (var i = 0; i < a.items.length; i++) {
                    var itemValue = typeof a.items[i] === 'object' ? a.items[i][a.params.valueProperty] : a.items[i];
                    var value = clicked.attr('data-value');
                    if (itemValue === value || itemValue * 1 === value * 1) {
                        clickedItem = a.items[i];
                    }
                }
```

So there is a question.
when my datasource have two string value "0051" and "00051",the compare way make "00051" is equals "0051",but it's not equal actualy!

**Comment by ZanderBrown** [comment]
Is this related to #1071 ?

**Comment by shenglingshi** [comment]
No related，this  code segment is source code of framework7( src / js / autocomplete.js  line 307) I  think  this compare way maybe make a bug in the future!

**Comment by ZanderBrown** [comment]
Ah i now see you point. care to contribute a fix?
