### ISSUE TITLE
Navigating in ajax pages after 2 pages

### ISSUE THREAD

**Issue by Jeelig** [nolimits4web/Framework7#1074]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.4.2
* Platform and Target: iOS

### What you did
**Page1 -> Page2 -> Page3** (pages being Ajax pages)

And then
**mainView.router.back()**

### Expected Behavior
Go back to "Page2"

### Actual Behavior
No back navigation !

**Comment by Jeelig** [comment]
Hi,
I'm using the last version of Framework7 (1.4.2) and I have an issue with ajax pages.
For the one or two first pages when you go through navigation and come back, it's alright. But when you go deep in the navigation, it looks like the navigation is broken. You won't be able to use "...router.back()" to go back to the previous page.
I've checked the docs and I have seen no such explaination about this behavior, that's why I decided to create an issue. I tried different ways, with a simple link button with class back. 
Nothing seem to make this work.
Thank you

**Comment by wang4978** [comment]
I have the same question

**Comment by valnub** [comment]
Hi, sorry for the late reply.

Can you please post a jsfiddle or codepen example so we can reproduce this issue? Thanks.

- http://www.jsfiddle.net
- http://www.codepen.io

**Comment by Jeelig** [comment]
It is particulary difficult to create a fiddle or coden since this uses ajax pages. 
I tried but ... they all allow one html file when this needs at least 2 html files to use ajax pages.
I can send you a zip with a sample project for example.

**Comment by ZanderBrown** [comment]
that could be helpful

**Comment by Jeelig** [comment]
You can test here :
http://kilma.fr/fiddle/

**Comment by Jeelig** [comment]
Here is the Fiddle : https://jsfiddle.net/zq08gL2p/4/

**Comment by Jeelig** [comment]
Any idea? What is this behavior due to?

**Comment by valnub** [comment]
Could this be the same problem as in #1151 ?

**Comment by Jeelig** [comment]
Could be ... The behavior is the same.
Now you have a fiddle.
Any idea about how to solve this?

**Comment by valnub** [comment]
I created an own fiddle stripped down to the minimum required code and it works there: https://jsfiddle.net/valmar/uqd86fet/

So, I guess it is not a bug in F7. The problem must be in your code. Let's see if we can find the difference between both.

**Comment by valnub** [comment]
Ah, ok. Here is the problem: You defined a general navbar and another one for detailsPage but none for the other pages. That's where things get a bit funky.

So, either you use one navbar for all pages **_or_** you define one navbar for each page (if you have 5 pages, use 5 navbars).

I fixed it for you in your code and it works now: https://jsfiddle.net/valmar/xf5L9ss3/

Does this solve your problem?

**Comment by Jeelig** [comment]
Ok, I got it.
The problem in this case was with the header. Thank you for your help.
But I can't figure out why it doesn't behave the same with ajax pages.
Unfortunately concerning ajax pages I can't use a fiddle as I said previously. 
I will send you a link to show exactly what's wrong.
Half of the issue is solved, thx

**Comment by valnub** [comment]
I think you can simulate Ajax requests in jsfiddle: http://doc.jsfiddle.net/use/echo.html
In jsfiddle, click "Ajax requests" on the left:

![ajax echo](https://cloud.githubusercontent.com/assets/3787662/19189798/2988f0bc-8c9a-11e6-9b1d-c73e0de947ca.jpg)

As an alternative, you could enable CORS on your webserver which serves the pages: http://enable-cors.org

**Comment by valnub** [comment]
Also, did you read this about using F7 with Ajax Pages and Angular? http://www.timo-ernst.net/blog/2016/02/24/how-to-use-ajax-pages-with-angular-1-x-in-framework7/

**Comment by Jeelig** [comment]
I tried your example. And I think my problem was due to anything else but not F7.
So I close the issue

**Comment by xiefangzhenz** [comment]
@jeelig I find this issues,how can I solve it?
