### ISSUE TITLE
Back button refuses to work after dynamically generating a page.

### ISSUE THREAD

**Issue by kodejuice** [nolimits4web/Framework7#1075]
- [ ] enhancement
- [x] bug
- [ ] feature-discussion (RFC)
- Framework7 Version: 1.4.2
- Platform and Target: Android
### Current page back button refuses to go back after a dynamically generated page was created.

**What i did:**
Opened a page named 'Search' **>>** Generate a new page with `mainView.router.loadContent(HTML)` **>>** Clicked back button in generated page **>>** Clicked back button in 'Search' page **>>** Refuses to go back, ignores click.

**Comment by valnub** [comment]
Hi, sorry for the late reply.

Can you please post a jsfiddle or codepen example so we can reproduce this issue? Thanks.

- http://www.jsfiddle.net
- http://www.codepen.io

**Comment by ZanderBrown** [comment]
Could you please expand you point?
Consider pointing code snippets here, on [Codepen](https://codepen.io) or on [JSFiddle](https://jsfiddle.net).
Make sure you have read the [documentation](http://framework7.io/docs/) correctly and followed any instructions it may give.

**Comment by ZanderBrown** [comment]
There hasn't been a response by the issues owner in 20 days.
This issue **will be closed in 7 days** if no further response is submitted
