### ISSUE TITLE
Add component : Pagination

### ISSUE THREAD

**Issue by evolutionjay** [nolimits4web/Framework7#1077]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: 1.4.2.
* Platform and Target: ALL.

I need Pagination , and maybe some one also need Pagination.

[Example](http://materializecss.com/pagination.html)

**Comment by valnub** [comment]
For which component do you want pagination? Swiper already supports it.

**Comment by ZanderBrown** [comment]
I would say between tabs & swiper we already have this
