### ISSUE TITLE
Memory-issue on nested views

### ISSUE THREAD

**Issue by reecube** [nolimits4web/Framework7#1082]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: Master: 136a545929b37d63ab9409b01eb49a39985aa03f
* Platform and Target: Desktop Computer, Windows 10, Chrome 51.0

### What you did

1. I went to the demo-site: http://framework7.io/kitchen-sink-ios/
2. I scrolled down to 'Dynamically Generated Content' and clicked on it.
3. I clicked on 'one more page' to open a new view/page.
4. I clicked on 'one more page' to open a new view/page.
5. I clicked 'back' in the navigation bar.
6. I clicked 'back' in the navigation bar.
7. I clicked 'back' in the navigation bar.

### Expected Behavior
The main view with the same scroll position and memory-data as before.

### Actual Behavior
The main view, but the scroll position and memory-data are lost.

=> This only happens if the nested level is deeper than 1, if you only go to one sub-view and go back, the behavior is as expected.

**Comment by reecube** [comment]
This pull-request would fix the issue on the core: https://github.com/nolimits4web/Framework7/pull/898

**Comment by nolimits4web** [comment]
This is why domCache parameter for, it saves previous page without removing them
