### ISSUE TITLE
[Material] An option for circular progress indicator on preloader and indicator to be multi-color

### ISSUE THREAD

**Issue by SirusDoma** [nolimits4web/Framework7#1085]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v1.4.2
* Platform and Target: Cordova (Android)

### What you did
Trying Modal Preloader and Indicator.

### Expected Behavior
- The loading text on preloader should be placed inline / aside with the circular progress indicator when using with material theme.
- Circular progress indicator should be multi-color in material theme (like what you guys did on progressbar in material)

### Actual Behavior
- The loading text is placed above the circular progress indicator
- Circular progress indicator isn't colorful (or doesn't have option to enable / disable it)

**Comment by SirusDoma** [comment]
Not quite sure if the author care enough about this, but I able to hack the preloader color by overriding the animation keyframes:

```
@keyframes preloader-left-rotate {
    0%,
    100% { 
        border-left-color: #4285F4; 
        transform: rotate(130deg);
    }
    75% { 
        border-left-color: #1B9A59;
        border-top-color: #1B9A59;
    }
    50% { 
        border-left-color: #F7C223; 
        border-top-color: #F7C223; 
        transform: rotate(-5deg);
    }
    25% {
        border-left-color: #DE3E35;
        border-top-color: #DE3E35;
    }
} 

@keyframes preloader-right-rotate {
    0%,
    100% { 
        border-right-color: #4285F4; 
        transform: rotate(-130deg);
    }
    75% { 
        border-right-color: #1B9A59;
        border-top-color: #1B9A59;
    }
    50% { 
        border-right-color: #F7C223; 
        border-top-color: #F7C223; 
        transform: rotate(5deg);
    }
    25% {
        border-top-color: #DE3E35;
        border-right-color: #DE3E35;
    }
}
```

Well, it's better to add a new selector class (e.g: `.preloader.colorful`) and assign to a new animation rather than override the default animation directly, it will let you specify whether you want to the preloader to be colorful or not.

**Comment by valnub** [comment]
Hi, can you create a PR for this? https://help.github.com/articles/about-pull-requests/

**Comment by SirusDoma** [comment]
yes please! :D

**Comment by SirusDoma** [comment]
Oh sorry for previous message (I deleted it), I though you want to create pull request hahaha
I will try to create PR later
