### ISSUE TITLE
Sortable List not working on Chrome / Windows

### ISSUE THREAD

**Issue by remko** [nolimits4web/Framework7#1089]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Framework7 Version: 1.4.2
- Platform and Target: Chrome on Windows 8 (but reported on other windows versions as well)
### What you did

I tried dragging items from the sortable list on http://framework7.io/docs/sortable-list.html to reorder them.
### Expected Behavior

Items would be draggable
### Actual Behavior

Items do not move

I tried this on other browsers and platforms, and it works fine there.

**Comment by ZanderBrown** [comment]
With mouse or touch?

**Comment by remko** [comment]
I can only test it with mouse, but it has been reported with touch as well.

**Comment by ZanderBrown** [comment]
ok because touch & mouse are handled differently. any code you can share?

**Comment by remko** [comment]
I probably wasn't clear, but I meant to say that the example on http://framework7.io/docs/sortable-list.html exhibits the problem, so no need for custom code.

**Comment by ZanderBrown** [comment]
In Chrome 54.0.2810.2 Windows 8.1 x86 I can confirm that sortable lists our unresponsive to mouse input but do respond to touch

Internet Explorer 11.0.9600.18427 Windows 8.1 x86 is responsive to mouse but not touch in both desktop & metro modes

*I can confirm this bug*

[Based on sample usage](http://framework7.io/docs-demos/sortable.html)

**Comment by remko** [comment]
Why is the priority low on this one? This makes UIs that use listViews pretty much unusable on Windows. Is desktop not an important target for Framework7?

**Comment by remko** [comment]
Since the PR has been reverted, can this issue be re-opened?
