### ISSUE TITLE
Preloader Indicator

### ISSUE THREAD

**Issue by rohannagpal** [nolimits4web/Framework7#1090]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Framework7 Version: 136a545
- Platform and Target: iOS
### What you did

I'm using JS to trigger the preloading indicator. I'm using the method suggested in the documentation -- `myApp.showIndicator();`
### Expected Behavior

The preloader indicator should become visible in the center of the page.
### Actual Behavior

I only see the black box in the center of the screen. The preloader indicator shows up on Android.

**Comment by ZanderBrown** [comment]
do div's with the class `preloader` show the animation

**Comment by valnub** [comment]
Has this issue been resolved?

If yes, please close.

If not, please create a fiddle, so the issue can be reproduced -> http://www.jsfiddle.net

Please respond within 1 week, of this issue gets closed.

**Comment by valnub** [comment]
Closed due to no response

**Comment by ErroneousFatality** [comment]
I'd like you to reopen this issue since it was not resolved. 
The problem isn't in the browsers being used, but rather in that the preloader spinning circle animation won't be visible without using the material.colors.css file in your project, if you're using the material.css.
But when you use the ios.css it works without needing to use ios.colors.css, so that's an incosistency.

**Comment by ErroneousFatality** [comment]
The same happens with the preloader component.

The div.preloader spins in both components but has nothing visible inside it.

**Comment by valnub** [comment]
I think the colors file should always be used alongside other css and js ressources. Why would you not use it?

**Comment by ErroneousFatality** [comment]
It was never stated in the docs that it must be used, and it's just incosistent that it works on iOS without the colors css and doesn't do the same on material without the colors css.
Make it consistent or document the difference in the documentation.
