### ISSUE TITLE
parameter passing doubt

### ISSUE THREAD

**Issue by sdjoyson** [nolimits4web/Framework7#1091]
sir , How to i pass <a ???> tag append parameter to ajax url in framework7. i tried

 $$.ajax({type: 'GET',
url: "http://localhost/likes.php?id="+imgid+"&user="+uid,
 cache : false,
dataType: "JSON",
success:function(data){
var contact = JSON.parse(data);
  (how to add response to append likes id)
 }
});

<div id="likes">'+value['like_count']+'</div>

kindly send simple syntax for passing parameter using <a> tag

**Comment by GuillaumeBiton** [comment]
Don't know if I have well understand your request but you can do like this :

```

var staticPartOfUrl = "http://localhost/likes.php?id=" + imgid + "&user=" + uid;

var myOwnRequest = function (path, success, error) {
    return $$.ajax({
        url: staticPartOfUrl + path,
        success: success,
        error: error
    });
};

```
and then call this myOwnRequest function with the extra needed tags.

**Comment by chalchis** [comment]
only as a supplement

```
//valores
            var datosPost = {               
               'keyasigmat_tx'  : $$('#field_1').val(),//key de la asignacion
               'keyrubpadre_tx' : $$('#field_2').val(),//key rubro padre registrado          
               'proceso_tx'     : 'remover'//proceso originado
            };

            //enviar datos ajax       
            $$.ajax({
                url: "/controller/method",
                method: 'POST',
                data: datosPost, 
                dataType: 'json',
                success: function(json)
                {
.
.
.
.
.
........
```

**Comment by sdjoyson** [comment]
Thank you boss , as per your suggestion i solved this with below coding.
$$(page.container).find('.link1').on('click', function (e) {  
                                                    var imgid = $$(this).data('imgid');
                                                    var likeid = $$(this).data('likeid');
                                                      $$.ajax({
                                                      type :'GET',  
                                                      url: 'http://localhost/toon2/www/likes.php',
                                                      data: {id:imgid,user:window.localStorage.getItem('key')},
                                                      cache : false,
                                                      dataType: "JSON",
                                                      success:function(data){
                                                          var contact = JSON.parse(data);
                                                          alert(contact[0].likecnt);
                                                          $$("#"+likeid).html(contact[0].likecnt);
                                                      } 
                                                       });
                                                    });
