### ISSUE TITLE
Navigation not working within a popover

### ISSUE THREAD

**Issue by rohitchandel** [nolimits4web/Framework7#1092]
<!DOCTYPE html>
<html>
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    
    <title>My App</title>
    
    <link rel="stylesheet" href="./node_modules/framework7/dist/css/framework7.ios.min.css">
    
    <link rel="stylesheet" href="./node_modules/framework7/dist/css/framework7.ios.colors.min.css">
    
  </head>
  <body>
    <div class="views">
      <div class="view view-mainzz">
        <div class="navbar">
          <div data-page="index" class="navbar-inner">
            <div class="center sliding">Awesome App</div>
          </div>
          <div data-page="services" class="navbar-inner cached">
              <div class="left sliding"><a href="#" class="back link"> <i class="icon icon-back"></i><span>Back</span></a></div>
              <div class="center sliding">Services</div>
            </div>
        </div>

        <div class="pages navbar-through toolbar-through">
          <div data-page="index" class="page">
            <div class="page-content">
              <p>Page content goes here</p>
              <a href="#"  class="open-popover" data-popover='.test-pop'>About app</a>
              <a href="#services" class="item-link">
                  <div class="item-content">
                    <div class="item-inner">
                      <div class="item-title">Service</div>
                    </div>
                  </div></a>
            </div>
          </div>
          <div data-page="services" class="page cached">
          </div>
        </div>
      </div>

    </div>
    <div class="popover test-pop">
      <div class="views">
      <div class="view view-pop" style="height:400px">
        <div class="navbar">
          <div data-page="index" class="navbar-inner">
            <div class="center sliding">Awesome App</div>
          </div>
          <div data-page="services" class="navbar-inner cached">
              <div class="left sliding"><a href="#" class="back link"> <i class="icon icon-back"></i><span>Back</span></a></div>
              <div class="center sliding">About Us</div>
            </div>
        </div>

        <div class="pages navbar-through toolbar-through">
          <div data-page="index" class="page">
            <div class="page-content">
              <p>Page content goes here</p>
              <a href="#services" class="item-link">
                  <div class="item-content">
                    <div class="item-inner">
                      <div class="item-title">Service</div>
                    </div>
                  </div></a>
            </div>
          </div>
          <div data-page="services" class="page cached">
          </div>
        </div>
      </div>
    </div>
    </div>
    <script type="text/javascript" src="./node_modules/framework7/dist/js/framework7.min.js"></script>
    <script type="text/javascript" src="app.js"></script>
  </body>
</html>

js

var f7 = new Framework7();
f7.addView('.view-mainzz',{dynamicNavbar: true,domCache: true});
f7.addView('.view-pop',{dynamicNavbar: true,domCache: true});
console.log(f7)

Im trying to navigate to different pages within a popover . Code above is not working. Is it possible to have views within a popover ?

**Comment by GuillaumeBiton** [comment]
Hi,

Have a look at [this reply in the forum](http://forum.framework7.io/#!/questions:loading-a-url-inside-popove) from Vladimir.

He gives the structure to do what you are expected.

Regards
