### ISSUE TITLE
Scrolling multiple lists on tabs at once

### ISSUE THREAD

**Issue by ilyagru** [nolimits4web/Framework7#1095]
Hello.
I have a view in the app. Inside the view there are 2 pages. On the first page there are three tabs with the lists of users. When I scroll the list on the first tab it  automatically scrolls on the second and third tabs.
How can I fix this?

**Comment by ilyagru** [comment]
I fixed it with adding page-content class to each tab. So there are three tabs with its own page-content class in one page.
But now how to make bars hide on scroll for all the page-contents separately? It works only for the first.

**Comment by ZanderBrown** [comment]
are you sure you are using tabs correctly? could we see some code?

**Comment by ilyagru** [comment]
This is my view: 
[plnkr](http://plnkr.co/edit/cdz77OKCuzgzO5K1THAj?p=preview)
