### ISSUE TITLE
scrollTo() does not work

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7#1096]
Following code does fire the event, but always logs "0".
Latest Chrome browser, Windows 7.

`Hey, 

```
$$('.page-content').on('scroll', function(e) {
        console.info($$('.page-content').scrollTop());
    });
````

**Comment by scriptPilot** [comment]
PS: $$('.page-content').scrollTop(100) works fine!

**Comment by valnub** [comment]
When do you call this code?

Also, can you create a fiddle please so it's easier to debug? Thanks :-) http://www.jsfiddle.net

**Comment by nolimits4web** [comment]
@scriptPilot this is because you may have more than one ".page-content" in the DOM. Make you selector more specific like `$$('.page[data-page="some-page"] .page-content').on('scroll', ...`

**Comment by scriptPilot** [comment]
Thank you, that works fine!
