### ISSUE TITLE
Position of dropdown is not correct if page-content is in center

### ISSUE THREAD

**Issue by Trion129** [nolimits4web/Framework7#1098]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.4.2
* Platform and Target: PC

### What you did
I have a page-content that is aligned in center of screen.
When I used Autocomplete drop-down, the drop-down appeared with a very high left offset that looked bad. On mobile the drop-down is properly aligned as the page-content is taking full space of screen.

### Expected Behavior
The drop-down appears directly below the input even if page-content is not taking complete screen

### Actual Behavior
The drop-down appears too much to the right instead of displaying directly below the input

I have implemented a fix, can I do a pull request for it?

Before:

![error](https://cloud.githubusercontent.com/assets/8445249/17817489/63e2e204-665c-11e6-9db9-cb3b9271c5a3.JPG)

After the fix:

![error1](https://cloud.githubusercontent.com/assets/8445249/17817503/7e60ce70-665c-11e6-8f76-5691cc888a54.JPG)

**Comment by chanty6680** [comment]
How did you fixed this? I have a similar problem

**Comment by Trion129** [comment]
@chanty6680 here is the change :-)
https://github.com/Trion129/Framework7/blob/4a6d6086a0324cde439172ee9190aacbab9855d6/src/js/autocomplete.js
