### ISSUE TITLE
Virtual keyboard issue on Android Chrome...

### ISSUE THREAD

**Issue by cnjsstong2** [nolimits4web/Framework7#110]
This issue happens only on mobile Chrome browser (mostly on Android I think...). The page was like this:
![screenshot_2014-07-08-14-54-36](https://cloud.githubusercontent.com/assets/4534745/3515053/d7923534-06d1-11e4-8881-4c757a8dc5b2.png)

Then, if I click on the lower "E-mail" input, a white area appears just above the virtual keyboard...
![screenshot_2014-07-08-14-54-42](https://cloud.githubusercontent.com/assets/4534745/3515052/d791674e-06d1-11e4-8a98-c5af00da6676.png)

This happens only if the clicked input was on the lower half of the screen. 
As this is not a normal behavior for an ordinary html input tag, what do you think may cause this problem?

**Comment by nolimits4web** [comment]
Closing it for now
