### ISSUE TITLE
Ugly background when scrolling in iOS

### ISSUE THREAD

**Issue by nilburcion** [nolimits4web/Framework7#1100]
In iOS when the app is added to iOS homescreen (or even in Safari) it is ugly/unnatural when it shows that gray background when and it moves all the page when scrolling. I found an answer by Ganjus in StackOverflow by that fixes that. What do you think?

Here's the link: http://stackoverflow.com/a/26853900/5959483

And here a picture of the issue:
![unnamed](https://cloud.githubusercontent.com/assets/11617562/17909230/d617700e-6983-11e6-9ee6-669da2b7aa08.jpg)

**Comment by valnub** [comment]
I think this would completely disable the rubber band effect which is not natural to iOS as well. Also, it might break pull-to-refresh feature.

**Comment by J05HI** [comment]
Yeah valnub it's an ios related thing with the rubber overscrolling. 
This ticket can be closed.
