### ISSUE TITLE
Adding Tab Bar items dynamically onBeforeInit - Cannot read property 'offsetWidth'

### ISSUE THREAD

**Issue by matthewbecker1990** [nolimits4web/Framework7#1102]
This is a:
* [x] bug

* Framework7 Version: Latest
* Platform and Target: CORDOVA - Android

### What you did
I am trying to Dynamically add Items to a Scrollable Tab Bar, however, even when I am calling my import onBeforeInit, framework7.js is throwing an error due to an empty .tabbar div.

```
$$(document).on('pageBeforeInit', '.page[data-page="calendar"]', function (e) {
	var cal_api = "https://.................";
  
  	$.getJSON(cal_api, function (data) {
	  	var cal = $.parseJSON(JSON.stringify(data));		
		$.each(data, function(cal_count, element) {
			if (cal_count){
				$( "<a>" ).attr( "href", "#"+element.id ).attr( "data-id", element.id ).addClass("tab-link").html(element.calendar_name).prependTo("#calendars");
				$( "#calendar-tabs" ).append( '<div class="tab" id="'+element.id+'"><div class="content-block notifications-all">'+element.calendar_name+'</div></div>');
			} else {
				$( "<a>" ).attr( "href", "#"+element.id ).attr( "data-id", element.id ).addClass("tab-link active").html(element.calendar_name).prependTo("#calendars");
				$( "#calendar-tabs" ).append( '<div class="tab active" id="'+element.id+'"><div class="content-block notifications-all">'+element.calendar_name+'</div></div>');
			}
                });
         });
});  
```

Results in - Uncaught TypeError: Cannot read property 'offsetWidth' of undefined on line 6540 of framework7.js. It seems to be related to the initialization of tab-link-highlight.

I believe the function starting at line 6532 may be getting called prior to page init.

**Comment by valnub** [comment]
Sorry for the late reply. Can you create a fiddle so we can look into the issue and debug? Thanks :) http://www.jsfiddle.net

**Comment by valnub** [comment]
Ps: If you try to access the DOM on `pageBeforeInit`, the page elements aren't ready yet. Maybe that's the reason for the problem. Try `pageInit` event instead.
