### ISSUE TITLE
"layout-white" is not applied when using material desing

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Framework7#1103]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Framework7 1.4.2.
- Platform and Target: "framework7.material.css" and "framework7.material.colors.css".
### What you did

I am using material-design.
### Expected Behavior

class="layout-white" should work in material, the same as with ios-them.
### Actual Behavior

Using the material desing and applying <body class="layout-white"> does not work. It only works with ios-theme. When using "theme-withe" with material-desing, then only statusbar and the like is white, hover the "font" and the like will remain white.

**Comment by nimo23** [comment]
Acutally, there is not ".layout-white"-class within framework7.material.colors.css".

**Comment by Tarekajaj** [comment]
The default layout in material is white

**Comment by valnub** [comment]
This is a bug, for white Material theme all fonts and icons' colors are white but should have darker color. This can be observed here: https://framework7.io/docs/color-themes.html

**Comment by nolimits4web** [comment]
Don't mess layout and theme, There is no layout-white in Material theme as it is white by default. As for white theme, use additional class to set text/icon color:
```
<div class="navbar theme-white color-pink">
  ...
    <i class="icon icon-back color-pink"></i>
```

**Comment by valnub** [comment]
@nolimits4web White theme should be removed from docs then as currently it looks like it's a valid option: https://framework7.io/docs/color-themes.html#material-theme-colors
