### ISSUE TITLE
new flex-layout-module 

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Framework7#1104]
Please add a small layout module by using flex-layout. For example, "l-flex-hor", "l-flex-vert". Actually, the "F7-layout-module" ("layout-grid") uses "calc-prop". 

Would be nice to add something like "layout-flex"-module in F7. 

F7 uses already a much of flex-props spread all over the F7-stylesheet. These props can be isolated within a new module "layout-flex" which can also be used internally by F7 for layouting and externally be the user.

**Comment by valnub** [comment]
You're very welcome to create a PR :-)

**Comment by nolimits4web** [comment]
I didn't get the issue. What should be added, what is `flex-layout`? Layout grid in F7 already uses flex

**Comment by valnub** [comment]
Closed due to no response after 8 days
