### ISSUE TITLE
Will manifest.php work?

### ISSUE THREAD

**Issue by ilyagru** [nolimits4web/Framework7#1105]
Hello.
If I use manifest.php in such way like in Weather7 app, will it work properly wnen I will build the app through PhoneGap or Cordova?
Or it is better to use a plain manifest.cache file without PHP?

It logs in the console an error: 
Creating Application Cache with manifest http://127.0.0.1:8000/manifest.php
127.0.0.1/:1 Application Cache Checking event
127.0.0.1/:1 Application Cache Error event: Failed to parse manifest http://127.0.0.1:8000/manifest.php

**Comment by ZanderBrown** [comment]
PHP won't run on device so if you hosting the AppCache locally it will fail
