### ISSUE TITLE
[Question] How to bind context updated to page

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7#1106]
Hey! I use Template7 pages and want to update the context. But if I refresh the page, the scroll position is initial the top, focus ist not as before etc. Is there any possiblity to update a specific part of a context without refresh? Regards and many thanks for this great piece of code! :-)

**Comment by valnub** [comment]
Did you try `mainView.router.load()`?

```
mainView.router.load({
    url: 'yourHtml.html',
    context: yourContext
})
```

See https://framework7.io/docs/template7-pages.html#pass-custom-context

**Comment by scriptPilot** [comment]
Yes I did. But as I can see, the whole page is refreshed than (with lost of form inputs and reset of scroll position and focus). So is there any way just to update some containers (defined with CSS selector) on the page with new context?

**Comment by valnub** [comment]
Did you see this? https://muut.com/framework7#!/framework7/getting-started:template7-context-dynamic-u

**Comment by scriptPilot** [comment]
Mhm. in that article I understand the question is how to update the last page. But that is not a problem I have ... my objective is to update just a specific part of a template with new context :-)

**Comment by valnub** [comment]
Vladi's answer in that post updates only the context given with parameter reload=false:

```
mainView.router.load({
    reload: false,
    reloadPrevious: true, /* You can also set this to false */
    template: Template7.templates.whys,
    context: Template7.data.causes.whys[1]
});
```

**Comment by scriptPilot** [comment]
Sorry, I was in vacation, now I come back to that issue.

I took the /dist and add in index.html:

    <script type="text/template7" id="myTemplate">
        <div class="page" data-page="myTemplatePage">
            <div class="page-content">
                <p>You can contact me:</p>
                <p>By phone: {{tel}}</p>
                <p>By email: {{email}}</p>
                <input type="text" />
            </div>
        </div>
    </script>  

Then I took the my-app.js and add:
```
mainView.loadContent(Template7.templates.myTemplate({tel: '123', email:'q@b.de'}));

setTimeout(function() {
  console.log('update');
  mainView.router.load({
      reload: false,
      reloadPrevious: false, /* You can also set this to false */
      animatePages: false,
      template: Template7.templates.myTemplate,
      context: {tel: '456'}
  });
}, 2000);
```
