### ISSUE TITLE
ajax page load failed in android webview: "Uncaught TypeError: Cannot read property 'f7form-payBack' of null"

### ISSUE THREAD

**Issue by imac8t** [nolimits4web/Framework7#1108]
webview log：
08-29 16:02:00.560: Iromium(25500): [INFO:CONSOLE(19)] "Uncaught TypeError: Cannot read property 'f7form-payBack' of null", source: http://mis.xlhealth.cn/backend/web/static/js/framework7.min.js (19)

payBack is the data-page

it is ok in ios and android system browser but failed in android webview

**Comment by imac8t** [comment]
i make the class "store-data" and form id out,it works fine!!!!

**Comment by ZanderBrown** [comment]
So the issue is resolved?

**Comment by imac8t** [comment]
@ZanderBrown no i think this is a bug?

**Comment by valnub** [comment]
Hi imac8t
- What is Iromium?
- What Android version are you on?
- Do you use an emulator or a real device?
- In which line of the **_unminified version_** of framework7.js does the error occur?

**Comment by imac8t** [comment]
@valnub i get this bug today again
"Uncaught TypeError: Cannot read property 'f7form-xxx' of null", source: http://mis.xlhealth.cn/backend/web/static/js/framework7.min.js (19) again！！！
 next time in ipad
 this time is android ，
all is real device 
 framework7.min.js (19)col！

**Comment by valnub** [comment]
@imac8t Did you even read my previous comment?

**Comment by ZanderBrown** [comment]
@valnub probably not

**Comment by valnub** [comment]
Closed due to no proper response
