### ISSUE TITLE
Wrong selected value in calendar

### ISSUE THREAD

**Issue by lulldev** [nolimits4web/Framework7#1109]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: CURRENT AND MAYBE OTHER
* Platform and Target: ALL

### What you did
In offical documentation https://framework7.io/docs/calendar.html when you open demo and see in google dev tools (elements) 
Choosen date for is example was 2016-08-29 - but in dev tools i was see this:

`<div data-year="2016" data-month="7" data-day="29" class="picker-calendar-day picker-calendar-day-today picker-calendar-day-selected" data-date="2016-7-29"><span class="">29</span></div>`

### Expected Behavior
From above
`
<div data-year="2016" data-month="8" data-day="29" class="picker-calendar-day picker-calendar-day-today picker-calendar-day-selected" data-date="2016-8-29"><span class="">29</span></div>`

### Actual Behavior
Selected value is wrong. 

------
Please test it!! Thanks

**Comment by Tarekajaj** [comment]
Months start counting from zero.

**Comment by jmarceli** [comment]
Is there any particular reason why month counting is zero based while other values are counted from one? It is quite misleading.
If it's not going to be normalized I would suggest adding some info to the documentation.

**Comment by ZanderBrown** [comment]
It is 'normalized' computers almost always start months at 0 just as they do array indexes

**Comment by jmarceli** [comment]
I know about arrays :) I mean that months numbering almost always starts with 1 e.g. Ruby `Date.today.month` returns `1` (which happens to by my backend language) or PHP `date('n')`.

Anyway, I find out that this "inconsistency" is related to the Javascript `getMonth()` implementation (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth), so it probably has to be that way.
