### ISSUE TITLE
Navigation Bar has gone

### ISSUE THREAD

**Issue by kukat** [nolimits4web/Framework7#111]
First, Thanks for the awesome work!

I have this problem when display web page in UIWebView.

This is how it looks when its normal:
![ios simulator screen shot 9 jul 2014 6 01 52 pm](https://cloud.githubusercontent.com/assets/107503/3522766/c8d0c98c-0750-11e4-86c8-17a53c5b9add.png)

But when keyboard shows, the entire webpage is pushed up, and the navigation bar has gone out of the screen. see image below

![ios simulator screen shot 9 jul 2014 6 01 22 pm](https://cloud.githubusercontent.com/assets/107503/3522757/c03e7080-0750-11e4-8f2e-669448be52dc.png)

Is that a bug or just me?

**Comment by nolimits4web** [comment]
Closing it for now
