### ISSUE TITLE
Page not changing

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#1112]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.4.2
* Platform and Target: Browser for now.

### What you did
Created a base app using doneJS and integrating Framework7

### Expected Behavior
When you click the about us link to switch page

### Actual Behavior
Nothing happens.

### Notes:
This is the repository with the problem https://github.com/MarcGodard/donejs-appframework

Framework7 is loaded because the right and left panel work fine and tracing the javascript when you click the about link traces just fine, however, I don't know if it is doing what it should be doing. Also created the exact same thing without doneJS (just html and f7) and the link works, but tracing the javascript was the same (however when tracing the javascript the page didn't open). So I assume there is some kind of timing thing that prevents it from working when you trace the JS. However, this doesn't explain why it doesn't work in my implementation.

If someone has experience with the javascript and knows how to trace it to see if it is calling the right stuff to open the page, that would be great.

**Comment by ZanderBrown** [comment]
If you set chrome to log XMLHttpRequests you should see it fetching your second page

**Comment by MarcGodard** [comment]
@ZanderBrown I am using cached pages, so I will not. However, that said, when you don't use cached pages, it doesn't show up.

**Comment by ZanderBrown** [comment]
it will (obviously not for cached) if you change the DevTools settings appropriately

**Comment by MarcGodard** [comment]
I am saying it doesn't show up even without cache pages. This is the bug I am reporting. I am assuming something is interrupting it or something with the libraries I am using. This is why I asked for someone who is familiar with tracing it. So they can download my add and trace it.

**Comment by ZanderBrown** [comment]
i have attempted to clone but you have so many dependencies my system could not cope.

**Comment by valnub** [comment]
@MarcGodard Can you strip out the relevant part of your code and create a really simple fiddle to replicate the problem, so it's much easier to look into this issue: http://www.jsfiddle.net - Thanks!

**Comment by MarcGodard** [comment]
@ZanderBrown and @valnub The largest dependencies (doneJS -- combo of a bunch of stuff) is what is interfering. If I remove that it isn't the same app, nor does the problem happen.

**Comment by valnub** [comment]
Sounds more like this is a 3rd party lib issue..

**Comment by ZanderBrown** [comment]
what does 'DoneJS' do? how does it help?

**Comment by MarcGodard** [comment]
DoneJS is a framework with a generator and allows ES6 and module design. And yes it most likely  a 3rd party lib issue, but a doneJS/framework 7 combo would be sick!

**Comment by ZanderBrown** [comment]
err why not just use TypeScript & Gulp?

**Comment by MarcGodard** [comment]
@ZanderBrown Because DoneJS and NPM is better.

**Comment by ZanderBrown** [comment]
err you haven't really explained why and if you knew about TS + Gulp you would know that they are two very popular **node** modules. Gulp being used in f7 itself and TS by Google to make the likes of Angular.

**Comment by valnub** [comment]
Closed since this is not a F7 bug.
@MarcGodard If you seek for help with your doneJS+F7 problem I suggest to ask on F7 forums (http://forum.framework7.io) or www.stackoverflow.com.
