### ISSUE TITLE
Android floating labels not working in popup

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#1113]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.4.2
* Platform and Target: Browser emulating android and Android using cordova

### What you did
I put forms with floating labels in a popup.

### Expected Behavior
Floating labels to be floating

### Actual Behavior
Didn't float and looked like iOS forms.

I know android doesn't have the same popup, but I am trying to make one app that works in both. So if there is a command or something to process the form to add the floating labels that would great.

**Comment by MarcGodard** [comment]
f7.initPageMaterialInputs($('.popup-sign-up'));

That fixed it :)

**Comment by admiremasaga** [comment]
Am having same issue where do i put that code to solve this problem
