### ISSUE TITLE
Open picker manually by clicking on html element

### ISSUE THREAD

**Issue by bramis** [nolimits4web/Framework7#1114]
Hello,

First, I would like to thank you a lot for "Framework7".

During my development, I found a kind of issue about "Picker" component (maybe it's not).

Indeed , I tried to open a picker manually, with javascript (by using method myPicker.open() ), by clicking on html element. However, I can't do that except if I set the "closeByOutsideClick" option to "false" in the configuration of the picker.

Here a simple example of what I wanna do (I took one of the documentation and I added a scenario close to my case):

## HTML code:
<pre>
&lt;div class=&quot;views&quot;&gt;<br/>        &lt;div class=&quot;view view-main&quot;&gt;<br/>            &lt;div class=&quot;page&quot; data-page=&quot;picker_page&quot;&gt;<br/>                &lt;div class=&quot;page-content &quot;&gt;<br/>                    &lt;div class=&quot;content-block-title&quot;&gt;Picker with single value&lt;/div&gt;<br/>                    &lt;div class=&quot;list-block&quot;&gt;<br/>                        &lt;ul&gt;<br/>                            &lt;li&gt;<br/>                                &lt;input type=&quot;text&quot; placeholder=&quot;Your iOS device&quot; readonly id=&quot;my-picker&quot; /&gt;<br/>                                &lt;button id=&quot;open_picker_manually&quot;&gt;Click !&lt;/button&gt;<br/>                            &lt;/li&gt;<br/>                        &lt;/ul&gt;<br/>                    &lt;/div&gt; <br/>                &lt;/div&gt;<br/>            &lt;/div&gt;<br/>        &lt;/div&gt;<br/>    &lt;/div&gt;
</pre>

## Javascript code:
<pre>
var myPicker = myApp.picker({
            input: '#my-picker',
            cols: [
                {
                    textAlign: 'center',
                    values: ['iPhone 4', 'iPhone 4S', 'iPhone 5', 'iPhone 5S', 'iPhone 6', 'iPhone 6 Plus', 'iPad 2', 'iPad Retina', 'iPad Air', 'iPad mini', 'iPad mini 2', 'iPad mini 3']
                }
            ]
        });
        $("#open_picker_manually").on("click", function () {
            console.log("manual opening clicked");
            myPicker.open();
        });
</pre>

### Explanation

As you can see, I initialize my picker and I configure a click event listener on my button.
But, if you test that code and open the javascript console of your browser or debugger, when you click on the button, just the message is display and the picker is not open (visually).

I explored the JS code of Framework7, and I found why that happened. Because of this line :

`if (!p.inline && p.params.closeByOutsideClick) $('html').on('click', closeOnHTMLClick);`

Because I clicked in the "html", outside of the "input" setted, that open and instantly close my picker.

Actually, the only solution to solve that is to put the "closeByOutsideClick" option to "false" when you initialize the picker. But, in my case I wanna keep this behaviour to "true" and be able to open picker manually by clicking somewhere, not on input, in some cases.

### The solution could be
Add an option in the picker, with a list of class and/or id to exclude in the line above and maybe elsewhere. Currently, no one else solution comes.

I'm pretty sure you will have better solution than me :smiley: 

This is just a suggestion, about an issue I found in my case, maybe you already knew about that and decide to don't manage this case.

**Comment by valnub** [comment]
Hi, just use `event.stopPropagation();` on that input button:

```
$$("#open_picker_manually").on("click", function(event) {
  event.stopPropagation();
  console.log("manual opening clicked");
  myPicker.open();
});
```

Fiddle: https://jsfiddle.net/valmar/Lh2a3102/

Does this fix the issue for you?

**Comment by bramis** [comment]
Hi :)

You're right, it works ! The issue is fixed :) 

That seems so obvious and logic ! Thank you so much and sorry for the post :)

**Comment by valnub** [comment]
No problem :)

**Comment by desarrollotamed** [comment]
Hi, one question please, in a page of Framework using component, Can I use event onclick in tag html, I explain me:
<button onclick='nameFunction(parameter)'>Pass Parameter</button>
I need pass a parameter a function when click button. I have many tag button with itself id. Thank

**Comment by LarsVoith** [comment]
For questions try the community forum. [http://forum.framework7.io](url)
But to answer your question in v2 check out the kitchen sink page-loader-component.html
You should be able to use /page/?id=5&foo=bar 
[https://framework7.io/docs/view.html#router-api-methods-properties](url)
But I think @click="functionName(pass something here)" would not work.
