### ISSUE TITLE
Virtual list - .trim is not a function

### ISSUE THREAD

**Issue by hessius** [nolimits4web/Framework7#1116]
This is a:
- [x] bug
- Framework7 Version: 1.42.
- Platform and Target: iOS Cordova + macOS Safari.
### What you did

Trying to test out a search function, thought I'd use a virtual list + searchbar. 

I've only used the basic example code and not (yet) customised any parameters to generate the virtual list:

```
var myList = myApp.virtualList('.list-block', {
    items: [1,2,3,4],
    height: 44
}); 

```
### Expected Behaviour

The virtual list is populated
### Actual Behaviour

If script is called before navigation has finished, navigation is aborted. If called after navigation is finished the list is populated with blank items. Either way console gives an error:

> TypeError: o[w].trim is not a function. (In 'o[w].trim()', 'o[w].trim' is undefined)

**Comment by dotgodly** [comment]
I can replicate this. Safari and Chrome.

**Comment by valnub** [comment]
Can you create a quick fiddle? Then it's easier to dig into the issue: http://www.jsfiddle.net

**Comment by valnub** [comment]
Closed due to no response

**Comment by peterel** [comment]
I get this as well. 

I use the example from framwork7, to what I can see, exact meassures.

JS
`	var myList = myApp.virtualList('.list-block.virtual-list', {
	    items: [1,2,3,4],
	    height: 44
	}); 
`
HTML
`	    <div class="list-block virtual-list">
	      
	    </div>
`

The error message from console is:
framework7.js:5946 Uncaught TypeError: o[w].trim is not a function
    at g.r.render (framework7.js:5946)
    at g.r.init (framework7.js:6040)
    at new g (framework7.js:6205)
    at window.Framework7.i.virtualList (framework7.js:6214)
    at r.<anonymous> (get_new_position.js:33)
    at r.n.emit (socket.io.min.js:1)
    at r.onevent (socket.io.min.js:1)
    at r.onpacket (socket.io.min.js:1)
    at n.<anonymous> (socket.io.min.js:1)
    at n.emit (socket.io.min.js:1)

Any hints is appreciated.

**Comment by tobya** [comment]
@peterel  can you create  a jsfiddle that shows it happening

**Comment by peterel** [comment]
@tobya Thanks. My suspicion of this being related to socket.io was wrong. I could replicate the issue in a jsfiddle using the sample from the framework7 docs. See https://jsfiddle.net/21rfpzze/ and open the console, you'll see an error "TypeError: items[i].trim is not a function" which is very similar to what I wrote that I got in my earlier post.

**Comment by peterel** [comment]
@tobya Any ideas where this may come from?

**Comment by ZanderBrown** [comment]
A working (broken 😄) fiddle https://jsfiddle.net/21rfpzze/1/

**Comment by peterel** [comment]
@ZanderBrown It is working (broken) :) If you open a console youll see "TypeError: items[i].trim is not a function" in both Chrome and FF (on Mac at least).

**Comment by tinwhisker** [comment]
@ZanderBrown, Sorry, I saved against your fiddle!

However, revision #4 shows a working example:
https://jsfiddle.net/21rfpzze/4/

The issue you found is that the Virtual List expects an object that can be parsed as an html object (that would have a style property if invoked, like a string containing a div "<div>blah</div>"), not base objects (like plain strings "hello" or integers 123).

The modified fiddle shows a quick'n'dirty use of a template.

**Comment by ZanderBrown** [comment]
@tinwhisker it's not my issue! This issue belongs to @hessius & @peterel 

However thanks for diagnosing the issue.

So @nolimits4web it would appear the behaviour of `.virtualList` is different to different to that shown in the docs (http://framework7.io/docs/virtual-list.html) specifically:

> ## Initialize Virtual List
> Now, when we have list's HTML, we need to initialize it. We need to use required App method:
> ```javascript
> myApp.virtualList(listBlockContainer, parameters) - initialize virtual list with parameters
> * listBlockContainer - HTMLElement or string (with CSS Selector) of "list-block" HTML element. Required.
> * parameters - object - object with virtual list parameters. Required.
> ```
> Method returns initialized Virtual List instance
> For example:
> ```javascript
> var myList = app.virtualList('.list-block', {
>     items: [1,2,3,4],
>     height: 44
> });
> ```
> > Note that Virtual List container (listBlockContainer) should be in DOM on a moment of initialization. 
> > So if you use virtual list not on home page, you need to initialize it within page:init (or page:beforeinit) event

So as far as i can see we have two options:
* Update the docs
* Update the default behaviour

And to finally solve @peterel & @hessius's original issue:
```javascript
var myList = myApp.virtualList('.list-block', {
    items: [1, 2, 3, 4],
    template: '<li class="item-content"><div class="item-inner"><div class="item-title">{{this}}</div></div></li>'
});
```
Allows use of the expected behaviour.

Perhaps `<li class="item-content"><div class="item-inner"><div class="item-title">{{this}}</div></div></li>` should be the default value of `template`?

**Comment by peterel** [comment]
Thanks :)
