### ISSUE TITLE
App Layout sample HTML in docs for Material

### ISSUE THREAD

**Issue by nickyspag** [nolimits4web/Framework7#1117]
In the App Layout sample html for Material in the documentation here:
https://framework7.io/docs/app-layout.html

I think the bottom toolbar needs `toolbar-bottom` class added?

`<div class="toolbar">`

I think it needs to change to:

`<div class="toolbar toolbar-bottom">`

**Comment by valnub** [comment]
Yes, I think you're right and should be fixed in docs @nolimits4web

**Comment by nolimits4web** [comment]
No, everything is correct in documentation. Toolbar in material theme is on the top (below navbar) by default

**Comment by DareDevil73** [comment]
The documentation is wrong.

**Comment by ZanderBrown** [comment]
Explain

**Comment by DareDevil73** [comment]
Till now i found these two changes to do:

```
<div class="pages navbar-fixed">
<div class="toolbar toolbar-bottom">
```
