### ISSUE TITLE
plan to create f7 ui component for vue or react?

### ISSUE THREAD

**Issue by yezongyang** [nolimits4web/Framework7#1119]
Framework7 is so perfect and i wanna  create app with mvvm framework(vue.js, react.js) with integrated Framework7 ui component, so do you have plan to do?

**Comment by ZanderBrown** [comment]
Ok would be good if this issue had a body but still having something like this or Polymer bindings would be useful

**Comment by inoas** [comment]
I can really see the point for ReactJS, however as long as there is no real contributor team it is going to be hard.
