### ISSUE TITLE
Implement Lazy loading of images for the media lists

### ISSUE THREAD

**Issue by gpetrov** [nolimits4web/Framework7#112]
It will be really nice if we can have some lazy loading mechanism for loading the images in the media lists only when they become visible on scroll.

Something like:
https://github.com/luis-almeida/unveil

This needs a specific Framework7 implementation as onscroll does not work well on iOS devices (it is only fired at the end) and a touchmove event should be used

This will make the media lists much faster and responsive. As currently when they are pretty large, like 100+ items they are initially very slow because all the images needs to be loaded.

**Comment by casper123** [comment]
Why doesn't lazy load plugin work with temaplte files?
