### ISSUE TITLE
hasClass does not work as expected

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Framework7#1124]
This is a (multiple allowed):
* [x] bug
* [x] feature-discussion (RFC)

I want to test if any (at least one) element in my list has the class .bingo.
I have a 5 li-tags and 1 tag is associated with class .bingo:

`var containBingo = $$('#mylist li').hasClass('bingo');`

this will always return "false", even one tag in my list is associated with class ".bingo".

I have to do this to get "containBingo" to "true"

```
	$$('#app_menu li').each(function() {
        if ($$(this).hasClass('bingo')) {
            console.log('BINGO');
            containBingo = true;
        }
        });
```

However, the f7 docs says this about hasClass():

Determine whether **any of the matched elements** are assigned the given class.

So according to the docs it must return true, because there is one element with class .bingo.

Is this a bug?

**Comment by ZanderBrown** [comment]
`this` will be the callback. use `value`
```
$$('#app_menu li').each(function(index, value) {
        if ($$(value).hasClass('bingo')) {
            console.log('BINGO');
            containBingo = true;
        }
});
```

**Comment by virtual-vicky** [comment]
Hey,

I don't think it's a bug!!
Though that totally depend upon your context of class "Bingo"..😁

**Comment by ZanderBrown** [comment]
@virtual-vicky fairly sure it's operator error

**Comment by valnub** [comment]
@nimo23 Can you post your HTML or even better create a fiddle to reproduce the problem? http://www.jsfiddle.net

As ZanderBrown's already said it's most likely a minor error in your selector declaration.

`.hasClass()` works properly the way described in the docs.

**Comment by nimo23** [comment]
hasClass only looks for "one" element and not for "all elements". 

I guess, that was intended. I have solved that with this:

`if( !document.querySelector('#mylist li.bingo') )`

f7-hasClass is the actually the same as document.classList.hasClass(). So I guess, it s okay.
