### ISSUE TITLE
ios style in material theme sidebar-left? bug?

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Framework7#1125]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.4.2.

### What you did
I included js and css-files for f-7 material (without ios-style!) in my html.
I did activate material in my app:

```
var views = new Framework7({
	init : false,
	material : true
```
Everything is okay. However, my sidebar left will be rendered with ios-style. I did not include ios-themes in my html, only material.css.

When looking in the kitchen sink, then sidebar left will be rendered in material style.

### Expected Behavior
My sidebar left should be rendered in material style. 

### Actual Behavior
Actually, my sidebar left is rendered in ios style. I did not include ios-themes.

What is wrong?

**Comment by ZanderBrown** [comment]
You haven't shared much code that's what's wrong

**Comment by nimo23** [comment]
Sorry, I just figured it out that it was my fault.
I  have to assign "panel-left panel-cover" instead of "panel-left panel-reveal". 
Now it works.
