### ISSUE TITLE
option for "swipeBack" also for material theme

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Framework7#1126]
This is a (multiple allowed):
* [] bug
* [] enhancement
* [x] feature-discussion (RFC)

Please provide the option to use "swipeBack" also for material theme. It s a really good feature in ios-theme which can enhance the material theme also.

Thanks.

**Comment by ZanderBrown** [comment]
but it's not material so no

**Comment by valnub** [comment]
ZanderBrown's right. It's not a Material feature.

**Comment by nimo23** [comment]
Yes, it s not a common material feature, however, it s a good feature. f7 has already all the "Swipe back"-Features built in". Actually it is so: "If you want swipe in, then you have to choose ios-theme". This is a little destrictive.
