### ISSUE TITLE
onSlideChangeEnd only fired occasionally in swiper

### ISSUE THREAD

**Issue by jvence** [nolimits4web/Framework7#1127]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 1.4.2
* Platform and Target: Cordova/Chrome

I've created a coverflow slider as follows:

` var pinSwiper = myApp.swiper('.swiper-pin', {
                effect: 'coverflow',
                coverflow: {
                    rotate: 0,
                    stretch: 20,
                    depth: 5,
                    modifier: 1,
                    slideShadows: true
                },
                onSlideChangeEnd: function () {
                    console.log('jsUpdatePinsSwiper:Slide change END: ' + pinSwiper.activeIndex);
                }
            });`

and noticed that onSlideChangeEnd is only called 1 in 10 times perhaps regardless of how fast we are swiping. This occurs both in Chrome and in IOS/Cordova app. 

Any idea on how to resolve this?

**Comment by jvence** [comment]
Figured out that if I swipe and remove my finger fast, then the function is called but if I swipe slow and over a longer distance and keep my finger for a while, then the function is never called.

**Comment by valnub** [comment]
Can you open a fiddle to show this issue? http://jsfiddle.net

**Comment by valnub** [comment]
Closed due to no reaction
