### ISSUE TITLE
searchbar-cancel of searchbar is not shown

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Framework7#1129]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 1.4.2.

### What you did
Use a Searchbar with Material Design:

```
<form class="searchbar searchbar-init" data-search-list=".search-here" data-search-in=".item-title">
				<div class="searchbar-input">
					<input type="search" placeholder="Search" />
					<a href="#" class="searchbar-clear"></a>
				</div>
<!-- searchbar-cancel is not shown -->
				<a href="#" class="link close-popup searchbar-cancel">Close</a>
			</form>
```

### Actual Behavior
The searchbar-cancel is not shown because f7 css file has 'display:none' when searchbar is shown:

.searchbar .searchbar-cancel {
    display: none;
}

### Expected Behavior
When searchbar is shown, then .searchbar .searchbar-cancel must be shown.

**Comment by valnub** [comment]
Hi, it does work properly in the kitchen sink demo, so there must be sth wrong with your code: https://framework7.io/kitchen-sink-material/
Please double-check and compare with the code from Kitchen Sink

**Comment by valnub** [comment]
Works perfectly in this fiddle: https://jsfiddle.net/valmar/99pyykLL/6/

The error must be in your code. Make sure that your form is within a page and a view.

Also double check if F7 is initialized correctly:

      var myApp = new Framework7({
          modalTitle: 'Framework7',
          material: true,
      });

      var mainView = myApp.addView('.view-main', {
      });

**Comment by nimo23** [comment]
hello, 

thanks. Yes, that was my fault: the searchbar was not correctly initialized. Now it works.

**Comment by valnub** [comment]
No problem :)
