### ISSUE TITLE
'back' link doesn't load fallback page from 'href'

### ISSUE THREAD

**Issue by obnijnil** [nolimits4web/Framework7#1131]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2b0fa3a5b171b1a3ca0ed2f3d6f97d6a6cd108ac.
* Platform and Target: iOS, ANDROID.

### What you did
Adding the 'back' class to a link with a 'href' attribute on a first page doesn't open the fallback 'href' url .

### Expected Behavior
As the [doc](http://framework7.io/docs/pages-ajax.html#going-back-in-navigation) says:
> If there are pages in navigation history Framework7 will always ignore url in "href" attribute
> If there are no pages in navigation history (for example, when you have "back" link on first home page) Framework7 will load page from "href" attribute

```js
// https://github.com/nolimits4web/Framework7/blob/master/src/js/router.js#L1008
url = options.url = view.history[view.history.length - 2];
// Should not override options.url and do:
url = view.history[view.history.length - 2] || options.url;
```

### Actual Behavior
It doesn't go back to the fallback page.

**Comment by valnub** [comment]
Hi, can you open a fiddle to show the issue? http://jsfiddle.net

**Comment by valnub** [comment]
Hi, I tried it and it works like a charm: https://jsfiddle.net/valmar/ku6jbe00/
When you click the back button it will take you to about page because history is empty and #about is set as href/default.
So, there must be something wrong with your code. Please double-check. If you can't figure it out, please post a fiddle. Otherwise this ticket gets closed.

**Comment by obnijnil** [comment]
@valnub It does go to the inline page, but it's not a "back" link (with the 'back' class).

After adding the 'back' class, nothing gets opened.

**Comment by valnub** [comment]
@obnijnil Yes, it does but you have to do it like this:

        <div class="navbar">
            <div class="navbar-inner">
                <div class="left">
                    <a href="#about" class="link">
                        <i class="icon icon-back"></i>
                        <span>Back</span>
                    </a>
                </div>
                <div class="center"></div>
                <div class="right"></div>
            </div>
        </div>

See https://jsfiddle.net/valmar/ku6jbe00/

**Comment by valnub** [comment]
@obnijnil Hm, you're right. Looks like a bug

**Comment by valnub** [comment]
Fixed in https://github.com/nolimits4web/Framework7/pull/1138
