### ISSUE TITLE
accordion-item and .picker-modal fires same event

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Framework7#1132]
**BUG**

**Version: 1.4.2**

I have a "accordion item" **within** a "picker modal" and have this event:

```
$$('.picker-modal').on('open', '.picker-modal', function (e) {
			e.stopPropagation();
			console.log('picker opened');
		}, false);
```

Unfortunately, this live-event will also be triggered if one item with css-class ".accordion-item" is expanded even if the picker-modal is already opened. The same goes for 

`$$('.picker-modal').on('close',`

If I shrink the ".accordion-item" (after it was expanded), then the close-Event of ".picker-modal" will be fired, even if the ".picker-modal" is not really closed. I guess, ".picker-modal"-open/closed events are not really isolated from ".accordion-item"-events. 

According to docs, picker-modal and accordion-items uses the **same event-names** (.open, .close, .opened, .closed). 

**However, these events have to be fired isolated from the both components by f7. Bug?**

**Comment by valnub** [comment]
Can you create a fiddle to reproduce the problem? Thanks :) http://www.jsfiddle.net

**Comment by nolimits4web** [comment]
@nimo23 this is because these events has same name, use it like:
```js
$$('.picker-modal').on('open', '.picker-modal', function (e) {
    if ($(e.target).hasClass('picker-modal')) {
        // Event generated by picker only, not by something else inside
        console.log('picker opened');
    }
}, false);
```
same for close event
