### ISSUE TITLE
New Chrome Update makes buttons float on scroll

### ISSUE THREAD

**Issue by rafuru** [nolimits4web/Framework7#1133]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.4.2 .
* Platform and Target: Desktop (Web) platform 

### What you did
Used a "<a>" with the class ".button" 

### Expected Behavior
Show a button where the <a> hyperlink is with a image (custom image) and scroll normally (along the content)

### Actual Behavior
after the last chrome update the buttons scrolls along the scrollbar

![captura de pantalla 2016-09-20 a las 9 03 45](https://cloud.githubusercontent.com/assets/778244/18685093/82bdf96a-7f2b-11e6-852d-a010e1e5193a.png)
![captura de pantalla 2016-09-20 a las 9 03 54](https://cloud.githubusercontent.com/assets/778244/18685094/82be3682-7f2b-11e6-842e-3bcd4a41e77a.png)

**Comment by ZanderBrown** [comment]
> Used a "" with the class ".button"

what is a ""?

Complete screenshots please if not code sample (jsfiddle ext)

**Comment by rafuru** [comment]
oh, github tried to parse the `<a>`

This is a sample of a button that moves along the scroll

```
<li class="item-content" >
                    <div class="item-inner">
                      <div class="item-title-row">
                        <div class="item-title">
                          <div class="floating-label">User</div>
                          <div class="item-input item-input-field not-empty-state">
                            <input  type="text" placeholder="User" autocomplete="off" required>
                          </div>
                        </div>
                      </div>
                      </div>
                    <div class="item-media pdIconMore " id="btn-opciones-emisor">
                      <a href="#" class="button" title="actions">
                        <i class="ion-plus-round ion3x"></i>
                      </a>
                    </div>
                  </li>
```

Due to the limits on my confidential agreement  I can't post a complete screenshot, but in the following pictures the gray button is aligned with  a box , when I scroll the button moves but the background keeps static.

I have tried this same page in firefox and , in fact, using the css inspector from chrome I have deactivated  the following properties in the .button class from framework7.materia.css : 

-webkit-transform: translate3d(0,0,0)
transform: translate3d(0,0,0)

![captura de pantalla 2016-09-20 a las 12 34 27](https://cloud.githubusercontent.com/assets/778244/18685978/19be4d08-7f2f-11e6-8bb1-284e39a86609.png)
![captura de pantalla 2016-09-20 a las 12 34 35](https://cloud.githubusercontent.com/assets/778244/18685979/19c07290-7f2f-11e6-8ed2-07c43f7d7ae9.png)

**Comment by valnub** [comment]
So, the problem is resolved?

**Comment by valnub** [comment]
Closed due to no reaction
