### ISSUE TITLE
If Template7 page fails to render, breaks routing

### ISSUE THREAD

**Issue by mikebetts** [nolimits4web/Framework7#1134]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.4.2
* Platform and Target: Cordova

### What you did
Using Template7 pages, if the template uses an object that isn't in the data, it will fail to render and breaks loading pages from then on.  To reproduce, in template7-pages example, just add following line to car.html and click on a car then try to click on the back link.

            <li><b>Air</b> - {{features.air}}</li>

### Expected Behavior
Expect that if data is missing from context it would just render with blank data.

### Actual Behavior
Using Template7 pages, if context data is not valid for template, rendering the template fails and leaves view.allowPageChange set to false. Subsequent calls to load pages then all fail.

**Comment by nolimits4web** [comment]
This happens because this is how JS works, if there is an error it breaks context. I can't check for existing of all variables in T7 before rendering because it could really slow down rendering/parsing performance. Just wrap such cases with custom `if` statements in templates:

```
<li><b>Air</b> - {{#if features}}{{features.air}}{{/if}}</li>

**Comment by mikebetts** [comment]
Hmmm, I understand the error is hard to prevent, but the bug is about what happens if it does occur.  Right now you can't render any pages in the entire app since the allowPageChange flag never gets reset.  

How about adding a try/catch around the call?  Then that page wouldn't render, but the app wouldn't stop working. I'm not familiar with the codebase, but something like:

```
try {
    t7_rendered_content = t7_template( t7_ctx );
}
catch( e ) {
    console.log( e.message );
    t7_rendered_content = '';
}
```
