### ISSUE TITLE
Framework7 ajax request and navigation don't work with phonegap for Android

### ISSUE THREAD

**Issue by phuongtailtranminh** [nolimits4web/Framework7#1136]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v1.4.2
* Platform and Target: PhoneGap 6.3.0 + Android API 23

### What you did
I tried to build my app on Android.
I used Phonegap + Framework7 in order to build an Android version.
I tested on Phonegap Developer App (on real device) aka Browser mode, it works fine.
But when I tried to build a version on Android -> It doesn't work at all.

### Expected Behavior
The **$$.ajax()** works fine.
The **navigation** works fine.

### Actual Behavior

**Problem** 

**The first problem** is: the **$$.ajax()** doesn't work at all on Android Emulator (but works well on Browser mode).
**The second problem** is: when I tried to navigating through views, the Android Log Windows displays:

`**Cannot call determinedVisibility() - never saw a connection for the pid xxxx**`

**Comment by valnub** [comment]
On Phonegap you have to wait until both, `deviceready` as well as `DOMContentLoaded` event have been fired. In the browser, only `DOMContentLoaded` is enough.

**Comment by nolimits4web** [comment]
@phuongtailtranminh make sure you have specified correct CSP in meta tag in the index.html file http://www.html5rocks.com/en/tutorials/security/content-security-policy/ . Also do the search for CSP on ftamework7 forum, there were a lot of discussions there about it
