### ISSUE TITLE
click event triggered twice in ios webview

### ISSUE THREAD

**Issue by lixinchuang** [nolimits4web/Framework7#1139]
I used framework7 like this:

<body class="">
    <button type="button" id="btn" style="margin:90px">click me</button>
    <script type="text/javascript" src="framework7.custom.min.js"></script>
    <script type="text/javascript">
        
           var myApp = new Framework7({});
           var $ = Dom7;
           alert($);
           $("#btn").on("click",function(e){
               
               alert("aaa");
           })
       
       </script>
</body>

when I  load the html in ios  simulator  webView, click the button,then alert twice!  

How to resolve this problem ?

Thanks a lot

**Comment by ZanderBrown** [comment]
Care to add further detail? A jsfiddle? a codepen? any code? a screenshot? meaningful description?

We are here to help. Help us help you.

**Comment by lixinchuang** [comment]
my code:
 <script type="text/javascript" src="framework7.custom.min.js"></script>
    <script type="text/javascript">
        
           var myApp = new Framework7({});
           var $ = Dom7;
 
           $("#btn").on("click",function(e){
               
               alert("aaa");
           })
       
       </script>

**Comment by lixinchuang** [comment]
my code just like this:


 var myApp = new Framework7({});
           var $ = Dom7;
       $("#btn").on("click",function(e){
             
           alert("tets")
      })


when I click the button, it alert twice

**Comment by lixinchuang** [comment]
I load the html in  ios simulator

**Comment by lixinchuang** [comment]
[index1.html.zip](https://github.com/nolimits4web/Framework7/files/493510/index1.html.zip)

the code is so easy ,but the alert is not show normally

**Comment by nolimits4web** [comment]
@lixinchuang don't use native JS `alert`, use `myApp.alert` instead. Native alerts break JS execution context which conflicts with fast click and you get double click instead

**Comment by lixinchuang** [comment]
In fact I need Call native App --- aplipay, but I found  I called Alipay twice,  How can I resolve this problem?

**Comment by lixinchuang** [comment]
Can I set the init property --fast click  to false?

**Comment by nolimits4web** [comment]
@lixinchuang you can disable fast click for this button by adding `no-fastclick` to it

**Comment by lixinchuang** [comment]
thanks very much, perfect!
