### ISSUE TITLE
transform: none; in button within scrollbar

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Framework7#1144]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.4.2

### What you did
I have a list of buttons within a scrollbar. All works. However, the browsers native scrollbar is **behind the button** and not in front of. F7-Button has this class-property:

`transform: translate3d(0, 0, 0);`

when setting it manually to 

`transform: none; `

then native scrollbar is correctly visible **in front of** the button.

However, then ripple-effect does no more work.

**Comment by valnub** [comment]
Hi, please post a code example to reproduce the issue via http://www.jsfiddle.net

**Comment by valnub** [comment]
No answer within 1 week. closed
