### ISSUE TITLE
Message Template Documentation seems to be cut

### ISSUE THREAD

**Issue by arvi** [nolimits4web/Framework7#1145]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.4.2.
* Platform and Target: Cordova
* Live Link or JSFiddle/Codepen: -

### What you did
I'm trying to create a custom message template so I tested passing the default template found in the docu for experimentation but I think the default template was cut right after the `message-appear` part
http://framework7.io/docs/messages.html (Message Template section)

### Expected Behavior
The correct default message template

### Actual Behavior
Messy display.

**Comment by valnub** [comment]
Hi, please post a code example to reproduce the issue via http://www.jsfiddle.net

**Comment by nolimits4web** [comment]
@arvi you are right, fixed. But this is issue not for F7 it is for website

**Comment by arvi** [comment]
Thank you for updating the docu :)

**Comment by ZanderBrown** [comment]
..mentation
