### ISSUE TITLE
Modals with custom html from file possible?

### ISSUE THREAD

**Issue by rogerhnn** [nolimits4web/Framework7#1149]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: Latest Version.
* Platform and Target: PC Android, ETC.

Hello, sorry if this has been already discussed, but I want to know if its possible to call a modal like the one from the example: https://framework7.io/kitchen-sink-material/ (popup link) with custom html file.
I want to show the content of a custom html file like in the views. Its possible?

Thanks
.

**Comment by J05HI** [comment]
You mean a modal which content is loaded dynamically through ajax? So it's content is a website or something like that?

**Comment by rogerhnn** [comment]
Yeah and no. Not a website, but a modal wich pulls its contents from a custom html file just like the views do. And not a modal that uses content from a js file.

**Comment by J05HI** [comment]
Okay should be easy to integrate :) 
+1 to integrate that, it may be useful for more users.

**Comment by nolimits4web** [comment]
What stops you do an Ajax request and call popup?
```
$$.get('somefile.html', function (content){
  myApp.popup(content);
})
```
`somefile.html` suppose you have the correct Popup's HTML structure
