### ISSUE TITLE
Can not  back to the first page

### ISSUE THREAD

**Issue by AlwaysBee** [nolimits4web/Framework7#1150]
I have four pages, index.html, test01.html, test02.html, test03.html.
Each page has the code like this

```
<div class="navbar">
    <div class="navbar-inner">
        <!-- We need cool sliding animation on title element, so we have additional "sliding" class -->
        <div class="left sliding">
            <a href="#" class="link back">
                <i class="material-icons">navigate_before</i>
            </a>
            <a href="test01.html" data-ignore-cache="true">test01</a>
        </div>
    </div>
</div>
```

but when I reached test03.html, and then click the back button, it can back to the test02.html,
and then click the back button in test02.html, it can not back to the test01.html
I don't know how can I implement it, please help

ps: sorry for my English, wish you can understand what I mean :-)

**Comment by ZanderBrown** [comment]
Does it go anywhere?

**Comment by AlwaysBee** [comment]
@ZanderBrown NO, nothing happened :(

**Comment by chalchis** [comment]
try using the demo
something must be wrong

**Comment by valnub** [comment]
Are there any errors in js console?

If you can post a fiddle or codepen example it would be easier to help you and debug this:

- http://www.jsfiddle.net
- http://www.codepen.io

**Comment by allantorres** [comment]
@AlwaysBee can you put your project in a repository ? 
Are you running this on http server like apache? 

You need to understand the navagation history is the base to use the back link. So if you came from another page, this page will be the back page, so in this case i suggest you organize your project and review your HTML and links to be sure, if all are in the right place.

**Comment by ZanderBrown** [comment]
Could you please expand you point?
Consider pointing code snippets here, on [Codepen](https://codepen.io) or on [JSFiddle](https://jsfiddle.net).
Make sure you have read the [documentation](http://framework7.io/docs/) correctly and followed any instructions it may give.

**Comment by ZanderBrown** [comment]
There hasn't been a response by the issues owner in 20 days.
This issue **will be closed in 7 days** if no further response is submitted
