### ISSUE TITLE
Infinite Scroll is not work when page has a Virtual list

### ISSUE THREAD

**Issue by pccai** [nolimits4web/Framework7#1152]
I have a cus page, want to some features: infinite-scroll, pull-to-refresh, searchbar, but infinite-scroll event is never fired?

my page html:

`<div class="page-content pull-to-refresh-content infinite-scroll">
                        <div class="pull-to-refresh-layer">
                            <div class="preloader"></div>
                            <div class="pull-to-refresh-arrow"></div>
                        </div>
                  <div class="list-block media-list  searchbar-found virtual-list" style="margin:0 0 35px 0;">
</div>`

**Comment by valnub** [comment]
Hi, can you please post a jsfiddle or codepen example so we can reproduce this issue? Thanks.

- http://www.jsfiddle.net
- http://www.codepen.io

Note: Please post your runnable example within 1 week, otherwise this issue will be closed.
