### ISSUE TITLE
links missing the "href" attributes in searchbar/smartselect do not work

### ISSUE THREAD

**Issue by seme1** [nolimits4web/Framework7#1154]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: V1.4.2.
* Platform and Target: Ios AND Android

--- 

I updated the description for this issue. PLEASE READ MY COMMENT BELOW. This bug does NOT cause an exception. It however causes the some links to stop functions such as the back link for the auto generated smartlink and the link for searchbar.

---- 

Framework7 expects ALL anchor links as in (< a >) links to have a "href" attribute. If there is a link with a missing "href" attribute and is used for example to open a popup with the class='open-popup' and the data- attributes, the framework would give an exception.

One may ask why a link would not have an href attribute ? Because the WKWebview for IOS sometimes crashes/freezes the app when there are empty links with empty href attribute (as in <a href="#" ></a>).

And in any case, it should be extremely an easy fix in Framework7 to simply check if there is an href attribute before processing the content of the attribute.
----

**Comment by nolimits4web** [comment]
Hi, actually there is actually a check for href attribute inside, and i can't really replicate this issue and see any exceptions. How to replicate the issue to see it?

**Comment by seme1** [comment]
I've made few changes to the original source code to fix the problems I was facing. This was done probably five or six months ago. I'll try to find the changes and get back. From what I recall, the problem was with the back/close button in the navbar of smartselects and searchbars.  It was an easy and quick fix but I spent several days till I figured out the source of the problem with href='#' attributes as was outlined in the Ionic blog and Framework7 forums by several members.

**Comment by seme1** [comment]
Ok, I think I found it. 
On last 5430 of the dist version of Framework7, I had to change the leftTemplate source code for the auto generated smartselect to the following:

`                    leftTemplate: openIn === 'popup' ? 
                        (app.params.smartSelectPopupCloseTemplate || (material ? '<div class="left"><a href="emptyLink" class="link close-popup icon-only"><i class="icon icon-back"></i></a></div>' : '<div class="left"><a href="emptyLink" class="link close-popup"><i class="icon icon-back"></i><span>{{closeText}}</span></a></div>')).replace(/{{closeText}}/g, closeText) :
                        (app.params.smartSelectBackTemplate || (material ? '<div class="left"><a href="emptyLink" class="back link icon-only"><i class="icon icon-back"></i></a></div>' : '<div class="left sliding"><a href="emptyLink" class="back link"><i class="icon icon-back"></i><span>{{backText}}</span></a></div>')).replace(/{{backText}}/g, backText)
`
I think when href is removed, the links no longer work as expected with smartselect.  

Then,  on 5462 I also modified the searchbarHTML variable in order to update the href attribute to something like href='emptyLink'. 

I'm closing this issue since it is exactly an exception/crash as I described earlier. However, the function of the "searchbar-cancel" and "close-popup" links would NOT work if the href attribute is missing.

**Comment by seme1** [comment]
I think this is still a bug. As I mentioned before, for the close link that is auto generated for the smartselect, if there is a missing href attribute, the link would not work (even though it has the "back" class).  The issue also happens with the searchbarHTML (on linke 5462 of the Framework7 dist file) as removing the href attribute would not make the link work.

**Comment by valnub** [comment]
Can you post a fiddle or codepen example so the issue can be replicated? Thanks :)

- http://www.jsfiddle.net
- http://www.codepen.io
