### ISSUE TITLE
Touch event: Highlighted text not removed when touching another element (Mobile Web)

### ISSUE THREAD

**Issue by arvi** [nolimits4web/Framework7#1157]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.4.2
* Platform and Target: CORDOVA / MOBILE WEB
* Live Link or JSFiddle/Codepen: http://framework7.io/kitchen-sink-material/

### What you did
1. In desktop web browser, click any component e.g Cards then highlight some text
2. Click anywhere aside from the highlighted text
3. You will notice that the highlighted text has been removed (the expected behavior)

1. In mobile web browser, click any component e.g Cards then highlight some text
2. Touch anywhere aside from the highlighted text
3. Nothing happens to the highlighted text

### Expected Behavior
In mobile browser, upon touching anywhere else, it should also remove the highlighted text like so:
1. In mobile web browser, open http://framework7.io/ then highlight some text
2. Touch anywhere aside from the highlighted text
3. You will notice that the highlighted text has been removed (the expected behavior)

### Actual Behavior
Nothing happens to the highlighted text on touch event. Problem seems specific to F7 upon inspecting other mobile web apps trying the same thing.

**Comment by valnub** [comment]
Hi, I cannot reproduce this issue on my iPhone with iOS10. What device and OS are you using?

**Comment by arvi** [comment]
@valnub Thanks for trying to help.

For the desktop browser, I am using Chrome. For the mobile web, I'm using an Android Lollipop phone.

**Comment by valnub** [comment]
Can anyone with an Android phone confirm this?

**Comment by arvi** [comment]
@valnub I recorded it :smile: 

Test done in http://framework7.io/kitchen-sink-material/

https://www.dropbox.com/s/aenlqpty29lsnmh/Movie%20on%2005-10-2016%20at%206.32%20PM.mov?dl=0

**Comment by valnub** [comment]
Thanks, looks like a bug.

Can you please also post:

- Device name (Manufacturer & model name (e.g. Samsung Galaxy S7))
- Browser name and version (e.g. Chrome 47)

**Comment by arvi** [comment]
Hello @valnub

1. I tried using my cheap china phone and my friend's latest Asus phone... Can't remember the brand (I don't think it's device specific)

2. I tried using other browsers (the default google browser) yielding same result.

I'll try tomorrow at work borrow my colleague's iphone and test the kitchen sink material and ios.

**Comment by arvi** [comment]
Hello @valnub

I can confirm that this is not happening on iOS upon testing http://framework7.io/kitchen-sink-material/ on colleague's iphone and ipad in Safari and Chrome browser. 

The bug is specific to Android.

Thanks. :smile:
