### ISSUE TITLE
when picker column data from ajax,didn't auto choose new data's first value

### ISSUE THREAD

**Issue by Ashley2014** [nolimits4web/Framework7#1161]
This is a (multiple allowed):
* [ ] bug

* Framework7 Version: 1.4.2
* Platform and Target: all

### What you did
I have 2 Column , the second col data replace via ajax, when ajax callback,I trigger picker.cols[1].replaceValues([1,2,3,4]) ,Column2 didn't select the first value.

this work

```
onChange:function (p, values, displayValues) {
   if(p.cols[1].replaceValues) {
     p.cols[1].replaceValues([1,2,3,4]);
  }
},
```

this didn't work

```
onChange:function (p, values, displayValues) {
   if(p.cols[1].replaceValues) {
      setTimeout(function () {
           p.cols[1].replaceValues([1,2,3,4]);
        },1000)
      }
 },
```

**Comment by valnub** [comment]
Hi, can you please post a jsfiddle or codepen example so we can reproduce this issue? Thanks.

You can use one of these templates for that:

- iOS [JSFiddle](https://jsfiddle.net/mvs820k0/)/[Codepen](https://codepen.io/nolimits4web/pen/vXmmgG)
- Material [JSFiddle](https://jsfiddle.net/u8a87yd2/2/)/[Codepen](https://codepen.io/nolimits4web/pen/pEPPPK)

Note: Please post your runnable example within 1 week, otherwise this issue will be closed.

**Comment by nolimits4web** [comment]
It works, just try to change Kitchen Sink's code at https://github.com/nolimits4web/Framework7/blob/master/kitchen-sink-ios/js/kitchen-sink.js#L604-L607

from
```
                onChange: function (picker, country) {
                    if(picker.cols[1].replaceValues){
                        picker.cols[1].replaceValues(carVendors[country]);
                    }
                }
```

to
```
                onChange: function (picker, country) {
                    if(picker.cols[1].replaceValues){
                        setTimeout(function () {
                            picker.cols[1].replaceValues(carVendors[country]);
                        }, 1000);
                    }
                }
```

And to be honest i don't see reason why it may not work in setTimeout or Ajax call, so look for the issue in your code

**Comment by Ashley2014** [comment]
@valnub @nolimits4web 
https://jsfiddle.net/yezhuyz/mer2n5m2/2/
sorry I'm kind of rookie,not familiar with jsfiddle. I create one, when you select American,the input still maintain Honda.
![croppercapture 6](https://cloud.githubusercontent.com/assets/7813671/19209808/0c8a2c32-8d45-11e6-95b7-ad762b141b78.Gif)

**Comment by valnub** [comment]
nolimits4web is right, there seems to be a problem with your code but it's most likely not a F7 bug, so this is the wrong place to ask.

I recommend to post your question on one of these platforms (include your fiddle!):

- [F7 forums](http://forum.framework7.io)
- [Stackoverflow](http://www.stackoverflow.com)

I'm sure there are some nice devs who will help you.
