### ISSUE TITLE
⚠️STOP link to the Chinese Document ⚠️

### ISSUE THREAD

**Issue by evolutionjay** [nolimits4web/Framework7#1164]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Framework7 Version: 1.4.2+

dont link to the http://f7cn.com
this website is no longer update.

**Comment by macdonst** [comment]
@evolutionjay I can still reach that site.

**Comment by evolutionjay** [comment]
@macdonst Of course, but the framework7 version is no longer updated.
