### ISSUE TITLE
Ajax error callback is always called  (after success callback) if I set timeout option

### ISSUE THREAD

**Issue by IvanPaiano** [nolimits4web/Framework7#1166]
This is a (multiple allowed):
- [x] bug
- Framework7 Version: V1.4.2.
- Platform and Target: All
### What you did

$$.ajax({
    url: 'operation/update',
    data: {id: 10},
    cache: false,
    method: 'POST',
    dataType: 'json',
    async: false,
    timeout: 10000, //10 sec
    success: function (data, status, xhr) {
        alert("OK!");
    },
    error: function (xhr, status) {
        alert("KO!");
    }
});

I get "OK!" alert and after 10 seconds I get "KO!" alert...
url returns a correct JSON .
Perhaps it is not properly reset timeout timer...

Thank you.

**Comment by macdonst** [comment]
@IvanPaiano I think I have a fix for this issue. More detailed description in the PR.
