### ISSUE TITLE
onPageInit for popup pages

### ISSUE THREAD

**Issue by henriqueweiand** [nolimits4web/Framework7#1168]
Hello!

I'm trying to apply onpageinit on a page that I set up in a separate html in what is called through a function and get right after myApp.popup (html);

Thus it seems to me that the f7 can not interpletar that the page was started and run in turn onpageinit event.

Am I doing something wrong or is it a bug / feature?

`myApp.onPageInit('login', function(page) {
	console.log("teste");
});`

**FUNCTION:**
`this.pageLoad = function(page) {
    $$.get(config.local + page,
        function (template) {
            myApp.popup(template);
        }
    );
}`

**HTML:**
`<div class="popup">

	<div data-page="login" class="page navbar-fixed">

		<div class="navbar" style="background:none">
	        <div class="navbar-inner">

	            <div class="left">
	                <a href="#" class="link icon-only close-popup">
	                    <i class="material-icons color-black">&#xE5CD;</i>
	                </a>
	            </div>

	        </div>
	    </div>

		<div class="page-content">

		</div>
	</div>

</div>`

**Comment by nolimits4web** [comment]
You should have full View HTML structure there with `.views > .pages > .page > ....` to have this event
