### ISSUE TITLE
Import css or js according to modularity

### ISSUE THREAD

**Issue by aliencyl7** [nolimits4web/Framework7#1169]
### Expected Behavior
For the mobile project. i don't want to load the whole css or js, cuz the size of the file is extremely big for the mobile app. Instead , i want to load partial js or css , but f7 doesn't support it .

**Comment by snsxn** [comment]
You can do a custom build: [Framework7 Custom Build](http://framework7.io/docs/custom-build.html)
You'll need Node and Gulp installed.
