### ISSUE TITLE
[Question] How to update context without page reload

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7#1171]
Hi there! I have created a JSFiddle and hope to find a solution for the following:

1) Click on the link (template will render page)
2) Type something in the input (within three seconds)
3)  ... and after three seconds: tel and email should update - BUT input value should stay

https://jsfiddle.net/scriptPilot/o7hjh1fq/8/

Is that possible out of the box or do I have to find any workaround?

Cheers!

**Comment by ZanderBrown** [comment]
`Template7` is like `PHP`. It's used to generate static content.
Give the element an id and modify it's innerHTML property

**Comment by scriptPilot** [comment]
Okay, thanks for that confirmation.

**Comment by nolimits4web** [comment]
Template7 doesn't have data bindings
