### ISSUE TITLE
when back to Index page, the page was empty

### ISSUE THREAD

**Issue by lixinchuang** [nolimits4web/Framework7#1172]
when page init: I  set domCache to false:

 window.mainview = myApp.addView('.view-main', {
            domCache: false, 
            dynamicNavbar: true
           
        });

besides, my first page's data was retived from ajax data;

then , I  opened more than three ajax pages, and then I clicked the back icon,  util  the page load the index page,but the index page's data was cleared

why this happend?

**Comment by ZanderBrown** [comment]
so what your saying is you disabled the cache and now the cache is empty?

**Comment by nolimits4web** [comment]
Because in this case router will load page using Ajax from index file and it is empty. Enable domCache or load its Ajax content once again when you get back to it
