### ISSUE TITLE
Search bar behind subnavbar

### ISSUE THREAD

**Issue by IAmJulianAcosta** [nolimits4web/Framework7#1174]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform and Target: iOS
* Live Link or JSFiddle/Codepen: http://codepen.io/iamjulianacosta/pen/kkzvjO

### What you did
Added search bar and subnavbar.

### Expected Behavior
Search bar visible.

### Actual Behavior
Search bar behind subnavbar, hidden.

![image](https://cloud.githubusercontent.com/assets/1844640/19601210/ea7e5b12-976d-11e6-9a5d-bbd0de56ff9a.png)

**Comment by ZanderBrown** [comment]
due to the way they are currently implemented you cannot have both at once

**Comment by nolimits4web** [comment]
Not easy to handle this case automatically, just increase `top` position to this searchbar and increase `padding-top` on page-content for this page
