### ISSUE TITLE
Navbar slides to the top on input field focus

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7#1177]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Framework7 Version: 1.4.2
- Platform and Target: iPhone SE / iOS 9.3.5
- Live Link or JSFiddle/Codepen: Please see attached screenshots
### What you did

Click into input fields and type some text
### Expected Behavior

Navbar remains completely visible (see first screenshot from remember the milk application and second one from framework7 picker example)
### Actual Behavior

Navbar slides to the top (see third screenshot from framework7 form inputs example)
![image 001](https://cloud.githubusercontent.com/assets/19615586/19639052/f7422a52-99d6-11e6-8c52-0fafbf538496.png)
![image 002](https://cloud.githubusercontent.com/assets/19615586/19639053/f746bc52-99d6-11e6-8ea4-759647691c70.png)
![image 003](https://cloud.githubusercontent.com/assets/19615586/19639054/f74a7298-99d6-11e6-9979-9f523308bfa4.png)

**Comment by nolimits4web** [comment]
Discussed many times, check forum for the solutions

**Comment by scriptPilot** [comment]
Unfortunately, all I found have been solutions with cordova plugins. Are there no solutions with Framework7 / JS only?

**Comment by nolimits4web** [comment]
Yes, not really much to do with the usual web app as it is the system browser limitation. The only thing you can try is to change position for navbar from `absolute` to `fixed`
