### ISSUE TITLE
Smartselect with data-back-on-select="true" does not close when clicking on the preselected item

### ISSUE THREAD

**Issue by cyberbeat** [nolimits4web/Framework7#1182]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Framework7 Version: 1.4.2
- Platform and Target: IOS

Smartselect with the option data-back-on-select="true" should always be closed, when clicking on an item, no matter which item.

**Comment by nolimits4web** [comment]
Same as #1045, already fixed
