### ISSUE TITLE
how to add a extra parameter to the dom7's ajax request 

### ISSUE THREAD

**Issue by imic07** [nolimits4web/Framework7#1183]
This is a (multiple allowed):
- [x] enhancement
- Framework7 Version: 1.4.2.
- Platform and Target: Chrome.
- Live Link or JSFiddle/Codepen: 
  ### What you did
  I init the ajax like this;

$$(document).on('ajaxStart', function(e){
    e.detail.xhr.requestUrl += '&_v=' + 10040;
    e.detail.xhr.requestParameters.data +='&_v=' + 10040;
    e.detail.xhr.requestParameters.url +='&_v=' + 10040;
    console.log(e.detail.xhr);
});
$$.ajaxSetup({
    data:{_v:10040},
    beforeSend:function(xhr){
        xhr.requestUrl += '&_v=' + 10039;
        xhr.requestParameters.data +='&_v=' + 10039;
        xhr.requestParameters.url +='&_v=' + 10039;
        console.log(xhr);
        myApp.showIndicator();
    },
    complete:function(xhr,s){
        myApp.hideIndicator();
    }
}
### Expected Behavior

i want all the ajax request url add a extra parameter like this  
http://www.xxx.com?_v=1
http://www.xxx.com?name=xx&_v=1
### Actual Behavior

http://www.xxx.com
http://www.xxx.com?name=xx

how can i solve this problem? tks

**Comment by nolimits4web** [comment]
Something like this
```
$$(document).on('ajaxStart', function (e) {
    var xhr = e.detail.xhr;
    var url = xhr.requestUrl;
    var newUrl = url + (xhr.requestUrl.indexOf('?')>=0 ? '?' : '&') + 'PHPSESSID=something';
    xhr.open(xhr.type, newUrl, true, xhr.requestParameters.user, xhr.requestParameters.password);
});
```

**Comment by imic07** [comment]
$$(document).on('ajaxStart', function(e){
	var xhr = e.detail.xhr;
    var url = xhr.requestUrl;
    var newUrl = url + (xhr.requestUrl.indexOf('?')>=0 ? '&' : '?') + '_v=1000';
    xhr.open(xhr.requestParameters.method, newUrl, true);
});

this can work well ,thank you
