### ISSUE TITLE
 z-index notifications 

### ISSUE THREAD

**Issue by henriqueweiand** [nolimits4web/Framework7#1186]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)

It seems to me that this notifications with a smaller z-index that popup screens ...

**Comment by nolimits4web** [comment]
No, it is not, Notification has 20000, while popup is 11000. Make sure you have correct popup

**Comment by heiko-nz** [comment]
In the framework7.material.css, Notification has a z-index of 10900, while for iOS it has 20000:

/* === Notifications === */
.notifications {
  position: absolute;
  left: 0;
  bottom: 0;
  width: 100%;
  z-index: 10900;

So on Android, the notification does not show over a popup.
What's the reason for the difference between Android and iOS here?
