### ISSUE TITLE
Pull-to-refresh does not work programmatically

### ISSUE THREAD

**Issue by lroal** [nolimits4web/Framework7#1187]
This is a bug.
- Framework7 Version: february 2016
- Platform and Target: chrome on linux.

When adding the pull-to-refresh programmatically, neither the arrow down nor the spinner shows.
Actually, you can reproduce the same by just pasting in the pull-to-refresh-html in developer modus in chrome instead of doing it by code. The sample below doesn't format properly, but I hope you understand.
**html:**
```
<body>
    <!-- Status bar overlay for full screen mode (PhoneGap) -->
    <div class="statusbar-overlay"></div>  
    <div class="panel-overlay"></div>  
    <!-- Views -->  
    <div class="views">  
        <div class="view view-main">  
            <div class="pages">  
                <div id='home' data-page="home" class="page navbar-fixed toolbar-fixed">  
                </div>  
            </div>  
        </div>  
    </div>  
    <script type="text/javascript" src="main.js"></script>  
</body>  
```
**js:**
```
var myApp = new Framework7();

var mainView = myApp.addView('.view-main', {
    dynamicNavbar: true
});

var win = require('window');
win.$$ = Dom7;
win.app = myApp;

var region = document.getElementById('home');
var cont =    '<div class="navbar">  
                  <div class="navbar-inner">  
                      <div class="left"></div>  
                      <div class="center">Climbing gyms</div>  
                      <div class="right"></div>  
                  </div>  
                </div>  
                <div data-name="pullToRefreshGyms" id="pullToRefreshGyms" class="page-content pull-to-refresh-content" data-ptr-distance="55">  
                     <div class="pull-to-refresh-layer">    
                         <div class="preloader"></div>  
                         <div class="pull-to-refresh-arrow"></div>  
                     </div>  
                </div>';
win.$$('#home').html(cont);
```

**Comment by lroal** [comment]
The html I am inserting dynamically in the home element is this:
`<div class="navbar"><div class="navbar-inner"><div class="left"></div><div class="center">Climbing gyms</div><div class="right"></div></div></div><div data-name="pullToRefreshGyms" id="pullToRefreshGyms" class="page-content pull-to-refresh-content" data-ptr-distance="55"><div class="pull-to-refresh-layer"><div class="preloader"></div><div class="pull-to-refresh-arrow"></div></div></div>`

**Comment by bicycleChen** [comment]
Maybe you can format your code first, and others can see clearly

**Comment by bicycleChen** [comment]
```html
      <div className="views">
        <div className="view view-main">
         <div className="page">
           <div className="page-content pull-to-refresh-content" data-ptr-distance="85">

             <div className="pull-to-refresh-layer">
               <div className="preloader"></div>
               <div className="pull-to-refresh-arrow"></div>
             </div>

             <div className="list-block">
               <ul>
                 <li className="item-content">
                   <div className="item-media"><img src="http://hhhhold.com/88/d/jpg?1" width="44" /></div>
                   <div className="item-inner">
                     <div className="item-title-row">
                       <div className="item-title">Yellow Submarine</div>
                     </div>
                     <div className="item-subtitle">Beatles</div>
                   </div>
                 </li>
               </ul>
             </div>
           </div>
         </div>
        </div>
      </div>
```
The html structure is the important in F7!!!! If there was any wrong with the code ,plz checked the structure of the html from the official demo

**Comment by lroal** [comment]
I have formatted it properly now. 
I left out the listening on the refresh event in this sample for convenience.

**Comment by ZanderBrown** [comment]
you can't create it dynamically! the various listeners wont get added!

**Comment by lroal** [comment]
Well, that is major problem. Shouldn't a framework like this support adding html at runtime ?
Is there any workarounds for this ?

**Comment by ZanderBrown** [comment]
it's actually quite tricky to do. maybe explain why you want to do it?

**Comment by lroal** [comment]
I have a recursive list of items. Inside an items there could be more items. I do not know in advance how deep it will be be. I depends on there data received from the server.

**Comment by ZanderBrown** [comment]
Just checked the docs and i suggest you try
```javascript
myApp.initPullToRefresh("#pullToRefreshGyms");
```

**Comment by lroal** [comment]
Success !
Thank you.

**Comment by vishnoor** [comment]
I had the same issue. The official doc example mentions the sample code as 

// Add 'refresh' listener on it
ptrContent.on('ptr:refresh', function (e) {

It should be 
// Add 'refresh' listener on it
    ptrContent.on('refresh', function (e) {

**Comment by Vacster** [comment]
@vishnoor Is right, it should be 'refresh' instead of 'ptr:refresh'. The docs should be changed to reflect this. Thanks vishnoor.
