### ISSUE TITLE
UI components cannot be really fixed on the bottom of a webpage (ios only)

### ISSUE THREAD

**Issue by newhow** [nolimits4web/Framework7#1188]
When I open the [kitchen-sink](http://framework7.io/kitchen-sink-ios) page in ios Safari, I find that some components, like toolbar, does not really stick to the bottom. It moves when swiped up. This is an ios only problem

**Comment by kivancsahici** [comment]
This is a mobile Safari feature. If you're building a Cordova app, you can easily fix it by configuration.

**Comment by kivancsahici** [comment]
You might wanna check this out
http://blog.blakesimpson.co.uk/read/87-prevent-the-cordova-web-view-from-bouncing

**Comment by newhow** [comment]
@kivancsahici thank you. Exactly the solution I was seeking.
