### ISSUE TITLE
Volvo isn't German (kitchen sink)

### ISSUE THREAD

**Issue by netsurfer912** [nolimits4web/Framework7#1190]
Hey. While dabbling with the demo, I came across this: 
![image](https://cloud.githubusercontent.com/assets/1337470/19928064/20ed9878-a0fd-11e6-8473-381a386ac063.png)
Volvo is based in Sweden and belongs to a Chinese company now. 
As a car industry interested German I take a little offense to this. 
Otherwise, no problems so far! Looks like a great framework!

**Comment by centrual** [comment]
hahaha, really? is that real? lol
