### ISSUE TITLE
Accordion events trigger side panel events

### ISSUE THREAD

**Issue by astaffen** [nolimits4web/Framework7#1192]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 1.4.2
* Platform and Target: Cordova, iOS, Android

### What you did
I've put an accordion in a side panel.

### Expected Behavior
When I open/close an accordion item, only accordion events should be triggered.

### Actual Behavior
When I open/close an accordion item, the side panels events (open, opened, close, closed) are also triggered.

**Comment by nolimits4web** [comment]
This events just have same names. So do the check if you rely on events, e.g.
```js
$('.panel').on('open', function(e){
  if (!$(e.target).hasClass('panel')) {
    //event triggered by panel
  }
})
