### ISSUE TITLE
Back link triggers PageInit event for two pages

### ISSUE THREAD

**Issue by GeorgThomassen** [nolimits4web/Framework7#1194]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.4.2
* Platform and Target: PhoneGap, IOS
* Live Link or JSFiddle/Codepen: https://www.georgthomassen.dk/issue/

### What you did
I'm trying to use the "back" class on a link. See Page 2 in live link

### Expected Behavior
The expected behavior is to go back only one step in history or when using the data-force attribute, only trigger the PageInit for one page.

### Actual Behavior
Pressing the back button does the following:

1. Goes __two__ steps back in the history *with no* `data-force="true"`
or 
2. Goes to the right page *with* `data-force="true"` but triggers the PageInit events for both pages.

See the console when navigating.

**Comment by yunusbolat** [comment]
there is no back page for back page , when you go back another back page is added by framework7 but this causes pageinit event, i agree this is a bug because you dont see page but a lot of functions and requests run binded to that pageinit event

**Comment by GeorgThomassen** [comment]
well.. A temporary fix is to use the onPageBeforeAnimation hook instead.

**Comment by nolimits4web** [comment]
It is not a bug, this happens because F7 preloads previous page (for swipeback availability) and, of course, it triggers pageInit event. You can enable domCache in this case or disable `swipeBackPage` and `preloadPreviousPage` parameters
