### ISSUE TITLE
.messagebar blocks last message in Firefox

### ISSUE THREAD

**Issue by softexe** [nolimits4web/Framework7#1195]
* [x] bug

* Framework7 Version: 1.4.2
* Platform and Target: Firefox 49/Windows
* Live Link or JSFiddle/Codepen: https://jsfiddle.net/Nikoniko/8hrbtjms/12/

### What you did
Запуская версию чата на firefox, но самое последнее сообщение закрывается .messagebar
Пробовал увеличить значение .padding-bottom для .messages, но не помогает.

**Comment by softexe** [comment]
Нашел решение через установку свойств 
```

.messagebar ~ .page-content {
	padding-bottom: 0;
	bottom: 44px;
}

```

**Comment by nolimits4web** [comment]
Это давний баг ФФ, он не корректно воспринимает padding-bottom на элементе с overflow:auto

**Comment by ZanderBrown** [comment]
There hasn't been a response by the issues owner in 20 days.
This issue **will be closed in 7 days** if no further response is submitted

**Comment by sheillendra** [comment]
some problem in page with tabbar layout, in firefox padding-bottom no effect, the solution override the class.
```
.tabbar-fixed .page-content, .tabbar-through .page-content, .toolbar-fixed .page-content, .toolbar-through .page-content {
    padding-bottom: 0;
    bottom: 44px;
}
```
