### ISSUE TITLE
Range Slider onchange event doesn't trigger.

### ISSUE THREAD

**Issue by knowthelist** [nolimits4web/Framework7#1198]
This is a
* [x] bug

* Framework7 Version: 1.5
* Platform and Target: iOS 9.3.5

Range Slider onchange event doesn't trigger after init a Framework7 app.

```html
<!DOCTYPE html>
<html>
<head></head>
<body>
    <input type="range" onchange="alert('huhu')">
</body>

<script src="lib/framework7.js"></script>
<script>
    var app = new Framework7();
</script>

</html>
```

**Comment by nolimits4web** [comment]
Because for range slider it should be "oninput" event

**Comment by knowthelist** [comment]
I know "oninput", but this behavior is different. It triggers on every single step. I need the value if the user finished movement. The value should be directly forwarded to server, but not each step to avoid overload issues.
"onchange" doesn't work only on iOS. No issue on Firefox on OSX or on Android.

If I disable this line like this:

//var app = new Framework7();

"onchange" works again

**Comment by ZanderBrown** [comment]
Look like there is defiantly an issue here

**Comment by dawiinci** [comment]
I can confirm this issue.
