### ISSUE TITLE
Badge not shown properly with f7-icons class

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7#1202]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

First of all thank you for the new icon set! One bug I have encountered with the new icons: If I use the icons in the tabbar together with a badge, the badge will only be shown properly if I add class "icon" to i element with "f7-icons" class - maybe the CSS changes could also be applied together with "f7-icons" only?

With and without "icon" class:

![screenshot 6](https://cloud.githubusercontent.com/assets/19615586/20186571/d6d55a44-a770-11e6-95ae-5df1f2389425.png)
![screenshot 7](https://cloud.githubusercontent.com/assets/19615586/20186573/d6f5a150-a770-11e6-86b4-24d1ddaf2fc8.png)

**Comment by drptbl** [comment]
@nolimits4web 
Hey and sorry in advance for throwing it there but it's probably related to this ticket.
I'm still seeing an issue while not using `icon` class together with `f7-icons`. Should they be used together or not?

with `icon` css class:
```
                    <a href="#" class="link icon-only">
                        <i class="icon f7-icons">bell<span class="badge bg-red">5</span></i>
                    </a>
```
<img width="39" alt="screen shot 2017-01-25 at 16 28 17" src="https://cloud.githubusercontent.com/assets/8177587/22296853/c08c954a-e31b-11e6-96dd-079cfdaf16b4.png">

without `icon` css class:
```
                    <a href="#" class="link icon-only">
                        <i class="f7-icons">bell<span class="badge bg-red">5</span></i>
                    </a>
```
<img width="63" alt="screen shot 2017-01-25 at 16 27 59" src="https://cloud.githubusercontent.com/assets/8177587/22296863/c84c8998-e31b-11e6-8f8e-a94ecd3a95fd.png">

Best regards,
Jacob.

**Comment by ZanderBrown** [comment]
If it works with both what's the problem?

I would say yes as off the top of my head `icon` is for the positioning within the toolbar whereas `f7-icons` if for using the bundled icons
