### ISSUE TITLE
Vertical form layout for long form element titles

### ISSUE THREAD

**Issue by ibrahimyilmaz7** [nolimits4web/Framework7#1203]
Hi everyone, here is nice solution for who needs long form titles. Maybe this could be a feature request.

**Form default:**
![form_old](https://cloud.githubusercontent.com/assets/5227444/20189640/c8679f10-a786-11e6-9cc7-ec1be14bd86a.PNG)

this is my solution:

```
.list-block.form-vertical .item-title {
    white-space: normal;
    width: 100%;
    min-width: 100%;
    max-width: 100%;
    margin-bottom: 5px;
}

.list-block.form-vertical .item-inner {
    display: block !important;
}

.list-block.form-vertical .item-title.label {
    width: 100%;
}

.list-block.form-vertical .item-title.label + .item-input {
    margin: 0;
}

.list-block.form-vertical .smart-select .item-after,
.list-block.form-vertical .autocomplete-opener .item-after {
    width: 100%;
    min-width: 100%;
    max-width: 100%;
}
```

and result:

**Form vertical:**
![form_new](https://cloud.githubusercontent.com/assets/5227444/20189644/cb9d7812-a786-11e6-921d-bdb192937fdf.PNG)

**Comment by ZanderBrown** [comment]
I'm not sure is complies with the iOS HIG.

**Comment by nolimits4web** [comment]
Fixed in v2
