### ISSUE TITLE
Back to home issue after 2 page navigation 

### ISSUE THREAD

**Issue by Tris10** [nolimits4web/Framework7#1204]
I'm having an issue where if a user navigates two pages deep, but goes back to the homepage, the cache of the home page is cleared. 
The home page is inline of course, the two pages are ajax.

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.0
* Platform and Target: All
* Live Link : http://mobile.leaguegaming.com/mobile/v5/www3/ Video demo https://www.youtube.com/watch?v=MPbtp1hddlw (notice how i first go one page deep, then back. then go two pages deep and back and the home page cache is gone)

### What you did
(close the login popup) click the top right menu > roster > any team, then go back to the home page.

### Expected Behavior
The homepage cache should still be there.

### Actual Behavior
returns a index.html as is, not as it was left.

**Comment by shuizhongyueming** [comment]
As I know, Framework7 only cache the `prev page`.

If the history is `home > list > article`, and current page is article with two pages deep, the page home will not be the prev page, and will remove automatically. 

When you back to the page list, page article will remove and the page home become the prev page.

At this time, Framework7 will load html of the page home.

When you back again, the page home is show.

But as your demo, you haven't add a listener for the pageInit event of the page home. So only the html is load and show, but the init action in js for the page home haven't trigger again.

**Comment by Tris10** [comment]
@shuizhongyueming , First thank you for your reply.

I didnt know it only caches one page, the reason this confused me is in older versions it never did this before, it would cache all the pages. I was wondering if its a setting or a default im missing but could not figure this out after searching through the docs

I did do a listener event for onPageBeforeAnimation and if its the index, fire off the INIT function that loads the home page to temp fix this.

**Comment by nolimits4web** [comment]
You have to enable `domCache` for the main View to keep the index page in DOM because as i see you fill its content with JavaScript. Or fill it using pageInit event http://framework7.io/docs/page-callbacks.html#callbacks-for-inital-pages
