### ISSUE TITLE
Feature Request: Table View

### ISSUE THREAD

**Issue by valnub** [nolimits4web/Framework7#1207]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

------------------

Can we have something like this? https://marcosmoura.github.io/vue-material/#/components/table
Multi-column sort feature would be really nifty.

![tablet view](https://cloud.githubusercontent.com/assets/3787662/20319104/2fdb6ca0-ab6d-11e6-9556-f4953d845a43.jpg)

**Comment by J05HI** [comment]
Yeah please include this! 
We all need tables

**Comment by ZanderBrown** [comment]
Tried to find some existing examples

Instead i found this:
https://developer.apple.com/ios/human-interface-guidelines/ui-views/tables/

Which seems to show Tables as being what we would call a list

**Comment by 7aduta** [comment]
+1

**Comment by krosoftware** [comment]
+10

**Comment by ZanderBrown** [comment]
Question is what within the iOS theme would it look like

**Comment by krosoftware** [comment]
Any news regarding that? I saw it is under development, do you (development) have any additional info?
Thank you.

**Comment by ZanderBrown** [comment]
U

**Comment by ZanderBrown** [comment]
Unless you

**Comment by ZanderBrown** [comment]
Speaking of which it would be good to get @nolimits4web 's perspective

**Comment by krosoftware** [comment]
@ZanderBrown , I saw it is under development, here: https://trello.com/b/AuvkBFfx/framework7-roadmap

**Comment by nolimits4web** [comment]
Added by commit 45004e1cdf2ddfd739e249412d5b79c45fcdf9bd

**Comment by J05HI** [comment]
Wow great @nolimits4web

**Comment by krosoftware** [comment]
@nolimits4web, you are the man. You can count on $100 donation for this 👍

**Comment by krosoftware** [comment]
Hello
any idea when it can be released, please?

**Comment by ZanderBrown** [comment]
See #1439
