### ISSUE TITLE
CSS class "not-empty-state" not being added or not being removed

### ISSUE THREAD

**Issue by alexandrubau** [nolimits4web/Framework7#1210]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.0
* Platform and Target: Phonegap, Android
* Live Link or JSFiddle/Codepen: https://jsfiddle.net/ga3vtc0n/

### What you did
I've tried to set some fields programatically. Using jQuery's `val()` method and also Framework7's `formFromData()` method.

### Expected Behavior
The class "not-empty-state" should be added or removed depending of the contents of the field.

### Actual Behavior
The class "not-empty-state" is not being added or removed accordingly.

**Comment by nolimits4web** [comment]
F7 can't really track such programmatic changes, just call `.trigger('change')` to trigger "change" event on such inputs and it will be removed
