### ISSUE TITLE
No documentation for swipeoutActionsNoFold

### ISSUE THREAD

**Issue by isiah-lloyd** [nolimits4web/Framework7#1211]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: Framework7 1.4.2
* Platform and Target: N/A
* Live Link or JSFiddle/Codepen: N/A

### What you did
There is a default app parameter located in `framework7.js` 

### Expected Behavior
For their to be explanation of what this parameter does on [this page](http://framework7.io/docs/init-app.html) or in a comment.

### Actual Behavior
There is no explanation for this parameter as I can see anywhere.

**Comment by isiah-lloyd** [comment]
This is also relevant for the version 1.5.0

**Comment by tobya** [comment]
Perhaps you could link to the line in framework7.js

**Comment by isiah-lloyd** [comment]
[Link to line](https://github.com/nolimits4web/Framework7/blob/f05d4417f2f8e3299419baa567ab4bea8c2c72a2/dist/js/framework7.js#L85)

**Comment by nolimits4web** [comment]
There is no documentation because it is not yet realised. Will be documented as soon as it will be ready and released
