### ISSUE TITLE
reloading/refresh Inline page(service) cached goes to back to index page

### ISSUE THREAD

**Issue by ebencosoft** [nolimits4web/Framework7#1212]
Hi, I have index.html(master view) that contains all pages in one file. when i load page(data-page='service') with json object or template7 data…it works fine and is able to make data-page='service' active but when the page(data-page='service') is reloaded/refresh........all the template7/localstorage/json is lost…then i notice that whenever you load inline page cached(data-page='service') and is reload/refresh…it goes to index page and make it active rather than the current service page which you are try to refresh...even though pushstate is enable......

**Comment by nolimits4web** [comment]
There is no sense to load inline page with template7/data options, it won't work. Pick something one. If you want to choose inline page then fill its content with template7 templates/data manually using, e.g., pageInit/Reinit events
