### ISSUE TITLE
signInWithPopup and signInWithRedirect not working with f7 & firebase on iOS

### ISSUE THREAD

**Issue by hhkweku** [nolimits4web/Framework7#1213]
With or without cordova inappbrowser I cannot seem to get firebase social auth working on iOS. Both popup and redirect work in the web browser though. I know this may not be an F7 issue but I would deeply appreciate it if something could be done from F7.
Please work your jutsu for me. Thanks.

**Comment by nolimits4web** [comment]
From a quick search I believe it is Firebase limitation http://stackoverflow.com/questions/37522541/firebase-auth-with-signinwithpopup-not-working-on-mobile-device https://firebase.googleblog.com/2016/07/firebase-react-native.html

**Comment by hhkweku** [comment]
I found a workaround; cordova-plugin-googleplus works with inappbrowser. Problem fixed. Thanks
