### ISSUE TITLE
back when using content

### ISSUE THREAD

**Issue by lroal** [nolimits4web/Framework7#1215]
This is a (multiple allowed):
* [x] bug
* Framework7 Version: 1.5.0.
* Platform and Target: chrome on linux.

I am using the router to load plain dom content (not using Templates, not using html pages). The back button does not work when going back more than one step.
What I do:
router.load({content: someDom});
...//in the next view:
router.load({content: someOtherDom});
..//pressing back first time works fine
..//pressing back one more time does nothing

**Comment by lroal** [comment]
I can see the problem is caused by only two pages are kept in history.
How can I overcome this limitation without manipulating the div containing the history ?

**Comment by nolimits4web** [comment]
Can you provide some live example or Fiddle/Codepen with the issue?

**Comment by lroal** [comment]
https://jsfiddle.net/lroal/1Lgvpm4f/28/

Her is the fiddle. Entering Trondheim KlatreSenter and back works fine.
Entering Trondheim Klatresenter - Sector A - back -back , does not work.

**Comment by lroal** [comment]
It seems to be a timeout in the cache. If you click quite fast back - it will work. 
But if you wait for a while, you will not be able to go back to first page.

**Comment by nolimits4web** [comment]
Ok, found out the problem. When you on the third page, the first (index) page is being removed from history and from dom. And you when you go back from 3 to 2 page, F7 will try to load this page using Ajax request. It won't and doesn't work in JSFiddle, so it can't load first page and can't back to it. In this case, if you have something similar with not working XHR request in your environment just enable `domCache: true` View's property to keep actual previous page in DOM

**Comment by lroal** [comment]
Thank you !
I have updated the fiddle with domCache: true on every view.
It works as expected.
An impressive framework by the way :)
