### ISSUE TITLE
Page content is flickering if page height is changed via accordion

### ISSUE THREAD

**Issue by astaffen** [nolimits4web/Framework7#1225]
* [x] bug

* Framework7 Version: 1.5.0
* Platform: iOS

If a scrollable page content gets non-scrollable via a closed accordion, the whole page content disappears for a moment and then appears again. Not always, but most of the time.
This behaviour is only appearing on iOS, I tested Android and browser without any issues.
<img src="http://i.imgur.com/3F9gzAt.gif" height="400">

**Comment by hessius** [comment]
I have also noted this, works fine on safari on mac os, but iOS is struggling

**Comment by hessius** [comment]
Adding these lines of css forcing HW acceleration improves flickering but unfortunately really lowers frame rate of animations

**Comment by hessius** [comment]
I’ve now tried every HW-forcing css trick I can find but can’t get rid of this behaviour; Almost only present on closing accordion and this seems to be some sort of issue with the DOM resizing to a smaller size?

**Comment by ZanderBrown** [comment]
As it's intermittent and only occurring in Safari i'm thinking it's a WebKit bug

**Comment by hessius** [comment]
For reference: this does not occur when wrapped in a Cordova app using wkwebview
