### ISSUE TITLE
autocomplete in navbar not working

### ISSUE THREAD

**Issue by peon501** [nolimits4web/Framework7#1226]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did
I tryed to use autocomplete in navbar but i need it there. I need dropdown from ajax for navbar search

### Expected Behavior
Thinked It will work in navbar.

### Actual Behavior
Not working in navbar. Iam getting errors.
in page content everything works well. 
Any Ideas how to slove it ?

**Comment by ZanderBrown** [comment]
Can you explain in more detail and provide code

**Comment by peon501** [comment]
nah. I made buggy work around, but that should be checked.

**Comment by peon501** [comment]
nah. still have this bug https://cloud.githubusercontent.com/assets/1125765/25792274/45c9df8a-33ce-11e7-98f5-29a8313140d9.png

just i cant use in navbar for some reason. only works in page-content

**Comment by ZanderBrown** [comment]
Define 'in navber'?

**Comment by peon501** [comment]
![image](https://cloud.githubusercontent.com/assets/1125765/25838266/f45c810c-349a-11e7-999e-f05b8d9fecf7.png)
![image](https://cloud.githubusercontent.com/assets/1125765/25838280/07238a10-349b-11e7-895d-82f61bca0f48.png)
![image](https://cloud.githubusercontent.com/assets/1125765/25838337/3fce7ce4-349b-11e7-9644-623c4e079934.png)

**Comment by peon501** [comment]
![image](https://cloud.githubusercontent.com/assets/1125765/25838480/01555b6c-349c-11e7-991e-ccd7a20bc13b.png)
works only in page-content

**Comment by ZanderBrown** [comment]
Non standard behaviour for iOS/Android and unsupported in F7 (positioning is relative the `page-content`)

**Comment by nolimits4web** [comment]
Fixed in v2
