### ISSUE TITLE
Navbar title loses center position after change of left/right navbar element content

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7#1227]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: Based on the given base JSFiddle
* Platform and Target: Google Chrome, Win7
* Live Link or JSFiddle/Codepen: https://jsfiddle.net/c9z0u2vp/1/

### What you did
Add content to **navbar-inner / left** after two seconds with status change of Vue JS element.

### Expected Behavior
**Center** stays centered

### Actual Behavior
**Center** goes some pixel to the right

**Comment by nolimits4web** [comment]
call `sizeNavbars` method after you change its content http://framework7.io/docs/navbar.html#related-app-and-view-methods

**Comment by scriptPilot** [comment]
Thank you, that was the solution! :-)
