### ISSUE TITLE
Feature Request: iNoBounce in-built

### ISSUE THREAD

**Issue by JosephShenton** [nolimits4web/Framework7#1229]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

### New Feature Idea
So my idea is to add iNoBounce as a deafult in framework7 so that way we don't have to manually add it because that can be a big pain.

**Comment by JosephShenton** [comment]
Anyone like this idea?

**Comment by J05HI** [comment]
+1

**Comment by ZanderBrown** [comment]
This has been suggested sooo many times

**Comment by scriptPilot** [comment]
Is part of [Framework7-Vue-Firebase](https://github.com/scriptPilot/framework7-vue-firebase)
