### ISSUE TITLE
Show panel on swipe option also affects split view on tablet

### ISSUE THREAD

**Issue by cyberbeat** [nolimits4web/Framework7#1231]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5
* Platform and Target: Android

### What you did
- As a base take the "Split View Application With Degradation To Panel" Layout from here: https://framework7.io/examples/
- Activate "swipePanel: 'left'" option

### Expected Behavior
The swipe option should not have any effect, when both panels fit onto the screen.

### Actual Behavior
On a big screen, the left panel swipe in is active, although the left panel is already displayed, with the effect, that the main panel is greyed out

**Comment by nolimits4web** [comment]
Fixed in https://github.com/nolimits4web/Framework7/commit/467e860ed6499c30d4d65caa6b49c812dc5f92aa
