### ISSUE TITLE
Bug: Framework7.io domain expired

### ISSUE THREAD

**Issue by hessius** [nolimits4web/Framework7#1232]
You probably know this but the framework7.io domain has expired and as far as I can see I this does not seem to be planned, it’s even up for sale by godaddy…

**Comment by modemlooper** [comment]
Derp.

**Comment by wiewioraseb** [comment]
Is anyone in possession of framework7's offline documentation and is willing to provide it here? I can't reach this subpage from google web cache.

**Comment by peter279k** [comment]
I have the same issue....

**Comment by slanska** [comment]
As a temporary solution, until Vladimir resolves domain registration issue, you can access content of entire Framework7 website (including documentation) at: https://github.com/nolimits4web/Framework7-Website/. Documentation is at: https://github.com/nolimits4web/Framework7-Website/tree/master/docs

**Comment by peter279k** [comment]
The domain seems to be fixed. The issue can be closed.

**Comment by ZanderBrown** [comment]
still some issues loading resources

**Comment by hessius** [comment]
@ZanderBrown link?

**Comment by nolimits4web** [comment]
Guys, do you still have issues with assets on website?

**Comment by GuillaumeBiton** [comment]
No.

**Comment by peter279k** [comment]
The website is normally worked for me now.

**Comment by ZanderBrown** [comment]
Seems resolved. not sure what happened
