### ISSUE TITLE
Dark Keyboard, As some apps have.

### ISSUE THREAD

**Issue by JosephShenton** [nolimits4web/Framework7#1236]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

So I have seen in many apps including safari a dark keyboard, and no matter how hard i try i can never find out how it works i have seen websites do it in safari on ios, but i can never figure out how to do it, So if Framework7 could have a dark keyboard or even a custom keyboard for it that would be amazing! Also i have looked up if it is possible to have a custom keyboard on ios safari it is, it just takes a lot of javascript, css and html so yeah. I hope this actually becomes a feature or a plugin!

**Comment by ZanderBrown** [comment]
I'm going to say this is massively out of scope. However plugins/PRs are welcome.
