### ISSUE TITLE
Back Page Error

### ISSUE THREAD

**Issue by xiefangzhenz** [nolimits4web/Framework7#1239]
I have three pages, one.html(index), two.html, three.html.

When one.html > two.html ,back nav is good.
 But one.html > two.html >three.html , three.html > two.html, two.html execute pageInit,but this function is belong to the first page(this issues show in PC).Besides,when I refresh two.html,will show one.html then skip to two.html. 
three.html > two.html is good,two.html  >one.html show error,one.html have no data,the data is load from ajax.(this issues show in  phone)

My English is not good,think all can understand my think,Thanks.

**Comment by ZanderBrown** [comment]
I believe this is a misunderstanding of the router.

As a future note it can often be better to submit issues in your native language, that way you can confidently add details and leave us to use Google Translate or our own Multilingual skills to read it
