### ISSUE TITLE
photoBrowser "close()" method and "onOpen()" callback don't work  if photoBrowser.type is 'page'

### ISSUE THREAD

**Issue by sepehrr** [nolimits4web/Framework7#1243]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5 
* Platform and Target: even in Browser

if `photoBrowser` object `type` parameter is set to 'standalone' everything is fine but when type is set to 'page', "close()" method and "onOpen()" callback don't work.

**Comment by valnub** [comment]
Well, it does make sense because pages do not trigger these events

**Comment by sepehrr** [comment]
You're right but It would be appreciated if this is stated in docs.
