### ISSUE TITLE
Add data-device for especific classes for especific devices

### ISSUE THREAD

**Issue by rafael-franca** [nolimits4web/Framework7#1247]
This is a (multiple allowed):
* [x] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: 1.5.0
* Platform and Target: All platforms

### What you did
Add data-device for especific classes for especific devices, for more customizable interfaces

For exemple:
```
<div class="list-block">
<a href="#" class="button button-big color-blue login-btn"  data-ipad="col-50">Log in</a>
<a href="#" class="button button-big color-blue cancel-btn"  data-ipad="col-50">Cancel</a>
</div>

```

Other exemple:
```
<div class="list-block">
<a href="#" class="button button-big color-blue login-btn"  data-ipad="col-33" data-android="col-50" data-iphone="col-50">Log in</a>
<a href="#" class="button button-big color-blue signin-btn"  data-ipad="col-33" data-android="col-50" data-iphone="col-50">Sign in</a>
<a href="#" class="button button-big color-blue cancel-btn"  data-ipad="col-33">Cancel</a>
</div>
```

### Expected Behavior
Allow to use some classes of components for specific devices. For example: if you run an app on an iPad, show it one way add one class, if on an iPhone, another way with another class, and so on.

### Actual Behavior
Currently it is very limited to create a custom interface.

**Comment by ZanderBrown** [comment]
Ok so you seem to be assuming all android devices are phones, there not.

So the result seems to be that you want a different widths for phones & tablets. This is already doable. Along with the `col-*` classes there are `tablet-*` classes that override the `col=*` classes on bigger screens

For example `col-100 tablet-50` is 100% on phones but 50% on tablets
