### ISSUE TITLE
parseUrlQuery can't use after the version update

### ISSUE THREAD

**Issue by hwygy001** [nolimits4web/Framework7#1248]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion 

* Framework7 Version: version 1.5
### Issue
After i update the new version framework7, i can't get my param when i set pushstate true.
such url **'http://127.0.0.1:8080/#/views/car-choice.html?loaddingMore=0'** will only get the {}.
and i find it caused by a merge  76d768c .

**Comment by hwygy001** [comment]
$.parseUrlQuery= function (searchStr, name) {
    var qObj = {};
    var searchStr = searchStr || location.href;
    searchStr = searchStr.indexOf('?')>-1 ? searchStr.replace(/\S*\?/,'') : '';
    if (searchStr) {
        var params = searchStr.split('&'),
            length = params.length, a;

        for (var i = 0; i < length; i++) {
            a = params[i].replace(/#\S+/g,'').split('=');
            qObj[decodeURIComponent(a[0])] = decodeURIComponent(a[1] || '');
        }
    }
    return name ? qObj[name] : qObj;
}

**Comment by nolimits4web** [comment]
Because in this case your query is part of the location hash not of the query. You can use `$$.parseUrlQuery('http://127.0.0.1:8080/#/views/car-choice.html?loaddingMore=0'.split('#')[1])` in such case
