### ISSUE TITLE
Icon (font) size depending on position

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7#1251]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

Framework7-Icons could be used in lists, on buttons, in text blocks ... but the size is currently always the same, to be adjusted with font-size or size property in Framework7-vue. I would appreciate if there are given font-sizes for the most used icon positions, so that the `<i>` elements are sized properly by default :-)

**Comment by valnub** [comment]
I think it's in the hand of devs to pick the right font-size for these icons. How is F7 supposed to know the right font size?

**Comment by scriptPilot** [comment]
Depending on the icon font and the position (list media, buttons, text inline) there is a font range so that icons looks great. That could be defined as default, so that everything looks fine, even if the developer didn't define the font size additionally.
