### ISSUE TITLE
Messages layout broke after adding new message

### ISSUE THREAD

**Issue by tinyCoder32** [nolimits4web/Framework7#1257]
![untitled](https://cloud.githubusercontent.com/assets/17817239/21456384/61742302-c930-11e6-9930-cc372803bbc3.gif)

The messages layout collapse after adding new message, im just using the standard example, i even tried `myMessages.layout()` after adding the message but it didn't work.

It was working fine before upgrading to 1.5.2.

Anything i should fix?

**Comment by nolimits4web** [comment]
Do you have live example? Looks like something wrong with messages layout HTML as i can't really replicate it

**Comment by tinyCoder32** [comment]
Thank you, i expected that, but here is my HTML layout:

```
<div class="messages">
		<div class="messages-date">
			December 17, 2016
		</div>
		<div class="message message-sent message-sent">
			<div class="message-text">
				jugdr ugn
			</div>
		</div>
		<div class="message message-sent message-with-avatar message-received">
			<div class="message-name">
				Elbruz
			</div>
			<div class="message-text">
				jjhjg hg gf ff
			</div>
			<div class="message-avatar" style="background-image:url(http://xxx.com/wp-content/plugins/wp-first-letter-avatar/images/default/48/latin_e.png)"></div>
		</div>
		<div class="message message-sent message-with-avatar message-received">
			<div class="message-name">
				Elbruz
			</div>
			<div class="message-text">
				jjjj
			</div>
			<div class="message-avatar" style="background-image:url(http://xxx.com/wp-content/plugins/wp-first-letter-avatar/images/default/48/latin_e.png)"></div>
		</div>
		<div class="message message-sent message-sent">
			<div class="message-text">
				kkkk
			</div>
		</div>
		<div class="message message-sent message-sent">
			<div class="message-text">
				yyyy
			</div>
		</div>
		<div class="messages-date">
			December 23, 2016
		</div>
		<div class="message message-sent message-sent">
			<div class="message-text">
				test message
			</div>
		</div>
	</div>
```

Am I missing something?

**Comment by tinyCoder32** [comment]
Same problem on your example in the Documentation Vladimire:

![screen shot 2016-12-27 at 6 18 23 pm](https://cloud.githubusercontent.com/assets/17817239/21502456/8e3d9654-cc58-11e6-825a-d692d906ef78.png)

Look at Kate's message.

**Comment by tinyCoder32** [comment]
This is what is causing the problem for me:

```
.messages-auto-layout .message-avatar {
    opacity: 0;
}

.messages-auto-layout .message-label, .messages-auto-layout .message-name {
    display: none;
}
```

These classes are added when I add a new message, and causing the avatar and sender name to get hidden!

**Comment by nolimits4web** [comment]
Sorry, so everything is fine now?

**Comment by tinyCoder32** [comment]
No, I don't know why the class `.messages-auto-layout` is being added to the dom every time I add a new message.

I'm still stuck with this issue.

**Comment by nolimits4web** [comment]
If you don't need auto layout then just disable it by passing `autoLayout: false` on messages initialization http://framework7.io/docs/messages.html#messages-parameters

**Comment by tinyCoder32** [comment]
OK, that solved my problem. Thank you Vladimir, great job you are doing there man.
Good luck.
