### ISSUE TITLE
Standalone Autocomplete should give users the option of entering custom values

### ISSUE THREAD

**Issue by seme1** [nolimits4web/Framework7#1258]
This is a (multiple allowed):
* [] bug
* [X] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v1.5.2.
* Platform and Target: IOS and Android.

When the user types in the standalone autocomplete and nothing is found, there should be an option to enable the user to continue and return to the previous page with the custom text he typed. Currently, only the cancel/back buttons are visible. Optimally, there should be a third button to allow "continue with entered text" option.

The above behavior does not occur with the simple dropdown autocomplete as users are allowed to enter custom values and the dropdown list appears only when matches are found. If no matches are found, the user can continue with the next field in the same page without losing whatever he/she wrote in the autocomplete field.

**Comment by nolimits4web** [comment]
In the default example you can just return query value to the render function if nothing is found:
```js

for (var i = 0; i < fruits.length; i++) {
    if (fruits[i].toLowerCase().indexOf(query.toLowerCase()) >= 0) results.push(fruits[i]);
}

// Add query to the results and it will be selectable
if (results.length === 0) results = [query];


render(results);
