### ISSUE TITLE
Disable highlighting matched characters in dropdown autocomplete

### ISSUE THREAD

**Issue by seme1** [nolimits4web/Framework7#1259]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.2.
* Platform and Target: Android AND ios

The issue is that in the autocomplete dropdown menu, when a user starts typing a character at time, Framework7 automatically *highlights* the matched character in the dropdown autocomplete menu by adding the bold HTML attribute (i.e. <b>Ap</b>) to the matched character in all the words of the dropdown menu.  This is problematic as words in languages where letters are connected seem to be broken since the shape of the character changes when it is part of a word. 

To solve the above, it would be nice to add an option to Autocomplete for disabling the above behavior.

**Comment by seme1** [comment]
The above explained behavior occurs on both IOS and Android. It would be very much appreciated if a fast solution can be proposed to resolve the issue.

**Comment by nolimits4web** [comment]
Added `highlightMatches` option which is enabled by default
