### ISSUE TITLE
Bug in Autocomplete When certain characters are inserted (try  ] or [)

### ISSUE THREAD

**Issue by seme1** [nolimits4web/Framework7#1260]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v1.5.2.
* Platform and Target: Android and IOS.

If you try to input only a single character such as ] in the input field of autocomplete, an error will occur (console shows the error below).

 `Uncaught SyntaxError: Invalid regular expression: /([)/: Unterminated character class
at new RegExp (<anonymous>)
    at framework7.js:8987
    at Object.source (autocomplete.html:152)
    at HTMLInputElement.a (framework7.js:8982)`

This issue is probably related to https://github.com/nolimits4web/Framework7/issues/1259 
Framework7 attempts to highlight the inputted characters in all the items of the autocomplete dropdown menu items. Certain characters cause an issue with regex expression used for highlighting. 

It would be nice to give the users the option of disabling the highlighting altogether as it is really useless in certain languages where characters take different shapes when they are inside words than when they are outside.

**Comment by ZanderBrown** [comment]
looks like it needs to be escaped

**Comment by seme1** [comment]
True. However, giving the option of avoiding regex expressions and disabling characters highlighting would be a nice option, too.

**Comment by ZanderBrown** [comment]
i believe such a feature was merged in yesterday

**Comment by seme1** [comment]
That's great. However, the regex line causing the error reported in this issue is still being executed even when highlightMatches is set to false. It would be nice to have Framework7 escape the string or avoids the declaration of the following line when highlightMatches is set to false. 

`var regExp = new RegExp('('+query+')', 'i');`
