### ISSUE TITLE
Panel problem when click back button on device

### ISSUE THREAD

**Issue by atukilham** [nolimits4web/Framework7#1264]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

I have a problem with panel.
When i open panel, and click back button on device, panel not closed and page was back to previous page.
How to make it just close panel without go to back page.
I was tried with check the body'class in pageBack events, if the body have class `.with-panel-left-cover`, close the panel and it's work.
But my problem, the page also turn back to previous page.

Help me please..

**Comment by valnub** [comment]
Hi, can you post a working example on Codepen? Thanks

**Comment by ZanderBrown** [comment]
Probably related to #150

**Comment by valnub** [comment]
> I was tried with check the body'class in pageBack events, if the body have class .with-panel-left-cover, close the panel and it's work.
> But my problem, the page also turn back to previous page.

Did you try `event.preventDefault()` ?

**Comment by atukilham** [comment]
@valnub , thanks for reply.
I think my problem same with [#150](https://github.com/nolimits4web/Framework7/issues/150) like @ZanderBrown said.

I use `pushState:true`,
the problem just with page back clicked on browser or back button on android device, not the framework back button when panel show. I think modal datepicker have same problem like this.

Where i must use `event.preventDefault()`, can give me an example?

**Comment by valnub** [comment]
Oh, I see you mean the back button of the Android device. I thought you might be able to put that code into the click event listener of Framework7's back button.

Hm, to be honest I don't know how to do this. You'll probably have to mess around with `popstate` event.

**Comment by Deep18** [comment]
@atukilham 
This is how i did it.
First of all add an id to the left panel div like this
`<div id="left_panel" class="panel panel-left panel-cover sidebar">`
add an eventlisterner on back button and check for the active class with hasClass function on the listerner.

```
document.addEventListener("backbutton", onBackKeyDown, false); 

function onBackKeyDown() { 
	
	 if ($$('#left_panel').hasClass( "active" )) 
		{ myApp.closePanel(); 
			return false; 
			} 
			
	else { 
		mainView.router.back();
		} 
		
	return true; 
}
```

**Comment by valnub** [comment]
Awesome, thanks for posting your solution!
