### ISSUE TITLE
Incorrect paths in kitchen-sink-material/index.html

### ISSUE THREAD

**Issue by tasaduq** [nolimits4web/Framework7#1265]
The paths given in above mentioned file is trying to load dependencies from /build/ where is the folder is name as dist.

I don't understand why this hasn't been fixed, its annoying everytime I download I have to rename this myself.

**Comment by ZanderBrown** [comment]
because if you use gulp and build it yourself `build` will exist

**Comment by nolimits4web** [comment]
It also says:

> Framework7' JS and CSS files in Kitchen Sink are temporary linked to build/ to make development process easier on this stage. So to make it work you need to build Framework7 (see Build section) or to re-link JS and CSS files to dist/ folder
