### ISSUE TITLE
picker.displayValue always [] before layout called

### ISSUE THREAD

**Issue by yexing** [nolimits4web/Framework7#1266]
in picker.js line 86
`        for (var i = 0; i < p.cols.length; i++) {
`
Because p.cols.length is 0 before layout() called.  p.displayValue is set to [] always(line 96)

**Comment by yexing** [comment]
a temporary solution

''''javascript
                if (p.cols.length === 0) {
                    for (var i = 0; i < p.params.cols.length; i++) {
                        if (p.params.cols[i].displayValues != undefined)
                            newDisplayValue.push(p.params.cols[i].displayValues[newValue[i]]);
                        else
                            newDisplayValue.push(newValue[i]);
                    }
                } else {
                    for (var i = 0; i < p.cols.length; i++) {
                        if (!p.cols[i].divider) {
                            newValue.push(p.cols[i].value);
                            newDisplayValue.push(p.cols[i].displayValue);
                        }
                    }
                }
''''

**Comment by valnub** [comment]
Why not open a PR? :-) https://help.github.com/articles/about-pull-requests/

**Comment by jmarceli** [comment]
Hi I think that there is a bug in cbcdea4, I made a PR with a fix.

**Comment by MiguelQueiroz** [comment]
Or maybe allow us to reset the picker value. By allowing to make setValue(null) or false, and that would also empty the input. Because right now this is not possible to reset the picker, and show the default placeholder...
