### ISSUE TITLE
API to close speed-dial floating action button

### ISSUE THREAD

**Issue by blackholegalaxy** [nolimits4web/Framework7#1269]
This is a:
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.2, Material Theme (will use material for both iOS and Android)
* Platform and Target: Cordova, iOS, Android

### What you did
In our app, on the third tab, we have a floating action button in speed-dial mode. With three speed dials. On of this spee-dial triggers a myApp.confirm which redirects via javascript to another app tab: `myApp.showTab('#tab1');`.

### Actual Behavior
The fact is, after being redirected on the tab1, if i go back to tab3, I can see the speed-dial is still "open" with all dials visible.

### Expected Behavior
I was expecting the speed-dial to trigger a "close" state/action on redirecting to other tab.

### My Question / Ask for feature
For the speed-dial, can we access the API and, after redirecting my user, call something like 
```
myApp.speedDialClose(idOfSpeedDialDiv);
```
or using Dom7
```
$$('idOfSpeedDialDiv').close();
```

**Comment by nolimits4web** [comment]
At the moment it is made by just adding/removing class. So you can close it like:
```
$$('.speed-dial.speed-dial-opened').removeClass('speed-dial-opened');

**Comment by valnub** [comment]
@blackholegalaxy Does this fix the issue for you? Can it be closed?

**Comment by blackholegalaxy** [comment]
Yes it works. Sorry about response delay.
