### ISSUE TITLE
Material white color theme unusable by default (uses white font so text/icons are invisible)

### ISSUE THREAD

**Issue by pshendry** [nolimits4web/Framework7#1273]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.2
* Platform and Target: Any
* Live Link or JSFiddle/Codepen: Select the white theme in the [Framework7 Documentation](https://framework7.io/docs/color-themes.html#material-theme-colors)
### What you did
Use the `theme-white` material color theme.

### Expected Behavior
The font colour of items which are given the themed white background should change to a suitable dark grey / black.

### Actual Behavior
The font colour for these items is white, so no text or icons are visible in navbars etc.

**Comment by centrual** [comment]
[In docs](https://framework7.io/docs/color-themes.html#material-theme-colors) Vladimir wrote:
``` bash
Framework7 also has 2 additional layout themes: "white" (iOS theme only) and "dark".

To apply layout theme we need to add layout-[theme] class to the required parent element.
It could be body, view, page, navbar, toolbar, list-block, etc.
```

So white theme for ios currently. I wrote just for info.

**Comment by valnub** [comment]
Yes, white theme does not work in Material Design. See duplicate here https://github.com/nolimits4web/Framework7/issues/1103
