### ISSUE TITLE
Material action button on the left of the screen

### ISSUE THREAD

**Issue by blackholegalaxy** [nolimits4web/Framework7#1274]
## Subject
- [ ] Bug
- [x] Question

## Question

Is there any way to add another action button on the left of the screen in material theme? We need two actions buttons: one on the right, another on the left.

**Comment by nolimits4web** [comment]
Just add some custom style:
```html
<!-- Default right button -->
<a href="#" class="floating-button color-pink"><i class="icon icon-plus"></i></a>
<!-- Left button -->
<a href="#" style="left:16px; right: auto" class="floating-button color-pink"><i class="icon icon-plus"></i></a>

**Comment by blackholegalaxy** [comment]
Thanks, I really thought it could have a hidden super css class. Thanks.
