### ISSUE TITLE
router didn't load file

### ISSUE THREAD

**Issue by beli3ver** [nolimits4web/Framework7#1276]
Hello,

I have this setup here:

https://gist.github.com/beli3ver/438c14e92f57881933c612717c6612c6

When I click on the 3 tab, I want that the file about.html ist loading, but nothing happends.
Could you maybe help me?

**Comment by ZanderBrown** [comment]
Are you loading it though a server or direct from the file system?

**Comment by beli3ver** [comment]
Filesystem

**Comment by ZanderBrown** [comment]
Because F7 uses Ajax to load pages you must be running through a server.

Personally I use https://www.npmjs.com/package/http-server

**Comment by valnub** [comment]
Yes, don't just doubleclick the html file as it will serve your app via `file:///`. Instead, you have to use `http`
