### ISSUE TITLE
panel:close bug

### ISSUE THREAD

**Issue by bigbossmaher** [nolimits4web/Framework7#1279]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.2
* Platform and Target: intel xdk : cordova
* Live Link or JSFiddle/Codepen: https://codepen.io/anon/pen/ZLWePg

### What you did
i added those lines 
$$('.panel-right').on('panel:close', function () {
    myApp.alert('Left panel is closing!');
});

### Expected Behavior
i should have an alert when the panel is closed

### Actual Behavior
i have not recieve any alert

**Comment by bigbossmaher** [comment]
is no one here to answer ?

**Comment by centrual** [comment]
I'll try soon. please check 1 hour later.

**Comment by centrual** [comment]
just write 'closed' for 'panel:close',
i think panel:close is action, 'panel:closed' is event. 'closed' is fits better.

**Comment by nolimits4web** [comment]
@bigbossmaher i see you use 1.4.2 in your codepen. Such event supported since v1.5.0
