### ISSUE TITLE
append() bug

### ISSUE THREAD

**Issue by henrymidio** [nolimits4web/Framework7#1280]
append() function not work with multiple values in the custom jquery ($$)

**Comment by nolimits4web** [comment]
For example?

**Comment by henrymidio** [comment]
$(".skills").append(skill1, skill2, skill3, skill4, skill5);

In this case I had to use regular jquery because with $$ it wasn't working

**Comment by valnub** [comment]
Well, Dom7 offers just a very small subset of jQuery, so if you want all of jQuery's features, you have to import jQuery which should be no problem.

**Comment by valnub** [comment]
ok, the fix was rather simple, I just added another for loop, see https://github.com/nolimits4web/Framework7/pull/1307
