### ISSUE TITLE
Open and Close Picker Modal

### ISSUE THREAD

**Issue by 4blacktop** [nolimits4web/Framework7#1283]
This is a (multiple allowed):
* [x] bug

### What you did
На странице 
http://framework7.io/docs/picker-modal.html#open-and-close-picker-modal

В блоке
Open and Close Picker Modal From HTML

На экране "смартфона" справа при нажатии Close Picker, а потом Open Picker 
Picker открывается и тут же закрывается

### Expected Behavior
ИМХО Picker должен оставаться открытым

**Comment by nolimits4web** [comment]
Не получается повторить проблему. Он и остается открытым. Попробуйте почистить кэш и попробовать снова
