### ISSUE TITLE
Calendar onDayClick callback not called

### ISSUE THREAD

**Issue by tbcrowe** [nolimits4web/Framework7#1284]
This is a (multiple allowed):
* [x] bug
* [x] feature-discussion (RFC)

* Framework7 Version: 1.5.2
* Platform and Target: IOS (All platforms are affected)

### What you did
Create a standard date picker (single date, not multiple and not range). 

### Expected Behavior
onDayClick should be called when any day is clicked.

### Actual Behavior
onDayClick is not called when the day clicked is the currently selected day.

The problem is the following line in handleDayClick method:
`if (day.hasClass('picker-calendar-day-selected') && !(p.params.multiple || p.params.rangePicker)) return;`

I believe this code is present to prevent p.addValue from being called lower in the method, but it also prevents onDayClick from being called and prevents the closeOnSelect functionality from working in the case the user wants to re-select the already selected date.  I would contend that both behaviors are desirable when clicking the already selected date.

I propose removing the line above and adding a condition around the p.addValue call as such:
`if (!day.hasClass('picker-calendar-day-selected')) {
     p.addValue(new Date(dateYear, dateMonth, dateDay).getTime());
}`

**Comment by valnub** [comment]
You could send in a PR and reference this issue
