### ISSUE TITLE
swipePanel option conflicts with range-input slider

### ISSUE THREAD

**Issue by cyberbeat** [nolimits4web/Framework7#1285]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.0
* Platform and Target: Android

I use the framework7 option "swipePanel: 'left'" and also a form with range-input-elements (sliders). 

When I try to slide the range-input-slider to the right, it does not work, but instead the left-panel is swiped in.

The panel-swipe should not be triggered, when started on such an input element.

**Comment by valnub** [comment]
Hi, can you post a running example of the issue on codepen?

**Comment by cyberbeat** [comment]
https://codepen.io/anon/pen/jymbgR

Just try to slide the slider to the right

**Comment by ZanderBrown** [comment]
Can confirm.

The slider works as expected however the side panel is also opened

**Comment by valnub** [comment]
Yes, I can confirm this as well

**Comment by cyberbeat** [comment]
Great, thanks for the fix!
