### ISSUE TITLE
Use styles only?

### ISSUE THREAD

**Issue by jaredreich** [nolimits4web/Framework7#1290]
Great work, but how can Framework7 be used just for its styles? Looks like nothing really works without the javascript included.

**Comment by centrual** [comment]
It's complete framework and everything linked with each other. You can't use only styles i think and there is no purpose of it. If you want to use material UI, you can use [MUI](https://www.muicss.com/)

**Comment by ZanderBrown** [comment]
Could you elaborate on 'just for its styles' please?

**Comment by jaredreich** [comment]
By just for styles I mean just use the nice iOS styling that comes with it, none of the JS

**Comment by ZanderBrown** [comment]
That's still not completely clear.

Why don't you want the JS?
What do you mean nothing really works without JS?

**Comment by jaredreich** [comment]
Pages won't even display. The reason for not using the js might be because maybe I want to use a different framework like React.

**Comment by ZanderBrown** [comment]
F7 includes the option to use a custom router

**Comment by centrual** [comment]
@jaredreich framework7 has alpha react and released vue versions.
Vue version: https://github.com/nolimits4web/Framework7-Vue
React version: https://github.com/bencompton/framework7-react

and nothing more. Just don't use css without js. It's mobile template, you need to make js code for handle page transitions, history and lot of more things. so js is must.

**Comment by jaredreich** [comment]
Thanks all for the help
