### ISSUE TITLE
Indicator not showing on Chrome and Safari

### ISSUE THREAD

**Issue by tinyCoder32** [nolimits4web/Framework7#1293]
This is a (multiple allowed):
* [x] bug

Hi, I'm using:

```
$$(document).on('ajaxStart', function () {
    myApp.showIndicator();
});
$$(document).on('ajaxComplete', function () {
    myApp.showIndicator();
});
```
or using `myApp.showIndicator();` in other functions, it is working as expected on Firefox, but not on Safari and Chrome, I saw a guy reported the same thing here before but no solution.

FIREFOX:
![firefox](https://cloud.githubusercontent.com/assets/17817239/22002749/045b84f0-dc57-11e6-9c66-89129e200e4f.gif)

CHROME & SAFARI:
![chrome](https://cloud.githubusercontent.com/assets/17817239/22002784/4626e23a-dc57-11e6-88fb-ef591c3ecd76.gif)

I don't imagine what can be done wrong to cause this issue, because as you see it works just fine on Firefox, and i'm using a standard function on a simple page, "can't share a link in public, if there is a way to share in private I can do that".

Thanks.

**Comment by tinyCoder32** [comment]
It was a bug in my code, I have `async: false` in my ajax request which works on Firefox and returns immediately on other browsers and causes the indicator to get hidden immediately, don't know why but that's it.

**Comment by tinyCoder32** [comment]
This is the same issue this guy faces: http://stackoverflow.com/questions/26906172/loader-not-working-during-synchronous-ajax-call-in-chrome

**Comment by ZanderBrown** [comment]
can i just point out that it's not a good idea to use synchronous ajax because, well it's synchronous. This means all other page operations (inc rendering) will be blocked until the request has finished.

There is a reason ajax is asynchronous by default. Use it that way

**Comment by valnub** [comment]
I guess, this is rather a browser problem than a F7 issue?

Also, as Zander said, the whole point of ajax is asynchronousness (guess what the 'a' in ajax stands for :-) )
