### ISSUE TITLE
can't run javascript on dynamic page

### ISSUE THREAD

**Issue by bigbossmaher** [nolimits4web/Framework7#1295]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.2
* Platform and Target: cordova intel xdk
* Live Link or JSFiddle/Codepen: PREFERABLY : https://codepen.io/anon/pen/rjWKEN

### What you did
i want to run alert on an element in dynamic page

### Expected Behavior
i should see alert window with hello

### Actual Behavior
nothing happened

**Comment by ibrahimyilmaz7** [comment]
> Try this:

```
$$('body').on('click', '#here', function (e) {
  // 'right' position to open Right panel
  alert("hello");
});
```

**Comment by bigbossmaher** [comment]
yes it works , thank you veru much , i sent an email could you please answer me
