### ISSUE TITLE
[Feature request] Open panel/popup/login screen/tab without animation

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7#1298]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

To restore the state after application reload, I search for a way to open panel, popup, login screen or tab without any delay or animation after page initialization. Is there any proper way to do so?

I figured out the following solution for popup, but so far no solution for login screen and side panels. 

Popup: Manually, with `removeClass('modal-out')`, `addClass('modal-in')` and `css('display', 'block')`

Best way would be a parameter on `openPanel()`, `popup()` and `loginScreen()` functions.

Maybe there is already a good way?

**Comment by centrual** [comment]
I'll add this feature to https://github.com/nolimits4web/Framework7/pull/1282 soon...

**Comment by scriptPilot** [comment]
Perfect! Could you propose any workaround for now?

**Comment by scriptPilot** [comment]
**noAnimated** option would be fine as well for `showTab()`

**Comment by valnub** [comment]
centrual's PR got merged.

@scriptPilot Did this solve the issue for you?

**Comment by centrual** [comment]
@valnub I didn't added this features to modals currently. I will make this feature request as soon as possible.

**Comment by scriptPilot** [comment]
@valnub, @centrual I think not completely - the request was for everything what could be opened by script - so, on the list are for me:

- [ ] side panels
- [ ] popups
- [ ] login screens
- [ ] tabs
- [x] pages 

I have integrated it in the runtime restoration for my open source project **[App Framework](https://github.com/scriptPilot/app-framework)** ([see demo](http://app-framework.scriptpilot.de/)) - if you play there a little bit around, open for example a panel and reload the page, it will be restored, but with animation - I would like to do it without :-)

**Comment by scriptPilot** [comment]
Works fine, thank you Vladimir
