### ISSUE TITLE
[Bug] $$.each cannot break out of loop. DOM7

### ISSUE THREAD

**Issue by JohnRSim** [nolimits4web/Framework7#1305]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.2
* Platform and Target: CHROME WEB BROWSER, CORDOVA-CROSSWALK, ANDROID.
* Live Link or JSFiddle/Codepen: https://codepen.io/anon/pen/xgqpmj

### What you did
DOM7 $$.each does not match expected behavior - how do you break out of the each statement in DOM7?
in JQuery if you return false it will break out but in DOM7 if you return false; it acts like continue; and moves onto next item in array.

### Expected Behavior
expect $$.each to break out of loop when return false callback is hit.

### Actual Behavior
$$.each when it hits return false .each just continues to next item in array - example in code pen above.
Expected to hit 'test' in array and break out of loop but you can see if just continues with the other items in the array

**Comment by valnub** [comment]
Yes, looks like a bug to me. Very weird behavior of `$$.each`

**Comment by ZanderBrown** [comment]
jQuery implementation for reference https://api.jquery.com/each/
