### ISSUE TITLE
Material design, Tab bar, multiple views : default view slider not initialized 

### ISSUE THREAD

**Issue by Pingolus** [nolimits4web/Framework7#1309]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 1.5.2.
* Platform and Target: CORDOVA
* Live Link or JSFiddle/Codepen: https://jsfiddle.net/Nicolus/d0hreL06/

### What you did
Used framework7, material design, tab bar widget with one view per tab.

### Expected Behavior
Default view is correctly initialized.

### Actual Behavior
Default view seems not correctly initialized regards to the slider after page loading.

**Comment by ZanderBrown** [comment]
It works fine for me.

Do you want to be able to swipe between them? Set them up accordingly http://framework7.io/docs/tabs.html#swipeable-tabs

**Comment by Pingolus** [comment]
Hi,

No, what I mean is that slider is not correctly initialized, we have to click on "Tab 2" to see light blue slider bar.

Perhaps this is my fault, but I tried with the example code http://framework7.io/docs/tabs.html#switch-views-from-tab-bar-example and it's the same.

**Comment by Pingolus** [comment]
Up :) Can you confirm this is a bug ? Thanks

**Comment by ZanderBrown** [comment]
Ah i see it

**Comment by ZanderBrown** [comment]
Have you tried exploring http://framework7.io/kitchen-sink-material/ >Tabs > Static Tabs

**Comment by Pingolus** [comment]
Thanks for your reply. Hm, the idea is to use one view per tab.

I tried static tab code but there's no slider at all : https://jsfiddle.net/Nicolus/gnLjo914/

**Comment by pedropamn** [comment]
I have similar issue: I try:

`<div class="toolbar tabbar">
				<div class="toolbar-inner">
				  <a href="#tab1" class="tab-link active" style="width: 50%;">Tab 1</a>
				  <a href="#tab2" class="tab-link" style="width: 50%;">Tab 2</a>
				</div>
			  </div>

 
            
            <div class="page-content">
				<div class="tabs-swipeable-wrap">
				  
				  <div class="tabs">
					
					<div id="tab1" class="page-content tab active">
					  <div class="content-block">
						... Tab 1 content <a href="cidade.html">cidade</a> 
					  </div>
					</div>
					
					<div id="tab2" class="page-content tab">
					  <div class="content-block">
						... Tab 2 content ...
					  </div>
					</div>
				   </div>
				 </div>		
           </div>`

![image](https://cloud.githubusercontent.com/assets/19939247/22328983/40cc8186-e3a6-11e6-961a-24fda3d89777.png)

It's really a bug or i'm wrong in my code?

Thanks

**Comment by Pingolus** [comment]
To bypass what I supposed to be a bug, il simulate click on "tab2" then "tab1"... not a proper way but I found no other solutions : 

<a id = "tab1Link" href="#tab1" class="tab-link">
        <span class="tabbar-label">Tab1</span>
      </a>
<a id="tab2Link" href="#tab2" class="tab-link">
        <span class="tabbar-label">Tab2</span>
</a>

Dom7("#tab2Link").click();
Dom7("#tab1Link").click();
