### ISSUE TITLE
CSS not rendering Android 4.2

### ISSUE THREAD

**Issue by satyajit9830** [nolimits4web/Framework7#1310]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 1.5.2
* Platform and Target: Phonegap / Android 4.2

### What you did
Created a hybrid app template with framework7 and phonegap. Tested in my mobile phone which have android 4.2

### Expected Behavior
It should show my template

### Actual Behavior
No css is working. Buggy View. It is working perfectly in upper version (kitkat) of android

**Comment by sepehrr** [comment]
Try using crosswalk to support older android versions

**Comment by satyajit9830** [comment]
Used crosswalk but size of app is too large. Any alternative?

**Comment by sepehrr** [comment]
1. you can use crosswalk lite:
https://crosswalk-project.org/documentation/crosswalk_lite.html
2. If i'm not mistaken old android browser doesn't support some css rules and attributes properly, like `display: flex` which many of f7 css classes rely on it (for example `.row`). override them with some other line of codes to achieve what you want. This links may help you:
http://stackoverflow.com/questions/23745344/flexbox-on-android-stock-browser
http://stackoverflow.com/questions/16595587/webkit-flex-not-displaying-properly-on-android

**Comment by farskid** [comment]
If you search for support of `flexbox` in [caniuse.com](caniuse.com), It sais Android engine before 4.3 only support the old flexbox definition which is found [here](https://www.w3.org/TR/2009/WD-css3-flexbox-20090723/). A good solution would be to use tools like *AutoPrefixer* and set the settings to support all browsers versions and it would create CSS for older versions of android.

**Comment by nolimits4web** [comment]
F7 has old flexbox styles as well, but the problem as it can't be supported correctly for old devices. So yes, to get most of support use crosswalk
