### ISSUE TITLE
Dom manipulation on active tab on `tab:show` event

### ISSUE THREAD

**Issue by farskid** [nolimits4web/Framework7#1312]
This is a :
* [x] bug

* Framework7 Version: 1.5.0
* Platform and Target: Cordova

### What you did
Created a hybrid app using framework7 of version 1.5.0 and cordova  version 4.2+.
The applications contains of 4 tabs and each tab content has two containers called `.js-grid .js-grid-loose` and `.js-grid .js-grid-condensed`. I implemented a grid view toggle that toggles data list between loose and condensed views.

### Expected Behavior
When user clicks on toggle button, I save the view mode in localStorage. After that each tab being clicked, I find the relative tab content, remove `active` class from all `.js-grid` elements and add `active` class to the `.js-grid-${mode}` element inside the tab content container. Consider a case that user clicks toggle to change view mode to *loose* mode. After that he clicks on `recent-news` tab, the content is inside `#tab-recent-news`, It should remove active class from all `.js-grid` elements and add active class to `#tab-recent-news .js-grid-loose`. I'm using DOM7 and no jQuery!

### Actual Behavior
It seems that DOM7 removes active class from all `.js-grid` elements but can't add active class to the active tab on `tab:show` event. but when I wrap the dom manipulation function inside `setTimeout(function(){...}, 0)`, It works as expected!

I guess the actions are being implemented simultaneously so when DOM7 is busy working with tabs, can't do any dom manipulation in sync.

**Comment by nolimits4web** [comment]
Would be good to see code example of how you are doing it or live example (or JSFiddle/Codepen) with the issue

**Comment by farskid** [comment]
@nolimits4web  I'll try to create a fiddle for the case and permalink it here.

**Comment by ZanderBrown** [comment]
There hasn't been a response by the issues owner in 20 days.
This issue **will be closed in 7 days** if no further response is submitted
