### ISSUE TITLE
$$.get(url, data, success, error)

### ISSUE THREAD

**Issue by bigbossmaher** [nolimits4web/Framework7#1313]
i use the ParkingData variable to show some markers on the map.
    $$.get('http://autopost.besthost.tn/app/parking.php', function (data,xhr) {
  alert(xhr); 
        ParkingData=data;
  console.log('Load was performed');
});
this is not working

but when i write it manually it works
like this picture it works
![capture3](https://cloud.githubusercontent.com/assets/15154710/22187284/cd68e3f0-e103-11e6-8fd3-5f6e2c18dc7a.PNG)

**Comment by ZanderBrown** [comment]
try `getJSON`

**Comment by bigbossmaher** [comment]
getJSON will not work because it needs a json file as parametres ( i tried it )
$$.getJSON('items.json', function (data) {
  console.log(data);
});

i made some changes on server files that shows data by adding <br> after every line
now the data varible is showing the HTML elements.
how can i make the data variable get the content as it like what i writen manually  in the first picture

alert(data)
![capture](https://cloud.githubusercontent.com/assets/15154710/22200139/27910218-e15e-11e6-8918-d4e202b19141.PNG)

**Comment by ZanderBrown** [comment]
Your 'by hand' approach shows your creating a JavaScript object, the data your loading is (admittedly invalid) JSON.

`get` returns a string whereas `getJSON` returns an object.

How/where is the info from http://autopost.besthost.tn/app/parking.php coming from and what are you trying to do with it

**Comment by bigbossmaher** [comment]
the parking.php is importing data from database :
`<?php
$servername = "localhost";
$username = "xxx";
$password = "xxx";
$dbname = "axxxxx";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}
$conn->query('SET NAMES utf8');
$sql = "SELECT location_title, location_latitude, location_longitude FROM wp_map_locations";
$result = $conn->query($sql);
echo "[";
if ($result->num_rows > 0) {
    // output data of each row
    while($row = $result->fetch_assoc()) {
        echo "{'title':" ."'".$row["location_title"]."','position': new plugin.google.maps.LatLng(" . $row["location_latitude"]. "," . $row["location_longitude"]. "),'icon': 'www/icons/parking.png'},\r\n";
    }
} else {
    echo "0 results";
}
echo "]";
$conn->close();
?>`

**Comment by bigbossmaher** [comment]
all what i need is to extract data from database then grab it to the app in the ParkingData variable . and should be like like a json ( see first picture )

**Comment by ZanderBrown** [comment]
as the data is being returned as JSON instead of trying to form it as JSON put it in an array and look at PHP's `json_` functions

**Comment by bigbossmaher** [comment]
please can you please help me doing it , i'm not good in programming and also a lost a lot of time making it.
just modify the php file and give me the $$get method that i should use

**Comment by ZanderBrown** [comment]
ok but i'm busy right now

**Comment by bigbossmaher** [comment]
so will help me in it later ?

**Comment by ZanderBrown** [comment]
I'm afraid if this doesn't work i can't spend anymore time on this (try StackOverflow)

parking.php
```php
<?php
	$servername = "localhost";
	$username = "xxx";
	$password = "xxx";
	$dbname = "axxxxx";

	// Create connection
	$conn = new mysqli($servername, $username, $password, $dbname);
	// Check connection
	if ($conn->connect_error) {
		die("Connection failed: " . $conn->connect_error);
	}
	$conn->query('SET NAMES utf8');
	$sql = "SELECT location_title, location_latitude, location_longitude FROM wp_map_locations";
	$result = $conn->query($sql);
	$list = array();
	if ($result->num_rows > 0) {
		// output data of each row
		while($row = $result->fetch_assoc()) {
			$res = array();
			$res['title'] = $row["location_title"];
			$res['latitude'] = $row["location_latitude"];
			$res['longitude'] = $row["location_longitude"];
			$res['icon'] = 'www/icons/parking.png';
			array_push($list, $res);
		}
	}
	echo json_encode($list, JSON_PRETTY_PRINT);
	$conn->close();
```

JavaScript:
```js
var parkingData = [];
$$.getJSON('http://autopost.besthost.tn/app/parking.php', function (data) {
	$$.each(data, function (index, elm) {
		var place = {};
		place.title = elm.title;
		place.position = new plugin.google.maps.LatLng(elm.latitude, elm.longitude);
		place.icon = elm.icon;
		parkingData.push(place);
	});
});
```

**Comment by centrual** [comment]
- You need to add:
```php
header('Content-Type: application/json');
```
- Check is there **BOM** in your php file. You can make it with Notepad++, Notepad2, Sublime Text or something like that. You need to remove BOM if there is.
- You don't need to pretty_print your json.
- If you using cordova for tests, probably there is a `content-security-policy` problem there. You need to configure your client's `content-security-policy` and you need to add this to your php file:
```php
header("Access-Control-Allow-Origin: *");
```

**Comment by ZanderBrown** [comment]
@centrual `getJSON` is a wrapper for fetching JSON & i included PRETTY_PRINT to make the output clear for @bigbossmaher who has yet to reply if the code i put together for them has had the desired effect

**Comment by centrual** [comment]
@ZanderBrown I'm sorry, i think you asked the question.

**Comment by ZanderBrown** [comment]
@centrual no i was just trying to give @bigbossmaher a helpful push in the right direction but they are yet to respond to the work i put in for the

**Comment by nolimits4web** [comment]
Closing it as doesn't seem like much related to F7
