### ISSUE TITLE
Several bugs in Firefox 50

### ISSUE THREAD

**Issue by reinhart1010** [nolimits4web/Framework7#1314]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.2
* Platform and Target: Android 6.0 via Firefox 50.1
* Live Link or JSFiddle/Codepen: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking one of the templates: Material [Material Kitchensink](http://framework7.io/kitchen-sink-material/), iOS [iOS Kitchensink](http://framework7.io/kitchen-sink-ios/)

### What you did
Open the page. No coding modifications added.

### Expected Behavior
The page should render properly like in WebKit-based browser (Safari, Google Chrome, etc.)

### Actual Behavior
Bubble/Notification Tag (such as 'NEW' text on list) does not aligned properly, The bottom part of page is hidden by footer. This can be shown under the 'Messages' example.

### Further reason to file this bug
Some people are still using Mozilla Firefox, whether they are developing an app using Framework7 or visiting a mobile site powered by Framework7. As this issue happens in Android, I think that the issue also exist in desktop versions of Firefox. In case a regression in Firefox is confirmed, it may take months for the fix to be released, as it passes through many testing channels.

**Comment by dawuwu** [comment]
F7 is a HTML Framework targeted for iOS and Android, as advertised on the homepage "Full Featured HTML Framework For Building iOS & Android Apps"
iOS and Android don't use Firefox as internal browser, so I dont think bugs in FF are a concern.

**Comment by blikblum** [comment]
I use FF daily in Android as my primary browser. 

If F7 is targeting only hibrid apps really it should not care about FF, but if is targeting web apps os reasonably to support it. Since FF is mostly web standard compliant should have no big issues.

**Comment by dawuwu** [comment]
> I use FF daily in Android as my primary browser.

Your primary and the internal browser is not the same, so F7 will work fine no matter what browser you use for surfing

**Comment by ZanderBrown** [comment]
Actually some Android distros do ship Firefox instead of Chrome so while PhoneGap etc. would render in WebKit online WebApps (inc. those pinned to homescreen) would be rendered in Gecko

**Comment by ZanderBrown** [comment]
Could you please expand you point?
Consider pointing code snippets here, on [Codepen](https://codepen.io) or on [JSFiddle](https://jsfiddle.net).
Make sure you have read the [documentation](http://framework7.io/docs/) correctly and followed any instructions it may give.
