### ISSUE TITLE
the content page of popup  behind the overlay

### ISSUE THREAD

**Issue by cloudus** [nolimits4web/Framework7#1316]
when i use the popup, i found that the content page behind ``<div class="popup-overlay modal-overlay-visible"></div>``
![image](https://cloud.githubusercontent.com/assets/12695053/22287822/47056864-e32f-11e6-87de-64d4ecda1f82.png)

**Comment by ZanderBrown** [comment]
Can you provide some code?

**Comment by nolimits4web** [comment]
Popup should be direct child of the app root element or direct child of body if you are not using app root element

**Comment by cloudus** [comment]
thank you
