### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by ErroneousFatality** [nolimits4web/Framework7#1317]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

Could you please update your package version on Nuget?
Currently it's still in beta over there: https://www.nuget.org/packages/genesisvargasj.framework7/
If not and you don't plan on keeping it updated, at least remove this outdated one.

**Comment by nolimits4web** [comment]
It is not an official package, have no idea who is the author of this package
