### ISSUE TITLE
Fixed Navbar in popup ios

### ISSUE THREAD

**Issue by maytis** [nolimits4web/Framework7#1318]
![screen shot 2017-01-25 at 10 12 37 pm](https://cloud.githubusercontent.com/assets/5130490/22299861/b0a6ec04-e34b-11e6-83d7-5b2885736ad3.png)

In the screenshot there is a navbar which is going off the screen. How can I make the navbar fixed in a popup.

**Comment by maytis** [comment]
`  <div class="popup newcontact-popup" style="display: none;">
    <div class="views">
    <div class="view">
      <div class="pages">
        <div class="page navbar-fixed">
          <div class="navbar">
            <div class="navbar-inner">
              <div class="left"><a href="#" class="link close-popup">Cancel</a></div>
              <div class="center" style="left: 107.5px;">New Contact</div>
              <div class="right"><a href="#" class="link addContact">Done</a></div>
            </div>
          </div>
          <div class="page-content">
            <form class="list-block">
              <ul>
                <li>
                  <div class="item-content">
                    <div class="item-media"><i class="icon light big ion-person"></i></div>
                    <div class="item-inner">
                      <div class="item-input">
                        <input class="name" type="text" placeholder="Full name">
                      </div>
                    </div>
                  </div>
                </li>
                <li>
                  <div class="item-content">
                    <div class="item-media"><i class="icon light big ion-ios-telephone"></i></div>
                    <div class="item-inner">
                      <div class="item-input">
                        <input class="phone" type="tel" placeholder="Phone number">
                      </div>
                    </div>
                  </div>
                </li>
                <li>
                  <div class="item-content">
                    <div class="item-media"><i class="icon light big ion-ios-email"></i></div>
                    <div class="item-inner">
                      <div class="item-input">
                        <input class="email" type="email" placeholder="E-mail">
                      </div>
                    </div>
                  </div>
                </li>
                <li>
                  <div class="item-content">
                    <div class="item-media"><i class="icon light big ion-person-stalker"></i></div>
                    <div class="item-inner">
                      <div class="item-input">
                        <select class="gender">
                          <option>Male</option>
                          <option>Female</option>
                        </select>
                      </div>
                    </div>
                  </div>
                </li>
                <li>
                  <div class="item-content">
                    <div class="item-media"><i class="icon light big ion-android-calendar"></i></div>
                    <div class="item-inner">
                      <div class="item-input">
                        <input class="dateOfBirth" type="date" placeholder="Birth day">
                      </div>
                    </div>
                  </div>
                </li>
                <li>
                  <div class="item-content">
                    <div class="item-media"><i class="icon light big ion-android-notifications"></i></div>
                    <div class="item-inner">
                      <div class="item-input">
                        <label class="label-switch">
                          <input class="notifications" type="checkbox" checked="">
                          <div class="checkbox"></div>
                        </label>
                      </div>
                    </div>
                  </div>
                </li>
              </ul>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>`

**Comment by maytis** [comment]
```
  <div class="popup newcontact-popup" style="display: none;">
    <div class="views">
    <div class="view">
      <div class="pages">
        <div class="page navbar-fixed">
          <div class="navbar">
            <div class="navbar-inner">
              <div class="left"><a href="#" class="link close-popup">Cancel</a></div>
              <div class="center" style="left: 107.5px;">New Contact</div>
              <div class="right"><a href="#" class="link addContact">Done</a></div>
            </div>
          </div>
          <div class="page-content">
            <form class="list-block">
              <ul>
                <li>
                  <div class="item-content">
                    <div class="item-media"><i class="icon light big ion-person"></i></div>
                    <div class="item-inner">
                      <div class="item-input">
                        <input class="name" type="text" placeholder="Full name">
                      </div>
                    </div>
                  </div>
                </li>
                <li>
                  <div class="item-content">
                    <div class="item-media"><i class="icon light big ion-ios-telephone"></i></div>
                    <div class="item-inner">
                      <div class="item-input">
                        <input class="phone" type="tel" placeholder="Phone number">
                      </div>
                    </div>
                  </div>
                </li>
                <li>
                  <div class="item-content">
                    <div class="item-media"><i class="icon light big ion-ios-email"></i></div>
                    <div class="item-inner">
                      <div class="item-input">
                        <input class="email" type="email" placeholder="E-mail">
                      </div>
                    </div>
                  </div>
                </li>
                <li>
                  <div class="item-content">
                    <div class="item-media"><i class="icon light big ion-person-stalker"></i></div>
                    <div class="item-inner">
                      <div class="item-input">
                        <select class="gender">
                          <option>Male</option>
                          <option>Female</option>
                        </select>
                      </div>
                    </div>
                  </div>
                </li>
                <li>
                  <div class="item-content">
                    <div class="item-media"><i class="icon light big ion-android-calendar"></i></div>
                    <div class="item-inner">
                      <div class="item-input">
                        <input class="dateOfBirth" type="date" placeholder="Birth day">
                      </div>
                    </div>
                  </div>
                </li>
                <li>
                  <div class="item-content">
                    <div class="item-media"><i class="icon light big ion-android-notifications"></i></div>
                    <div class="item-inner">
                      <div class="item-input">
                        <label class="label-switch">
                          <input class="notifications" type="checkbox" checked="">
                          <div class="checkbox"></div>
                        </label>
                      </div>
                    </div>
                  </div>
                </li>
              </ul>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
```

**Comment by ZanderBrown** [comment]
There hasn't been a response by the issues owner in 20 days.
This issue **will be closed in 7 days** if no further response is submitted

**Comment by nolimits4web** [comment]
It is default and native iOS app behavior. You should use some Cordova/Phonegap keyboard plugin to configure such behavior, e.g. https://www.npmjs.com/package/cordova-plugin-keyboard#keyboardshrinkview
