### ISSUE TITLE
Panel with effect 'reveal' won't close

### ISSUE THREAD

**Issue by dsl101** [nolimits4web/Framework7#1319]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: framework7@1.5.2
* Platform and Target: ios
* Live Link or JSFiddle/Codepen: Built with f7+Vue - is there a jsfiddle setup for that?

See also #1016 which I suspect has the same root cause, but I can't see how to apply the solution there to the Vue case here.

### What you did
Trivial 'hello world' app to try out f7+Vue for the first time:

    <template>
      <div id="app">

        <f7-navbar fixed>
          <f7-nav-center>Test App</f7-nav-center>
          <f7-nav-right>
          <f7-link icon="icon-bars" open-panel="right"></f7-link>
          </f7-nav-right>
        </f7-navbar>

        <f7-card title="Card Title" content="Card Content" footer="Card Footer"></f7-card>

        <f7-panel right reveal>
          <f7-navbar title="Panel">
            <f7-nav-right>
              <f7-link close-panel>Close</f7-link>
            </f7-nav-right>
          </f7-navbar>
          <f7-block>This is the panel content</f7-block>
        </f7-panel>

      </div>
    </template>

### Expected Behavior
The panel should open and close using the navbar icon and the Close link in the panel

### Actual Behavior
The panel opens but won't close. If I change the panel spec to this:

    <f7-panel right cover>

it animates in and closes perfectly. Tested on ios (iphone 6) and desktop browser - same behaviour on both.

I can't put the panel outside the main div as suggested in #1016, as Vue complains that there must be only 1 root element in the template. I also tried putting a div round the navbar / card, and another one round the panel, but still no joy.

**Comment by nolimits4web** [comment]
Your app structure is a bit wrong. Check the correct one in example here https://github.com/nolimits4web/Framework7-Vue-Webpack-Template/blob/master/src/app.vue or here http://framework7.io/vue/app-layout.html#advanced-layout

**Comment by dsl101** [comment]
Thanks - really helpful. And I now realised this should probably be in f7-vue - apologies! But for the sake of keeping it together, I can now close the panel, but the panel navbar isn't shown when sliding on an iphone after the first open/close cycle. It works fine in the browser, and it 'appears' when the panel stops moving. But in between it's blank. The panel _content_ is shown fine, so it's just a visual glitch. This is the panel setup I have, in place of the one in that template:

    <f7-panel left cover layout="dark">
      <f7-view id="left-panel-view">
        <f7-navbar title="Units">
          <f7-nav-right>
            <f7-link close-panel>X</f7-link>
          </f7-nav-right>
        </f7-navbar>
        <f7-pages>
          <f7-page>
            <f7-list form>
              <template v-for="typeName in allTypes">
              <f7-list-button
                close-panel
                @click="type = typeName"
              >{{typeName}}</f7-list-button>
              </template>
            </f7-list>
          </f7-page>
        </f7-pages>
      </f7-view>
    </f7-panel>

and here's a codepen which shows the glitch: http://codepen.io/anon/pen/XpEwjP/

**Comment by dsl101** [comment]
Decided to open a proper ticket in the right place here: https://github.com/nolimits4web/Framework7-Vue/issues/85 Please ignore this one.
