### ISSUE TITLE
[Enhancement] Search bar onClear when empty

### ISSUE THREAD

**Issue by JohnRSim** [nolimits4web/Framework7#1321]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.2
* Platform and Target: Win10 Chrome 55, crosswalk cordova
* Live Link or JSFiddle/Codepen: https://codepen.io/anon/pen/rjGjXQ

### What you did
Added a searchbar set customSearch as true to initialise own search commands.
2 Things - 
1. Tried to initialise onClear event by selecting X icon when there is no text as clear X icon is available when focused on the search input.
2. Initialised onClear event by selecting X icon when there is a search text string available - onClear initialises but does not display s.value the text that was cleared just shows the s.value is empty.

### Expected Behavior
EXPLAIN WHAT IS TO BE EXPECTED, HERE.
1. When selecting clear ie X icon -  if there is no value added then onClear does not appear to be triggered but out of the box actions like hide the X icon occur - it would be nice if onClear could trigger so developers could add custom behavior/actions like the automatic removal of the X to other elements of the app..
2. Expected onClear to clear the value which it did - however expected it to return the value that was cleared in s.value

### Actual Behavior
EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.
1. onClear does not get triggered if the user just selects X icon with no search string value.
2. OnClear value is empty expecting onclear s.value to have text that was cleared.

**Comment by nolimits4web** [comment]
Add previous value for onClear method. As for the 1st point, use onDisable method/event in this case
