### ISSUE TITLE
[Enhancement] Panel swipe on touch/swipe event listener.. 

### ISSUE THREAD

**Issue by JohnRSim** [nolimits4web/Framework7#1325]
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.2
* Platform and Target: Crosswalk cordova Android
* Live Link or JSFiddle/Codepen: N/A

### What you did
Enabled swipePanel:'left' on the app. 

On dragging finger across the screen the panel can be seen to move - as an enhancement can there be another event created that can be used ie 
```
$$('.panel-left').on('panel:swiping', function () {
    //custom code - ie hide DOM
}); 
```

As the user puts their finger on the screen and moves  across the screen the event above is initialised - as panel:close'/'open' is only called when finger is raised off the screen. 

### Expected Behavior
'panel:swiping' to be triggered if swpePanel is enabled to allow developers to customise content panel to help improve performance.

### Actual Behavior
There is no event to allow developers to trigger the above behavior.

I will experiment with the touchmove event on the window

**Comment by ZanderBrown** [comment]
http://framework7.io/docs/side-panels.html:
> ## Panel Events
> Panel events could be very useful to detect how user interact with your panels, or to do something in JavaScript when Panel opened/closed
> 
> | Event | Target | Description |
> | --- | --- | --- |
> | panel:open |  Panel Element `<div class="panel">` | Event will be triggered when Panel starts its opening animation | 
> | panel:opened |  Panel Element `<div class="panel">` | Event will be triggered after Panel completes its opening animation | 
> | panel:close |  Panel Element `<div class="panel">` | Event will be triggered when Panel starts its closing animation | 
> | panel:closed |  Panel Element `<div class="panel">` | Event will be triggered after Panel completes its closing animation | 

Would `panel:open` not suffice?

**Comment by JohnRSim** [comment]
Unfortunately panel:open only works  when I swipe and move finger off the screen..

I'm using this googlemaps plugin for cordova - https://github.com/mapsplugin/cordova-plugin-googlemaps

The map appears under the browser in a dimension defined by a container div - so you can't layer it over element and so make all layers transparent. 

I want to set a background color on page as the user is swiping the panel open or close. 

But using the above means as I swipe panel:open is not initialised until I release my finger from the screen and I need the background colour as I'm doing a touchmove with the panel.

I tried $$(document).on('touchmove' but that doesn't initialise if I try the swipe close the panel. Works great swiping the panel open.

**Comment by JohnRSim** [comment]
![screenshot_20170128-091216](https://cloud.githubusercontent.com/assets/364208/22395563/20325c26-e53a-11e6-9ba1-aa00e50bff9c.png)

Quick example you can see as I swipe the page panel is transparent to show google maps behind the browser so I need to set a BG colour as a default Google map grey and hide the Google map during the transition - as the background is transparent on panel swipe looks wrong.
