### ISSUE TITLE
[Bug] pageName.split is not a function - (onPageAfterAnimation)

### ISSUE THREAD

**Issue by JohnRSim** [nolimits4web/Framework7#1326]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: Chrome 55 Win 10
* Platform and Target: Crosswalk cordova.
* Live Link or JSFiddle/Codepen: https://codepen.io/anon/pen/ZLaajX

### What you did
Added onPageAfterAnimation
```
myApp.onPageAfterAnimation(function() {});
```
### Expected Behavior
Was expecting no errors - for some reason the above generates a.split error in codepen and pageName.split error in my project. - The function does however execute correctly without any issues when transitioning between pages.

### Actual Behavior
Error is displayed in console - after page transition from on to the next code is not initialized.

**Comment by ZanderBrown** [comment]
http://framework7.io/docs/page-callbacks.html:
> myApp.onPageBeforeAnimation(pageName, callback(page)) - "callback" function will be executed when everything initialized and page (with "pageName" data-page attribute) is ready to be animated
> * pageName - string - expected page's "data-page" attribute
> * callback(page) - function - callback function that will be executed. As an argument it receives Page Data object

In your code you only provide a callback meaning the first argument is a function when a string was expected

Assuming you wanted the callback to run for every page in your app the following would work:
```
myApp.onPageAfterAnimation('*', function() {});
```
*Note the use of '\*'*

**Comment by JohnRSim** [comment]
Thanks zander!

Sorry misread the documentation - my bad :(
