### ISSUE TITLE
Bold status in modal buttons not working in webview

### ISSUE THREAD

**Issue by tinyCoder32** [nolimits4web/Framework7#1327]
This is a (multiple allowed):
* [x] bug

Hi, the first screenshot taken from Android 5.1.1 in my app running inside CrossWalk WebView, the button is not bold.

![android](https://cloud.githubusercontent.com/assets/17817239/22404119/db75d262-e632-11e6-8cf1-66018e4bf149.jpeg)

Second screenshot is from Firefox on Mac.

![firefox](https://cloud.githubusercontent.com/assets/17817239/22404120/e0ab1eea-e632-11e6-8bf1-9a18e545491d.png)

Code is simple:

```
$$(document).on('click', '.report-ad', function () {
    myApp.modal({
      title:  'What is the problem?',
      text: '<div class="input-field"><textarea class="modal-text-input" type="text" placeholder="Type here.." rows="4"></textarea></div>',
      buttons: [
        {
          text: 'Cancel',
          close: true,
        },
        {
          text: 'Send',
          bold: true,
          onClick: function() {
            myApp.alert('You clicked second button!')
          }
        }
      ]
    });
  });
```

**Comment by nolimits4web** [comment]
Because of the issue with fonts in different themes. Use Material theme for Android or add the following CSS rule:
```css
.modal-button.modal-button-bold {
  font-weight: bold;
}
```
