### ISSUE TITLE
Critical issue, slider dosen't work on ios 10.3 beta. 

### ISSUE THREAD

**Issue by mnill** [nolimits4web/Framework7#1330]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.2
* Platform and Target: ios 10.3
* Live Link or JSFiddle/Codepen: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking one of the templates: iOS [JSFiddle](https://jsfiddle.net/s2n1p730/)/[Codepen](https://codepen.io/nolimits4web/pen/WRRWwN), Material [JSFiddle](https://jsfiddle.net/0ogxxcvt/)/[Codepen](https://codepen.io/nolimits4web/pen/pEPPPK)

### What you did
Install ios 10.3 beta and checked examples

### Expected Behavior
Worked slider in 10.3

### Actual Behavior
Slider doesn't work, issue like in chrome in 
https://github.com/nolimits4web/Framework7/issues/929

**Comment by nolimits4web** [comment]
Fixed with #1163
