### ISSUE TITLE
[FEATURE] Autocomplete: Load all items on open

### ISSUE THREAD

**Issue by J05HI** [nolimits4web/Framework7#1333]
This is a:
* [x] feature-discussion (RFC)

Hello nolimits4web, 

can you please add a parameter to autocomplete popup to load all items on open? 
Would be very helpful. 
Thank you for your amazing project!!!

**Comment by ZanderBrown** [comment]
http://framework7.io/docs/autocomplete.html See 'Dropdown With All Values'

**Comment by J05HI** [comment]
@ZanderBrown 

Yeah I saw it but I don't need it as drop down. 
I need it as a popup. 
Is this possible with the current version?

**Comment by J05HI** [comment]
@nolimits4web 
Thank you soooo much!!!!
