### ISSUE TITLE
App Framework - Now with deployment to Apple App Store

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7#1335]
Hey folks, after two month of development, I am happy to present you now: **App Framework**

<br />

# [App Framework]( https://github.com/scriptPilot/app-framework) &nbsp; &nbsp; &nbsp; [![](https://img.shields.io/npm/dt/app-framework.svg)](https://www.npmjs.com/package/app-framework) [![](https://img.shields.io/npm/v/app-framework.svg)](https://www.npmjs.com/package/app-framework) [![](https://img.shields.io/npm/l/app-framework.svg)](https://www.npmjs.com/package/app-framework)

**Does all the tricky stuff for you to develop, test, build and deploy iOS and Android like web applications.** 

## Features
> The power is under the hood - but for sure, we have a [Demo App](https://app-framework.scriptpilot.de/).

**Beautiful**
- All well known [iOS](http://framework7.io/kitchen-sink-ios/) and [Material](http://framework7.io/kitchen-sink-material/) user interface components as well as native transitions
- Comprehensive icon fonts like [FontAwesome](http://fontawesome.io/), [Framework7](http://framework7.io/icons/), [Ion](http://ionicons.com/) and [Material Icons](https://material.io/icons/)
- Phone frame around your application on big screens

**Powerful**

- Easy realization of state based, reactive user interfaces with the power of [Vue.js](https://vuejs.org/)
- State kept for history, tabs, scroll positions, panels, modals, form and page component data
- User registration, password reset and login processes with [Firebase Authentication](https://firebase.google.com/docs/auth/)
- [Realtime database](https://firebase.google.com/docs/database/) and [file storage](https://firebase.google.com/docs/storage/) services with Firebase
- Application hosting with [Firebase Hosting](https://firebase.google.com/docs/hosting/)
- Offline capabilty, flexible routing and multi-language support

**Timesaving**

- Creation of a lightweight and well-organized project folder, prepared to push to [GitHub](https://github.com/about)
- Development server with live reload, perfectly to use together with [Chrome DevTools](https://developers.google.com/web/tools/chrome-devtools/) 
- Your application is splitted up in easy to maintain [single file components](https://vuejs.org/v2/guide/single-file-components.html) with [ES2015 support](https://babeljs.io/learn-es2015/)
- Generation of favicons, touch icons and splash screens out of a single image file
- Integrated code checks for [correctness](http://eslint.org/) and [standard conformity](http://standardjs.com/)
- Build process with version bump and compression of all HTML, CSS, JavaScript and image files
- Deployment to [Firebase Hosting](https://firebase.google.com/docs/hosting/) or your own server without downtime and with easy rollback solution

**Comment by farskid** [comment]
No React support?

**Comment by scriptPilot** [comment]
App Framework is mainly based on Framework7-Vue components, so no React support planned for now, but feel free to fork the project for React :-)

**Comment by scriptPilot** [comment]
Scope extended - Deployment will be realized for Apple App Store and Google Play Store as well.

[![App Framework process](https://raw.githubusercontent.com/scriptPilot/app-framework/master/media/process.png)](https://github.com/scriptPilot/app-framework)

**Comment by scriptPilot** [comment]
Version 1.1 released - now with Apple App Store deployment :-)

https://github.com/scriptPilot/app-framework

**Comment by ZanderBrown** [comment]
Whilst this is all very interesting i'm not sure this is really the right place to discuss it.

Although seriously congratulations i can see you have put a LOT of work into this

**Comment by scriptPilot** [comment]
@ZanderBrown - I used this place as **App Framework** is based on Framework7 for UI development. I will propose Vladimir a pull request for the F7-Vue starter kit page soon. Thank you, could you propose a better place to promote the project?

Now, the deployment to Google Play Store is supported as well :-)

**Comment by ZanderBrown** [comment]
There is  a forum [here](http://forum.framework7.io/)
