### ISSUE TITLE
Autocomplete positionDropDown Bug in Popup

### ISSUE THREAD

**Issue by bpshonyak** [nolimits4web/Framework7#1337]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.2
* Platform and Target: CORDOVA [iOS and Android]
* Live Link or JSFiddle/Codepen: https://codepen.io/bpshonyak/pen/bgKzae

### What you did
I created a simple popup with an input field that used autocomplete.

### Expected Behavior
When I click on the input field I expect the autocomplete to work just like it does on a page.

### Actual Behavior
The autocomplete input field does not work because the positionDropDown function uses the .page-content class which is not present in the popup.

**Comment by nolimits4web** [comment]
In this case the following structure is required and always recommended in Popup:
```
.popup
  .view
    .page
      .page-content
```
To make all things work correctly. Page-content is required for Autocomplete to work, otherwise it is pretty hard (and heavy) to detect correct position and all scrollable layers
