### ISSUE TITLE
Anybody knows how make a simple submit with ajax in rails with framework 7?

### ISSUE THREAD

**Issue by marcosvicente** [nolimits4web/Framework7#1339]

**Comment by ZanderBrown** [comment]
No Code & No Description.

@marcosvicente this is not a forum. Try stackoverflow.

@valnub & @nolimits4web Move to close?

**Comment by valnub** [comment]
@ZanderBrown is right

@marcosvicente Please ask on one of these platforms and **_add more details to your question so others can understand what you're asking_**:

- http://forum.framework7.io
- http://www.stackoverflow.com

**Comment by valnub** [comment]
Hey, @ZanderBrown can you contact me please via https://www.timo-ernst.net/contact/ or https://twitter.com/timo_ernst

I want to ask you something, thanks! :)
