### ISSUE TITLE
Swipeable tabs and Side panel bug

### ISSUE THREAD

**Issue by StefansArya** [nolimits4web/Framework7#1340]
**What I did**
I'm enabled swipePanel from javascript:
var myApp = new Framework7({
    modalTitle: 'Framework7',
    swipePanel: 'right',
    material: true,
});

And trying the example on:
Tabs -> Swipeable Tabs

And when I swipe the tabs, the side panel also swiped too..

**Expected Behavior**
It should only swipe the tabs only

**Comment by ZanderBrown** [comment]
I imagine this is related to #1285

**Comment by StefansArya** [comment]
Oh! you're right..

**Comment by ZanderBrown** [comment]
That being said as #1285 has been closed with a specific fix having been committed it would be good to keep this open as it's slightly different.

My comment was meant to highlight the similarities

**Comment by StefansArya** [comment]
I just modify the recent fix with this and it worked for me..

`if (e.target && e.target.nodeName.toLowerCase()==='input'||e.target.type==='range'||e.target.offsetParent.className.search('swiper-slide')!=-1||e.target.className.search('swiper-slide')!=-1) return;`

**Comment by StefansArya** [comment]
My current problem is when I click (not drag) somewhere, the menu showing up...

**Comment by ZanderBrown** [comment]
Give it a go and submit a PR 😄
