### ISSUE TITLE
empty page after clicking a link

### ISSUE THREAD

**Issue by MerNat** [nolimits4web/Framework7#1341]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Platform and Target: IOS, ANDROID

### What you did
Here is what happened, i do have an opened page with a url address of itemshow.html?id=1&c=1 having a contents and links referencing to others and one of them to itemshow.html?id=1&c=2. and when i click this link it goes to new page, but when i returned back to the itemshow.html?id=1&c=1 the page remains empty … and sometimes a new page with empty div is opened. [N.B. the itemshow.html page is loaded with an ajax call when it's initialized of course.]

### Expected Behavior
its supposed to open the the itemshow.html?id=1&c=2 with the contents received by the ajax call. 

### Actual Behavior
Empty page is shown after clicking the link.

**Comment by valnub** [comment]
Hi, can you please post a runnable example of the problem on [Codepen](http://codepen.io)? Thanks
