### ISSUE TITLE
How make a form ajax post in framework 7?

### ISSUE THREAD

**Issue by marcosvicente** [nolimits4web/Framework7#1342]
I search in the documentation for this resolution of my problem, but I don't understood how make a create, anybody help me ? 
please

**Comment by ZanderBrown** [comment]
1: This is not a forum

http://framework7.io/docs/form-ajax-submit.html

> ## Send form data on submit
> To enable Ajax form and send data automatically on submit, we just need to add "ajax-submit" class to form:
> 
> ```
> <form action="send-here.html" method="GET" class="ajax-submit">
>     ...
> </form> 
> ```
> And when user will submit this form, it automatically will be sended using Ajax with the following rules:
> 
> * Form data will be sended to the file/url specified in form's "action" attribute
> * Request method will be the same as specified in form's "method" attribute
> * Content type will be the same as specified in form's "enctype" attribute. By default (if not specified), it is application/x-www-form-urlencoded

If you wish to post merely set the method as `POST`

**Comment by rgfpy** [comment]
This code is Valid for Call Ajax Request? In documentation not find example

```
$$.ajax({
	url: 'http://api.example.com',
        method: 'POST',
	dataType: 'json',
	contentType: 'application/json',
	data: {
		user: 'usuario',
		pass: '12345'
	},
	success: function(response){
		alert(JSON.stringify(response));
	},
	error: function(xhr, status){
		alert('Error: '+JSON.stringify(xhr));
		alert('ErrorStatus: '+JSON.stringify(status));
	}
});
```
