### ISSUE TITLE
Framework7 Mithril

### ISSUE THREAD

**Issue by lroal** [nolimits4web/Framework7#1346]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

Does anyone have knowledge of a [Mithril ](http://mithril.js.org/) version of Framework7 in development ?
Or is there any react version up-to-date that could be ported to Mithril ?

**Comment by ZanderBrown** [comment]
@nolimits4web, @valnub any thoughts?

**Comment by nolimits4web** [comment]
There is no a Mithril version in development i know about. As for React version, here is the one and up-to-date https://github.com/bencompton/framework7-react/
