### ISSUE TITLE
On hiding the Toolbar Div in Android Material theme, for accordion list white space generates

### ISSUE THREAD

**Issue by alapanme** [nolimits4web/Framework7#1347]
On the Index page I have hidden the Toolbar div and have used the accordian list view in the page content. But there is a blank space that has popped up above the accordian. How to remove that ?
![capture](https://cloud.githubusercontent.com/assets/25705483/22853672/c476dc1e-f082-11e6-8a26-f38ed9f1fe5c.PNG)

**Comment by ZanderBrown** [comment]
Could you please expand you point?
Consider pointing code snippets here, on [Codepen](https://codepen.io) or on [JSFiddle](https://jsfiddle.net).
Make sure you have read the [documentation](http://framework7.io/docs/) correctly and followed any instructions it may give.

**Comment by alapanme** [comment]
`<body>
  
    
    <div class="views">
      
      <div class="view view-main">
        
        <div class="pages navbar-fixed toolbar-fixed">
          
          <div data-page="index" class="page no-toolbar">
 
            
<div class="navbar">
     <div class="navbar-inner">
        <div class="left">
            <a href="#" class="link icon-bars">
                <i class="icon icon-bars"></i>
            </a>
        </div>
        <div class="center">Demo 2</div>
        <div class="right">
            <a href="#" class="link icon-bars">
                <i class="f7-icons">info_fill</i>
            </a>
        </div>
    </div> 
</div> 

			
             <div class="toolbar toolbar-hidden">
              <div class="toolbar-inner">
                <a href="#" class="link">Link 1</a>
                <a href="#" class="link">Link 2</a>
              </div> 
            </div>
			
            
            <div class="page-content">
              
			  <div class="content-block-title">List View Accordian</div>
<div class="list-block accordion-list">
  <ul>
    <li class="accordion-item"><a href="#" class="item-content item-link">
        <div class="item-inner">
          <div class="item-title">Demo 1</div>
        </div></a>
      <div class="accordion-item-content">
        <div class="content-block">
          <p>loremsum ipsum</p>
        </div>
      </div>
    </li>`

As in the code, I have explicitly hidden the toolbar **<div class="toolbar toolbar-hidden">** and because of this, a white space is coming above the accordion list.

**Comment by ZanderBrown** [comment]
Is the toolbar needed?

**Comment by alapanme** [comment]
No I don't want it. But If i remove the entire Toolbar DIV too, the space is still present.

**Comment by ZanderBrown** [comment]
Works correctly here: https://codepen.io/13b/pen/ZLmNrY

**Comment by ZanderBrown** [comment]
@alapanme did the pen i provided resolve your issue?

**Comment by alapanme** [comment]
@ZanderBrown No, it didn't. Please find my entire index html and my-app js.
https://jsfiddle.net/ch3md5f9/1/

**Comment by ZanderBrown** [comment]
You didn't need the toolbar div or any of the `toolbar-` classes https://jsfiddle.net/dkkpv379/1/

**Comment by alapanme** [comment]
@ZanderBrown Thnaks a lot ...Removing the unwanted toolbar classes did the trick. 
![capture1](https://cloud.githubusercontent.com/assets/25705483/22856607/a11c040a-f0ba-11e6-9c9f-369cadb1258d.PNG)
