### ISSUE TITLE
Autocomplete backOnSelect does not work when user clicks previously selected item

### ISSUE THREAD

**Issue by seme1** [nolimits4web/Framework7#1348]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.53.
* Platform and Target: IOS and Android
* Component affected: Autocomplete with standalone simple page or "Simple Standalone Autocomplete" as it appears in the Docs here:
http://framework7.io/docs/autocomplete.html

When a user selects an item for the first time and backOnSelect is set to true, the autocomplete page closes as expected. When the autocomplete page is triggered to re-open again, it displayed the previously selected value which is nice. However, when the user re-chooses the previously selected item, the page does not close. If he wants to go back, the only option he has is to select the Back arrow key in the top corner of the autocomplete page. This is inconvenient for many users. 

Expected behavior: if a user selects a previously selected item when backOnSelect is set to true, the autocomplete page should still close.

**Comment by ZanderBrown** [comment]
Can confirm
