### ISSUE TITLE
Regarding Autocomplete extender in search-bar

### ISSUE THREAD

**Issue by sushanttorankar** [nolimits4web/Framework7#1351]
how can i use search bar autocomplete extender for asp.net web application ?
i tried to use that search-bar with AJAX Autocomplete Extender,but it is not displaying any results.
so if you have any solution please let me know.I'll be grateful.

Thanks

**Comment by ZanderBrown** [comment]
Could you please expand you point?
Consider pointing code snippets here, on [Codepen](https://codepen.io) or on [JSFiddle](https://jsfiddle.net).
Make sure you have read the [documentation](http://framework7.io/docs/) correctly and followed any instructions it may give.

**Comment by sushanttorankar** [comment]
hello,
i have query displaying DIV in different devices.
so is there any css class in framework7 that will hide my DIV in Desktop and display in Mobile view ?

thanks

**Comment by ZanderBrown** [comment]
https://www.w3schools.com/cssref/css3_pr_mediaquery.asp
