### ISSUE TITLE
Old page is not cached after click back button

### ISSUE THREAD

**Issue by StefansArya** [nolimits4web/Framework7#1352]
This is a:
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: 1.5.2.
* Platform and Target: Cordova, Chrome Browser.

### What I did
1. Navigate to Framework7 Kitchen sink example
2. Click Pull to Refresh
3. Pulling down the page and new value is added (Total list is 4)
4. Click Back (Not the browser's back)
5. Click Pull to Refresh again

### Expected Behavior
I expect the old page with the 4 list to be cached and loaded again when I re-click the Pull to Refresh button

### Actual Behavior
The Pull to Refresh was back to it original state with 3 list.
I have tried to modify the kitchen-sink.js like this, but it's doesn't work:

```
var myApp = new Framework7({
    modalTitle: 'Framework7',
    swipePanel: 'both',
    material: true,
    pushState: true,
    reload: true, //I changed this to false but still doesn't work
    reloadPrevious: true,
    force: false,
    ignoreCache: false,
});
```

**Comment by loveisalie92** [comment]
I have the same problem when upgrade bower to the newest version. This Bug may destroys the killer feature "Swipe To Go Back" in IOS platform.

**Comment by ZanderBrown** [comment]
Have you tried `domCache: true`

**Comment by StefansArya** [comment]
It doesn't work, when I go to Pull to Refresh page it still reset to default value, my alternative way is making a page as popup element in the index.html
But, it will make my index.html more bigger and more complex..

The problem is just same when I fill value on Forms->Form Elements, go back and open again..

**Comment by nolimits4web** [comment]
F7 doesn't have any built-in data storage, you should use your own implementation (DB, FireBase, LocalStorage, etc.) what is fit best for you and your app
