### ISSUE TITLE
Side Panel is not getting invoked

### ISSUE THREAD

**Issue by alapanme** [nolimits4web/Framework7#1353]
I have a hamburger menu icon on the navigation bar and I want to insert a side panel on the click on the hamburger icon. 

Please find in the link my Index.html and my-app.js 

https://jsfiddle.net/0gnckfkp/

**Comment by StefansArya** [comment]
Is this supposed to be a question? if yes please ask at StackOverflow instead..
You can invoke the [side panel with javascript](https://framework7.io/docs/side-panels.html#using-javascript)

**Comment by ZanderBrown** [comment]
As @StefansArya said this would be better asked on SO

**Comment by alapanme** [comment]
@StefansArya  @ZanderBrown Thanks for your input. I resolved the issue by looking into the code of 'Kitchen Sink' app. Hence closing the issue.
