### ISSUE TITLE
Allow differenciation between notification scripted  / clicked close event

### ISSUE THREAD

**Issue by MatthiasBusch** [nolimits4web/Framework7#1354]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

### What you did
I am trying to differenciate between a user triggered close of a notification and a closing of my app when switching the view

### Expected Behavior
The close event should pass the original click event or so to be able to trigger different actions depending on the close trigger

### Actual Behavior
It is impossible to differenciate, if the user closed the notification or not

**Comment by valnub** [comment]
Could you explain this a bit more in detail?

> differenciate between a user triggered close of a notification and a closing of my app when switching the view

Maybe post screenshots/video and code examples?

Are you building a web app or native app (Cordova/PhoneGap)?

Are you talking about F7 notifications or native Push Notifications of mobile operating systems?

**Comment by MatthiasBusch** [comment]
I am building a phonegap app with F7 notifications.

**What I want to achieve:**
When the switches the page, the notifications are closed and reopen when going back. Therefore the notifications will only appear on a specific page. But if the user closes a notification, it is supposed to trigger an action and the notificiation disappears.

**The problem at the moment:**
I can not detect, if the popup is closed because the user closed it with a click on the close button or if it was closed programatically because of a page change

**Comment by valnub** [comment]
Did you check the `onClose` callback described here? https://framework7.io/docs/notifications.html

**Comment by MatthiasBusch** [comment]
I did so indeed and it says: 
Callback function that will be executed when notification is closed (**by click** on close icon **or** via API **using myApp.closeNotification** method)

But I want to trigger a specific code, **only** if the user closed it via click. There is another callback function onClick, but that one is triggered, if I click anywhere on the notification even without closing it

**Comment by nolimits4web** [comment]
Pushed fix for this, now `onClose` method accepts second `event` argument which is passed only in case it was closed by click:
```js
...
onClose: function (item, event) {
  if (event) {/*closed by click*/}
  else {/*closed by script*/}
}
