### ISSUE TITLE
floating labels do not float on **formFromData**

### ISSUE THREAD

**Issue by ardabeyazoglu** [nolimits4web/Framework7#1356]
When i use **myApp.formFromData** method in a material form, the form fields are filled with values, however the floating labels do not float. So they overlap the actual input value. 
You can see here : http://prntscr.com/e8mf6b

FW7 version: 1.5.3
I call the method on page init

**Comment by valnub** [comment]
Hi, can you post a live code demo on codepen? Thanks :) https://codepen.io/hello/

**Comment by ardabeyazoglu** [comment]
Here it is: [http://codepen.io/anon/pen/ygmPRq](http://codepen.io/anon/pen/ygmPRq)
