### ISSUE TITLE
Symbol ">" on the right side of the list item is not centered vertically

### ISSUE THREAD

**Issue by DAnn2012** [nolimits4web/Framework7#1358]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.3
* Platform and Target: iOS and Android

I think that the correct position of the symbol ">" on the right side of the list item is centered vertically.

I tried to edit the files "framework7.ios.css" and "framework7.material.css"in this way:

1) delete 
`background: none;`
 from block 
`.list-block.media-list .item-link .item-inner, .list-block li.media-item .item-link .item-inner`

2) delete items
`background`
`background-image`
`background-size`
from block
`.list-block.media-list .item-link .item-title-row, .list-block li.media-item .item-link .item-title-row
`

In this way the result is surely better.

BEFORE:

![before](https://cloud.githubusercontent.com/assets/1197819/22968184/c2c2374e-f369-11e6-9cfc-ef752561a661.png)

AFTER:

![after](https://cloud.githubusercontent.com/assets/1197819/22968208/d51dbb0c-f369-11e6-853f-9cc1e401b0e9.png)

**Comment by valnub** [comment]
Are you sure? I think the upper ("before") version corresponds to the official Apple UI guidelines. Does someone have a screenshot of an official Apple app that uses lists like this?

**Comment by ZanderBrown** [comment]
The [HIG](https://developer.apple.com/ios/human-interface-guidelines/ui-views/tables/) is a tad unconclusive

**Comment by DAnn2012** [comment]
Yes, it is inconclusive. But even here it

[http://stackoverflow.com/questions/31368335/tableviewcell-disclosure-indicator-position](http://stackoverflow.com/questions/31368335/tableviewcell-disclosure-indicator-position)

it is reported that the default position in Xcode is:

> I have a custom tableviewcell with the standard disclosure indicator positioned in the centre vertically by default. How can I move this standard disclosure indicator vertically like in the iOS mail app?

**Comment by nolimits4web** [comment]
I did it near the "title" line because it was what we can see in few native iOS apps (like Mail). Also it has some real advantage, because moving it bottom (center) will "eat" additional 20px width from "item-subtitle" and "item-text" elements, and space is what is really expensive on small screens. So i won't change it to center by default. If you need it, just add few custom CSS rules to achieve it, what you already did.
