### ISSUE TITLE
Inline picker width error when resizing

### ISSUE THREAD

**Issue by SteffenDE** [nolimits4web/Framework7#1359]
This is a:
* [x] bug

When resizing a page containing an inline picker (date/time) the columns get unreadable using Safari 10 on OS X Sierra (on iOS using Cordova too):
![feb -15-2017 16-01-54](https://cloud.githubusercontent.com/assets/4116351/22979887/346b7ee0-f398-11e6-8315-6b1460d692e2.gif)

It's working in Chrome though:
![feb -15-2017 16-02-29](https://cloud.githubusercontent.com/assets/4116351/22979895/37cca852-f398-11e6-8755-06c43d36fead.gif)

**Comment by ZanderBrown** [comment]
That's one seriously weird edge case bug that. Good catch @SteffenDE!
