### ISSUE TITLE
Change the color of floating-button (Floating Action Button) icon

### ISSUE THREAD

**Issue by idyrda** [nolimits4web/Framework7#1360]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.3
* Platform and Target: CORDOVA, ANDROID.

### What you did
I added the Floating Action Button:
```
  <a href="#" class="floating-button color-yellow">
    <i class="icon icon-plus color-black"></i>
  </a>
```

### Expected Behavior
I want yellow button with black icon.

### Actual Behavior
I have yellow button with white icon.

![1](https://cloud.githubusercontent.com/assets/25587438/22980242/add7dd2e-f3a1-11e6-8dd6-e9c405d7a1ca.JPG)

What should I do to change white icon to black icon in Floating Action Button?

**Comment by ZanderBrown** [comment]
The colour of the image is hardcoded in a url encoded data uri.

**Comment by idyrda** [comment]
Thank ZanderBrown.
I added in my-app.css code:
```
i.icon.icon-plus {
  background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg%20fill%3D'%23000000'%20height%3D'24'%20viewBox%3D'0%200%2024%2024'%20width%3D'24'%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%3E%3Cpath%20d%3D'M19%2013h-6v6h-2v-6H5v-2h6V5h2v6h6v2z'%2F%3E%3Cpath%20d%3D'M0%200h24v24H0z'%20fill%3D'none'%2F%3E%3C%2Fsvg%3E");
}
```
and the icon has become black ))
