### ISSUE TITLE
The problem with the alignment of popover in floating-button-to-popover (Morph To Popover)

### ISSUE THREAD

**Issue by idyrda** [nolimits4web/Framework7#1362]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.3
* Platform and Target: CORDOVA, ANDROID.

### What you did
I wrote the following code:
```
  <a href="#" data-popover=".popover-add" class="floating-button floating-button-to-popover open-popover">
    <i class="icon icon-plus color-black"></i>
  </a>

  <div class="popover popover-add">
    <div class="popover-inner">

      <div class="list-block inputs-list">
        <ul>
          <li class="item-content">
            <div class="item-inner">
              <div class="item-title floating-label">Text</div>
              <div class="item-input"><input type="text"></div>
            </div>
          </li>
        </ul>
      </div>

      <div class="content-block">
        <a href="#" class="button button-raised">Save</a>
      </div>

    </div>
  </div>
```

### Expected Behavior
I would like to automatically leveled popover.

### Actual Behavior
Popover jump up leaving a yellow background behind himself when resizing the window.

Phone Android:
![1](https://cloud.githubusercontent.com/assets/25587438/23028625/8f0df6ba-f470-11e6-9f2b-8c381645bbfc.gif)

Desktop Chrome:
![2](https://cloud.githubusercontent.com/assets/25587438/23028664/a7df155c-f470-11e6-8703-b8a7a8fb95f8.gif)

**Comment by valnub** [comment]
Hi, I don't know the solution to your problem but how did you create all these cool gifs? :D

**Comment by idyrda** [comment]
)) I used the [screentogif](https://screentogif.codeplex.com/) for desktop and [AZ Screen Recorder](https://play.google.com/store/apps/details?id=com.hecorat.screenrecorder.free) with conversion of video over [ezgif.com](http://ezgif.com/video-to-gif) for Android phone. Sorry for my English.
