### ISSUE TITLE
Theme color is missing for `.statusbar-overlay`

### ISSUE THREAD

**Issue by iBinJubair** [nolimits4web/Framework7#1364]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.3
* Platform and Target: iOS

### What you did
Adding class selectors lines to `framework7.ios.colors.css` and `framework7.material.colors.css` to cover theme colors. e.g.
`.theme-red .statusbar-overlay {
	background-color: #f44336;
}`

### Expected Behavior /  Actual Behavior
If this tag has been used `<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />`, the status bar background color will be always `blue`. The `.statusbar-overlay` must be added to theme color css files.

**Comment by valnub** [comment]
Is this a question or do you have a suggetion for improvement? If the latter is the case, you post your improvement as a pull request? Thanks

See https://help.github.com/articles/about-pull-requests/

**Comment by macdonst** [comment]
Yeah, this looks like a good candidate for a PR. Also, whomever sends in a PR should make sure that they follow the the Material style guidelines. If the primary color is blue then the status bar should be primary color dark as per: https://developer.android.com/training/material/theme.html#StatusBar

**Comment by macdonst** [comment]
I added a PR for this as it seemed like a fun way to spend a Sunday night learning .less.

**Comment by nolimits4web** [comment]
Fixed in #1377 by @macdonst 👍
