### ISSUE TITLE
Material Theme on IOS bugs: ripple, checkbox, status bar

### ISSUE THREAD

**Issue by hesrun** [nolimits4web/Framework7#1366]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.3
* Platform and Target:  CORDOVA, IOS.

[screenshot](https://monosnap.com/file/asOvwaGQd3Fdo5NBFi0kR9e44vtGPo)

We built the app for ios with material theme. And we have some problem:
1. ripple wave is not hiding after tap on the tab and they overlap each other.
2. checkbox only works on a double tap
3. I do not understand how the status bar work? The remaining space between tabs.

**Comment by valnub** [comment]
Hi, can you post some screenshots, video or live demo to showcase the issues? Thanks

**Comment by navi8602** [comment]
This video problem [https://monosnap.com/file/YqcEyDyo7rLBYrUJJlRfe5P9PajimF](url)

**Comment by valnub** [comment]
@navi8602 Link returns a 404

**Comment by navi8602** [comment]
@valnub  Fix link

**Comment by navi8602** [comment]
https://monosnap.com/file/YqcEyDyo7rLBYrUJJlRfe5P9PajimF

**Comment by valnub** [comment]
I don't see these problems in the official demo http://framework7.io/kitchen-sink-ios/

So, the issue must be in your code. Can you provide it? Best is to use Codepen http://codepen.io/

**Comment by hesrun** [comment]
On the WEB there are no such problems.
Such problems have to build applications running IOS device.

**Comment by navi8602** [comment]
@valnub help please

**Comment by valnub** [comment]
Sorry, I don't know how to help without seeing the code

**Comment by navi8602** [comment]
In this video, there is a code and configuration that we use when you hold for two seconds and release, it works. With the rapid clicking does not work 

https://monosnap.com/file/S9MpWNU6olD7YNIcccyom2Nlgmi3k0

**Comment by navi8602** [comment]
@valnub If you do build a android then everything works wonderfully. For iOS experience difficulties

**Comment by valnub** [comment]
Are you using React or Framework7-React?

Also, can you post your code to Codepen? it's very hard to debug like this.

**Comment by valnub** [comment]
Are you using React or Framework7-react?
It's very hard to debug and see what's going on just based on the video.

**Comment by valnub** [comment]
Also, why are you setting checked to true in the click event?

**Comment by hesrun** [comment]
We use meteor js with framevork7.
Problem with active-state class, when i do fast tap on checkbox, or radio, or button, active-state class added to element, but after tap don't removed and ripple element note removed... If we make long tap, is it work. But we use default setting App...

**Comment by valnub** [comment]
It looks like your problem is rather related to your custom project architecture than being a F7 bug.

This Github page is only for reporting bugs in F7.

As far as I know there is no official support for Meteor in F7 anyways, so you're using it at own risk. F7 is best used with Vue.js, jQuery or Dom7/Template7.

If you seek for help with your code please ask on one of the following platforms. 

- [Official Framework7 forum](http://forum.framework7.io)
- [Stackoverflow](http://www.stackoverflow.com)

I'm sure that someone will be able to help you there. Make sure to post your full runnable code alongside your videos.

Good luck!

**Comment by navi8602** [comment]
@valnub We solved the problem with our probable! The cases were in the mobile-experience
In order for it to work fast click and rip it in the meteor you need to remove mobile-experience Package from the meteor

**Comment by MiguelQueiroz** [comment]
I have seen this issue in a pure F7 v2 project. Doing that fast click, on the close of the nav bar with modals, when clicking fast. But i dont have a sample to show.  But i have seen it..
