### ISSUE TITLE
preloader broken since 1.5.0 on vuejs app

### ISSUE THREAD

**Issue by xdadda** [nolimits4web/Framework7#1367]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.0
* Platform and Target: ALL (it's a webapp)

Hi guys. I've written a small app in vuejs and framework7 (directly, without framework7-vuejs).
It was working fine, until I've upgraded to 1.5.0/1.5.2. Since then the showPreloader(), picker and all modals in general don't seem to work anymore!
Any idea what could have happened? 

Note: I've reverted back to 1.4.2 and everything is back working fine!

**Comment by ZanderBrown** [comment]
I suggest if you wish to use Vue you use the bindings @nolimits4web provides https://github.com/nolimits4web/Framework7-Vue

**Comment by valnub** [comment]
Yes, better use official framework7-vue lib

**Comment by ZanderBrown** [comment]
@xdadda any response?

**Comment by xdadda** [comment]
response? still waiting for a reason why it's broken
of course there's framework7-vue, but that doesn't answer the original question

ps: just to clarify, framework7-vue works fine, but in some circumstances it's too limited vs the original

**Comment by ZanderBrown** [comment]
Well as we haven't seen any of your code that's hard to do.

**Comment by valnub** [comment]
How do you think F7-vue is limited? Maybe we can use your feedback to improve it.

**Comment by xdadda** [comment]
zanderbrown: you are right, I'll try to replicate on jsfiddle
valnub: well any slightly complex mix of functionalities ... for example virtual list + swipeout elements + infinite scroll is giving me some headache (ie swipeout events handling)

**Comment by xdadda** [comment]
here's the test code: https://github.com/xdadda/testapp
if I use framework7 1.4.2 then an alert box will be displayed at startup (see component Home.vue, mounted() hook)
if I upgrade framework7 no alertbox (or any other modal) is displayed

can't figure it out

**Comment by valnub** [comment]
I ran your app but there is no alert box popping up at startup although F7 1.4.2 is used. There must be an error somewhere else in your code.

**Comment by xdadda** [comment]
valnub: ehm ... my code doesn't use F7 1.4.2
to use 1.4.2 you need to change package.json from "framework7": "^1.4.2" to "framework7": "1.4.2"

**Comment by nolimits4web** [comment]
Please check the existing F7-Vue templates and what is new `root` parameter introduced in F7 since 1.5.0 which you should pass as same as your Vue root element. Also, i don't believe it is good idea to use `<body>` in the template and mount Vue app directly to body is also not allowed, use some separate root element like `<div id="root">`
