### ISSUE TITLE
Post Action to Save data in database

### ISSUE THREAD

**Issue by sushanttorankar** [nolimits4web/Framework7#1369]
hello,
I am using Framework7 for my web application in asp.net , but to save data to database i am using SQL Server 2012 database.
I guess there is code in .php and i am weak in php to understand.so is there any simplest way to use Framework7 Post Method with SQL server database ?

Thank You & Regards.

**Comment by valnub** [comment]
Sorry but this has nothing to do with Framework7. Please ask your question on a more generic platform like for example http://www.stackoverflow.com including more details as well as code examples.
