### ISSUE TITLE
Page multi-level problem

### ISSUE THREAD

**Issue by tanqiyuan** [nolimits4web/Framework7#1370]
My page has multiple levels，mainView.router.loadPage('*.html')，To the third time, how to return when not reload the previous page, because the first page has a lot of things, reloading things and no.Can only keep two records?

**Comment by valnub** [comment]
Sorry, I do not understand your question. Could you please:

- Clarify and give more details
- Post demo code on http://codepen.io
- Show screenshots or videos of the problem

Thanks

**Comment by ZanderBrown** [comment]
I think domCache may be the solution

**Comment by valnub** [comment]
Ah, now I get it. Thanks @ZanderBrown 

@tanqiyuan Have a look at inline pages https://framework7.io/docs/pages-inline.html

**Comment by tinyCoder32** [comment]
This will keep your first page in DOM.
```
var mainView = myApp.addView('.view-main', {
  domCache: true
})
```

**Comment by tanqiyuan** [comment]
@valnub @ZanderBrown @tinyCoder32  Thank you very much for your help!!!!!Although can not do.

**Comment by valnub** [comment]
![084](https://cloud.githubusercontent.com/assets/3787662/23588330/5648e41c-01bc-11e7-9482-5cae4cfa55ee.png)
