### ISSUE TITLE
1.5.3 back/forward browser buttons not working correctly, URL not updated

### ISSUE THREAD

**Issue by kimslawson** [nolimits4web/Framework7#1373]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.3
* Platform and Target: web browsers
* Live Link or JSFiddle/Codepen: http://slawson.org/kernelpanic/f7/

### What you did
* Made multiple pages (separate html page for each link). Tested clicking on them and using the header button to go back: OK.
* Set pushstate to true in F7 initialization.
* Tried to use the browser's back button to go back from one of the subpages: failed, goes back to page loaded before index.html. Tested in latest Chrome, Safari and Firefox on Mac OS 10.11.6

### Expected Behavior
Browser's back and forward buttons use navigation from F7. URL is changed when navigating between pages.

### Actual Behavior
HTML history is not modified by F7. When the browser's back button is pushed, the browser goes back to the site before this F7 site. The browser's forward button is disabled. Additonally, the URL isn't changed when navigating between pages.

I also see a couple issues open from earlier builds regarding history/pushstate that don't seem to be resolved.

**Comment by ZanderBrown** [comment]
Does the console show anything?

**Comment by kimslawson** [comment]
Nothing on the console when loading any of the F7-based pages or when navigating from page to page. When I manually reload a page I get "Navigated to [[URL-of-page]]" (in Chrome)

**Comment by kimslawson** [comment]
in myapp init I have

var myApp = new Framework7({ pushState:true });

**Comment by ZanderBrown** [comment]
Odd I've never had a problem with push state.
Have you got a view with class `view-main` initialised?

**Comment by kimslawson** [comment]
Indeed, My main div is       
`<div class="view view-main">`
in not only index.html but also subsequent pages loaded in by ajax. hosted online at http://slawson.org/kernelpanic/f7/

**Comment by ZanderBrown** [comment]
Navigation controls work fine on that [link](http://slawson.org/kernelpanic/f7/index.html)

**Comment by m0k1** [comment]
Yea works fine for me too @kimslawson .

**Comment by kimslawson** [comment]
Huh weird. Now it's working for me too, and I didn't change anything. Closing this issue; thanks.
