### ISSUE TITLE
Touch event simulation not working anymore after 1.5.3

### ISSUE THREAD

**Issue by tinyCoder32** [nolimits4web/Framework7#1374]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Hi, I have just upgraded to 1.5.3, unfortunately touch simulation event on Firefox and Chrome not working anymore, I can not use Pull to Refresh or the Swiper, Swipe Panel events.... etc.

1.5.2 Was working fine and I have never changed my settings after upgrade.

**Comment by valnub** [comment]
Hi, which Firefox/Chrome versions are you referring to? Also, which operating system?

**Comment by tinyCoder32** [comment]
Latest Firefox and Latest Chrome, on latest macOS Sierra.

**Comment by valnub** [comment]
I cannot reproduce this issue with latest Chrome on current macOS version:

- Chrome 56.0.2924.87 (64-bit)
- macOS 10.12.3
- Framework7 1.5.3 Kitchen Sink http://framework7.io/kitchen-sink-ios/

Are you sure that you have touch emulation enabled? Also, which application are you using for testing? Did you try in the official kitchen sink demo? Maybe it's a problem in your code.

**Comment by tinyCoder32** [comment]
Hi, I'm sorry that I didn't test the kitchen sink demo first, touch event simulation works on the demo.
I don't know why is this strange behavior appeared on my app just after upgrade, I did not change my code at all, just replaced the FW7 core files.

Do you think i should check some settings?

**Comment by valnub** [comment]
Are you sure that you upgraded all files (js and css) to 1.5.3? Maybe you missed one.

Also, you could check the changelog if you can find something there that causes the issue: https://github.com/nolimits4web/Framework7/blob/master/CHANGELOG.md

You might also wanna try to remove that `fastClicksExclude` config line and test if that fixes the issue.

As a last resort, remove everything from the config so your initialization looks like this:

```
var myApp = new Framework7();
```

If this fixes the problem, re-add each line one by one to see which one causes the problem.

**Comment by tinyCoder32** [comment]
Thank you for following, disabling `fastClicksExclude` solved the issue, although it was working normally before, I will see what I can know more.

Thanks again.

**Comment by valnub** [comment]
No problem, good luck :)
