### ISSUE TITLE
The Material status bar overlay should be 24px

### ISSUE THREAD

**Issue by Lazza** [nolimits4web/Framework7#1375]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.3
* Platform and Target: Cordova – Android

### What you did

I created a PhoneGap application running on Android API 21+ and then I explicitly enabled fullscreen using this code:

```
window.getDecorView().setSystemUiVisibility(
                        View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                                | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);
                window.setStatusBarColor(Color.TRANSPARENT);
```

To check the statusbar size, I temporarily set it to red:

`.statusbar-overlay { background-color: red; }`

### Expected Behavior

The status bar overlay should be 24px while using the Material theme.

### Actual Behavior

The status bar is set to 20px and a lot of other elements depending on it also use a padding or top position of 20px.

**Comment by macdonst** [comment]
@Lazza I'm a little confused as to what the problem is. Maybe you can post a screen shot that shows the issue?

**Comment by Lazza** [comment]
Yes, as I said before the height of `.statusbar-overlay` is wrongly set to 20px all over the CSS files of the Material theme:

![wrong](https://cloud.githubusercontent.com/assets/8294041/23342358/2cc18756-fc59-11e6-9058-766135747fba.png)

However, Android devices require a status bar 24px tall, which can be obtained by changing all relevant occurrences of `20px` with `24px` in the material style:

![right](https://cloud.githubusercontent.com/assets/8294041/23342371/4d6c65ca-fc59-11e6-9211-da731d668885.png)

My suggestion is to implement the correct size by default. If people need the material style on iOS (a bit weird but it might happen) they can either "mask" the problem by having the overlay with the same color as the navbar or another class might be needed.

**Comment by macdonst** [comment]
@Lazza are you using the statusbar plugin in your PhoneGap app?

**Comment by Lazza** [comment]
No, because that plugin doesn't support the status bar overlaying the WebView as per the release notes (although I am currently sending them a PR to enable that feature).

As you can imagine, the red color is only temporary. The final goal is to have the WebView contain a picture that will go under the status bar given that it is currently fully transparent. Of course if I wanted to have a solid color I would just disable the overlay and set the color programmatically.

**Comment by macdonst** [comment]
@lazza this cool. I just wanted to make sure I understood the bug. Link you status bar issue/PR here as well. I'm an apache Cordova core committee / Adobe Phonegap team member and I want this to work seamlessly for everyone.

**Comment by Lazza** [comment]
Great, thanks for your prompt responses. I am a bit inexperienced with Github, actually. For now I have added a link to my previous comments. Is there any other way I should link the PR here? Should I mention the PR number somewhere so that GitHub "sees" the link or something else?

**Comment by macdonst** [comment]
@Lazza I just meant you could add a link to your PR here in the issue but I found it.

https://github.com/apache/cordova-plugin-statusbar/pull/77
