### ISSUE TITLE
navbar with 3 parts doesn't work well in materil theme

### ISSUE THREAD

**Issue by xcchcaptain** [nolimits4web/Framework7#1378]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.2 
* Platform and Target: win10+firefox 
### What you did
 
![qq 20170228164814](https://cloud.githubusercontent.com/assets/5080022/23398013/c79484d6-fdd5-11e6-811d-2551b5168569.jpg)

### Expected Behavior
the center part should be at the center of navbar

### Actual Behavior
the center part just followed the left part

**Comment by ZanderBrown** [comment]
Have you initialized the view?

**Comment by nolimits4web** [comment]
According to official Material guidelines center part should follow the left part, not centered
