### ISSUE TITLE
use more than one tabbar,  .tab-link-highlight  width is wrong

### ISSUE THREAD

**Issue by nonenull** [nolimits4web/Framework7#1380]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.3
* Platform and Target:  all

Bug. See Code:
framework7.js line 6888

            function tabbarSetHighlight() {
                // use more than one tabbar,  .tab-link-highlight  width is wrong
                for(var i=0;i<tabbar.length;i++){
                    app.materialTabbarSetHighlight(tabbar[i]);
                }
            }

**Comment by ZanderBrown** [comment]
Can you further explain the bug to us @nonenull ?

**Comment by nonenull** [comment]
![qq 20170302111821](https://cloud.githubusercontent.com/assets/11241809/23491633/654bab18-ff3a-11e6-8edd-65d5197e2fb3.png)

**Comment by nonenull** [comment]
use multi tabbar in one page.  Page after initialization, we can see the .tab-link-highlight width is too short. 

it's count all .tab-link number to set .tab-link-highlight width
Reasonable approach should be to traverse tabbar, separately for each tabbar tag number, set .tab-link-highlight width

the formula is:
tabLinkWidth = 1 / tabbar.find('.tab-link').length * 100 + '%';

1 / 6 * 100 + '%'   is  16.6666...%

The right width should be
1 / 3 * 100 + '%'   is  33.33333...%

**Comment by ZanderBrown** [comment]
Odd it works fine [here](http://framework7.io/kitchen-sink-material/)

Can we see your HTML please? I can only assume having 2 tab bars with 3 tabs on one page is confusing it
