### ISSUE TITLE
Wrong position calculation for autocomplete dropdown in cordova iOS

### ISSUE THREAD

**Issue by kurni** [nolimits4web/Framework7#1381]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.3
* Platform and Target: CORDOVA (IOS ONLY)

### What you did
I ran kitchen-sink-ios' autocomplete.html on PhoneGap developer app and tapped on the Language field (under DROPDOWN WITH AJAX-DATA). This issue applies to all autocomplete fields, but I use the Language field as an example.
* If I position the field at the top of the screen, the dropdown appears correctly (please see 1.jpg and 2.jpg attached).
* However, if I position the field at the middle or bottom of the screen (which causes the entire screen to be pushed up after tapping the field - i.e. keyboard appears from the bottom of the screen), the dropdown appears far below the field - below POPUP STANDALONE AUTOCOMPLETE (please see 3.jpg, 4.jpg and 5.jpg attached).

### Expected Behavior
Dropdown appears right below the Language field.

### Actual Behavior
Dropdown appears far below the Language field - below POPUP STANDALONE AUTOCOMPLETE.

### Note
This issue seems to be specific to Cordova iOS (tested using PhoneGap developer app). I can't recreate the issue on Cordova Android nor browsers in various different platforms. Upon further investigation, it seems that the offset() function called in positionDropDown() returns unexpected "top" if the page got pushed up because of the keyboard appearing (only under PhoneGap developer app in iOS). The offset() function also returns other unexpected "top" for landscape layout (i.e. different pattern from portrait layout). Please let me know if I can help you further.

1.jpg
![1](https://cloud.githubusercontent.com/assets/1920298/23447989/9a3fee26-fea2-11e6-84a5-9e23ceb998ba.jpg)
2.jpg
![2](https://cloud.githubusercontent.com/assets/1920298/23447988/9a3f3cec-fea2-11e6-8448-15dd5a4356de.jpg)

3.jpg
![3](https://cloud.githubusercontent.com/assets/1920298/23447990/9a404808-fea2-11e6-847d-48c91ca2c51b.jpg)
4.jpg
![4](https://cloud.githubusercontent.com/assets/1920298/23447986/9a3eb59c-fea2-11e6-9138-7a64ff41e58c.jpg)
5.jpg
![5](https://cloud.githubusercontent.com/assets/1920298/23447987/9a3f182a-fea2-11e6-80bd-9afefc10d5ca.jpg)

**Comment by ZanderBrown** [comment]
Possible relation to #1337?

**Comment by kurni** [comment]
Hi @ZanderBrown ,
I think it's different as the .page-content class is present in dropdown, but the offset() calculation is not correct.

**Comment by ZanderBrown** [comment]
@kurni correct however they are both about misaligned autocomplete menus

**Comment by kurni** [comment]
@ZanderBrown You're right :)

**Comment by macdonst** [comment]
@kurni can you reproduce this in cordova-ios but not in the PhoneGap Developer app? I would like to rule out that the Dev app as the root cause. If it is a dev app issue we can handle it over on it's repo.

**Comment by kurni** [comment]
@macdonst Yes, I can reproduce this issue in the resulting compiled ios app if that's what you mean.

**Comment by kurni** [comment]
I can confirm that this issue has been fixed.
Thank you so much, Vladimir.
