### ISSUE TITLE
Wrong range selected in the datepicker

### ISSUE THREAD

**Issue by tatxini** [nolimits4web/Framework7#1385]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 1.5.3
* Platform and Target: Material theme & iOS Theme.

### What you did
Select a date from range datepicker

### Expected Behavior
When you select the range, all days shoud be selected in the calendar.

### Actual Behavior
The last day on some cases is not marked, but the date above is correct.

This issue is reproducible in the kitchen sink, both material theme and iOS theme.
The gif shows some examples with the wrong behavior, and the last one is the expected behaviour.

![bug range calendar f7](https://cloud.githubusercontent.com/assets/25824042/23506536/1045c496-ff49-11e6-91b5-6813ff4df309.gif)

**Comment by nolimits4web** [comment]
Well, for some reason i can not replicate it and it works fine for me. Can anyone confirm there is such issue cc @valnub @ZanderBrown

**Comment by valnub** [comment]
I can't replicate it in the online Kitchen Sink demo at http://framework7.io/kitchen-sink-material/ using Google Chrome on latest macOS.

@tatxini Which browser and OS are you using?

**Comment by valnub** [comment]
Yes, I can replicate it using Google Chrome on macOS.

The problem only occurs if you select exactly the same date range as in the gif (March 16th-30th).

On other date it works correctly.

**Comment by valnub** [comment]
I also see another problem in the date picker. When I click on a day, it will not always select the day (nothing happens). Sometimes I have to click multiple times on a day and then it will select it. I remember that someone posted about a change in Google Chrome that breaks clicking behavior in F7. Don't remember that post tho. This problem does not exist in other browsers, e.g. Firefox. Other users also reported similar issues with components not always reacting when clicked.

**Comment by macdonst** [comment]
I can reproduce it as well but I haven't discovered what the magic combination is. The first few date ranges I select work fine then eventually the date range stops highlighting the last day.

**Comment by nolimits4web** [comment]
Still works fine for me 😞 What is environment. I'm checking at:
http://framework7.io/kitchen-sink-material/
macOS 10.12.3
Chrome OSX 56.0.2924.87 (64-bit) (with both emulating mobile device (android) and not)

**Comment by Tarekajaj** [comment]
Was about to post about this issue, Happens for me on windows 7 64bits, chrome 56.0.2924.87 and on firefox 51.0.1. Also I can reproduce it on iPad pro v10.2 & a Samsung Note 5 running android 6.0.1

**Comment by Tarekajaj** [comment]
Try a range from 15 to 31 march 2016 or october 2016.

**Comment by valnub** [comment]
- http://framework7.io/kitchen-sink-material/
- Chrome 56.0.2924.87 (64-bit)
- macOS 10.12.3
- No emulator

Make sure to follow the steps exactly:
- Open kitchen sink (Material)
- Select Calendar
- Scroll down to select range
- Click on 15
- Click on 30

**Comment by Tarekajaj** [comment]
This seems to affect march and october only

**Comment by Tarekajaj** [comment]
I think I found the cause: whenever daylight saving dates are in the selected range the issue happens.

**Comment by valnub** [comment]
😂 That would be funky but sounds plausible since Vladi is in Russia. Do you have daylight saving time over there?

**Comment by ZanderBrown** [comment]
Followed @valnub 's steps. Can confirm bug on: `Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3013.3 Safari/537.36`

Might be something in the daylight saving theory, the UK changes from GMT (+0000) to BST (+0100) on the 26th which is, of course, between the 15th and 16th of March

**Comment by macdonst** [comment]
OMG! Another thing we can blame on daylight savings time.

**Comment by nolimits4web** [comment]
Wow, that is why it works fine for me

**Comment by nolimits4web** [comment]
Ok, i believe we already fixed it by @Tarekajaj PR

**Comment by hz2030** [comment]
www.3aiqi.com
