### ISSUE TITLE
Add an .editorconfig file

### ISSUE THREAD

**Issue by macdonst** [nolimits4web/Framework7#1387]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

The project should have a .editorconfig file to prevent whitespace issues like in PR #1386 from happening. For example [here is the one I use](https://github.com/phonegap/phonegap-plugin-push/blob/master/.editorconfig).

Editorconfig is already integrated in most popular code editors.

If folks agree, I can send a PR.

**Comment by nolimits4web** [comment]
@macdonst folks agree :)

**Comment by macdonst** [comment]
@nolimits4web PR sent
