### ISSUE TITLE
How to reinitialize after appending RTL style dynamically?

### ISSUE THREAD

**Issue by tinyCoder32** [nolimits4web/Framework7#1389]
Hi, I need to append the RTL style without reloading the page, I use:

`$$('head').append("<link rel='stylesheet' id='rtl-style' href='http://mywebsite.com/css/f7.rtl.min.css' type='text/css'>");`

But a lot of problems appear with animations between tabs and on search bar and so on.. I tried using `myApp.init()` and `myApp.params.rtl = true` after appending the style but it didn't help, how do I tell F7 that I did append the RTL style to interact with it?

Thanks.

**Comment by tinyCoder32** [comment]
I tried `myApp.rtl = true` and saw it changed in the developer toolbox DOM viewer, now page animations and tabs direction are good, but search bar still adds `margin-left` to the `Cancel` button instead of `right` (as example). maybe there is another parameter I should change too?

**Comment by ZanderBrown** [comment]
you probably need to reinitialize the search bar

**Comment by nolimits4web** [comment]
Yes, as @ZanderBrown stated, searchbar should be reinitialized as well. But it is not recommended to change it on the fly, it is better to reload the page and init app again with rtl styles
