### ISSUE TITLE
About using ReactJS And ReactRouter

### ISSUE THREAD

**Issue by tanqiyuan** [nolimits4web/Framework7#1394]
excuse me ! 

I use ReactJS combined with Framework7，Use the default Ajax routing system will produce a lot of HTML files.

I want to load a new page in the form of a component.

Did any of the guys use ReactRouter to route? The use of ReactRouter in the animation is tricky.

thanks!  I can't VueJS,don't need to introduce him.

**Comment by valnub** [comment]
You should use Framework7-react: https://github.com/bencompton/framework7-react
