### ISSUE TITLE
function trim BUG 

### ISSUE THREAD

**Issue by yoke1990** [nolimits4web/Framework7#1396]
when I use Smart Select on Chrome
code:   
            function watchChangeState(e) {
                /*jshint validthis:true*/
                var i = $(this), value = i.val();
                var type = i.attr('type');
                if (notInputs.indexOf(type) >= 0) return;
                var els = i.add(i.parents('.item-input, .input-field')).add(i.parents('.item-inner').eq(0));
                if (value && value.trim() !== '') {
                    els.addClass('not-empty-state');
                }
                else {
                    els.removeClass('not-empty-state');
                }
            }
error:
framework7.js:8301   Uncaught TypeError: value.trim is not a function

**Comment by ZanderBrown** [comment]
Can you provide a CodePen or jsFiddle?

**Comment by yoke1990** [comment]
js Fiddle:/dist/js/material-inputs.js
http://material.framework7.cn/   
then open Form->Smart Select
when select car option, you will see the bug.
The interesting thing is that if iOS doesn't happen

**Comment by macdonst** [comment]
Yeah, this is reproducible. The `watchChangeState` function is getting called twice.

**Comment by ZanderBrown** [comment]
So is it confirmed?

**Comment by macdonst** [comment]
@ZanderBrown yeah confirmed. The hack would be:

```
if (value && value.trim && value.trim() !== '') {
```

but I don't understand why it fires twice so far and now I'm off to lunch and will probably forget about everything.

**Comment by ZanderBrown** [comment]
Excuse me whilst i do things in the future
![image](https://cloud.githubusercontent.com/assets/17074021/23762441/da2d8b14-04ed-11e7-966d-6e7485208667.png)

**Comment by nolimits4web** [comment]
Fixed, it fires twice because: first time on checkbox input and second on related smart select's select

**Comment by QuangHoang** [comment]
Have you committed the fix?
