### ISSUE TITLE
Bounce effect

### ISSUE THREAD

**Issue by projetoarduino** [nolimits4web/Framework7#1398]
Hi i want remove bounce overscroll effect in ios (On android this does not happen)

I have another project in my ios using materalizecss And it does not have that effect.

I believe it's something in css but I did not find anything related in the files.

If I remove this part of the project 

link rel="stylesheet" href="css/framework7.ios.css"

it loses all the styles and continues with the scroll and the bounce effect disappears

**Comment by ZanderBrown** [comment]
You can add iNoBounce or similar

**Comment by projetoarduino** [comment]
Inobounce no work 100%

**Comment by ZanderBrown** [comment]
Well use another then but @nolimits4web has made it clear on many occasions it's not something he plans to include

**Comment by projetoarduino** [comment]
What I mean is that I do not think the bouce effect is native to ios, as I said earlier I have other projects running on ios that do not appear in the bouce effect

**Comment by ZanderBrown** [comment]
the bounce effect is native to webkit, the engine that displays all web content on iOS.

Therefore all pages will have it unless it's defeated with techniques like iNoBounce
