### ISSUE TITLE
Not showing tapped item in input autocomplete

### ISSUE THREAD

**Issue by edukondalu123** [nolimits4web/Framework7#1399]
I am able to select the dropdown of autocomplete. But that selected element is not rendering in input.
May i know the reason?

**Comment by edukondalu123** [comment]
May i get your attention? Please

**Comment by macdonst** [comment]
@edukondalu123 please follow the issue template and you will get a better response.

**Comment by ZanderBrown** [comment]
Examples help

**Comment by intissar12** [comment]
any news here ! i have the same problem plzz help
