### ISSUE TITLE
Not able to go back to the first page after opening many pages

### ISSUE THREAD

**Issue by mohamadfala** [nolimits4web/Framework7#1401]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: Framework7 1.4.0
* Platform and Target: Cordova

### What you did
I created multiple pages, let's say 3 for now.
index.html (page1) -> results.html (page2) -> user.html(page3)

### Expected Behavior
Page 2 should go back to page 1
### Actual Behavior
I'm able to go to all of the pages, go back from page 3 to page 2, and then when I hit the back button from the navbar of page 2 it doesn't go back to page 1.

I tried to use Router API, but whenever I access page 3 and go back to page 2, going back to page 1 is not possible.

P.S if I don't open page 3, page 2 can go back to page 1

**Comment by ZanderBrown** [comment]
Could you share a Gist demonstrating the problem?

**Comment by ZanderBrown** [comment]
Does the problem occur with the latest F7? (you said your using 1.4)

**Comment by mohamadfala** [comment]
I've created a Gist containing the html files for the 3 pages.
[](https://gist.github.com/mohamadfala/3c8611d870f5c84ae67c399beb3d8658
)
The Javascript files, contains Ajax requests to show data on the results page.

To move to the user page and send more data, I'm using href="user.html?firstname=name&..."
and then get the data by url_query in user.html.

I didn't use any router API to navigate within these pages, so it has the original settings for navigating back in pages.

Regarding the latest version, I used Phonegap to download the template automatically I thought it was the latest one.


I also attached a video showing you the actual behavior:
[](http://mohamadfala.com/nimbus-record-video.webm
)

**Comment by mohamadfala** [comment]
And I tried to update to the latest F7 just now, and still no luck.
(I copied the JS files from the dist folder after downloading the latest version and replaced the old ones I had) is this the right way to use the latest version?

**Comment by ZanderBrown** [comment]
should work but i would recommend copying the css as well

**Comment by mohamadfala** [comment]
Copying the CSS will result in losing the previous styling I made.
Isn't there anything else I need to do?

**Comment by mohamadfala** [comment]
I also tried it, but still not working.

**Comment by J05HI** [comment]
I've the same problem but it's not very often. 
Don't know when and why

**Comment by J05HI** [comment]
It's in the boilerplate too if you enable push state.

**Comment by mohamadfala** [comment]
Closing this issue as there was no support yet, and seems like I'm gonna have to search for an alternative way to make that back button works.
Thanks anyways.

**Comment by nolimits4web** [comment]
You have wrong HTML layout, all modals (popup, etc.) should be direct children of body of app root element

**Comment by ZanderBrown** [comment]
Whoa give us a chance, saying you've had no support is wrong as I responded requesting more information almost immediately 

Please remember that other than @nolimits4web when he's given donations are completely unpaid for the time we spend maintaining Framework7 and as such can't always give in-depth responses as quick as you might like

**Comment by mohamadfala** [comment]
I didn't mean it this way, and I truly appreciate what you're doing guys, and I'm not even allowed to judge!

My point is that I have to figure out a solution asap, and I don't have the right to bother you and ask you for it, so I decided to look around hopefully I might be able to fix it.

And regarding @nolimits4web 's message, can you explain it please? I'm new here, I haven't build mobile apps before, this is my first time using F7, and I adore how it makes it easier for us to make a stunning mobile app.

The popup, and the login screen are in the index file, right after the closing tag of the page-content, where shall I put them?

And how is that affecting the back navigation after going to the third page?

Sorry again.

**Comment by nolimits4web** [comment]
Pop up and login screen are inside of "pages" div as I see in you file, they should be inside of body

**Comment by mohamadfala** [comment]
Thank you so much! It's not an issue at all, it was my bad!
Sorry again and thank you so so much!!!!!!!!!!!

It's working perfectly!

**Comment by J05HI** [comment]
And why is the bug in the kitchen sink too? 
I can't be the layout

**Comment by nolimits4web** [comment]
@J05HI i can't see such bug in kitchen sink. How to replicate it?

**Comment by J05HI** [comment]
@nolimits4web 
Only with push state and navigation with browser back button.

**Comment by J05HI** [comment]
I can make a video
