### ISSUE TITLE
Dynamic popup and page does not work on Android (all good in iOS/web though)

### ISSUE THREAD

**Issue by peterel** [nolimits4web/Framework7#1408]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.0
* Platform and Target: CORDOVA/ANDROID

### What you did
Ive been able to get a dynamic popup and page to open/load on iOS. In fact Ive released this app using Cordova and Framework7. But, trying the same app on an Android Emuluator or even device is yielding unexpected/broken behavior. Ive elaborated a bit more on SO before I realized that I probably should post it here. http://stackoverflow.com/questions/42749797/framework7-popup-or-page-with-dynamic-content-does-not-work-on-android

### Expected Behavior
Expected behavior is that dynamic popup and pages should act same on Android, i.e. open/load.

### Actual Behavior
Nothing happens from what I can see. E.g. I do enter the code where the popup is created but it does not seem to fire.

Looking forward to resolving this. Thanks.

**Comment by ZanderBrown** [comment]
Material or iOS theme?

**Comment by peterel** [comment]
iOS theme. Do you think that is the cause?

**Comment by ZanderBrown** [comment]
Shouldn't be the cause but the HTML layout differs between the two.

**Comment by peterel** [comment]
Didn't think theme could be the cause either but its tricky to tell sometimes. So, I assume you've not come across this before? I've at least not found references to issues such as this.

**Comment by nolimits4web** [comment]
Looks like something wrong with HTML content you are trying to pass to methods. Would be good to see live example or more code examples

**Comment by peterel** [comment]
Sure. Game as webapp can be played here, http://34.250.179.3/ (just make sure to set your browser to emulate phone/tablet) or downloaded from app store https://itunes.apple.com/us/app/push-penguin/id1210906366?mt=8.

Sample of a page that works on iPhone and web (Chrome) but not on Android device:

 ```
var userHTML =
    '<div class="view">' +
    '<div class="pages">' +
    '<div data-page="user" class="page navbar-fixed toolbar-fixed">' +
    header +
    '<div class="page-content">' +
    '<div class="content-block">'+
    '<div class="list-block inset">' +
    '<ul>' +
    '<li>' +
    '<div class="item-content">' +
    '<div class="item-media"><i class="icon f7-icons">person</i></div>' +
    '<div class="item-inner">' +
    '<div class="item-input">' +
    '<p style="margin:0; padding:0;">' +
    userInfo["username"] +
    '</p>' +
    '</div>' +
    '</div>' +
    '</div>' +
    '</li>' +
    '</ul>' +
    '</div>' +
    user1to5Place +
    myPosition +
    '</div>'+
    '</div>'+
    footer +
    '</div>' +
    '</div>' +
    '</div>';

     mainView.router.load({
    content: userHTML,
    animatePages: true
     });
```
Where e.g. the header variable is constructed as such:
```
function userPageHeaderFunction() {
    var header =
	'<div class="navbar">' + 
	'<div class="navbar-inner">' +
	'<div class="left">' +
	'<a href="" class="navbarGear">' +
	'<i class="f7-icons">gear</i>' +
	'</a>' +
	'</div>' +
	'<div class="center">Me & I</div>' +
	'<div class="right">' +
	'<a href="" class="navbarIcon">' +
	'<i class="f7-icons">info</i>' +
	'</a>' +
	'</div>' +
	'</div>' +
	'</div>';
    return header;
}
```

**Comment by peterel** [comment]
Hmm, several things seem a bit shaky moving over to Android dev compared to iOS here. The welcomescreen plugin fires a bit randomly, the admob ad dismiss also closes open popup in the background and the animation is significantly more laggy. Is it simply a bit more tricky to get things to work on Android than on iOS? Ive previously used Cordova with goratchet but dont remember it being such a leap to get Android up and running. Any tips on what I may be doing wrong? Or is simply Framework7 "better"/easier towards iOS?

**Comment by peterel** [comment]
Hi, sorry, seems its a programming bug from my end! Was disguised under a gradle issue on Android Studio under path issue on Android under findIndex (which works on Safari but not on Chrome mobile). The really really tricky thing here is that it worked sometimes, very confusing. Im still not "done" but I dont think it has anything to do with Framework7 at this point. Will ping back if I figure out otherwise. Closing.
