### ISSUE TITLE
Android Blur on bottom of left panel, while scrolling

### ISSUE THREAD

**Issue by phanivaranasi** [nolimits4web/Framework7#1415]
Hi Team,
Using left panel, content at bottom is getting blur.
![screenshot_2017-03-15-15-52-21](https://cloud.githubusercontent.com/assets/6230353/23946265/c6531378-099f-11e7-93d4-e72495fe4247.png)
![screenshot_2017-03-15-17-02-06](https://cloud.githubusercontent.com/assets/6230353/23946659/460ea518-09a1-11e7-9be4-c80c349cde29.png)

In above screen shot, it can be observed bottom two links are getting blur.
Can any one help me in fixing this.

Thanks
Krishna

**Comment by ZanderBrown** [comment]
Interesting, can you provide some code?

**Comment by phanivaranasi** [comment]
@ZanderBrown 
Below is my code related to left panel

`<div class="panel panel-left panel-cover" ng-controller="leftPanelController">
        <div class="view navbar-fixed">
            <div class="pages">
                <div class="page" data-page="panel-left" ng-init="initUserNav()">
                    <div class="toolbar toolbar-bottom">
                        <div class="toolbar-inner">
                            <a ng-click="shareApp()" class="link">
                                <i class="material-icons">share</i>
                            </a>
                            <a href="#" class="link">
                                <i class="material-icons">feedback</i>
                            </a>
                        </div>
                    </div>
                    <div class="page-content zeroPaddingTop">
                        <div class="menu-user-content bg-cyan">
                            <div class="menu-user-image-wrapper">
                                <div class="menu-user-image">
                                    <script>
                                        function altImage() {
                                            var img = app.$$('#patientImage');
                                            if(app.rootScope.patientDetails.gender === "Male") {
                                                img.attr('src', 'app_images/male.jpg');
                                            } else if(app.rootScope.patientDetails.gender === "Female") {
                                                img.attr('src', 'app_images/female.jpg');
                                            } else {
                                                img.attr('src', 'app_images/other.png');
                                            }
                                            img.onerror = "";
                                        }
                                    </script>
                                    <img id="patientImage" ng-src="{{patientDetails.image}}" onerror="altImage()"/>
                                </div>
                            </div>
                            <div class="menu-user-info">
                                {{patientDetails.patientName | titleCase}}
                            </div>
                        </div>
                        <div class="list-block menu-list accordion-list zeroMargin">
                            <ul>
                                <li>
                                    <a href="{{urls.dashboard}}" class="close-panel">
                                        <div class="item-content">
                                            <div class="item-media"><i class="fa fa-home" style="color:#166d85"></i></div>
                                            <div class="item-inner">
                                                <div class="item-title">Home</div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{{urls.depAppointment}}" cl class="close-panel">
                                        <div class="item-content">
                                            <div class="item-media"><i class="fa fa-calendar" style="color:#558115"></i></div>
                                            <div class="item-inner">
                                                <div class="item-title">Book Appointment</div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{{urls.viewAppointment}}" cl class="close-panel">
                                        <div class="item-content">
                                            <div class="item-media"><i class="fa fa-eye" style="color:#795548"></i></div>
                                            <div class="item-inner">
                                                <div class="item-title">View Appointment</div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{{urls.allergy}}" cl class="close-panel">
                                        <div class="item-content">
                                            <div class="item-media"><i class="fa fa-warning" style="color:#ff9800"></i></div>
                                            <div class="item-inner">
                                                <div class="item-title">Allergies</div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{{urls.diagnosis}}" cl class="close-panel">
                                        <div class="item-content">
                                            <div class="item-media"><i class="fa fa-user-md" style="color:#03a9f4"></i></div>
                                            <div class="item-inner">
                                                <div class="item-title">Diagnosis</div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{{urls.medication}}" cl class="close-panel">
                                        <div class="item-content">
                                            <div class="item-media"><i class="fa fa-medkit" style="color:#ef2e2e"></i></div>
                                            <div class="item-inner">
                                                <div class="item-title">Medication</div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{{urls.calculators}}" cl class="close-panel">
                                        <div class="item-content">
                                            <div class="item-media"><i class="fa fa-calculator" style="color:#673ab7"></i></div>
                                            <div class="item-inner">
                                                <div class="item-title">Calculators</div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                            <ul>
                                <li>
                                    <a class="close-panel" ng-click="aboutUs()">
                                        <div class="item-content">
                                            <div class="item-media"><i class="fa fa-map-marker" style="color:#6d7aa5"></i></div>
                                            <div class="item-inner">
                                                <div class="item-title">Location</div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="close-panel" ng-click="aboutUs()">
                                        <div class="item-content">
                                            <div class="item-media"><i class="fa fa-info-circle" style="color:#0b78d8"></i></div>
                                            <div class="item-inner">
                                                <div class="item-title">About Us</div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="close-panel" ng-click="settings()">
                                        <div class="item-content">
                                            <div class="item-media"><i class="fa fa-gear" style="color:#272727"></i></div>
                                            <div class="item-inner">
                                                <div class="item-title">Settings</div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="close-panel" ng-click="logout()">
                                        <div class="item-content">
                                            <div class="item-media"><i class="fa fa-sign-out" style="color:#777777"></i></div>
                                            <div class="item-inner">
                                                <div class="item-title">Logout</div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>`

**Comment by nolimits4web** [comment]
Not sure what happens but looks like device rendering issue. Do you see same issue on another android device, have you tried to use Crosswalk?

**Comment by phanivaranasi** [comment]
@nolimits4web Its seems to be device rendering issues!! In other devices I'm facing similar issue.
I'm closing this issue.
