### ISSUE TITLE
Calendar onDayClick function returning wrong month

### ISSUE THREAD

**Issue by odesey** [nolimits4web/Framework7#1419]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.3, 1.5.4
* Platform and Target: Material Android.
* Live Link or JSFiddle/Codepen: https://jsfiddle.net/hLhL42a0/1/

### What you did
Click/Select a day in the inline calendar.

### Expected Behavior
`onDayClick` function should return the date of the selected/clicked day.

### Actual Behavior
The date returned is one month behind. If I select 3-10-2017, the `onDayClick` function returns 2-10-2017

**Comment by ZanderBrown** [comment]
Months, as is standard in most languages including JavaScript, starts at 0

So

| Month | Value |
| --- | -- |
| January | 0 |
| February | 1 |
| March | 2 |
| April | 3 |
| May | 4 |
| June | 5 |
| July | 6 |
| August | 7 |
| September | 8 |
| October | 9 |
| November | 10 |
| December |  11 |

**Comment by odesey** [comment]
Thanks for the response.
For anyone else who runs into the same issue, the date can be adjusted with momentjs:

```javascript

      onDayClick: function (p, dayContainer, year, month, day) {
        console.log(moment([year, month, day]).month(month).format("LLL"))
      }
```
