### ISSUE TITLE
Issue with popup modal on IOS

### ISSUE THREAD

**Issue by sleimanx2** [nolimits4web/Framework7#1424]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 1.5.2.
* Platform and Target: PHONEGAP IOS.

### What you did
Testing popup with ios - vue - framework 7 on iphone se

### Expected Behavior
Expected the modal to fill the screen 

### Actual Behavior
The popup modal is not filling the screen

the issue is illustrated in this video https://youtu.be/R6MmXfgh4tQ?t=26m12s

**Comment by ZanderBrown** [comment]
Can anyone confirm? I see the video is by @valnub

**Comment by valnub** [comment]
Yes :)

I don't remember every detail of that code but I think it was something with the popup modal defined as a direct child of `div#app` https://github.com/valnub/Twitvue04/blob/master/src/home.vue

Maybe the popup needs to be defined somewhere within a view or page?

**Comment by ZanderBrown** [comment]
Not being familiar with vue i wouldn't know.

@nolimits4web any thoughts?

**Comment by nolimits4web** [comment]
We can close it. Just keep correct layout structure and it should be fine
