### ISSUE TITLE
Detect if browser supports Framework7

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7#1430]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

Hi Vladimir, is there any way to detect if the browser supports Framework7 or not? Neither in device API nor support API I found something. For example, IE 11 does not support Web Apps, Google Chrome does it well. So there should be any variable with true/false to use and show alerts according the status. Regards, Dennis

**Comment by ZanderBrown** [comment]
Define

> IE 11 does not support Web Apps

**Comment by scriptPilot** [comment]
@ZanderBrown - If I open an Framework7 app in IE 11, I have a black page with small grey menu on top - but no more. Open the same in Chrome, there is no issue. Dennis

**Comment by ZanderBrown** [comment]
I don't currently have access to IE11 but using [IE NetRenderer](https://netrenderer.com/index.php) to load [Kitchen Sink](http://framework7.io/kitchen-sink-ios/) produces:
![image](https://cloud.githubusercontent.com/assets/17074021/24093400/8876f236-0d4b-11e7-9198-18bcbbdcd6c8.png)

**Comment by scriptPilot** [comment]
@ZanderBrown - Please find attached my result for Internet Explorer 11.0.9600 on Windows 7
![screenshot 001](https://cloud.githubusercontent.com/assets/19615586/24146412/e429c17c-0e35-11e7-9501-cadaf1b2d71b.png)

**Comment by nolimits4web** [comment]
Are you sure it is related to F7? I see your errors are because of none supported "Object.assign" method. F7 doesn't use this method

**Comment by akikochuchu** [comment]
Thank

**Comment by scriptPilot** [comment]
@nolimits4web - Did you test on IE 11 - or, should it even work in IE 11?

**Comment by akralj** [comment]
Hi, 
this is not an issue with framework7, but with framework7-vue. 
Object.assign is used there in 4 places ([see this link](https://github.com/nolimits4web/Framework7-Vue/search?utf8=✓&q=Object.assign&type=))

Using this polyfill fixed it for me:
https://github.com/rubennorte/es6-object-assign
It would be great to add this to framework7-vue to make ie 11 happy.

**Comment by ZanderBrown** [comment]
@akralj could you post this over at the f7-vue repo?
