### ISSUE TITLE
[BUG] Swipe actions don't work anymore

### ISSUE THREAD

**Issue by J05HI** [nolimits4web/Framework7#1432]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: master branch
* Platform and Target: Chrome on Android

### What you did
Normal swipe to delete or swipeable tabs in the kitchen sink.

### Expected Behavior
The swipe action works as before.

### Actual Behavior
It does nothing. Can't swipe anymore.

**Comment by ZanderBrown** [comment]
Seems to work for me. Can anyone confirm?

**Comment by nolimits4web** [comment]
Works for me as well

**Comment by J05HI** [comment]
@nolimits4web @ZanderBrown 
Really on the master branch? 
1.5.4 is working.

**Comment by ZanderBrown** [comment]
i'll rebuild later but at present yes

**Comment by nolimits4web** [comment]
Okay, on Master branch issue was presented. Fixed by e748fee0c03442bf56730ab3de6ddd2f6d238e81

**Comment by J05HI** [comment]
Thanks!

**Comment by J05HI** [comment]
@nolimits4web @ZanderBrown 
Sorry, I've tested it and the swipe to delete is working fine again but the PhotoBrowser/SwiperSlider and the swipeable tabs don't work as before.

**Comment by ZanderBrown** [comment]
Okay then reopening

**Comment by J05HI** [comment]
@nolimits4web @ZanderBrown @valnub 
Please mark this as high priority.

**Comment by nolimits4web** [comment]
Fixed by dd5eed0397d7a6fd81b0a7d30d1ac3e762f234f2
