### ISSUE TITLE
Trigger to refresh tabs loaded dinamically

### ISSUE THREAD

**Issue by vousys** [nolimits4web/Framework7#1433]
Hi! I'm using the latest library 1.5.4
This is my question, I need to create  full dinamically the nav tab and the content of the tab, via ajax.
I saw that with the ROUTER api, I can load views, but how can I load only a part of a view? because if I append the html to the page, the tabs not work as a tab (I saw one div next to the other)

Ej: 
This is my html

```

<div data-page="restaurante-home" class="page toolbar-fixed">
  <div class="navbar">
    <div class="navbar-inner">
      <div class="left"><a href="index.html" class="back link icon-only"><i class="icon icon-back"></i></a></div>
      <div class="center">TITULO</div>
      <div class="right"><a href="carrito.html" class="link icon-only"><i class="material-icons">shopping_cart</i></a></div>
    </div>
  </div>


  <div class="toolbar tabbar">
    <div class="toolbar-inner"><!-- contenido dinamico !--></div> 
  </div>


  <div class="tabs-swipeable-wrap">
    <div class="tabs">
      <!-- contenido dinamico !-->
    </div>
  </div><!-- tabs-swipeable-wrap !-->
  
</div>
```

and this my JS:
```
myApp.onPageInit('restaurante-home', function (page) {
  
    // Asigno titulo a la pantalla
    $$(".navbar-inner").html ("Restaurante");


    // Creo los tabs con las categorias de los productos
    $$(".toolbar-inner").empty();
    $.getJSON("https://ipinfo.io/64.233.191.255/json",{},function (data){
            var i     = 0;
            var html  = "";

       $.each(data, function(k, v) {

                // El nav del tab
                  html = '<a href="#tab-'+i+'" class="'+(i==0?'active': '') +' tab-link">'+k+'</a>';
                  $$(".toolbar-inner").append(html);


                  // Contenido del tab
                  html='<div id="tab-'+i+'" class="page-content tab '+(i==0 ? 'active': '') +'">' +
                    '<div class="content-block">' +
                    '  <p>This is tab '+i + ' <br /> '+ k + ' content</p>' +
                    '  <p>'+v+'</p>' +
                    '</div>' +
                  '</div><!-- tab !-->';

                   $$(".tabs").append(html);

                  i++;
            });
      }) ; 
});
```

**Comment by ZanderBrown** [comment]
Template7 / preprocess / PHP / ASP maybe more suitable than onPageInit

**Comment by vousys** [comment]
Thanks! And one more question. 
How can I manage the "onClick" function to that dinamyc page.
Ex:

`         <script type="text/template7" id="carrito-seleccion-productos-template">
              <div data-page="{{page_name}}" class="page toolbar-fixed">
                        <div class="navbar"> 
                            <div class="navbar-inner"> 
                               <div class="left"><a href="index.html" class="back link icon-only"><i class="icon icon-back"></i></a></div> 
                               <div class="center">{{titulo}}</div> 
                               <div class="right"><a href="carrito.html" class="link icon-only"><i class="material-icons">shopping_cart</i></a></div> 
                           </div> 
                       </div>  
                                  
                                  
                       <div class="toolbar tabbar">
                            <div class="toolbar-inner">{{tabs_navigation}}</div> 
                       </div>
                                
                       <div class="tabs-swipeable-wrap">
                            <div class="tabs">{{tabs_contenido}}</div> 
                       </div> 

                       <a href="#" class="btn-add floating-button color-red"><i class="icon icon-plus"></i></a>
                </div>
        </script>  
`

I try this, but nothing happens:

`
function restaurante_home_btn_add() {
  alert("click en btn");
}

$$('#content-restaurante_home .btn-add').on('click', restaurante_home_btn_add);`

**Comment by nolimits4web** [comment]
Try:
```js
$$(document).on('click', '#content-restaurante_home .btn-add', restaurante_home_btn_add);
