### ISSUE TITLE
Ajax call to the same Page in Framework7

### ISSUE THREAD

**Issue by guigiani** [nolimits4web/Framework7#1434]
Hi there,

Im currently developing a project using Framework7 and it is actually at the very first stage. I have implemented a [login-screen modal-in] view along with the main view in my index.html page (to handle the Login screen)

Everything works fine actually, the first screen that pops up is the login screen as expected, and as soon as I click on login it pops down and the index screen (main) shows up.

I've noticed a strange behavior which is, as soon as the index page is loaded, if I click on the home button (which is a link with href to the index.html page) it performs the ajax call to the index.html page even though it is actually the page that is currently being displayed.

I've been reading some articles here and could be something to do with the framework initialization, perhaps I've tried the proposed hints and could not overcome this issue.

Obs.: If I click on another link, which will refer to another page, then go back to index page I can click as many times as I want that the ajax won't reload it.

My index.html and app.js are attached.

[index.html.txt](https://github.com/nolimits4web/Framework7/files/855902/index.html.txt)
[app.js.txt](https://github.com/nolimits4web/Framework7/files/855904/app.js.txt)

Framework version is v1.5.3

Please let me know if you need more details.
Any help is more than appreciated.
BR,
Gui

**Comment by chalchis** [comment]
It would be more useful if you would show a sketch of what you want to apply

**Comment by guigiani** [comment]
Well,

I guess it's more like what I want to avoid. Need to understand why at the first time the index.html page is loaded, if I click on the option that will refer to itself, it recalls the same page while next times I click it won't.

Please check the code for further details.

**Comment by jdf221** [comment]
I think this is because Framework7 is using the full URL of the page to identify it.

So when you first load your app the page it's on is `http://path.to/page/index.html` and when you click your link with `href="index.html"` the new page is just `index.html` with no path. Since the url (`index.html`) doesn't match the original page url (`http://path.to/page/index.html`) it makes a request to the page.

Quick test of this:

https://www.youtube.com/watch?v=ozgnowj--MA

So the easiest fix would be to just replace your index button with a full path link.

**Comment by guigiani** [comment]
Thanks @jdf221 your solution works (not really charming) more like a workaround. This situation I think it's really linked with this thread https://github.com/nolimits4web/Framework7/issues/28#ref-commit-4c47ac5

I tried initiating the API manually perhaps I get the error that $$ is not a function.

Would this might have changed again in latest releases (regression bug) ?

**Comment by nolimits4web** [comment]
Or set initial URL (`url: 'index.html'`) parameter for the view when you initialize it
