### ISSUE TITLE
page:init event not being triggered

### ISSUE THREAD

**Issue by TroyMaeder** [nolimits4web/Framework7#1436]
I'm currently developing a web app and I've run into an issue trying to implement the F7 swiper. If I insert the swiper to the home page it works fine but when I insert it into one of the tabs it becomes glichy and doesn't slide as it should. 

On the docs it says "Note that Swiper container should be in DOM on a moment of initialization. So if you use slider not on home page, you need to initialize it within page:init event". I've tried doing this and the event is not being triggered. I've tried the event for all pages and also for each page and neither is being triggered.

### What I did
```
$$(document).on('page:init', function(e) {
    console.log('Event triggered');
 });

$$(document).on('page:init', '.page[data-page="about"]', function (e) {
    console.log('Event triggered');
});  
```

**Comment by nolimits4web** [comment]
http://framework7.io/docs/page-callbacks.html#callbacks-for-initial-pages
