### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by krosoftware** [nolimits4web/Framework7#1439]
Hello
any idea when Table component will be released?
Thank you.

**Comment by krosoftware** [comment]
I see it is done but when I run it, I see this:
http://imgur.com/EeyUIIW
It can be that I'm wrong but I'm using /dist/js/framework7.js dated 03/21/2017

**Comment by ZanderBrown** [comment]
`/dist/js/framework7.js` was last generated 9 days ago and @nolimits4web pushed the feature 8 days ago.

As for being released 'officially' i imagine within a couple of weeks but you can build it yourself if you need it now

**Comment by krosoftware** [comment]
Thank you. Where I can find info's of how to build data-table, please?

**Comment by ZanderBrown** [comment]
Install node.js and follow the [instructions in the README](https://github.com/nolimits4web/Framework7#build)

**Comment by krosoftware** [comment]
Thank you, will try it.

**Comment by krosoftware** [comment]
Just in case - did someone build data table? If yes, any chance to post it?
Thank you.

**Comment by nolimits4web** [comment]
@krosoftware use Build instructions from README and use JS/CSS files from `build/` folder

**Comment by krosoftware** [comment]
Thank you but I do not understand where to start. What means:
"First you need to have gulp-cli which you should install globally."
Where I can find "gulp-cli" ? Also, what means "Then install all dependencies, in repo's root"
I have 10+ years experience in Windows desktop programming (Visual Basic) and I just started on HTML/JS world so those instructions are strange to me. If there is no chance that someone post compiled version with Data Table, I will wait. I just asked - if someone built it already to post it somewhere..

**Comment by ZanderBrown** [comment]
Have you installed node.js?

**Comment by krosoftware** [comment]
Yes I am. I have installed it into C:\Program Files\nodejs\ and there is node.exe and some other files. When I run node.exe it show me DOS command prompt and that's all. I searched for "gulp" and there is no such file. How to start? Look, if it is problem for you or someone to build data table, I will wait. I will not to disturb you or someone else if you have no time to build it.. I just asked if someone already did that - if not, OK.

**Comment by ZanderBrown** [comment]
Which version of Windows are you running? If 8, 8.1 or 10 open File Explorer to wherever you cloned Framework7 to and run `npm install -g gulp` that makes gulp available globally then `npm install` downloads F7's dependencies locally with `gulp build` building it

**Comment by krosoftware** [comment]
OK it worked, thank you so much.
