### ISSUE TITLE
Bottom toolbar labels are not in uppercase

### ISSUE THREAD

**Issue by waptaxi** [nolimits4web/Framework7#1442]
In 1.5.4 for some reason bottom toolbar labels' text became not in uppercase by addition of these code:
`.tabbar-labels.toolbar-bottom span.tabbar-label {
  text-transform: none;
}`

**Comment by macdonst** [comment]
@waptaxi what platform, Android or iOS? Regardless, as far as I know neither Android nor iOS UI guidelines specify that the toolbar labels must be upper case.

**Comment by ZanderBrown** [comment]
[Material Guidlines](https://material.io/guidelines/components/bottom-navigation.html) & [iOS HIG](https://developer.apple.com/ios/human-interface-guidelines/ui-bars/tab-bars/) shows tab labels as simply having the first letter capitalised
