### ISSUE TITLE
Swiper not working within tabs class

### ISSUE THREAD

**Issue by TroyMaeder** [nolimits4web/Framework7#1443]
I have an app that's set mostly within tabs.
When I use the swiper inside of the tab class it is very glitchy and does not work as it should. If I put the swiper outside of the tab class then it works perfectly.

**Comment by nolimits4web** [comment]
Would be good to see live example or JSFiddle with the issue

**Comment by ryandong8321** [comment]
where can I find live example? Thx.

**Comment by blikblum** [comment]
fork https://jsfiddle.net/nolimits4web/o2ejupu1/

**Comment by ryandong8321** [comment]
Thank you for reply, @blikblum .

Actually, I have an issue when using swiper with tabs(routable),  and the swiper didnt work but initialisation I think, I have tried to get the swiper object using $('.swiper-container'), but I couldnt get the object at all.

So, could anyone pls tell me how should I do? Thx.

**Comment by ryandong8321** [comment]
Hi @TroyMaeder , I so sorry to trouble you.
could you please tell me how to fix this problem you provided?
waiting for your reply.
Thank you.
