### ISSUE TITLE
Cannot trigger html5 download with javascript on Android

### ISSUE THREAD

**Issue by kokororin** [nolimits4web/Framework7#1445]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.4
* Platform and Target: Android
* Live Link or JSFiddle/Codepen: 
http://kokororin.github.io/demo/f7.html 
http://kokororin.github.io/demo/f7.html#nof7

### What you did
Hi. I use javascript to trigger download files.
code like 
```javascript
      var a = document.createElement('a');
      a.href = 'https://cache.pixiv.moe/aqours/music/442314572.mp3';
      a.setAttribute('download', true);
      a.className = 'external';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
```
On PC Browser, it works well.
On Chrome for Android and other Android Web Browser, when I click the button in the demo url, it doesn't work.
There are two demo urls, the one which has hash `nof7` doesn't have `new Framework7`,and it works well.While the other one with f7 initialized doesn't work.

### Expected Behavior
Download should start

### Actual Behavior
Download not start, nothing happened.

**Comment by nolimits4web** [comment]
Try
```js
a.className = 'external no-fastclick';

**Comment by kokororin** [comment]
It works. Thank you!
