### ISSUE TITLE
SmartSelect won't open from PopUp!

### ISSUE THREAD

**Issue by tinyCoder32** [nolimits4web/Framework7#1446]
Hi, I have a popup window that has a smart select in it, the SmartSelect doesn't work in it:

Here is a fiddle: https://jsfiddle.net/tinyCoder32/xvqd0vn5/

In my script it works if I use javascript `myApp.smartSelectOpen` but I want to open the smartselect as a page to be able to navigate back using Android back button.

**Comment by nolimits4web** [comment]
Use correct view->pages->page layout inside of popup to make it work

**Comment by tinyCoder32** [comment]
Sorry, I did but it still doesn't work: https://jsfiddle.net/tinyCoder32/xvqd0vn5/

**Comment by nolimits4web** [comment]
https://jsfiddle.net/fys92vyj/
