### ISSUE TITLE
Preprocess with Template7 not working on homepage

### ISSUE THREAD

**Issue by snakeman21** [nolimits4web/Framework7#1449]
This was asked several times, and you even gave a response here https://github.com/nolimits4web/Framework7/issues/530. I have also searched throughout the entire forum and found nothing that worked. I am using preprocess with Template7 data and I tried to call `mainView.router.refreshPage()`. This does not solve this issue, which is why I am wondering if there is a bug with the version I am using (1.5.2). I can post my coding example if necessary, but I'm really thinking it's a bug if this is not working correctly.

**Comment by ZanderBrown** [comment]
@nolimits4web for V2 we probably need to rethink the way initial pages work as we keep getting issues likes this.

@snakeman21 have you tried manually calling `.init()` and are you aware that initial content is *not* fetched through ajax

**Comment by snakeman21** [comment]
Hey Zander, thank you so much for your response. I tried all of the 3 of these methods for callbacks on initial page with several different scenarios, but still no success somehow http://framework7.io/docs/page-callbacks.html#callbacks-for-initial-pages. I truly don't think there is a solution to this unfortunately :(

**Comment by nolimits4web** [comment]
@snakeman21 can you show an example of what you are trying to achieve?

**Comment by snakeman21** [comment]
@nolimits4web absolutely

```
preprocess: function (content, url, next) {
  if (url === 'newPage.html') {
    $$.ajax({url: 'https://example.com/ajax-page.php', method: 'POST', dataType: 'json', data: {}, success: function (data) {
      template = Template7.compile(content);
      result = template(data);
      next(result);
    }});
  }
}	
```

I would like to be able to make this work on the homepage right away. All the methods I listed above didn't work. This is somewhat of a related issue, since it deals with initial page rendering, but I also couldn't figure out a good way to deal with logged in state. The reason I'm bringing this up is because I figured a good solution to this would be to just have the index page be the login page. But if I do that, then I have issues with checking `if(loggedIn) mainView.router.loadPage('newPage.html')`.

I'm rambling here, but the true end goal is any solution that allows me load my ajax content with T7 preprocess, while also being able to figure out if it should go to the logged out page or logged in initial page. Of course I could do the modal login solution, but that still doesn't solve the preprocess on initial page issue.

**Comment by nolimits4web** [comment]
Well, you can just call View reload method when it is initialized:
```js
// App
var myApp = new Framework7({
    // ...
    preprocess: function (content, url, next) {
        if (url === 'index.html') {
            $$.ajax({
                url: 'https://example.com/ajax-page.php',
                method: 'POST',
                dataType: 'json',
                data: {},
                success: function (data) {
                    template = Template7.compile(content);
                    var result = template(data);
                    next(result);
                }
            });
        }
        else next(content);
    }
});

// Add main view
var mainView = myApp.addView('.view-main', {
    // ...
    url: 'index.html'
});

// Just just do reload on app load
mainView.router.load({reload: true, url: 'index.html'});

**Comment by snakeman21** [comment]
@nolimits4web This still doesn't work. In the console, the ajax call is being made, but I guess T7 isn't waiting for the preprocess.

**Comment by snakeman21** [comment]
Any thoughts? I can't finish up my app until I get this issue resolved.

**Comment by ZanderBrown** [comment]
try using `template7pages` and `template7data`

**Comment by snakeman21** [comment]
Still doesn't work. I'm surprised there aren't any answers to this as it is a fairly common use case. I'd even argue that it's the most common scenario for an app. In a website this would be a very simple task.

**Comment by nolimits4web** [comment]
This was working example i have personally tested. Problem somewhere on your side. Due to lack of Ajax support on JSFiddle, here is an example using `preroute` instead of preprocess https://jsfiddle.net/hnbLj21d/1/

**Comment by snakeman21** [comment]
Can confirm that this works. Thank you so much for taking the time to help Vlad! You are obviously extremely busy, so I'm grateful that you are nice enough to actually help. You're the man, and I hope this awesome framework continues to grow!
