### ISSUE TITLE
onPageInit for Index page?

### ISSUE THREAD

**Issue by tinyCoder32** [nolimits4web/Framework7#1450]
Hi, I was looking for a way to know if the user is now in the main Index page after he gets back from other pages, so I tried `onPageAfterBack` and `onPageBack` to get the page name, but it seems they return the current page name not the target one.

I need to fire up a function every time the user gets back again to the index page, as `onPageInit('index', ..` doesn't work for this.

is there a way?

**Comment by jdf221** [comment]
Pretty sure `onPageInit` is only called when the page isn't in the cache, so you would need to use `onPageReinit`.

`onPageBeforeAnimation` and `onPageAfterAnimation` would also work I think.

Haven't actually tested this though...

**Comment by ZanderBrown** [comment]
`onPageBeforeAnimation` is probably the best way to go.

@nolimits4web we probably need a better way to handle this

**Comment by tinyCoder32** [comment]
`OnPageReinit` actually worked, thanks @jdf221.

```
myApp.onPageReinit('*', function(page) {
	if (page.name == 'index') doIndexFunction();
});
```
