### ISSUE TITLE
Fixed App

### ISSUE THREAD

**Issue by ibagaric** [nolimits4web/Framework7#1453]
How to make app, made with F7 and Cordova , to be fixed, [https://ibb.co/gAQY8v]. I do not want to scroll all app down.

Putting 

```
overflow-y: hidden;
-webkit-overflow-scrolling: auto;  
```

on body, html, views does not help.

Thank you in advance!

**Comment by ZanderBrown** [comment]
iNoBounce

**Comment by ZanderBrown** [comment]
iNoBounce

**Comment by ibagaric** [comment]
I just found answer:

if you're using Cordova 2.3.0+ find config.xml and add this line:
<preference name="UIWebViewBounce" value="false" />

or in Cordova 2.6.0+:
<preference name="DisallowOverscroll" value="true" />

that is all, you do not need any library...
