### ISSUE TITLE
Calendar 'day selected' circle gets put on the day before

### ISSUE THREAD

**Issue by tribalboy3000** [nolimits4web/Framework7#1454]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: Framework7 1.5.4
* Platform and Target: IOS

### What you did
I just selected a day on the calendar. And it puts the blue circle on the day before. Its doing it on your examples too.

https://framework7.io/docs/calendar.html

Im on a MacOS Sierra
Version 10.12.3

**Comment by nolimits4web** [comment]
Same as #1413
