### ISSUE TITLE
JQuery namespaces not working

### ISSUE THREAD

**Issue by vmexia** [nolimits4web/Framework7#1459]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: 1.5.4
* Platform and Target: Browser
* Live Link or JSFiddle/Codepen: _

### What you did
Inside the page:init I defined this event,

`$$('body').on('click.roomtype', '.elem', function () {
    console.log('elem clicked');
    var classes = $$(this).attr('class').split(' ');
    var id = classes[1];
    console.log(id);
  });`

### Expected Behavior
I have a list block generated with Template7, and a click on one of those elements should trigger the click event and log its id.

### Actual Behavior
No click event is triggered. If I remove the namespace ( .roomtype) it will work, but will also add multiple calls to that click. I can use .off() to stop this last behaviour, but it would require namespacing to work with anonymous functions (**note**: Anonymous functions are a must).

**Comment by ZanderBrown** [comment]
You're going to need to explain jQuery namespaces

**Comment by vmexia** [comment]
https://api.jquery.com/event.namespace/

**Comment by ZanderBrown** [comment]
Unless @nolimits4web knows otherwise Dom7 doesn't support this.

Is there no alternatives you could use?

**Comment by vmexia** [comment]
Well yeah, I have a working alternative implemented, but not a very fancy one, atleast if I'm understating how we are supposed to use the custom DOM7 implemented by the framwork. My thoughts are that on page:init-beforeinit-afteranimation-etc we are supposed to code some functionality, necessary for that page, for me its's the .click() actions. It doesn't make much sense to me defining an handler for a component that may or not be loaded to the DOM. Maybe I'm thinking about this in a wrong way..?

**Comment by ZanderBrown** [comment]
OnPageInit should receive a page object with includes a container property. Handlers ect should be attached to that not body (thus effecting only that one page)

**Comment by nolimits4web** [comment]
Right, as @ZanderBrown mentioned just use something more narrow than body:
```js
app.onPageInit('somepage', function (page) {
    $$(page.container).find('.template7-generated-list').on('click', '.item-link', function () {
        // Do something
    });
    // Or
    $$(page.container).on('click', '.template7-generated-list .item-link', function () {
        // Do something
    });
});

**Comment by vmexia** [comment]
Well that solution does work, but it does not change the fact that the support for namespaces isn't there.

Cumpz.
