### ISSUE TITLE
Is panel opened - specific example

### ISSUE THREAD

**Issue by krosoftware** [nolimits4web/Framework7#1467]
Hello,
how to check is panel opened or not – on this application: http://guillaumebiton.github.io/HackerNews7/
I mean on right (black) panel.
Thank you.

**Comment by ZanderBrown** [comment]
Nice app!

I'm assuming the panel you want to check is the author info pane?

Could you please explain how this would be useful for you?

**Comment by ZanderBrown** [comment]
[See docs](http://framework7.io/docs/side-panels.html#panel-is-opened?)

> ## Panel is Opened?
> Sometimes it could be useful to detect do we have some Panel opened or not? It is easy, when some panel is opened `<body>` will have addition class generated by the following rule: **with-panel-[position]-[effect]**:
> * If you have Left panel opened with Cover effect, body will have the "with-panel-left-cover" class `<body class="with-panel-left-cover">`
> * If you have Left panel opened with Reveal effect, body will have the "with-panel-left-reveal" class `<body class="with-panel-left-reveal">`
> * If you have Right panel opened with Cover effect, body will have the "with-panel-right-cover" class `<body class="with-panel-right-cover">`
> * If you have Right panel opened with Reveal effect, body will have the "with-panel-right-reveal" class `<body class="with-panel-right-reveal">`
>
> You can use it in JavaScript to detect opened panel:
>```js
> if ($$('body').hasClass('with-panel-left-cover')) {
>     console.log('Left Panel is opened')
> }
> ```
> Or in CSS for additional styling:
> ```css
> /* Change Status Bar background when panel is opened */        
> body.with-panel-left-cover .statusbar-overlay{
>     background-color: #333;
> }
> ```

**Comment by krosoftware** [comment]
Hello @ZanderBrown, yes it is user info panel
I saw that on doc's but 
$$('body').hasClass('with-panel-right-cover') 
or 
$$('body').hasClass('with-panel-right-reveal') 
does not work
do you have any other idea, please?

**Comment by krosoftware** [comment]
Here is solution:
if ($$(window).width() <= 1280px) {
    if (!$$('.panel-right').hasClass('active)) {
        alert('panel invisible')
    } else {
        alert('panel visibe')
    }
} else {
    alert('panel visibe')
}
