### ISSUE TITLE
Swipe panel strange background

### ISSUE THREAD

**Issue by brainformatik** [nolimits4web/Framework7#1470]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: Master branch
* Platform and Target: All
* Live Link or JSFiddle/Codepen: The kitchen sink material with swipe enabled

### What you did
Used swipeable panel

### Expected Behavior
The panel should change its background related to how much of the panel is visible

### Actual Behavior
The panel background is fully visible on swipe start and will get lesser if there is more of the panel visible

**Comment by nolimits4web** [comment]
It is fixed in dev master branch

**Comment by J05HI** [comment]
@nolimits4web 
Thanks!
