### ISSUE TITLE
Message bar layout shouldn't change on RTL style

### ISSUE THREAD

**Issue by tinyCoder32** [nolimits4web/Framework7#1471]
In all chat apps and the native iOS, the message bar has the same layout, that the submit "SEND" button stays on the right, and the input field stays to the left.

![photo_2017-04-03_17-26-12](https://cloud.githubusercontent.com/assets/17817239/24614056/c49354d8-1892-11e7-93a3-145ee75a6351.jpg)

But in my F7 app, I get the submit button on the left and the input field on the right, it is really bad to keep it like this, I couldn't manage to find a way to change it.

![screen shot 2017-04-03 at 5 28 52 pm](https://cloud.githubusercontent.com/assets/17817239/24614140/0718ebba-1893-11e7-85ed-2362f6ac9006.png)

**Comment by ZanderBrown** [comment]
Is this related to RTL

**Comment by tinyCoder32** [comment]
I'm using the default messages layout, using the RTL css file reverts the submit and text input positions.

**Comment by ZanderBrown** [comment]
odd shows the right way round in the demos

**Comment by tinyCoder32** [comment]
![screen shot 2017-04-04 at 00 25 18](https://cloud.githubusercontent.com/assets/17817239/24632542/32727d82-18cd-11e7-9823-0a497815485d.png)

Basic example from the demo after adding RTL css file.

**Comment by seme1** [comment]
NO. Send button in RTL applications should stay on the LEFT side. Please do NOT change it as the way it's implemented now is correct.

**Comment by tinyCoder32** [comment]
Man just look up there, I included the first image in this thread which is directly from iPhone using Arabic language, where do you see the Send button?

It is on the right in all apps on my phone, WhatsApp, Telegram and IMO...

**Comment by ZanderBrown** [comment]
The first screenshot maybe in arabic but not RTL

**Comment by seme1** [comment]
@tinyCoder32 
I just checked again, and you are right. In native Arabic OS, it should be on the right side.

**Comment by tinyCoder32** [comment]
@ZanderBrown No one would make Arabic app without using RTL style layout, or everything will be messed up.

Also no one would use RTL style unless he is using Arabic or Hebrew. RTL and Arabic are the same for us.

**Comment by ZanderBrown** [comment]
In RTL the back button is on the right not left, the first screenshot has it on the right.

Whilst the language maybe set to Arabic it's not in RTL mode

**Comment by tinyCoder32** [comment]
But my friend why would a user use RTL mode if he is not using Arabic or Hebrew?
Setting the language to Arabic or Hebrew in iOS keeps the buttons on the same position, and in my F7 app if i didn't use RTL mode lots of things will be messed up, so i'm forced to use RTL but the BACK and SEND button for example don't look native as they are in the wrong positions.

That's what I wanted to make clear.

Thank you.

**Comment by ZanderBrown** [comment]
![image](https://cloud.githubusercontent.com/assets/17074021/24634719/3ac10586-18c7-11e7-8670-3ef04a59b470.png)

Got this from a friend running the latest iOS, as you can see the buttons are flipped

**Comment by tinyCoder32** [comment]
@ZanderBrown thank you.
That's really confusing, I'm not aware of that.
On my iPhone 4 (iOS 7):

**iMessage**
![photo_2017-04-04_10-12-53](https://cloud.githubusercontent.com/assets/17817239/24645157/b5a2acd4-191f-11e7-8fb9-6a4c350815bb.jpg)

**IMO***
![photo_2017-04-04_10-13-00](https://cloud.githubusercontent.com/assets/17817239/24645173/c2778f9c-191f-11e7-98b1-237c9e81e1bf.jpg)

**Telegram**
![photo_2017-04-04_10-13-14](https://cloud.githubusercontent.com/assets/17817239/24645181/c97836de-191f-11e7-8382-304d6c28d0dc.jpg)

**WhatsApp**
![photo_2017-04-04_10-13-18](https://cloud.githubusercontent.com/assets/17817239/24645189/cf216dd0-191f-11e7-9d73-80850463a1ae.jpg)

** Notes **
![photo_2017-04-04_10-13-10](https://cloud.githubusercontent.com/assets/17817239/24645197/d80ecc08-191f-11e7-8e09-be870183c2ee.jpg)

**Settings**
![photo_2017-04-04_10-13-04](https://cloud.githubusercontent.com/assets/17817239/24645210/e4ed56ec-191f-11e7-8a24-87ed327b1e95.jpg)

Thank you for your time anyway, do you think there is a way I can more the SEND button to the right side? I didn't know how.
