### ISSUE TITLE
Can't using "Mo-js" in framework7  :confused: 

### ISSUE THREAD

**Issue by cuduy197** [nolimits4web/Framework7#1476]
P/S:  To use Mo-Js with Framework7 :point_down: 
add z-index: 0 to app style .
Problem: 
I can't using http://mojs.io/ in framework7 :disappointed: 
I dont know why? :confused: 
Pleace help me. :face_with_head_bandage:  

P/s And this is demo using mojs : https://jsfiddle.net/cuduy197/h0cs7pmt/

**Comment by nolimits4web** [comment]
Would be good to see what you have tried?

**Comment by cuduy197** [comment]
Oh i know how fix it :smile:  
add `z-index: 0` to app style .
