### ISSUE TITLE
Smart select option images shown to big

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7#1479]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did
Assign data-option-image to a smart select option.

### Expected Behavior
Image shown according available space.

### Actual Behavior
Image shown to big and destroys layout.

### Workaround / Fix
```
.smart-select-page .item-media img {
  max-width: 29px;
  max-height: 29px;
}
```

**Comment by nolimits4web** [comment]
Yes, custom CSS should be added (not so hard i think) as users may need different image sizes  there according to their needs
