### ISSUE TITLE
No Smart Select close callback

### ISSUE THREAD

**Issue by tinyCoder32** [nolimits4web/Framework7#1483]
How can I manage to know when a specific Smart Select is closed, like popups have?

```
$$('.popup-categories').on('popup:close', function () {
 //...
});
```

Adding this feature in next releases would be awesome, as it is very needed.

**Comment by nolimits4web** [comment]
If you mean SS opened in page you can use page callback (like pageBack or another which fits best for you) for this

**Comment by vousys** [comment]
Hi Vladimir, I can't handle the events.. can you help me?
I tryed:
$$(document).on('open', '.smart-select-page', function( e ) {
 console.log("open");
});
also:
$$('.smart-select-page').on('close', function () {
 console.log("close");
});

I need to exec another function each time someone click on an option.
I've got this set.   smartSelectBackOnSelect: true,
