### ISSUE TITLE
when otherview.router.loadpage ,the url is not  changed 

### ISSUE THREAD

**Issue by huangyuanyazi** [nolimits4web/Framework7#1485]
the project structure likes this
                               views(class=tabs)
                                      tabs
                                      view1(class=tab view-main)
                                      view2(class=tab view2)
                                      view3(class=tab view3)
                                      view4(class=tab view4)
only view-main ajax  loadpage,the url is changed,the other views is not changed

**Comment by ZanderBrown** [comment]
pushState is only supported in view-main

**Comment by huangyuanyazi** [comment]
if otherviews want to change url,what can  i  do?   thanks for your answer

**Comment by ZanderBrown** [comment]
some people have changed which view is the main-view, otherwise consider changing your app structure

**Comment by huangyuanyazi** [comment]
thanks again for your answer
