### ISSUE TITLE
Login screen issue in docs

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7#1491]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did
Clickend on "open login screen with JS"

### Expected Behavior
To be closed after click on sign in.

### Actual Behavior
Did not close - see screenshot (error).

![bildschirmfoto 2017-04-11 um 21 26 44](https://cloud.githubusercontent.com/assets/19615586/24926985/b71fe926-1efd-11e7-8e1d-9d0f769e571e.png)

**Comment by GuillaumeBiton** [comment]
It's just that goBack() function has been renamed to back() [while ago](https://github.com/nolimits4web/Framework7/blob/master/CHANGELOG.md#framework7-v097---updated-on-october-7-2014).

**Comment by ZanderBrown** [comment]
@GuillaumeBiton PR?

**Comment by GuillaumeBiton** [comment]
I get try but it should be in [Framework7-Website repository](https://github.com/nolimits4web/Framework7-Website)
