### ISSUE TITLE
Adding dataType option to $$.post() and $$.get()

### ISSUE THREAD

**Issue by snakeman21** [nolimits4web/Framework7#1492]
This is a (multiple allowed):
* [] bug
* [x ] enhancement
* [ ] feature-discussion (RFC)

Thoughts on adding dataType parameter to `$$.post()` and `$$.get()` to DOM7? In jQuery, I can do the following with a json dataType.
```
$.post('ajax-page.php', {params}, function(data) {
}, 'json');
```

**Comment by ZanderBrown** [comment]
For get there is getJSON
For post you can use $$.ajax which does accept a datatype parameter

**Comment by snakeman21** [comment]
Ya for sure. I just love using the $$.post shorthand, while passing in json as the datatype, but of course you can just do the long way with $$.ajax. While certainly not necessarily, I think it would be an nice feature to add.
