### ISSUE TITLE
mainView.router is unusable after a return false happens

### ISSUE THREAD

**Issue by snakeman21** [nolimits4web/Framework7#1496]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
1.5.4
* Platform and Target: PLATFORM CLIENT YOU ARE TARGETING SUCH AS CORDOVA, IOS, ANDROID, ETC.
* Live Link or JSFiddle/Codepen: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking one of the templates: iOS [JSFiddle](https://jsfiddle.net/s2n1p730/)/[Codepen](https://codepen.io/nolimits4web/pen/WRRWwN), Material [JSFiddle](https://jsfiddle.net/0ogxxcvt/)/[Codepen](https://codepen.io/nolimits4web/pen/pEPPPK)

### What you did
EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.
Let's say I just lost internet connection momentarily, and I try to go to an ajax page while routing. On the first request, it will return undefined, but the second time it will return false. When it returns false, you can no longer navigate to pages anymore. For instance, the following won't work until I force quit the app. `mainView.router.load({url: 'example.html', reload: true, ignoreCache: true})`

### Expected Behavior
EXPLAIN WHAT IS TO BE EXPECTED, HERE.
I'd like to be able to make routing to different pages work, even after it is disabled by the return false breaking.

### Actual Behavior
EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.
You can't navigate to different pages until you force quit.

**Comment by snakeman21** [comment]
In fact, even if you are just going to any ajax page like this `<a href="about.html">Go to About page</a>` and turned off your internet, then tried to click on that link while offline. Then turn on your internet connection again and you won't be able to access that page anymore until you force quit the app. 

@nolimits4web any thoughts on this? This is a serious issue for usability.

**Comment by J05HI** [comment]
Tested and have the same problem

**Comment by snakeman21** [comment]
In case anyone is googling this, the best solution I came up with is to use a global variable that is set to false on a failed ajax request on preprocess. Then I give the user a modal telling them that something went wrong. When they click ok, the variable is set to true again. Even if they don't click ok and just leave the app in the background, then I also check this variable on the Cordova event `pause`. Hopefully this helped someone.

**Comment by nolimits4web** [comment]
In default scenario i can't replicate it:

* Open Kitchen Sink
* Open Chrome and enable device emulation
* Set network throttling to Offline
* Try to load any page - XHR error in console
* Set network throttling to No throttling
* Try to load any page
* All works

So will be good to see exact scenario of replicating the issue

**Comment by snakeman21** [comment]
You're right, this is true in the kitchen. I think the difference is in my scenario I use preprocessing for Template7. I do something like the following. Let me know if you need anything else. It seems like we've narrowed down the cause to using a custom ajax functions inside preprocess.

```
preprocess: function (content, url, next) {
        if (url === 'index.html') {
            $$.ajax({
                url: 'https://example.com/ajax-page.php',
                method: 'POST',
                dataType: 'json',
                data: {},
                success: function (data) {
                    template = Template7.compile(content);
                    var result = template(data);
                    next(result);
                }
            });
        }
        else next(content);
    }
```

**Comment by snakeman21** [comment]
@nolimits4web any thoughts on how it would be possible to solve this issue or is it impossible to fix?

**Comment by snakeman21** [comment]
@ZanderBrown maybe you know the answer? This is an issue that a ton of people seem to have and is asked on the forum a lot

**Comment by nolimits4web** [comment]
@snakeman21 just add `error` callback to your ajax call, and then call something (fallback content) with `next(fallbackContent)` or just set your related View `allowPageChange` property to `true`, .e.g.:
```js
...
error: function () {
    mainView.allowPageChange = true;
}

**Comment by J05HI** [comment]
@nolimits4web
This doesn't work for ajax pages. 
Framework7 handles the ajax request of the new page internally. 
Maby add a new page callback "onPageError" :)

**Comment by snakeman21** [comment]
@nolimits4web Thank you so much for the response! setting ` mainView.allowPageChange = true` seems to work fine for me actually. Unless I'm just stupid, I couldn't find that anywhere in the documentation. Maybe it would be a good idea to add it. I appreciate the help, as I know you're very busy.
