### ISSUE TITLE
Range slider has no color 

### ISSUE THREAD

**Issue by dawiinci** [nolimits4web/Framework7#1498]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.0
* Platform and Target: ORDOVA, IOS
* Live Link: http://framework7.io/docs/form-elements.html

### What you did
Move the slider to the right. 

### Expected Behavior
Left part of the line gets blue. 

### Actual Behavior
Remains grey.

**Comment by nolimits4web** [comment]
Same as #1463
