### ISSUE TITLE
hide-toolbar-on-scroll does not work well with Swipeable Tabs or Animated Tabs

### ISSUE THREAD

**Issue by kokororin** [nolimits4web/Framework7#1501]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.0
* Platform and Target: Android & iOS
* Live Link or JSFiddle/Codepen: http://kokororin.github.io/demo/tab-test.html

### What you did
I have three tabs with Swipeable Tabs, and add `hide-toolbar-on-scroll` to  all of the three `page-content` divs.

### Expected Behavior
All tabs should have the `hide-toolbar-on-scroll` effect.

### Actual Behavior
Only the first tab work with the `hide-toolbar-on-scroll` effect.
The second and the third tab 's tab do not hide when I scroll down and do not show when I scroll up.

**Comment by nolimits4web** [comment]
Same as #1241
