### ISSUE TITLE
Problem with the center class in android

### ISSUE THREAD

**Issue by AndiLeni** [nolimits4web/Framework7#1502]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.0
* Platform and Target: Windows -> CORDOVA, IOS, ANDROID, ETC.

### What you did
I created a navbar and two pages. 

### Expected Behavior
The page name should be centered and the 'back' button should be displayed if I click the link to the second page.

### Actual Behavior
The page name is on the left and overlapps with the back button.
Also there is a mistake in the material.css (https://github.com/nolimits4web/Framework7/blob/master/dist/css/framework7.material.css)
text-align is used twice in the same class.
I don't know what is causing the problem but this looks strange.
If I use the ios.css everything works as expected.

How it looks like:
![2017-04-14 13_46_46-w3w viewer](https://cloud.githubusercontent.com/assets/13385771/25048822/cd341668-213e-11e7-9f46-5adb847b9961.png)

How it should look like:
![2017-04-14 18_20_24-w3w viewer](https://cloud.githubusercontent.com/assets/13385771/25048893/3b067050-213f-11e7-9957-1e2f7448cbff.png)

The css part which might cause the issue:

`.navbar .center,
.subnavbar .center {
  font-size: 20px;
  font-weight: 500;
  text-align: center;
  margin: 0 16px;
  position: relative;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  line-height: 56px;
  display: inline-block;
  text-align: left;
}`

**Comment by ZanderBrown** [comment]
Material spec states it should be aligned left

**Comment by AndiLeni** [comment]
I understand that it is intended to be right aligned, but this does not mean it should be overlapped by default. 
What about the css? Why is the text-align used twice? This doesn't make any sense.

**Comment by ZanderBrown** [comment]
[Works fine here](http://framework7.io/kitchen-sink-material/) Material apps shouldn't have the word 'Back' only the icon
