### ISSUE TITLE
Loading pushState page directly always shows index page briefly and fires it's callbacks

### ISSUE THREAD

**Issue by WeaponX86** [nolimits4web/Framework7#1503]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.0
* Platform and Target: Google Chrome, Phonegap

### What you did
Enabled pushState and disabled automatic init

### Expected Behavior
Loading a page directly or refreshing (An external template i.e. _https://mysite.com/index.html#!/contacts.html_) should only fire events for that page.

**Console output:**
onPageBeforeInit - page: contacts
onPageInit - page: contacts

### Actual Behavior
Loading a page directly (An external template i.e. _https://mysite.com/index.html#!/contacts.html_) the index page from index.html is shown briefly and it's events are fired before loading the login page.

**Console output:**
onPageBeforeInit - page: index
onPageInit - page: index
....
onPageBeforeInit - page: contacts
onPageInit - page: contacts

**Example code (Modified examples\template7-pages\js\my-app.js):**

```
// Initialize your app
var myApp = new Framework7({
	init: false,
	pushState: true
});

// Load phonegap, sqlite, etc...before displaying requested page
setTimeout(function(){
	myApp.init();
	
	// Add main View
	var mainView = myApp.addView('.view-main', {	});	
},1000);

myApp.onPageBeforeInit('*', function (page) {
	console.log('onPageBeforeInit - page: ' + page.name);
});

// executed after Framework7 initialize required page's (with "pageName" data-page attribute) components and navbar
myApp.onPageInit('*', function (page) {
	console.log('onPageInit - page: ' + page.name); 
});

```
I also tried moving the call to myApp.addView before myApp.init() but throws an error in the console when I try to open _https://mysite.com/index.html#!/contacts.html_:
Uncaught TypeError: Cannot read property 'contacts.html' of undefined

**Comment by nolimits4web** [comment]
Well, you should handle it manually. It shows index page and initialize it because it is in your INDEX file

**Comment by WeaponX86** [comment]
All of my templates are external. If I don't have a dummy index page, F7 just displays a blank page. Am I missing something?
