### ISSUE TITLE
template7Pages in index.html

### ISSUE THREAD

**Issue by kkordinia** [nolimits4web/Framework7#1505]
This is a (multiple allowed):
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.0
### What you did
template7pages feature not work in index.html. [in this issue](https://github.com/nolimits4web/Framework7/issues/530) was told that "**.router.refreshPage**" is a way to slove this problem. but there is a problem. this way cuase Repeat somde code. is there another way for slove this problem? or is possible run main page as dynamic page?

**Comment by J05HI** [comment]
@nolimits4web 
I have the same problem here. I hope you can fix that

**Comment by nolimits4web** [comment]
Refer to #1449

**Comment by kkordinia** [comment]
@nolimits4web 
i test this soulation already. but when i run some code in pageinit event for example:
`myApp.alert("message");`
the code run again. It would be great if template7pages behavior like other pages.
