### ISSUE TITLE
Smart Select pushstate?

### ISSUE THREAD

**Issue by tinyCoder32** [nolimits4web/Framework7#1506]
Hi, Android users are trying to click back on an opened smart select control but that causes app to close (for example), it would be awesome to have smart select change the pushstate like you did for dynamic page (add `/#content-1` to the URL, and close the smart select on back, that'd be more easy and needed solution.

Thanks.

**Comment by J05HI** [comment]
Yeah would be great but it isn't possible to do that without changing Framework7. 
@nolimits4web needs to help us.

**Comment by nolimits4web** [comment]
@tinyCoder32 it works as expected when pushState is enabled and Smart Select used as a Page. Otherwise, use `onbackbutton` cordova callback to close it when you need it

**Comment by tinyCoder32** [comment]
@nolimits4web not if I opened it using JavaScript.
And I don't use Cordova, I open the Smart Select using JavaScript when users click on an icon, pushstate is enabled but not changing.

**Comment by J05HI** [comment]
@nolimits4web 
How to initiate smart select as page

**Comment by tinyCoder32** [comment]
@J05HI by adding `data-open-in="page"` which is the default mode, but that doesn't change pushState when opened from JavaScript, even you can't change it to `popup` from JavaScript, it always open as page, it will be very useful to have that option in JS too.

**Comment by J05HI** [comment]
Yeah
