### ISSUE TITLE
Modal / Action Sheet events are ambiguous

### ISSUE THREAD

**Issue by WeaponX86** [nolimits4web/Framework7#1507]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.0
* Platform and Target: Google Chrome, Phonegap
* Live Link or JSFiddle/Codepen: https://jsfiddle.net/weaponx86/k8584mdt/3/

### What you did
Made multiple calls to myApp.actions with different options, created an actions:closed listener. Trying to distinguish them from one another

### Expected Behavior
Need to be able to pass an id to myApp.actions() to be sent along with events or some distinguishing value needs to be passed into the template.

### Actual Behavior
Can't bind action sheet events to individual action sheets. Callbacks do not send back any meaningful identifier.

**Comment by ZanderBrown** [comment]
`.actions()` returns the genrated HTMLElement, `actions:closed` is triggered with the target of that HTMLElement

Either add an id to the HTMLElement returned by `.actions()` or store it and compare it to `actions:closed` target

**Comment by WeaponX86** [comment]
Adding the id made a lot more sense.

Here is my code for anyone else:
```javascript 
$(document).on('click','#btn-sort-home', onClickSort);
$(document).on('actions:closed','#action-sheet-home-sort',function(e){
	console.log('Sort action sheet closed');
});

function onClickSort(){

	var aoActions = [];

	for (var sField in oGlobals['oSortFields']){
		aoActions.push({
			text: oGlobals['oSortFields'][sField],
			data: JSON.stringify({field: sField}),
			value: sField
		});
	}

	var hModal = myApp.actions(aoActions);

	jqModal = $(hModal);

	jqModal.attr('id','action-sheet-home-sort');
}
```
