### ISSUE TITLE
Vue Cordova no images transferring 

### ISSUE THREAD

**Issue by packytagliaferro** [nolimits4web/Framework7#1512]
I just started with Framework7 Vue starter kit and wasnt sure how the images worked. There is a folder for images under `src/assets/static/images` and in their docs it says to put images for the project there. My question is in a vue file how do I reference them? In the www project folder I dont see any images in put in the `src/assets/static/images` being transferred anywhere when I do a build? Do I need to add something to webpack config to do it?????

Framework V 1.5.4

### What you did
added images to `src/assets/static/images`

### Expected Behavior
webpack creates an image folder in the www folder when I build or run the app so i reference them like `<img src="img/logo.png">`

### Actual Behavior
No images are transferred anywhere that I can tell

**Comment by centrual** [comment]
Hallo @packytagliaferro 

You need to include image file inside javascript. Just like that:

```
var myImage = require('./src/assets/static/image/image.jpg')
// myImage = 'abcdef0987654321.jpg'

// --- OR IN SINGLE PAGE COMPONENT --- //

<script>
export default {
  data: {
    myImage: require('./src/assets/static/image/image.jpg')
  }
}
</script>

<template>
  <div>
    <img :src="myImage">
  </div>
</template>
```

Webpack automatically compiles included image files to output folder with new name. i couldn't find any other way to do it.

Have a great day!

**Comment by packytagliaferro** [comment]
Thanks @centrual that worked for when I add images to my .vue files but how would that work with my sass? For instance I am replacing some Font Awesome icons with my own to use within the system like so:
```
.fa-facebook::before {
  content: url("facebook.png");
}
```
So there is no js variable to use. If I try in main js:

`var myImage = require('./src/assets/static/image/image.jpg')`

it still will not transfer so I can use it in my Sass. It only works when I use the inside a js file calling the variable.

**Comment by ZanderBrown** [comment]
This seems to be much more a Vue.js issue than an F7 one.

That said tagging in @valnub

**Comment by packytagliaferro** [comment]
@ZanderBrown in Vue.js I can add an image like so just fine:

```
<script>
export default {
  data: {
    myImage: require('./src/assets/static/image/image.jpg')
  }
}
</script>

<template>
  <div>
    <img :src="myImage">
  </div>
</template>
```

The real issue is a Framework7 or documentation issue at least. The Framework you download has a specific folder for assets (`src/assets/static/`). In there there is a Sass folder that complies to CSS and is included in the build just fine. I think it is safe to assume that the Frameworks webpack config would also handle the transfer of images or anything in that assets folder. I have yet to find any information or documentation on how to transfer the images which seems like it would be a common situation to put images in the images folder and have webpack send them to the build.

**Comment by centrual** [comment]
@packytagliaferro Which template you are using currently? If it is cordova-template-framework7-vue-webpack than it's github page is: https://github.com/centrual/cordova-template-framework7-vue-webpack. Css-loader in webpack can catch relative file paths, so you can use relative file paths in your css. Check webpack loaders for more information.

But for main idea of your question: Static folder doing this job.

Sorry for bad English, my English not fluent. I hope I could help.

Have a great day!

**Comment by valnub** [comment]
I think he's referring to the starter packs at http://framework7.io/vue/ - especially the one with Webpack, that's just a guess though.

From what I understand, this is neither a Vue nor F7 issue but rather related to Webpack bundling and ES6 imports. I know that Webpack supports image bundling but I don't have experience with this. I usually do not bundle static stuff like images. Instead, I simply put them in the destination directory and then reference them in my html/js/css whatever.

Maybe this helps you? http://stackoverflow.com/questions/37671342/how-to-load-image-files-with-webpack-file-loader

Would love to hear what experiences others have with bundling static media via Webpack. I could imagine that one would run into performance/caching issues since images then couldn't be cached separately any more. Also, bundles would become ridiculously huge and would have to be transferred completely each time a new/different bundle is requested.

**Comment by packytagliaferro** [comment]
Thanks @valnub. I read through those links and got my scss file images working.

As for my initial comment, I think the confusion is there is nothing in the docs on what to expect. If you have used webpack before I get you might know how to reference images in sass and in .vue files, but I would suggest maybe some documentation in the github repo just to save some people some time, specially if they are used to Gulp where it actually transfers all the files and folders.
