### ISSUE TITLE
floating action button position in rtl direction

### ISSUE THREAD

**Issue by kkordinia** [nolimits4web/Framework7#1514]
in rtl direction, floating action button Placed on right of page while it should be palaced on left of page. please fix this problem.

**Comment by sepehrr** [comment]
I think it's better to be optional and developer decides it goes to left or right side of the app.

**Comment by nolimits4web** [comment]
Fixed in v2

**Comment by Maheshwbc** [comment]
Floating button got hidden in Android


I am using floating action button in page.

But its not working in android device.

When scroll the page sometimes only shows the button.

Device : Lenovo model:: Vibe k5
OS: Android 5.1.1- lollipop


![plus icon](https://user-images.githubusercontent.com/32213371/37271722-1aa31de8-25fa-11e8-8049-2cc93d0d01fc.png)


Other device screens

![screen shot 2018-03-12 at 12 54 49 pm](https://user-images.githubusercontent.com/32213371/37271728-23129b34-25fa-11e8-80c0-f8de5b749ae3.png)
