### ISSUE TITLE
I want to load an external JS file on page intialization?

### ISSUE THREAD

**Issue by alapanme** [nolimits4web/Framework7#1515]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

### What you did
I want to display some Mathematical expression on my app. In my index.html file on mentioning the Js file under script tags, everything works well, but when I am navigating to other pages, the JS file doesn't need to be loading. So to curb the issue I wrote this on the my-app.js file:

myApp.onPageInit('numbersystem', function (page) {
$$.getScript('https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML')
});

### Expected Behavior
The JS file should be loaded upon page initialization of numbersystem page and the Maths expression should be updated on the page.

### Actual Behavior
Nothing Happened.

**Comment by ZanderBrown** [comment]
"Nothing Happened." more acuratly `TypeError: $$.getScript is not a function` was thrown because `$$.getScript` doesn't exist.

Why can't you refrence the script in `index.html` or include it's contents in the `page:init` handler?

**Comment by alapanme** [comment]
Hi @ZanderBrown I have referenced the script in the Index only, but since the pages are loaded as ajax, the external js https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML is not loaded in other pages except index. If I have to load the external JS via page init, how can I do that?

**Comment by ZanderBrown** [comment]
5 mins looking at the docs for MathJax.js say to call `MathJax.Hub.Typeset()` after inserting dynamic content

```js
myApp.onPageInit('*', function () {
    MathJax.Hub.Typeset();
});
```

**Comment by alapanme** [comment]
Thanks a lot @ZanderBrown . Appreciate your help.

**Comment by ZanderBrown** [comment]
@alapanme your welcome 😄
