### ISSUE TITLE
Close Modal by clicking the overlay

### ISSUE THREAD

**Issue by eeeeeLin** [nolimits4web/Framework7#1519]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* [Link scenario](https://codepen.io/QinSung/pen/EmgaKw)

### What you did
Open a Modal

### Expected Behavior
Can I close the Modal by clicking the overlay, as the popup

**Comment by ZanderBrown** [comment]
Please remember that this is not a help forum & [to read the docs](http://framework7.io/docs/init-app.html)

Close by outside is disabled by default for models, [you need to set `modalCloseByOutside` to true](https://codepen.io/anon/pen/eWdzgY)

**Comment by eeeeeLin** [comment]
Thx ~ 
Appreciate it 😜
