### ISSUE TITLE
Custom Build problem

### ISSUE THREAD

**Issue by idyrda** [nolimits4web/Framework7#1522]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 1.6.0
* Platform and Target: CORDOVA, ANDROID.

### What you did
I custom for search and test all components/modules 
from page https://framework7.io/docs/custom-build.html
gulp custom -accordion,searchbar,messages,modals,swipeout,sortable,cards,smart-select,virtual-list,pull-to-refresh,infinite-scroll,scroll-toolbars,tabs,fast-clicks,forms,push-state,progressbar,autocomplete,swiper,photo-browser,notifications,picker,calendar

### Expected Behavior
Everything has to work.

### Actual Behavior
Timeline does not appear in the style after custom.
Why?

**Comment by ZanderBrown** [comment]
It seems `modules.json` wasn't updated to support timeline

**Comment by lovelyelfpop** [comment]
This is still not solved
