### ISSUE TITLE
search if previousQuery doesn't exist

### ISSUE THREAD

**Issue by Phillipip** [nolimits4web/Framework7#1526]
* [x] bug

### What you did
i opened the searchbar again and put the last search string into the input field. if i delete this, i get no new searchresult.

### Expected Behavior
should be start new search

### Actual Behavior
if it is one one character it doesn't start new search after deleting this character.

**Comment by ZanderBrown** [comment]
Could you please expand you point?
Consider pointing code snippets here, on [Codepen](https://codepen.io) or on [JSFiddle](https://jsfiddle.net).
Make sure you have read the [documentation](http://framework7.io/docs/) correctly and followed any instructions it may give.

**Comment by Phillipip** [comment]
It would be great if you could confirm my fix. I have not so much time to build a testcase :-( you can test it with phone here: https://www.gayguide.travel/Europa/Deutschland/Berlin
please open the filter and add a character to searchbar, then close the filter and open again. now it's possible to remove this character and the search start now.
