### ISSUE TITLE
Using the framework7 development page, there will be no scrollbars on my phone

### ISSUE THREAD

**Issue by Eliosa** [nolimits4web/Framework7#1541]
Because of demand, I need to replace height:100% whole with height:auto, but this will cause the page to not display.what should i do.（ i wonder if there are other ways to make the page scroll when it slides on the phone.）
因为用framework7开发的页面，是放在 微信 上使用的，但是因为所有的元素都有 height:100%属性，使得页面不会有滚动条（可能是其他原因导致的，但我实在没有找到）。但是当我将 css属性中的,height:100%替换成 height:auto时， 页面一片空白。
我想知道有没有其他方法，可以使页面在手机上显示时，出现滚动条。

**Comment by valnub** [comment]
This is not possible since F7 uses [momentum scrolling](https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/) rather than page scrolling.

In short: Don't mess around with scrolling.
