### ISSUE TITLE
Data table column sort does not work in kitchen sink

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7#1548]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

### What you did
Played with the kitchen sink on Framework7.io, opened data tables page, clicked on column header in order to sort table.

### Expected Behavior
Sorted by selected column.

### Actual Behavior
Nothing happend.

Browser: Google Chrome on macOS
![bildschirmfoto 2017-05-07 um 22 13 06](https://cloud.githubusercontent.com/assets/19615586/25784749/a55b47f6-3372-11e7-9602-7cb460bc98f0.png)

**Comment by lothcor** [comment]
It is noted in the docs at the bottom of the sortable section
http://framework7.io/docs/data-table.html#sortable

Note, there is no actual sortable logic provided by framework. Actual sorting logic should be realized manually

**Comment by scriptPilot** [comment]
@lothcor - OK, so I updated the issue as an enhancement, not as a bug.

**Comment by valnub** [comment]
Yes, @lothcor is right. F7 only provides the look and feel. Logic has to be implemented on your own.

**Comment by caique0202** [comment]
What is the event when the sort column is clicked?

Thanks
Carlos
