### ISSUE TITLE
Autocomplete not in full screen feature request

### ISSUE THREAD

**Issue by peon501** [nolimits4web/Framework7#1550]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

![image](https://cloud.githubusercontent.com/assets/1125765/25791652/80662a62-33ca-11e7-8667-00ac6c191cb8.png)

### What you did
I just want autocomplete with html content,not in full screen, but cant find element like this.

### Expected Behavior
I just want autocomplete with html content,not in full screen.

### Actual Behavior
We dont have element like this, so yeah I think we need this feature.

**Comment by peon501** [comment]
****
![image](https://cloud.githubusercontent.com/assets/1125765/25792274/45c9df8a-33ce-11e7-98f5-29a8313140d9.png)
ps. I tryed dropdown in navbar but it throws error.

**Comment by ZanderBrown** [comment]
No confused now

**Comment by valnub** [comment]
Don't get it 😕 ❓

**Comment by ZanderBrown** [comment]
I think we can close this as out of scope
