### ISSUE TITLE
Ajax Form Submit can not send form data to server

### ISSUE THREAD

**Issue by kkordinia** [nolimits4web/Framework7#1556]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.0
* Platform and Target: CORDOVA

### What you did
Ajax Form Submit can not send data to server in post method. see below code:

```html
<form action="https://reqres.in/api/login" class="list-block inputs-list ajax-submit" method="post">
	<ul>
		<li>
			<div class="item-content">
				<div class="item-inner">
					<div class="item-title floating-label">
						Email Address
					</div>
					<div class="item-input">
						<input name="email" type="email">
					</div>
				</div>
			</div>
		</li>
		<li>
			<div class="item-content">
				<div class="item-inner">
					<div class="item-title floating-label">
						Password
					</div>
					<div class="item-input">
						<input name="password" type="password">
					</div>
				</div>
			</div>
		</li>
		<li>
			<div class="item-content">
				<div class="item-inner">
					<div class="buttons-row">
						<button class="button button-raised button-fill" type="submit">Login</button>
					</div>
				</div>
			</div>
		</li>
	</ul>
</form>
```
whe i submited the form get an bad request error. when i checked the request parameters, form data is null:
```ts
$$(".ajax-submit").on("form:error", (e: F7Event) => {
	App.hidePreloader();
	App.alert(JSON.stringify(e.detail.xhr.requestParameters.data));
});
```

**Edit by @ZanderBrown for code readability**

**Comment by ZanderBrown** [comment]
Shouldn't make any difference but are you using TypeScript by any chance?
Have you been able to test this with the debugger / console open?

**Comment by kkordinia** [comment]
i using framework7 with typescript and [visual studio tools for apache corodva](https://taco.visualstudio.com/). [you can find framework7 defination for typescript here.](https://github.com/JasonKleban/Framework7.d.ts). and i put F7Event interface in below code:
`interface F7Event extends Event {
    detail: {
        xhr:Dom7.Dom7XHR,
        data:any
}
}`

**Comment by ZanderBrown** [comment]
Okay that answers the out of interest / off topic question, how about about the one that might help us fix the issue:
> Have you been able to test this with the debugger / console open?

[This seems to show how](https://taco.visualstudio.com/en-us/docs/debug-using-visual-studio/)

**Comment by kkordinia** [comment]
in visual studio javascript console i get this error:

> Failed to load resource: the server responded with a status of 400 (Bad Request)

**Comment by kkordinia** [comment]
It seems that ajax form submit send request content type as multipart/form-data.

**Comment by kkordinia** [comment]
i found the soulation. just replace this code in [forms-ajax.js](https://github.com/nolimits4web/Framework7/blob/master/src/js/framework7/forms-ajax.js) file:
```js
 if (method === 'POST') data = new FormData(form[0]);
else data = $.serializeObject(app.formToJSON(form[0]));
```
with this code:
```js
var data = app.formToJSON(form[0]);
```
this soulation work for me.
