### ISSUE TITLE
Accent insensitive search on search and smart-select

### ISSUE THREAD

**Issue by JCKodel** [nolimits4web/Framework7#1558]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: "framework7": "^1.5.4",
* Platform and Target: cordova browser
* Live Link or JSFiddle/Codepen: 

### What you did
Created a Vue listitem with accented strings (ex.: Coração):
```
<f7-list-item smart-select smart-select-searchbar smart-select-open-in="popup" title="Operações" smart-select-searchbar-placeholder="Pesquisar">
				<select name="car" multiple="multiple" >
					<optgroup v-for="operation in operations" v-bind:label="operation.text">
						<option v-for="item in operation.children" v-bind:value="item.id">{{item.text}}</option>
					</optgroup>
				</select>
			</f7-list-item>
```

### Expected Behavior
While searching the list, when typing coracao, it should find the option Coração (case and accent insensitive).

Or at least give me an event to program it.

### Actual Behavior
coracao filters Coração

**Comment by Extracreative** [comment]
@JCKodel 
I used this to this 
`
Dom7.removeDiacritics
$$.removeDiacritics(text) - Replace diacritics in specified text string with standard latin characters

text - string - Text string
var text = $$.removeDiacritics('ÁÓL');
console.log(text); //-> 'AOL'
`

**Comment by chittattoo** [comment]
chit

เมื่อ 24 ส.ค. 2017 14:52 "Luke Wheatle" <notifications@github.com> เขียนว่า

**Comment by JCKodel** [comment]
I know how to remove accents from a string, but there is no event (AFAIK) to do so on F7 autocomplete.
