### ISSUE TITLE
Calendar / datepicker Wrong month on data-month and  onDayClick function

### ISSUE THREAD

**Issue by vousys** [nolimits4web/Framework7#1561]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6
* Platform and Target: CORDOVA 
* Live Link or JSFiddle/Codepen: 
This screencast image is captured from your website https://www.screencast.com/t/mxgM2NJUT 

### What I did
When I click, I saw that the data-month attribute is 1 month before.
And another issue: If I need to use TODAY as minDate, I have to pass YESTERDAY value, because if I use TODAY, I can't click on today.

Thanks!

**Comment by ZanderBrown** [comment]
[Expected](https://linux.die.net/man/3/localtime) [behaviour](http://stackoverflow.com/a/344400/3975351) as [found](http://stackoverflow.com/questions/2552483/why-does-the-month-argument-range-from-0-to-11-in-javascripts-date-constructor) in mose [cases](https://web.archive.org/web/20111203213751/http://docs.oracle.com/javase/1.3/docs/api/java/util/Date.html) where dates are used programmatically

*Please note this comment contains a [saved response](https://help.github.com/articles/working-with-saved-replies/)*
