### ISSUE TITLE
I do not understand...

### ISSUE THREAD

**Issue by sbegh** [nolimits4web/Framework7#1564]
* [x] bug

* Framework7 Version: Framework7 v1.6.0
* Platform and Target: ALL

### What you did
I use 3D panel and a button on the left to open it, when the panel is open, i change the class of the button in order to toggle functionnality => Change the icon and change the beahavior to close `it.`

this is the code ::

`$$('.panel-left').on('panel:opened', function () {
$$('#men').removeClass('icon icon-bars').addClass('fa fa-arrow-circle-o-left');
$$('#menubut').removeClass('open-panel').addClass('close-panel');
console.log('open')

});	

$$('.panel-left').on('panel:closed', function () {
$$('#men').removeClass('fa fa-arrow-circle-o-left').addClass('icon icon-bars');
$$('#menubut').removeClass('close-panel').addClass('open-panel');
console.log('close')
});	`

### Expected Behavior
do the thing !

### Actual Behavior
it's work like a charm in main view, but nothing not on the other views... only the console.log works...

PS : sorry for my english...

**Comment by snakeman21** [comment]
If you're talking about this https://github.com/nolimits4web/Framework7-3D-Panels, it's a little out of date. Hasn't been updated to conform to the latest F7.

**Comment by sbegh** [comment]
Hi, Thank you for the answer, I'am going to change so...

**Comment by sbegh** [comment]
Hi,
Nope...i've changed to another thing...
Thank for reply
