### ISSUE TITLE
Swipeable Tabs Disables Swipe Back on page with Dynamic Navbar

### ISSUE THREAD

**Issue by snakeman21** [nolimits4web/Framework7#1568]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: 1.5.4
* Platform and Target: iOS 10.3.2

### Expected Behavior
I'd like to be able to still use the dynamic navbar swipe back feature alongside the swipeable tabs.

### Actual Behavior
If you use the swipeable tabs, then you can't swipe back pages like you normally could when using the through layout. On the computer it actually works perfectly, but not on a mobile device. Try out the kitchen sink example on your phone and you'll see.

Maybe this isn't a bug and is expected behavior, but I figured I'd raise this issue in case it is in fact a bug. If this is the case, then I apologize in advance.

**Comment by valnub** [comment]
I'm not sure if this is possible. I mean if you swipe on an element, how is the device gonna know if you want to swipe the tabs or swipe back?

**Comment by snakeman21** [comment]
Was thinking the same thing. I think I may actually have a solution for this myself, and I would love to send a pull request once I have more free time. I'll close this as I feel really bad adding another issue for Vladimir on here.

**Comment by valnub** [comment]
Ha, ha, no problem. PR's are always welcome of course :-)
