### ISSUE TITLE
Improve Input files

### ISSUE THREAD

**Issue by vousys** [nolimits4web/Framework7#1570]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6
* Platform and Target:CORDOVA

I would be very useful if the input box (text, number, email, textarea) could have the "X" at the end of it, so the user could clear all of its content.

**Comment by J05HI** [comment]
Develop it by your own, it's easy :)

**Comment by valnub** [comment]
Pull requests and plugins welcome :-)

See

- https://help.github.com/articles/about-pull-requests/
- http://framework7.io/docs/plugins-api.html

**Comment by vousys** [comment]
I fix it using the type "search" instead "text". Maybe this could help someone else.
