### ISSUE TITLE
unsafe-eval is not allowed with CSP

### ISSUE THREAD

**Issue by frozenamazon** [nolimits4web/Framework7#1573]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.0
* Platform and Target: Web

### What you did
I am using Framework7 together with the baked in Template7. In my html, I have included the meta tag to include Content-Security-Policy. 
<meta http-equiv="Content-Security-Policy" content="default-src 'self'"/>

### Expected Behavior
Should work with CSP?

### Actual Behavior
'Uncaught EvalError: Refused to evaluate a string as Javascript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self'"
at eval()
at o (framework7.js:13994)

**Comment by ZanderBrown** [comment]
if you bundle all you js into one HTML file does it work

**Comment by frozenamazon** [comment]
Hi Zander
Do you mean bundle all the js into one js file then link to that file? I am currently already doing that. If you meant include all the JS and embed into the HTML with a script tag, it usually disabled as CSP do not allow inline scripts.

**Comment by ZanderBrown** [comment]
Hmm, checking the docs `eval` isn't allowed anywhere.
How about opening an issue in the T7 repo?

**Comment by frozenamazon** [comment]
Ok will do so. Thanks
