### ISSUE TITLE
Uncaught ReferenceError: Dom7 is not defined

### ISSUE THREAD

**Issue by PhilippeAssis** [nolimits4web/Framework7#1575]
As of version 1.6.2, when using the webpack, this error is returned: Uncaught ReferenceError: Dom7 is not defined.

It is not yet time to try to solve it. So good luck: D

*Version 1.6.0 is okay for this

**Comment by devgeeks** [comment]
I am still seeing this in 1.6.3?

**Comment by PhilippeAssis** [comment]
@devgeeks Yes. The error persisted in 1.6.3.

**Comment by kokororin** [comment]
Use `imports-loader` and replace `import 'framework7';` with
`import 'imports-loader?exports=>false,define=>false,this=>window!framework7';`
could solve this problem temporarily.

**Comment by Wolferring** [comment]
should we import Dom7 manually?

**Comment by nolimits4web** [comment]
Fixed in v1.6.4
