### ISSUE TITLE
Datepicker causes routing 

### ISSUE THREAD

**Issue by alonrbar** [nolimits4web/Framework7#1577]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.0
* Platform and Target: PhoneGap with Aurelia

I'm using Aurelia's router instead of Framework7's. When I click the 'Done' button it navigates to /# and it messes up with my routes. I fixed it in my code using this line inside the onOpen event handler:

`calendar.container.find('.button.close-picker').removeAttr('href');`

Though I think it's better if the href wasn't there in the first place...

EDIT:

Well, just found out it happens also when changing months using the picker. Changed my solution to:

`calendar.container.find('a').removeAttr('href');`

b.t.w - thanks, it's a great framework!

**Comment by valnub** [comment]
Great that you found the solution for your issue.

However, it is usually best to use F7 router instead or others.
