### ISSUE TITLE
[v2] FAB Component

### ISSUE THREAD

**Issue by nolimits4web** [nolimits4web/Framework7#1582]
* [x] Implement/Port
* [x] Support for more positions
* [x] Morph to elements
* [x] ~Morph to Popover~ (removed)

**Comment by J05HI** [comment]
@nolimits4web 
How about adding labels to the FAB?
Like Angular Material [https://material.angularjs.org/latest/demo/fabSpeedDial](https://material.angularjs.org/latest/demo/fabSpeedDial)


![1](https://user-images.githubusercontent.com/16399787/27508525-672ad1b4-58e7-11e7-9e02-f5c3f6f23391.PNG)

**Comment by J05HI** [comment]
@nolimits4web 
Many thanks for the new morph buttons!!!
They are amazing and the animation is butter smooth :)

**Comment by J05HI** [comment]
@nolimits4web 
Another improvement:
Hide fab on scroll optionally :)

**Comment by J05HI** [comment]
@nolimits4web 
It would also be great to have morph to page if that isn't already possible :)

**Comment by J05HI** [comment]
@nolimits4web 
It would also be great to have morph to page if that isn't already possible :)

**Comment by J05HI** [comment]
@nolimits4web 
Can you please add the FAB labels?
