### ISSUE TITLE
[v2] Cards Component

### ISSUE THREAD

**Issue by nolimits4web** [nolimits4web/Framework7#1584]
Depends on #1602

**Comment by valnub** [comment]
Started working on this

**Comment by ZanderBrown** [comment]
How does this depend on #1602?

**Comment by nolimits4web** [comment]
@ZanderBrown Card links in card-footer in MD theme should looks like a button https://github.com/nolimits4web/Framework7/blob/v2/src/components/card/card-md.less#L22

**Comment by valnub** [comment]
Yes, I added CSS manually in md CSS for Cards temporarily but it would be better if CSS from button component would be used.

**Comment by valnub** [comment]
See line 25 here https://github.com/valnub/Framework7/blob/c5d5fcd814b4c2c8ed63c2499367999735cec5e8/src/components/card/card-md.less

**Comment by ZanderBrown** [comment]
Side note: [You can link to a specific line](https://github.com/valnub/Framework7/blob/c5d5fcd814b4c2c8ed63c2499367999735cec5e8/src/components/card/card-md.less#L25)

**Comment by valnub** [comment]
Thanks, but I knew that. Didn't work well on my iPhone though :-)
