### ISSUE TITLE
[v2] Form Inputs

### ISSUE THREAD

**Issue by nolimits4web** [nolimits4web/Framework7#1601]
* [x] Text-fields
* [x] Floating labels
* [x] Validation
* [x] Resizable textarea
* [x] Radio and Radio List
* [x] Checkbox and Checkbox List

**Comment by kkordinia** [comment]
there are several problem for form inputs in framework7. The most important is when we focus on form input and keyboard appeared, input hidden and page-content element not scrolled to input (in prompt modal input, This problem does not exist) . please fix this problem in version 2.0
