### ISSUE TITLE
[v2] Button Component

### ISSUE THREAD

**Issue by nolimits4web** [nolimits4web/Framework7#1602]

**Comment by ZanderBrown** [comment]
Work-in-progress https://github.com/ZanderBrown/Framework7/tree/v2

**Comment by J05HI** [comment]
@nolimits4web 
What about adding this type of buttons?

![screenshot_20170624-145444](https://user-images.githubusercontent.com/16399787/27508821-f5335caa-58ed-11e7-86d0-558f9e39a732.png)

**Comment by J05HI** [comment]
@nolimits4web 
Great! Thank you very much :)

**Comment by numberokta** [comment]
When touch and hold two button together ripple stuck on one of them !
