### ISSUE TITLE
[v2] List View Component

### ISSUE THREAD

**Issue by nolimits4web** [nolimits4web/Framework7#1610]

**Comment by J05HI** [comment]
@nolimits4web
Sticky list group titles only work for iOS Safari :(
On other devices its hidden behind the navbar. I hope you can fix that.

![](http://i.imgur.com/R1eqhWe.png)   


If I remove the navbar it's visible:

![](http://i.imgur.com/dP0VJVM.png)

**Comment by J05HI** [comment]
@nolimits4web 
Great fix! Thank you very much!!!
