### ISSUE TITLE
[v2] Navbar

### ISSUE THREAD

**Issue by nolimits4web** [nolimits4web/Framework7#1616]
* [x] Hide on page scroll functionality
* [x] Hide/show for pages on page change
* [x] Subtitle
* [x] Hidden for default page
* [x] Don't move Navbar from page for iOS dynamic navbar. Done with `iosSeparateDynamicNavbar` router parameter
* [x] Improve iOS theme transitions when dynamic navbar is not separated

**Comment by J05HI** [comment]
Reference to https://github.com/nolimits4web/Framework7/issues/1582#issuecomment-311034945 for the hide on scroll functionality.
