### ISSUE TITLE
[v2] Components

### ISSUE THREAD

**Issue by nolimits4web** [nolimits4web/Framework7#1624]
* [x] `mounted` lifecycle method
* [x] `beforeDestroy` lifecycle method
* [x] `destroy` lifecycle method
* [x] Better handling for custom events, attaching and detaching
* [x] Better handling for scoped styles

**Comment by nolimits4web** [comment]
beforeCreate, created, mointed, beforeDestroy, destroyed

**Comment by J05HI** [comment]
@nolimits4web 
Can you please implement a functionality (api) that gives us the ability to write and add our own components?

**Comment by ZanderBrown** [comment]
https://developer.mozilla.org/en-US/docs/Web/Web_Components

**Comment by J05HI** [comment]
@ZanderBrown 
Great thank you very much!!!

**Comment by ZanderBrown** [comment]
I believe Safari will need a polyfill but on Chrome it should **just work™**

**Comment by J05HI** [comment]
@ZanderBrown 
Okay mabe @nolimits4web will describe on the f7 website how to do it.
