### ISSUE TITLE
Can't remove message using "myMessages.removeMessage(message);"

### ISSUE THREAD

**Issue by peterel** [nolimits4web/Framework7#1640]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: Framework7 1.5.0,  Released on: November 8, 2016      
* Platform and Target: Web
* Live Link or JSFiddle/Codepen (IMAGE ADDED): 

<img width="375" alt="screen shot 2017-06-08 at 18 23 22" src="https://user-images.githubusercontent.com/24371993/27014229-ef80ae14-4ef4-11e7-8ed0-5776e438266d.png">

### What you did
Using e.g.

`myMessages.removeMessage(".message-first");`

deletes all messages. I want to delete the last message but cant distinguish between them all except for all sent and all received.

### Expected Behavior
I expect to have a difference between the messages to pinpoint what message to delete. Otherwise, how would the .removeMessage actually work.

### Actual Behavior
All or no messages are deleted.

--
What I want to create is a "I am writing message" as you get in iOS at least (with a "bouncing" dotdotdot "..."). This message is then deleted before the actual message has reached the client. Adding a "..." is no problem, making it "bounce" I may be able to figure out somehow but any tips are more than welcome, removing that specific message is what I primarily need help with here.

**Comment by shevcenko9** [comment]
i also hava a same issue, i use sqlite to save my messages but i dont have any idea how to use myMessages.removeMessage();

>  $$('.message-text').on('click', function (e) {
		// here is command to delete my message   
	});	
if you already got the solution please help me too
thankyou

**Comment by peterel** [comment]
@shevcenko9 Nope, Ive not hear of anything about this nor have I gotten it solved. Still waiting to hear if this is bug or if I simply doing something else wrong.

You are very welcome to also let me know if you figure this out :)

**Comment by peterel** [comment]
@shevcenko9 Ive also posted this on SO and got below response a while back. Its a workaround which I didnt get to work unfortunately. Maybe it helps you? 

https://stackoverflow.com/questions/44441172/remove-message-framework7

**Comment by dawuwu** [comment]
Does this also happen with Framework7 1.6.4?

**Comment by peterel** [comment]
@dawuwu I dont know. Id prefer not to update just to test this. If it is a know issue that is fixed in 1.6.4 then Id be more than happy to update :) Anyway, Ive now made a "ugly" solution which is shared here: https://stackoverflow.com/questions/44441172/remove-message-framework7. Ill keep this ticket open until someone from this repos team says its a bug or not and to close it or not.

**Comment by shevcenko9** [comment]
@peterel  thankyou sir

**Comment by nolimits4web** [comment]
Well, looks like the issue is about how CSS selectors work. So just `myMessages.removeMessage(".message:last-child");`

**Comment by peterel** [comment]
@nolimits4web Thanks, that works.
