### ISSUE TITLE
Autocomplete menu flushes to the left when inside list-block class

### ISSUE THREAD

**Issue by kobyl** [nolimits4web/Framework7#1646]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: Whatever the default fiddle (https://jsfiddle.net/s2n1p730/) is based on.
* Platform and Target: Cordova/Web(Chrome)
* Live Link or JSFiddle/Codepen: https://jsfiddle.net/s6xqmudv/

### What you did
Attempting to use autocomplete. When in tablet mode I'd like to have a form in 3 columns. Built form, wrapping in list to get pretty styling.

### Expected Behavior
Clicking on middle and right columns have the autocomplete come up under the textboxes in correct place.

### Actual Behavior
When wrapped in the list-block class, the autocomplete flushes left(left:0). The JSFiddle should be pretty clear on what's happening.

Similar issue: 1381

**Comment by nolimits4web** [comment]
Fix in v2
