### ISSUE TITLE
How to load a html page inside a div of another page

### ISSUE THREAD

**Issue by surendiranganesan** [nolimits4web/Framework7#1648]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.4
* Platform and Target: 
* Live Link or JSFiddle/Codepen: 

### What you did
Thank you for giving this amazing framework.

I am using requireJs in my project[taken example from your official website tutorials]
I am loading all pages via ajax. for ex take 4 pages
main page
page1
page2
page 3

I need to show page 3 in both page1 and page 2. i tried app.mainview.load method which navigates to page 3. i want to show page 3 inside a div of page 1 and page 2.

kindly help me how to achieve this.

regards,
suren

**Comment by kinimodmeyer** [comment]
hey ho, i dont use requireJS but if you want to load stuff for your page you can do it with this:
```
$$(document).on('page:beforeanimation', function (e) {
    var page = e.detail.page;

    if (page.name == 'page1' || page.name == 'page2') {
    $$.ajax({
            type       : "GET",
            url        :  'page3.html',
            crossDomain: true,
            dataType   : 'html',
            timeout    :  10000,
            success    : function(html) {
                $$(e.target).find('.page-content').html(html);
            }
        });
  }
```

**Comment by ZanderBrown** [comment]
Seriously out of scope
