### ISSUE TITLE
Feature request: Floating button + infinite-scroll // Fixed aligned to right bottom  (Material design) // 

### ISSUE THREAD

**Issue by vousys** [nolimits4web/Framework7#1649]
This is a (multiple allowed):
* [x] bug 

* Framework7 Version: 1.6.4.
* Platform and Target:  CORDOVA 

Hi Vladimir, this is a css fix I had to use everywhere and maybe you can add it to the core.

The problem:
When you scroll down using an infinite-scroll, and has floating button in the code, it's stay in absolute position, not moving with the content and re-aligned.
This pictures shows you as an example:

![image](https://user-images.githubusercontent.com/12813221/27256432-df23264c-538a-11e7-9c50-cae5de308e06.png)

This is the html I use:

```
	<div class="tabs-swipeable-wrap">
		<div class="tabs">

			<div id="tab-mis-novedades" class="page-content infinite-scroll tab active"  >

				<div class="content-block ">


					    <!-- Preloader -->
					  <div class="infinite-scroll-preloader">
					    <div class="preloader">CARGANDO</div>
					  </div>

					<div class="card sin-registros">
						<div class="card-content">
							<div class="card-content-inner">
								<p>Ups... No tienes ningúna novedad favorita :(</p>
							</div>
						</div>
					</div>
					<div class="cards">

					</div>
				</div>

				<a href="#" class="floating-button novedades_nuevo" data-tipo="2"><i class="icon icon-plus"></i></a>

			</div>

```

And this is the css I had to add in my projects to fix it.

```
		.tab .content-block + .floating-button {
			position: fixed;
			right: auto;
		}
		.tab:nth-child(1) .content-block + .floating-button { left: calc(100% - 72px) }
		.tab:nth-child(2) .content-block + .floating-button { left: calc(200% - 72px) }
		.tab:nth-child(3) .content-block + .floating-button { left: calc(300% - 72px) }
		.tab:nth-child(4) .content-block + .floating-button { left: calc(400% - 72px) }

```

**Comment by Flame2057** [comment]
+1 same issue

**Comment by vousys** [comment]
I've found the solution. The floating button should be outside the page-content div.

https://github.com/nolimits4web/Framework7/commit/8aaabd8c69f653ded35bb6394629ac31e8a75b71
