### ISSUE TITLE
1.6.3 => 2.0 version

### ISSUE THREAD

**Issue by krosoftware** [nolimits4web/Framework7#1656]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

Hello
question si regarding upgrading 1.6.3 => 2.0 version - is it possible to use existing code (1.6.3) in 2.0 version, without changes or some changes will be needed?
Thank you.

**Comment by ZanderBrown** [comment]
Some changes will be needed. I expect documentation to be available when 2.0 is released to ease the process.
