### ISSUE TITLE
Feature request: Add class in parameters in Custom modals

### ISSUE THREAD

**Issue by vousys** [nolimits4web/Framework7#1657]
Hi Vladimir, can you add this, for you next release:

In the optionals parameters of custom modals, create a new one, to add a "Class" which will be added next to: class="modal  modal-in".
It would be very usefull when you create dynamic modal.

**Comment by nolimits4web** [comment]
Hi @vousys . Well, it is not documented but it is already supported by adding `cssClass` parameter to custom modal

**Comment by vousys** [comment]
oh!!! excellent   :)
Thank you!!!
