### ISSUE TITLE
Cannot type into editor using f7

### ISSUE THREAD

**Issue by wsngamerz** [nolimits4web/Framework7#1660]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 1.6.4
* Platform and Target: cordova android only

### What you did
enabled and added the ide to the project.
There is a video [here](https://youtu.be/CMJqtMfEJPI) showing what is happening

### Expected Behavior
You are ment to be able to tap on the ide and type.

### Actual Behavior
You cannot type anything or even select the editor but if you try and use it out of the f7 envoronment, it will work like normal in chrome browser on android and cordova.
https://realstep.co.uk/Projects/mobileIDE/test.html shows it working mormaly out of f7
https://realstep.co.uk/Projects/mobileIDE/index.html shows it broken

**Comment by wsngamerz** [comment]
It is caused by the touchstart event listeners added by framework7, is there a way to disable it?

**Comment by ZanderBrown** [comment]
Disable fast click

**Comment by wsngamerz** [comment]
Thanks, you helped alot
