### ISSUE TITLE
ajaxComplete and ajaxSend

### ISSUE THREAD

**Issue by sbryfcz** [nolimits4web/Framework7#168]
Any chance we could get ajaxComplete and ajaxSend functions implemented like they are in jquery? I have a need to use them for jwt authentication and would prefer not to bring jquery into my library if possible.  Thanks!

**Comment by petarov** [comment]
I've actually tested these in the latest master but I could not get them to work. `complete` and `beforeSend` are not being triggered.

Neither this:

```javascript
	$$.ajaxSetup({
		'complete': function(xhr, stat) {
			console.log('complete');
		},
		'beforeSend': function(xhr) {
			console.log('beforeSend');
		}			
	});	
```
nor this:

```javascript
		$$.ajax({
			method: method,
			url: url,
			data : params,
			success : function(data, status, xhr) {

			},
			error: function(xhr) {

			},
		    complete: function(xhr, stat) {
			  console.log('complete');
            },
		    beforeSend: function(xhr) {
			 console.log('beforeSend');
            }	
		});
```

**Comment by nolimits4web** [comment]
@petarov are you using it to request `JSONP`?

**Comment by petarov** [comment]
@nolimits4web Yeah, I've just edited my comment. It's jsonp.

**Comment by nolimits4web** [comment]
But as you may see in code, JSONP request is not XHR request at all, it is just loading JS using `<script> ` tag. I may try to emulate these callbacks using `.onload` script callback but there is no much sense in it

**Comment by petarov** [comment]
Ah, you're right! I've missed that. 
No, I think there's no point in adding these callbacks for <script> loading. I'll be doing some tests with POST queries later on.

**Comment by sbryfcz** [comment]
Thanks for working on this. One less item I need to use jquery for.

**Comment by petarov** [comment]
I can confirm that both callbacks work for GET, POST non-jsonp requests. I think this may be closed.
