### ISSUE TITLE
Pass Custom Context not working!

### ISSUE THREAD

**Issue by rtanzifi** [nolimits4web/Framework7#1681]
Hey guys. First i should thanks you all for The best Framework7. I have a problem in passing custom context to a page. Lets see, I have a page with Listview on it. The listview items are populated with database. Here is my code:

~`for(var x = 0; x < resultSet.rows.length; x++) {
                resultContent += "<li><a href='contentPage.html' data-context="+'{"title": "'+resultSet.rows.item(x).title+'", "body": "'+resultSet.rows.item(x).body+'"}'+"class='item-link item-content'><div class='item-inner'><div class='item-title'>"+resultSet.rows.item(x).title+"</div></div></a></li>"
                // alert("id is :" + resultSet.rows.item(x).id +"  "+"title is : "+ resultSet.rows.item(x).title);
            }`~

```js
for(var x = 0; x < resultSet.rows.length; x++) {
    resultContent += "<li><a href='contentPage.html' data-context="+'{"title": "'+resultSet.rows.item(x).title+'", "body": "'+resultSet.rows.item(x).body+'"}'+"class='item-link item-content'><div class='item-inner'><div class='item-title'>"+resultSet.rows.item(x).title+"</div></div></a></li>"
    // alert("id is :" + resultSet.rows.item(x).id +"  "+"title is : "+ resultSet.rows.item(x).title);
}
// Please ensure code is readable via the preview tab  - @ZanderBrown
```

So with above code i create a ListView with hyperlink on them to contentPage.html and pass data with data-context attribute. My contentPage look like this:

~[contentPage.html](https://ibb.co/iwjxUa)~

> ![image](https://user-images.githubusercontent.com/17074021/27997425-af7a4300-64ef-11e7-897f-82d4ea364f4f.png)
> <cite>It's easier if you embed images - @ZanderBrown</cite>

```html
<!-- or better yet actually embed the code - @ZanderBrown -->

<!-- We don't need a full layout in this file because this page will be parsed with Ajax. -->

<!-- Top Navbar -->
<div class="navbar">
	<div class="navbar-inner">
		<div class="right">
			<a href="#" class="back link">
				<i class="icon icon-back"></i>
				<!-- <span>Back</span> -->
			</a>
		</div>
		<div class="center sliding">{{title}}</div>
		<div class="right">
			<a href="#" class="link icon-only open-panel"><i class="icon icon-bars"></i></a>
		</div>
	</div>
</div>
<div class="page" data-page="contentPage">
	<div class="page-content">
		<div class="content-block-title">{{title}}</div>
		<div class="content-block">
			<p>{{body}}</p>
		</div>
	</div>
</div>
```

The problem is Listview populated right but when click on items nothing happen. Did i miss something? This is my first app. Any help would be appreciated. Thanks

**Comment by ZanderBrown** [comment]
Where is 
```js
for(var x = 0; x < resultSet.rows.length; x++) {
    resultContent += "<li><a href='contentPage.html' data-context="+'{"title": "'+resultSet.rows.item(x).title+'", "body": "'+resultSet.rows.item(x).body+'"}'+"class='item-link item-content'><div class='item-inner'><div class='item-title'>"+resultSet.rows.item(x).title+"</div></div></a></li>"
    // alert("id is :" + resultSet.rows.item(x).id +"  "+"title is : "+ resultSet.rows.item(x).title);
}
```
being run from? if it's after the page is initialised the click handlers may not be connected.

Any console errors?

**Comment by rtanzifi** [comment]
@ZanderBrown Thanks for answering. in myApp.onPageInit() function, after populate data from database, i am creating items to inject into ListItem. There is something intersting happen: When i removed data-context attribute and json string, the app works right. It create right URL for each <a> tag and navigation to contentPage.html works great(without any data pass) But when using data-context the URL not working(the anchor elemnt not change to blue link if you understand what i mean).

**Comment by rtanzifi** [comment]
Ok. I changed my code to this and now it's working:
```js
for(var x = 0; x < resultSet.rows.length; x++) {
                    jsonstr = '{"title": "'+resultSet.rows.item(x).title+'","myImage": "img/'+resultSet.rows.item(x).image+'", "body": "'+resultSet.rows.item(x).body+'"}';
                    resultContent += "<li><a href='contentPage.html' data-context='"+jsonstr+"' class='item-link item-content'><div class='item-inner'><div class='item-title'>"+resultSet.rows.item(x).title+"</div></div></a></li>";
                                   }
```
The problem is about quotation syntax in json string.

**Comment by ZanderBrown** [comment]
Suspected as much but I hadn't had a chance to check
