### ISSUE TITLE
Live Binding for Template7 Pages

### ISSUE THREAD

**Issue by kkordinia** [nolimits4web/Framework7#1682]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.4
* Platform and Target: CORDOVA

please add Live Binding feature for template7 pages like [CanJS Live Binding](https://v2.canjs.com/docs/can.mustache.Binding.html) or [handlebars.binding](https://www.npmjs.com/package/handlebars.binding).

**Comment by J05HI** [comment]
@kkordinia @nolimits4web 
This would be amazing!!!

**Comment by D-Marc1** [comment]
I agree, this would be awesome

**Comment by kkordinia** [comment]
I wanted this feature to update the content of the page after the change template7 page data. But the content of the page can be updated after the change through the following code:
```js
 viewMain.router.reloadPage("pagename.html");
```

**Comment by J05HI** [comment]
@kkordinia 
That's true but live binding would be great too!
