### ISSUE TITLE
Custom build failed

### ISSUE THREAD

**Issue by zannet** [nolimits4web/Framework7#1689]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.4
* Platform and Target: CORDOVA, IOS, ANDROID

### What you did
gulp custom -swiper,photobrowser

### Expected Behavior
successfully built

### Actual Behavior
src/js/dom7/framework7.custom.js
  line 252   col 36   Strings must use singlequote.
  line 252   col 77   Strings must use singlequote.
  line 254   col 34   Strings must use singlequote.
  line 254   col 69   Strings must use singlequote.
  line 273   col 51   Strings must use singlequote.
  line 278   col 50   Strings must use singlequote.
  line 287   col 50   Strings must use singlequote.
  line 472   col 34   Strings must use singlequote.
  line 475   col 54   Strings must use singlequote.
  line 478   col 50   Strings must use singlequote.
  line 515   col 47   Strings must use singlequote.
  line 540   col 53   Strings must use singlequote.
  line 543   col 81   Strings must use singlequote.
  line 550   col 51   Strings must use singlequote.
  line 556   col 26   Strings must use singlequote.
  line 556   col 46   Strings must use singlequote.
  line 556   col 68   Strings must use singlequote.
  line 556   col 88   Strings must use singlequote.
  line 556   col 98   Strings must use singlequote.
  line 556   col 120  Strings must use singlequote.
  line 655   col 98   Expected an assignment or function call and instead saw an expression.
  line 658   col 128  Expected an assignment or function call and instead saw an expression.
  line 683   col 29   If a strict mode function is executed using function invocation, its 'this' value will be undefined.
  line 690   col 29   If a strict mode function is executed using function invocation, its 'this' value will be undefined.
  line 697   col 29   If a strict mode function is executed using function invocation, its 'this' value will be undefined.
  line 922   col 47   Strings must use singlequote.
  line 1010  col 33   Strings must use singlequote.
  line 1053  col 22   If a strict mode function is executed using function invocation, its 'this' value will be undefined.
  line 1142  col 22   If a strict mode function is executed using function invocation, its 'this' value will be undefined.
  line 1704  col 13   If a strict mode function is executed using function invocation, its 'this' value will be undefined.
  line 1882  col 13   If a strict mode function is executed using function invocation, its 'this' value will be undefined.
  line 1975  col 22   Strings must use singlequote.
  line 1996  col 29   Strings must use singlequote.
  line 2071  col 45   Strings must use singlequote.
  line 2075  col 52   Strings must use singlequote.
  line 2106  col 58   Strings must use singlequote.
  line 2106  col 106  Strings must use singlequote.
  line 2130  col 24   Strings must use singlequote.
  line 2145  col 40   Strings must use singlequote.
  line 2145  col 73   Strings must use singlequote.
  line 2147  col 38   Strings must use singlequote.
  line 2147  col 70   Strings must use singlequote.
  line 2150  col 24   Strings must use singlequote.
  line 2150  col 37   Strings must use singlequote.
  line 2154  col 24   Strings must use singlequote.
  line 2180  col 21   Strings must use singlequote.
  line 2196  col 36   Strings must use singlequote.
  line 2196  col 64   Strings must use singlequote.
  line 2198  col 36   Strings must use singlequote.
  line 2198  col 58   Strings must use singlequote.
  line 2198  col 58   Too many errors. (19% scanned).

  ✖  1 error
  ⚠  50 warnings

**Comment by lovelyelfpop** [comment]
Does anyone have a workaround?

**Comment by lovelyelfpop** [comment]
I have found a workaround, just comment this line in `.jslintrc`
```
//"quotmark"     : "single",
```

**Comment by nolimits4web** [comment]
It is not failed, just a JSHint warnings. Build is still produced in custom folder
