### ISSUE TITLE
iOS8 document overscroll

### ISSUE THREAD

**Issue by johnjamesjacoby** [nolimits4web/Framework7#169]
In iOS8, the entire document now has an overscroll effect when reaching the top or bottom of any page. This is problematic for full-screen web-apps that typically would have fixed position bars and status-bar overlays.

![screenshot-2014-08-08-08 31 40](https://cloud.githubusercontent.com/assets/88951/3857159/959e2948-1f00-11e4-879f-2c2c1fa787e9.png)

**Comment by johnjamesjacoby** [comment]
I'm closing this here, as there is nothing F7 could do by itself to avoid this very annoying Safari and iOS web app bug. IMO this is Apple's UX to fix.

**Comment by nicooprat** [comment]
Not sure if I correctly understood your problem, but I'm using this code snippet (Coffeescript) :

```coffee
scrolling = false

$('body').on 'touchstart', '.page-content', (e) ->
  if !scrolling
    scrolling = true
    if e.currentTarget.scrollTop == 0
      e.currentTarget.scrollTop = 1
    else if e.currentTarget.scrollHeight == e.currentTarget.scrollTop + e.currentTarget.offsetHeight
      e.currentTarget.scrollTop -= 1
    scrolling = false
  if e.currentTarget.scrollHeight <= e.currentTarget.offsetHeight
    e.preventDefault()
  return

$('body').on 'touchmove', '.navbar', (e) ->
  e.preventDefault()
```

Seems to be working pretty well on iOS 8 (simulator + iPhone 5S tested, on web + Cordova hybrid app). Code taken from this SO answer : http://stackoverflow.com/a/14448336/758728.

I'm also using a little CSS hack to force `.page-content` to always scroll in Cordova app, even if the content is smaller than its container : 

```sass
.page-content:after
  content: ''
  position: absolute
  top: 100%
  height: 1px
  width: 100%
```

Hope it helps.
