### ISSUE TITLE
[v2] Space bug before lists

### ISSUE THREAD

**Issue by J05HI** [nolimits4web/Framework7#1702]
@nolimits4web

There is an ugly space between the headers and the lists (was in v1 too).
Is this intention or can you fix that, please :)

Here some samples:
![screenshot_20170804-210230](https://user-images.githubusercontent.com/16399787/28983369-b9f220ea-7959-11e7-8c3a-7dc84f4b50b3.png)
![screenshot_20170804-210427](https://user-images.githubusercontent.com/16399787/28983368-b9ed313e-7959-11e7-9c79-7d98f1639faa.png)
![screenshot_20170804-210022](https://user-images.githubusercontent.com/16399787/28983370-b9f68d06-7959-11e7-81f0-a38e945ffc95.png)
![screenshot_20170804-210048](https://user-images.githubusercontent.com/16399787/28983371-ba08348e-7959-11e7-8a97-835f7c371e2b.png)
![screenshot_20170804-210101](https://user-images.githubusercontent.com/16399787/28983372-ba0fc280-7959-11e7-946c-0a80b936bacc.png)
![screenshot_20170804-210200](https://user-images.githubusercontent.com/16399787/28983373-ba21eb86-7959-11e7-9994-70de04a43b19.png)

**Comment by ZanderBrown** [comment]
This is intentional and uses the common margins
