### ISSUE TITLE
[v2] got an error in console on login-screen-close 

### ISSUE THREAD

**Issue by GuillaumeBiton** [nolimits4web/Framework7#1712]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.0-beta1
* Platform and Target: all
* Live Link or JSFiddle/Codepen: none 

### What you did
Open login-screen demo as overlay

### Expected Behavior
it works well without any message in console

### Actual Behavior
it works with this message in console:
TypeError: Argument 1 ('node') to Node.appendChild must be an instance of Node

**Comment by nolimits4web** [comment]
Fixed by https://github.com/nolimits4web/Framework7/commit/643d9f3696a192eeb461ab488e3a572ebb4a7f53
