### ISSUE TITLE
swipeout-opened and swipeout-closed events not fired

### ISSUE THREAD

**Issue by mysth** [nolimits4web/Framework7#1724]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.4
* Platform and Target: Just web for now, later Cordova
* Live Link or JSFiddle/Codepen: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking one of the templates: iOS [JSFiddle](https://jsfiddle.net/s2n1p730/)/[Codepen](https://codepen.io/nolimits4web/pen/WRRWwN), Material [JSFiddle](https://jsfiddle.net/0ogxxcvt/)/[Codepen](https://codepen.io/nolimits4web/pen/pEPPPK)

### What you did
Just listening to the events `swipeout-opened` and `swipeout-closed`.

### Expected Behavior
I expect that the callbacks linked to the events were called.

### Actual Behavior
Nothing happens, the events are not triggered. I found why ... in the code there are more events : `opened` and `closed`.
Line 7711 : `swipeOutEl.trigger(action === 'open' ? 'opened' : 'closed');`
Only those events are used ... The events `swipeout-opened` and `swipeout-closed` are missing ...
The documentation only tells us about `swipeout-opened` and `swipeout-closed` events ...

**Comment by nolimits4web** [comment]
Where did you find such `swipeout-opened/closed` events? Correct events are here http://framework7.io/docs/swipeout.html#swipeout-events

**Comment by mysth** [comment]
Sorry i have put '-' instead of ':'. I edited my description accordingly.
