### ISSUE TITLE
Input Date is not filled

### ISSUE THREAD

**Issue by guilhermelirio** [nolimits4web/Framework7#1725]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v1.6.4
* Platform and Target: Chrome 60.0.3112.90 (Versão oficial) 64 bits (Firefox works!)

### What you did
When I click on the input for the recipe date (Data da Receita), it opens the datepicker to select the date. I select, but the input is not filled with the date selected.

HTML:
```
<div class="content-block-title">Data Receita</div>
                    <div class="item-content">
                      <div class="item-media"><i class="icon f7-icons">today</i></div>
                      <div class="item-inner"> 
                        <div class="item-input">
                          <input type="date" placeholder="Data da receita" id="data_receita" readonly>
                        </div>
                      </div>
                    </div>
```

JS
```
	var data_rec = myApp.calendar({
	 input: '#data_receita',
   dateFormat: 'dd/mm/yyyy',
	 monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
	 dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'] 
	}); 
```

### Expected Behavior
Fill in the selected date.

### Actual Behavior
Anything. The input is not filled.

### Obs
Console error: The specified value "11/08/2017" does not conform to the required format, "yyyy-MM-dd".

**Comment by nolimits4web** [comment]
Error means what it says: `The specified value "11/08/2017" does not conform to the required format, "yyyy-MM-dd".` Means the value format is wrong. It is limitation of "data" input. Use input type="text"
