### ISSUE TITLE
[v2] Grid Action sheet iOS Theme no rounded corner 

### ISSUE THREAD

**Issue by GuillaumeBiton** [nolimits4web/Framework7#1732]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v2.0.0-beta
* Platform and Target: IOS

### What you did
Only 1 group of button in grid action sheet

### Expected Behavior
All corner round

### Actual Behavior
only last-child css property is get and the top corner aren't round.

**Comment by GuillaumeBiton** [comment]
works more than one group

**Comment by nolimits4web** [comment]
Fixed by https://github.com/nolimits4web/Framework7/commit/7889a57ad60f9e4d7902ffc3df0d2278c6c0394b
