### ISSUE TITLE
onPageBeforeAnimation function is not called after router.refreshPage()

### ISSUE THREAD

**Issue by cronoklee** [nolimits4web/Framework7#1744]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Framework7 Version: 1.6.4

**With an simple event handler like this:**
`myApp.onPageBeforeAnimation('mypage', function(url){ alert('loading '+url+'...') })`

**I would expect that calling:**
`mainView.router.refreshPage()` 

on 'mypage' should alert : _"loading mypage..."_ but it does not. Is this by design? Is there some other event that is always triggered when a page is loading and refreshing?

**Comment by ZanderBrown** [comment]
If you where on 'mypage' and you have reloaded 'mypage' no animation has occured

**Comment by nolimits4web** [comment]
Yes, it should be obvious that `onPageBeforeAnimation` doesn't occur when there is no animation. You can use `pageInit` event in this case

**Comment by cronoklee** [comment]
Ah I should have realised the `PageBeforeAnimation` event related to page transitions. 
`pageInit` works fine. Thanks for the help!
