### ISSUE TITLE
Colors css files missing in latest npm package

### ISSUE THREAD

**Issue by wakiem** [nolimits4web/Framework7#1753]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.0-beta.1

### What you did
npm install --save framework7

import Framework7Theme from 'framework7/dist/css/framework7.ios.min.css'
import Framework7ThemeColors from 'framework7/dist/css/framework7.ios.colors.min.css'

### Expected Behavior
CSS files are added

### Actual Behavior
This dependency was not found:
* framework7/dist/css/framework7.ios.colors.min.css in ./src/main.js

**Comment by nolimits4web** [comment]
There is no more separate colors files. Colors are built in main css files

**Comment by tvvignesh** [comment]
@nolimits4web Please update the documentation here: http://framework7.io/get-started/ with the same. I had to look into the issues for the same.

**Comment by pauloguerraf** [comment]
Happened exactly the same to me. How long does it take to update documentation?
