### ISSUE TITLE
[v2] Error with js returned in html

### ISSUE THREAD

**Issue by J05HI** [nolimits4web/Framework7#1754]
My IDE (PhpStorm) gives me the following error:

![unbenannt](https://user-images.githubusercontent.com/16399787/29621198-5f91fbc2-8820-11e7-8103-794d0914ee9d.PNG)

How can I fix that?

**Comment by nolimits4web** [comment]
I believe it is because your IDE doesn’t know about F7’s component pages

**Comment by J05HI** [comment]
@nolimits4web 
What do you use or how to fix that?

**Comment by nolimits4web** [comment]
I just disable linter. You can try the following 
‘’’
function page() {
  return ...
}()
