### ISSUE TITLE
callback in autocomplete Standalone mode

### ISSUE THREAD

**Issue by rgfpy** [nolimits4web/Framework7#1758]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.3
* Platform and Target: Cordova With Android (Tested in Android 7.0)

### What you did
I use the AutoComplete Component With the code in Standalone mode:

var objSelect = $$('#aLinkAutocomplete');
var aListados = ['lista 1', 'lista 2'];
f7.autocomplete({
					openIn:'page',
					searchbarPlaceholderText:'Buscar...',
					notFoundText:'No se encontrarón coincidencias',
					opener:objSelect,
					backOnSelect:true,
					source:function(autocomplete,query,render){
						var results=[];
						if(query.length===0){
							render(results);
							return;
						}

						for(var i=0;i<5;i++){
							if(aListados[i].indexOf(query.toUpperCase())>=0)results.push(aListados[i]);
						}
						render(results);
					},
					onChange:function(autocomplete,value){
						alert(value[0]);
					}
				});

-- When i pressed the icon back arrow in Toolbar the framework call the callback PageInit method from the home page, example this cod execute in data-page="clientsLists" but the callback exec data-page="home" event

-- And the phisic back buttom not work only work the back icon in toolbar to go back

### Expected Behavior
Expected simple return to the actual data-page without callback event onPageInit

### Actual Behavior
Callback event onPageInit

**Comment by nolimits4web** [comment]
It happens because when you go to previous page your home page gots preloaded. It is intended behavior to kee two pages in dom for swipeBackPage work

**Comment by rgfpy** [comment]
Yes the autocomplete with the standalone mode I use it on a secondary page I have my Dashboard and from there I go to another page and that page I call the standalone but when it returns from the standalone it makes a call to the onPageInit () event of the main page and refreshes the whole DOM is as if it were loaded for the first time, should not do it

**Comment by nolimits4web** [comment]
Everything is correct and it is designed behavior. Don't want it then enable "domCache" and your home page will be always in dom without any reloadings
