### ISSUE TITLE
Black-text status bar in iOS home screen web app

### ISSUE THREAD

**Issue by GuillaumeBiton** [nolimits4web/Framework7#177]
Hi,

there is a little hack that allow to have black text when status bar style is set to "black-translucent". It consists in removing the meta tag when iOS standalone mode is detect ([article here](http://blog.flinto.com/how-to-get-black-status-bars.html)):

`if(window.navigator.standalone) $$("meta[name='apple-mobile-web-app-status-bar-style']")[0].remove();`

I have also need to modify a css class to prevent from a 20px black header in the left view.

`html.with-statusbar-overlay body .panel { padding-top: 0px }`

don't know if it's a bug or something wanted so I report it here.

**Comment by nolimits4web** [comment]
I think we may close it
