### ISSUE TITLE
[v2] Toast Component

### ISSUE THREAD

**Issue by nolimits4web** [nolimits4web/Framework7#1776]
- [x] Implement

**Comment by J05HI** [comment]
Please add toast with icon:
[https://github.com/framework7io/Framework7/issues/1794](https://github.com/framework7io/Framework7/issues/1794)

**Comment by numberokta** [comment]
Toast stuck after back to main page and it does't work !

**Comment by J05HI** [comment]
@numberokta
Can confirm that.
