### ISSUE TITLE
preloader-indicator-overlay

### ISSUE THREAD

**Issue by ytbryan** [nolimits4web/Framework7#1779]
* [x] feature-discussion (RFC)
* Framework7 Version: 1.6.4
* Platform and Target: iOS

---

This is a discussion regarding `.preloader-indicator-overlay` overlay which get added after myApp.showIndicator()

Currently, I am setting display to none to disable the overlay. I think the user may wish to press the back button of a page to cancel the "loading". I believe such behaviour is common on native apps where the back button is not disabled when a preloader is shown.

Two questions: 

1. Are there any disadvantages to disable the overlay? I cannot find its purpose in the documentation. 

2. Is there a way to disable the overlay via javascript? Can we have that in the future if it does not exist yet? :)

**Comment by nolimits4web** [comment]
> Are there any disadvantages to disable the overlay? I cannot find its purpose in the documentation.

Yes, if you for example doing Ajax request to load the page, then user could probably load another page in meanwhile.

> Is there a way to disable the overlay via javascript? Can we have that in the future if it does not exist yet? :)
There is no way to disable it. If you don't need you need probably use some inline/inplace preloader rather than preloader overlay
