### ISSUE TITLE
[v2] Error calling router.load with route option undefined

### ISSUE THREAD

**Issue by blikblum** [nolimits4web/Framework7#1781]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v2.beta2
* Platform and Target: web

### What you did
Call `router.load` with params.url defined and options.route undefined 

### Expected Behavior
The route option should be dynamically defined, according to line:

```
if (!options.route && url) {
    options.route = router.findMatchingRoute(url, true);
  }
```

### Actual Behavior
An exception occurs at a code executed earlier

```
if (options.route.route &&
   [...]
    return false;
  }
```

Since there are no docs, i'm not sure what to do. Should the check options.route be checked before accessing it? If so it will be needed to add check also in `forward` 

```
if (options.route.route.tab) {
```

**Comment by nolimits4web** [comment]
I fixed it but such using of `router.load` is the v1-way of navigation. In v2 navigation is route based and `router.load` is mainly for internal usage. Routes specification in v2 should be enough in 99% of cases. So show me how do you use it and it is probably could be done via `routes` app parameter.

There is no docs yet, but today or tomorrow i'll post big article on http://blog.framework7.io/ about v2 router

**Comment by blikblum** [comment]
I use `router.load` to navigate for dynamic generated pages. The simplest example is: https://codepen.io/blikblum/pen/rwqOpQ . The v2 version (not working due to #1780 ): https://codepen.io/blikblum/pen/MvdrWO

I use it with Marionette.js, it's working fine so far (preparing a medium article also about using F7). The full integration code is at: https://github.com/blikblum/marionette.f7/blob/master/src/index.js basically i use `router.loader` passing pageElement, `app.popup` , `app.closeModal` and the page events

A more complete example, with multiple views and popups, can be found at  https://github.com/blikblum/marionette.f7/tree/master/examples/tab-bar/src

**Comment by nolimits4web** [comment]
Well, this exact example can be reworked like that https://codepen.io/anon/pen/qXGGQr?editors=1010

**Comment by blikblum** [comment]
Thanks. I think this can be closed
