### ISSUE TITLE
Project Site triggers CPU Fan and eats 40% of CPU Power on an i7-2760QM

### ISSUE THREAD

**Issue by COLABORATI** [nolimits4web/Framework7#1785]
The [project website](http://framework7.io/) after triggers the starting of the cpu fan on a modern business laptop with an i7-2760QM CPU. The Chromium task manager shows CPU power goes up to 40% on that page. 

This is totally inacceptable for a mobile framework.

**Comment by nolimits4web** [comment]
Website is not related to framework performance

**Comment by COLABORATI** [comment]
haha, that was a good one! very funny and shows your professional approach :)

**Comment by nolimits4web** [comment]
Sorry but have you read the issue form when you filled the issue? If you have issue with website there is a separate repo for this. Such CPU load happens because there is a video on home page. If you don't like it, i think it will be more correct to open issue for Chromium
