### ISSUE TITLE
The keyboard hides the input box

### ISSUE THREAD

**Issue by OVampireo** [nolimits4web/Framework7#1787]
This is a (multiple allowed):
* [x] enhancement
* [x] feature-discussion (RFC)

* [ ] bug
* Framework7 Version: The last version
* Platform and Target: ANDROID 
* Live Link or JSFiddle/Codepen: http://material.framework7.cn

### What you did
I didn't do anything. Just test

### Expected Behavior
In the android environment when I'm typing input. I think it should be like ios the page will be pushed up. But it doesn't

### Actual Behavior
Enter in the input box below the page, the keyboard will block the input box. If you use an iphone, it won't do that.
I don't understand, hope the big god grant.

**Comment by J05HI** [comment]
How to fix that?

**Comment by OVampireo** [comment]
There's no good way to do it right now. It's foolish to listen on the offset.
I'm using :
    setTimeout(function(){
          el.scrollIntoViewIfNeeded();  // In mozilla. An unstandard method
    },500). // If it's too small, it will "fail."
