### ISSUE TITLE
iOS 8 Mode for Popups (iPhone) and Swipeout lists

### ISSUE THREAD

**Issue by SniperGER** [nolimits4web/Framework7#179]
In iOS 8, Popups do not cover the whole screen. Instead, there is some space with at least the height of the Navigation Bar, without the Status Bar. (Can't check exact values or behaviour, don't have iOS 8 installed currently). You can see that pretty well on this picture:
![predicts_screen_mail](https://cloud.githubusercontent.com/assets/6178765/3933643/1fae429a-2482-11e4-86d5-d8bab2da518b.jpg)

In Swipeout Lists, the buttons are not static, but slide in as you move your finger to the left (or to the right):
![ios-8-mail-swipe](https://cloud.githubusercontent.com/assets/6178765/3933669/5b9d291a-2482-11e4-9763-85ab690b69dd.png)

Is it possible to have these features in the next release? Popups shouldn't be that hard, I'm trying that out myself in a while.

**Comment by MarcGodard** [comment]
Can I make a small request!

When the swipeout options are open, clicking on the item should close the options, not go into the link (when its a link item)

**Comment by nolimits4web** [comment]
@MarcGodard not sure what do you mean. Can you explain it more detailed?

**Comment by MarcGodard** [comment]
When the swipe out is opened (you can see the options) clicking on the item should close the options.

Not sure how I can give an example.

**Comment by nolimits4web** [comment]
I think we may close it
