### ISSUE TITLE
[v2] Set the route url for a page

### ISSUE THREAD

**Issue by J05HI** [nolimits4web/Framework7#1793]
@nolimits4web 

How can I set the url route for a page?
The path in the "routes.js" defines that? But how to enable it (like "pushState" param in v1)?
Thanks!

**Comment by nolimits4web** [comment]
What do you mean? How to enable pushState?

**Comment by J05HI** [comment]
@nolimits4web
Yeah :)

**Comment by nolimits4web** [comment]
Check this article https://blog.framework7.io/mastering-v2-router-958ea2dbd24f
And this comment https://medium.com/@alfahelper/great-re-work-f8d2bf3bd823?source=linkShare-2febe1e79b23-1505311403

**Comment by J05HI** [comment]
@nolimits4web
Wow amazing you have a blog. Didn't know that

**Comment by J05HI** [comment]
@nolimits4web 

I have a problem:

Setting it globally is working:
<img width="272" alt="1" src="https://user-images.githubusercontent.com/16399787/30389849-5f399e9c-98b4-11e7-95c8-d5b2638d5308.PNG">

But setting it at the route itself doesn't work:
<img width="228" alt="2" src="https://user-images.githubusercontent.com/16399787/30389853-62b2db56-98b4-11e7-976d-6826e937e0f4.PNG">

**Comment by J05HI** [comment]
@nolimits4web
Could you please help me with that :)
