### ISSUE TITLE
Black gap appears when no statusbar is used on IOS with PhoneGap

### ISSUE THREAD

**Issue by gpetrov** [nolimits4web/Framework7#247]
When building a fullscreen app with PhoneGap without statusbar, Framework7 still reserves the space.

I tried to remove the placeholder div.statusbar-overlay but the class with-statusbar-overlay always gets added resulting in a black gap.

The check for statusbar is wrong at https://github.com/nolimits4web/Framework7/blob/a2dcc853e5a3b722315f61051a1e50dd8ec38b03/src/js/proto-device.js#L61

because the device width & height are always equal with Phonegap and IOS.

Maybe you should add check for having the .statusbar-overlay?

**Comment by johnjamesjacoby** [comment]
Looks like this can be closed.
