### ISSUE TITLE
ptr has no animation when the page is scrollable

### ISSUE THREAD

**Issue by lihongxun945** [nolimits4web/Framework7#270]
I have find this code in ptr:
if (container[0].scrollHeight === container[0].offsetHeight || app.device.os !== 'ios') {
useTranslate = true;
}

if the page content is too long , then the container[0].scrollHeight !== container[0].offsetHeight, so there is no translate when I touch and pull down on the page.

**Comment by nolimits4web** [comment]
Closing as seems to not actual
