### ISSUE TITLE
build folder index.html vs. min js and css

### ISSUE THREAD

**Issue by scottlawton** [nolimits4web/Framework7#302]
After 'grunt build' the build/index.html file references the min files, but the build/ folder only contains the regular files.

line 10:     link rel="stylesheet" href="css/framework7.min.css"
line 98:     script type="text/javascript" src="js/framework7.min.js" ...

Perhaps templates/index.jade should contain a variable? I would guess there's a standard solution but I've never used grunt so not sure what to try. (Of course it's trivial to fix by hand after the build, but still worth fixing the code at some point.)

**Comment by mashinista** [comment]
Same thing happens after "gulp build" as well and minified versions are not generated inside /build. Copying framework7.min.js and framework7.min.css to your /build/js and build/css folders from /dist folders fixes the /build for development, but not sure about the index.jade fix either.

**Comment by nolimits4web** [comment]
minified versions shouldn't be in build/ as it is for developing of F7 itself. I'll try to configure it so it points to full versions in build/
