### ISSUE TITLE
ajax complete not called after error is called

### ISSUE THREAD

**Issue by boynet** [nolimits4web/Framework7#306]
checking jquery spec: http://api.jquery.com/jquery.ajax/
"A function to be called when the request finishes (after success and error callbacks are executed)."

**Comment by intricareruchika** [comment]
ajax not call everytime..my code is:

function clickon()
{

	//$('#loader').show();
	$.ajax({
      type: "POST",
      url:"<?php echo Yii::$app->urlManager->createUrl(["activated-device/locationview"]) ?>",
	  data:$(this).serialize,
      success: function(data){
		 /*   */
		 //var activated_devices_location = <?php echo count($activated_data) ?>;

           $('#myModal1').modal('show');
		   
	setTimeout(function(){ window.location.href = "<?php echo Yii::$app->urlManager->createUrl(["activated-device/locationview"]) ?>"; }, 10000);
          },
      
    });
	
	
}
