### ISSUE TITLE
caniuse: classList

### ISSUE THREAD

**Issue by czb** [nolimits4web/Framework7#308]
See:
http://caniuse.com/#feat=classlist

Known issues: WebKit browsers (Safari, Android browser, but NOT Chrome) and IE do not have support for classList on SVG elements.

I have a svg image which I drag using D3. While I try to drag it in IE11 I get an error in Framework7 because it tries to do classList stuff with the svg element.

Is that intended behavior?

**Comment by ZanderBrown** [comment]
Im assuming 2 years later this issue is resolved. Move to close?
