### ISSUE TITLE
Slow stuff on old devices

### ISSUE THREAD

**Issue by dieulot** [nolimits4web/Framework7#31]
As discussed in #29, here is my tour of what I found slow in the Kitchen Sink. It’s running on an iPhone 3GS, in an “app” pinned to the homescreen, so no Nitro JS engine, really putting Framework7 to stress.

Again, I haven’t looked into the source code. A recurring theme is that elements that need to track touch are the slowest to respond. Those perform better in Safari.

Sorted by descending slugishness, more or less:

## Swipe back

Those are really slow when they’re under your fingers: https://www.youtube.com/watch?v=bb15tIcZ_rY

Once released, the animation is okay though: https://www.youtube.com/watch?v=sNUHA_h3YYM

## Slider

Really slow, and the fact that this element is pretty easily missed by your finger doesn’t help: https://www.youtube.com/watch?v=4N-umyLUQxo

## Swipe to delete

Pretty slow: https://www.youtube.com/watch?v=6_3reKI-Dkc

It looks like it’s a bit less slow when they’re tiny, might just be an illusion though: https://www.youtube.com/watch?v=WKD7snR0vVA

## Pull to refresh

For some reasons, the first one or two pulls are pretty laggy, after that they’re acceptable: https://www.youtube.com/watch?v=JHG7SJEGFiU

## Form inputs

I guess you’re aware of this one: https://www.youtube.com/watch?v=qbsCjiilC9g

The known solution is https://github.com/ftlabs/fastclick; but it’s probably not worth it to merge FastClick into Framework7.

## Switch

The switch feels a bit slow to respond without the nice iOS 7 effects : https://www.youtube.com/watch?v=Nxdz4R71byE

I think setting the border to green (or grey if it’s already checked) on touchstart might do the trick.

## Scroll

Scroll is a bit less responsive than normally, for some reason this is the thing from this list that bothers me the less: https://www.youtube.com/watch?v=WS06O3JoNGo

Regular scrolling in Safari on a simple website, for comparison: https://www.youtube.com/watch?v=M9W3howFo2Q

**Comment by nolimits4web** [comment]
I think we may close it for now
