### ISSUE TITLE
Popup and Popover behind overlay

### ISSUE THREAD

**Issue by tekkenking** [nolimits4web/Framework7#311]
I dont know why Popover and Popup falling behind overlay. Here is the picture..
![issue](https://cloud.githubusercontent.com/assets/1980114/5136612/a0209414-712b-11e4-9128-6a74413dd30b.png)

Please i need urgent help to resolve this..
Thanks

**Comment by hotgeart** [comment]
I confirm, I had the same problem. (You can close)

**Comment by venkatesh-surya** [comment]
Hai friend i have solution for popup overlay.

.popup-overlay{z-index: 111 !important;}
