### ISSUE TITLE
Scroll with 100% sticky header and footer.

### ISSUE THREAD

**Issue by nodkrot** [nolimits4web/Framework7#319]
While scrolling, the header sticks but when I scroll all the way to the top, then stop until the content stops moving, and then scroll up the header goes down with the content. Same with bottom. I tested this on iphone 5s and 6 with kitchensink.

There is a neat CSS solution with -webkit-overflow-scrolling:touch;  (I see you are using it, but I think you need to do a little more work). Here is what I found: http://code.tutsplus.com/tutorials/ios-5-fixed-positioning-and-content-scrolling--mobile-8332

Currently I implemented iScroll 5 and seems to be working good, but CSS is solution over JS is always better.

**Comment by iVanPan** [comment]
I disable disallowOverscoll in cordova，but it doesn't work

**Comment by MarcGodard** [comment]
```javascript
<preference name="DisallowOverscroll" value="true"/>
```
plus a keyboard plugin (such as ionic), plus 
```javascript
cordova.plugins.Keyboard.disableScroll(true);
```

**Comment by nolimits4web** [comment]
I think we can close it
