### ISSUE TITLE
Form switch doesn't work on Android

### ISSUE THREAD

**Issue by edwinvdpol** [nolimits4web/Framework7#335]
The switch does not work on Android.
It works fine in the browser and iOS.

**Comment by nolimits4web** [comment]
Do you mean this switch?
![switch](https://cloud.githubusercontent.com/assets/999588/5592065/ff0bba56-91c1-11e4-85de-e8c5f564d7fe.png)

Works fine for me on Android 4.0+

The only problem could be with Checkboxes and Radios, but this related to Android's bad support of SVG background images

**Comment by doxiaodong** [comment]
I use PNG to replace.
