### ISSUE TITLE
Callback FromJSON

### ISSUE THREAD

**Issue by edwinvdpol** [nolimits4web/Framework7#336]
I'm using the FromJSON function to restore form data from JSON.
My app has custom radio buttons (ala Bootstrap).
The original radio button is hidden, and the 'button-like' style is displayed.

Is there a possibility to set the 'active' class on each of the parent label of the radiobutton when using FromJSON?

**Comment by nolimits4web** [comment]
You are right, there is no such callback/event. Will add it
