### ISSUE TITLE
Confirmation button in smart-selects

### ISSUE THREAD

**Issue by VoroninAndr** [nolimits4web/Framework7#337]
Hello, is it possible to add a confirmation button (something like "OK") in the bottom of smart-select options list? I think it will be more convenient than use "Back" button on top panel.

**Comment by nolimits4web** [comment]
No, there is no such opportunity by default, but you can add it manually using page callback, for example:
```
$$(document).on('pageInit', '.page[data-page*="smart-select-"]', function (e){
  var pageContainer = $$(e.detail.page.container);
  pageContainer.find('.page-content').append('<a href="#" class="button back">Ok</a>');
})

**Comment by nolimits4web** [comment]
Closing as no further discussion
