### ISSUE TITLE
pageAfterBack not firing on iOS

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#338]
pageAfterBack doesn't seem to be triggered on ios 8.1 on an iPhone6 plus.

Will investigate... but if anyone has an idea if this is intentional, please let me know.

**Comment by nolimits4web** [comment]
Everything is fine for me, it is actually shouldn't be related to os and device

**Comment by MarcGodard** [comment]
I understand that. It fires fine in the browser, just not with cordova on ios.

**Comment by MarcGodard** [comment]
My bad... I had a race condition and my code wouldn't run cause the page wasn't reloaded yet. My apologies.
