### ISSUE TITLE
Inline Page URL Plus Query?

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#339]
Is there a way to pass a query with the inline page urls?
```html
<a href="#profile?id=345634">Go to a Profile page</a>
```
I haven't tried the following, but if you know it will work (or something similar), please let me know.
```javascript
mainView.router.load({pageName: 'about', query:{id: 342523}});
```
If neither of these work, I guess this would be a feature request?

**Comment by nolimits4web** [comment]
Right, none of these are possible, will add it

**Comment by nolimits4web** [comment]
Now it is possible with both ways
