### ISSUE TITLE
indicator doesn't shows up

### ISSUE THREAD

**Issue by lok0613** [nolimits4web/Framework7#340]
var myApp = new Framework7({
    // Hide and show indicator during ajax requests
    onAjaxStart: function (xhr) {
        myApp.showIndicator();
    },
    onAjaxComplete: function (xhr) {
        myApp.hideIndicator();
    }
}); 

The indicator stills not shows up while post request but works on get request.

$$('.confirm').on('click', function (e) {
        e.preventDefault();
            // post request here
            myApp.alert("complete！");
            mainView.back();
        
    });

**Comment by nolimits4web** [comment]
These two callbacks onAjaxStart/End are only for internal XHR requests, you may just use this, like in kitchen sink:
```
$$(document).on('ajaxStart', function () {
    myApp.showIndicator();
});
$$(document).on('ajaxComplete', function () {
    myApp.hideIndicator();
});

**Comment by lok0613** [comment]
I tried it, just not working.....

**Comment by nolimits4web** [comment]
Look for problem on your side or provide a link so i can take a look. It works for everyone

**Comment by lok0613** [comment]
Sorry I cant, my code runs on android. In webview it looks fine!

**Comment by nolimits4web** [comment]
Then i can't say much. Try to look for problem, as it does work in kitchen sink and for everyone else

**Comment by nolimits4web** [comment]
Closing for now, if you still have it issue, provide a link or more code examples
