### ISSUE TITLE
Lazy loader

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#341]
Hi @nolimits4web 

I created a lazy loader in the framework on my testing branch. There are many other things that I am playing with in that branch so I am not doing a pull request just yet. Just thought I would let you know if you wanted to check it out.

Just so you are aware, all the work I am doing is for use as cordova framework, so it relies on the webkit web UI available JS version and is not backwards compatible.

The lazy loading is important for mobile apps, so I thought you might want to consider adding it. If you do a diff, you will see many other small changes here and there (I also just pulled from your master branch).

I am planing on working a lot on this framework and expanding on it, if you would like to discuss some of my ideas, let me know.

If you want to work together that would be great, if not, I will just start my own project based on yours and give you the credit where due.

Let me know,

Marc

**Comment by nolimits4web** [comment]
Hi there,
Lazy loading and other improvements sounds great. But what do you think about releasing it as plugin. Because lazy loading could be not only in pages but also in modals, popovers, popups, panels. So i think it would be easier and better to do it as plugin file, where we can keep all related code in one place, instead of adding related parts through the whole lib. The same i think to do with your Ionic Keyboard implementation.

So what do you think? And we can work together on it

**Comment by MarcGodard** [comment]
I was thinking about that, but to me it made more sense for it to be part of the framework. You don't typically need many images if any in modals, popovers, popups and panels. If you do need them there, there is no point in lazy loading them as there typically isn't a scroll or much of one.

I have also started implementing Material Design look for android and created a bunch of plugins to easily add cordova plugins.

I have also been looking into adding node CLI stuff like ionic has. I think you have a much better base and start than ionic did and would like to see this framework go that far.

If your long term plans do not line up, maybe we can split off and still contribute to each others projects.

My long term goals are the following:

- Easy CLI for cordova and cordova plugins (like Ionic has)
- Automatically looks like Android (Material Design) when building for android.
- Very simple MVC base that people can start with or not. Some start projects (again like Ionic)
- Easy plugins and framework support (like ngCordova) to add keyboard, camera, geolocation, localization, or other things really easily.

I also want to come up with a new name for such a project, as googling the word 'framework' brings about many other things and it really had to develop a community without good google help.

**Comment by nolimits4web** [comment]
It is ok about lazy loading. I'll start to integrate it into F7 based on your implementation, it requires for  some tweaks.
I also have in plans to do Android-look plugin. But that is right after 1.0 release of F7, there is still a lot of work here.

About MVC base, i was thinking about it and had some tries, but then i came to conclusion that there is no much sense to "reinvent wheel" and it is better to do few plugins that make it compatible with well known MVC libs like Angular, Backbone, Ember, etc.

**Comment by nolimits4web** [comment]
Ok, just added and pushed Lazy loader with appropriate demo in kitchen sink. You can check the code, i've made some improvements:
* Function `isElementInViewport` didn't consider the case when image could be larger than viewport
* Added `threshold` option
* Added option to load images sequential to prevent unnecessary loading of images during fast scroll
* Added fade-in animation by adding "lazy-fadeIn" class to image/block with bg
* Added placeholder image option so image may have size until it loaded

**Comment by MarcGodard** [comment]
Awesome. Nice work. I took a look at it.
