### ISSUE TITLE
slider onSlideChangeEnd not fired on fast sliding

### ISSUE THREAD

**Issue by boynet** [nolimits4web/Framework7#344]

**Comment by nolimits4web** [comment]
You may just compare activeSlideIndex and previousSlideIndex properties to know the direction ;)

**Comment by boynet** [comment]
you didnt understand me :)
the direction less concern me, the solution to the bug I reported is that the slider is missing basic event to know when slideChanged. we dont have any way right now as - onSlideChangeEnd not called on fast sliding and onSlideChangeStart make the slide laggy.
so the solution is to have simple events just like swiper that dont belongs to transition or touch or anything.
 that fire when activeSlideIndex is changing no matter how if by touch or by button

**Comment by nolimits4web** [comment]
i got you right :) onSlideNext/Prev in Swiper are just particular case of onSlideChangeStart with the index check inside, like in my previous answer :)

**Comment by boynet** [comment]
oh now i get you

**Comment by nolimits4web** [comment]
I think we can close it, right?)
