### ISSUE TITLE
External Links With Cordova

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#345]
Hi I was trying to do an external link for cordova wiht the inAppBrowser plugin. Which if you add target="_system" should open in a new browser window.

F7 seems to capture this and not allow the link to work.

I made some changes, not worth a pull request.

```JavaScript      
        var external = clicked.attr('target') === '_system';
        if (external) {
            window.open(url, '_system', 'location=yes');
            e.preventDefault();
            return;
        }
```
on line 11 of clicks.js

You can also connect it with the external parameter if you want, but you can use these differently as just adding the external class will not work for cordova.

**Comment by nolimits4web** [comment]
What if you just add it to `externalLinks` app parameter:
```js
var f7 = new Framework7({
  externalLinks: '.external, a[target="_system"]'
});

**Comment by MarcGodard** [comment]
didn't work. It would open it in the app itself as if _system was not the target. Didn't investigate why, cause my solution worked.

**Comment by MarcGodard** [comment]
So I tried a million things to get this to work without impacting Framework7 code. Its not possible.

I have gotten it to open in an external browser, but then it also opens in the app. These changes shouldn't impact anything new.

#366
