### ISSUE TITLE
Disable Panels

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#346]
Has anyone done anything to disable the panels. As in before you login there are no menus, then once you login there it is?

**Comment by MarcGodard** [comment]
I found that I can do this:
```JavaScript
f7.allowPanelOpen = false;
```
Is there a reason this isn't documented? Are there problems with it? Is it incomplete. Seems to work and can be switched on and off.

**Comment by nolimits4web** [comment]
It is mostly for internal usage, but yes, you it is safe for use. But if you need to disable swipe panels, you may use `f7.params.swipePanel = false` to disable it

**Comment by MarcGodard** [comment]
Thanks,

Also the allowPanelOpen = false disables swipe to open too.
