### ISSUE TITLE
From a cached page to a non cached page

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#347]
My app uses cached pages and non-cached depending on the need.

This seems to work amazingly until you go from a cached page to a non cached page.

For some reason the cached class goes onto the non-cashed page and the page loads as if it was cached.

This seemed to be working before, so I am not sure what changed. I did pull the recent changes to master recently, but it might also be something I did. Will investigate.

**Comment by MarcGodard** [comment]
So If I go, cached page to non-cached then hit the back button, then go back to the same non-cached page, it acts as it was cached (because its still loaded for the back button). Then it breaks all my non-cached pages.

**Comment by MarcGodard** [comment]
Doing the reInit seems to work.

**Comment by nolimits4web** [comment]
If you mean then if you go deeper and deeper, then yes, Ajax pages are become cached while they are in history. What do you mean by "reInit"?

**Comment by MarcGodard** [comment]
I spoke too soon.

When I go from one page call it "profile" that initializes with id=1, then from that page I go to another profile with id=5, the pageBeforeInit and pageReinit doesn't fire.

With the profile page as non-cached.

**Comment by MarcGodard** [comment]
Actually pageBeforeInit does fire... something else is broken... :(

**Comment by MarcGodard** [comment]
![screen shot 2015-01-08 at 3 22 06 pm](https://cloud.githubusercontent.com/assets/5016637/5669973/26339490-974a-11e4-88db-9c08667a5747.png)

This is what happens, and now my init function doens't know which profile page to populate.

**Comment by MarcGodard** [comment]
I decided to use page.container and page.navbarInnerContainer instead of my own IDs. Works great... now I just need to apply it everywhere.

**Comment by MarcGodard** [comment]
Hahaha, sorry for continuing this issue and reopening it.

So everything works great except for the message stuff.

When there are 2 or more pages with the messages part of the framework, the myApp.addMessage(parameters) stuff doesn't know where to put the new message.

Can we pass it another parameter with the page.container?

I can do this and make it a pull request if you want, but you might be able to do it faster.

**Comment by nolimits4web** [comment]
Sure, already added in local version. But currently can't merge it until i complete another big feature. But the fix is simple:
![1](https://cloud.githubusercontent.com/assets/999588/5691603/3e457c86-98e1-11e4-819b-c1e86de2e132.png)

**Comment by MarcGodard** [comment]
Awesome, thanks!

**Comment by MarcGodard** [comment]
```JavaScript
    messagesContent = messagesContent || $('.messages-content');
```

Doesn't that make better sense?

So you can do this...

```JavaScript
    myApp.f7.addMessage({
      text: message.text,
      type: message.type,
      name: message.name,
      day: day
    }, $(page.container).find('.messages-content'));
```

**Comment by nolimits4web** [comment]
`$(messageContent || '.messages-content')` 
is almost the same as 
`messagesContent || $('.messages-content')` 

but also cover cases when passed messageContent is string CSS selector or HTML element.

By the way $($($($('.messages-content')))) is the same as just $('.messages-content'), so it is safe to wrap Dom7 result with Dom7 again ;)

**Comment by MarcGodard** [comment]
Ahh, thats great, thanks.
