### ISSUE TITLE
Can my-app.js encode by utf-8 ?

### ISSUE THREAD

**Issue by wupojung** [nolimits4web/Framework7#349]
Thanks for your contribution !!
I’m loving it so much ! :+1: 

Here is my suggest .
Is that can be encoded by utf-8 for all file  in the dist folder ? 
Yes, I can do it myself . 
But not friendly for other user , especially, the Chinese users or Japanese users. Is not good for popularize I think .

Thanks again !

---
Sorry for my English~  :smile:

**Comment by nolimits4web** [comment]
Don't sure that i understand what you mean, but all files are already in UTF-8 encoding

**Comment by nolimits4web** [comment]
Closing as no further discussion
