### ISSUE TITLE
Framework7 + AngularJS

### ISSUE THREAD

**Issue by nodkrot** [nolimits4web/Framework7#35]
This is a well done framework (in the very early stages). However, I decided to use framework7 for one of my projects and I wanted to integrate it with angularJS. The difficulty I faced is combining page transitioning/changing from both frameworks. Angular uses ng-view and Framework7 similarly (with partial html) changes pages except for top navbar and bottom navbar. 

Help/Advice on how to control the navigation of pages in Framework7 with AngularJS routes, templates would be very useful.
Thank you.

**Comment by kevincobain2000** [comment]
Hi, 
Does the 1.0.0 release enable us to use f7 with angularjs ?https://github.com/nolimits4web/Framework7/commit/e4f701176d24c5896f8b290ce71a7bae2db38a54

**Comment by nolimits4web** [comment]
@kevincobain2000 i am not strong in Angular, but i see that many already use F7 with Angular, so yes, you can use it with Angular

**Comment by kevincobain2000** [comment]
@nolimits4web Sweet I will give it a go. 
If you come across some tutorial or even template project using F7 and angular, could you please post the links over here.

**Comment by CaledoniaProject** [comment]
I had the same doubt, but then I found the following solutions!

Use template7
http://www.idangero.us/template7/

Really, nobody ever found this demo?
https://github.com/valnub/Framework7-with-AngularJS-demo-app

**Comment by pruimmartin** [comment]
Hi guys! I'm using F7 for a while and now want to integrate angular just for data binding etc. 
In the index.html page everything is working very good. However if i open another html page (in the same view) just by clicking an anchor tag. All Angular Magic stops working.

Has anybody else had this issue? Thanks!

**Comment by CaledoniaProject** [comment]
@pruimmartin Try template7 with pageInit callbacks

**Comment by nolimits4web** [comment]
It is time to close this issue as there are many examples of how to use both

**Comment by ashvin777** [comment]
Try this.. https://github.com/ashvin777/framework7.angular it is under development but can we used for framework7 and angularjs combination. Cheers !!

**Comment by Russian60** [comment]
I'm currently **also** integrating F7 with AngularJS. I create a custom F7 Router for angular very similar to ngRoute like this:

```
$Router()
  .when('#/', {
    name: 'Showcase',
    controller: 'ShowcaseController',
    controllerAs: 'vm',
    templateUrl: 'showcase.view.html'
  })
  .when('#/product', {
    name: 'Product',
    controller: 'ProductController',
    controllerAs: 'vm',
    templateUrl: 'product.view.html'
  })
  .when('#/register', {
    name: 'Register',
    controller: 'RegisterController',
    controllerAs: 'vm',
    templateUrl: 'register.view.html'
  })
```

And it works! 
I will give more news soon ;D

**Comment by ashvin777** [comment]
Hello Guys,

Try the working demo(Kitchen-sink-app) of Framework7 along with AngularJS at below URL
http://ashvin777.github.io/framework7.angular/kitchen-sink-material/#!/home.html

Github Repo
https://github.com/ashvin777/framework7.angular

**Comment by rajukiran** [comment]
Hi,

I configured environment service for F7 along with AngularJS project, At last, I need to inject the envService as a module to the project. Can anyone help me on how to inject the module in F7

I tried like this,
 MyApp.config.$inject=['envService'];
MyApp.angular.module('MyApp').factory('UrlConfig',config);

Thanks & Regards,
