### ISSUE TITLE
change search bar search-in value

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#351]
Hi I added a check for a different search-in option

line 89 of searchbar.js I simply added
```Javascript
            searchIn = searchbar.attr('data-search-in');
```
This way I can change the data-search-in attribute on the fly

Works well.

I really wish the search worked more like native does (under the scroll with a snap, and when you focus the navbar disappears).

I might work on it if you are not planing on it.

**Comment by MarcGodard** [comment]
#354

**Comment by nolimits4web** [comment]
Merged, about hidden navbar when searchbar is enabled, i thought about it, but it is prertty complicated to consider all cases with all available navbar layouts (Fixed, Through and Static)

**Comment by MarcGodard** [comment]
Yes I noticed that too. Maybe in a future release!
