### ISSUE TITLE
Uncaught TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#352]
```JavaScript
    var mainView = f7.addView('.view-main', {
        dynamicNavbar: false,
        domCache: true
    });
```
I get the following error:
Uncaught TypeError: Cannot read property 'find' of undefined

With line 539 of router.js:
```JavaScript
newNavbarInner.find('.sliding, .sliding .back .icon').transform('');
```

When I switch dynamicNavbar to true it works fine.

**Comment by nolimits4web** [comment]
How can i replicate this issue? Can't see any errors with the same setup in kitchen sink

**Comment by MarcGodard** [comment]
Maybe its a combination with something else i am doing. I am going to close this for now.
