### ISSUE TITLE
Something slowing clicks?

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#359]
I am having an issue where I need to unfocus and refocus an input element (its a keyboard cursor fix on iOS after a JavaScript scroll while input is focused).

The trick is after the scroll is done, you unfocus and refocus the input immediately.

This has worked on many other platforms and in other places that I have done this. But for some reason this is slow using this framework, which makes the keyboard jump down a bit before the refocus.

```JavaScript
$(activeInput).blur();
$(activeInput).focus();
```

Is there something in the framework code (like other events on the inputs or a delay) that would prevent the following lines of code to have a delay between them?

**Comment by nolimits4web** [comment]
I think the only thing could be is the call of .blur in fast click when you click out active element (https://github.com/nolimits4web/Framework7/blob/master/src/js/fast-clicks.js#L244) 

Try to disable fastClicks to check is the problem still there?

Also try to use it without dom lib with just, if activeInput is HTMLElement:
```
activeInput.blur();
activeInput.focus();

**Comment by MarcGodard** [comment]
Already tried without the DOM.

Also tried where I add an event (on blur trigger refocus) to see if it would run faster, and no.

When I removed fastclick, it didn't fix it, but it caused other issues, like I couldn't unfocus by clicking off the input.

For the messages, when someone clicks on the send button, I have it refocusing on the textarea and the keyboard doesn't bounce.

I will keep investigating and will keep this thread updated. Strange that if work on click for the messagebar.

**Comment by nolimits4web** [comment]
> For the messages, when someone clicks on the send button, I have it refocusing on the textarea and the keyboard doesn't bounce.

You may just prevent blur when you click on messagebar send button:
```
$('.messagebar .link').on('click', function (e){
  e.preventDefault();
  e.stopPropagation();
  //do your send message logic here....
});

**Comment by MarcGodard** [comment]
Thanks about the message bar.

The other issue (the cursor position fix) could also be fixed like this:
```javascript
$(aE).val('.');
$(aE).val('');
```

It works great, thanks again for your help.
