### ISSUE TITLE
tabs as a sub header? Feature Request!

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#360]
I was wondering if you can easily add tabs as a sub header. I have seen this on my iPhone and I like it. I can't seem to find it right now to take a screen shot.

**Comment by nolimits4web** [comment]
Need to see screenshot or mockup of what do you mean :)

**Comment by MarcGodard** [comment]
![img_0247](https://cloud.githubusercontent.com/assets/5016637/5838380/1a9846e8-a155-11e4-9d4a-c35e08305172.PNG)

**Comment by petarov** [comment]
Awesome! I was also quite interested in this having made a workaround before. Will test it asap.

**Comment by MarcGodard** [comment]
Awesome... Very fast too.

However, not working with themes!

![screen shot 2015-01-21 at 2 07 14 pm](https://cloud.githubusercontent.com/assets/5016637/5842938/e5b50b2e-a176-11e4-8070-7dd7c5696823.png)
