### ISSUE TITLE
Inline Date time picker alignment

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#364]
The alignment of the ":" seems off. Its too close to the last number (the minutes)

![screen shot 2015-01-21 at 2 14 19 pm](https://cloud.githubusercontent.com/assets/5016637/5843068/dfd1a554-a177-11e4-8156-41158650c028.png)

**Comment by nolimits4web** [comment]
Where do you see this?

**Comment by nolimits4web** [comment]
I guess it is Chrome with emulation of iPhone? :) It displays it wrong, look on real iPhone or in Chrome without iPhone emulation

**Comment by MarcGodard** [comment]
Yes it was chrome Iphone emulator. I will check more soon.

**Comment by nolimits4web** [comment]
I think we can close it for now
