### ISSUE TITLE
Cannot set initial url for main-view

### ISSUE THREAD

**Issue by PiJoules** [nolimits4web/Framework7#365]
For the app I'm making, when the user first enters the app, the default home page is loaded (let's call it `index.html`). After the user signs in, they are routed to another page of the app (let's call this `feed.html`).

When the user leaves the app and decides to come back later, but is still logged into the app, I want the user to automatically see `feed.html` when the app loads, rather than `index.html`. I use `localStorage` to keep track of whether or not the user is logged in. My problem is trying to get `feed.html` to load instead of `index.html`. I have tried passing a `url` parameter when adding the main view to the app, though it does not seem to redirect the page.

Is there any way I can do this? I have tried changing the default url dynamically and in the html as indicated [here](http://www.idangero.us/framework7/docs/views.html#default-view-url), but `index.html` keeps loading instead of `feed.html`.

This is the code I was using:
```js
var mainView;
if (localStorage.getItem("isLoggedIn") !== null){
    // If already logged in
    mainView = myApp.addView(".view-main", {
        url: "feed.html"
    });
}
else {
    mainView = myApp.addView(".view-main", {});
}
```

Before this, I would forward the user to `feed.html` after `index.html` loads using the router:
```js
mainView.router.load({
    url: "feed.html"
});
```
but I would rather have the user land on `feed.html` instead of `index.html` if possible, since UX-wise, it would seem odd if the user is logged in, yet has to see the original screen where they originally logged in.

Thanks in advance.

**Comment by nolimits4web** [comment]
I guess this problem was solved on forum, so we can close it

**Comment by zanurano** [comment]
mainView.router.load({
    url: "feed.html",
 reload: true
});
