### ISSUE TITLE
page.context is undefined when in onPageBack callback

### ISSUE THREAD

**Issue by petarov** [nolimits4web/Framework7#369]
Not sure if I'm doing this right but when I have an onPageBack callback I was expecting the context property to persist as when in the onPageInit callback.

An example:

```javascript
myApp.onPageInit('page-1', function (page) {
		console.log(page.context);  // Object exists
});
```

```javascript
myApp.onPageBack('page-1', function (page) {
		console.log(page.context);  // undefined
});
```

**Comment by nolimits4web** [comment]
Did you try with latest dev version?

**Comment by petarov** [comment]
No, but I did today and it works. I have previously tried used v0.10.
Thank you!
