### ISSUE TITLE
height() and width() include padding

### ISSUE THREAD

**Issue by sbryfcz** [nolimits4web/Framework7#370]
Is there some reason that height() and width() include padding? I'm just curious since jQuery's method do not and it tripped me up a little bit.

**Comment by nolimits4web** [comment]
Yes, it returns calculated CSS width, and it includes padding and border if you use `box-sizing` border-box. Otherwise you may need to use `content-box` or divide paddings

**Comment by nolimits4web** [comment]
I think we can close it for now
