### ISSUE TITLE
framework7.min.css is not minified

### ISSUE THREAD

**Issue by petarov** [nolimits4web/Framework7#371]
`framework7.min.css` is not minified neither in the `custom` task nor in the `dist` task.

`framework7.min.js` is ok.

EDIT: I mean when building using Grunt

**Comment by nolimits4web** [comment]
What do you see here?)
https://github.com/nolimits4web/Framework7/blob/master/dist/css/framework7.min.css

**Comment by petarov** [comment]
It's fine the repo, I'm just building it on my side, so it could be an issue on my system. Will double check, although I'm doing exactly the steps as in the README.

**Comment by petarov** [comment]
Works fine, if I downgrade the grunt-contrib-less version to `^0.12.0`. Both `grunt dist`and `grunt custom` targets now produce minified `framework7.custom.min.css` files. 

I think to simulate this issue you need to delete `node_modules/grunt-contrib-less` and run `npm update`again or simply build a fresh clone of the project.
