### ISSUE TITLE
Slider loop -> duplicate slide = total mess

### ISSUE THREAD

**Issue by czb** [nolimits4web/Framework7#372]
Slider loop does not play nicely with e.g. forms, knockout data-bind etc. As soon as you start duplicating slides you start to create difficult to find errors ;). I would rather have an other form of animation for the loop that does not require duplicating the slides. Is that possible? As it is now the loop feature is unusable and very risky. I spent one day finding out why knockout data-binding behaves completely randomly...

**Comment by nolimits4web** [comment]
There is no way to create correct loop without creating duplicated slides, that is the idea of loop. But you just need to consider those duplicated slides, they have additional class and data-slide-index attribute which represents index of "real" slide.

Swiper works in the same way, and a lot of devs using it with all possibles MVC frameworks :)

**Comment by nolimits4web** [comment]
I think we can close it for now
