### ISSUE TITLE
Status bar should be hidden for iPhone 6+ In landscape view

### ISSUE THREAD

**Issue by johnjamesjacoby** [nolimits4web/Framework7#381]
![image](https://cloud.githubusercontent.com/assets/88951/6014135/614b8a22-ab24-11e4-8bc8-4c92af9d1876.jpg)

Attached screenshot shows how in iOS 8 on the iPhone 6+, the status bar is made completely hidden. I could not find documentation to force it, either. It appears quite common, as even native apps hide the status bar. I'm attaching the weather app below as an example:
![image](https://cloud.githubusercontent.com/assets/88951/6014176/f4b41b12-ab24-11e4-85c2-3e0e84c0cc06.jpg)

**Comment by nolimits4web** [comment]
As it not always required, you may use this simple workaround:
```JS
if (iPhone6Plus) {
  $(window).on('orientationchange', function (){
    if (window.orientation === 90 || window.orientation === -90) {
      $('html').removeClass('with-statusbar-overlay');
    }
    else {
      $('html').addClass('with-statusbar-overlay');
    }
  })
}
```
You may use cordova device plugin or check the screen size to make sure that it is iPhone 6 Plus

**Comment by johnjamesjacoby** [comment]
Thanks @nolimits4web. Ended up doing something like:

```

function my_app_statusbar_toggle() {
	if ( My_App.device.statusBar ) {
		if ( window.orientation === 90 || window.orientation === -90 ) {
			$$( 'html' ).removeClass( 'with-statusbar-overlay' );
		} else {
			$$( 'html' ).addClass( 'with-statusbar-overlay' );
		}
	}
}

window.addEventListener( 'orientationchange', function() {
	my_app_statusbar_toggle();
} );

window.addEventListener( 'load', function() {
	my_app_statusbar_toggle();
} );
```
