### ISSUE TITLE
content of page flash when DOM manipulated

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#382]
With cordova on iPhone 6 and iPhone 6 plus, when you manipulate the DOM sometimes there is a flash where the content disappears for a split second.

After some investigation, this is most likely caused by the many translate3d's that are used everywhere. This puts a lot of pressure on the GPU (mostly unnecessarily). This means the GPU must page memory, and when its in a reflow state, it must calculating the z-index with all the 3d transforms.

I experimented with using different background colors to see what color the flash is. This showed that the page-content is disappearing for the split second while its calculating.

This isn't an issue in the browser as computers have a lot more GPU memory.

Has anyone else seen this?

**Comment by nolimits4web** [comment]
Can you give me a little guide on how to replicate it?

**Comment by doxiaodong** [comment]
I see it on webapp

**Comment by MarcGodard** [comment]
I added a cordova project framework7-mvc-demo that is heavy enough to see the flashes.

Let me know if I added it correctly, its my first time adding something to github like this.

**Comment by nolimits4web** [comment]
@MarcGodard wow, that looks super nice! :+1: didn't see flashes in dimulator, will update my Xcode and try it on real iPhone 5S and iPad 2

**Comment by MarcGodard** [comment]
Ok. I saw the flashes on iphone 6 and 6 plus. I don't have others to test on.

Thanks glad you liked it. Was only playing around with stuff, not doing anything with this, I have a huge app about 50% done that I will put in your showcase when done.

With this demo app, i also sometimes see the nav bar have the menu button and back button overlapping but i have never seen it in my other app. I figure thats just something I messed up.

**Comment by MarcGodard** [comment]
@nolimits4web Did you see the flashing that I mentioned?

**Comment by nolimits4web** [comment]
Not yet, checked, was busy with another project. Will have more time tomorrow and check it

**Comment by nolimits4web** [comment]
Ok, it took a while to understand where is the problem. Seems to be it is because of opacity animation on `.page`, for example setting this CSS rule solves the problem:
```
.page {
  opacity: initial !important;
}
```
But we loose opacity animation for back page. So i will need to rework a bit pages animation to leave "new" page opacity totally intact

**Comment by MarcGodard** [comment]
Sounds good. Great job finding it. I couldn't. Let me know when you fixed it all.

**Comment by nolimits4web** [comment]
Can you try it now, totally removed box-shadow animation. Now, at least on my old iPad 2, animations perform a much much smoother and without any flashed

**Comment by MarcGodard** [comment]
Ok, been moving, will test this weekend. Thanks again.

**Comment by MarcGodard** [comment]
Its still happening :(

Even in my demo app that I posted.

**Comment by nolimits4web** [comment]
@MarcGodard  can you make a video of that?

**Comment by MarcGodard** [comment]
Sure, just need to figure out how to record my iPhone screen. Doesn't happen in the emulator or through a web browser.

**Comment by nolimits4web** [comment]
@MarcGodard at least you may record it with another device/phone :smiley: Also, try it with todays 1.0.2 release

**Comment by MarcGodard** [comment]
Ok will do

**Comment by johnjamesjacoby** [comment]
Can confirm the transitions are much smoother now. I never saw literal flashing of content, but it was quite jittery. In 1.0.2 it's buttery smooth.

**Comment by nolimits4web** [comment]
Ok, i think we can close it for now

**Comment by MarcGodard** [comment]
I found more details into this problem.

I no longer see the flashes when its web only, but in cordova I still see them.

Here are the details (iOS only so far):

When you have a page that doesn't have enough content to make it scroll, but have an accordion that expands enough to then make it scroll, then you close that accordion (the webUI goes from overflow scrolling to removing overflow scrolling) this is what causes the flashes that i see.

XCode also produces an error on occasion.

```
WebKit discarded an uncaught exception in the webView:willRemoveScrollingLayer:withContentsLayer:forNode: delegate: <NSInvalidArgumentException> -[WebActionDisablingCALayerDelegate 
```

The fixes I have found so far (but not good enough).
1) remove -webkit-overflow-scrolling: touch
but this creates an ugly app without the overflow scrolling.

2) make all pages have enough content to always be in the overflow space
but this is often impossible with dynamic content

@nolimits4web I was wondering if you could make all .page or .page-content whichever it is always have overflow scrolling? Maybe by making the height 101%? I tried to do this, but couldn't get the idea to work.

If you could help me that would be great, as those flashes are very distracting.

**Comment by Jannings** [comment]
how do you resolve?

**Comment by willmero** [comment]
@nolimits4web Was there ever a fix for this flashing issue? I am seeing this happen with some accordions of mine. 
P.S Thank you for putting so much time into such an amazing framework!

**Comment by MarcGodard** [comment]
@Jannings I never solved this.
