### ISSUE TITLE
i want to contribute for translation

### ISSUE THREAD

**Issue by tormahiri** [nolimits4web/Framework7#384]
hello framework7 team
i want contribute for translation  framework7 home site to my own language 
how i can contirbute for this purpose?please guid me

**Comment by nolimits4web** [comment]
You may fork this repo https://github.com/nolimits4web/Framework7-Website and translate .jade files to your language. After you done with it, you may upload it somewhere and give me a link, or give me package and i can place it on main website in subfolder

**Comment by tormahiri** [comment]
ok thanks

**Comment by nolimits4web** [comment]
Closing for now here, if you'll have question or need my help you can email me or open issues in https://github.com/nolimits4web/Framework7-Website
