### ISSUE TITLE
Tab Bar with an error style when width>=768px

### ISSUE THREAD

**Issue by doxiaodong** [nolimits4web/Framework7#386]
Hi, I find that bug on v0.10.0. Just as http://www.idangero.us/framework7/docs-demos/tabbar-badges.html

**Comment by nolimits4web** [comment]
Yes, it is a Chrome bug: 
http://stackoverflow.com/questions/28109129/is-this-a-chrome-css-bug
http://stackoverflow.com/questions/28203658/chrome-not-properly-overriding-justify-content-for-flex-box
http://www.idangero.us/framework7/forum/#!/bugs-and-issues:tabs-bug-google-chrome
