### ISSUE TITLE
Poor targeting on iPad

### ISSUE THREAD

**Issue by johnjamesjacoby** [nolimits4web/Framework7#387]
I have an iPad Air 2 that I use for testing my web-app, and recently the tap targeting has become somewhat erratic and inaccurate. Taps don't register, sidebars don't collapse or swipe away, and it generally feels laggy and unresponsive compared to several weeks ago. The only changes to it in recent weeks have been keeping with F7 updates.

* The iPhone 6+ I use for testing is acting normal.
* I am able to duplicate this laggy behavior using the apps on your example page, such as: http://www.idangero.us/framework7/examples/split-view-panel/
* This happens in both browser and web-app views.
* I do not have a native app to test whether or not this improves anything.
* I am not able to duplicate it using Chrome's developer tools.

**Comment by nolimits4web** [comment]
Not really sure that understand what do you mean. But if you mean that taps sometimes are not working on iPad, you may try to increase `fastClicksDistanceThreshold` app parameter

**Comment by johnjamesjacoby** [comment]
I'll try that. I'll see about recording a demo for you, too.

**Comment by johnjamesjacoby** [comment]
Might it make sense for `var distance` to be:

`app.params.fastClicksDistanceThreshold * app.device.pixelRatio`
 
Since the fastClicks distance is measured in literal pixels, multiplying it by the device pixel ratio will result in a real world translation for the device, rather than white might end up a minuscule number.

Take for example the iPhone 6 Plus with a ratio of `3`. A `20` pixel `fastClicksDistanceThreshold` is still a relatively small margin of touch error.

**Comment by nolimits4web** [comment]
fastClicksDistanceThreshold was set to 10 by default. Anyway, this issue can be fixed by playing with this value. Closing for now
