### ISSUE TITLE
scrollTopOnStatusbarClick does not work on iPhone portrait orientation

### ISSUE THREAD

**Issue by kivancsahici** [nolimits4web/Framework7#390]
I'm experiencing something strange with this new scrollTopOnStatusbarClick feature.
It works fine on iPad ( landscape and portrait, both). However, on my iPhone 4S, it works only for landscape orientation. On portrait orientation, nothing happens when I click on status bar.

I was also able to reproduce this problem for HackerNews7 demo app. I updated the app with the new FM7 js/css files and set scrollTopOnStatusbarClick to true. Everything works fine on my iPad, but on the iPhone it doesn't work on portrait orientation

**Comment by kivancsahici** [comment]
I did some remote debugging on my Mac, and I can clearly say the click event is not firing at all on statusbar, on iPhone4S.

**Comment by nolimits4web** [comment]
Yes, it seems to be that it is Safari/iOS issues that doesn't produce click events at all when status bar is visible, so this feature mostly for Cordova apps

**Comment by kivancsahici** [comment]
But isn't it strange that it fires on iPad but not on iPhone?. Both devices have IOS 8.1.1.

**Comment by nolimits4web** [comment]
Yes, strange, but it is not related to Framework7
