### ISSUE TITLE
Swipe right and transition left

### ISSUE THREAD

**Issue by rosco1502** [nolimits4web/Framework7#393]
I want to be able to [swipe](http://www.idangero.us/framework7/i/feats/swipeback.mp4) but the other way around. Example: I would click on a link and it would slide in from the right, instead of the left, and then swipe back from the left side, instead of the right. It would be great if you could add this as a class such as `class="swipe-right trans-left"`. This is a Feature Request, thanks for your time!

**Comment by nolimits4web** [comment]
You describe exactly how it behaves now, new page slide in from right, and swipe back for the left side

**Comment by rosco1502** [comment]
Oh my bad, What I am looking for is to reverse that effect, new page slide in from the left and slide back from the right.

**Comment by nolimits4web** [comment]
This is possible in RTL layout, not in LTR http://www.idangero.us/framework7/docs/rtl-layout.html#.VRVQiJOsXLg
