### ISSUE TITLE
Tabbar icons weird on large screens

### ISSUE THREAD

**Issue by czb** [nolimits4web/Framework7#395]
Take a look here in the Google Chrome 40 on a large screen:

http://www.idangero.us/framework7/docs-demos/tabbar-labels.html

What I see is only two tabbar icons out of 4. As I make the Chrome window narrower all the icons get into view.

I do not know if it is the same bug but I included

```
.view {
  max-width: 768px;
  margin-left: auto;
  margin-right: auto;
}
```

into my CSS. When the page gets wider than 768px the tabbar icon position is broken - I can never see the last icon. As soon as the screen size gets under the 768px all is fine.

**Comment by nolimits4web** [comment]
It is Chrome issue that landed in v 40, should be fixed in Chrome 41 or 42, nothing can do here

**Comment by czb** [comment]
Perfect. Thanks for the info ;)

**Comment by nolimits4web** [comment]
Closing as seems to be not actual anymore and a F7 issue
