### ISSUE TITLE
encodeURIComponent of all url("data:image/svg+xml;charset=utf-8

### ISSUE THREAD

**Issue by czb** [nolimits4web/Framework7#396]
Could you please apply `encodeURIComponent` or `base64` to all occurences of `url("data:image/svg+xml;charset=utf-8` in css to make it work also in IE? See here:

https://github.com/less/less.js/issues/1716

**Comment by nolimits4web** [comment]
Currently not sure about it, because IE is not a target browser, and having encoded or base64 background will bring pain if someone will want to change, for example, icon color

**Comment by czb** [comment]
Well, I think that you should follow http://tools.ietf.org/html/rfc2397 where it is mentioned that:

Without ";base64", the data (as a sequence of octets) is represented using ASCII encoding for octets inside the range of safe URL characters and using the standard %xx hex encoding of URLs for octets outside that range.

So IE is the only browser that follows the RFC ;)

Probably you could include the encoding process into LESS compilation.
