### ISSUE TITLE
Problem with alignment within list blocks in Firefox

### ISSUE THREAD

**Issue by pianomister** [nolimits4web/Framework7#397]
Consider the following code for a list block, or check the list view with right-aligned elements here in kitchen sink:
http://www.idangero.us/framework7/kitchen-sink/

```html
<div class="list-block tablet-inset">
  <ul>
    <li><div class="item-content">
      <div class="item-inner">
        <div class="item-title">Total balance</div>
        <div class="item-after" id="total-balance">234.32</div>
      </div>
    </div></li>
    <li><div class="item-content">
      <div class="item-inner">
        <div class="item-title">Current month</div>
        <div id="total-balance-month" class="item-after"><span class="color-red">-45.43</span></div>
      </div>
    </div></li>
    <li><div class="item-content">
      <div class="item-inner">
        <div class="item-title">Last month's total</div>
        <div id="total-balance-lastmonth" class="item-after"><span class="color-green">279.75
</span></div>
      </div>
    </div></li>
  </ul>
</div>
```

Firefox browser (tested in version 35.0.1) seems to have a problem with positioning of the right aligned text in lists. The elements with class "item-after" are not aligned at the right, but instead somewhere in the middle of the list row - maybe an issue with flex property. Except for the last element, which is aligned correctly.

**Result in Firefox 35.0.1**
![alignment_issue](https://cloud.githubusercontent.com/assets/5443951/6214438/cd75e254-b5f8-11e4-94b3-6020ba3cef47.png)

**Comment by nolimits4web** [comment]
Yes, see that too. Seems to be FF bug with wrong flexbox layout that landed in FF 35, so it is because of new borders and item has the following content:
```jade
.item-inner
  .item-title
  .item-after
  ::after
```
It counts ::after pseudo element which as flex item, but it has position absolute and should be ignored as in other browsers

**Comment by nolimits4web** [comment]
Hmm, setting:
```
.item-after {
  margin-left: auto;
}
```
seems to be fix it

**Comment by pianomister** [comment]
Thanks! I added this fix in my custom app CSS for now.
