### ISSUE TITLE
Dynamic add smart-select option

### ISSUE THREAD

**Issue by VoroninAndr** [nolimits4web/Framework7#398]
Hello, I use smart-select with search bar. I want make this: when in search result nothing found, show "Add" button, and by click, add new option to this smart select. 
Prompt, please, what is the best way to add a new option in the open smart select?

**Comment by nolimits4web** [comment]
You may use page callbacks to modify smart select page, for example on pagehttp://www.idangero.us/framework7/docs-demos/smart-select-searchbar.html try to add in console:
```js
var $$ = Dom7;
$$(document).on('pageBeforeInit', '[data-page*="smart-select"]', function (e) {
    var page = e.detail.page;
    // Add not found relation
    $$(page.container).find('.searchbar').attr('data-searchbar-not-found', '.searchbar-not-found');
    // Add link to add new option
    $$(page.container).find('.page-content').append('<a href="#" class="add-option searchbar-not-found">Add New Option</a>');
});
$$(document).on('click', 'a.add-option', function(e) {
    //do something to add option here
});

**Comment by VoroninAndr** [comment]
Yes, I doing like this. But my question is: what i need to write in 
```javascript
$$(document).on('click', 'a.add-option', function(e) {
    //do something to add option here
});
```
I try add option in select
```javascript
selectUsers = $$('select.users'),
selectUsers.append('<option value="' + val + '">' + val + '</option>');
```
it's good! And after click to back button and click to select again - all works fine.
But how add "li" option in open smart select?
I think is not good write something like this
```javascript
selectUsersUl.append('<li><label class="label-checkbox item-content"><input type="checkbox" value="' + val + '" name="checkbox-1424113124395"><div class="item-media"><i class="icon icon-form-checkbox"></i></div><div class="item-inner"><div class="item-title">' + val + '</div></div></label></li>');
```
Ideally, it is desirable to have a method something like "addOption"

**Comment by nolimits4web** [comment]
Nothing really bad in to write this :)
```js
selectUsersUl.append('<li><label class="label-checkbox item-content"><input type="checkbox" value="' + val + '" name="checkbox-1424113124395"><div class="item-media"><i class="icon icon-form-checkbox"></i></div><div class="item-inner"><div class="item-title">' + val + '</div></div></label></li>');
```

Probably i'll add such method, but anyway it will do the same :)

**Comment by VoroninAndr** [comment]
The same, but if one day will change the markup, css classes or something else, it would be better if it be done in a single method.
And I don't know what is name="checkbox-1424113124395" in input?

**Comment by wangyazhen** [comment]
@nolimits4web   call `smartSelectAddOption ` after , The  `searchbar`  input value disappears and loses focus,  because `page` is `reInit`

**Comment by wangyazhen** [comment]
Thanks for some advice !
