### ISSUE TITLE
Message gap on iOS

### ISSUE THREAD

**Issue by shauntrennery** [nolimits4web/Framework7#399]
There is a slight gap between the keyboard and the messages input textarea.

![messages](https://cloud.githubusercontent.com/assets/98803/6225371/e367afb8-b691-11e4-8c07-c7a2e9136070.png)

**Comment by nolimits4web** [comment]
Yes, that is iOS issues, currently can't see the way how to fix it in Safari browser. And there is no such issue in cordova/home screen app

**Comment by nolimits4web** [comment]
Closing as seems to be iOS bug and have no way to fix it
