### ISSUE TITLE
how to integreate json data to infinite scroll ?

### ISSUE THREAD

**Issue by tormahiri** [nolimits4web/Framework7#403]
i have lot working with framework7's infinite scroll component,i'm trying example code on framework7's docs site, but i'm not achived as expected result 
i want to make news reader app ,that app require data as json , i loaded json data from remote server ,but i have no idea how i integerate fetched json data into infinite scroll ,so how i can achive this purpose,please guid me or you provide full implementation example code on the your's framework7 site,thanks

**Comment by nolimits4web** [comment]
If you already have JSON with all data, it is better to use Virtual List in this case where you can pass it render items dynamically http://www.idangero.us/framework7/docs/virtual-list.html#.VOncnVOsXLg

**Comment by tormahiri** [comment]
thanks

**Comment by nolimits4web** [comment]
I guess we can close it for now? Reopen if still have a quiestions
