### ISSUE TITLE
Improve dom cached pages with navbars structure

### ISSUE THREAD

**Issue by gpetrov** [nolimits4web/Framework7#404]
Currently if you want to use dom cached pages with navbars, you have to do something like this:

```
.views
  .view
    .navbar
      .navbar-inner
      .navbar-inner cached data-page=about
    .toolbar
    .pages
      .page data=page=index
        .page-content
      .page cached data=page=about
        .page-content
```

but this creates a lot of problems if you have multiple dom cached pages with every its own navbar as you have to sync the structures.

Wouldn't it be much more easier if you can just nest the navbar inside the dom cached page? Like this:

```
.views
  .view
    .navbar
      .navbar-inner
    .toolbar
    .pages
      .page data=page=index
        .page-content
      .page cached data=page=about
        .navbar
          .navbar-inner
        .page-content
```

**Comment by nolimits4web** [comment]
It is impossible, that is how HTML/CSS works. If you want to use dynamic navbar, it should be put outside of page itself, otherwise there is no way to work it. But you may use such layout if you'll use Fixed layout type without dinamic navbar

**Comment by murliatdure** [comment]
+1

**Comment by murliatdure** [comment]
:+1:

**Comment by murliatdure** [comment]
Any plans for material with dynamic navbar?

I just thought of having the same deck.. u can chnage the skin either IOS/Material.. no chnage in structures of navbar etc.

**Comment by nolimits4web** [comment]
> Any plans for material with dynamic navbar?

No, as there is no such feature in Material. Maybe this article will help you http://www.idangero.us/framework7/tutorials/maintain-both-ios-and-material-themes-in-single-app.html#.Vb48t5Ptmko

Closing the issue
