### ISSUE TITLE
Fast tap or "tap, hold, drag" on "< Back" (back link) not always responding

### ISSUE THREAD

**Issue by dnmd** [nolimits4web/Framework7#405]
First of, thanks for this amazing project!!

I do however experience a small issue. In the simulator/browser everything works fine when clicking the "< Back" (back link). On a device however "< Back" does not always respond:
- when tapping it fast;
- when you tab, hold and drag.

It is clearly visible that in both scenario's the "active-state" class gets applied, you can see the opacity changing (to 0.3) but the page is not going back as expected. 

In iOS however, as long as you start you "touchstart" on a "< Back" link, no matter if you make a drag movement afterwards, or tap it really fast, you always go back.

Framework7 v1.0.2
iPhone 6, iOS 8.1.3 (real device)
Deployed the "/dist" folder from the master to the device (PhoneGap).

**Comment by nolimits4web** [comment]
you may try to increase fastClicksDistanceThreshold app parameter

**Comment by dnmd** [comment]
Thanks, I'll look into it and let you know if it fixed things for me.

**Comment by MarcGodard** [comment]
That worked for me. I am thinking the default for it should be more like 20 and not 0.

I have downloaded many F7 apps, and they all seem to have that problem on retina devices (maybe because movement is more common on denser screens)

**Comment by johnjamesjacoby** [comment]
Likely related to #444

**Comment by ZanderBrown** [comment]
Time has passed and #444 was merged
