### ISSUE TITLE
Prevent scrolling on overlays

### ISSUE THREAD

**Issue by kwaak** [nolimits4web/Framework7#407]
This issue exists with [fastClicks = false].

I think the preventDefault on touchstart event to prevent overlay scrolling is to restrictive.

For example it will prevent a click event on .panel-overlay. And thus closing a open panel by clicking 'outside' of it doesn't work anymore.

The offending code:
https://github.com/nolimits4web/Framework7/blob/master/src/js/clicks.js#L316-L322
`````
    // Prevent scrolling on overlays
    function preventScrolling(e) {
        e.preventDefault();
    }
    if (app.support.touch) {
        $(document).on('touchstart', '.panel-overlay, .modal-overlay, .preloader-indicator-overlay, .popup-overlay, .searchbar-overlay', preventScrolling);
    }
`````

This is one of the events that will no longer be possible to occur:
https://github.com/nolimits4web/Framework7/blob/master/src/js/clicks.js#L63-L105
````
    function handleClicks(e) {
        
        ....

        if (clicked.hasClass('panel-overlay') && app.params.panelsCloseByOutside) {
            app.closePanel();
        }
````

I suggest to change the touchstart event to touchmove. This will still prevent scrolling, but not block the touchstart/touchend event properly shooting off the click event.

**Comment by nolimits4web** [comment]
I am wondering, where do you see such issue? On iOS it is still successfully produces click events

**Comment by kwaak** [comment]
I can reproduce it actually.

1. I downloaded the latest version.
2. Update kitchen-sink\js\kitchen-sink.js. Change 
````
var myApp = new Framework7({
    modalTitle: 'Framework7',
    animateNavBackIcon: true
});
````
to
````
var myApp = new Framework7({
    modalTitle: 'Framework7',
    animateNavBackIcon: true,
    fastClicks: false
});
````
3. Host it locally somehow, open on Safari on iOS.
4. Tap the hamburger menu, and tap outside on the panel-overlay.
5. The hamburger menu won't close.

With fastClicks turned on it obviously does work. Since your're eventually manually firing the Click event

**Comment by nolimits4web** [comment]
Missed this part `..with [fastClicks = false]` Ok, will modify it

**Comment by jascolley** [comment]
I am finding an issue with this same exact line of code now when tapping on modal-overlay's on iPad. I am using Framework7 inside of React for my web app. I'm using a popover and it opens/closes just fine in Chrome. However, on iPad when tapping on the modal-overlay to close the popover it insteads calls preventScrolling and never goes into the handleClicks() anymore. So, the popover can't be closed once opened. 

It looks like whenever I tap the modal-overlay it is the touchstart event that is being fired which of course is the one being bound to the preventScrolling method with fastClicks enabled. Should it be manually firing the click event when when I tap the modal-overlay as mentioned above by kwaak? I'm assuming the firing of the click event manually is what would allow it to be handled by handleClicks which would close the modal and behave as expected. I am pretty new to Framework7 and React so it is very possible I am just overlooking something basic.
