### ISSUE TITLE
It can't work on the mobile safari...

### ISSUE THREAD

**Issue by levelseaivy** [nolimits4web/Framework7#408]
Here's the demo page: http://www.idangero.us/framework7/kitchen-sink/

I open it on my iPhone5, version8.1.3.
And it works fine in Chrome, but in Safari, it can't work anymore. Looks like it is not loading the framework7.js file at all.

Is there any method to solve this problem? Thanks a lot!!!

**Comment by nolimits4web** [comment]
Look for problem on your side, maybe some problems with caching as for and fi everyone it works fine
