### ISSUE TITLE
Swiper and Lazyload

### ISSUE THREAD

**Issue by evolutionjay** [nolimits4web/Framework7#414]
In my case, I use Swiper and lazy load,
but it only show first swiper element's img , the other must show,and then scroll the containt ,and it will be show

**Comment by nolimits4web** [comment]
LazyLoad currently is not compatible with Swiper, but you may just hide images there and show only for active slide in CSS:
---css
.swiper-slide img {
  display:none;
}
.swiper-slide-active img, 
.swiper-slide-next img, 
.swiper-slide-prev img {
  display:block;
}

**Comment by nolimits4web** [comment]
Fixed in 1.0.3 as swiper support lazy load now
