### ISSUE TITLE
Trying to get Chart.js to Work

### ISSUE THREAD

**Issue by RappsodyStudios** [nolimits4web/Framework7#419]
I'm having an issue with [Chartjs.org] (http://chartjs.org). The implementation seems simple enough, but when I setup the canvas element in the divs I'd like my charts to appear, it just sets the width and height and renders no chart. I'm aiming at prototyping some simple mobile analytics.

Implementation is a simple as include the JS and copy and paste the JS in each sample. the chart.js is the only externally referenced file. Any thoughts on the issue?

**Comment by nolimits4web** [comment]
Do you initialize your Chart's code inside of pageInit and when it is in DOM?

**Comment by RappsodyStudios** [comment]
I assume in DOM. I included the chart.js file in the index.html toward the bottom, and I wrote the JS in the analytics.html file.

**Comment by nolimits4web** [comment]
Sounds like something wrong :) Maybe you have a live link or code examples?

**Comment by RappsodyStudios** [comment]
Here's a link to the build folder in Git: [https://github.com/RappsodyStudios/kitchen-cloud-mobile/tree/working-base/dist]

**Comment by nolimits4web** [comment]
It is very not good, you should know that browser never parse scripts in HTML files that loaded by Ajax, you should move all this logic (and no sense in F7 plugin there) to your my-app.js, something like:

```
...
myApp.onPageInit('anayltics', function(page){
//your code for init charts should be there

    var randomScalingFactor = function(){ return Math.round(Math.random()*100)};
    var lineChartData = {
        labels : ["January","February","March","April","May","June","July"],
        datasets : [
            {
                label: "My First dataset",
                fillColor : "rgba(220,220,220,0.2)",
                strokeColor : "rgba(220,220,220,1)",
                pointColor : "rgba(220,220,220,1)",
                pointStrokeColor : "#fff",
                pointHighlightFill : "#fff",
                pointHighlightStroke : "rgba(220,220,220,1)",
                data : [randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor()]
            },
            {
                label: "My Second dataset",
                fillColor : "rgba(151,187,205,0.2)",
                strokeColor : "rgba(151,187,205,1)",
                pointColor : "rgba(151,187,205,1)",
                pointStrokeColor : "#fff",
                pointHighlightFill : "#fff",
                pointHighlightStroke : "rgba(151,187,205,1)",
                data : [randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor()]
            }
        ]
    }

    var ctx = document.getElementById("line_chart").getContext("2d");
    window.myLine = new Chart(ctx).Line(lineChartData, {
        responsive: true
    });


});

**Comment by RappsodyStudios** [comment]
If I were continue that, would I put the variable and the function inside the same onPageInit? Say for instance, the top half is a line chart, the bottom portion displays a doughnut chart.

**Comment by nolimits4web** [comment]
You should put to this pageIni everything what related to this page

**Comment by RappsodyStudios** [comment]
Thanks for your help. Both of the charts I need look great.
