### ISSUE TITLE
swiper: releaseFormElements does nothing

### ISSUE THREAD

**Issue by czb** [nolimits4web/Framework7#421]
Probably not implemented?

see:
https://github.com/nolimits4web/Framework7/search?utf8=%E2%9C%93&q=releaseFormElements

**Comment by nolimits4web** [comment]
Yeap, just rudiment from previous swiper, will remove it as not required

**Comment by czb** [comment]
Well whenever I swipe to a new slide while above eg text input the input gets activated. Thats why I looked for a solution. The slide with the form inputs is added to swiper later dynamically.

**Comment by nolimits4web** [comment]
But this will not resolve it, but you may just use .blur() on elements within onTouchMove callback. I will recheck it

**Comment by nolimits4web** [comment]
I think we can close it, as this option was removed, and some improvements were made in Swiper related to inputs
