### ISSUE TITLE
How to add the alphabet indexer on the right of list?

### ISSUE THREAD

**Issue by heimasi** [nolimits4web/Framework7#425]
How to add the alphabet indexer on the right of list? 
It's like section index titles for UITableView in iOS!

**Comment by kivancsahici** [comment]
There's already a plugin for this purpose. Have you checked that one?

https://github.com/boynet/Framework7-Indexed-List-plugin

**Comment by heimasi** [comment]
Thanks a lot, I'll check this plugin right now!
