### ISSUE TITLE
setting pushState = true  && use $$.post() to fetch data from remote server，then when i click browser' history back button，the webapp didn't  goback。

### ISSUE THREAD

**Issue by plusmancn** [nolimits4web/Framework7#426]
> Debug in this file ([src/js/push-state.js](http://https://github.com/nolimits4web/Framework7/blob/623d8c6a1fc72c6d443b81f671a05390537ec0cb/src/js/push-state.js))

**if commment line from 26 to 30,force to set blockPopstate = false，history goback will work，may be it is not a good solution**

	app.initPushState = function () {
	    var blockPopstate = true;
	    
	    /**
	    $(window).on('load', function () {
	        setTimeout(function () {
	            blockPopstate = false;
	        }, 0);
	    });
	    */

**Comment by nolimits4web** [comment]
As i remember this code was very important, as on some platforms, it push to history index page without even navigate it, especially on iOS

**Comment by nolimits4web** [comment]
Closing as seems to be not actual anymore
