### ISSUE TITLE
Why ajax async is not valid

### ISSUE THREAD

**Issue by xubing6243** [nolimits4web/Framework7#427]
Why ajax async is not valid
<pre>
<code>
var asyncTest = 'no';
                $$.ajax({
                    async: false,
                    url: url,
                    method: options.method,
                    data: options.data,
                    dataType: 'json',
                    success: function (data) {
                        asyncTest = 'ok';
                    }
                });
                alert(asyncTest);
</code>
</pre>

**Comment by xubing6243** [comment]
var asyncTest = 'no';
                $$.ajax({
                    async: false,
                    url: url,
                    method: options.method,
                    data: options.data,
                    dataType: 'json',
                    success: function (data) {
                        asyncTest = 'ok';
                        xhr.resetXhr();
                        (typeof(callback) === 'function') ? callback(data) : '';
                    }
                });
                alert(asyncTest);

**Comment by nolimits4web** [comment]
Does work for me. I hope you change `option.mehod`, `option.data`, `url` to real values?) Also if you has JSONP request, then it will not work, because it doesn't use XHR request at all

**Comment by xubing6243** [comment]
How it should be done, while using jsonp, async and I can work

**Comment by nolimits4web** [comment]
jsonp cannot be async because it doesnt use xhr

**Comment by xubing6243** [comment]
OK, I know, thank you！
