### ISSUE TITLE
Calendar/Datapicker not disappears when swiping back on iOS Safari browser

### ISSUE THREAD

**Issue by pnapieracz** [nolimits4web/Framework7#428]
Calendar/Datapicker not disappears when swiping back on iOS Safari browser.
In not touchable browser (Chrome for Linux) its working properly.

**Comment by nolimits4web** [comment]
Sorry, don't understand what do you mean? Maybe screenshots or video?

**Comment by pnapieracz** [comment]
Its happens when  you open a datapicker by tapping input controller and then try to swipe back. The datapicker is still visible. I think datapicker should close in swipe back action.
If you need screenshot I'll deliver it to you later. 
You can check it using iphone browser and your full screen preview.

**Comment by nolimits4web** [comment]
Ok, i see now, will fix it
