### ISSUE TITLE
Swiper + Modal Prompt

### ISSUE THREAD

**Issue by czb** [nolimits4web/Framework7#431]
I have a prompt modal in the swiper. It works as expected on pc. On mobile (IOS 8) when I try to enter text, only the first character is pressed and the remaining characters are blocked. When I try to set value by e.g. `$('.modal-text-input').val('abcdef')` it works as expected. What is going on?

**Comment by nolimits4web** [comment]
Are you at last version of F7? Textarea is inside of Swiper?

**Comment by czb** [comment]
Ok, it was me :). I changed in my css this

    * {
        -webkit-touch-callout: none;
        -webkit-user-select: none; /* Disable selection/copy in UIWebView */
       }

into

    *:not(input,textarea) {
        -webkit-touch-callout: none;
        -webkit-user-select: none; /* Disable selection/copy in UIWebView */
       }

And now it works again :).
