### ISSUE TITLE
datepicker issue

### ISSUE THREAD

**Issue by clrnbeek** [nolimits4web/Framework7#433]
Hi Vladimir,

I believe i found a bug in the datepicker:
When you set the datepicker minDate to the current date, and in the datepicker popup you click on the next year button, the previous year button stops working. 

I also found that when the setting touchMove is true (default), the day click event 'sometimes' doesnt work. After debugging i found that allowItemClick is false in the method handleDayClick, after a normal mouseclick operation. It has something to do with the mechanism that detects if a mouseup is considered a click or move operation.
I therefor set touchmove to false to make sure the day clicks always work.

Regards,
Martijn

**Comment by nolimits4web** [comment]
Issue with min/maxDate and year switch just fixed in src.

But about touchMove and not working onDayClick handler, i can't replicate it. Can you guide me step by step on how to replicate this issue?

**Comment by clrnbeek** [comment]
Hi,

Thx for the fix. The second issue i can't reproduce either when i test
http://www.idangero.us/framework7/docs/calendar.html#.VQvSsI6G8rE 
That issue only came up within our own framework7 application. For now, I cannot find the time to provide a step by step guide that matches our usage scenario of the datepicker.

I think this might not be a datepicker issue, but has to do with our own application.
So for now you can close the issue and when i can reproduce the issue i will reopen it.

Thx.
