### ISSUE TITLE
Firefox app in iframe

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#437]
TypeError: window.getComputedStyle(...) is null framework7.js:9181
TypeError: window.getComputedStyle(...) is null framework7.js:7756

Not sure if this is causing the visual problems but if you go to:

http://rapiddevgroup.com/

With firefox, you will see those errors and the iframes show broken framework7 apps.
All other browsers seem to be fine.

**Comment by MarcGodard** [comment]
Also works fine in firefox if you open only the app. (only broken through iframe)

**Comment by nolimits4web** [comment]
Googling says that it is pure FF issue firefox getcomputedstyle in iframe

**Comment by MarcGodard** [comment]
Any ideas on a work around?

**Comment by nolimits4web** [comment]
Not sure that here could be a fix. Only if you find out how to replace it and retrieve element styles in Dom7 .css() method

**Comment by MarcGodard** [comment]
I hate firefox even more now. haha

Thanks for the help, I will just replace with images in FF.
