### ISSUE TITLE
A small bug

### ISSUE THREAD

**Issue by xubing6243** [nolimits4web/Framework7#438]
When using <code>swipeout-overswipe</code>. Don't use mobile phone mode, is normal! But use mobile phone mode, <code>swipeout-overswipe</code> failure. Test on the mobile phone also is such!

<h1>test image</h1>
![qq 20150320094135](https://cloud.githubusercontent.com/assets/4361465/6744531/bb51bf48-cee5-11e4-86f6-4e60a37581ea.png)
![qq 20150320094319](https://cloud.githubusercontent.com/assets/4361465/6744532/bb52af5c-cee5-11e4-9e41-fbf47eb88c67.jpg)

**Comment by nolimits4web** [comment]
Thanks, fixed in dev version
