### ISSUE TITLE
IE8 coverflow fails

### ISSUE THREAD

**Issue by Nytrm** [nolimits4web/Framework7#439]
IE8 coverflow fails, s.wrapper.style is undefined so perspectiveOrigin cannot be set.

s.wrapper is an array of elements so s.wrapper[0].style seems to work.

    //Set correct perspective for IE10
    if (window.navigator.pointerEnabled || window.navigator.msPointerEnabled) {
          var ws = s.wrapper.style;
          ws.perspectiveOrigin = center + 'px 50%';
    }

**Comment by nolimits4web** [comment]
Sorry, IE 8 and IE 9 are not supported
