### ISSUE TITLE
Themes: Tab Bar Icons not colored according to accent color settings

### ISSUE THREAD

**Issue by SniperGER** [nolimits4web/Framework7#441]
While exploring the current version of the Kitchen Sink, I experienced a graphical issue with Tab Bar Icons (or Icons in general?).
Icons have a "fixed" color (src/less/icons.less), which is not changed when changing the theme color.

This is what it looks like with Dark as background and ~~Red~~ Pink as accent color:
![before](https://cloud.githubusercontent.com/assets/6178765/6813152/a88f7a76-d273-11e4-8f1d-a2d640fa8b9a.png)

This is what it is supposed to look like (which I "fixed" using Web Inspector):
![after](https://cloud.githubusercontent.com/assets/6178765/6813168/bfd5b682-d273-11e4-82fe-852a78526442.png)

**Comment by nolimits4web** [comment]
Yes, but these icons are for demo purpose only, they are not a part of F7, you should use your own icons (SVG or PNG or font) in your app.
