### ISSUE TITLE
Open page in popup

### ISSUE THREAD

**Issue by VoroninAndr** [nolimits4web/Framework7#442]
Hello, I want open page in popup by click on link.
For example 
```html
<a class="link" href="page/about.html">About</a>
```
And I dont want load about.html content before.
Is it possible to load page content and show in popup by link?

**Comment by nolimits4web** [comment]
No, not possible by default. You may create popup with its initialized View, and when you click on this link you need to open popup and then use Router API to navigate Popup view to this page

**Comment by VoroninAndr** [comment]
Ok, thanks.
I think it would be useful if this feature in the future will be default.

**Comment by nolimits4web** [comment]
Maybe i'll add it, but it is easy for custom use. You may even just do it using custom XHR call:
```html
<a class="link popup-link external" href="page/about.html">About</a>
```
```js
$(document).on('click', '.popup-link', function (e){
    e.preventDefault();
    $.get($(this).attr('href'), function (content){
        myApp.popup('<div class="popup">' + content + '</div>');
    });
});
```
And that is all, you have permanent working solution

**Comment by VoroninAndr** [comment]
Yes, it's easy. Just was wondering whether there is a possibility by default.
Thanks for your reply :)

**Comment by max-wen** [comment]
@nolimits4web   will it works if I have links in the .popup page?   
if I click the links in the popup page ,  where will the page be loaded?

**Comment by iamsudharshan** [comment]
@nolimits4web,  Vlad am using three tabs based layout structure. each tab has many inner pages, an inner page has navigation to 3tabs. when I click on the links it's not showing respective tabs. I used below approach, please help me out to fix this issue. 
$$("a.home").on('click', function () {
	  mainView.router.loadPage('index.html');
          myApp.showTab('#tab2');
