### ISSUE TITLE
refresh(Previous)Page function

### ISSUE THREAD

**Issue by GuillaumeBiton** [nolimits4web/Framework7#443]
Hi Vladimir,

I use F7 with Template7 pages enabled.
On a "<a>" link item I have two actions. One enable by F7 with ajax load of a T7 page, Another one trigger on click that set a global variable using HTML5 data attribute.

there is my template7 pages history : wizard.html -> wizard-language.html -> wizard-server.html

this is my second action on click :

    $$(document).on('click', '.wizard-setLocale', function (e) {
		var locale = $$(this)[0].dataset.locale;
		if (i18n.locale !== locale) {
			i18n.locale = locale;
			mainView.router.refreshPage();
		}
	});

I have try refreshPage() and refreshPreviousPage() (I think i could be fire after page init) but In both cases my wizard-language is update but If I go back to wizard.html, it has changed. I use an helper for localization.

Any idea ?

**Comment by GuillaumeBiton** [comment]
Ok I found a solution by disabling one action using href='#'

**Comment by nolimits4web** [comment]
Right, because you can't use router methods until router is in progress. So `#` or class "external" on link will do its job

**Comment by nolimits4web** [comment]
We can close this, problem is solved?

**Comment by GuillaumeBiton** [comment]
Ok I close this issue for the moment because I can't work on my project. Will reopen it if necessary
