### ISSUE TITLE
Blurry "Bars" icon on device with 1.5 dppx

### ISSUE THREAD

**Issue by fernap3** [nolimits4web/Framework7#450]
I've noticed on devices with 1.5 dppx displays, the "bars" menu icon appears blurry.  I've pasted the offending CSS below, along with a proposed solution, tested on devices with 1, 1.5, and 2dppx.  I don't understand this media query:

@media all and (-webkit-max-device-pixel-ratio: 1), (max-resolution: 120dppx)

No device (that I know of) has a 120dppx display; I'm not really sure what this is trying to do.  Note that similar media queries also exist elsewhere in the CSS.
Thanks!

Peter

**Current CSS:**

i.icon.icon-bars {
  width: 21px;
  height: 13px;
  background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%2042%2026'%3E%3Cpath%20fill%3D'%23007aff'%20d%3D'M0%2C0h4v4H0V0z%20M8%2C1h34v2H8V1z%20M0%2C11h4v4H0V11z%20M8%2C12h34v2H8V12z%20M0%2C22h4v4H0V22z%20M8%2C23h34v2H8V23z'%2F%3E%3C%2Fsvg%3E");
}
@media all and (-webkit-max-device-pixel-ratio: 1), (max-resolution: 120dppx) {
  i.icon.icon-bars {
    height: 14px;
    background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%2021%2014'%3E%3Cpath%20fill%3D'%23007aff'%20d%3D'M0%2C0h2v2H0V0z%20M4%2C0h17v1H4V0z%20M0%2C6h2v2H0V6z%20M4%2C6h17v1H4V6z%20M0%2C12h2v2H0V12z%20M4%2C12h17v1H4V12z'%2F%3E%3C%2Fsvg%3E");
  }
}

**My Solution:**

i.icon.icon-bars {
  width: 21px;
  height: 14px;
  background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%2021%2014'%3E%3Cpath%20fill%3D'%23007aff'%20d%3D'M0%2C0h2v2H0V0z%20M4%2C0h17v1H4V0z%20M0%2C6h2v2H0V6z%20M4%2C6h17v1H4V6z%20M0%2C12h2v2H0V12z%20M4%2C12h17v1H4V12z'%2F%3E%3C%2Fsvg%3E");
}
@media all and (-webkit-min-device-pixel-ratio: 2), (min-resolution: 2dppx) {
  i.icon.icon-bars {
    height: 13px;
    background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20viewBox%3D'0%200%2042%2026'%3E%3Cpath%20fill%3D'%23007aff'%20d%3D'M0%2C0h4v4H0V0z%20M8%2C1h34v2H8V1z%20M0%2C11h4v4H0V11z%20M8%2C12h34v2H8V12z%20M0%2C22h4v4H0V22z%20M8%2C23h34v2H8V23z'%2F%3E%3C%2Fsvg%3E");
  }
}

**Comment by nolimits4web** [comment]
Thanks, should be fixed now

**Comment by fernap3** [comment]
Thanks for responding so quickly!  I would still include the "min-resolution" part of the media query as that seems to be the CSS standard going forward:

(-webkit-min-device-pixel-ratio: 2), (min-resolution: 2ddpx)

**Comment by nolimits4web** [comment]
Sure, added it
