### ISSUE TITLE
Ajax form has a invalid Content-Type

### ISSUE THREAD

**Issue by yisheng** [nolimits4web/Framework7#454]
The document says:

> Content type will be the same as specified in form's "enctype" attribute. By default (if not specified), it is application/x-www-form-urlencoded

But:

1. If `enctype` attribute is not specified, the `Content-Type` is `null`
2. If `enctype` attribute is specified as `application/x-www-form-urlencoded`, the `Content-Type` is also `null`

![f7-2](https://cloud.githubusercontent.com/assets/352986/6979321/de5a6abe-da14-11e4-8138-9dc14efb7faa.jpeg)

**Comment by nolimits4web** [comment]
We may close it
