### ISSUE TITLE
router.back empty page query object

### ISSUE THREAD

**Issue by fernap3** [nolimits4web/Framework7#456]
Hey Vladimir, loving the product so far!

I'm running into an issue where I load several pages with:

```javascript
view.router.load(
{
	content: pageContent,
	query: {foo: bar, ...}
}
```

This works fine, but I have an issue when using `router.back`.  Imagine I have the following setup:

```
----------       ----------       ----------
|        |       |        |       |        |
| Page 1 |  ==>  | Page 2 |  ==>  | Page 3 |
|        |       |        |       |        |
----------       ----------       ----------

```

When `router.back` is called (or the "back" toolbar link pressed) when Page 3 is active, the `onPageInit` event is called for Page 1, but `page.query` is an empty object when I would expect it to be the query with which the page was initially loaded.  Am I missing something or could this be a bug?  I need a way to get data to a page that is loaded as the result of a `router.back` call.

Thanks,
Peter

**Comment by nolimits4web** [comment]
Oh man, kudos to you! I guess you spent some time by making this cool picture with pages :+1: 
Yes, in this case page query will be lost, because F7 doesn't save/store page data in this case, because when you on Page 3 then Page 1 will be removed from Dom and memory. 

If you don't have too deep navigation, then i can recommend you to enable `domCache` to keep previous pages in Dom, and its data/state will be safe

**Comment by fernap3** [comment]
haha thanks.  I managed to work around it by reorganizing my class structure.

**Comment by sanks** [comment]
Hi Vladimir.
I have the same issue.

I enabled domChache when I was creating this view
```javascript
app.addView('.my-view', {
    dynamicNavbar: true,
    domCache: true
});
```

And navigate between pages inside current view using this:
```javascript
app.getCurrentView().router.load({
    content: pageContent,
    query: {foo: bar, ...}
});
```

But when I navigate back using element with "back" class, old pages do not keep their data (I mean query data).
```javascript
$(document).on('pageBeforeInit', function (e) {
    console.log(e.detail.page.query)); // is empty when I navigate back
});
```

Can you suggest something?
Thank you.

**Comment by sanks** [comment]
@fernap3 or can suggest some workaround that you made?

**Comment by fernap3** [comment]
Hey @sanks, I ended up persisting the data in an object outside of Framework7 so I didn't need to use they page query object.

**Comment by nolimits4web** [comment]
@sanks it was fixed here https://github.com/nolimits4web/Framework7/issues/674

**Comment by sanks** [comment]
@nolimits4web I built dev version but it still not works.

**Comment by nolimits4web** [comment]
@sanks then i need detailed steps on how to replicate it. Also you wrote that you use `pageBeforeInit` - this callback is useless with `domCache` for "back" pages, if so, then change it to `pageReInit`

**Comment by sanks** [comment]
@nolimits4web thank you, `pageReinit` helps.
