### ISSUE TITLE
Picker cannot get selected value after page reloading

### ISSUE THREAD

**Issue by yisheng** [nolimits4web/Framework7#458]
Picker works fine after first initialized. But, when the page reload itself (like below), then I cannot get `picker.cols[0].value`.

``` javascript
// Page Reload
mainView.router.load({
    url: 'picker.html',
    reload: true,
    ignoreCache: true
});
```

**Comment by nolimits4web** [comment]
It is good to see in live example. But if you use inline picker, then you should definitely reInit Picker too, and in any case, with current page reloading picker will loose its linked `<input>`. Anyway, page reloading is always not a great option

**Comment by nolimits4web** [comment]
Closing as no further response
