### ISSUE TITLE
Usage of href="#" in Links

### ISSUE THREAD

**Issue by thomasf1** [nolimits4web/Framework7#459]
Hey...

We´re using Framework7 together with a modified router and app-cache.

Due to some other bug, we´ve switched to Anchor/Hashtag based routing and then noticed that there are a couple of links hardcoded with href="#" in Framework7 - but their callbacks don´t disable default behavior.

We´ve simply deleted the href="#", going for <a> tags without the href and that seems to work well, which begs the question if they´re actually needed in Framework7?

There´s an interesting article about it on StackOverflow
http://stackoverflow.com/questions/11144653/a-script-links-without-href

What do you think?

**Comment by nolimits4web** [comment]
They don't required, but i guess they can't make something bad and doesn't depend on any performance.  By default F7 do `preventDefault` for any link that doesn't match to "external" condition, you can see it here https://github.com/nolimits4web/Framework7/blob/master/src/js/clicks.js#L236

So it is totally up to you, use them or not

**Comment by nolimits4web** [comment]
Closing as no further response/discussion
