### ISSUE TITLE
Dom 7 click not work

### ISSUE THREAD

**Issue by xhacker5000** [nolimits4web/Framework7#461]
<div id="personalinfo_openPic"><input   type="file" accept="image/*" /></div>
there is a input file , I wish can use dom7 to call that click like this:

$$('#personalinfo_openPic').click();

but it dosen't work

**Comment by nolimits4web** [comment]
It is a security restriction for input file. Look for solution on StackOverflow:
http://stackoverflow.com/questions/210643/in-javascript-can-i-make-a-click-event-fire-programmatically-for-a-file-input/210652#210652
http://stackoverflow.com/questions/6974228/problem-using-click-on-inputtype-file
