### ISSUE TITLE
Tab bar and navbar in popup

### ISSUE THREAD

**Issue by rozv** [nolimits4web/Framework7#462]
Is it possible to have a tab bar and/or navbar in a popup?

**Comment by nolimits4web** [comment]
Yes, as in any other View:
```
.popup
  .view
     .pages
       .page
         ...etc
```
Just follow Layout types documentation http://www.idangero.us/framework7/docs/navbar-toolbar-layouts.html

By the way, as you may see in any demo app/kitchen sink, popups have navbar, look at least there

**Comment by Schnatteraffe** [comment]
As soon as is add a class .page into my popup it is no longer possible to use a back link from the site with the popup when i came back from a following site.
