### ISSUE TITLE
Lazy Load in popup and panel

### ISSUE THREAD

**Issue by rozv** [nolimits4web/Framework7#463]
Is it possible to lazy load images in a popup and panel? i have the "lazy" class and "data-src" but the images don't load when the popup or panel is opened/scrolled

**Comment by nolimits4web** [comment]
It is not really designed for panels and popups. And at least in popup, if you have full pages (view, pages, page, page-content) structure, you may try to trigger 'lazy' events when popup opened:
---
$('.popup').on('opened', function(){
  $(this).find('img.lazy').trigger('lazy');
})

**Comment by nolimits4web** [comment]
Closing as no further response or discussion
