### ISSUE TITLE
Swiper + Tabbar

### ISSUE THREAD

**Issue by braininteractive** [nolimits4web/Framework7#464]
I have an issue with the swiper. 
I build one sample project with tabbar,
Only the swipers on first tab are displayed the others do not show unless the screen is resize or the app is init on second tab.

Any trick to fix this ?

**Comment by nolimits4web** [comment]
You need to call Swiper's `.update` method when tab with it becomes visible, because when it is hidden there is no way to calculate its size. So something like
```
$('.tab#tab2').on('show', function(){
  var swiperInstance = $(this).find('.swiper-container')[0].swiper;
  if (swiperInstance) swiperInstance.update();
})

**Comment by braininteractive** [comment]
Function swiper.update() + one light delay works for me..
