### ISSUE TITLE
Cards in Layout Grid issue

### ISSUE THREAD

**Issue by dacheezypuffs** [nolimits4web/Framework7#465]
So, I'm developing an in house web app for my server, and I want to use cards to display different information like a mix of google now and iOS in one. However, the problem is, when I use different size cards such as 25%, 50% and another 25% card, they get all wonky. I have tried removing the margin all together, it works...but it's terrible looking. Any idea how to fix this? Heres my code:

```html
<div class="row">
	<div class="card col-100 tablet-25" id="server-card">
		<div class="card-header">
			<span>Servers</span>
			<span class="preloader"></span>
		</div>
		<div class="list-block">
			<ul>
				
			</ul>
		</div>
		<div class="card-footer">
			<span class="updated">Updated: <span class="time_ago" data-livestamp=""></span></span>
			<a href="#" class="link" id="server-refresh">Refresh</a>
		</div>
	</div>
	
	
	<div class="card col-100 tablet-50" id="projects-card">
		<div class="card-header">Recent GIT Changes</div>
		<div class="card-content">
			<div class="card-content-inner">Card with header and footer. Card header is used to display card title and footer for some additional information or for custom actions.</div>
		</div>
		<div class="card-footer">Card Footer</div>
	</div>
</div>
```

Screenshot:
![untitled](https://cloud.githubusercontent.com/assets/1112585/7081065/fa47b320-df01-11e4-80f5-b6f62d91d6f1.png)

**Comment by nolimits4web** [comment]
First of all i see only two cards in your Code. And i will recommend to separate .col and .card and use the following structure:
```
.row
  .col-25
    .card
  .col-50
    .card
  .col-25
    .card
```
To keep cards inside of columns, and yes, probably, you'll need to remove margin-left/right on such cards

**Comment by dacheezypuffs** [comment]
Works beautifully! thanks!
