### ISSUE TITLE
preroute  not work

### ISSUE THREAD

**Issue by wozzup** [nolimits4web/Framework7#466]
http://www.idangero.us/framework7/docs/init-app.html#example-with-preroute

```
var myApp = new Framework7({
    animateNavBackIcon:true,
    preroute: function (view, options) {
        console.log(view);
        console.log(options);
        alert('preroute');
        return false;
    }
});
```

no console, no alert, no error, nothing returned...

**Comment by wozzup** [comment]
okay....

preroute is working on mainView page loaded and other page loads preroute...
```
var myApp = new Framework7({
    animateNavBackIcon:true,
    preroute: function (view, options) {
        console.log(view);
        console.log(options);
        alert('preroute');
        return false;
    }
});
```

this code working on mainView page clicked... not on myApp initialize....

**Comment by bgold0** [comment]
I'm having the same issue but don't understand what you did to make it work.

**Comment by red010182** [comment]
@wozzup would you please explain more on how you make it work?
