### ISSUE TITLE
photobrowser can not double finger zoom in at Android Device( NOTE 3)

### ISSUE THREAD

**Issue by xhacker5000** [nolimits4web/Framework7#467]
photobrowser can not double finger zoom in at Android Device( NOTE 3), any solotions?

**Comment by nolimits4web** [comment]
No solutions, Android doesn't support multitouch gestures events

**Comment by boynet** [comment]
it possible to detect pinch event in android, i thinking of implement it using hammerjs, I'll submit it as plugin or something

**Comment by nolimits4web** [comment]
@boynet 
> it possible to detect pinch event in android, i thinking of implement it using hammerjs, I'll submit it as plugin or something

Yes, Hammer provides some kind of hacky abstraction on this. Would be great if you can do it as plugin or **something** :)

**Comment by xhacker5000** [comment]
you wrong !!!! there is example !
function pinchListener(){
	var handleTouchyPinch = function(e, $target, data) {
		if( extentcheck(moveXPercent, moveYPercent, data.scale * endScale) ) return;
		scale = data.scale * endScale;
		$(img).css({
			'webkitTransform': 'translate3d(' + (moveXPercent * 100) + '%,' + (moveYPercent * 100) + '%,0) scale(' + scale + ',' + scale + ')'
		})
	};
	$('#can').bind('touchy-pinch', handleTouchyPinch);
	$('#can').data('touchyPinch').settings.requiredTouches = 2; //
}

**Comment by xhacker5000** [comment]
http://m.tanlu.cc/center.html

you can check this website  , no encrypt javascript , press your F12 to look code

**Comment by xhacker5000** [comment]
I decide move the html code and js code here 

html:


<!doctype>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta name="HandheldFriendly" content="true" />
		<title>上传头像</title>
		<link href="css/common.css" rel="stylesheet" type="text/css" />
		<link href="css/style.css" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src="js/jquery.min.js"></script>
		<script type="text/javascript" src="js/jquery.touchy.min.js"></script>
		<script type="text/javascript" src="js/fastclick.js"></script>
		<script type="text/javascript" src="jscom/handler.js"></script>
		<script type="text/javascript" src="jscom/global.js"></script>
		<script type="text/javascript" src="jspage/myHeadUpload.js"></script>
		
	</head>
	<body style="background-color: #000000;">
		<div id="imageDiv" style="width:100%; height: 100%;" >
			<canvas id="can" width="100" height="100" style="position: absolute; left: 0px; top: 0px; z-index: 99997;"></canvas>
			<canvas id="headCanvas" width="200" height="200" style="display: none; position: absolute; left: 0px; top: 0px; z-index: 99998;"></canvas>
		</div>
		<ul id="buttonBar" style="width:100%; height: 30px; background-color: rgba(0,0,0,0.5); position:fixed; bottom: 0px; z-index: 99999;">
			<li style=" width: 33%;float: left;"> <a onclick="window.location.href='center.html'" href="javascript:(0)" style=" text-align: center;float: left; line-height: 30px; width: 100%; text-decoration: none; color: #ffffff;">返回</a> </li>
			<li style=" width: 33%;float: left;"> <a  onclick="upload()" href="javascript:(0)"  style=" text-align: center;float: left; line-height: 30px; width: 100%; text-decoration: none; color: #ffffff;"> 上传 </a></li>
			<li style=" width: 33%;height: 30px;float: right; background: url(images/image.png) no-repeat center center;"><input type="file" id="file"  style="background-color:transparent;border:0px;opacity: 0;"></li>
		</ul>
	</body>
</html>




javascript code 

var scale = endScale = 1;
var startXPercent = moveXPercent = startYPercent = moveYPercent = 0;
var rectTop = rectLeft = rectRight = rectBottom = 0;
var imageScaleRate = 1;
var originalImageWidth,originalImageHeight;
var img;

$(document).ready(function() {
	FastClick.attach(document.body);
	initHtmlElem();
	imageFileVisible("#file");
})

function initHtmlElem(){
	$('#imageDiv').height($(window).height());
	$('#can').width($(window).width());
	$('#can').height($(window).height());
	$("#can").css({"top": "0px","left": "0px"});
	$('#buttonBar').width($(window).width());
}

function imageFileVisible(fileSelector) {
	$(fileSelector).on("change", function() {
		var file = this.files[0];
		if (file.type.match(/image.*/)) {
			var reader = new FileReader();
			reader.onload = function() {
				img = new Image();
				img.src = reader.result; 
				setTimeout(setImageAndCanvas, 500);
			}
			reader.readAsDataURL(file);
		} else {
			alert("不是图片");
		}
	})
}

/**
 * 初始化图片和画布  Init Image and canvas
 */
function setImageAndCanvas(){
	$("#imageDiv").prepend(img);
	initImage();
	initCanvasTransform();
	setHeadCanvas();
	drawRect();
	addCanvasEvents();
}


/**
 * 获取图片宽高和窗口宽高，然后设置缩放比例，和图片的起至位置，让图片居中显示 
 * get Image width and height  and set scale and make the image center of screen
 */
function initImage(){
	var windowWidth = $(window).width();
	var windowHeight = $(window).height();
	originalImageWidth = img.width;
	originalImageHeight = img.height;
	//alert(originalImageWidth + ',' + originalImageHeight);// 826, 463
	if(originalImageWidth < originalImageHeight){
		img.width = windowWidth;
		imageScaleRate = originalImageWidth / img.width;
	}else{
		img.height = windowWidth;
		imageScaleRate = originalImageHeight / img.height;
	}
	var top = (windowHeight - img.height)/2;
	var left = (windowWidth - img.width)/2;
	$(img).css({"top": top + "px","left": left + "px","display": "block", "position": "absolute"});
}

/**
 * 初始化画布变换
 * init canvas transform
 */
function initCanvasTransform(){
	$(img).css({ 'WebkitTransform': 'translate3d(0,0, 0) scale(1,1)' });
}

/**
 * 设置头像画布宽高和位置
 * set Head canvas 
 */
function setHeadCanvas(){
	var canvas = document.getElementById('headCanvas');
	canvas.width = $(window).width() - 20;
	canvas.height = $(window).width() - 20;
	var top = ($(window).height() - canvas.height)/2;
	var left = ($(window).width() - canvas.width)/2;
	$('#headCanvas').css({"top": top + "px","left": left + "px"});
}

/**
 * 画遮罩画布层的边框
 * draw 
 */
function drawRect() {
	var canvas = document.getElementById('can');
	canvas.width = $(window).width();
	canvas.height = $(window).height();
	var context = canvas.getContext('2d');

	rectLeft = 10;
	rectTop = (canvas.height - (canvas.width - 20)) / 2;
	rectRight = canvas.width - 10;
	rectBottom = rectTop + (canvas.width - 20);

	context.rect(0, 0, canvas.width, canvas.height);
	context.fillStyle = 'rgba(0, 0, 0, 0.39)';
	context.fill();
	context.clearRect(rectLeft, rectTop, canvas.width - 20, canvas.width - 20);
	context.beginPath();
	context.rect(rectLeft, rectTop, canvas.width - 20, canvas.width - 20);
	context.lineWidth = 2;
	context.strokeStyle = "#ffffff";
	context.stroke();
}
		
function addCanvasEvents() {
	pinchListener();
	dragListener();
	touchendListener();
}
/**
 * 双指缩放事件
 * Double finger drag scale  ---------------------------->  I test in Android Device it's work!!!
 */
function pinchListener(){
	var handleTouchyPinch = function(e, $target, data) {
		if( extentcheck(moveXPercent, moveYPercent, data.scale * endScale) ) return;
		scale = data.scale * endScale;
		$(img).css({
			'webkitTransform': 'translate3d(' + (moveXPercent * 100) + '%,' + (moveYPercent * 100) + '%,0) scale(' + scale + ',' + scale + ')'
		})
	};
	$('#can').bind('touchy-pinch', handleTouchyPinch);
	$('#can').data('touchyPinch').settings.requiredTouches = 2; //准确了,能在双指和单指之间切换
}

/**
 * 拖动事件
 * the Listner
 */
function dragListener(){
	var handleTouchyDrag = function(event, phase, $target, data) {
		var bodyWidth = $('body').width(),
			bodyHeight = $('#can').height(),
			xDelta = data.movePoint.x - data.lastMovePoint.x,
			yDelta = data.movePoint.y - data.lastMovePoint.y,
			newMoveXPercent = moveXPercent + (xDelta / bodyWidth),
			newMoveYPercent = moveYPercent + (yDelta / bodyHeight);
			if( extentcheck(newMoveXPercent, newMoveYPercent, scale) ) return;	
			moveXPercent = newMoveXPercent;
			moveYPercent = newMoveYPercent;
		$(img).css({
			'WebkitTransform': 'translate3d(' + (moveXPercent * 100) + '%,' + (moveYPercent * 100) + '%, 0) scale(' + scale + ',' + scale + ')'
		})
	}
	$('#can').bind('touchy-drag', handleTouchyDrag);
	$('#can').data('touchyDrag').settings.requiredTouches = 1;
	//alert('增加事件监听 dragListener');
}

/**
 * 触摸结束事件
 * Touch End
 */
function touchendListener(){
	document.getElementById('can').addEventListener('touchend', tend, false);
	//alert('增加事件监听 touchendListener');
}

function tend(event) {
	endScale = scale;
}

/**
 * 判断是否超出边界
 * Check if out of borad 
 */
function extentcheck( moveXPercentTemp, moveYPercentTemp, scaleTemp ) {
	var imgLeft = $(img).offset().left;
	var imgTop = $(img).offset().top;
	var baseWidth = $(img).width();
	var baseHeight = $(img).height();
	var centerX = $(window).width()/2;//关键的一步，以场景中心点为准，而不是图像中心点 var centerX = baseWidth / 2 + imgLeft;
	var centerY = $(window).height()/2;//var centerY = baseHeight / 2 + imgTop;
	var currentWidth = baseWidth * scaleTemp;
	var currentHeight = baseHeight * scaleTemp;
	var centerXMove = moveXPercentTemp * baseWidth;
	var centerYMove = moveYPercentTemp * baseHeight;
	var newCenterX = centerX + centerXMove;
	var newCenterY = centerY + centerYMove;
	var leftVal = newCenterX - (baseWidth * scaleTemp) / 2;
	var topVal = newCenterY - (baseHeight * scaleTemp) / 2;
	var rightVal = newCenterX + (baseWidth * scaleTemp) / 2;
	var bottomVal = newCenterY + (baseHeight * scaleTemp) / 2;
	
	if (leftVal > rectLeft || topVal > rectTop || rightVal < rectRight ||  bottomVal < rectBottom) {
		return true;
	}else{
		return false;
	}
}


function upload() {
	//alert( getBase64() );
	ajaxUpload( getBase64() );
}

function getBase64(){
	var head = document.getElementById('headCanvas');
	var headContext = head.getContext('2d');
	
	var imgLeft = $(img).offset().left;
	var imgTop = $(img).offset().top;
	var baseWidth = $(img).width();
	var baseHeight = $(img).height();
	var centerX = $(window).width()/2;//var centerX = baseWidth / 2 + imgLeft;
	var centerY = $(window).height()/2;//var centerY = baseHeight / 2 + imgTop;
	var currentWidth = baseWidth * endScale;
	var currentHeight = baseHeight * endScale;
	var centerXMove = moveXPercent * baseWidth;
	var centerYMove = moveYPercent * baseHeight;
	var newCenterX = centerX + centerXMove;
	var newCenterY = centerY + centerYMove;
	var leftVal = newCenterX - (baseWidth * endScale) / 2;
	var topVal = newCenterY - (baseHeight * endScale) / 2;
	
	var sx = ((10 - leftVal) / currentWidth) * originalImageWidth;
	var cantop = ($(window).height() - ($(window).width() - 20)) / 2;
	var sy = ((cantop - topVal) / currentHeight) * originalImageHeight;
	var swidth = head.width * imageScaleRate / endScale;//原始图片比例为基准
	var sheight = head.height * imageScaleRate / endScale;//原始图片比例为基准
	
	headContext.drawImage(img, 
						sx, sy, 
						swidth, sheight, 
						0, 0, 
						head.width, head.height);
						
	var imgData = head.toDataURL("image/png");
	var b64 = imgData.substring(22);
	$(img).css({"display": "none"});			
						
	
//	var canvas = document.getElementById('headCanvas');
//	var ctx = canvas.getContext('2d');
//	ctx.drawImage(img,0,0);
//	var imgData = canvas.toDataURL("image/jpeg",60/100);
//	var b64 = imgData.substring(23);
//	img.src = "";
	$('#headCanvas').css({"display": "block"});
	return b64;
}

function ajaxUpload(b64){
	$.ajax({type: "post", dataType: "json", crossDomain: true, url: appHandler,
		    data: {"msg": "{ 'transCode':'1040','version':'1.0','signature':'signature','imageData':'" + b64 + "','AppUserId':'" + getStorageUserId() + "','ImageType':'0' }"},
			success: function(msg) {
				if (msg.RetCode == "9999") {
					alert(msg.ErrorMsg);
				} else if (msg.RetCode == "0000") {
					//window.location.href = 'center.html';
					//alert(img.width + ',' + img.height);
					alert('上传头像成功');  // upload suc
				}
			}
	})
}

**Comment by nolimits4web** [comment]
Your code uses third-party "Touchy" library for that, i'll take a look on it. But if there are a lot of code for it, then i will not add it, because don't want to add a lot of code for none-target platform as, Framework7, currently designed for iOS

**Comment by xhacker5000** [comment]
I use canvas touch event worked , you can close issue :D

**Comment by wozzup** [comment]
in the android part, phonegap have a crosswalk solution: https://github.com/crosswalk-project/crosswalk-cordova-android

**Comment by boynet** [comment]
@nolimits4web  whats the right way to extend the photobrowser ?
I need to add this code somewhere:
````
var hammertime = new Hammer(gestureSlide[0]);
hammertime.get('pinch').set({ enable: true });
hammertime.on( 'pinchstart', pb.onSlideGestureStart );
hammertime.on( 'pinchmove', pb.onSlideGestureChange );
hammertime.on( 'pinchend', pb.onSlideGestureEnd );
````

**Comment by nolimits4web** [comment]
@boynet 
You can pass these methods:
```
hammertime.on( 'pinchstart', pb.onSlideGestureStart );
hammertime.on( 'pinchmove', pb.onSlideGestureChange );
hammertime.on( 'pinchend', pb.onSlideGestureEnd );
```
into PB's `onOpen` callback.

But with this  `var hammertime = new Hammer(gestureSlide[0]);` i am not sure. As you may see in code it is dynamic and `gestureSlide` is assigned when gesture begins https://github.com/nolimits4web/Framework7/blob/master/src/js/photo-browser.js#L375

**Comment by nolimits4web** [comment]
Maybe instead of gestureSlide, you may try to just use all its slides?

**Comment by boynet** [comment]
just ignore the gestureSlide[0]. got there by one of my tries to put it in the right place.
"new Hammer()" should get the current active slide element.
I tried even something like: inside pb.attachEvents
````
                   target.each(function( index ) {
                       var hammertime = new Hammer(this);
                       hammertime.get('pinch').set({ enable: true });
                        hammertime.on( 'pinchstart', pb.onSlideGestureStart );
                       hammertime.on( 'pinchmove', pb.onSlideGestureChange );
                       hammertime.on( 'pinchend', pb.onSlideGestureEnd );
                    });
````
ofcouse it dosent feel right

**Comment by nolimits4web** [comment]
Hmm, this looks correct. Did you try to `console.log` some variables/steps inside of `onSlideGestureStart/Change/End` methods? Probably hammer could pass there something different

**Comment by boynet** [comment]
the code I put is working fine.. the only problem is that its change the core photobrowser so i dont know where to put it so it will not get deleted each time I update to new f7 version

**Comment by nolimits4web** [comment]
Should work if you put in in `onOpen` callback:
```js
...
onOpen: function (pb) {
  var target = pb.params.loop ? pb.swiper.slides : pb.slides;
  target.each(function( index ) {
    var hammertime = new Hammer(this);
    hammertime.get('pinch').set({ enable: true });
    hammertime.on( 'pinchstart', pb.onSlideGestureStart );
    hammertime.on( 'pinchmove', pb.onSlideGestureChange );
    hammertime.on( 'pinchend', pb.onSlideGestureEnd );
  });
}

**Comment by boynet** [comment]
oh thanks.. tommrow I will post here the whole code with onClose for anyone looking for it in the future

**Comment by boynet** [comment]
a 1 more obstacles:
````
pb.onSlideGestureStart = function (e) {
        if (!gestureSlide) {
            gestureSlide = $(this);
            gestureImg = gestureSlide.find('img, svg, canvas');
            gestureImgWrap = gestureImg.parent('.photo-browser-zoom-container');
            if (gestureImgWrap.length === 0) {
                gestureImg = undefined;
                return;
            }
        }
        gestureImg.transition(0);
        isScaling = true;
    };
````
when onSlideGestureStart is called with hammerjs $(this) and gestureSlide is equal to empty dom7 elemnt so gestureSlide is true and gestureImg.transition(0); is get called and raise an error.

if I change the function to this everything is working:
````
pb.onSlideGestureStart = function (e) {
                if (!gestureSlide || !gestureSlide.length) {
                    gestureSlide = pb.swiper.slides.eq(pb.swiper.activeIndex);
                    gestureImg = gestureSlide.find('img, svg, canvas');
                    gestureImgWrap = gestureImg.parent('.photo-browser-zoom-container');
                    if (gestureImgWrap.length === 0) {
                        gestureImg = undefined;
                        return;
                    }
                }
                gestureImg.transition(0);
                isScaling = true;
            };
````

**Comment by boynet** [comment]
thanks the other problem like I said is in line 375 https://github.com/nolimits4web/Framework7/commit/346e77b5ace5dd56ceecc7321e10f9e5bad6a638#diff-58a03374079568ecefec70f988073d0bR375
$(this) is empty Dom7: 
````
Dom7 {length: 0, addClass: function, removeClass: function, hasClass: function, toggleClass: function…}length: 0
````

**Comment by boynet** [comment]
thanks working great now

**Comment by seme1** [comment]
@boynet 
Can you please share the code you used for getting photo browser to work on Android ??

**Comment by boynet** [comment]
@seme1 I am using kind of old version so maybe you need to make few changes:

the photoBrowser onOpen and onClose callbacks
```
onOpen: function (pb) {
            if (myApp.device.os =='ios') return;
            var target = pb.params.loop ? pb.swiper.slides : pb.slides;
            var hammertime=[];
            target.each(function (index) {
                hammertime[index] = new Hammer(this);
                hammertime[index].get('pinch').set({
                    enable: true
                });
                hammertime[index].on('pinchstart', pb.onSlideGestureStart);
                hammertime[index].on('pinchmove', pb.onSlideGestureChange);
                hammertime[index].on('pinchend', pb.onSlideGestureEnd);
            });
        },
        onClose: function(pb){
            if (myApp.device.os =='ios') return;
            var target = pb.params.loop ? pb.swiper.slides : pb.slides;
            var hammertime=[];
            target.each(function (index) {
                hammertime[index] = new Hammer(this);
                hammertime[index].off('pinchstart');
                hammertime[index].off('pinchmove');
                hammertime[index].off('pinchend');
            });
        }
```

**Comment by seme1** [comment]
Thank you so much. I'm sure this would be useful for others, too.

**Comment by media0101** [comment]
This problem has not yet been solved?
