### ISSUE TITLE
Template7 > how to equal two variables from different contexts?

### ISSUE THREAD

**Issue by lukasMega** [nolimits4web/Framework7#469]
My template context object example:
```javascript
{
	label: "Image Size",
	current: "3872x2592",
	choices: [
		"3872x2592",
		"2896x1944",
		"1936x1296"
	]
}
```
my template: 
```html
{{#if choices}}
  <select name="{{label}}">
    {{#each choices}}
    <option value="{{@index}}" {{#js_compare "this == current"}}selected{{/js_compare}} >
      {{this}}
    </option>
    {{/each}}
  </select>
{{/if}}
```
I need compare every item in ```{{#each}}``` block with variable from parent context (in my case variable ```current```)
I tried:
 - current
 - {{../current}}
 - ../current

... no success.
Is it possible?
Thanks for answer :)

**Comment by nolimits4web** [comment]
No need to duplicate same issue in different repo. Will close this one, and give you an anwer in Template7's one
