### ISSUE TITLE
why the .css use px unit?

### ISSUE THREAD

**Issue by wozzup** [nolimits4web/Framework7#470]
why the `css` use `px` unit, why not `em` or `rem`?

**Comment by nolimits4web** [comment]
I can ask you the same, why it should use `em` or `rem` and not a `px`? I chosen `px` because they are much more widely used and more people understand it much better than `em` or `rem`

**Comment by wozzup** [comment]
haha, that is true. px get better understanding. thanks

**Comment by hixiaoguan** [comment]
why the css use px unit, why not rem???

**Comment by ZanderBrown** [comment]
mostly because iOS is the same size everywhere so f7 should to
