### ISSUE TITLE
router api View Navigation Methods reload options not set correctly

### ISSUE THREAD

**Issue by wozzup** [nolimits4web/Framework7#471]
http://www.idangero.us/framework7/docs/router-api.html#view-navigation-methods

index.html on app init
``` html
<div class="view view-main" data-page="index">
```

on click to load about.html
```javascript
mainView.router.loadPage({
    url: 'about.html',
    reload: true
});

// or
// mainView.router.reloadPage('about.html');
```
in this case the `.view-main` should set `data-page="about"`, but in options `reload` it is not, the `data-page` still is the `index`
``` html
<div class="view view-main" data-page="index">
```
but should be `data-page="about"` right?
``` html
<div class="view view-main" data-page="about">
```

it is a bug? or i am misunderstanding?

**Comment by nolimits4web** [comment]
Yep, seems like a bug. Will fix it
