### ISSUE TITLE
Support lazy loading within Messages.

### ISSUE THREAD

**Issue by shauntrennery** [nolimits4web/Framework7#473]

**Comment by nolimits4web** [comment]
I am a bit confused, isn't it supported for images in messages?

**Comment by shauntrennery** [comment]
I've tripple checked. It could be something I'm missing something thou.

**Comment by nolimits4web** [comment]
So it would be good live example where it is not working

**Comment by shauntrennery** [comment]
I'll create a test and upload it here if still not working. I'll close if I'm unable to reproduce.

**Comment by shauntrennery** [comment]
Pasting the HTML below into http://www.idangero.us/framework7/kitchen-sink/ is a good demonstration of the lazy feature not working in Messages.

<img class="lazy" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-lazy="http://i2.cdn.turner.com/money/dam/assets/150407145223-ibm-watson-chef-ice-kitchen-cookbook-620xa.jpg" width="195px" height="109px">

Pasting the non lazy version of the HTML above works as expected. 

<img src="http://i2.cdn.turner.com/money/dam/assets/150407145223-ibm-watson-chef-ice-kitchen-cookbook-620xa.jpg" width="195px" height="109px">

**Comment by nolimits4web** [comment]
Be careful. It should be `data-src` on img, not `data-lazy`. With `data-src` it works

**Comment by shauntrennery** [comment]
Leaving as closed.

Pasting the HTML below into the demo on the home page still does not work for me.

```
<img class="lazy" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="http://i2.cdn.turner.com/money/dam/assets/150407145223-ibm-watson-chef-ice-kitchen-cookbook-620xa.jpg" width="195px" height="109px">
```

**Comment by nolimits4web** [comment]
If "by passing" you mean insert it into message field, then it will not work. Because you need to reinit lazy loading for page. And there is no much sense in it for user to send message and see lazy loaded image, i think. But if you add this HTML in initial page html, then, on page load it works as expected

**Comment by boynet** [comment]
@shauntrennery if you need to work with a lot of ajaxed inserted images you can try https://github.com/aFarkas/lazysizes or https://github.com/callmecavs/layzr.js

**Comment by shauntrennery** [comment]
Thank you @boynet. I've actually been looking at https://github.com/callmecavs/layzr.js 

Working as expected from my initial tests.
