### ISSUE TITLE
css for -webkit

### ISSUE THREAD

**Issue by wozzup** [nolimits4web/Framework7#474]
maybe add follow style to html body make fonts clear: 
``` css
-webkit-font-smoothing: antialiased;
-webkit-text-stroke-width: 0.2px;
```

**Comment by nolimits4web** [comment]
Not sure about it. It is not required for default/system fonts, and could produce performance issues. So lets leave it up to developer, because it is always easy to add these two lines in custom app's CSS file

**Comment by wozzup** [comment]
you are the pro. hahaha
