### ISSUE TITLE
searchbar onBeforeRemove called on already destroyed searchbar

### ISSUE THREAD

**Issue by boynet** [nolimits4web/Framework7#477]
and raise an error of:
Uncaught TypeError: Cannot read property 'detachEvents' of null

a quick fix is to put if (s) like:
````
s.destroy = function () {
                if (s)
                    s.detachEvents();
                s = null;
            };
````
dont know if its the best solution so I didnt opend a pr

how to replicate:
1.open kitchen-sink go to Search Bar page
2. write in console:
````
$$('.searchbar')[0].f7Searchbar.destroy();
````
3.click on back button

**Comment by nolimits4web** [comment]
Fixed, thanks

**Comment by nolimits4web** [comment]
With this commit https://github.com/nolimits4web/Framework7/commit/a4e78b50d71ef41a66ed2a7efb16394d40a1d3c9
