### ISSUE TITLE
Swiper Slider not working on mainView.router.loadPage

### ISSUE THREAD

**Issue by wozzup** [nolimits4web/Framework7#478]
Swiper Slider not working on `mainView.router.loadPage` or `reloadPage`

``` javascript
var myApp = new Framework7({
  template7Pages: true
});

var mainView = myApp.addView('#main', {
  dynamicNavbar: true
});

mainView.router.reloadPage('home.html');
// or mainView.router.loadPage('home.html');

var mySwiper = myApp.swiper('.swiper-container', {
  autoplay: 10
});

console.log(mySwiper);
```

console:
```
window.Swiper {params: Object, classNames: Array[0], $: function, container: e, isSafari: true…}
```

but in screen swipe left or right both not response

**Comment by wozzup** [comment]
set in data attr works
``` html
<div class="swiper-container swiper-init">
```

but not in javascript

**Comment by nolimits4web** [comment]
Docs are pretty useful: http://www.idangero.us/framework7/docs/page-callbacks.html

> Page Callbacks become very handy when you need to execute specific code for specific pages

```
myApp.on('pageInit', function(page){
  var mySwiper = myApp.swiper('.swiper-container', {
    //...
  }
});
```

Kitchen sink could help too https://github.com/nolimits4web/Framework7/blob/master/kitchen-sink/js/kitchen-sink.js#L478
