### ISSUE TITLE
How to access device's camera?

### ISSUE THREAD

**Issue by mreigen** [nolimits4web/Framework7#479]
(I don't know how to label this issue 'question')

I've been building an app to upload pictures via my phone using Framework7. I have a very basic app running that allows users to select photos in their phone which is awesome. However, I'd like to know if there is anyway the app can allow users to access the device's camera to take photo? I know one app in the showcase list claims that they can do this (Datingher.dk - Gratis dating)

Does any body know how to do this?  Thank you.

**Comment by wozzup** [comment]
gogole: phonegap cordova

**Comment by mreigen** [comment]
@wozzup Thank you.
I have just found something along that line: http://learn.ionicframework.com/formulas/cordova-camera/
I'm going to give it a try now.
