### ISSUE TITLE
Scrolling .tab

### ISSUE THREAD

**Issue by MattCowley** [nolimits4web/Framework7#483]
I have a div that is 70% of the page in width, with tabs in it. One of the tabs overflows off the screen (with tab-bar at bottom) and even with
```
.tab .content-block {
  overflow:auto;
  -webkit-overflow-scrolling: touch;
}
```

it still will not let me scroll inside that tab.

Please help

**Comment by nolimits4web** [comment]
Need to see live example or JSFiddle

**Comment by MattCowley** [comment]
http://dev.mattcowley.co.uk/dev/PRIVATE/BMI/

**Comment by MattCowley** [comment]
My Appointments -> My Operation -> Recovery Tab

**Comment by MattCowley** [comment]
Also, Is there a fix for youtube videos, if i have a YT video on there, save it to home screen and open the app, it instant redirects tot the video in the you tube app.

**Comment by nolimits4web** [comment]
You need to fix block height if you want to make it scrollable. For example:
```css
.tab .content-block {
  height: -webkit-calc(100vh - 44px - 70px - 44px - 56px);
  height: calc(100vh - 44px - 70px - 44px - 56px);
}

**Comment by MattCowley** [comment]
Oh, ok thanks man, any fix for YouTube

**Comment by nolimits4web** [comment]
Not sure, seem like iOS or YouTube issue

**Comment by nolimits4web** [comment]
But you can try to use YouTube API just to get the Video URL and use it as usual embed `<video>` tag

**Comment by MattCowley** [comment]
Ok, I'll see if that works

**Comment by MattCowley** [comment]
For future reference, this works well http://jsfiddle.net/qpbsfxgr/

**Comment by nolimits4web** [comment]
Cool, thanks :+1:
