### ISSUE TITLE
Form Element "Switch" does not behave like native ios-switch

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Framework7#485]
The form element "switch" only toggles after click, but does not toggle by swipe left/right. In ios, we can make the toggle also by swipe left/right. Would be nice to enhance the f7 "switch"-form to adapt the ux of ios. Thanks!

**Comment by nolimits4web** [comment]
I will think about it. Just don't want to add 3 event listeners for each switch, which is not really main element in app

**Comment by boynet** [comment]
I think its should come as a plugin.. like you said it not worth it for most of the apps

**Comment by nimo23** [comment]
Plugin would be bad. I guess, users expect native user experience and most of the users expect that a "slider toggle" behaves like a slider toggle and not like a checkbox. A good idea would be to make it optional (for example, by assigning a class to the slider-toogle or by providing a global parameter such as "nativeSliderFeeling=true". There are a lot of users sliding the slider instead of clicking, because it is a slider-toogle;)

**Comment by SammySoft** [comment]
I use this code to solve this Problem:

	(function () {

		// Checkbox drag extention
		var m_IsDraggingCheckbox = false;

		function handleTouchStart(e) {
			var touchStartX = e.targetTouches[0].clientX;
			var input = $$(this).parent().find('input');

			if (input[0].checked && touchStartX > ($$(this).offset().left + $$(this).width() / 2))
				m_IsDraggingCheckbox = true;
			else if (!input[0].checked && touchStartX < ($$(this).offset().left + $$(this).width() / 2))
				m_IsDraggingCheckbox = true;
			else
				m_IsDraggingCheckbox = false;
			
			if(m_IsDraggingCheckbox)
				 e.preventDefault();
		}

		function handleTouchMove(e) {
			if (!m_IsDraggingCheckbox)
				return;

			var touchStartX = e.targetTouches[0].clientX;
			var input = $$(this).parent().find('input');

			if (touchStartX > ($$(this).offset().left + $$(this).width() / 2))
				input[0].checked = true;
			else if (touchStartX < ($$(this).offset().left + $$(this).width() / 2))
				input[0].checked = false;
		}

		function handleTouchEnd(e) {
			m_IsDraggingCheckbox = false;
		}


		$$(document).on(myApp.touchEvents.start, '.label-switch .checkbox', handleTouchStart);
		$$(document).on(myApp.touchEvents.move, '.label-switch .checkbox', handleTouchMove);
		$$(document).on(myApp.touchEvents.end, '.label-switch .checkbox', handleTouchEnd);

	})();


This could be a hint, how this problem could be solved.
Maybe someone could integrate it in a better way in the framework.

**Comment by nimo23** [comment]
for inspiration (material design) "toggle-button" by google:

https://elements.polymer-project.org/elements/paper-toggle-button?active=paper-toggle-button&view=demo:demo/index.html

**Comment by abremner** [comment]
@SammySoft Thank you very much for this solution. I have observed many iOS users who **only** swipe on toggles, they don't even know that you can just tap them. This should definitely be included in the F7 Framework.

**Comment by 16patsle** [comment]
This would probably be a good candidate for a configuration option on app initialization. So you could do something like this if you wanted it enabled:
```javascript
var myApp = new Framework7({
    switchSwipe: true // enable swipe-to-switch on switch form elements
});
```

**Comment by Paddy78de** [comment]
If you use SammySoft's code and have a change event on the checkbox/switch you have to trigger the event manually in the handleTouchMove-function:

`if (!m_IsDraggingCheckbox)
			return;

		var touchStartX = e.targetTouches[0].clientX;
		var input = $$(this).parent().find('input');
		var changetrigger=false;

		if (touchStartX > ($$(this).offset().left + $$(this).width() / 2)) {
			if (!input[0].checked) {
				
				 changetrigger=true;
				
			}
			input[0].checked = true;
			
		} else if (touchStartX < ($$(this).offset().left + $$(this).width() / 2)) {
			if (input[0].checked) {
				
				 changetrigger=true;
				
			}
			input[0].checked = false;
			
		}
		if (changetrigger) {
			
			input.trigger("change");
		}`

**Comment by ZanderBrown** [comment]
I'm fairly sure this has been committed to master
