### ISSUE TITLE
On Ajax success reload view content

### ISSUE THREAD

**Issue by nehil** [nolimits4web/Framework7#486]
I have form with Multiple HTML elements. How can I reload this content value on Ajax success? 

I am using this framework in PhoneGap.

I tried - mainView.router.reloadContent(content);

    $$.ajax({
			type:'POST',
			url: "http://www.xyz.co/upload.php",
			dataType:'text',
			data:{'data':data},	
                        success:function(data){		
							myApp.hidePreloader();
							myApp.alert(data, 'Yay Success!');
							var productsPageHTML = $$('#view-1').html();
							mainView.router.reloadContent(productsPageHTML);
								}
																				
		});			

Buy its not working?

**Comment by nolimits4web** [comment]
Will answer you on forum
