### ISSUE TITLE
Memory leak happening on kitchen-sink !

### ISSUE THREAD

**Issue by mingodad** [nolimits4web/Framework7#488]
Hello !

Doing tests with framework7 I found a memory with kitchen-sink under chromium/chrome, to reproduce we need to open http://www.idangero.us/framework7/kitchen-sink/ navigate to:

"Forms" -> "Form Elements" and once there -> "Forms" (back button on top).

If we continue switching between "Form Elements" and back ("Forms") with the chromium/chrome taskmanager open we can see that the memory only increase each time we switch (for me around 1 megabyte for each 2 or 3 switches).

For a long running application this is a problem, I plan to make an offline application with framework7 and this application can remain open weeks.

I'll continue testing to see if other iteractions also cause memory leaks.

Cheers !

**Comment by mingodad** [comment]
Hello again !
It seems that I did not understood correctly how chrome taskmanger/profiler works altough the total memory/tab reported always grow the  javascript memory goes up and/down.

But the number of nodes do not goes down the same way.
![framework7-memory-profiler](https://cloud.githubusercontent.com/assets/462618/7671451/91131b3a-fcc8-11e4-853c-447c6a6062c9.png)

**Comment by nolimits4web** [comment]
It is not a memory leak. It is how browser's garbage collector works. When we remove element/node from DOM, browser doesn't remove it from memory, but removes it later. So you shouldn't worry about it

**Comment by aries1980** [comment]
GC can't happen in many case: http://stackoverflow.com/a/12658212/3188624 . The GC algorithm and kickin  depend on the JS engine. I haven't tried with this particular case, but you can trigger a GC in Firefox in about:memory to confirm the leakage.

**Comment by nolimits4web** [comment]
@aries1980 unfortunately we can't control it much in mobile apps/browsers. It also depends on developers, which should remove/destroy components (like Swiper, Virtual List, etc.) on pages removing (when they are not needed)
