### ISSUE TITLE
div-tags within label tags not allowed

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Framework7#491]
The documentation of f7 contains examples with div-tags within label-tags. 

For example (copied from http://www.idangero.us/framework7/docs/checkboxes-radios.html): 
`<label class="label-checkbox item-content">
        <input type="checkbox" name="my-checkbox" value="Books" checked="checked">
        <div class="item-media">
          <i class="icon icon-form-checkbox"></i>
        </div>
        <div class="item-inner">
          <div class="item-title">Books</div>
        </div>
      </label>`

*According to html-spec, this is not allowed, hence html-validatiors would complain that.*
(http://stackoverflow.com/questions/18609554/is-div-inside-label-block-correct).

**Would be better to replace divs within label with span-elements or do the divs out of the label-tags.**

**Comment by nolimits4web** [comment]
Do you really care what html-spec states about it? I am not, as it works like it should everywhere and will work, it hasn't any cons, and of course - it doesn't affect performance or anything else . Anyway, you can just replace all those `divs` with `spans` if this is really matters for you ;)

**Comment by nimo23** [comment]
Yes, I know, it works;) however, it is not valid html. Automated tests would complain such structure..is there any good reason why you use divs instead of spans within label-tags? (I will replace all such divs with spans..)

**Comment by nolimits4web** [comment]
> is there any good reason why you use divs instead of spans within label-tags

Yes, because they are block elements by default and to keep the same consentient HTML layout through all list-block elements

> it is not valid html. Automated tests would complain such structure

I'll ask again :) Who ever cares about valid HTML? It became not relevant since HTML5 ... and especially for mobile apps

**Comment by lvivtotoro** [comment]
Screen readers, strict browsers, etc.
