### ISSUE TITLE
provide different transistions between pages

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Framework7#492]
Actually, f7 does only provide page-transistion from right-to-left and vice versa. Would be nice to provide other (hardware-accelareted) transistions as well. (Examples: http://tympanus.net/Development/PageTransitions/)

We could put the kind of transistion within a-tag by class-names (or by adding transistion-class to .navbar-header):

`<a href=“../tpl/create_user.html” class=“link” id=“icon-add-channel” class=“transistion-bottom-to-top”>+</a>`

Would be nice to provide css-classes for different sliding effects, this would enhance UX-Feeling;)

**Comment by nolimits4web** [comment]
I would avoid that for many reasons, for example:

* It breaks native behavior, as pages in iOS apps are loading in this way. If you want something pop up from bottom then there is a  `popup` for that case. This is what iOS users are used to
* swipe back will not work or its logic will be not straight forward for user
* it can be done manually without a hassle. Animation is based on CSS animation. So if it is really required, developer may add by himself in CSS for selected pages

**Comment by nimo23** [comment]
yes, you are right. I guess, it is best to close this request. It really breaks native ux, so this feature request is senseless. Please close this request. Thx.

**Comment by Savjee** [comment]
I'm also interested in this because the "slide in from the bottom" transistion is native to iOS.
See what happens when you make a new appointment in the Calendar app. It slides up from the bottom.

Is there any way to do this with Framework7?

**Comment by ZanderBrown** [comment]
It slides up because it's a popup. if you want a popup use a popup
