### ISSUE TITLE
label-switch should align to right by default

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Framework7#494]
Label switch is not aligned to right by default.

`<div class="item-content">
							<div class="item-inner">
								<div class="item-title label">App-Töne</div>
								<div class="item-input" style="text-align: right;">
									<label class="label-switch">
									<input type="checkbox">
										<div class="checkbox"></div>
									</label>
								</div>
							</div>
						</div>`

I have to assign **"text-align: right" in .item-input.** Should be aligned to right by default.

**Comment by nimo23** [comment]
I dont know, but i guess, only on iphones it should be right. On ipad it is not an issue?!

**Comment by nolimits4web** [comment]
Screenshots will be helpful

**Comment by nimo23** [comment]
Look at the "Framework7-master/kitchen-sink/" in section "Forms"-> "Switch". The switch-toggle is aligned to left instead of right.

**Comment by nimo23** [comment]
Maybe it s a personal taste, however, I have not seen any app on iphones where switch-toggle is not aligned to right;) On Ipad (larger screens), maybe, it s okay to leave that on the left side.

**Comment by boynet** [comment]
from a quick search it looks like you are right:
https://www.google.co.il/search?q=ios+8+switch&newwindow=1&safe=off&espv=2&biw=1366&bih=667&source=lnms&tbm=isch&sa=X&ei=q65cVZHxCoqcsgGBx4CIBQ&ved=0CAYQ_AUoAQ

**Comment by nolimits4web** [comment]
If you need it on right, then just put it in `.item-after` like on "List View" example page
