### ISSUE TITLE
iPad1 refresh not drawing properly

### ISSUE THREAD

**Issue by mingodad** [nolimits4web/Framework7#495]
Hello !

I'm testing the kitchen-sink on an iPad1 and for example "List View" when we scroll up the new content appears only partially.

![img_0001](https://cloud.githubusercontent.com/assets/462618/7727241/828bce84-feff-11e4-831b-69e784faefdc.PNG)

Here is the "Lazy Load Images":
![img_0002](https://cloud.githubusercontent.com/assets/462618/7727364/2c13abde-ff00-11e4-9191-40ea10932415.JPG)

Also on the "Forms" -> "Checkboxes And Radios" the "RADIO BUTTONS GROUP" do not show checked:
![img_0004](https://cloud.githubusercontent.com/assets/462618/7727622/de0da5e6-ff01-11e4-8e9a-b11dd4bb1fe8.PNG)

**Comment by nolimits4web** [comment]
The same, iOS 6, and especially iPad 1 are not supported, they are too outdated
