### ISSUE TITLE
iPad1 "Hacker News" landscape do not draw properly

### ISSUE THREAD

**Issue by mingodad** [nolimits4web/Framework7#496]
Hello !

When testing the "Hacker News" application on an iPad1 in landscape the split between the left and right panel do not work properly:
![img_0003](https://cloud.githubusercontent.com/assets/462618/7727488/e2ef6afa-ff00-11e4-9eee-a13f9bb874a1.PNG)

**Comment by nolimits4web** [comment]
Sorry, iOS 6, and especially iPad 1 are not supported, they are too outdated
