### ISSUE TITLE
option to rerender previous view

### ISSUE THREAD

**Issue by Nytrm** [nolimits4web/Framework7#497]
Hi, is there a way i can re-render the previous Page instance on back button click?

I have list and a list detail page, the details has the functionality to change the name of the list Item

List click on item 1 -> list detail (item 1) and re-name item 1 to item 2 ( with a server call).
When going back i still see the cached page instance with item 1.

I can get the page instance and also change the name in DOM but i would like it to redownload json from the server with the latest items and also with the renamed item.

Any of this available ? maybe remove the old page instance cache somehow and force it to recreate it?

**Comment by nolimits4web** [comment]
There is a `reload` and `reloadPrevious` options for this in Router, or short `.router.reloadPreviousPage` method

**Comment by braininteractive** [comment]
Anyway we can catch a callback for router.refreshPreviousPage() or .router.reloadPreviousPage()
I would like trigger router.back() when the content of my previous page is refreshed.

**Comment by DmonteiroD** [comment]
Apparently I am having this issue too. I post a new question in the forum about this.

**Comment by ZanderBrown** [comment]
@braininteractive is this issue resolved?

**Comment by braininteractive** [comment]
@ZanderBrown : no more problem my side, I guess you can close this issue.
