### ISSUE TITLE
formToJSON() does NOT convert to JSON

### ISSUE THREAD

**Issue by arrbie** [nolimits4web/Framework7#501]
The app method formToJSON() doesn't convert to JSON at all. It actually returns a key-value structured javascript OBJECT.

If this is the intended behavior, the name of the method is quite misleading. Even, the Framework7 manual says: "formToJSON(form) - convert form fields valus to JSON".

Suggestion: Either change the implementation of the formToJSON method so that it really returns a JSON string, or change the name of the method and the manual text to something that doesn't use the word JSON at all.

--------------
PS. I think there are several other occasions throughout Framework7 and the manual that add to this confusion between javascript objects and JSON strings. It would be great if you could clean these up consistently.

Notice: JSON is a text format (string), not a key-value javascript object. These are two completely different types.
In your manual you write things like "formData - object with form data in JSON format". This doesn't make any sense. There is no such thing as a javascript object in JSON format.

**Comment by nolimits4web** [comment]
`formToJSON` method name will not be changed, and it will return JS object, not JSON `string`. Where says that JSON is a mandatory string?
