### ISSUE TITLE
Date bug.

### ISSUE THREAD

**Issue by hideweb** [nolimits4web/Framework7#504]
At this time, when the number of 29 will appear bug.

![001](https://cloud.githubusercontent.com/assets/5046036/7908147/5e259d9e-0874-11e5-90c2-5c198736af71.jpg)
![002](https://cloud.githubusercontent.com/assets/5046036/7908206/fdbe3f14-0874-11e5-80ea-3e6348e86058.jpg)

**Comment by nolimits4web** [comment]
What the Android version and browser version?

**Comment by hideweb** [comment]
IOS version and Android version and browser are the wrong style.

**Comment by hideweb** [comment]
I am from China. English is not too good. Hey.
