### ISSUE TITLE
question about the swiper in modal

### ISSUE THREAD

**Issue by abcsun** [nolimits4web/Framework7#505]
hi, 
i just put the swiper container into a modal-body, but when the modal was fired by click a link, the swiper could't work. when i resize the browse's size, it will be ok.

 the swiper demo i used is https://github.com/nolimits4web/Swiper/blob/master/demos/01-default.html

and my test code is
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Swiper demo</title>
    
<link href="http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="http://cdn.bootcss.com/Swiper/3.0.0/css/swiper.min.css">

<script src="http://cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>

<script src="http://cdn.bootcss.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

<script src="http://cdn.bootcss.com/Swiper/3.0.0/js/swiper.min.js"></script>

```
<!-- Demo styles -->
<style>
body {
    background: #eee;
    font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
    font-size: 14px;
    color:#000;
    margin: 0;
    padding: 0;
}
.swiper-container {
    width: 500px;
    height: 300px;
    margin: 20px auto;
}
.swiper-slide {
    text-align: center;
    font-size: 18px;
    background: #fff;

    /* Center slide text vertically */
    display: -webkit-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    -webkit-justify-content: center;
    justify-content: center;
    -webkit-box-align: center;
    -ms-flex-align: center;
    -webkit-align-items: center;
    align-items: center;
}
</style>
```

</head>
<body>
    <div class="modal fade" id="myModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <a aria-hidden="true" class="close" data-dismiss="modal" >&times;</a>
                        <h4 class="modal-title">
                          <p >swiper in modal</p>
                        </h4>
                    </div>
                    <div class="modal-body">
                        <div class="subcontent box-shadow-3" id='test'>
                            <div class="swiper-container">
                                <div class="swiper-wrapper">
                                    <div class="swiper-slide">Slide 1</div>
                                    <div class="swiper-slide">Slide 2</div>
                                    <div class="swiper-slide">Slide 3</div>
                                    <div class="swiper-slide">Slide 4</div>
                                    <div class="swiper-slide">Slide 5</div>
                                    <div class="swiper-slide">Slide 6</div>
                                    <div class="swiper-slide">Slide 7</div>
                                    <div class="swiper-slide">Slide 8</div>
                                    <div class="swiper-slide">Slide 9</div>
                                    <div class="swiper-slide">Slide 10</div>
                                </div>
                                
                                <div class="swiper-button-next"></div>
                                <div class="swiper-button-prev"></div>
                            </div>

```
                    </div>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-success" data-dismiss="modal" >ok</a>
                </div>
            </div>
        </div>
</div>  <!-- end imgsModal modal-->
<!-- Swiper -->
<a data-toggle="modal" href="#myModal" >Modal</a>


<!-- Swiper JS -->

<!-- Initialize Swiper -->
<script>
$(document).ready(function () {  //initialize swiper when document ready     
    var mySwiper = new Swiper ('.swiper-container', {
      //lazyLoading: true,  
      //direction: 'vertical',
      nextButton: '.swiper-button-next',
      prevButton: '.swiper-button-prev',
      loop: true
    })  ;
});
</script>
```

</body>
</html>

**Comment by nolimits4web** [comment]
You need to init Swiper or call its `update` method when it becomes visible. 
Closing as not related to Framework7

**Comment by iamsudharshan** [comment]
@nolimits4web , Hi Vladimir, swiper cube effect is not working in modal pop up. could please help me how to fix this issue. This is how I have initialized swiper.

$$('.open-slider-modal').on('click', function () {
  
   var swiper = new Swiper('.swiper-container');
});

Thanks a lot

**Comment by ZanderBrown** [comment]
Cube effect?

**Comment by iamsudharshan** [comment]
Hi  @zanderbrown, yes, 3d cube transition is not working

**Comment by ZanderBrown** [comment]
Not seeing it in the docs. Got a link?

**Comment by iamsudharshan** [comment]
Hi @zanderBrown, nope

**Comment by ZanderBrown** [comment]
So how is the cube effect supposed to work and why do you think it's supposed to be present

**Comment by iamsudharshan** [comment]
Hi Zander, as per client's requirement I wanted to show swiper 3d cube in pop-up. But swiper cube transition is not working, just working as normal swipe

**Comment by ZanderBrown** [comment]
Right so the docs are [here](http://idangero.us/swiper/api/)
