### ISSUE TITLE
Scrolling page-content on Android is pretty bad :(

### ISSUE THREAD

**Issue by nimeso** [nolimits4web/Framework7#510]
Hey ya! 

I'm loooving Framework 7! Thanks!

My only real grip is the performance when scrolling the page-content area. There is no velocity and elements 'jitter'... some elements get momentarily 'stuck' in the old position but other elements are fine.

HTC One
Android 4.2.1
I'm viewing in the Android browser
example project: http://staging.onefatsheep.com/~vizstage/plattar/view/getHomePage?appid=23

Is there anything I can do to make it better? Any help would  be great as it's holding off 'sign-off' from the client :(

Cheers

**Comment by nolimits4web** [comment]
No, it is Android, and its browser is that what you see. If you are creating Cordova app, then you may use Crosswalk project to replace bad and slow webview with Chrome

**Comment by nimeso** [comment]
@nolimits4web thanks! Unfortunately we are not using Cordova :( We are using Unity 3D with web views... I'll get the Unity developer to do a build and we will see if the scrolling is any better.

Do you have any idea why it scrolls so badly in Android Chrome? Is this a issue I can try and help fix?
The more I use Framework 7 & the more I love it! I don't want to change back to another framework.

I'm happy to pay you for your time to help solve this issue if it is fixable :)

**Comment by boynet** [comment]
@nimeso it could be a lot of things.. do the framework7 kitchen sink also work slow? if not its some problem in your side.. check the chrome devtools timeline panel

**Comment by nolimits4web** [comment]
@nimeso it is a general problem old Androids, i don't that it is possible to do something with it. But in Chrome, as i see, everything is fine

**Comment by evolutionjay** [comment]
Try this greensock.com 's draggable

**Comment by aries1980** [comment]
@nolimits4web I can confirm this issue with the latest Firefox and Chrome too. I ran a FF profiler and the spent most of the time spent on the following (without playing the videos):
- plusone.js (12.4%)
- www-embed-player.js (12.03%)
- html5player (3.64%)

The framework7.js ate just 1.47% of the resources. I think this going to be a Youtube issue.

**Comment by nolimits4web** [comment]
@aries1980 did you test Framework7 website (http://idangero.us/framework7/) or Framework7 itself (http://idangero.us/framework7/), because there are no such scripts in Framework7 itself

**Comment by aries1980** [comment]
@nolimits4web: no, it was in the OP's code: http://staging.onefatsheep.com/~vizstage/plattar/themes/default/framework7/js/framework7.min.js

**Comment by nolimits4web** [comment]
@aries1980 ah, yes, that could also be an issue. But, anyway, overall scrolling performance in Framework7 on Android < 4.4 is not smooth

**Comment by nimeso** [comment]
Wow thanks guys!
I can confirm it's fine in newer browsers :) And yes, the youtube videos
embed don't help. I'm happy with it now so don't spend to much time
investigating.

On Sun, Jun 21, 2015 at 8:18 AM, Vladimir Kharlampidi <
notifications@github.com> wrote:

> @aries1980 <https://github.com/aries1980> ah, yes, that could also be an
> issue. But, anyway, overall scrolling performance in Framework7 on Android
> < 4.4 is not smooth
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nolimits4web/Framework7/issues/510#issuecomment-113817377>
> .
>



-- 
  q-p
 /\"/\
(`=*=') JAMIE BARKER
 ^---^`-._

   P: +64 3 338 2482
   Skype: jam.dog

**Comment by mnill** [comment]
@nimeso
Try to add fastClicks: false in app initialization.var myApp = new Framework7({fastClicks: false, material: true, animateNavBackIcon:true});

**Comment by J05HI** [comment]
@nolimits4web @valnub @ZanderBrown 
Can be closed.
