### ISSUE TITLE
iOS 9 Action Sheet got more rounded

### ISSUE THREAD

**Issue by boynet** [nolimits4web/Framework7#514]
when do you think its the right time to go ios9 ready?
see this screen shots:
ios9 on left:
http://cdn.redmondpie.com/wp-content/uploads/2015/06/1313.png

from here: http://www.redmondpie.com/ios-9-beta-vs-ios-8-visual-differences-compared-screenshots/

or this (ios9 on right):
http://rotter.net/User_files/forum/5581b8675a35691b4.jpg

**Comment by nolimits4web** [comment]
I think that it is a bit early for iOS 9 specific thinks, as it can be changed in next iOS beta :D Let's wait at least for a month

**Comment by nolimits4web** [comment]
already in release
