### ISSUE TITLE
Virtual Listview

### ISSUE THREAD

**Issue by hsmith825** [nolimits4web/Framework7#515]
Newbe to Framework7, old Jquerymobile user.  Will someone give me an example building a list view in javascript.  I have tried to do it with and without Virtual Listview.  Here is my situation:
I have an html page with an empty list view.  I am unable to initialize the list view using the instructions in the documentation.  My list is items are constructed from data base info.  I have tried initializing in the home page init.  I have tried initializing outside the init.  In both cases I get vl.pageContent[0].offsetHeight undefined in framework7.js.

Thanks!

**Comment by nolimits4web** [comment]
If your virtual list is not on home page, then you have to use page callbacks (http://www.idangero.us/framework7/docs/page-callbacks.html) to init it, for example:
```
app.onPageInit('somepage', function(){
  var vl = app.virtualList(...);
});

**Comment by hsmith825** [comment]
Hi Vladimir,

I am having a tough time with Virtual Listview.  I have to use the virtual list view because I am building the list view from a database.  The list view as shown works if it is static.  I will keep the question very simple.  
I have a list view in a file different from called other.html that has the following data:

<div class="pages">
    <div data-page="projects" class="page no-toolbar no-navbar">
        <div class="page-content">
            
            <div class="navbarpages">
                <div class="nav_left_logo"><a href="index.html"><img src="images_mobix/logo.png" alt="" title="" /></a></div>
                <div class="nav_right_button"><a href="#" data-popup=".popup-menu" class="open-popup"><img src="images_mobix/icons/white/menu.png" alt="" title="" /></a></div>
            </div>
            
            <div id="pages_maincontent">
                
                <h2 class="page_title">My Requests</h2>
                <div class="page" data-page="my_requests">
                <div class="page_content">
                    
                    <ul class="features_list_detailed list-block virtual-list">
                        
                        <li>
                            <div class="feat_small_icon"><img src="images_mobix/icons/black/photos.png" alt="" title="" /></div>
                            <div class="feat_small_details">
                                <h4>Photo gallery</h4>
                                <a href="photos.html">Easy create your own photo gallery app. List and full screen options available.</a>
                            </div>
                            <div class="view_more"><a href="photos.html"><img src="images_mobix/load_posts_disabled.png" alt="" title="" /></a></div>
                        </li>
</ul></div></div></div></div></div></div>

On my .js page I have the following relevant code.  I did not include the variables in the template to keep it simple.  I am assuming the result would be a list view with identical items as shown in the template.:
var vl;
$$(document).on('pageInit', function (e) {
                myApp.onPageInit('my_requests', function(){
                                  vl  = myApp.virtualList('.list-block',{                                                                                                                                                                                                                                                                                                                                                                                                                                              template: '<li><div class="feat_small_icon"><img src="images_mobix/icons/black/photos.png" alt="" title="" /></div><div class="feat_small_details"><h4>Photo gallery</h4><a href="photos.html">Easy create your own photo gallery app. List and full screen options available.</a></div><div class="view_more"><a href="photos.html"><img src="images_mobix/load_posts_disabled.png" alt="" title="" /></a></div></li>',
});});});

var format_loans = function() {
        for (facebook_i=0; facebook_i < facebook_objData.length; facebook_i++) {
            rowTemplate += '<li><div class="feat_small_icon"><img src="images_mobix/icons/black/photos.png" alt="" title="" /></div><div class="feat_small_details"><h4>From ' +facebook_objData[facebook_i].loaner_name +' on ' + facebook_objData[facebook_i].create_date +'</h4><a href="photos.html">' +facebook_objData[facebook_i].loan_message +'</a></div><div class="view_more"><a href="photos.html"><img src="images_mobix/load_posts.png" alt="" title="" /></a></div></li>,';
            }
        vl.appendItem(facebook_objData);
};

I am stuck and can not get list views to work that need refreshing such as the one dipicted above.

Any help is appreciated!

Thanks!
Howard
> On Jun 20, 2015, at 4:00 AM, Vladimir Kharlampidi <notifications@github.com> wrote:
> 
> var vl

**Comment by hsmith825** [comment]
Hi Vladimir,

I think I see the light.  Ignore my previous email.

Thanks for your support!!!
Howard
