### ISSUE TITLE
Scroll position ? 

### ISSUE THREAD

**Issue by mesutgok** [nolimits4web/Framework7#519]
Hi,

How to scroll position ? Scroll to css add class not working.

**Comment by nolimits4web** [comment]
What have you tried? It works with:
```
$$('.page-content').scrollTop(100, 600);

**Comment by nolimits4web** [comment]
Closing as no further response/discussion

**Comment by chalchis** [comment]
scroll to specific item

```
var container = $$('.page-content'),
                scrollTo = $$('#item_element');

                //mover scroll posicion, duracion
                container.scrollTop(scrollTo.offset().top - container.offset().top + container.scrollTop(), 600); 
```

**Comment by martinr77** [comment]
Hi,

$$('.page-content').scrollTop(100, 600);

is working in Chrome but with Phonegap there are issues. It scroll to the right position and a second later it scrolls a bit down.

Any idea to fix this?

Thanks

**Comment by Kagiso47** [comment]
Hi, 
how can one achieve this in F7+vue ?
