### ISSUE TITLE
DATETIME PICKER lags on some device

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#524]
Hello,
tried to use the DATETIME PICKER on one of the page .. 

The typing inside the teatarea lags by 4-5 secs, and inline picker rendering is fatal.

Phone ASUS-5

Please assist me for the same.

**Comment by nolimits4web** [comment]
How the textarea related to picker? As for Android, don't use `rotate` effect to improve performance, Android is just slow

**Comment by nolimits4web** [comment]
Closing as no further response/discussion
