### ISSUE TITLE
造成安卓4.4- 滚动卡顿的原因是什么？

### ISSUE THREAD

**Issue by ada90** [nolimits4web/Framework7#525]
f7Plus版其中一项为了解决安卓4.4以下滚动不顺的问题，但是我用了之后，在4.1 4.2 还是卡，
我自己做的无限滚动，不用框架，反而不卡（布局类似，也是在百分百绝对定位div里滚动）。请问造成滚动卡顿的原因是什么？

**Comment by roshanca** [comment]
确定用中文人家看得懂吗 -_-b

**Comment by OpenGG** [comment]
Move this issue to [Framework7-Plus](https://github.com/sdc-fe/Framework7-Plus)
