### ISSUE TITLE
How to change the script in the page header navbar?

### ISSUE THREAD

**Issue by jeka5555** [nolimits4web/Framework7#527]
If you do so: 

$$('.navbar .center').text('bla-bla-bla');

That title is not on the middle. Maybe you can somehow re Init, it would be that he stood on the middle?

**Comment by jeka5555** [comment]
Oh, I have found a solution, cause after changing the title: myApp.reinitPage ();

**Comment by nolimits4web** [comment]
Nope, you have to call `.sizeNavbar` method http://www.idangero.us/framework7/docs/navbar.html#related-app-and-view-methods

**Comment by jeka5555** [comment]
Really. Although visually it works as well as with reinitPage, but apparently does extra actions
