### ISSUE TITLE
Why scroll is not smooth when webapp run in android 4.1 or 4.2?the webapp used Frameworrk7 Plus.

### ISSUE THREAD

**Issue by ada90** [nolimits4web/Framework7#528]
Why scroll is not smooth when webapp run in android 4.1 or 4.2?the webapp used Frameworrk7 Plus.

**Comment by nolimits4web** [comment]
I guess because Android is slow. But anyway, ask this question in Framework7 Plus repo, i am not related to it

**Comment by ada90** [comment]
thx for you answer,but I write a simple demo by myself,the scroll is smooth; Is it proves the reason what makes scroll be not smooth isn't slowly Android?

**Comment by ashokkumar88** [comment]
@ada90 can you please post the code you wrote for smooth scrolling?
