### ISSUE TITLE
Pull to refresh with multitouch

### ISSUE THREAD

**Issue by leecrossley** [nolimits4web/Framework7#529]
When 3 or 4 fingers are placed on the screen where there is the pull to refresh component, the content jumps around:

[Demo here](http://s13.postimg.org/l6u7tzxtx/ptr.gif).

**Comment by nolimits4web** [comment]
Thanks, fixed. It is also possible to follow only last changed touch but i am not sure to bring hundreds of lines of code for that. Now it follows just a first touch, at least much better than jumping content :)

**Comment by leecrossley** [comment]
Looks good - thanks for the quick fix :)

I will try it out shortly and let you know if I have any issues.

**Comment by leecrossley** [comment]
Works like a charm. Thanks again.
