### ISSUE TITLE
Template7 It does not work in index.html

### ISSUE THREAD

**Issue by jeka5555** [nolimits4web/Framework7#530]
Hi!

var myApp = new Framework7({
	template7Pages: true,
	template7Data: {
	    'url:index.html' : {
	        test: '1111',
	    },
	    'url:action.html' : {
	        test: '2222',
	    }
	}
});

When the home page is loaded, the data is output, and line output {{test}} when loaded action.html, then everything is correct. 

How to do that on the main page of the data exchange work?

Thank you for the quick support!

**Comment by nolimits4web** [comment]
Yes, it doesn't work on app init, because F7 doesn't load something. There are a lot of solutions on forums, check them. For example, you may just call `.router.refreshPage` method to reload home page and preprocess it with T7

**Comment by nolimits4web** [comment]
Closing as no further response/discussion

**Comment by snakeman21** [comment]
This doesn't work. Any chance you can provide a practical example of this? I am using ajax content with preprocess.
