### ISSUE TITLE
Prevent overflow on standalone

### ISSUE THREAD

**Issue by jose-carrillo** [nolimits4web/Framework7#533]
I often use the script below to prevent overflow. The script allows for the scrolling element as identified below is the container of the content and is scrollable. The header and footer always stay in place. Is there a way to integrate this with framework7? I realize that fw7 already has some kind of script to prevent overflow but you can still see some degree of overflow.

When I try using the script with fw7, nothing scrolls regardless what div I assign the scrolling to.

function checkDeviceStandAlone() {
	if (window.navigator.standalone == true) {
		var overflow = function(el) {
				el.addEventListener('touchstart', function() {
					var top = el.scrollTop,
						totalScroll = el.scrollHeight,
						currentScroll = top + el.offsetHeight
					if (top === 0) {
						el.scrollTop = 1
					} else if (currentScroll === totalScroll) {
						el.scrollTop = top - 1
					}
				})
				el.addEventListener('touchmove', function(evt) {
					if (el.offsetHeight < el.scrollHeight) evt._isScroller = true
				})
			}
		overflow(document.querySelector('#scrollind-elem'));
		document.body.addEventListener('touchmove', function(evt) {
			if (!evt._isScroller) {
				evt.preventDefault()
			}
		});
	}
}

**Comment by nolimits4web** [comment]
It depends on element where you apply this. In F7 it should be `.page-content`. And make sure you call it when required `.page-content` is in the DOM. Also note, that this trick will not work if page has not much content and it is not scrollable

**Comment by nolimits4web** [comment]
Closing as no further response/discussion and not really related to F7 issue
