### ISSUE TITLE
template7 get data from an array

### ISSUE THREAD

**Issue by jeka5555** [nolimits4web/Framework7#534]
Hello!

there is an array:
var appData = {
    '100' : {
      'title' : 'test1'
    },
    '101' : {
      'title' : 'test2'
    };
template7Data: {
  'page:action' : appData 
  }
} 

Requests a page "action": http://myapp.ru/#!/action.html?id=101
As in the template to get the desired subarray ID, passed in the parameter URL?

I tried different ways:
{{ actions[{{url_query.id}}].title }}
{{ js "appData.actions [url_query.id] .title" }}
{{js "appData.actions[getParameterByName('id')].title"}} // getParameterByName - function parses the URL

But in all cases I get all sorts of errors. Is it possible to somehow dynamically display an array of ID passed in the URL?

**Comment by nolimits4web** [comment]
There is no any `actions` or `appData` variables in your context. And there is no any arrays. You probably should call something like:
```
{{js "return this[url_query.id].title"}}
```
or
```
{{js "return this[this.url_query.id].title"}}

**Comment by nolimits4web** [comment]
Closing as no further response/discussion
