### ISSUE TITLE
Rtl mode, Android 5 animation bug

### ISSUE THREAD

**Issue by shaulhadar** [nolimits4web/Framework7#535]
hello Vlad, I can confirm a bug in rtl mode, when pressing the back transition, the page jumps a bit to the right, and you can see a black area ...this only happened in Android 5 lollipop.

**Comment by nolimits4web** [comment]
Yes, it is. And as I wrote in forum, it is already fixed in dev version

**Comment by shaulhadar** [comment]
thanks Vlad !

**Comment by nolimits4web** [comment]
Fixed in 1.2.0
