### ISSUE TITLE
Template7 auto Auto Compilation Problem

### ISSUE THREAD

**Issue by puny-d** [nolimits4web/Framework7#538]
I have found that Template7 auto compilation only work in index.html, while in other pages.html, it won't works. 
And I read your source code, found that the check function only run once when app init, but I think it maybe run when a page is init, Or you could note it in the document, it would make confusion to user。

Tips: Maybe you could use other mvvm frameworks like angular or vuejs instead of Template7
Links: http://vuejs.org/

**Comment by nolimits4web** [comment]
I thought it should be straightforward. And i don't see much sense to include templates into pages. For this case you may just enable template7Pages and pages will be rendered as templates. Also, browsers don't allow and ignore `<script>` in Ajax loaded content.

As for other frameworks, this is up to developers, i can't integrate there all possible frameworks. I just provided one built-in way. Developers may use other frameworks which they know

**Comment by nolimits4web** [comment]
Closing as no further response/discussion
