### ISSUE TITLE
Zoom problems in photo browser in android

### ISSUE THREAD

**Issue by shaulhadar** [nolimits4web/Framework7#539]
Hi Vlad, I found a bug in the photo browser in Android. when clicking twice and zooming in, I can't click twice to zoom out, it is stuck on the zoomed picture....

thanks for your time,

shaul.

**Comment by nolimits4web** [comment]
Hi, will check it, thanks

**Comment by nolimits4web** [comment]
And what is Android version and browser? As i can't replicate this issue

**Comment by shaulhadar** [comment]
hi vlad, i used android lollipop...
i also exported to crosswalk 14 if it helps...

i checked and saw that it is supposed to work, i dont know why it didnt work for me, maybe its connected to crosswalk?

**Comment by shaulhadar** [comment]
OK, I checked again and it still doesn't work even when I check the kitchen sink online demo as well. I am working with latest Chrome on Android 5 lollipop.

**Comment by nolimits4web** [comment]
Still work for me. Try on another device. It could be device-related issue

**Comment by nolimits4web** [comment]
Closing as duplicate of #671
