### ISSUE TITLE
Hidden status bar on iphone 6 plus

### ISSUE THREAD

**Issue by acadet** [nolimits4web/Framework7#540]
Hi there,

I noticed the status bar (`.statusbar-overlay` div) is hidden on any iPhone 6 Plus. Its `display` property is set to `none` ; the body has no `padding-top` and, obviously, the `views` div has an incorrect height (bigger than expected). 
However, using an iPhone 6, everything is fine. My code is the same on both devices.

Did I miss any configuration?
I have seen [this current issue](#531), but I do not think they are related.

**Comment by nolimits4web** [comment]
Can't see such issue, for example in default demo app:
![statusbar](https://cloud.githubusercontent.com/assets/999588/8763293/a3c54108-2d9d-11e5-9024-d5fcbee0a6e1.png)

**Comment by nolimits4web** [comment]
If use Cordova, make sure that you have correct settings about Status bar

**Comment by acadet** [comment]
Hi Vladimir,

I am not using Cordova but wrapping my HTML & JS app into a UIWebView.

I have just noticed the html root tag does not have the `with-statusbar-overlay` class. Any idea why?

**Comment by nolimits4web** [comment]
It is not a cordova, just an webapp pinned to home screen. Anyway, you can always force to enable it by setting `statusbarOverlay:true` app parameter

**Comment by acadet** [comment]
I did use that parameter. It has no effect.
I tested the rendering on both emulator and real device.

**Comment by acadet** [comment]
I did use that parameter. It had no effect.
I tested the rendering on both emulator and real device.

Here is a screenshot of what I have so far. You can see the overlapping right corner background. Also, I noticed strange paddings/gutters on both vertical sides.

![screen shot 2015-07-20 at 13 48 10](https://cloud.githubusercontent.com/assets/6152745/8786964/23857a68-2ee6-11e5-822a-14cb9101e60e.png)

**Comment by nolimits4web** [comment]
It is not really possible for this parameter to have no effect as it forces to make visible `statusbar-overlay`. Otherwise there is something wrong or conflict in your HTML layout

**Comment by nolimits4web** [comment]
Closing as there is no further discussion and not really replicable
