### ISSUE TITLE
enhancement request - tabs change onswipe

### ISSUE THREAD

**Issue by shaulhadar** [nolimits4web/Framework7#542]
hello vlad, i am checking the great material version.
i would like to make a wish, that you add onswipe built in to change the tabs. currently it is only on click,and in android the tabs usually have the swipe feature.  if there is any chance of you adding this to the  material theme it would be amazing!!

thanks,
shaul.

**Comment by nolimits4web** [comment]
But there is a Swiper for that, no? Just attach its callbacks to switch classes on tab bar buttons

**Comment by shaulhadar** [comment]
that sounds cool, though i admit i do not know how to do this, but i will check and see if i can manage this...

thanks for your help :)

**Comment by nolimits4web** [comment]
```html
<div class="buttons-row">
    <a href="#" class="button my-tab-link active">Slide 1</a>
    <a href="#" class="button my-tab-link">Slide 2</a>
    <a href="#" class="button my-tab-link">Slide 3</a>
</div>

<div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide">....</div>
        <div class="swiper-slide">....</div>
        <div class="swiper-slide">....</div>
    </div>
</div>
```
and example of JS:
```js
var swiper = myApp.swiper('.swiper-container', {
    onSlideChangeStart: function (s) {
        $('.my-tab-link').removeClass('active');
        $('.my-tab-link').eq(s.activeIndex).addClass('active');
    }
});

$('.my-tab-link').on('click', function (e) {
    swiper.slideTo($(this).index();)
});
```

**Comment by shaulhadar** [comment]
Thanks Vlad :)

**Comment by murliatdure** [comment]
:+1:

**Comment by u01jmg3** [comment]
There are now [Swipeable Tabs](http://framework7.io/docs/tabs.html#swipeable-tabs).
