### ISSUE TITLE
Pull up load

### ISSUE THREAD

**Issue by xubing6243** [nolimits4web/Framework7#547]
hi Vladimir !
There are ready to add Pull up load ? now Infinite Scroll It's not very good.

**Comment by nolimits4web** [comment]
No, there is no such feature, as i don't remember i saw such pattern anywhere. And what is wrong with Infinite Scroll?

**Comment by J05HI** [comment]
@nolimits4web @valnub @ZanderBrown 
Can be closed.

**Comment by ZanderBrown** [comment]
@J05HI Why?

**Comment by J05HI** [comment]
@ZanderBrown 
Because there is no pull up to refresh feature. Noone needs that. If he specifically needs that he can develop a plugin.
