### ISSUE TITLE
Gulp Server and Cordova iOS/material Selecting

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#549]
Hi gulp server opens the files now instead of localhost. Did I mess something up?

Also, I noticed that you create the material design stuff, great job. Next you should add blackberry. HAHA jk, no one would use it.

Does the same code work for both? Meaning if I write javascript to load the appropriate css files based on the device that is running the code, would that work?

**Comment by MarcGodard** [comment]
Never mind, I found that they are different. Just want to figure out an easy way to program one code for both platforms.

**Comment by nolimits4web** [comment]
> Hi gulp server opens the files now instead of localhost. Did I mess something up?

Need to update dependancies `npm install`

> Just want to figure out an easy way to program one code for both platforms.

JS should be the same. But not layout, Material has a bit different patterns. You have to change Dynamic navbar with Through-type layout to fixed one by putting it inside of `.page`.

**Comment by MarcGodard** [comment]
The page content stuff is the same? So I can use a template system with 100% the same code?

**Comment by nolimits4web** [comment]
`.navbar` should be inside of `.page`, some form elements are also a bit different, and navbar back link doesn't contain text

**Comment by MarcGodard** [comment]
Ok, but

```HTML
<div class="page-content">
     All content here?
</div>
```

is the same?

**Comment by nolimits4web** [comment]
yes

**Comment by MarcGodard** [comment]
Perfect :) thanks you!

Btw, good work, love it. Is there somewhere I can donate money?

**Comment by nolimits4web** [comment]
Thanks. There is a section on website http://www.idangero.us/framework7/donate/#.VbUpABPtmko

**Comment by MarcGodard** [comment]
You should add a bitcoin address?

**Comment by nolimits4web** [comment]
It is illegal to use in Russia :D

**Comment by MarcGodard** [comment]
Oh. That's unfortunate. :(
