### ISSUE TITLE
Messages auto scrolling problems?

### ISSUE THREAD

**Issue by puny-d** [nolimits4web/Framework7#550]
When I use messages engine to send image, the auto scrolling won't works well, you have refered in in the forum, but how to fix this?

Buy the way, I found if I open Photo Browser in Messages, the scrolling up/down gesture of photo would affect the message content.

**Comment by nolimits4web** [comment]
Because it need time to load image to detect its size. You may fix image size in messages in CSS to make it work

> Buy the way, I found if I open Photo Browser in Messages, the scrolling up/down gesture of photo would affect the message content.

It is iOS bug with overflow, it scrolls scrollable content behind the layer. You may add `overflow:hidden` to messages content when you open PB, using callback for example

**Comment by puny-d** [comment]
Thank you very much!

**Comment by boynet** [comment]
>It is iOS bug with overflow, it scrolls scrollable content behind the layer. You may add overflow:hidden to messages content when you open PB, using callback for example

I think it will be nice to add some section like bootsrap have (http://getbootstrap.com/getting-started/#support) with this little tips like you gave to solve this little bugs

**Comment by ZanderBrown** [comment]
Can this be closed
