### ISSUE TITLE
[Material] Ripple effect on tabs adds up

### ISSUE THREAD

**Issue by KLVN** [nolimits4web/Framework7#552]
Here's a video demonstration: https://dl.dropboxusercontent.com/u/31870855/Forum/fw7_tabbug.mp4

Samsung Galaxy S4
Android: 5.0.1
Chrome: 43.0.2357.93

**Comment by KLVN** [comment]
Vladimir you're amazingly fast :D

**Comment by ahmadramadan** [comment]
should I add any js code ?
because I have the same problem and I'm using the latest version 

thanks :)

**Comment by Symorp** [comment]
Hello i didnt saw your video, but i guess i have same problem ripple wave is adding so many ripple waves divs, so i write this:

$(document).on('click','a', function () {

    //define link
    var link = $(this);

    //put link in timetout context, we need wait 1400 ms until animation finish then we can start animation to hide ripple effect
    setTimeout(function (link_a) {
        return function () {
            //we find all ripples -> for each of them we start hide animation -> then we need to wait another 1400 ms until finish application
            link_a.find(".ripple-wave").each(function (index, ripple) {
                $(ripple).css('opacity', 0);

                setTimeout(function (ripple) {
                    return function () {
                        $(ripple).remove();
                    }
                }(ripple), 1400);

            })
        }
    }(link), 1400);
});
