### ISSUE TITLE
Date Picker - Defect

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#555]
Unable to clear the value of the component.. If picker open can't close/reset . so looking for the RESET Button and/or custom fields extensions options with callback function support.

Thanks,

**Comment by nolimits4web** [comment]
Sorry, don't understand what do you mean. Can you explain it more detailed and what have you tried?

**Comment by murliatdure** [comment]
Hello,
Would like to have the CLEAR feature on DATA Picker Component.

![image](https://cloud.githubusercontent.com/assets/7137859/9026645/25b41c04-3954-11e5-8752-ff47504aae74.png)

**Comment by nolimits4web** [comment]
I will consider it, but it should be done without a hassle manually using Calendar API

**Comment by murliatdure** [comment]
can u pls share teh calendar API link, I can't find in docs.
Thanks alot.

**Comment by nolimits4web** [comment]
http://www.idangero.us/framework7/docs/calendar.html

**Comment by murliatdure** [comment]
Thanks
