### ISSUE TITLE
I just discovered your frameword 7

### ISSUE THREAD

**Issue by chalchis** [nolimits4web/Framework7#556]
hello
I just discovered your frameword 7
It is very beautiful that you have created

I have just one question
Where I can see how to apply the events in the documentation?
and

Where I can see where some js code
validate fields, add data .... etc ?

excuse my doubts
I come to use much jquery

greetings

**Comment by nolimits4web** [comment]
> Where I can see how to apply the events in the documentation?

The same as in jQuery, using jQuery or built in lib http://www.idangero.us/framework7/docs/dom.html

> Where I can see where some js code, validate fields, add data .... etc ?

On the web, they will be the same as for jQuery. There is no specific things for F7

P.S. It is better to use Forum for question. GitHub is for issues

**Comment by chalchis** [comment]
thank you very much
for some reason
could not see the documentation of the comprehensively framework

thank you very much
and great framework
