### ISSUE TITLE
Material Forms with Data Store

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#559]
Using the data store with material floating-label causes a problem as the label doesn't float when it fills in the data.

**Comment by nolimits4web** [comment]
Fixed, thanks

**Comment by MarcGodard** [comment]
I just pulled and tested. The data doesn't show up now.

**Comment by nolimits4web** [comment]
Sorry but this commit doesn't change anything about data. And as i tested everything works for me

**Comment by MarcGodard** [comment]
I have duplicated ios and material code. The data store worked in both but the labels in material was overlapping. Now the ios one still works but the data doesn't show up in the material input.

I will investigate more, but something is going on to make it not work now.

**Comment by MarcGodard** [comment]
My bad. I figured it out. Sorry that I doubted you. My bad *bows to you* Thanks for everything.

**Comment by ardabeyazoglu** [comment]
I've just tested this with version 1.5.3, and it doesnt work again. When i use app.**formFromData** method in a material form, the floating labels do not float.
You can see here : http://prntscr.com/e8mf6b
