### ISSUE TITLE
FM7 doen't work on Safari browser

### ISSUE THREAD

**Issue by Leon-Kennedy** [nolimits4web/Framework7#560]
Hi,
I have a problem with FM7 when run on safari brower. This is error: 
"framework7.min.js:49 EvalError: The "this" value passed to eval must be the global object from which eval originated"

I tested my website with Firefox, Chrome, IE, FM7 worked well, but Safari is not. 
My Safari browser's version is 5.1.7 and FM7's version is  1.2.0. Any solution for this problem ?

**Comment by nolimits4web** [comment]
Sorry, Safari 5 is very old and outdated browser. It is not supported
