### ISSUE TITLE
F7 and AngularJS

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#561]
Hello,
I know I am talking about totally different world .. of aNGular-js.

I know I am dealing with one of the best Hybrid Framework (Framework7). 
I tried to compare other market options.. I came across with OnsenUI ... which uses angularJS as base.. and as a core features of the angular (2 way data binding), makes life more easier etc.
It would be awesome 2 get advantage of best of the two worlds.. would be awesome development life .. to have that.

I tried to integrate the same .. It was successful.. I m getting the $scope of angular into F7 index page.
But on the fragmented pages it doesn't work. $scope is undefined.

If you can intercept/hook some idea for the same.. would be a awesome feature.

Looking forward for your comments.
Thanks for serving the best till time.

Some references: https://github.com/darlinglele/mobile-app-seed

**Comment by nolimits4web** [comment]
I am not too familiar with Angular, but there are a lot of solutions on the web

#35

https://github.com/valnub/Framework7-Pure-Angular-Template

Closing as non the F7 issue
