### ISSUE TITLE
Responsive Helper Classes

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#562]
Hello,

I seen col-50 -- which works awesome.

Can we have the (using media queries etc). device dependent helper classes.. something like what bootstrap does.

col-lg-50 (Large), col-md-50 (Medium), col-sm-50 (Small),  and col-xs-50 (Extra Small)..

Thanks,

**Comment by nolimits4web** [comment]
There is a helper `tablet-` classes http://www.idangero.us/framework7/docs/grid.html#.Vb49cpPtmko

Please, use Forum for questions
