### ISSUE TITLE
Android  - status bar

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#563]
On iOS we are getting the status bar.. But on Android we are not getting the same.
Any solution/workaround on the same.

**Comment by murliatdure** [comment]
http://3.bp.blogspot.com/-sP-FZy8_QFI/VI9bDn6U53I/AAAAAAAAArg/tGroorElsIU/s1600/app%2Bbar%2Bwithout%2Bname.png

Awesome to have something like that.

**Comment by murliatdure** [comment]
![image](https://cloud.githubusercontent.com/assets/7137859/9026748/ec8cbe68-3958-11e5-8ff0-f4c215e68f4e.png)

assets/7137859/9026748/ec8cbe68-3958-11e5-8ff0-f4c215e68f4e.png)

**Comment by nolimits4web** [comment]
For app https://github.com/apache/cordova-plugin-statusbar
For web https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android

Use Forum for questions

**Comment by murliatdure** [comment]
Cordova plugin doesn't support on android :-1: 

![image](https://cloud.githubusercontent.com/assets/7137859/9078104/a68b4648-3b54-11e5-9f3e-37ae0cd8367e.png)

**Comment by adaniello** [comment]
Not all features are supported, but some yes. Eg backgroundColorByName and backgroundColorByHexString works well but only on Android 5+: Android 5.0 Lollipop introduced Material Design theme which automatically colors the status bar based on the ColorPrimaryDark value of the theme, before it's established by the theme the phone has.
