### ISSUE TITLE
Picker for Keyboard Spacer *Small Feature Request*

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#565]
Is it possible to use your picker code to add space and scroll for when a cordova keyboard is used and opened?

Perhaps this:

``` JavaScript
var keyboardPicker = myApp.picker({
  input: '.keyboard-picker',
  visible: 'false',
  height: 255
});
```

This way the page will scroll and position itself nicely for when cordova and a keyboard is used.

Also, if visible is false, you should be able to type in the input fields.

What do you think?

**Comment by nolimits4web** [comment]
Sorry, i don't see much sense it - to use picker without picker :) You can just reuse some of the code part when keyboard became opened to add additional padding to page and scroll it https://github.com/nolimits4web/Framework7/blob/master/src/js/picker.js#L437-L458

**Comment by ZanderBrown** [comment]
Can this be closed?
