### ISSUE TITLE
When hide navbar on scroll, searchbar doesn't move to top

### ISSUE THREAD

**Issue by Leon-Kennedy** [nolimits4web/Framework7#566]
Hi,
I refer searchbar & hide bars on scroll example at http://www.idangero.us/framework7 to implement my website.
When i scroll, navbar hide but search bar doesn't move to top. So layout look bad at that time.

I also refer DOM7 library but i don't find any event which fires when navbar hidden.
Any idea for moving searchbar to top when navbar hidden ?

**Comment by nolimits4web** [comment]
In this case you should put it inside of subnavbar

**Comment by Leon-Kennedy** [comment]
Thank for your reply, it helped me to resolve my problem
