### ISSUE TITLE
Multi select and active state

### ISSUE THREAD

**Issue by MarcGodard** [nolimits4web/Framework7#567]
When you have a list of links and you do multi touch, one of the links becomes active, the 2nd touch eliminates the removal of the active state, leaving the active class and link shaded. 

Is there an easy way to eliminate this problem? Maybe detect 2nd touch and remove all active states?

**Comment by MarcGodard** [comment]
@nolimits4web IS this possible? Do you have anything to detect multi-touch?

**Comment by nolimits4web** [comment]
Sorry, missed this issue for some reason. Should be fixed now
