### ISSUE TITLE
virtual listview is not working on windows phone

### ISSUE THREAD

**Issue by AdrianV** [nolimits4web/Framework7#568]
I know windows phone is not supported, but anyway I tried :)
the virtual listview on windows phone 10, but it doesn't load the items at the end of the screen.
Any idea what I can do to get it work ?

**Comment by nolimits4web** [comment]
Sorry, have no idea what happens on windows phone. Maybe you see any errors in console?

**Comment by AdrianV** [comment]
I did some test and come so far, that this is not a problem of Framework7. Virtual Listview works on windows phone, when used in a cordova universal app. When used in a cordova windows phone 8 app they don't work, and other things like swipe to delete don't work either in wp8 because the webview eats up some of swipe events and handles them itself. I am searching now for a solution for this.

**Comment by nolimits4web** [comment]
Closing is seems to be not F7-related issue. Reopen if you found out it is F7-related
