### ISSUE TITLE
Lazy Load not working for hidden tabs.

### ISSUE THREAD

**Issue by jasonswan** [nolimits4web/Framework7#569]
When you have a media list inside two tabs, the tab thats hidden (despite still being display:none by default), every single image in the hidden tab will be loaded, not even just the ones in viewport.

**Comment by nolimits4web** [comment]
Do you use Lazy Load on it or you have usual media list there?

**Comment by jasonswan** [comment]
I have two tabs, both with a media list, the media list img's have class="lazy" on them, the lazy loading works fine for the defaulted open tab, but the hidden tab, it will load *all* the images even though the tab is hidden and not in viewport.

**Comment by jasonswan** [comment]
If F7 could have a :hidden selector like jquery, this would be easily fixable with something pseudo like:

`if ($e.is(":hidden")) return;`

Would detect if any of ancestor elements are hidden.

**Comment by nolimits4web** [comment]
Ok, should be fixed now in dev version
