### ISSUE TITLE
html-layout android and ios should stay the same

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Framework7#570]
Hello, I like the android-theme. Really good work! 

However, According to http://www.idangero.us/framework7/docs/app-layout.html#.VcHRpLfYBE4, html-layout is different for android and ios. 

It would be nice, if html-layout for both can be the same, so only css-files is to change. 

Html-Layout should not be affected by css. Imagine, developing for both platforms, actually I need to have different html-files.

**Comment by MarcGodard** [comment]
This is not possible without some serious re-writing (I have looked into it).

However, using any sort of MVC model should fix this. I use the templates7 and the only thing I change is the index file to go back and forth between ios and android. Works well for what it is.

**Comment by nolimits4web** [comment]
These themes use different patterns and logic in many places, it is not just colors and sizes, so yes, it is impossible. This may help you http://www.idangero.us/framework7/tutorials/maintain-both-ios-and-material-themes-in-single-app.html
