### ISSUE TITLE
Material icons via Google Web Fonts and badges not working as expected

### ISSUE THREAD

**Issue by gtorodelvalle** [nolimits4web/Framework7#573]
I noticed that using material icons via Google Web Fonts with badges does not work.
I mean linking Google Web Fonts for material icons:
```html
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
```
and using them as indicated in Google's documentation (see https://google.github.io/material-design-icons/#icon-font-for-the-web):
```html
<i class="material-icons">face</i>
```
Which in the case of Framework7 I guess it should look like something such as:
```html
<i class="icon material-icons">face<span class="badges bd-red">5</span></i>
```
(notice the `icon` and `material-icons` classes)
Using it this way will just not show the "5" text (the badge will appear "empty").

The problem is with the `font-family` the Google Web Fonts for material icons sets.

To fix it I included a piece of style for my app such as the following:
```css
.material-icons .badge {
    font-family: Roboto, Noto, Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: initial;
}
```
to get the same look and feel as with the icons included in Framework7.

I didn't want to send a pull request to discuss with you the best approach to solve the issue, just in case you may find a better one :)

**Comment by nolimits4web** [comment]
I guess you can use something like this:
```
<i class="icon"><span class="material-icons">face</span><span class="badges bd-red">5</span></i>

**Comment by nolimits4web** [comment]
Closing as there is no further discussion
