### ISSUE TITLE
Can we open the page as POPUP?

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#579]
Although we can put the structure as PAGE inside popup will work.
I am looking for something where the same contents should work as POPUP and PAGE as well via API support.

**Comment by nolimits4web** [comment]
Not by default, but it is not hard to do this using API, for example:
```
$.get('somepage.html', function(data){
  myApp.popup('<div class="popup">' + data + '</div>')
});

**Comment by murliatdure** [comment]
Aweosme .. Thanks

**Comment by murliatdure** [comment]
Can we have the F7 solution - where we can use .. 
- Template7
- Inline Pages

etc..

**Comment by murliatdure** [comment]
Hey, Thanks, Tried the following snapcode and achieved what I was looking for - 

$.get('fragments/case-info.html', function(data) {            
            var compiled = Template7.compile(data)
            application.popup('<div class="popup tablet-fullscreen">' + compiled(context) + '</div>');
        });
