### ISSUE TITLE
css class set to black instead of transparent and strange white lines on the right side

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Framework7#581]
f7 has set background:#fff in .pages css-class. Should be set to transparent. In Safari browser this leads to strange black line at the right side..

And the navbar has a white line at the right side on safari browser. You can see it if you change the color to black on .navbar-class. For this, I cannot find the reason in f7-css..

**Comment by nimo23** [comment]
For the second case, I found the reason. When I route from index to about then on the left side of the about-page the strange white line comes from the underlined index-page which is covered by about-page due to its page property:
-webkit-transform: translate3d(-165px, 0, 0);
opacity: 0.9138686131386862;

However, when decreasing the number of 165px the white line (which is the index-page), then index-page will be covered full by about-page.

Actually, in Safari when I route from p1 to p2, then p1 is not fully hidden (thus, the strange lines at the left side)..

**Comment by nolimits4web** [comment]
Sorry, i can't see such issue. Do you have a link where i can see such issue?

**Comment by nimo23** [comment]
Forget it. The reason was because of a slide which was not complete and views the background-layer-view.
