### ISSUE TITLE
change "width" of  ".buttons-row .button" to "auto"

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Framework7#582]
Actually in f7 this css-property

 .buttons-row .button{
	width: 100%;
}

leads in safari to cutted buttons (when using button-row).

Changing this to 

  .buttons-row .button{
	width: auto;
}

solves the problem. Other browsers will not be affected by the change.

**Comment by nolimits4web** [comment]
No, sorry. According to guidelines (and you may see it any native app) buttons in button row should be the equal size. If you need such solution for your app, just add mentioned css to your app css, but not for everyone
