### ISSUE TITLE
align back-button and "Back" test to middle

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Framework7#583]
Actually, the back-button and the text "Back" is not as a whole aligned to center - the look can be better, if back-button and "Back"-Text are really aligned to middle. You can try it yourself: 
set "padding-top: 2px;" of ".navbar a.link span" inf F7.css to the "Back"-Text-Element and it looks a bit better as now.

**Comment by nolimits4web** [comment]
Sorry, according to styles this is centred and depend on browser implementation. In iOS i see it 100% match which is enough for me to leave it like it is not:
![s](https://cloud.githubusercontent.com/assets/999588/9292888/45781fca-4419-11e5-81ab-b513fad5060b.jpg)

The first navbar is from native Settings app, and the second one is from F7. The only difference i see is the size if icon, on native app it is a little bit larger
