### ISSUE TITLE
Issue with Pull-to-refresh and on-screen keyboard on iOS, PTR gets stuck

### ISSUE THREAD

**Issue by lexaux** [nolimits4web/Framework7#586]
Hi All! 

Thanks for the great framework; it seems to rocket web development for devices, especially fro hybrid apps. 

So the issue for me is as follows: 
1. On iOS 8 (also checked with iOS7, same resutls), we have a pull-to-refresh panel with the input (textbox) on it. 
2. When that input is focused, the on-screen keyboard is shown. 
3. After that, while the keyboard is shown, if I pull the panel down, it just gets stuck (no 'release' really happens), the arrow stays visible. 
   1. However, there's certain threshold to make this happen. 

I have actually wrapped in the simplest possible cordova container one of the demo apps - Hackers news - which features this issue, to see how it behaves. And here is screen recording from it: https://dl.dropboxusercontent.com/u/18312907/framework7_issue_webview_scroll.mov

Would appreciate any help regarding the issue!

Cheers,
Alex.

**Comment by lexaux** [comment]
Done some additional research. 

This is a well-known behavior in the desktop world - basically what happens is that Pull-to-refresh relies on 3 events to operate - touchStart, touchMove and touchEnd. 

In our case, when the keyboard is shown, and user drags an ample distance, the touchEnd event is not received (since touchEnd happens on the keyboard, and not our web view). 

Any ideas how we could fix this? I was thinking of 2 approaches: 

1. Ugly: add a timer, if PTR initiated, collapse it in .5 seconds. Should be really annoying to end users. 
2. Better: somehow detect the webview has lost touch, and either throw in touchEnd or handle it separately. 

Thanks!

**Comment by ZanderBrown** [comment]
What's the status of this?

**Comment by nolimits4web** [comment]
Let's close it for now as there is no more reports about it
