### ISSUE TITLE
.item-after doesn't align correctly on Firefox

### ISSUE THREAD

**Issue by JamesLefrere** [nolimits4web/Framework7#587]
![screen shot 2015-08-17 at 17 46 57](https://cloud.githubusercontent.com/assets/5450382/9309155/1dc8735e-4508-11e5-9c9e-f0a6d78e567f.png)

It seems as if the :after style used for the border between list items causes Firefox to incorrectly justify the content in .item-inner. If the :after style is switched off, .item-after text is aligned properly. I'm not sure what the best solution would be.

**Comment by nolimits4web** [comment]
Sorry, don't know either how to fix it, it is a long playing FireFox issue. The only fix here will be remove those `:after` borders and replace them with plain CSS `border`

**Comment by nolimits4web** [comment]
You know, you can add the following CSS rule:
```
.list-block .item-title {
  width: 100%;
}
```
But i am not sure that it will not break something else

**Comment by JamesLefrere** [comment]
Ah I see, yes, do you know the issue for that bug? I can't find it with the search. 

Thanks for the suggestion, but I'm afraid it causes a few other problems; it may help for some though, since it depends on the markup.

**Comment by nolimits4web** [comment]
Just google `firefox position absolute in flexbox` some of the first results lead to FF issues
