### ISSUE TITLE
When you open a little the panel (swipe) and close that. The events close/closed on the panel no triggered.

### ISSUE THREAD

**Issue by pato12** [nolimits4web/Framework7#589]
Hi!

When you open a little the panel (swipe) and close that. The events close/closed on the panel no triggered.

My code:
`    $$(document).on('open', '.panel-left', function () {
		console.log('open');
	});
	$$(document).on('close', '.panel-left', function () {
		console.log('close');
	});
	$$(document).on('opened', '.panel-left', function () {
		console.log('opened');
	});
	$$(document).on('closed', '.panel-left', function () {
		console.log('closed');
	});
`

Without open
![without open](https://cloud.githubusercontent.com/assets/1323180/9314826/cccc037c-4501-11e5-8f30-bed2bd7dc041.png)

Little open
![little open](https://cloud.githubusercontent.com/assets/1323180/9314827/cccf58ec-4501-11e5-8102-b6cee7851055.png)

And closed
![and close](https://cloud.githubusercontent.com/assets/1323180/9314828/ccd190f8-4501-11e5-942a-f71e94d87483.png)

Open panel, triggered the events
![open panel](https://cloud.githubusercontent.com/assets/1323180/9314829/ccd4eb7c-4501-11e5-9399-983c9ed1bed2.png)

This lines, call to open/close panel and trigger the event, but the panel is ".active" or not, and the functions not continue.
![lines](https://cloud.githubusercontent.com/assets/1323180/9314962/9e981166-4502-11e5-8829-0fc73e45b807.png)

Sorry for my english.

**Comment by nolimits4web** [comment]
Yes, in this case panel doesn't trigger any events because state of the panel wasn't changed
