### ISSUE TITLE
Tab bar flickering after back animation ("no-tabbar")

### ISSUE THREAD

**Issue by tonkado** [nolimits4web/Framework7#590]
I faced an issue with flickering interface after back animation.
Here is the sample video:
https://youtu.be/jY5e30yZxzY?t=25

It only happens with "no-tabbar" option.
I would appreciate any suggestions.

P.S.: video recorded on iPhone 5s (cordova+Framework7 app)

**Comment by nolimits4web** [comment]
Do you change CSS `overflow` property on something?

**Comment by tonkado** [comment]
I didn't made any changes to CSS.
I found this issue in my app and then I made a new app from "clean" tab-bar example. I just add class to change navbar colour.

The problem occur only if "no-tabbar" option is enabled.
It's not visible in desktop browser, only on real device in PhoneGap app (http://app.phonegap.com/) or in compiled iOS app.

**Comment by nolimits4web** [comment]
Ok, i will check it more deeply on this weekend

**Comment by tonkado** [comment]
Here is Phonegap project that I used in video for testing:
https://yadi.sk/d/loUgGpXLihLqK

**Comment by MarcGodard** [comment]
This is the same issue I reported before. However the thread was changed into a shadow issue. 

I added a bunch of information on the cause to that other thread. I assume you are using Cordova and phone gap and even safari I have seen this. 

If I was at my computer I would link or copy the info I had found. 

It has to do with the height of the window not being 100% and the over scroll being added and removed by the web UI or by safari. Whenever the overflow scroll is added or removed there is a flash. 

The only solution I can think of trying (been busy and haven't tried it yet) is to have the page content be 100% plus 1 pixel so the over scroll stays on the page.

**Comment by nolimits4web** [comment]
Ok, finally had time to take a look at this. The solution of this particular issue is simple, just add this rule to your CSS:
```css
.views {
  overflow: hidden;
}

**Comment by tonkado** [comment]
Thanks for the solution!
I really appreciate your feedback.

By the way I already find some workaround:

    myApp.onPageBeforeAnimation('player', function(page) {
        $(".toolbar.tabbar").hide();
    });

    myApp.onPageBack('player', function(page) {
        $(".toolbar.tabbar").show();
    });

But CSS way it's definately better :)
