### ISSUE TITLE
Swipeout animation glitch on Chrome (44.0.2403.107)

### ISSUE THREAD

**Issue by JamesLefrere** [nolimits4web/Framework7#592]
We have observed in testing that swipeouts on Chrome are sometimes causing a strange animation glitch. It's fine in Safari, but oddly enough Chrome glitches out in some instances but not all. This can be observed in the kitchen sink example; see the video here for a recording of the issue: https://vid.me/0FWg 

It's quite hard to debug; slowing the animations down in devtools doesn't allow the issue to be reproduced, so I'm not sure quite which part of the CSS is causing the problem.

**Comment by nolimits4web** [comment]
It is on desktop on on mobile device?

**Comment by nolimits4web** [comment]
Ok, see the issue, will check it

**Comment by murliatdure** [comment]
On mobile, for the lists with Swipe-options gets hide, If I click again that displays; seems to be a rendering issue only with the swipe-options list/media list.

**Comment by nolimits4web** [comment]
It is already fixed in dev version

**Comment by murliatdure** [comment]
mostly the list gets blank and once tap it rerenders. It happens frequently with the Tabs and Swipeout panels. Can you please share a quick fix..

**Comment by nolimits4web** [comment]
Closing as fixed
