### ISSUE TITLE
Virtual List run on Android has no item sep line

### ISSUE THREAD

**Issue by yejianhui** [nolimits4web/Framework7#593]
![screenshot 2015-08-19 6 43 30](https://cloud.githubusercontent.com/assets/63774/9360486/083bb880-46c9-11e5-8a39-e7f7e4596fb7.png)
Before 1.2 is OK, but I upgrade to 1.2 the VList item sep line gone.

**Comment by nolimits4web** [comment]
Real device or emulator?

**Comment by yejianhui** [comment]
Real device

**Comment by nolimits4web** [comment]
Do you still have this issue?
