### ISSUE TITLE
Titles overlap

### ISSUE THREAD

**Issue by davidqdr** [nolimits4web/Framework7#595]
![screenshotframework7](https://cloud.githubusercontent.com/assets/5203985/9423289/2797f5f6-48b6-11e5-8249-2f917c8fbdc8.png)
**************************************************
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <title>My App</title>
    
    <link rel="stylesheet" href="css/framework7.material.min.css">
    
    <link rel="stylesheet" href="css/my-app.css">
  </head>
**************************************************
Chrome (44.0.2403.133) for android (5.1.1) Nexus 5 Build/LMY48I Javascript version V8.4.4.63.25
**************************************************
Link: http://smarq.es/examples/frame7/

**Comment by nolimits4web** [comment]
Use "Fixed" layout type for navbars (http://www.idangero.us/framework7/docs/navbar-toolbar-layouts.html#fixed-layout) in Material theme and disable dynamicNavbar

**Comment by alketcecaj12** [comment]
I have the same problem but your answer is so implicit and doesn't allow for comprehension ? What do you mean exacly ?

**Comment by eduardoalvara2** [comment]
I am having the same problem, and I don't understand the answer of nolimits4web.

Where I disable the dynamicNavbar?

**Comment by alketcecaj12** [comment]
Here yo find a working example on how to overcome the problem https://stackoverflow.com/questions/47157985/how-can-i-avoid-the-overlap-that-happens-in-framework7-between-the-navbars-when/47164698?noredirect=1#comment81473667_47164698

**Comment by eduardoalvara2** [comment]
Thank you alketcecaj12!, 

Besides your link, for reference I add [this tutorial from Framework7](https://framework7.io/tutorials/maintain-both-ios-and-material-themes-in-single-app.html), that would be useful to see the diferences between iOS and Material
