### ISSUE TITLE
Pull-to-refresh stuck after pulling again when preloader is shown

### ISSUE THREAD

**Issue by lexaux** [nolimits4web/Framework7#599]
Hi! 

I'm having issues again with PTR. At this time, however, seem to have them fixed easily - please see https://github.com/Logicify/Framework7/commit/4108f97df52c98dbb26854d2f4883596941503d1 for the proposed fix, I'll create pull request if that's a good idea. 

Generally, steps to reproduce. I'm running it off Cordova, however I was able to gain same behavior in safari (all on OS X 8): 

1. Open http://guillaumebiton.github.io/HackerNews7/ nice test application
1. Pull the whole thing to refresh, release so that preloader is shown 
1. While the preloader is spinning, pull aga with a long gesture (almost to the bottom of the screen) and wait till preload finishes.
1. Once preloader finished spinning, `.pull-to-refresh-layer` is visible, and the whole view is stuck somewhere mid-screen with `translate` applied to it. 

Please see illustrative video for details https://www.dropbox.com/s/wm2o3d3lo1mxd3j/issue_with_ptr_2.mov?dl=0

Cheers,
Alex.

**Comment by nolimits4web** [comment]
Your fix is ok :+1: , waiting for PR
