### ISSUE TITLE
Focus jump on next input element (on "pinned to Home" and Cordova/Phonegap apps)

### ISSUE THREAD

**Issue by marcopesce** [nolimits4web/Framework7#600]
Tapping on an input field result on cursor moving (and focusing) on another field.

You can replicate this bug on "Kitchen Sink demo". If you choose the "Form Storage" demo section (from "Forms" menu) and try to click on "Name" input field, the selected item will be "Phone" (or one of the following items). It seem that this bug has something to do with the scrolling of the pane content, because if you try the same test on the "Form Elements" demo section you will not get the jump until you try to click on the input fields that require a scroll of the pane content (like "Password" or "Phone"). This will not happen every time but only if you "tap" normally: if you tap really fast you will not get the bug.

This bug is not present if you open the app from Safari.

My configuration: iPhone 6 Plus, pinned to Home app, iOS 8.4

**Comment by marcopesce** [comment]
This bug seem to affect also the cordova/phonegap version (tried on a published app)

**Comment by marcopesce** [comment]
Tried on iPad 2 with iOS 7.1.2: same problem.

**Comment by marcopesce** [comment]
UPDATE: the issue is present on all iOS device, web app (pinned on home) or PhoneGap.

**Comment by nolimits4web** [comment]
Can you make a video of this issue, as i can't really replicate it?

**Comment by marcopesce** [comment]
Here you are:   http://www.youtube.com/watch?v=dlaJoIYUQM0

**Comment by marcopesce** [comment]
An additional video with jump on not focusable input element, with weird beaviour:

http://www.youtube.com/watch?v=XP39GTk3ahs

**Comment by nolimits4web** [comment]
Ok, now i see the issue. Will try to figure out problem

**Comment by marcopesce** [comment]
some more experiment: if the issue does not show immediately on a specific session (app just restarted after closing) then it will not show during the whole session and viceversa.

**Comment by marcopesce** [comment]
Update: disabling "Fastclick" (fastClicks: false) fix the problem but introduce new issues on menu/side panel that can't be closed (to close it you need to select one of the options)

**Comment by nolimits4web** [comment]
It took time to figure out where this damned issue was. Now seems to be fixed

**Comment by Floky87** [comment]
I also have this issue. My device: iPhone 5c with iOS 9.1. I use Cordova 5.3.3.

**Comment by nolimits4web** [comment]
@Floky87 try to use WKWebView plugin

**Comment by Floky87** [comment]
Sorry, used outdated F7 version. In 1.4.0 problem is solved.

**Comment by marcopesce** [comment]
With the current version of the framework the issue is back
