### ISSUE TITLE
IOS8 photo-browser 长图片问题

### ISSUE THREAD

**Issue by AngryCrotch** [nolimits4web/Framework7#602]
长图片无法使用滚动。 我测试的图片规格是 400*4500

**Comment by nolimits4web** [comment]
Will be good to see this in English

**Comment by AngryCrotch** [comment]
While long images can not be used to scroll. I test the picture specification is 400*4500

**Comment by AngryCrotch** [comment]
photo browser plugin

**Comment by nolimits4web** [comment]
Ok, will check it

**Comment by nolimits4web** [comment]
I guess it is not actual anymore and i couldn't replicate it
