### ISSUE TITLE
CSS issue since 1.2.0

### ISSUE THREAD

**Issue by GuillaumeBiton** [nolimits4web/Framework7#603]
I have updated HackerNews7 with F7 1.2.0. After that, the "Back" link in navbar as changed. The icon is blue not white anymore, and the white color apply on .navbar class only applies on title not on the text in le .left div ?

**Comment by nolimits4web** [comment]
Hi,
All colour related styles are moved to the separate additional `framework7.ios.colors.min.css` file, so just include this stylesheet after main F7 stylesheet

**Comment by GuillaumeBiton** [comment]
Sorry I didn't notice that in the changelog. Thanks the issue is fix.
