### ISSUE TITLE
[Feature Requiest] Material new UI and Transitions

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#604]
Any plans for the material ui more components and transitions effects, as library is stable and almost there for next phase of effect -
http://stackoverflow.com/questions/20823671/google-profile-like-scrolling-effect

**Comment by nolimits4web** [comment]
Yes, there are plans for something like new page transition, but later

**Comment by 7aduta** [comment]
+1

**Comment by shaulhadar** [comment]
can be an awesome addition to an awesome framework :)

**Comment by murliatdure** [comment]
![image](https://cloud.githubusercontent.com/assets/7137859/10714474/c461e9cc-7b16-11e5-9226-0a7e9754c4f5.png)


![image](https://cloud.githubusercontent.com/assets/7137859/10714480/0b713854-7b17-11e5-9b3a-5ca07fb720d5.png)

**Comment by murliatdure** [comment]
https://github.com/saulmm/Android-Material-Examples

![image](https://camo.githubusercontent.com/c3e790f0f32002d54ac498927ca1aeb36ebc7d9b/68747470733a2f2f6c68342e676f6f676c6575736572636f6e74656e742e636f6d2f2d646d44466f4637633555592f564437374e73464b386b492f4141414141414141754c4d2f4d74537150384a6f51636f2f773238322d683439392d6e6f2f323031342d31302d313625324230305f35315f33342e676966)


![image](https://camo.githubusercontent.com/82a4ee22be3278ebef4241ebbd8eb9443c3f003d/68747470733a2f2f6c68362e676f6f676c6575736572636f6e74656e742e636f6d2f2d65636f5751656a4c6d46452f5645426f526f3351735f492f41414141414141417554552f595a37383535476d4f66772f773237362d683439382d6e6f2f6170706561722e676966)

![image](https://camo.githubusercontent.com/82497b070232deae261241b28ca058173bfa4ba4/68747470733a2f2f6c68352e676f6f676c6575736572636f6e74656e742e636f6d2f2d4e2d306152456e7444644d2f564576503449356b7872492f41414141414141417651412f33435248387048355671342f73313030362d6e6f2f736c6964696e672e676966)

**Comment by murliatdure** [comment]
Searchbar integrated with the Navbar (incl back button)

![image](http://i.stack.imgur.com/rtRLq.png)

![image](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3aUhWVUw3TFhUN1U/components_textfields_auto1.png)


References:
https://www.google.com/design/spec/components/text-fields.html#text-fields-formatting

**Comment by nolimits4web** [comment]
Searchbar integrated with the Navbar (incl back button)

![image](http://i.stack.imgur.com/rtRLq.png)

![image](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3aUhWVUw3TFhUN1U/components_textfields_auto1.png)

![image](http://d.ibtimes.co.uk/en/full/1438927/whatsapp.png)

![image](http://www.tuexpertoapps.com/wp-content/uploads/2015/04/whatsapp-material-design-android-02.jpg)

![image](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3M1RJdzAwWE05cmc/components_textfields_auto4.png)

![image](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3ZTFiMi1fRzZIcVU/components_textfields_auto6.png)

References:
https://www.google.com/design/spec/components/text-fields.html#text-fields-formatting
https://www.google.com/design/spec/components/text-fields.html#text-fields-auto-complete-text-field

**Comment by murliatdure** [comment]
http://codepen.io/suez/full/emjwvP/ - some references

**Comment by ZanderBrown** [comment]
Has this come to anything or can it be closed?

**Comment by ZanderBrown** [comment]
There hasn't been a response by the issues owner in 20 days.
This issue **will be closed in 7 days** if no further response is submitted
