### ISSUE TITLE
how to start Virtual List in specified index

### ISSUE THREAD

**Issue by pajooh** [nolimits4web/Framework7#606]
i have a huge list to render, and i want the user to view from an specified index (variable).
if I use virtual list, and then use ```scrollToItem(index)``` to target index, will the Framework7 render previous indexes? (from the beginning?). if so, how could I implement my use case? (maybe by starting list from the target index, and after initial page render, ```prependItems(items)``` to the list?)
any help would be highly appreciated

**Comment by nolimits4web** [comment]
> if I use virtual list, and then use `scrollToItem(index)` to target index, will the Framework7 render previous indexes?

No, it won't render previous items, it is safe to use
