### ISSUE TITLE
Sortable List not smooth

### ISSUE THREAD

**Issue by thdoan** [nolimits4web/Framework7#607]
I tried out the [Kitchen Sink](http://www.idangero.us/framework7/kitchen-sink-material/) Sortable List demo on my Snapdragon 801 phone (running Kit-Kat) and it's not smooth at all. When I touch and drag a name, it's either very jumpy or the name just sticks to the same location and isn't dragged along with my finger. I'm using the lastest version of Chrome on my phone.

**Comment by nolimits4web** [comment]
Sorry, it depends on browser performance, not on processor, and Android's browsers can't be proud with their performance.

**Comment by thdoan** [comment]
FYI this sortable list is super smooth on my phone: http://forresst.github.io/demos/sortable/en/index.html

This means it's possible to create a smooth operating sortable list in Chrome on Android.

**Comment by nolimits4web** [comment]
Ok, remove transparency, box-shadow and you will probably get the same smooth as here. But on my Android device and in emulator it is very smooth
