### ISSUE TITLE
Change Viewport

### ISSUE THREAD

**Issue by anonrig** [nolimits4web/Framework7#61]
Hello,

I would like to offer you to change viewport scaling. Right now, using 1 as scale moves the sidebar gestures to more 2px at a time. Safari has a bug, in iOS, in retina displays. It doubles the pixel count. Therefore using 0.5 as a scaling will solve this problem, and it will make the swipe gestures and effects run more smoothly.

Proposed replacement is:

    <meta name="viewport" content="width=device-width, initial-scale=0.5, maximum-scale=0.5, minimum-scale=0.5, user-scalable=no, minimal-ui">

Also, CSS should change.

**Comment by nolimits4web** [comment]
Closing it for now
