### ISSUE TITLE
What should I do when I need initialize a swiper after a view rendered?

### ISSUE THREAD

**Issue by mathxlee** [nolimits4web/Framework7#610]
Hey there, I need to initialize a swiper in a View (named viewA), as you know, a swiper's initialization will work after a view rendered, but I don't have found a callback function which used to call after a view rendered in document.
so, please show me a solution, what should I do now?

**Comment by nolimits4web** [comment]
What do you mean by `view rendered`? Usually you do it in `pageInit` callback for pages which contain swiper

**Comment by nolimits4web** [comment]
Closing as there is no further discussion
