### ISSUE TITLE
Feature request : highlight .swipeout-overswipe before releasing

### ISSUE THREAD

**Issue by nicooprat** [nolimits4web/Framework7#611]
Hi,

Here's a little improvement that could really benefit to the swipeout feature. When dragging enough to trigger a click on the `.swipeout-overswipe`element, it would be handy to add a class on it, so we could highlight it with CSS to tell the user that the action is about to be performed. See what I mean ?

PS. Huge thanks for F7, amazing work.

**Comment by nolimits4web** [comment]
Sounds useful, will add it

**Comment by nicooprat** [comment]
Thanks !

**Comment by nolimits4web** [comment]
Added

**Comment by nicooprat** [comment]
You rock ! Thanks.
