### ISSUE TITLE
IOS9 previewTouch and DeepTouch

### ISSUE THREAD

**Issue by etiennea** [nolimits4web/Framework7#613]
Could it be possible to load the next "page" in a popup on longTouch and then do the push but with an expansion transition on veryLongTouch or revert if let go?

I think this would be quite complicated but would add another killer feature to this framework

**Comment by nolimits4web** [comment]
Not by means of JS as i don't see any new events in Safari touch events docs

**Comment by kivancsahici** [comment]
<a href="https://github.com/freinbichler/3d-touch">3d-touch</a> JS library could be interesting

**Comment by nolimits4web** [comment]
There is no library need for that, it is native JS event, so you can use it like:
```
$(something).on('touchstart', function (e) {
  var force = e.targetTouches[0].force;
  //do something depending on force
})
