### ISSUE TITLE
template7 issue query_url in #for

### ISSUE THREAD

**Issue by etiennea** [nolimits4web/Framework7#614]
{{#each this.backend}}
            <li>
              <a href="language-details.html?id={{url_query.id}}" class="item-link item-content">
                  <div class="item-inner">
                    <div class="item-title">{{this.name}}</div>
                  </div>
              </a>
            </li>
        {{/each}}

I don't understand why this errors, it says I can use template7 global variables? Maybe the url_query ones are not added in a #each ?

**Comment by nolimits4web** [comment]
No, it won't work in this way as `url_query` is in the top context, will not work as `each` helper changes context to "deeper" one

**Comment by nolimits4web** [comment]
Actually it can work but with this syntax in your case `{{../url_query.id}}` or `{{@root.url_query.id}}`
