### ISSUE TITLE
Tabbar issue on Kitchen Sink Material

### ISSUE THREAD

**Issue by zulfahmi** [nolimits4web/Framework7#615]
I build Kitchen Sink Material for Android 5.0 and everything looks fine, except that Tabbar (Toolbar with or without label) is not show at the bottom, but go up. It is different from what I saw on test page using browser on my computer.
Any idea how can I fix this?
Thank you

**Comment by nolimits4web** [comment]
Will be good to see something like screenshot/video and/or code. Issue probably is on your side

**Comment by zulfahmi** [comment]
I'll check it anyway. 
But so far I just copied the whole file from examples package. Change nothing.
![screenshot_2015-09-13-23-13-04](https://cloud.githubusercontent.com/assets/1472983/9837587/853e3ac0-5a6e-11e5-854d-35154fabc63d.png)

**Comment by zulfahmi** [comment]
Just see the same result on Framework7 homepage.

![screen shot 2015-09-14 at 3 59 37 pm](https://cloud.githubusercontent.com/assets/1472983/9846066/dda9ac7c-5af9-11e5-9ef1-21c86521d693.png)

**Comment by nolimits4web** [comment]
Sorry, i still don't get what you mean. If you mean that top tabbar in Material theme is the issue, it is not. It is by design: tabbar in Material theme is on the top

**Comment by zulfahmi** [comment]
Owh sorry too, I misunderstood. I thought it is at the bottom, because on document the definition of Toolbar is at the bottom. It is okay then. Thank you for explanation.
Btw, if I want to move Material Toolbar to the bottom, would you give me a clue what should I do?
