### ISSUE TITLE
Swipeout panel

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#617]
Hello,
Can you have the swipe out panels get off once clicked on any items

- close-action-panel - By Class
- $(this).closeSwipeOutPanel() - By JS

something like this.

**Comment by vdcrea** [comment]
You add the class .close-pannel to the links.

**Comment by nolimits4web** [comment]
Yes, as @vdcrea said, just add this class to any element with this class, or there is `closePanel` app method

**Comment by murliatdure** [comment]
Thanks,

**Comment by murliatdure** [comment]
I tried to do the same, It doesn't work for the Swipe Panels 

![image](https://cloud.githubusercontent.com/assets/7137859/9974572/239d97ea-5eb3-11e5-9a3c-a783c8317cc0.png)

**Comment by murliatdure** [comment]
Adding - application.closePanel() doesn't close the same.

**Comment by vdcrea** [comment]
I thought it was about a panel not a swipeable list item. I didn't already use this feature so I can't help sorry.

**Comment by nolimits4web** [comment]
Swipeouts is different, you may add `swipeout-close` class to links to close opened swipeout
