### ISSUE TITLE
Message Bar - Emo Icons

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#618]
Any plans for the EMOICONS for the message bar?

**Comment by nolimits4web** [comment]
No, as there is no reason for this, as all modern devices support Emoji from the box

**Comment by murliatdure** [comment]
Emoji Keyboard - as UI Component or plugin extension what I was asking for..

**Comment by nolimits4web** [comment]
Still can't see any reason as all modern devices has such keyboard built-in, no?))

**Comment by 7aduta** [comment]
i agree with you .. but for a month a ago .. i didn'y know there is any emoji in the default key board :D ... so this will be for users doesn't know such a feature .. like i was :)

**Comment by murliatdure** [comment]
My thought for this subject - 
1. Depending on the platform/OS may vary on standardization for Android/iOS/WIN
2. Installing the custom application as addon to the Keyboard is again a hit on the UI standards.

Hence, though of one feature for the emo's, as there is a messeges component may need the same.

Found some discussions and implementations - 
EMO ICONS - 
http://one-signal.github.io/emoji-picker/
http://emojione.com/

References:
http://emojione.com/
http://www.discourse.org/
https://github.com/wedgies/jquery-emoji-picker
http://wedgies.github.io/jquery-emoji-picker/demo.html

Let me try to fork and add this feature, if possible.
Thanks,
