### ISSUE TITLE
Swiper slider and mousewheelControl and keybordControl issue

### ISSUE THREAD

**Issue by vdcrea** [nolimits4web/Framework7#619]
Hi, it seems that mouse wheel (and keyboard) control doesn't work with swiper slider. I tried the same params as the ones used in the demo http://www.idangero.us/swiper/demos/20-mousewheel-control.html but without success. Using material theme.

**Comment by nolimits4web** [comment]
Built-in F7's version of Swiper doesn't support mousewheel and keyboard control as it is mobile framework and there is no sense for these "modules". If you need it (for some reason) you may include standalone version of Swiper in addition.

I will add note in docs that it doesn't support it

**Comment by vdcrea** [comment]
Thanks for the explanation :-) I want to use it as a web app also for desktop no matter if it doesn't display well on older browsers.  
So should I only have to replace src/js/swiper.js with your standalone Swiper before build with gunt? Or is it easier to remove swiper from F7 and include Swiper separately?

**Comment by nolimits4web** [comment]
It is easier to remove swiper from F7 and include Swiper separately? Or if you don't mind about few extra KB, you can just include standalone Swiper after F7 to keep F7 lib as it is

**Comment by vdcrea** [comment]
Thanks that s what i will do. Have a nice day
