### ISSUE TITLE
Parameterized grid mixins

### ISSUE THREAD

**Issue by Papipo** [nolimits4web/Framework7#620]
In order to be able to avoid markup pollution, it would be nice to have mixins to apply col and tablet styles. Something like this: http://getbootstrap.com/css/#mixins

Otherwise I can't just mix-in those classes, LESS complains saying that they aren't defined.

**Comment by nolimits4web** [comment]
Because they are not mixins. But you can just copy it from source https://github.com/nolimits4web/Framework7/blob/master/src/less/ios/grid.less and make as your own mixins
