### ISSUE TITLE
No trailing newline/EOF character

### ISSUE THREAD

**Issue by frdmn** [nolimits4web/Framework7#622]
I noticed that the dist versions of framework7 assets doesn't have any EOF character / newline at the end of the files.

This may result in some bad behaviour like I experienced just now, when concating 2 JavaScript files (Framework7 and your own on top of that) into one. Then you'll notice that the first line of your script is attached next to the last line of Framework7:

```js
//# sourceMappingURL=framework7.js.map;var myApp = new Framework7();
var $$ = Dom7;
```

instead of 

```js
//# sourceMappingURL=framework7.js.map;
var myApp = new Framework7();
var $$ = Dom7;
```

Adding an empty new line at the end of Framework7 JS assets should fix this issue :)

**Comment by nolimits4web** [comment]
Sorry, it is done by minifiers automatically and actually this is what you expect from them. So if you do concatenation manually (or automatically) just add "new line" manually
