### ISSUE TITLE
[Popup/Modal] Is it possible to choose the slide effect?

### ISSUE THREAD

**Issue by kiki-le-singe** [nolimits4web/Framework7#623]
[Popup](http://www.idangero.us/framework7/docs/popup.html)
By default the popup opens with slideInUp effect. Can we open it with another effect (slideInDown, slideInLeft, slideInRight) ?

Thanks

**Comment by nolimits4web** [comment]
No, but it is CSS based https://github.com/nolimits4web/Framework7/blob/master/dist/css/framework7.ios.css#L3886-L3923 So you should be easily add your own effects for that

**Comment by kiki-le-singe** [comment]
@nolimits4web ok great thanks :)
