### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#624]
Can we auto-focus the Accordian body once open.
I seen there is API exposed for the same, but unable to achieve as none of the standard scrolling tricks responds.

Can you please suggest the idea for the same.
Thanks,

**Comment by nolimits4web** [comment]
What do you mean by `auto-focus the Accordian body`?

**Comment by murliatdure** [comment]
Once I click on the Accordion header, It opens the same and there is hook along with this. 
My concern is whenever the accordion opens the body gets slides downwards, which is expected; but most of the user's didn't get there is change happened If it open within off-canves (last element on the list); It opens and manually we have to scroll little up.

I tried to use many plugins.tricks (get the offset from top), and forcefully pushes the body/container upwards. Bad luck .. unable to achieve the same.

**Comment by nolimits4web** [comment]
Shouldn't be hard:
```
$$('.accordion-item').on('opened', function(){
    var pageContent = $$(this).parents('.page-content');
    var newScroll = $$(this).offset().top - 44 + pageContent[0].scrollTop;
    $$(this).parents('.page-content').scrollTop(newScroll, 400);
});
```
And please, use Forum for questions
