### ISSUE TITLE
Input doesn't work

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#626]
Hello,
Some devices INPUT doesn't work, Input simply doesn't responds.

- Sony Xperia SP (Android) - version  Kit Kat
- Samsung Grand - version Jelly Bean

Do we have some minimum SDK for android?

**Comment by nolimits4web** [comment]
Any live example, screenshot, video?

> Do we have some minimum SDK for android?
Better support in Android 4.4+

**Comment by murliatdure** [comment]
https://www.youtube.com/watch?v=8DasqHipjdw&feature=youtu.be

**Comment by murliatdure** [comment]
https://mmf.cdn.whatsapp.net/d/npn08-FXqc1SFjUOPeuHblYFejw/Apq_AzUb94c1qEMf72LgG8OjCgkbKU0IGqPZKSLIPYHl.mp4?x=2

**Comment by nolimits4web** [comment]
Have you tried it on other devices? Could be device-specific issue

**Comment by murliatdure** [comment]
Issue was from custom css that doesnt react for particular android versions.. anyways thanks alot for your support.

Tested for v4.1-5.0 - working well.
