### ISSUE TITLE
View class and prototype, memory efficiency question

### ISSUE THREAD

**Issue by babakness** [nolimits4web/Framework7#627]
Hello, I'm looking over the source code and have noticed that when a new view is instantiated via

var myView = new View(..);

Every single function is created all over again because prototypes are not being used. I was curious if this was by intention and what the purpose is.

I will elaborate here:

The "new" statement creates pointers to all the functions attached to the "prototype" attribute. 

I hope I'm not being too pedantic as I'm sure you're well aware of this, I'm asking this for the sake of making my question complete:

```javascript
var Demo = function(){
  this.testA = function(){return 1}
}
Demo.prototype.testB = function(){return 2}

var a = new Demo()
var b = new Demo()

Demo.testA = function(){return 3}
Demo.prototype.testB = function(){return 3}

console.log(a.testA()) // returns 1
console.log(a.testB()) // returns 3
```

The method testA is attached to the instance not to the class. Every instance has its own copy, which takes up memory.

The method testB, attached to the prototype attribute, is attached to the class. Every instance references the same copy (unless overwritten).

In the source code I noted:

```javascript
app.addView = function (selector, params) {
            return new View(selector, params);
};
```

Every call to addView creates a new instance and therefore, a new copy of all the functions attached to `this` in view

```javascript
var view = this
```

If the intention is to have class wide variables, shared by all instances, one could leverage a closure:

```javascript

var Demo = (function()){
  var classAttribute = 1

  var Demo = function(){
    this.instanceAttribute = 2
  }
  
  Demo.prototype.method = function(){}

  return Demo
)()
```

**Comment by nolimits4web** [comment]
The intention was different, to make each View as closed and separate from another as much as possible. And it is not really a question about overwrite parameters/methods as you wouldn't and shouldn't do it)) But performance/memory question is interesting, but Views are not used such often, you probably have up to 5 instances maximum in app. So is there any chance to estimate how much we can win with rewriting it to prototypes ?:)
