### ISSUE TITLE
Handling page transitions

### ISSUE THREAD

**Issue by tarqe39** [nolimits4web/Framework7#628]
Is it possible to fire page transitions without setting the page content? Something like pushing the state.
I'm trying to use react router to handle navigation, but i want to have proper transitions.
Maybe there is a workaround i'm not aware of?

**Comment by nolimits4web** [comment]
No, transition should be between something. Probably you can do it to empty page and then fill its content with React

**Comment by tarqe39** [comment]
Ok, seems that its the best way to handle this. Thank you.
