### ISSUE TITLE
Center in navbar is broken in material design 

### ISSUE THREAD

**Issue by Phyks** [nolimits4web/Framework7#631]
Hi,

Center in navbar is broken in material design. It is moving and not keeping in the middle of the navbar.

Here is an explanatory screenshot from http://www.idangero.us/framework7/docs-demos/navbar-multiple-links.html (same code, using a material design instead of ios one):
![2015-09-24-160919](https://cloud.githubusercontent.com/assets/3856586/10075584/caea35ae-62d6-11e5-8a6c-708729cd1765.png)

Did I miss something or is it really a bug?

**Comment by nolimits4web** [comment]
Can't see such issue. What is your device/os version and app settings?

**Comment by Phyks** [comment]
I am using the exact page from http://www.idangero.us/framework7/docs-demos/navbar-multiple-links.html except that I changed "ios" to "material" in the CSS includes. Everything else is the same.

I am viewing it in Firefox for desktop, in 640x480 with the responsive view.

**Comment by nolimits4web** [comment]
You also have to enable `material: true` in app settings
