### ISSUE TITLE
Material - hide-bars-on-scroll

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#632]
Transitions doesn't looks good since of material and ios behavior.

https://impondesk.tinytake.com/sf/MzEzOTYyXzE4NjEzMzg

**Comment by nolimits4web** [comment]
It is already fixed in dev version

**Comment by murliatdure** [comment]
Can you please share the link of roadmap on site, easier for us for contribution and will be on the same page.
Thanks,
