### ISSUE TITLE
fail to make ajax call

### ISSUE THREAD

**Issue by amoebageek** [nolimits4web/Framework7#638]
am trying to make an api call in my hybrid app using framework7 Dom7 Its working very fine when i am testing on browser,but when i build online on phonegap for android's APK on my phone.Rest all JS working fone on phonebut only ajax call is not getting fired.

var myApp = new Framework7();
var $$ = Dom7;

$$('form.ajax-submit').on('submitted', function (e) {
    e.preventDefault();
myApp.showPreloader();
    var searchKey=$$("#search-key").val();
              $$("#track").text('API calling');
    $$.get("http://my/api/path/dev/apiv-1-0-2/students/"+searchKey,function(response){
             $$("#track").text('got the response');
});
});

I had applied the track of my js progress code ,i get the response "API CALLING" but not the "GOT THE RESPONSE" message.

**Comment by nolimits4web** [comment]
Are there any errors in browser console when you do it from PhoneGap app?

**Comment by amoebageek** [comment]
no,no error but yes i put my div text changing code on different part like $$("#track").text('API calling');
its changing ie code running fine before ajax call code but text not changing when make an ajax call.i believe this means there is some issue with the ajax call.

**Comment by nolimits4web** [comment]
issue can be only on your server side or with wrong phonegap configuration. Make sure you have whitelisted your api domain

**Comment by Tarekajaj** [comment]
instead of :
```javascript
$$.get("http://my/api/path/dev/apiv-1-0-2/students/"+searchKey,function(response){
    $$("#track").text('got the response');
});
````

use:
````javascript
$$.ajax({
    url: "http://my/api/path/dev/apiv-1-0-2/students/"+searchKey,
    success: function(response){
        alert('got the response');
    },
    error: function(){
        alert('got the error');
    }
});
````

and see what you get

**Comment by nolimits4web** [comment]
Closing as no further response/discussion
