### ISSUE TITLE
MessageBar - Issue

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#641]
Android v4.2.2, Model: GT-I9082 (Samsung Grand)
Andrdoi 4.3, Sony Xperia SP
Input send button is not coming.

Although same code is working on all Android 5.0 devices.

![20151007102300](https://cloud.githubusercontent.com/assets/7137859/10345291/3e63a942-6d46-11e5-990a-a7027e65a49c.jpg)

**Comment by shauntrennery** [comment]
I have the same problem on a Samsung Grand.

**Comment by murliatdure** [comment]
Lots of real devices v4.1-4.3 are reproducable; and getting blocker for hte send button.
