### ISSUE TITLE
[feature request] date range picker

### ISSUE THREAD

**Issue by muzuiget** [nolimits4web/Framework7#643]
Hi, can Framework7 add a date range picker? The picker similar to the [Google Analytics](https://www.quora.com/Where-can-I-find-a-date-picker-similar-to-the-one-in-Google-Analytics-Not-Good).

There a example in Kitchen Sink -> Calendar -> Multiple Values look close to this feature, but what I need is only two value, and auto highlight the date cells between min and max date after each pick;

**Comment by nolimits4web** [comment]
But you have callbacks in calendar, right? Where you can highlight manually all values between first and last

**Comment by aviaialon** [comment]
I second that! F7 really needs a date range picker

**Comment by aviaialon** [comment]
You Rock!

**Comment by Mickey-** [comment]
nice,thx
