### ISSUE TITLE
Change to documentation

### ISSUE THREAD

**Issue by lionel-bijaoui** [nolimits4web/Framework7#646]
I'm totally new to Framework7 and I've been testing it on Cordova (+ xwalk).
While implementing [this tutorial](http://www.idangero.us/framework7/tutorials/maintain-both-ios-and-material-themes-in-single-app.html) I was getting an error with prependTo().
A quick look to Dom7 reveal that this function does not exist anymore.
How can I fix this ?

Also, what is the good method between these two :
    
    if (isAndroid) {
        // Change class
        $$('.view.navbar-through').removeClass('navbar-through').addClass('navbar-fixed');
        // And move Navbar into Page
        $$('.view .navbar').prependTo('.view .page');
    }

or

    if (isAndroid) {
        // Change class
        $$('.pages.navbar-through').removeClass('navbar-through').addClass('navbar-fixed');
        // And move Navbar into Page
        $$('.view .navbar').prependTo('.view .page');
    }

**Comment by nolimits4web** [comment]
Yes, there is an issue. Actually this method was recently implemented and will appear in next release soon. But anyway `$$('.view .navbar').prependTo('.view .page');` is basically the same as `$$('.view .page').prepend('.view .navbar');`

As for two of your examples, first method is better (for View) as it set more `global` styles and should be more correct

**Comment by lionel-bijaoui** [comment]
Ok ! Thank you very much for your fast help.
Then [this page](http://www.idangero.us/framework7/docs/app-layout.html) should be updated to implement the best method, no ?

**Comment by nolimits4web** [comment]
> Then this page should be updated to implement the best method, no ?
I guess, will update it

> EDIT: when I use your method it actually add ".view .navbar" as text. Weird.
Then this:
```
$$('.view .page').prepend($$('.view .navbar'));
```

**Comment by lionel-bijaoui** [comment]
Thanks you

**Comment by nolimits4web** [comment]
Ok, checked again, there is no difference for "...-fixed" class used on `pages` or `view` so docs is correct
