### ISSUE TITLE
Custom build without Template7 or Dom7

### ISSUE THREAD

**Issue by lionel-bijaoui** [nolimits4web/Framework7#647]
I appreciate that it is possible to do a custom build of Framework7 with ```gulp custom -accordion,modals,tabs``` but is it possible for Framework7 to work without Template7 or Dom7 ? If yes, how ? I don't have experience with gulp so I don't know which file should be modified.
Thank you in advance for your time and help.

**Comment by nolimits4web** [comment]
No, sorry, it is not possible

**Comment by lionel-bijaoui** [comment]
Okey, I guess they are used internally. What if I want to use [vuejs](https://github.com/yyx990803/vue) (or Riot.js/KnockoutJS/etc) instead of Template7 ? They both use mustache binding, is there a risk of conflict ?

**Comment by nolimits4web** [comment]
If you don't use Template7 and don't enable it in your app, you won't get any conflicts

**Comment by lionel-bijaoui** [comment]
Just to be sure :

    var myApp = new Framework7({
        template7Pages: false
    });

And I'm good to go ?

**Comment by nolimits4web** [comment]
Yes, it is disabled by default :)

**Comment by lionel-bijaoui** [comment]
Thank you very much, back to coding !
