### ISSUE TITLE
ios9 fixed navbar stays not fixed after opening keypad

### ISSUE THREAD

**Issue by msio17** [nolimits4web/Framework7#651]
On ios9 fixed navbar will not stay fixed at to top after opening keypad by selecting e.g. input field but it is hidden. I am attaching the screenshots to make to make it clear. screen 1 shows correct behaviour after opening keypad. screen 2 shows incorrect behaviour how it looks right know
thanks for any help
best regards 
Michal
![simulator screen 1](https://cloud.githubusercontent.com/assets/2778376/10418594/ab05922e-705f-11e5-9cef-a517694ad2da.png)
screen 1
![simulator screen 2](https://cloud.githubusercontent.com/assets/2778376/10418595/ab05c398-705f-11e5-982c-6788750abc6a.png)
screen 2

**Comment by nolimits4web** [comment]
It is not a Framework7 issue http://www.idangero.us/framework7/forum/#!/bugs-and-issues:ios9-fixed-navbar-stays-not

**Comment by murliatdure** [comment]
Without the Keyboard plugin also it works well.. We need to false the fullScreen preferences for this.

**Comment by ddtramp** [comment]
@murliatdure how to use fullscreen fix this...?
