### ISSUE TITLE
"Media Lists" with images are overflowing to the right side of the page

### ISSUE THREAD

**Issue by yusufyilmaz** [nolimits4web/Framework7#657]
Hi,
First of all thank you for bringing fw7 to us. It is a great job.

I am trying to use "Media  Lists" with image but when the "item-title" is long, screen overflowing and horizontal scrollbar is showing. I am not getting this issue without images. Could it be a bug?

![image](https://cloud.githubusercontent.com/assets/4222204/10466765/98c4663a-71fe-11e5-97e3-a19c78e7f78c.png)

**Comment by Tarekajaj** [comment]
To solve this issue I add an extra class to the list-item to tell if it has an image and what size is it. in the screenshot you attached the image is 44px wide so I add with-media-44 class to the list-item
```html
<a href="#" class="item-link item-content with-media-44">
    <div class="item-media">
        <img src="http://lorempixel.com/88/88/fashion/2" width="44">
    </div>
    <div class="item-inner">
        <div class="item-title-row">
            <div class="item-title">Don't Stop Me Now</div>
        </div>
        <div class="item-subtitle">Queen</div>
    </div>
</a>
```
then in my style sheet I have
```css
.with-media-44 .item-media + .item-inner {
    max-width: calc(100% - 59px);
}
```

even this works for
