### ISSUE TITLE
Sticky Lists not working on Chrome

### ISSUE THREAD

**Issue by D1no** [nolimits4web/Framework7#658]
Hi, I am happily testing Framework7 right now :) very impressed.

I found anyhow a bug, running kitchen-sink-material:
- On chrome all sticky headers are not sticking. Impacted:
 - List View
 - Contact View

Example Chrome vs. Safari:
![image](https://cloud.githubusercontent.com/assets/2397125/10471827/17dc11f0-721a-11e5-8d6e-02e54a7bbfdf.png)

System:
- Mac OSX El Capita, 10.11 (latest Update)
- Chrome: Version 46.0.2490.71 64-bit (latest Update)

**Comment by Tarekajaj** [comment]
it doesn't work on chrome because it uses ```position:sticky ```  which **was temporarily  removed** from chrome.
You can read more about it [Here](https://code.google.com/p/chromium/issues/detail?id=231752#c28).

**Comment by D1no** [comment]
... temporarily removed... for over a year now... (-.-)

Support of ``position:sticky`` looks really terrible right now
![image](https://cloud.githubusercontent.com/assets/2397125/10485429/59ebd524-728a-11e5-8eff-6642516b4105.png)

Any idea for a workaround to bridge the behaviour to chrome (latest)? 18% Global support is really a bummer.

**Comment by nolimits4web** [comment]
You can find few polyfills in the end of this article http://www.sitepoint.com/css-position-sticky-introduction-polyfills/

**Comment by nolimits4web** [comment]
I think we can close it as Chrome-specific issue, not the F7
