### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by caiiiycuk** [nolimits4web/Framework7#659]
1:

Page:
http://www.idangero.us/framework7/docs/router-api.html#.Vh3H563tlBd

Section:
View Navigation Shortcuts Methods

Problem in code:
mainView --> .. <-- router.loadContent(content) - load dynamically generated content as a new usual page.

2:

Getting started:
http://www.idangero.us/framework7/get-started/#.Vh3JFq3tlBc

```
<a href="#" class="link icon-only open-panel"><i class="icon icon-bars-blue"></i></a>
```

**icon-bars-blue** - icon does not exists

**Comment by nolimits4web** [comment]
Thanks, will fix it. But for such issues in future post it in appropriate repo at https://github.com/nolimits4web/Framework7-Website

**Comment by nolimits4web** [comment]
Fixed
