### ISSUE TITLE
failed to manipulate created DOM

### ISSUE THREAD

**Issue by zxdvd** [nolimits4web/Framework7#660]
Example, I got a page via ajax, and I'd like to change it a bit before adding it. But I failed with DOM7 while I succeed with jquery.

A simple test code:
 
    var test="<div><p>test</p></div>";                                                                            
    test = $$('<html>').html(test);                           
    console.log(test);                                                                       
    console.log($$('p', test).html());

I got following error:

    Uncaught TypeError: (t || document).querySelectorAll is not a function

Is it a bug? Is there any workaround?

**Comment by nolimits4web** [comment]
First of all, Dom7 doesn't allow to create 'html` elements, as it doesn't create documents during this. And actually there is no much sense in it. Also second `text` (context) parameter in your `$$('p', test)` can be only HTMLElement, as again there is no much sense to use something else there. So this will work:

```js
var test = $$('<div><p>test</p></div>');
console.log( $$('p', test[0]).html() ); // -> 'test'
```
Which is also doesn't make much sense :D More strait forward will be this:
```js
var test = $$('<div><p>test</p></div>');
console.log ( test.find('p').html() ); // -> 'test'

**Comment by zxdvd** [comment]
Thanks very much.

`console.log($$('p', test[0])).html()` works well.
