### ISSUE TITLE
Form Elements - Transformed labels cause horizontal overflow and scrolling

### ISSUE THREAD

**Issue by D1no** [nolimits4web/Framework7#661]
Form labels cause an overflow do to the transform, leading to horizontal scrolling in the viewport.

Impact: Navigate to Form Elements Page

1) Example: 
![20151014-172340_capture](https://cloud.githubusercontent.com/assets/2397125/10488880/0852ba46-729b-11e5-85ae-2b76c47b74ea.gif)

2) Example:
![20151014-172716_capture](https://cloud.githubusercontent.com/assets/2397125/10488904/30c9f868-729b-11e5-972f-0da5cd032a7f.gif)

3) Example with a very long label:
![20151014-172925_capture](https://cloud.githubusercontent.com/assets/2397125/10488937/501b36aa-729b-11e5-87fb-e31290092ae0.gif)

**Comment by nolimits4web** [comment]
Fixed
