### ISSUE TITLE
Please change css & js links in examples files

### ISSUE THREAD

**Issue by xianghongai** [nolimits4web/Framework7#664]
[kitchen-sink-ios]  & [kitchen-sink-material] 。

**Comment by nolimits4web** [comment]
Please, see the README file:

> Framework7' JS and CSS files in Kitchen Sink are temporary linked to build/ to make development process easier on this stage. So to make it work you need to build Framework7 (see Build section) or to re-link JS and CSS files to dist/ folder.

**Comment by xianghongai** [comment]
I got it，thanks 。
