### ISSUE TITLE
Framework tries to load /t on startup

### ISSUE THREAD

**Issue by Thomasdezeeuw** [nolimits4web/Framework7#666]
I used the `index.html` from the getting started page and started to play around with options the framework offers. Until I ran into a really interesting issue. The framework tried to load the page `/t` on startup with the following javascript:

```js
var app = new Framework7({
	pushState: true,
	pushStateSeparator: '',
})

var mainView = app.addView('.view-main', {
	dynamicNavbar: true
})
```

After some digging through the code I think I found the issue, on the following line https://github.com/nolimits4web/Framework7/blob/master/src/js/views.js#L553. It tries to split the document location with an empty push state, which returns the complete document location in a array and takes the second item. So for `http://localhost` that would be a `t` and proceeds to load that "page".

Now I would be happy to create a pull request to fix it, except I'm not sure what the code is supposed to return and I don't have time to find out at the moment. I hope some else can fix this.

Ps. I think the code would also fail if the `pushStateSeparator` appeared twice in the `docLocation`, returning a partial url. I think you should join the array back together leaving only the first item.

**Comment by nolimits4web** [comment]
You have to specify also `pushStateRoot` in this case, otherwise F7 can't know root of the app

**Comment by Thomasdezeeuw** [comment]
I'm currently using `window.location.origin + '/'`, so it would work in both production and development. But couldn't that be the default?

**Comment by nolimits4web** [comment]
> But couldn't that be the default?
It could, but it is not always the case. Will add it as the default value

**Comment by Thomasdezeeuw** [comment]
Want me to create a pr? Am I correct in think this: https://github.com/nolimits4web/Framework7/blob/master/src/js/f7-intro.js#L26, is the correct location for that?

**Comment by nolimits4web** [comment]
I haven't added this default separator, but better prevented to load such `/t` thing on app load. As this `location.origin` is not a solid solution which won't work for subfolder projects and cordova apps
