### ISSUE TITLE
serializeObject / parseUrlQuery fail with a nested object

### ISSUE THREAD

**Issue by mgesmundo** [nolimits4web/Framework7#668]
In v. 1.3.1 try to serialize and parse a deep nested object:

```js
var obj = {
  'root0a/root0b': 'main/submain',
  root1: {
    prop1: {
      prop1a: 'value1a',
      prop1b: 'value1b'
    },
    prop2: 'value2'
  },
  root2: [
    {
      a: 1,
      b: 2,
      c: [
        {
          d: 3,
          e: [ 'a', 'b' ]
        }
      ]
    },
    {
      f: 'c'
    }
  ]
};
```
Both the serialized string and the parsed object are wrong.

**Comment by nolimits4web** [comment]
Fixed now, but such usage doesn't have much sense :)

**Comment by mgesmundo** [comment]
Thanks Vladimir, but this solve only the serialization, not the parsing.
Try this simple object:
```js
var obj = {
  'root-a/root-b': 'main/submain',
  root1: {
    prop1: 'value1',
    prop2: 'value2',
    prop3: ['value3a', 'value3b']
  }
};
```
If you serialize and then parse it, the result is:

```js
{
  root-a%2Froot-b: "main%2Fsubmain", 
  root1[prop1]: "value1", 
  root1[prop2]: "value2", 
  root1[prop3][]: "value3b"
}
```
Into parseUrlQuery is missing <code>decodeURIComponent</code> for the key and the value, the object tree is not recreated and the <code>value3a</code> is lost.

**Comment by nolimits4web** [comment]
At the moment parseUrlQuery is not intended to parse such complex queries, just for basics, as such queries usually parsed automatically by server-side language. Anyway, it is better to use JSON.serialize/parse in such case

**Comment by nolimits4web** [comment]
Actually, i am wondering do you really use it in this way with deep objects/queries? Can you show me real-life example of such usage? :)

**Comment by mgesmundo** [comment]
Sorry, but if you do not know a real-life example of such usage, why you added this enhancement in serialization? Why not in parsing? Your framework is very useful and complete and I'm simply surprised to see an incomplete solution :) If you want to open a local url (inside a Cordova app) passing a simple object using an url query, you propose a serialization method but not the corresponding parsing method to manipulate it into the destination page. I use JSON stringify/parse to solve this, but your serialization (the same used in PHP) is more compact and can be used only if there is a corresponding parsing method. Please note that I don't want to stress you, but only to make your framework always better! :)

**Comment by nolimits4web** [comment]
> Sorry, but if you do not know a real-life example of such usage, why you added this enhancement in serialization?

There are few real life examples when we need such serialization, basically it is when we need to send GET request with deep data, it is not good but i saw few weird APIs working like that. Also for forms with multiple selects/checkboxes (arrays). 

But i don't know the real life example of parsing such thing on client side.

> Why not in parsing?

Because it is damned not easy to parse such thing :D I will try it, but can't promise i will succeed in it :D
