### ISSUE TITLE
Bug - cant zoom out in android 5 photobrowser

### ISSUE THREAD

**Issue by shaulhadar** [nolimits4web/Framework7#671]
Hello Vlad...
I once posted about this bug, and i can still see it.

in android 5, when you double click the image in a photobrowser, the picture zooms, but when you double click again, it doesnt zoom out.

i checked it on a 4.4 device, and it worked well, so i guess its only related to android 5.

please check it out when you have a sec....i checked 3 devices with android 5, and its thesame....also when checking the kitchen sink through chrome btw....

thanks for your time!!

**Comment by Tarekajaj** [comment]
Just Tested on Android 5.1.1 and it's working normally.

**Comment by nolimits4web** [comment]
Ok, checked on 5.0 emulator and 5.1 real device. Can't see such issue, it is working normally

**Comment by nolimits4web** [comment]
Do you still have this issue?

**Comment by vestaxpdx** [comment]
Sorry to bring up an old post. But I am experiencing this issue still on Android 5.0 Samsung SMG900F, Framework7 1.4.2

Double tap only zooms in, then you get stuck and can't zoom out.

http://photoswipe.com/ allows you to pinch zoom in and out on Android. This would be amazing to add to Framework7 if possible to keep that native feel.

Absolutely amazing framework by the way!!
