### ISSUE TITLE
Query parameters do not get added to view history with domCache

### ISSUE THREAD

**Issue by bfcam** [nolimits4web/Framework7#674]
This is the same issue as described in #209 but with domCache: true and using #pagename navigation.

If I navigate by clicking on this link:

`<a href="#page1">Page1</a>`

And then click on this link within Page 1:

`<a href="#page2?foo=bar">Page 2</a>`

And then click on this link within Page 2:

`<a href="index.html" class="back">Back</a>`

This listener would show an empty query where I would expect to see the "foo: bar" query data:

`$document.on('pageReinit', function(e) {
  console.log(e.detail.page.query);
});`

I made a 1 line change that fixes the problem in my case but I am not aware if this causes any other side effects:

```
--- framework7.js.orig	2015-10-24 18:21:16.000000000 -0300
+++ framework7.js	2015-10-24 18:21:06.000000000 -0300
@@ -2556,6 +2556,8 @@
             var content = options.content;
             var pageName = options.pageName;
             if (pageName) {
+                options.url = '#' + pageName;
+
                 if (pageName.indexOf('?') > 0) {
                     options.query = $.parseUrlQuery(pageName);
                     options.pageName = pageName = pageName.split('?')[0];
```

**Comment by nolimits4web** [comment]
Thanks, fixed now in dev version

**Comment by bfcam** [comment]
Confirmed. Thanks for the quick fix!
