### ISSUE TITLE
Material: Custom Action Sheet options

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#677]
Doubly action sheet -or- responsive for the Phone (single) and Tabs (Double) - configuration driven.

![image](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3VE1WN0h5Ql9ZR2M/components_bottomsheets_modal14.png)

**Comment by nolimits4web** [comment]
Again, it is just `float:left; width:50%` on action button
