### ISSUE TITLE
Material: Forms

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#678]
Form double components

![image](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsVkg5V3htMWk0OVk/components_buttons_mobile2.png)

**Comment by murliatdure** [comment]
![video](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3321sZLoP_HTS1LdnhrTl9TRzg/components-buttons-otherbuttons-060203_MobileDropdowns_xhdpi_006.webm)

**Comment by nolimits4web** [comment]
Again, this is easy to done manually. Just add 2 `item-input` and set required width on them
