### ISSUE TITLE
Material: Float Action Button (FAB)

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#679]
ISSUE: Currently FAB is attached to the Page Fragment as fixed position; rather relative to the page/tab etc.
I guess it should having exposures relative to the other components

https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsNVRkV3FZMktvMWc/components-buttons-fab-behavior_06_xhdpi_009.webm

**Comment by murliatdure** [comment]
ENHANCEMENT: Multiple FABs - 

https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B8v7jImPsDi-S01HZEpTMEdaUkk/components-buttons-fab-transition_trigger_02.webm

**Comment by murliatdure** [comment]
ENHANCEMENT: FAB convertiable toolbar

The floating action button can transform into a toolbar upon press or from a toolbar upon scroll. The toolbar can contain related actions, text and search fields, or any other items that would be useful at hand.

https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B8v7jImPsDi-ajMzVHp3VzJ4UkU/components-buttons-fab-transition_toolbar_02.webm

**Comment by murliatdure** [comment]
ENHANCEMENT:  FAB Speed dial
The floating action button can fling out related actions upon press. The button should remain on screen after the menu is invoked. Tapping in the same spot should either activate the most commonly used action or close the open menu.

https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3TmpnUHVKRV9DU0E/components-buttons-fab-transition_speeddial_02.webm

**Comment by murliatdure** [comment]
ENHANCEMENT: FAB Morph

The floating action button can transform into sheets of material that are part of the app structure. This dramatic transformation accentuates the action the button enables.

When morphing the floating action button, transition between starting and ending positions in a logical way. For example, do not pass through other sheets of material.

The morph animation should be reversible and transform the new sheet of material back into the floating action button.

https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B8v7jImPsDi-c0UwMFAyQU5Jb1U/components-buttons-fab-transition_morph_02.webm

**Comment by nolimits4web** [comment]
As for FAB attachement - just set in child of required element - tab, page, view, etc. to get the desired behavior
As for Multiple FAB - what or who stops you to add multiple FABs and set required top/bottom position on them?
As for FAB - speed dial, will look, maybe i implement it
As for Morph - not really possible to do common solution as it is too specific by itself

**Comment by murliatdure** [comment]
As a powerful HTML5, CSS3 and JS Framework, nothing stops. Currently the given example is of type position:fixed; where I would like to get this highlighted for handling the relative to the elements.

Thanks,
