### ISSUE TITLE
Breadcrum Component

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#681]
New Component - 

![image](http://www.1stwebdesigner.com/wp-content/uploads/2012/06/css3-tutorials/breadcrumb-css3-text-effect-tutorials.jpg)

![image](http://i.stack.imgur.com/SD46Y.jpg)

**Comment by nolimits4web** [comment]
Bread crumbs is not a mobile apps thing, there is no breadcrumbs in mobile apps. Also, it can be created with few lines of custom styles
