### ISSUE TITLE
Material: Tabs

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#684]
![image](http://i.stack.imgur.com/5etSi.gif)

Looking for something like this 
1. Sliding Tabs
2. More Tabs support - Android most of the apps shows this offcanvas tabs (rather justifies); on slide users can access the same .. nice approach for responsiveness.

**Comment by murliatdure** [comment]
![image](https://camo.githubusercontent.com/82497b070232deae261241b28ca058173bfa4ba4/68747470733a2f2f6c68352e676f6f676c6575736572636f6e74656e742e636f6d2f2d4e2d306152456e7444644d2f564576503449356b7872492f41414141414141417651412f33435248387048355671342f73313030362d6e6f2f736c6964696e672e676966)

**Comment by nolimits4web** [comment]
Already discussed here, with solution, can be achieved by using Swiper

**Comment by murliatdure** [comment]
I added the SWIPER classes and initialization on the tab, It works as expected; but with this approach the tab highlight (bottom border) was not getting that swiping effect. Hence looking for tabs to have inbuilt feature of swiping.

And there is another feature specially for the android devices; tabs more than the screen size gets the swiping feature; just like in the given GIF there are multiple tabs (more than 3-4); Top Grossing is out of the canvas; so after swiping on the tab links can switch to the tabs. Which is again a cool feature for the considering responsive and multiple sizes of devices. (~3-6inch devices in the market).

Just a suggestion based on the usage of the F7 till time.
