### ISSUE TITLE
Material Scrolling Techniques

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#686]
https://www.google.com/design/spec/patterns/scrolling-techniques.html#scrolling-techniques-scrolling

- Flexible space
- Flexible space with image
- Flexible space with overlapping content

**Comment by nolimits4web** [comment]
This won't be implemented by default, because such kind of transitions work very slow in browser

**Comment by nolimits4web** [comment]
Anyway, i think this issues is related to/same as #604

**Comment by murliatdure** [comment]
Agreed this is having the impact on the different devices/platforms.
