### ISSUE TITLE
Cards - Footer Orientation

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#687]
Action/footer bar in cards are justified similar to toolbar; rather we should have the left|center|right segments where individual can compose the required controls at any place.

Currently all given controls gets justified.

**Comment by nolimits4web** [comment]
Please stop flooding with issues which are not issues or bugs. You probably better to keep them all in single thread as they basically have the same subject. Also, don't need to create issues for one-line custom solutions. As this one, you can control alignment using `justify-content` CSS property

**Comment by murliatdure** [comment]
Can you please enable the Labels so that accordingly we can tag for the Enhancements, Suggestion etc.

Anyways, Currently the component automatically supports the same; as JUSTIFIED behavior. I was looking for the navbar effect as (LEFT|CENTER|RIGHT) options inside the card footer.
