### ISSUE TITLE
Total Beginner F7 

### ISSUE THREAD

**Issue by sangyoo91** [nolimits4web/Framework7#688]
I need to know how to switch between views.
```
.views
  .view.view-main#view-1
    // ..
  .view#view-2
  .view#view-2
```
So from here, if I want to click on a link inside `#view-1` to switch to `#view-2` with page animation,
how can I achieve this?

I am using `MeteorJS`.

```
  viewPageList = cleanJ.addView '#view-1',
    dynamicNavbar: true

  viewCropper = cleanJ.addView '#view-2',
    dynamicNavbar: true
```

**Comment by nolimits4web** [comment]
Or if your Views are Tabs, then `myApp.showTab('#view-2')` http://www.idangero.us/framework7/docs/tabs.html#show-tab-using-javascript

**Comment by nolimits4web** [comment]
I think we can close it as there is no further discussion
