### ISSUE TITLE
Sorry, i just want to ask how to change active view in javascript when u have many view.

### ISSUE THREAD

**Issue by adisak1618** [nolimits4web/Framework7#689]
sorry i find and read all of document, then try a lot of coding. i still stuck in this problem. i just want to know how to change active view when i have multiple view in my application.
Thank a lot!.

**Comment by GuillaumeBiton** [comment]
views enabled are "active" maybe you have a z-index issue if some of your buttons or input are not accessible.

**Comment by nolimits4web** [comment]
Or if your Views are Tabs, then `myApp.showTab('#view-2')` http://www.idangero.us/framework7/docs/tabs.html#show-tab-using-javascript

**Comment by adisak1618** [comment]
WOW Thank!
