### ISSUE TITLE
content-block padding to margin proposal

### ISSUE THREAD

**Issue by czb** [nolimits4web/Framework7#690]
As it is now, the vertical scrollbar is partly hidden on Google Chrome. I propose the following to fully show the vertical scrollbar. The idea is basically to replace padding by margin and to change 100% height to `calc` height.

I propose to replace all `padding-top: 44px;`, `padding-top: 88px;` and `padding-bottom: 44px;` on `content-block` with zero padding. Then I would add `margin-top` 44px and 88px respectively on the `content-block`. Finally I would change `height` of `content-block` from `100%` to something like `calc(100% - 86px)`.

**Comment by nolimits4web** [comment]
I guess you mean `page-content` not `content-block`.

The issue is that many devs use transparent/semi-transparent navbars/toolbars, or iOS9 gives opportunity to use backdrop blur (like in native apps). But such padding-to-margin change will break such opportunities
