### ISSUE TITLE
issue material sub navbar

### ISSUE THREAD

**Issue by comdevx** [nolimits4web/Framework7#691]
can't show tabs. but ios no issue http://www.idangero.us/framework7/docs/sub-navbar.html#.Vi-dvpegaP8

**Comment by nolimits4web** [comment]
And why it can't show tabs? What is your code or screenshot or better live example?

**Comment by comdevx** [comment]
![screenshot_2015-10-28-03-42-51](https://cloud.githubusercontent.com/assets/8242229/10772068/b77f1ba0-7d26-11e5-8618-efbf2c62e685.png)

https://www.dropbox.com/s/kmzyzhq8iwf7zrq/index.txt.txt?dl=0

build on phonegap

**Comment by nolimits4web** [comment]
`navbar-through` is not supported as well as "Through" type layout in general in Material theme http://www.idangero.us/framework7/docs/navbar-toolbar-layouts.html#through-layout
