### ISSUE TITLE
Unwanted navbar scroll on Cordova app

### ISSUE THREAD

**Issue by skycult** [nolimits4web/Framework7#692]
Using the kitchen-sink example I've created an example iOS Cordova App. All works fine, but when I try the form example and I focus an input field, the entire page scrolls up and the navbar disappears. How I can fix on to the navbar scrolling only the page content?
Thanks!

**Comment by nolimits4web** [comment]
This is default Cordova behavior. You need to use Keyboard plugin https://github.com/apache/cordova-plugins/tree/master/keyboard take a look at `disableScrollingInShrinkView` and `shrinkView` methods

**Comment by skycult** [comment]
Thanks!
