### ISSUE TITLE
Value Stepper for iOS

### ISSUE THREAD

**Issue by MauriceConrad** [nolimits4web/Framework7#694]
I'm new to your framework and because of that it's possible that I haven't found it, but in my opinion there is no value stepper for iOS.

Please look at my little project on GitHub:
https://github.com/MauriceConrad/stepper9/

If I'm right and there is really no module in your framework, please use it.

Maurice Conrad

**Comment by merlinn31** [comment]
I agree!

**Comment by J05HI** [comment]
@nolimits4web @valnub @ZanderBrown 
Can be closed because we have the Picker.
