### ISSUE TITLE
Include another js and work with yandex map api

### ISSUE THREAD

**Issue by AnotherAnkor** [nolimits4web/Framework7#699]
Hi everyone!
Now I try use yandex map api inside framework7 project.
But,  if js is not in app.js it  will be ignored.
I have one question: how I can include  ```<script src="https://api-maps.yandex.ru/2.1.29/?lang=ru_RU" type="text/javascript"></script>``` in framework7 project and work with it?

**Comment by nolimits4web** [comment]
I guess it is the same as here http://www.idangero.us/framework7/forum/#!/getting-started:how-to-use-jquery-in-projec
