### ISSUE TITLE
Navbar doesn't  stay the same in "Through" Layout 

### ISSUE THREAD

**Issue by ausiuming** [nolimits4web/Framework7#700]
I am trying to use the "Through" Layout, which the Navbar should stay the same through different pages. But I cannot make it work. Test link: http://demo.medcomhk.net/f7-test/

I have checked the examples in the Framework7 Docs. In "Navbars & Toolbars Layout" > "Through" Layout", the "Hello" and "World" links I suppose should demonstrate linking to other pages have no response.

In "Mixed" Layout, there is a typo: &lt;div class="pages navbar-through fixed-through"&gt; should be &lt;div class="pages navbar-through toolbar-fixed"&gt;

In "Cheat sheet" > "Fixed", .pages.navbar-fixed.navbar-through should be .pages.navbar-fixed.navbar-fixed.

**Comment by nolimits4web** [comment]
Ok, will check the typos. As for your navbar, don't enable `dynamicNavbar` to keep it same

**Comment by nolimits4web** [comment]
Typos are fixed. I guess we can close it for now
