### ISSUE TITLE
ajax json data

### ISSUE THREAD

**Issue by vhoxha08** [nolimits4web/Framework7#701]
Somehow i'm finding it impossible to send an ajax request with JSON post data. Whatever settings i choose in ajax config object it always converts it to form data

**Comment by nolimits4web** [comment]
```
var data = {foo: 'bar'};
$.ajax({
    url: '...',
    method: 'POST',
    processData: false,
    data: JSON.stringify(data)
})

**Comment by vhoxha08** [comment]
thnx
