### ISSUE TITLE
"chips" not available for custom build in gulp script

### ISSUE THREAD

**Issue by D1no** [nolimits4web/Framework7#703]
Seems like the new material `chips` component is not available in gulp custom build script.
```
Framework7 git:(master) ✗ gulp custom -chips
[17:57:56] TypeError: Cannot read property 'dependencies' of undefined
```

**Comment by nolimits4web** [comment]
Just added them to custom build. But chips are parts of core, not available as a module

**Comment by D1no** [comment]
Good enough 👍
On Mo., 9. Nov. 2015 at 13:25, Vladimir Kharlampidi <
notifications@github.com> wrote:

> Just added them to custom build. But chips are parts of core, not
> available as a module
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nolimits4web/Framework7/issues/703#issuecomment-155050444>
> .
>
-- 
Send from my Smartphone. Beware spelling and grammar.
-- 
Dino Scheidt
Tel.: +49 (0) 151 2265 6200
Luxemburger Str. 118 | 50939 Cologne | Germany
//Connect with me via LinkedIn.dino-scheidt.de
