### ISSUE TITLE
Cannot read property 'addClass' of undefined

### ISSUE THREAD

**Issue by iamxiaoma** [nolimits4web/Framework7#704]
// Initialize your app
    var myApp = new Framework7({
        pushStateRoot: pushStateRoot,
        //global: true,
        init: true,
        modalTitle: 'Framework7',
        animateNavBackIcon: true,

        pushState: true,
        pushStateSeparator: "",
        pushStateNoAnimation: true,  //设置为true,否则页面刷新的时候会先切换一下
        pushStatePreventOnLoad: false, //使用require.js则需要设置为false

        preloadPreviousPage: false,

        //statusbarOverlay: statusbarOverlay,
        scrollTopOnStatusbarClick: true,

        scrollTopOnNavbarClick: true,

        swipeBackPage: false, //开启/关闭滑动返回上一页功能。

};

    // Export selectors engine
    var $$ = Dom7;

    // Add main View
    var mainView = myApp.addView('.view-main', {
        // Enable dynamic Navbar
        dynamicNavbar: false,
        // Enable Dom Cache so we can use all inline pages
        domCache: true,
        //pushStateSeparator: ""
    });

The key code lines are   
1. swipeBackPage: false,
2.  dynamicNavbar: false,

Then it will cause the error: Cannot read property 'addClass' of undefined  in the router.js from line 
541.

**Comment by iamxiaoma** [comment]
thank you for fixing it.

**Comment by nolimits4web** [comment]
Thanks, fixed in dev version
