### ISSUE TITLE
Scrollbar scroller goes behind navbars and toolbars

### ISSUE THREAD

**Issue by mishoboss** [nolimits4web/Framework7#706]
Scrollbar scroller goes behind navbars and toolbars. Also it is noticeable if additional paddings applied to pages.

**Comment by nolimits4web** [comment]
It is by design, look at #690

**Comment by mishoboss** [comment]
Thanks for the info. Yes, seems logical. I applied custom CSS to fix this in cases when no backdrop or transparent navbars are needed. Also not needed for Material design.

**Comment by nournia** [comment]
Is it possible to introduce an option for showing proper scrollbar without having those features?
I'm showing quite large amount of text in Material Design and this beheaded scrollbar doesn't feel good.
