### ISSUE TITLE
Improve rendering performance for hair line

### ISSUE THREAD

**Issue by evolutionjay** [nolimits4web/Framework7#709]
F7 using hair line css is  :after.   is bad for rendering performance.
I suggest use:
@media screen and (-webkit-min-device-pixel-ratio: 2) {
.listItemClassName {
    background-position: left top;
    background-image: -webkit-gradient(linear,left bottom,left top,color-stop(0.5,transparent),color-stop(0.5,#e0e0e0));
    background-repeat: repeat-x;
    -webkit-background-size: 100% 1px;
}
}

**Comment by nolimits4web** [comment]
Sorry, but this is not an option for few reasons:
1) Why do you think that `:after` will perform worse than numerous `grandient`s background? Do you have some proof of this?
2) Such "background"-hairlines will bring huge limitation to styling and making impossible to use backgrounds in addition to hairlines on numerous elements

**Comment by evolutionjay** [comment]
Well, I've been tested on some of the old Android devices, and it's a practical background thread that makes the whole page scroll more fluid.
But this is the case for most of the next year, as China's handheld devices are out of hand.

**Comment by ikodota** [comment]
I have the same problem。you can visit url http://www.fmyangche.com/f7/kitchen-sink-ios/video/webwxgetvideo.mp4
