### ISSUE TITLE
Search + Virtual List cannot get it to work

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [nolimits4web/Framework7#712]
Hello Framework Team,

I cannot seem to get the Search + Virtual List to work. I use below code.
Can you advise how to do this?
```
<!-- We don't need full layout in this file because this page will be parsed with Ajax. It is just enough to put here .navbar and .page-->
 
<!-- Top Navbar-->
<div class="navbar">
  <div class="navbar-inner">
    <div class="left">
      <a href="#" class="back link">
        <i class="icon icon-back"></i>
        <span>Back</span>
       </a>
    </div>
    <div class="center sliding">7consumptionSearch</div>
    <div class="right">
      <a href="#" class="link icon-only open-panel"><i class="icon icon-bars"></i></a>
    </div>
  </div>
</div>
<div class="pages">
	<div data-page="7consumptionSearch" class="page">
	    <!-- Search bar -->
	    <form class="searchbar">
	        <div class="searchbar-input">
	            <input type="search" placeholder="Search">
	            <a href="#" class="searchbar-clear"></a>
	        </div>
	        <a href="#" class="searchbar-cancel">Cancel</a>
	    </form>
	    
	    <!-- Search bar overlay-->
	    <div class="searchbar-overlay"></div>
	    
	    <!-- Page content -->
	    <div class="page-content">
	        <div class="content-block searchbar-not-found">
	                Nothing found
	        </div>
	 
	        <div class="list-block list-block-search searchbar-found">
	            <ul>
	                ... list view items ...
	            </ul>
	        </div>
	    </div>
	</div>
</div>
```
And in my-app.js
```

myApp.onPageInit('7consumptionSearch', function (page) {

	var myList = myApp.virtualList('.list-block.virtual-list', {
	    items: [
	        {
	            title: 'Item 1',
	            picture: 'path/to/picture1.jpg'
	        },
	        {
	            title: 'Item 2',
	            picture: 'path/to/picture2.jpg'
	        },
	        {
	            title: 'Item 1000',
	            picture: 'path/to/picture1000.jpg'
	        },
	    ],
	    template: '<li class="item-content">' +
	                  '<div class="item-media"><img src="{{picture}}"></div>' +
	                  '<div class="item-inner">' +
	                      '<div class="item-title">{{title}}</div>' +
	                  '</div>' +
	               '</li>'
	});

	var mySearchbar = myApp.searchbar('.searchbar', {
	    searchList: '.list-block-search',
	    searchIn: '.item-title'
	});

})

```
Kind regards,
Mario

**Comment by nolimits4web** [comment]
Looks like you forgot to specify `searchByItem` or `searchAll` methods in Virtual List settings

**Comment by nolimits4web** [comment]
http://www.idangero.us/framework7/docs/virtual-list.html#using-with-search-bar

**Comment by MarioVanDenEijnde** [comment]
Hello nolimits4web,

Thanks for the feedback. We tried your tutorial in every possible way (except the right one obviously) but we did not succeed to get it working.
However we need to use the searchbar/result list with data from a local/remote database and we found an excellent example called "FW7_Autocomplete-master" which also was very helpfull understanding the template7 features.

But thanks for the excellent Framework it has great features and the inline page content was just what I was looking for ;-)

But while I have got your attention:
One example I am missing is "video" In our present solution we have got quite an issue showing Vimeo movies in the Android devices. In some it works and in some it just does not.
If you have got some material for me I would appreciate this.

Another thing is "sending json data to the next page". I have read in some post that sending between pages is only possible with strings. Now we have solved it using javascript calling the same data again in the new page.
We tried using "Template7.registerHelper('stringify', function (context){ return JSON.stringify(context[0]); });
But that did not seem to work return anything.
Can you advise the best way to send json to the next page ? We call the link from inside a template.

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
The last question I also asked in the following post: https://github.com/nolimits4web/Template7/issues/4

**Comment by nolimits4web** [comment]
Yes, using data-context it is not a bulletproof method, especially for deep and complex data, and you can always get into mess with quotes, which is also depends on quote type (single/double) you use for HTML attributes. This was just for example that it is possible. I would better stick with the calling router's method and passing context there: 

```
mainView.router.load({
    template: Template7.templates.someTemplate,
    context: data
});
```

or (in case you have enabled template7Pages and you store them in separate files)
```
mainView.router.load({
    url: 'something.html',
    context: data
});
```

**Comment by nolimits4web** [comment]
As for videos, not really sure what happens, but good practices here (like with YouTube in Cordova apps) is to use some native Cordova plugins or using Vimeo/YouTube API to get the source of the video and add it as <video> tag, try to avoid using iframes
