### ISSUE TITLE
Swiper + Tabbar,  the aotuplay does not work

### ISSUE THREAD

**Issue by MakeHui** [nolimits4web/Framework7#718]
```
<div data-pagination=".swiper-pagination-c1" data-space-between="30" data-autoplay="2500" data-autoplay-disable-on-interaction="false" class="swiper-container swiper-init ks-carousel-slider">
```

![](https://cloud.githubusercontent.com/assets/8622405/11290967/5ce4ee4c-8f76-11e5-8cb5-0f3d1f65f346.gif)

**Comment by nolimits4web** [comment]
It will be broken because Swiper became hidden. You need to `stopAutoplay` when tab containing it becomes invisible and `startAutoplay` when it becomes visible again

**Comment by MakeHui** [comment]
Thank you, it works. but Is this a possible bug?

```
$$('#view-1').on('show', function (e) {
  var mySwiper = $$('.swiper-container')[0].swiper;
  mySwiper.stopAutoplay();
  mySwiper.startAutoplay();
});
```

**Comment by nolimits4web** [comment]
Looks correct, no bugs should be there. But i would improve it as:
```
$('.view.tab').on('show', function (e){
  var mySwiper = $$('.swiper-container')[0].swiper;
  if ($(this).attr('id') === 'view-1') mySwiper.startAutoplay(); //tab with swiper became visible
  else mySwiper.stopAutoplay(); //other tab became visible
})

**Comment by MakeHui** [comment]
It is cool :)

**Comment by ryandong8321** [comment]
Hi @MakeHui ,
Could you please tell me how do you fix this problem you provided?
Thanks.

**Comment by MakeHui** [comment]
According to the owner, go back to `view-1` and re-execute `startAutoplay()`, but that's a long time ago, you can have a try.
