### ISSUE TITLE
Layout Grid: not responsive to device screen sizes

### ISSUE THREAD

**Issue by azn1viet** [nolimits4web/Framework7#722]
- current way is responsive to pre-assigned, meant if you have 2 columns, it would be 2 columns on both phone and tablet. What I meant here is if you have 320px and 1920px width of 2 devices, it just always display 2 columns. The responsiveness to the screens should be 12 columns on 1920px screens but remaining 2 columns in 320px screen.

Small screen break points

    |||
    |||
    |||

Big screen break points

    |||||||||||||
    |||||||||||||
    |||||||||||||

**Comment by nolimits4web** [comment]
It is mobile-only framework, and it supports 2-sizes: phone and tablet. You can do column like:
```
<div class="col-50 tablet-10">...</div>
```
It is explained in documentation http://www.idangero.us/framework7/docs/grid.html
