### ISSUE TITLE
Style bug

### ISSUE THREAD

**Issue by a-sydorenko** [nolimits4web/Framework7#723]
Hi. I'm use F7, and few days ago I noticed the error. Using hide toolbar on scroll page function parallel with styles /framework7.material.css, toolbar slideUp instead slideDown. 

I fix this problem change
.toolbar.toolbar-hidden:not(.messagebar){
   -webkit-transform:translate3d(0,-100%,0);
   transform:translate3d(0,-100%,0)
}
on
.toolbar.toolbar-hidden:not(.messagebar){
   -webkit-transform:translate3d(0,100%,0);
   transform:translate3d(0,100%,0)
}
So now it works.

P.S. Thank you for so good & smart framework!

**Comment by nolimits4web** [comment]
This is because toolbar in Material theme is on top, not on the bottom
