### ISSUE TITLE
Show query in url

### ISSUE THREAD

**Issue by Yokaze** [nolimits4web/Framework7#724]
with pushState there is no way for URL to contain the query

**Comment by nolimits4web** [comment]
Why? Can't see such issue

**Comment by Yokaze** [comment]
with pushState, add query into url, like "#profile?id=1" for direct page access

**Comment by nolimits4web** [comment]
This is because the URL like `/#!/#about?a=b` doesn't have much sense. But that `a=b` page query is still available in Page Data object where you can access it
