### ISSUE TITLE
Material : Tabs changing on scroll left or right

### ISSUE THREAD

**Issue by Adri-7** [nolimits4web/Framework7#725]
It would be cool if we could have scrolling tabs with Framework7 just like in most of the android applications.

**Comment by Adri-7** [comment]
It would be cool if we could have scrolling tabs with Framework7 just like in most of the android applications.

**Comment by nolimits4web** [comment]
There is a Swiper for that. Duplicate of #542

**Comment by Adri-7** [comment]
Ok thanks, I didn't see that before.
