### ISSUE TITLE
Material Design Tabs not being highlighted and not showing content on RTL

### ISSUE THREAD

**Issue by acalatrava** [nolimits4web/Framework7#726]
When you enable RTL mode the TABs on Material Design are not being highlighted. Only the first tab is highlighted and the animation is done from the wrong direction.

Also the animated tabs won't show the content, only the content of the first one.

![tabs_rtl_bug](https://cloud.githubusercontent.com/assets/8502129/11392498/748e5780-935a-11e5-836a-83b0d283dbce.gif)

**Comment by nolimits4web** [comment]
Are you sure you are using latest version?

**Comment by acalatrava** [comment]
Absolutely. In fact that is the kitchen sinc from the website.

**Comment by acalatrava** [comment]
*sink

**Comment by nolimits4web** [comment]
Can't see such issue. Where do you see this?

**Comment by acalatrava** [comment]
Just download the kitchen sink and add the material rtl css. Go to tabs and you will see it.

**Comment by nolimits4web** [comment]
Exactly, i can't see it, it works fine. At least in latest Chrome

**Comment by acalatrava** [comment]
I see that behavior in both Safari for Mac OSX and iPhone... I will wrap a project and upload it.

**Comment by acalatrava** [comment]
Ok, sorry about that, the problem is with my implementation... I detect that it is using a rtl language during the runtime and append the rtl css to the head. However because the app was previously initiated the transitions will not work as expected...

Any recommendations?

BTW, congratulations for this awesome framework ;)

**Comment by nolimits4web** [comment]
You can try to set `myApp.rtl = true` and `$('html').attr('dir', 'rtl')` after you add it. But i would recommend you before the app init

**Comment by acalatrava** [comment]
Thank you Vladimir. I will change the logic to the app and initialize it after add the RTL CSS.

Sorry about this time wasted! :-/
