### ISSUE TITLE
Ajax page: "navbar-through" works fine but "toolbar-through" does not

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [nolimits4web/Framework7#727]
I am scratching my head but I cannot get toolbar-through in an ajax page.
Should it work?
navbar is changing fine but the toolbar is not changing.
It is working fine for an inline page.
I am doing like cheatsheet below. I also tried putting the navbar and toolbar in the ajax page itself.
```
.view
  .navbar
  .pages.navbar-through.toolbar-through
    .page
      .page-content
  .toolbar
```
Please advise.

Kind regards,
Mario

**Comment by nolimits4web** [comment]
No, toolbar-through will stay the same for all pages, it doesn't updated for pages like navbar.

**Comment by MarioVanDenEijnde** [comment]
So I can only have a toolbar-through with inline pages?

**Comment by MarioVanDenEijnde** [comment]
What I actually wanted was to show an optional toolbar button on a certain page.
Can I read in javascript when a page is active?
And use this to do something like $('.classelement).show();

**Comment by MarioVanDenEijnde** [comment]
I expplored the tab-bar example and it seems that when I call a specific view like href="#view-2"
then I can get the toolbar with that view.
But this is not working when I call the page that is inside this view.
Can we call a page and tell to use a certain view?


We also tried your example like below but this does not change the toolbar
```
<div class="view view-main left-view">
  <div class="page" data-page="about-right">
    ... This page will be loaded when you click about.html link from Left view ...
  </div>          
</div>
```

**Comment by nolimits4web** [comment]
Don't mess Tab Bar app layout and Toolbar through-type. Toolbar's Through type layout is just about styling and visuals, in this case toolbar will be always visible and stays the same. If you want to show different toolbar for specific page, use fixed toolbar in that page and hide main tab bar toolbar

**Comment by nolimits4web** [comment]
You can see how it is done in Kitchen Sink toolbars examples

**Comment by MarioVanDenEijnde** [comment]
Is the Kitchen Sink example available online?
And which example in particular shoul I look at?

And about "hide main tab bar toolbar": What is the best way to only hide the toolbar for a specific page?
Thus if we go to another page it is showing again?

**Comment by nolimits4web** [comment]
It is available online here http://www.idangero.us/framework7/
Navbar & Toolbars -> Tab Bar you can see it hides main toolbar for this page

**Comment by MarioVanDenEijnde** [comment]
So basically it is just: use the classes: no-toolbar and toolbar-fixed

**Comment by nolimits4web** [comment]
Yes, you also need to add extra style/class to this page's toolbar to keep it visible with `no-toolbar` class

**Comment by MarioVanDenEijnde** [comment]
"need to add extra style/class to this page's toolbar to keep it visible "
which ones?
Indeed I don't see the toolbar.

**Comment by MarioVanDenEijnde** [comment]
I cannot spot extra style/class in your example.

**Comment by nolimits4web** [comment]
<img width="352" alt="s" src="https://cloud.githubusercontent.com/assets/999588/11405602/cfd542f2-93b9-11e5-8f52-9e412353d6a1.png">

**Comment by MarioVanDenEijnde** [comment]
Aha. So there is some puzzling todo.
I have to find out which [data-page="tabbar"] style does the trick.
And if I have more "custom" toolbar pages I probably will create a class for this?
I am not complaining about your excellent framework but I can presume this is a common request?

**Comment by MarioVanDenEijnde** [comment]
I think I have got it.
Not a big deal after all if you know the trick.

Thanks a lot.

One last Q for today:
When would you suggest using views instead of inline pages?

Kind regards,
Mario

**Comment by nolimits4web** [comment]
> When would you suggest using views instead of inline pages?

Views and Pages are different substances and not really replaceable. Please use Forum for questions in future
