### ISSUE TITLE
Default page in view is last one?

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [nolimits4web/Framework7#728]
Hello Framework team,

We explore the tab-bar example and added some pages in view-1.
It appears that the last page in the view is shown on default.
Is this by design or is there a setting we haven't used.

Kind regards,
Mario

**Comment by nolimits4web** [comment]
If you use Inline Pages then the active page the one which doesn't have "cached" classes. For other types of navigation it is not really allowed to multiple pages at the app start into single View

**Comment by MarioVanDenEijnde** [comment]
OK. Is mutliple pages in a view not allowed for the app start view? Or for all views?

**Comment by nolimits4web** [comment]
One page per view. If you need more pages (for some reason) then look at Inline Pages
