### ISSUE TITLE
Go back in navigation for inline pages

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [nolimits4web/Framework7#730]
Hello Framework team,

The way as described in your docs does not seem to fit
Below div is not closed in the page structure.directly after the opening tag but at the end of the page.

For the ajax pages you describe the same but we solved this using a custom navbar section.
```
<div class="page" data-page="about">
  <!-- Just add additional "back" class to link -->
  <a href="#index" class="back"> Go back to home page </a>
</div>
```
Can you advise?

Kind regards,
Mario

**Comment by nolimits4web** [comment]
Sorry, didn't understand, what is the issue?

**Comment by MarioVanDenEijnde** [comment]
I thought the code provided would introduce a back button on the navigation bar. But reading this better it only sets a link on the page.
So basically the question is how do I get a back button on the navbar of an inline page?

**Comment by nolimits4web** [comment]
Still not clear what do you mean. Back button in navbar is the same link, so the same `<a href="#index" class="back"> Go back to home page </a>`. You can also add force to skip pages in between `<a href="#index" class="back" data-force="true"> Go back to home page </a>`

**Comment by MarioVanDenEijnde** [comment]
OK. Then the question is how do I get a navbar on the inline page different from the one defined in the view?

**Comment by nolimits4web** [comment]
There is no something special about that for Inline Pages. It depends on what type of layout do you use for this View: Fixed, Static, Through or Through with Dynamic Navbar. All this is well described at http://www.idangero.us/framework7/docs/navbar-toolbar-layouts.html No?

**Comment by MarioVanDenEijnde** [comment]
Hello nolimits4web,

You are probably right. But I thought the "through" would allow a back button and a title the easy way.
Now I have to go from navbar on view level to a navbar on page level and I have to create navbars on every page.

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
Hello nolimits4web,

I have got a strange issue: 
I have got 2 icons on the main view navbar.
When I go to another page (twice) and then go back using the back button with every back button click one icon on the navbar dissappears.

Please advise.

Kind regards,
Mario

**Comment by nolimits4web** [comment]
Really hard to say without looking at live example or code snippets. But it is definitely something wrong with layout

**Comment by MarioVanDenEijnde** [comment]
Hello nolimits4web,

Our scenario is as follows:
We have an index.html page with a view and 2 inline pages: the "index" page and "page2"
The navbar and toolbar are on view level.
We also have another ajax page3.html. We call this page using <a href="page3.html" class="item-content item-link">link</a>
The ajax page3.html has got its own navbar and toolbar.

The issue is as follows:
We start from the main index page.
When we go to the ajax page3.html and go back everything works fine.
But when we go to inline page2 and from there go to the ajax page3.html and then go back we loose the icons.

Does this help to make it clear?

Kind regards,
Mario

**Comment by nolimits4web** [comment]
There is no difference what type of page you are loading. If you use dunamicNavbar then each page MUST have its  own navbar

**Comment by MarioVanDenEijnde** [comment]
Hello nolimits4web,

I will try to make an example.
But may I ask a different question: do you have an example how to filter a list view (using a smart select for example) immediately after making a selection?

Kind regards,
Mario

**Comment by nolimits4web** [comment]
Is it still actual?

**Comment by MarioVanDenEijnde** [comment]
My mistake. I should have read the documentation correctly.

Kind regards,
 Mario
