### ISSUE TITLE
parralax swiper in RTL app is broken

### ISSUE THREAD

**Issue by shaulhadar** [nolimits4web/Framework7#731]
Hello Vlad, when putting a parallax swiper in an RTL app, all the slides show on top of each other, and also slides don't take a whole page width....

Please fix this for the next update, thanks for your time man :)

Shaul.

**Comment by nolimits4web** [comment]
Thx, fixed in dev

**Comment by shaulhadar** [comment]
Hi Vlad, i saw you fixed the parallax in rtl, but there is still a small issue.
The background now ends and shows the white area too soon.  when i swipe to the left, i can see there is more of the background to the left... so this means that perhaps the background needs to be adjusted somehow a little bit... is there any chance you can fix this? or at least let me know how to fix this in an edit? thanks man...

**Comment by shaulhadar** [comment]
![f7p1](https://cloud.githubusercontent.com/assets/5478497/11649353/e17f825c-9d86-11e5-8983-3b786db611e0.png)

**Comment by shaulhadar** [comment]
Hi Vlad, after checking some css edits i think i found a fix, though i am not sure if its the permenant one...
here is the code:

.ks-parallax-slider .swiper-parallax-bg {
left: -230px;
}

If it helps in anything, its my pleasure, and if not, maybe it will help anybody who has this problem also...

**Comment by shaulhadar** [comment]
The fix is good on tablet but not on phone... well i will wait for a fix from vlad i guess :)

**Comment by nolimits4web** [comment]
It is not the issue. You just used KS's demo setup which is not for RTL. You need to change styles for background correctly. Probably change: 'left:0' to 'right:0'
