### ISSUE TITLE
F7 material, links are jot clickable 

### ISSUE THREAD

**Issue by KaveenR** [nolimits4web/Framework7#732]
I'm using F7 material for my project, and none of my links are clickable. 

When I comment out 'var my app = new Framework7()' the links are working but when the F7 js is included links cease to work this include ng-click events. The only way around for now is to include 'tab-link' as a class in the links, but I need things like Ajax loading which isn't working . My project is at stake please help me

**Comment by nolimits4web** [comment]
I have no idea. Issue is somewhere on your side because i guess you can't see such issue in Kitchen Sink demo? Also refer to correct Angular examples and templates

**Comment by KaveenR** [comment]
My bad, I haven't done my reading properly and I was freaked out, sorry for the inconvenience
