### ISSUE TITLE
Provide a compreensive example on how to switch views

### ISSUE THREAD

**Issue by jarodium** [nolimits4web/Framework7#734]
Hello there.

I have the following issue:
i have this struct:

.views
    .view.view-main
        .pages
            .page
                SPLASH SCREEN
    .view.view-first
        .pages
            .page
                ABOUT CONTENT

And I have fullfilled all init requirements for all views.
I wish to use JS to automatically go from one view-main to view-first's about page.
How do I achieve that?
According to the docs I could do:
´´´
firstView.router.load("pageName":"about");
´´´

This should result in hiding view-main and switch in view-first.
I don't want to place a link pointing to view-first since the slash screen may vary in content.
Also, i see that there is a getCurrentView method, but, a setCurrentView is not documented anywhere I can see, so I assume there is none.

Can someone point me in the right direction?

**Comment by nolimits4web** [comment]
You are doing something really wrong.
```
firstView.router.load("pageName":"about");
```
Will try to load `about` page into mainView. But you haven't such page there. You probably just need single view and put 2 pages there. Look at Inline Pages example: https://github.com/nolimits4web/Framework7/tree/master/examples/inline-pages

**Comment by jarodium** [comment]
Thank you for the reply.
I need 2 views because one is the splash screen ( which is the main view ) and the second view will have mostly the rest of the app. 
When the app is loaded, the second view should switch with the main view.
The examples show with view linking with links, but there is no documented example on to switch views...

I'll try to manually trigger the link and report back the results.

**Comment by jarodium** [comment]
<a href="#about" id="sl" data-view=".view-first"><img src="img/logo.png" class="col-auto"></a> does not work. This I suppose, is expected not to work.

I will try to work with a single view app then.

Thank you @nolimits4web :)
