### ISSUE TITLE
'complete' callback is not fired on ajax error

### ISSUE THREAD

**Issue by bullno1** [nolimits4web/Framework7#735]
It should be fired [here](https://github.com/nolimits4web/Framework7/blob/master/src/js/dom7-ajax.js#L237) and maybe [here](https://github.com/nolimits4web/Framework7/blob/master/src/js/dom7-ajax.js#L99) too.

**Comment by nolimits4web** [comment]
Who said that? Error is not the same as complete

**Comment by bullno1** [comment]
From this page: http://www.idangero.us/framework7/docs/dom.html#ajax

> A function to be called when the request finishes (after success and error callbacks are executed)

And this: http://www.idangero.us/framework7/docs/dom.html#ajax-events

> Event to be triggered when the request finishes (after success and error events are executed)

Firing only error without complete is inconsistent with what's written in the doc.

**Comment by nolimits4web** [comment]
The key phrase here is `when the request finishes` There are type of XHR errors when it can NOT be finished/executed/completed like No internet connection, File not found, etc. For usual errors - when server respond with error status and request is finished/completed, it will appear in `complete` callback
