### ISSUE TITLE
formFromJSON set field empty

### ISSUE THREAD

**Issue by ipfung** [nolimits4web/Framework7#737]
When passing 
<code>
myApp.formFromJSON{
  lastName: '',
  firstName: 'Peter'
}
</code>

Found that formFromJSON() will bypass lastName field because of below code:

``` javascript
   if (!formData[name]) return;
```

change to 

``` javascript
   if (formData[name] == undefined) return;
```

resolve it.

**Comment by unstableair** [comment]
I've also encountered this bug.
