### ISSUE TITLE
Notifications on Material Design will close without animation on Safari

### ISSUE THREAD

**Issue by acalatrava** [nolimits4web/Framework7#738]
It seems that Notifications on Material Design will not animate when closing on Safari (and therefore on Cordova apps). However they work fine under Chrome.

Here you can see what I mean:
![notifications_issue](https://cloud.githubusercontent.com/assets/8502129/11555992/5048f786-99a4-11e5-8c89-61a2a619c387.gif)

**Comment by nolimits4web** [comment]
Yes, it is due to Safari bug. But Material theme is intended to be used in Android apps, in Chrome :)

**Comment by acalatrava** [comment]
I insertando but I'm planning to develop an app on material theme both for iOS and Android. I think it's best to use the same theme so the app is homogeneous. I will try to find a workaround for this...

Also, is there any way to add a "link" to the notification so you can click on it to do some action and not only close it?

**Comment by nolimits4web** [comment]
There is a `onClick` callback available for that when you add notification
