### ISSUE TITLE
disable open page twice

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [nolimits4web/Framework7#739]
Hello Framework7 team,

This is driving me crazy. Can you please help me.
Is it possible to have a page open only once?
We have a popover with several buttons: (page1, page2,)
When we open page1 -> page2 -> page1 they all open a new page.
Is there a way to prevent this and have the second time we open page1 to go back to the already opened page1.
Or if this is not possible skip history all the way?

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
I have found a possible route but encounter an issue:
I have tried following code:
```
	for (var i = 0; i < mainView.history.length; i++) {
	  if (mainView.history[i] === '7foodSearch.html') mainView.router.back({url: '7foodSearch.html', force: true});
	}

The "force: true" makes the navigation jumps right back to the wanted page.
But on our search page we have got a template7 listview.
When the backjump is only 1 step then the template is rendered fine.
But when the backjump is 2 steps the template is not rendered with data anymore.

Can you advise how to overcome this?

Kind regards,
Mario

```

**Comment by MarioVanDenEijnde** [comment]
I found out this only occurs using an ajax page. Not an inline page. So now I am switching to inline.

**Comment by snowbreeze** [comment]
Was this resolved, I am still facing this. i use ajax pages, but my home page is an inline page isnide the main view.
