### ISSUE TITLE
Menus [feature request]

### ISSUE THREAD

**Issue by jarodium** [nolimits4web/Framework7#740]
Hello

Does framework7 will implement the Menu component to Material option in the new future?
https://www.google.com/design/spec/components/menus.html#

**Comment by nolimits4web** [comment]
Not in plans as it is not really Mobile component. For mobile you have Popover

**Comment by jarodium** [comment]
I see.
Other component it should be able to provide is the timepicker. Is that is not in the plans this codepen should prove useful: http://codepen.io/SimeonC/pen/XJdWPy

I know there is already a timepicker in the example for iOS theme, but since the framework provides Material theme, the picker for time inputs should be also available.

**Comment by nolimits4web** [comment]
Sorry, i am not sure that i want to implement and so much of code because of just Material time picker. At least not in near future, and `<input type="time">` still works good in Android
