### ISSUE TITLE
Redirection Issue

### ISSUE THREAD

**Issue by karthikeyan-perpetua** [nolimits4web/Framework7#743]
Hi all.
@nolimits4web 

We have 3 pages,

1.Index.html - Login Form
2.Content.html  
3.Details.html 

I am new to Framework7 . 

I have used default form (ajax-submit) in Framework7. In ajax success function , i have redirected index page to Content.html using appView.router.loadPage(redirectURL); It works fine but the problem happened on Details.html , If we click back button on Details.html it goes to Content.html Correctly but in javascript it trigger as index.html

I have removed Navigation bar and Sidebar in index.html using 

$$(document).on('pageInit', function (e) { 

		var page = e.detail.page; 

		if (page.name === 'index') { 

})

But it will trigger on Content.html page, 

I think redirect was not working properly. Please tell me how to handle these types of issue. 

FYI:

Form Submit Code:

                        $$('form.ajax-submit').on('submitted', function (e) { 
			var xhr = e.detail.xhr;  
			var json = e.detail.data;   
			var jsonParse = JSON.parse(json); 
			if(jsonParse!='false') 
			{    
				appView.router.loadPage('contents.html'); 
                        }
                        })

Thanks in advance

**Comment by karthikeyan-perpetua** [comment]
@nolimits4web 

HI,

Then i have tried the below code,

appView.router.back({url: redirectURL, force: true}); 

It works fine. But i can't able to find how it works.

If we use this code, we can't able to goBack ? 

If yes please tell me how to give go back url manually. 

Thanks in advance.

**Comment by nolimits4web** [comment]
Can you post the whole code that page, not by parts?

**Comment by nolimits4web** [comment]
I think what you mean, that when you go back from Details to Content you see pageInit event for Index page? This is correct, because F7 preloads index page when you to Content page which is already initialized and pageInit event won't be triggered for it. Use `pageBeforeAnimation` callback instead if you need to track when you go back from Details to Content

**Comment by karthikeyan-perpetua** [comment]
@nolimits4web 

Thank you .. Let me check it.

**Comment by sdjoyson** [comment]
Help me to run this function.
//home.html
$$('.fa-camera').on('click', function () {
          mainView.router.loadPage('profile.html',function(){
             capturePhoto(); // profile.html page function // 
        });
    });
//end home.html
