### ISSUE TITLE
swipeout with link element documentation

### ISSUE THREAD

**Issue by unstableair** [nolimits4web/Framework7#745]
Documentation for swipeout with link elements  gives the following example:

````
<li class="swipeout">
  <a href="#" class="swipeout-content item-content item-link">
    <div class="item-media">...</div>
    <div class="item-inner">...</div>
  </a>
  <div class="swipeout-actions-right">
    <a href="#">Action 1</a>
    <a href="#">Action 2</a>
  </div>
</li>
````

However this results in a lot of animation lag when swiping and poor user experience.

Kitchen sink moves the 'swipeout-content'  into a wrapping div which results in much smoother animation. Recommend update to documentation.

````
<li class="swipeout">
  <div class="swipeout-content">
    <a href="#" class="item-link item-content">
````

**Comment by nolimits4web** [comment]
There shouldn't be much difference in this case. I will check it. On what device have you tested it?

**Comment by unstableair** [comment]
iOS9 iPhone 6 (also Safari on osx). The problem is very noticable with poor sync between the movement of the content and actions.

**Comment by nolimits4web** [comment]
Ok, will double check it

**Comment by unstableair** [comment]
simple codepen to help illustrate the issue.

http://codepen.io/unstableair/pen/mVJVmv

**Comment by nolimits4web** [comment]
Thanks, will fix it

**Comment by brunoserra** [comment]
Was this issue fixed? I'm having the same problem

**Comment by unstableair** [comment]
Yes. The documentation has been updated with the suggested amendment. See my original post on this thread for details.

**Comment by pluckannfeel** [comment]
swipeout have issues when swiping, the action buttons will disappear and then its goes back again like a glitch
