### ISSUE TITLE
Some of the tutorial codes are outdated and not working. 

### ISSUE THREAD

**Issue by humbleBeginner** [nolimits4web/Framework7#747]
### Here are some of the links 

[iOS theme to Material theme migration](http://www.idangero.us/framework7/tutorials/tips-to-migrate-ios-theme-app-to-material-theme.html)

[maintining both themes in a single app](http://www.idangero.us/framework7/tutorials/maintain-both-ios-and-material-themes-in-single-app.html)

**Comment by nolimits4web** [comment]
No, they are up to date
