### ISSUE TITLE
pickerModal should trim whitespace or ignore text elements

### ISSUE THREAD

**Issue by tbcrowe** [nolimits4web/Framework7#748]
I ran into a problem with pickerModal when I loaded the HTML for the picker from a script template.  The problem was that the leading and trailing space returned by Dom7.html() were being added as text elements in the pickerModel function that in turn would cause errors when Dom7.show() attempted to set style.display='block' on them.  There are several different ways this problem can be fixed, but I'm not sure which is best.  For now, I have just added a trim() call to the HTML before calling pickerModal.  It may be best to simply add a check in Dom7.show() before attempting to set the style property as that would catch similar problems in much more general situations.  Alternatively/addiitionally, perhaps Dom7.html() should auto-trim leading/trailing space.

**Comment by nolimits4web** [comment]
Ok, see the issue. Will fix it
