### ISSUE TITLE
[Issue] Preloader and arrow from Pull To Refresh - Material design

### ISSUE THREAD

**Issue by djap96** [nolimits4web/Framework7#749]
This works perfectly with iOS.css but with material doesn't show at all.
I'm using 1.4.0 Release.
The event forks perfectly, is just the aesthetics.

With iOS:
![1](https://cloud.githubusercontent.com/assets/9372893/11664842/f319c1d2-9db1-11e5-80c9-8e965763078b.PNG)
![2](https://cloud.githubusercontent.com/assets/9372893/11664843/f31c7260-9db1-11e5-9847-2242b7b124a4.PNG)

With Material:
![3](https://cloud.githubusercontent.com/assets/9372893/11664853/08234c74-9db2-11e5-900a-9216b8bfddfe.PNG)
![4](https://cloud.githubusercontent.com/assets/9372893/11664854/083d43d6-9db2-11e5-930c-1fde59ec5bcc.PNG)

**Comment by nolimits4web** [comment]
That is something wrong with layout. Do you have a live link so i can check it?

**Comment by brayancruces** [comment]
https://interfaces-djap96.c9users.io/index.html

**Comment by brayancruces** [comment]
Bad configuration, maybe.

**Comment by nolimits4web** [comment]
PTR layer is not visible in this case because you need to add `padding-top:48px` to that page-content. Also for material theme you need to pass `material:true` when you init app

**Comment by djap96** [comment]
Thank you a lot! i was missing the padding, works insanely perfect! Thanks a lot again and sorry, that was my bad
