### ISSUE TITLE
Picker Modals aren't actually modal

### ISSUE THREAD

**Issue by tbcrowe** [nolimits4web/Framework7#750]
I've run into another problem with picker modals.  They're not actually modal.  I've tried loading them via the simplified method (static html) and via javascript; in neither case are they modal.  By not modal I mean that I'm able to click links and otherwise interact with the app in areas not covered by the picker modal.  As with other modals, these areas should not be interactive while the picker is displayed.

This is using the iOS theme, by the way.  I've reviewed the source to see if there was an obvious fix and I see the code works differently for the Material theme.

**Comment by nolimits4web** [comment]
They are. And they shouldn't have overlay by default. Checkout Picker and Calendar components, the rest of the page should be usable, it is by design. Otherwise use something different or add and customise overlay div manually

**Comment by tbcrowe** [comment]
Alright.  Thanks for clarifying.  Sounds like we just have a difference in terminology.  I've made the min-height for the picker 100% to work around this.

**Comment by nolimits4web** [comment]
But with 100% height it is the same as Popup, which is has background overlay :)

**Comment by tbcrowe** [comment]
Heh.  Good point.  I've switched to a popup and done away with my CSS hack.  Thanks.
