### ISSUE TITLE
Page Issues 

### ISSUE THREAD

**Issue by karthikeyan-perpetua** [nolimits4web/Framework7#752]
@nolimits4web 

$$(document).on('pageAfterAnimation', function (e) { 
var page = e.detail.page; 
if(page.name === 'trackerMap')
{
setInterval(function(){ 
console.log('Running...');
},14000); 	
}
})

I used above code , if click back button from template.html it goes to index.html(I have not used back function , linked index.html manually because template.html doesn't have back history) ,here also that interval function called.

Can't able to fix that issue.

Tried pageInit function also. How to trigger only center page. ? 

````
<div class="page page-on-left" data-page=" template.html">...content...</div>
<div class="page page-on-center" data-page="index.html">...content...</div>

I have using the following html to redirect

<div class="left sliding"><a href="template.html"   class="link"><i class="icon icon-back"></i><span>Home</span></a></div>
`````

**Comment by nolimits4web** [comment]
Sorry, your question is how use intervals in general. Just save its ID to some variable and do `clearTimeout` when you go to another page

**Comment by karthikeyan-perpetua** [comment]
@nolimits4web

Thanks for your quick response.

Sorry, i can't get you. I just want you to know how to trigger center page only. 

````clearTimeout```` - How it works ? any example for this

**Comment by karthikeyan-perpetua** [comment]
@nolimits4web 

Sorry , That issue fixed. Thanks for your time and quick response.
