### ISSUE TITLE
Abount Template7.compile QA

### ISSUE THREAD

**Issue by pccai** [nolimits4web/Framework7#756]
When we used "var template = Template7.compile('about.html');", but in about.html page we used a hidden field control:  " input id=procinstid value={{url_query.procinstid}} type=hidden" and a placeholder {{chs_back}}, the {{url_query.procinstid}} cannot compiled valid?

**Comment by nolimits4web** [comment]
You can't pass file name/path like `about.html`) to the `compile` method. It should be direct template string like: `var template = Template7.compile('input id=procinstid value={{url_query.procinstid}}');`
