### ISSUE TITLE
Typescript definitions?

### ISSUE THREAD

**Issue by MrAndMrsK** [nolimits4web/Framework7#758]
I can't find the .d.ts files for Framework 7 anywhere.  Do they not exist yet?  Is there a technical reason why Framework7 is not compatible with typescript definitions?  (like an api style that cannot be easily defined).

**Comment by nolimits4web** [comment]
No, they not exist, and won't be in near future

**Comment by MrAndMrsK** [comment]
Well I made some here:  https://github.com/MrAndMrsK/Framework7.d.ts

**Comment by nolimits4web** [comment]
Thanks, will check it. But as you see there are too many methods which can accepts different sets of arguments, so it is not easy to define them all

**Comment by MrAndMrsK** [comment]
Ok.  But in case you haven't spent much time evaluating typescript, you can overload function signatures like I did for showProgressbar.  (I'm not saying that these signatures are absolutely correct but it demonstrates that typescript can express overloads).

```typescript
showProgressbar(container : HTMLElement | string | Dom7.Dom7, color : string): void;
showProgressbar(progress : number, color : string): void;
showProgressbar(container : HTMLElement | string | Dom7.Dom7, progress : number, color : string): void;
showProgressbar(): void;
```

**Comment by nolimits4web** [comment]
Ok, thanks. Will get deeper when i have enough time
