### ISSUE TITLE
How to repeat the ajax request after timeout ajax error?

### ISSUE THREAD

**Issue by shastox** [nolimits4web/Framework7#759]
I want to show a message, if there is no Internet, when the user clicks on the link:

```
$$.ajaxSetup({
    timeout : 3000,
    error: function (xhr, status) {
        if ( status === "timeout") {
            myApp.alert("No internet connection", 'Error!');
        }
    }
});
```

After receiving the error, click on the link does not cause any actions (do not send ajax request).

**Comment by GuillaumeBiton** [comment]
Maybe You should compare to 408 http statuts code : request timeout

    If ( status === 408 ) {

**Comment by shastox** [comment]
You did not understand me.

Steps:

1. Click on the link "<a href="page.php">Page</a>"

2. Framework7 create ajax request to "page.php"

3. Timeout error. 

4. Alert: myApp.alert("No internet connection", 'Error!');

5. Click on the link "<a href="page.php">Page</a>": Nothing happens.

To restore the link operability, you need to restart the browser.

Sorry for my English.

**Comment by shastox** [comment]
I found the solution:

```
$$.ajaxSetup({
    timeout : 5000,
    error: function (xhr, status) {
        if ( status === "timeout") {
            setTimeout(function() {
                //Delete from cache!
                myApp.removeFromCache(xhr.requestUrl);
            }, 1000);
            myApp.alert("No internet connection", 'Error!');
        }
    }
});
```
Because: https://github.com/nolimits4web/Framework7/blob/master/dist/js/framework7.js#L1673
This line call first: 

```callback(xhr.responseText, true);```

And then:

```if (app.params.onAjaxError) app.params.onAjaxError(xhr);```

I can not write:
```
$$.ajaxSetup({
    timeout : 5000,
    error: function (xhr, status) {
        if ( status === "timeout") {
            //Dont' work! Because app.cache is empty!!
            myApp.removeFromCache(xhr.requestUrl);

            myApp.alert("No internet connection", 'Error!');
        }
    }
});
```

**Comment by shastox** [comment]
I believe that this code must be added to the documentation.

**Comment by nolimits4web** [comment]
So i guess it is solved
