### ISSUE TITLE
Problems with route.back(options)

### ISSUE THREAD

**Issue by lanlanx** [nolimits4web/Framework7#760]
In the Router's API, I found that mainView.router.back(options) accepts the param 'url' and 'pageName'.
Now my history is ['http://localhost', 'category', 'product'] and I want to back to root page directly
I've tried using mainView.router.back({url:'http://localhost'}) and  mainView.router.back({pageName:'index'}), but neither of them works.

I want to know what's the problem is and how to do?

**Comment by nolimits4web** [comment]
Use `force: true`
