### ISSUE TITLE
Add method app.updateCache(url, content)

### ISSUE THREAD

**Issue by shastox** [nolimits4web/Framework7#761]
This method is very necessary.

For example, by steps:
1. Open the "page1.html"
2. There is DOM manipulation, for example: `$$(...).show();`
3. Click on link to "page2.html"
4. Click on "Back". All DOM manipulations is lost.

**Comment by nolimits4web** [comment]
There is `domCache` parameter for that, it keeps "back" pages in history

**Comment by ZanderBrown** [comment]
This seems to be resolved.
