### ISSUE TITLE
anchor link

### ISSUE THREAD

**Issue by azn1viet** [nolimits4web/Framework7#763]
Because my app page is long and separated in sections, I'd need an anchor link smooth scrolling from position 1 ID to position 4th ID, for example.

I couldn't find such feature and I've tried to add the script myself but it doesn't work since it's conflicted with the framework "href=#" tag. Am I missing something?

Please add the feature if not already.

Thanks.

**Comment by nolimits4web** [comment]
forum search can be helpful http://www.idangero.us/framework7/forum/#!/questions:scroll-to-div
