### ISSUE TITLE
Swiper autoplay in Tabbar Page 

### ISSUE THREAD

**Issue by boboxiaodd** [nolimits4web/Framework7#764]
I found that, in Tabbar , View1 change to View2 or View3 , about 5 sec. later,  Timer in View1 had Cleaned , so my Swiper in View1 can not autoplay ,   we must restart timer when Tabbar change to View1.

the method startAutoplay()  include 

       if (typeof s.autoplayTimeoutId !== 'undefined') return false;

and  stopAutoplay() include:

       if (!s.autoplayTimeoutId) return;

so can not use to restart timer, but we can use undocument method  pauseAutoplay() 

       mySwiper.autoplayPaused = false;
       mySwiper.pauseAutoplay(0);

if i set loop:true ,it don't work,  i think swiper need to add a method to restart timer when switch View.

**Comment by nolimits4web** [comment]
It won't be added as there are too many ways which can produce this issue which is cased by swiper hidden container. Just use Swiper's `stopAutoplay` when tab with it becomes hidden and `startAutoplay` when it becomes visible again.
