### ISSUE TITLE
Added dom doesn't disappear after returning to previous page

### ISSUE THREAD

**Issue by dspjm** [nolimits4web/Framework7#767]
For example, when I use the single view demo, within the framework7 package, under dist/index.html.

When I get into about page and type this in console, 

```$$('.list-block ul').append('<li>hi</li>')```

a row of hi will be added,

But when I click the back button and return to index, the column would not disappear.

**Comment by nolimits4web** [comment]
Why should it disappear? Previous page is kept in DOM

**Comment by dspjm** [comment]
Ok, I see.
