### ISSUE TITLE
use f7 in Safari9, something goes error

### ISSUE THREAD

**Issue by hyc94** [nolimits4web/Framework7#770]
When I use f7 in Safari9, error occurs:
SyntaxError: DOM Exception 12: An invalid or illegal string was specified.
framework7.js(line46): An invalid  or illegal string was specified

**Comment by nolimits4web** [comment]
Looks like issue on your side. Please provide some example

**Comment by hyc94** [comment]
Yes，I found error on my code，I'm sorry
