### ISSUE TITLE
Data lost after changing template data.

### ISSUE THREAD

**Issue by dspjm** [nolimits4web/Framework7#771]
I use template7 to load a page.

After I alter the data with app.template7Data.data, then use view.route.refreshPage() to show the updated content. The data is not shown at all.

By the way, there is no Templates global variable as documented in the doc.

```
> Templates
VM600:2 Uncaught ReferenceError: Templates is not defined(…)
```

**Comment by nolimits4web** [comment]
Won't work because i guess you have loaded it like `a(href="somepage.html", data-context-name="somecontext")` To reload it you need to use full router API like:
```
mainView.router.load({
    url: 'somepage.html',
    reload: true,
    context: somecontext
});
```

> By the way, there is no Templates global variable as documented in the doc.

There is no such in docs. It is `Template7.templates` or `app.templates`

**Comment by dspjm** [comment]
In http://www.idangero.us/framework7/docs/template7-pages.html#access-and-modify-templates-pages-data

We may access and modify specified template7Data in any moment. It is accessible in global Templates.data object, or in its alias myApp.template7Data

**Comment by nolimits4web** [comment]
Ok, it is issue in docs, should be `Template7.data`

**Comment by nolimits4web** [comment]
Fixed in docs
