### ISSUE TITLE
Unable to listen on page events like pageInit, pageReinit, etc. When used with require.js, and knockout.js components

### ISSUE THREAD

**Issue by humbleBeginner** [nolimits4web/Framework7#776]
I put my app initialization file into a separate module, something like this:
![blahadsf](https://cloud.githubusercontent.com/assets/7194216/12057606/b4189a66-af7d-11e5-89fd-a12041617e44.PNG)

Then I required the module into the main.js, and set up the event listener like this(all my pages are inlined)
![balh](https://cloud.githubusercontent.com/assets/7194216/12057644/04e3b80e-af7e-11e5-8823-6eff04dfcc39.PNG)

BUT, it can't listen to page events.

**Comment by humbleBeginner** [comment]
@nolimits4web Sir can you help me with this?

**Comment by nolimits4web** [comment]
Hard to say as i'm not a require.js pro. Did you look at require demo app?

**Comment by humbleBeginner** [comment]
Yes sir. I had a look at it already. 
When I use 
```
$(document).on('pageBeforeInit') 
```
inside of my module for example, it will detect that event, but when I use App.onPageBeforeInit() it's not working

**Comment by nolimits4web** [comment]
Then it would be good to see live example, it is hard to understand where is the issue without it

**Comment by humbleBeginner** [comment]
@nolimits4web I will make a demo later on sir, so that you can check. Thank you

**Comment by humbleBeginner** [comment]
@nolimits4web Sir, my code is similar to this http://www.idangero.us/framework7/tutorials/mobile-mvc-apps-with-framework7-requirejs-and-handlerbars.html. I did not have a time to make a demo today, maybe later on after my work. But, for now sir maybe you take a look at that. Please. Thank you.

**Comment by humbleBeginner** [comment]
@nolimits4web Sir, here's my test app, btw I'm also using knockout.js for the component, and databindings

I inlined my pages so that knockout can bind on those pages, knockout can't bind on dynamically created page. I also used the ko's component to make a component of each page, (e.g. <index-page></index-page> to clean things up as I'm using inline pages.

The other issue I've found is, when I access a page for example about page, and when I click the back button, it's not working. Maybe it's an issue with knockout? Or require?

<a href="https://drive.google.com/open?id=0B4yi3z3m3Q53OWVTaEtBcHZVcGM">Link to test app</a>

**Comment by nolimits4web** [comment]
The link is private, can't access to it

**Comment by humbleBeginner** [comment]
@nolimits4web  Sorry sir. Here's the updated <a href="https://drive.google.com/file/d/0B4yi3z3m3Q53OWVTaEtBcHZVcGM/view?usp=sharing">link</a>.

Framework7 seems like it does not like knockout.js component binding sir. I made another simple app just now without it and everything works.

**Comment by nolimits4web** [comment]
That means the problem somewhere in knockout-part, sorry i'm not familiar with it so won't be able to help much with it

**Comment by ZanderBrown** [comment]
Out of scope + no response
