### ISSUE TITLE
swiper within popup bug?

### ISSUE THREAD

**Issue by MrAndMrsK** [nolimits4web/Framework7#777]
I have a swiper in a popup.  If I put the swiper in a `.page`, it works fine, but if I move it to a `.popup`, it still mostly initializes but the bullets and paging work as if there's only one slide.  The second slide *is visible* if you drag, but you can't actually swipe to it - it just snaps back.  It is the only swiper in the app.

I've tried adding a `.page-content` wrapper to the popup but that doesn't seem to be what it needs.

Is there a workaround?

**Comment by nolimits4web** [comment]
It is because swiper is invisible when you initialize it. Call swiper's `.update()` method when your popup with swiper becomes visible

**Comment by MrAndMrsK** [comment]
Awesome, thanks!  

Should the `.swiper-init` be honored in this situation (as a bug?)
