### ISSUE TITLE
Supply modal 'open' event listener on creation

### ISSUE THREAD

**Issue by hvt** [nolimits4web/Framework7#779]
When you create a modal using JavaScript, it would be nice to have the ability to attach an `open` event listener immediately. This can, for example, be of help when you want to fill the contents of a 'prompt-like' input field.

I have something like this in mind:

```javascript
myApp.modal({
  title: 'Prompt',
  text: 'Enter some text',
  onOpen: function(modal) {
    $$(modal).find('input[type="text"]').val('some preset prompt value');
  }
});
```

Or perhaps I am missing something, and would something like this already be possible using the current API.

**Comment by nolimits4web** [comment]
```
var modal = myApp.modal({
  title: 'Prompt',
  text: 'Enter some text',
});

$$(modal).find('input[type="text"]').val('some preset prompt value');
```
