### ISSUE TITLE
searchbar-input bug in wechat browser on Android

### ISSUE THREAD

**Issue by Poordeveloper** [nolimits4web/Framework7#780]
.searchbar-input{width:100%;height:28px;position:relative;-webkit-flex-shrink:1;-ms-flex:0 1 auto;flex-shrink:1}

in wechat browser, "cancel' button on the right side can not be shown. I solved with below change.

.searchbar-input2 {
    -webkit-box-flex: 1;
    -webkit-flex: 1;
    -ms-flex: 1;
    flex: 1;
    height: 28px;
    position: relative;
}

**Comment by nolimits4web** [comment]
Sorry, don't know what is wechat browser. On Android it is only Chrome and default browser (4.4+) are supported
