### ISSUE TITLE
Can't use rich text editor

### ISSUE THREAD

**Issue by questionlin** [nolimits4web/Framework7#782]
I can't use any rich text editor in Framework7, no matter `<div contenteditable="true"></div>` or `<iframe></iframe>`

**Comment by nolimits4web** [comment]
Would be good to see live example with the issue, especially with iframe case

**Comment by nolimits4web** [comment]
As for contenteditable just add `no-fastclick` class to that container

**Comment by questionlin** [comment]
Thank you for replying so fast. It works when added `no-fastclick` class. `<iframe></iframe>` also works without that. I made a mistake.

**Comment by chenkun24** [comment]
It seems that adding `no-fastclick` to that container would cause other problems. For example, `taphold` event will fire when the container is scrolling. While problem does not happen without `no-fastclick`.

**Comment by imrealashu** [comment]
@questionlin which editor have you used ?

**Comment by manuelph** [comment]
If you're using Handlebars, you can also use {{{ }}} triple mustache, for it to be rendered as HTML inside container

<div contenteditable="true" class="no-fastclick">{{{ data.note }}}</div>
