### ISSUE TITLE
How can I include query string in window.location.href?

### ISSUE THREAD

**Issue by Poordeveloper** [nolimits4web/Framework7#783]
I can get query via page.query, but window.location.href does not show the string. This is useful when somebody wanna share the page.

**Comment by nolimits4web** [comment]
You need to enable `pushState` if you want to have different URLs

**Comment by Poordeveloper** [comment]
I have enabled pushState and I can see something like http://localhost:3000/#!/#cars. My link is #cars?id=100, I can not see ?id=100 part.
