### ISSUE TITLE
Unable to pick a value with autocomplete on Android

### ISSUE THREAD

**Issue by ecordani** [nolimits4web/Framework7#784]
Hi,
I'm developing an iOS/Android app that uses the new autocomplete component but while on iOS it works perfectly, on Android when I tap on a value the dropdown list disappear with nothing selected.
This behaviour occurs both on physical device and on emulator (Genymotion).

**Comment by nolimits4web** [comment]
Android version? Do you have same issue in Kitchen Sink demo on website for Material theme?

**Comment by ecordani** [comment]
Genymotion:
- Android v. 4.1.1 & v.5.1.0
Real device with v.4.2.1
Yes, I've tested also the Kitchen Sink in fullscreen and got the same error.

**Comment by nolimits4web** [comment]
Ok, see that. Will check it
