### ISSUE TITLE
Looking for Sticky elements on scroll

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#786]
WayPoint Sticky is working with Framework7

https://github.com/imakewebthings/jquery-waypoints 

var waypoint = new Waypoint.Sticky({
      element: $('.basic-sticky-example')[0], //document.getElementById('trigger-point-example'),        
      handler: function(direction) {
          //console.log($(this));
          console.log('Trigger point: ' + this.triggerPoint)
      },
      offset : 'bottom-in-view'
        //offset: 'right-in-view'
    });

Applying offset as number/perc is not responding.

Also window.scrollY is always '0' - F7 pages.

Can you please assist me on this.

**Comment by nolimits4web** [comment]
Window is not scrolling in Framework7, it is `page-content`, so you need to change in this lib to listen scrolling on that div instead of window or maybe it has such option/parameter

**Comment by murliatdure** [comment]
Unable to get the scrollY on page-content element.

![image](https://cloud.githubusercontent.com/assets/7137859/12227351/50348be0-b851-11e5-9391-f91ebf32e804.png)

Do we have some simpler options for handling the same?
