### ISSUE TITLE
Feature: Ability to reset page history when using router.back or router.load

### ISSUE THREAD

**Issue by tbcrowe** [nolimits4web/Framework7#789]
I previously requested a feature similar to this in the forums ("View noHistory option").  What I'm looking for is some way to reset the page history.  I provided two scenarios in that post, but another one is:
I have an app that has a logged in/out state.  The user can navigate several pages deep into the page hierarchy.  When they become logged out (either because their session times out or because they click a "logout" button available in the UI) I display the special login view.  After they log back in, though, the previous view (potentially multiple pages deep) is displayed again.  Instead, I need to take them back to the "home" page. 

I've tried using app.mainView.router.back({ url: 'home.html', force: true }) but that only pops one page off the history stack.  Similarly, app.mainView.router.load({ url: 'home.html' }) doesn't clear the history stack.  Both options load the "home" page, but leave the previous pages in the history.

Is there any way to clear the page history using existing functionality?  If not, would it be possible to add a "reset" option to the back/load methods to do this?

**Comment by nolimits4web** [comment]
> I've tried using app.mainView.router.back({ url: 'home.html', force: true }) but that only pops one page off the history stack

Then url passed here is wrong. Use it like:
```js
app.mainView.router.back({ url: app.mainView.history[0], force: true })

**Comment by tbcrowe** [comment]
Thanks! Using the history object for the url value was the trick.  I hadn't thought of that.  Evidently, the URLs I'd tried HAD NOT matched and that was the problem (this is the home page so its wasn't clear before I looked at mainView.history[0] whether url should be '/', 'index.html', 'http:/my.site.com', or something else; using the history array is foolproof, though).
