### ISSUE TITLE
The template parameter of Photo Browser has been removed, but it is still in your document

### ISSUE THREAD

**Issue by chengbo** [nolimits4web/Framework7#791]
`template` parameter has been removed in below commit

https://github.com/nolimits4web/Framework7/commit/7a9f8898fbaa13b61a024c385463c8bc54d150ea#diff-58a03374079568ecefec70f988073d0bL77

But it's still in your document

http://www.idangero.us/framework7/docs/photo-browser.html

Is it removed by accident or your document is just not the latest?

**Comment by nolimits4web** [comment]
Yes, it was removed as you can use other atomic templates for its different parts. Will remove it from docs
