### ISSUE TITLE
$$(..).dataset(); does not work on Android 4.1.1 and 4.3: return empty data

### ISSUE THREAD

**Issue by shastox** [nolimits4web/Framework7#792]
Tested: Sumsung S3 (Android 4.3.), Genymotion emulator Android 4.1.1.

**Comment by nolimits4web** [comment]
You are probably doing something wrong. It works, otherwise none of clicks will work at all

**Comment by shastox** [comment]
Have you tested "dataset()" on PhoneGap Build?

**Comment by nolimits4web** [comment]
No, but it works in Cordova/Phonegap and in browser. Phonegap Build doesn't use something else

**Comment by nolimits4web** [comment]
Would be good to see live example of this issue

**Comment by shastox** [comment]
Yes.

Very simple example: 
[example-web.zip](https://github.com/nolimits4web/Framework7/files/87335/example-web.zip)

Example of PhoneGap Build Project: 
[example-phone-gap.zip](https://github.com/nolimits4web/Framework7/files/87336/example-phone-gap.zip)

APK by PhoneGap Build: 
[example-debug.zip](https://github.com/nolimits4web/Framework7/files/87338/example-debug.zip)

Tested:
Windows browsers: OK
Genymotion Android 4.4.4 (Galaxy S5): OK
Genymotion Android 4.1.1 (Galaxy S3): Bad
Android 4.4.2 (Lenovo): BAD
Samsung Galaxy S3: BAD

Sorry for my English.

**Comment by nolimits4web** [comment]
Looks like specific Android/device issue because dataset is supported http://caniuse.com/#search=dataset. Anyway, you shouldn't use `numeric` properties like `data-1` etc. From what i see it works fine with string values. Otherwise just use Crosswalk to use edge webview with correct support
