### ISSUE TITLE
Ability to specify page transitions in any theme

### ISSUE THREAD

**Issue by Samnan** [nolimits4web/Framework7#794]
I would like to have the control over the transitions in either the material or ios theme, I understand they are designed to look like native, but some (cool) apps might need to have more control over the page transitions. So page transitions might be pulled out of the two themes and be available as a separate feature?

So I think it might be a good idea to:
- keep the page transitions as a separate build task, so you can choose which type of transitions you want in your theme. In app initialization a new option can be added to specify default transition for all pages.
- (optionally) also be able to create one's own page transitions in a separate css that can be included in  custom build.
- (optionally) allow transition for each page to be specified by overriding the default transition set in app initialization, so for example, I might open one page in the app using a separate transition for some reason...

@nolimits4web what do you think?

**Comment by nolimits4web** [comment]
There is no in plans in to add custom page transition by default as it will lead to misuse with worse native-like look & feel. But they are pure CSS based, so people who know and sure they need it, can change it. It is just:
```css
.page-from-right-to-center {
   animation: custom-animation1 ...
}
.page-from-center-to-right {
   animation: custom-animation2 ...
}
.page-from-center-to-left {
   animation: custom-animation3 ...
}
.page-from-left-to-center {
   animation: custom-animation4 ...
}

**Comment by Samnan** [comment]
Fair enough :)

**Comment by juliusbangert** [comment]
I have a special case where I would like to have a fade transition. I have my index page as a kind of loading splash screen with just the app logo and a progress bar. When everything's done on there and it's time to transition to the page I would like it to be a fade rather than a slide.

How could I do this?
