### ISSUE TITLE
Accordion Component not working 

### ISSUE THREAD

**Issue by vaibhavch** [nolimits4web/Framework7#795]
I have not edited or tweaked anything with the original material accordion component. Please see my screencast video so that you will come to my issue better.

http://screencast-o-matic.com/watch/cDVX14hpfe

After clicking the accordion. its not opening. its opening and closing  in a fraction of milli seconds.

**Comment by nolimits4web** [comment]
Can't replicate it. Do you see such issue on kitchen sink demo and does it happen on real device?

**Comment by vaibhavch** [comment]
kitchen sink demo is working fine. All js,css files for both my project and kitchen sink are same.  No, I have not tested in real device. But  "accordion-item-expanded"  css class is not appending in my project while it does in kitchen sink demo.

**Comment by nolimits4web** [comment]
then something is wrong. Would be good to see live example then

**Comment by vaibhavch** [comment]
http://goo.gl/NNQAar   Click on "daily products" menu to see accordion.

**Comment by nolimits4web** [comment]
You have initialized F7 twice! You shouldn't do it:
```js
// Initialize your app
var myApp = new Framework7();

var myApp = new Framework7({
    swipePanel: 'left',
});
```

**Comment by vaibhavch** [comment]
Very Thanks.!
