### ISSUE TITLE
navbar - z-index

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#796]
unable to place the fab on navbar - 

![image](https://cloud.githubusercontent.com/assets/7137859/12228590/b0d5b61a-b863-11e5-86eb-34b0de5ff7c6.png)

z-index  doesn't react on any combinations - position and z-index etc.

**Comment by nolimits4web** [comment]
Just put floating button on the same level in DOM as your Navbar, like in kitchen sink demo

**Comment by murliatdure** [comment]
Planning for the header & FAB relative to long header - on scroll the FAB will be attached to the navbar, please have a look at screenshots.


![xcxe0](https://cloud.githubusercontent.com/assets/7137859/12346269/e954b50a-bb78-11e5-880b-ab7f8a2909d3.png)
![components_subheaders4]
(https://cloud.githubusercontent.com/assets/7137859/12346271/ead61144-bb78-11e5-9b09-ba03d6e1fa13.png)
