### ISSUE TITLE
data-reload="true" deletes history

### ISSUE THREAD

**Issue by 4blacktop** [nolimits4web/Framework7#797]
Hello.
First of all, thank you so much for the super awesome Framework 7!
Fast, smooth and clean!

My page structure using Template7:

Index 
-> Category1
----> Post1
----> Post2
-> Category2 
----> Post3
----> Post4
----> Post5

Category pages can be opened either from Index page or from Left Panel:

If I am now on Category1 page and tap link from Left Panel on Category2, I have to force reload Category2 page  (data-reload="true"), otherwise nothing happens.

Problem is:
When I use link from Left Panel, Back Button (either h/w or in Navbar) stops working so I can't back to Index page, works only Post -> Category (Like history is almost cleared). 
If I don't use data-reload="true" in Left Panel links, everything works great.

Thanks in advance.

**Comment by nolimits4web** [comment]
This is how it should work. `reload` replace last page in history with the new one. Just don't use reload if you need to load new page in history

**Comment by 4blacktop** [comment]
Thanks for quick answer!

But I have a problem with refreshing template:
When I'm on category.html page (for example, category1), and try to load other data (category2) tapping on Left Panel link, nothing happens without data-reload="true"

**Comment by nolimits4web** [comment]
Can't say without live example or code example on how do you load them

**Comment by 4blacktop** [comment]
http://27podarkov.ru/f7/

You may open left panel on any page swipePanelActiveArea: 50

**Comment by nolimits4web** [comment]
This is because, these pages have same URL and F7 doesn't allow to load same URL pages by default. So you can add some query to url of such pages or just enable `allowDuplicateUrls: true` parameter in app or view settings when you init it

**Comment by 4blacktop** [comment]
Thank you VERY much!
Best wishes to you and your projects!
