### ISSUE TITLE
Different page structure between android and ios

### ISSUE THREAD

**Issue by DmonteiroD** [nolimits4web/Framework7#799]
Well the behavior is documented, but I think that is a really bad practice in terms of modularity. 

*As you may see the Material layout is almost the same. It just has different CSS files related to Material theme, and a bit different page structure where Navbar and Toolbar are inside of the page*

http://www.idangero.us/framework7/docs/app-layout.html#basic-android-material-app-layout

For example, I have an app with the old structure where only ios style is available. 

Now the migration to make the app compatible visually with android and IOS is a completely pain, since the structure changes, and implies strong modifications in includes and page structure. The ideal behavior should be only something like this:

```
if (getMobileOperatingSystem() === 'iOS') {
    console.log('ios');
    document.write('<link rel="stylesheet" href="{{url_for("static", filename="css/framework7.ios.min.css")}}">');
    document.write('<link rel="stylesheet" href="{{url_for("static", filename="css/framework7.ios.colors.min.css")}}">');
} else {
    console.log('android');
    document.write('<link rel="stylesheet" href="{{url_for("static", filename="css/framework7.material.min.css")}}">');
    document.write('<link rel="stylesheet" href="{{url_for("static", filename="css/framework7.material.colors.min.css")}}">');
}
```

Well the summary is, the page structure should be the same for both styles, in terms of cleaning, migration and future modularity, in my opinion.

**Comment by nolimits4web** [comment]
Discussed many times. These OSes have pretty different structure and many things are just impossible to do with same HTML layout. Nothing painless, all you need is to just move navbar to page. Otherwise you may use "Fixed" navbar for iOS as well and have totally same layout
