### ISSUE TITLE
React Router

### ISSUE THREAD

**Issue by man2** [nolimits4web/Framework7#800]
Hi, I'm using meteor with react and react router. Is there way to integrate framework7 into react router? So far I only found this, but it's using iron router https://github.com/nicooprat/meteor-framework7-routing

**Comment by Poordeveloper** [comment]
I have thought about this before, finally I choose f7's routers. If you do not use f7 routers, you will lose a lot of benefits of f7.

**Comment by Poordeveloper** [comment]
I have thought about this, eventually I chose f7's routers, I love its page transition implementations. However, its pushState only works on main view, this have force me to think about writing my own history implementation.

**Comment by nolimits4web** [comment]
You can look at #702 but as far as i know it is not really possible
