### ISSUE TITLE
Floating button on IOS

### ISSUE THREAD

**Issue by shauntrennery** [nolimits4web/Framework7#805]
Is it possible to get the floating button working with the iOS theme?

**Comment by nolimits4web** [comment]
No, it is not supported by iOS theme. But apparently you can just copy styles from material theme for floating button to your app's css to have same visuals

**Comment by shauntrennery** [comment]
Working well if I include floating-button.less and comment out the check as per the code below:

```
        //if (app.params.material) {
          if (clicked.hasClass('floating-button') && clicked.parent().hasClass('speed-dial')) {
            clicked.parent().toggleClass('speed-dial-opened');
          }
          if (clicked.hasClass('close-speed-dial')) {
            $('.speed-dial-opened').removeClass('speed-dial-opened');
          }
        //}
```
