### ISSUE TITLE
Looking for x-editable in F7 forms.

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#808]
https://github.com/vitalets/x-editable
- adding as 'a'  for elements - doesn't respond
- adding as controls (text/textarea), the editable works but the updated values are not reflecting.

Can you please assist me for the same.
Thanks,

**Comment by nolimits4web** [comment]
Don't know what happens. Probably conflict with FastClick lib, you can try to add "no-fastclick" class to such elements
