### ISSUE TITLE
enhance "Messages"-Component with fixed-floated grouping

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Framework7#810]
In Whatsapp the "date" of a message is shown above the message in the middle of the screen and is fixed at the top while scrolling as long as messages within this date are available. This enhances the usability. Please provide a option to make this available within the component of framework7-messages. Thanks!!

**Comment by nolimits4web** [comment]
F7 is not a Whatsapp replica, it is not so complex feature to realize manually, just look at `position: sticky` CSS property or numerous JS "sticky" libraries and plugins

**Comment by nimo23** [comment]
Yes, you are right. The "sticky"-thing is not a complex feature. 

However, it is not only about to stick the datetime on the top while scrolling all the messages within a datetime. The thing is, that grouping behaviour of datetime:

For example, having 4 messages with a different datetime but within the same day, then group these messages so that on top it is shown the word "Yesterday" instead of 4 different datetimes for each message with (1. Msg) 30.01.16 12.33, (2. Msg) 30.01.16 12.57, (3. Msg) 30.01.16 13.46, (4. Msg) 30.01.16 14.21. I think, this is a good feature. I know, F7 is not a WP replica and should not be. However, maybe you think also, that this is a nice feature and would enhance the messaging component of F7. A property like "groupMessageByDate" can be there to enable it.
