### ISSUE TITLE
Manipulating the nav/router api's "back" history stack?

### ISSUE THREAD

**Issue by MrAndMrsK** [nolimits4web/Framework7#811]
I don't know if this would be framework7 specific answer because of integration with the internal router or if it would be entirely generic html5 history solution - like supressing the default routing behavior somehow upon the onpopstate event?

Is there a way to at certain points clear the (inline, hash) history stack?  Or possibly stack it in a desired way?

  * I use the left panel as a menu to switch modes and I don't want the user to be able to go back to a previous mode using swipe or back from that point - instead, the user should just open them panel menu again.  
  * Also, the user might navigate in a circle, I want to somehow detect this and shortcut the back history path with a more direct route.
  * The user might change some underlying data that makes a history item on the stack deleted or otherwise outdated and so going "back" through this page would be inappropriate.

Thanks!

PS.  This library is awesome.  I showed a native iOS developer who didn't think hybrid apps could have decent performance and when I showed him he insisted that it must be some html-to-compiled tool I was using.  He was impressed with the smooth graphics/transitions/performance of this library when I told him it was just a webpage that I was hosting myself.

**Comment by nolimits4web** [comment]
You can check View's `.history` property. It is an array with pages/URL which you can modify. To jump back any specific page you can use router's `.back()` method with `force:true` parameter, e.g. `mainView.router.back({url: 'another-page.html', force: true})`

But if you use `pushState` you can't modify browser's history in such way, so it won't work properly with it

**Comment by MrAndMrsK** [comment]
Ok, thanks.  

And I also think that the better answer is that modals and modals-containing-views is a better solution.  Only have pages for UI that will always exist (such as UI showing lists of things, even if that list is empty) and use popups for editing individual items (items which can be added or removed by the user).  When items themselves contain lists, their popup can be a view itself with further popups for individual sub-items.

Do you agree that that approach is more natural and will scale?

**Comment by nolimits4web** [comment]
It depends on your app and layout/UI/UX just make sure that your logic/behavior should be clear and expected from user
