### ISSUE TITLE
Form Submit Issue

### ISSUE THREAD

**Issue by karthikeyan-perpetua** [nolimits4web/Framework7#813]
@nolimits4web 

$$('form.ajax-submit').on('beforeSubmit', function (e) {  
   if(!$$("#use_name").val())
    return false; 
});
$$('form.ajax-submit').on('submitted', function (e) { 
	var xhr = e.detail.xhr;  
	var json = e.detail.data; 
});

How to work with form submit ? . If user name not entered by user , need to show error before form submit. But beforeSubmit and submitted both are working same time. So , it hit server file for every form submission . How to avoid this. ? . 

Here i don't want to use jquery click function. How to i done with these functions (beforeSubmit , submitted) ?

May i know the details(or examples or demo ) of these functions submitted ,  beforeSubmit  ,  submitError

**Comment by nolimits4web** [comment]
You can see solution on forum here http://www.idangero.us/framework7/forum/#!/getting-started:cancel-ajax-form-submission

**Comment by nolimits4web** [comment]
I guess you are the same person, we can consider it resolved then :)

**Comment by karthikeyan-perpetua** [comment]
yes :)
