### ISSUE TITLE
photobrowser close method to have event.preventDefault()

### ISSUE THREAD

**Issue by veeramarni** [nolimits4web/Framework7#815]
Hi,

I'm having issue when i click on the close button of the photobrowser as it triggers ``jQuery.event add``  method after ``close()`` method is done which i want to avoid. After modifying the code as below, i was able to fix the issue. Is there a clean way to do it? Not sure why the ``click event`` is not captured in the ``close`` method. 

```
           pb.close = function (e) {
                // custom: add prevent default to avoid conflict jquery event after this method completes.
                e.preventDefault();
                pb.opened = false;
                if (!pb.swiperContainer || pb.swiperContainer.length === 0) {
                    return;
                }
                if (pb.params.onClose) {
                    pb.params.onClose(pb);
                }
                // Detach events
                pb.attachEvents(true);
                // Delete from DOM
                if (pb.params.type === 'standalone') {
                    pb.container.removeClass('photo-browser-in').addClass('photo-browser-out').animationEnd(function () {
                        pb.container.remove();
                    });
                }
                // Destroy slider
                pb.swiper.destroy();
                // Delete references
                pb.swiper = pb.swiperContainer = pb.swiperWrapper = pb.slides = gestureSlide = gestureImg = gestureImgWrap = undefined;
            };
```

**Comment by nolimits4web** [comment]
Can you explain a bit more detailed. What are you trying to achieve with this? Probably there is another way of fixing this

**Comment by veeramarni** [comment]
Well, i'm using only photobrowser  module of framework7 in an ionic+angular app. The integration with ionic+angular+photobrowser worked very well without any issue but when i click on the ``close`` anchor of photobrowser to close it, it closes but also the click event propagate to ionic framework and automatically triggers ``back`` method (could be due to position of  ionic's ``back`` anchor and photobrowser ``close`` are at same location) which unintentionally moves the page to previous page.  I want the click event to stop propagating right after the photobrowser closes.

**Comment by nolimits4web** [comment]
Ok, the issue isn't related to Framework7, looks like the issue something in integration with Ionic. You can try to call stopPropagation after PB is opened like:
```
$('.photo-browser-close-link').on('click', function(e){
    e.stopPropagation();
})
```
There is no `event` argument in `.close` method because in Framework7 this method is not really attached to click on that link, such structure with close link click is just one of the many use cases in F7
