### ISSUE TITLE
Weird crash with switch (iOS Safari)

### ISSUE THREAD

**Issue by nicooprat** [nolimits4web/Framework7#816]
Just found a weird issue while testing my app on my device. Tapping on switch element crashes almost every time my iPhone 5S and iPad Mini 1st gen. I finally found that this did the trick:

````
.label-switch .checkbox:before {
  display: none;
}
````

It seems like Safari doesn't like `transform: scale()` transitions on pseudo-elements... I'm curious if anyone encounters the same problem. I should precise that my app is pretty fat on memory at the moment :) But this only line of CSS resolved the issue.

Hope it helps someone in the future.

**Comment by nolimits4web** [comment]
Sounds weird. Does it happen on real device or simulator, and what is iOS version?

**Comment by nicooprat** [comment]
On the simulator, there's only some kind of a little freeze.

Tested it on a real iPhone 5S and iPad Mini 1st gen with iOS 9.2.

**Comment by nolimits4web** [comment]
Don't know what to suggest, i can't replicate it :) What i can suggest is try to add `translate3d(0,0,0)` to that scale transform property for its pseudo elements, also try to add `-webkit-backface-visibility: hidden` CSS property to checkbox and its pseudo elements. Potentially this could help

**Comment by nicooprat** [comment]
No problem, I guess I just encountered a very specific edge case. I'll close this and hope it helps someone else one day :)
