### ISSUE TITLE
pull to refresh is causing "Terminated due to memory error." when you have big lists

### ISSUE THREAD

**Issue by rlech** [nolimits4web/Framework7#819]
it looks like the animation is causing an kill2homescreen when I have a long view of listItems (cordova/meteorJS build). If the page with the pull2refresh is long the animation is laggy also after a few entries. happens in UIWebView and WKWebView.

**Comment by nolimits4web** [comment]
I can only recommend you to use Virtual List here to keep the required amount of DOM in the list

**Comment by rlech** [comment]
was overlooking this in your docs. I will try this out
