### ISSUE TITLE
support for typescript or jspm

### ISSUE THREAD

**Issue by nimo23** [nolimits4web/Framework7#821]
Please provide support for using "f7" in typescript (ts-template) or jspm. Another thing is f7 uses global variables and cannot be used out of the box with "jspm" and "aurelia-framework". When loading f7 by jspm (https://github.com/jspm/registry), then f7 cannot be injected within the page. Are there any plans to support jspm or integrate it in http://kasperlewau.github.io/registry/#/ ?

**Comment by nolimits4web** [comment]
There is no plans at the moment to support these. Check the #758
