### ISSUE TITLE
"Images Lazy Load" does not work well with dynamic added images

### ISSUE THREAD

**Issue by Poordeveloper** [nolimits4web/Framework7#824]
e.g.

Dom7('#imgtest').append('`<img data-src="http://lorempixel.com/500/500/nature/3" width="100%" class="lazy lazy-fadeIn">`');

http://codepen.io/Poordeveloper/pen/RrVOjq

though I can use https://github.com/aFarkas/lazysizes instead, but I still hope F7 can be more bugless.

**Comment by nolimits4web** [comment]
In this case you have to init lazy script manually using, for example: `app.initImagesLazyLoad('.page');`

**Comment by arachimi** [comment]
Where should I write app.initImagesLazyLoad('.page');.
After var myApp = new Framework7(); ?
I should be -> myApp.initImagesLazyLoad('.page');

**Comment by aniketbhoite** [comment]
Try adding this before adding dynamic view
$$('div.lazy').trigger('lazy'); for <div>
or
$$('img.lazy').trigger('lazy'); for <img>
this works in some conditions
