### ISSUE TITLE
Dragging a view down, drags the top and bottom navigation bars too

### ISSUE THREAD

**Issue by simoami** [nolimits4web/Framework7#825]
I've included a demo video of the issue showing the top and bottom navigation bars getting dragged as I scroll the view:

http://cl.ly/2a3d062O0h0g

In the same video, I also show how [another](ionicframework.com) framework app doesn't have this issue:

http://coenraets.org/apps/directory-angular-ionic/#/employees

This gives a hint that it's not a native app, which I'd not want to show.

Any chance this gets fixed?

**Comment by nolimits4web** [comment]
This is default iOS browser behavior, Ionic uses custom JS scroll vs native scroll in F7, so no chances to get it fixed here. In cordova app it is configurable via, for example, `DisallowOverscroll` property in `config.xml`
