### ISSUE TITLE
iOS mode  bug

### ISSUE THREAD

**Issue by wakerman** [nolimits4web/Framework7#827]
From the 【Dynamically Generated Content】button to go in, in the iOS mode under the 【 one more page】 several times, you can not return to the first page .

**Comment by nolimits4web** [comment]
It is the issue of Kitchen Sink only, look for correct code at https://github.com/nolimits4web/Framework7/blob/master/kitchen-sink-ios/js/kitchen-sink.js#L1056-L1083
