### ISSUE TITLE
mouseover() event not working

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [nolimits4web/Framework7#829]
Hello Framework7 team,

I cannot seem to get a mouseover event working. I tried among others below code.
Please advise.

```
	$$('#my-form-keuringedit').on('mouseover', 'input[id="checkboxDeleteAttachment"]', function () {
		console.log("checkboxDeleteAttachment mouseover"); 	
	});
```
Kind regards,
Mario

**Comment by nolimits4web** [comment]
It can't not work. It means you are attaching it to a wrong element or in a wrong moment (when it is not in DOM)

**Comment by MarioVanDenEijnde** [comment]
Hello nolimits4web,

I have an on change also which works fine:
```
	$$('#my-form-keuringedit').on('change', 'input[id="checkboxDeleteAttachment"]', function () {
		console.log("checkboxDeleteAttachment changed");
		var filePath = this.value;//$$('input[id="checkboxDeleteAttachment"]').data('filePath');//attX.attr('data-filePath');
		var spid = page.query.spid;
		console.log("spid: "+spid+"filePath: "+filePath);
		deleteAttachment(spid,filePath);
	});
```

**Comment by nolimits4web** [comment]
If you use default F7' styled checkboxes/radio, the input element itself is hidden there, it is impossible to use `mouseover` event on it because it is hidden. Attach this event to input's visible parent element

**Comment by MarioVanDenEijnde** [comment]
OK. Thanks.
I changed it to below and now works fine.
Question: is there an easy way to show a tooltip or should I use a popover.

```
	$$('#my-form-keuringedit').on('mouseover', 'i[class="icon-delete-16"]', function () {
		console.log("checkboxDeleteAttachment mouseover"); 	
	});
```

Kind regards,
Mario

**Comment by nolimits4web** [comment]
There is no tooltips in F7, should be implemented manually. Don't think that popover is a good fit for this
