### ISSUE TITLE
Struggling with form data onPageReinit

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [nolimits4web/Framework7#830]
Hello Framework7 team,

I am struggling with form data not being populated onPageReinit (formFromJSON).
onPageInit all works fine.

Scenario: We have 2 views (viewMain and viewRight)
We have list items on a page in viewMain and call an item form in viewRight.
The form is populated nicely with the formFromJSON.
To make sure that the data is renewed when we call the form again from a second item link while the form is still open we included data-reload="true" data-ignore-cache="true".

This works fine.
But when we "close" the item form via javascript and reopen the form a second time no data is loaded in the form. The dataprovider formFromJSON is being called nicely.

Am I clear and can you advise?

```
	$$('.back').on('click', function(){
		console.log("back");
		rightView.router.loadPage('#index-right');
	})
```

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
After doing several tests I found that after adding data-reload="true" there is no way to remove the page from the DOM
Please advise.

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
I have solved it using the following code:
```
var element = document.getElementById("7keuringEdit");
element.parentNode.removeChild(element);
```

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
I have to update the code like below. Don't ask me why but it works like below:
```
$('.page-on-left').remove();
var element = document.getElementById("7keuringEdit");
element.parentNode.removeChild(element);
```
Kind regards,
Mario

**Comment by nolimits4web** [comment]
So i guess the problem is solved. Reopen if you still have this issue
