### ISSUE TITLE
Remove diacritics for Virtual List

### ISSUE THREAD

**Issue by czb** [nolimits4web/Framework7#835]
It is not really necessary but it would be nice to send `removeDiacritics(query)` to `searchAll` and `searchByItem` also for Virtual List to have consistent behaviour with normal lists. Otherwise it should be mentioned in the documentation that it does not work for Virtual Lists. I do not know how about thisone `.trim().toLowerCase()`. That should probably remain onto the custom function to do it?

**Comment by czb** [comment]
BTW: The `removeDiacritics ` is not accessible from outside, right? Would be a nice tool to have :).

**Comment by nolimits4web** [comment]
Yes, it is not accessible. Will add such option to VL
