### ISSUE TITLE
file input

### ISSUE THREAD

**Issue by lws68825** [nolimits4web/Framework7#836]
Hi,
Does framework7 support form including file input element?

**Comment by chalchis** [comment]
try

<input class="button button-big button-fill" type='file' id='_file' accept="image/*;capture=camera">

css
´´´javascript
.custom-file-input 
		{
			display: inline-block;
			position: relative;
			color: #FFFFFF;
		}
		.custom-file-input input 
		{
			visibility: hidden;					
		}
		.custom-file-input:before 
		{
			content: '\f030  seleccionar';
			font-family: FontAwesome;
			display: block;
			background: -webkit-linear-gradient( -180deg, #007AFF, #007AFF);
			background: -o-linear-gradient( -180deg, #007AFF, #007AFF);
			background: -moz-linear-gradient( -180deg, #007AFF, #007AFF);
			background: linear-gradient( -180deg, #007AFF, #007AFF);
			border: 3px solid #007AFF;
			border-radius: 10px;
			padding: 5px 0px;
			width: 40%;
			outline: none;
			white-space: nowrap;
			cursor: pointer;
			text-align: center;
			font-size: 12pt;
			position: absolute;
			left: 0;
			right: 0;
		}
		.custom-file-input:hover:before 
		{
			border-color: #007AFF;
		}
		.custom-file-input:active:before 
		{
			background: #007AFF;
		}	
´´´

**Comment by lws68825** [comment]
@chalchis, thank you very much for your wonderful reply.

**Comment by chalchis** [comment]
Please close the issue
if the answer is expected

**Comment by chalchis** [comment]
Another way

![input_file](https://cloud.githubusercontent.com/assets/2206648/15957717/81505836-2eb6-11e6-8b2f-517928e2ba74.gif)


css
```
 /*input file*/
    .fileUpload 
    {
        position: relative;
        overflow: hidden;           
    }

    .fileUpload input.upload 
    {
        position: absolute;
        top: 0;
        right: 0;
        margin: 0;
        padding: 0;
        font-size: 20px;
        cursor: pointer;
        opacity: 0;
        filter: alpha(opacity=0);
    }

    .ico_upload
    {
      padding-left: 8px; font-size:25px
    }

```

```
  +'<div class="list-block inputs-list theme-indigo">'
                        +'<div class="item-content">'
                            +'<div class="item-media button button-raised button-fill color-indigo fileUpload">'
                                +'<span class="ico_upload"><i class="fa fa-paperclip" aria-hidden="true"></i></span>'
                                +'<input id="tx_file_programa" type="file" class="upload"/>'
                            +'</div>'
                            +'<div class="item-inner">'
                              +'<div class="item-title floating-label">Archivo seleccionado</div>'
                              +'<div class="item-input">'
                                +'<input id="file_lectura" readonly type="text" placeholder=""/>'
                              +'</div>'
                            +'</div>'
                        +'</div>'
                    +'</div>'
```

**Comment by lws68825** [comment]
@chalchis , it is fantastic, thank you very much!

**Comment by Svetoslav0712** [comment]
Does framework7 support form including audio files ?
