### ISSUE TITLE
Navbar Title off center when dynamically loading iOS or Material theme

### ISSUE THREAD

**Issue by devgeeks** [nolimits4web/Framework7#837]
When using the example of how to maintain Material and IOS in a single app from here:

http://www.idangero.us/framework7/tutorials/maintain-both-ios-and-material-themes-in-single-app.html

The title in the navbar in iOS starts uncentered.

This can be corrected by running `myApp.sizeNavbars('.view-main');`, but you can't do it right away as soon as the app is initialised. If you do it a tad later (say 'deviceready' in PhoneGap) then there is a visible "jump" when the title corrects to the center.

![off-center-title](https://cloud.githubusercontent.com/assets/554999/12939528/a661e780-d014-11e5-86be-dea5aeaeb110.png)

**Comment by nolimits4web** [comment]
Ok, played a bit with it. Find the pretty weird behavior, or didn't know it works like that. So when we append styleshets in `my-app.js` browser loads them asynchronously, but if we load it in another file or directly in HTML before `my-app.js` it loads them synchronously. So part with stylesheets should be removed from my-app.js and order should be the following:
```html
<body>
    ...
    <script type="text/javascript" src="js/framework7.min.js"></script>
    <script>
      (function () {
        if (Framework7.prototype.device.android) {
              Dom7('head').append(
                  '<link rel="stylesheet" href="css/framework7.material.min.css">' +
                  '<link rel="stylesheet" href="css/framework7.material.colors.min.css">' +
                  '<link rel="stylesheet" href="css/my-app.material.css">'
              );
          }
          else {
              Dom7('head').append(
                  '<link rel="stylesheet" href="css/framework7.ios.min.css">' +
                  '<link rel="stylesheet" href="css/framework7.ios.colors.min.css">' +
                  '<link rel="stylesheet" href="css/my-app.ios.css">'
              );
          }
      })();
    </script>
    <script type="text/javascript" src="my-app.js"></script>
</body>
```

**Comment by nolimits4web** [comment]
I will update tutorial with this snippet

**Comment by devgeeks** [comment]
Interesting. This will clash with a Content Security Policy (that doesn't allow `'unsafe-inline'`), so I might personally look for a build-time solution just for those stylesheets. 

However, as a general fix for the guide, this looks like a good solution. Thanks :)

**Comment by devgeeks** [comment]
Note: It turns out the snippet above can be used in an external JS file, as long as it is loaded before `my-app.js` as above.

```javascript
<script type="text/javascript" src="js/framework7.min.js"></script>
<script type="text/javascript" src="js/init-styles.js"></script>
<script type="text/javascript" src="my-app.js"></script>
```

**Comment by nolimits4web** [comment]
Yes, should be anywhere but before my-app.js. To be honest i don't really understand why browser does like that :)
