### ISSUE TITLE
Stop swipe to delete on window scroll

### ISSUE THREAD

**Issue by marianbodisteanu** [nolimits4web/Framework7#838]
Hi. Is it possible to disable swipeout when window is scrolling? For example I scroll a Swipeable list and I want to scroll vertically but sometimes swipeout is triggered even when window is scrolling. Such behaviour forces me not to use swipeout. On iPhone it works differently, during scroll no swipeout. Thanks.

**Comment by chalchis** [comment]
can you show some of your app screen

**Comment by ZanderBrown** [comment]
There hasn't been a response by the issues owner in 20 days.
This issue **will be closed in 7 days** if no further response is submitted
