### ISSUE TITLE
How Can I Get Element From Inside a Modal?

### ISSUE THREAD

**Issue by emrevural20** [nolimits4web/Framework7#839]
I have a modal. I want to progressbar inside modal. This progressbar will be dynamic. I need to get this progressbar's id or class. For example : $$('#progressbar').attr('data-progress');

**Comment by chalchis** [comment]
please show some of his script
Cheers!!!!

**Comment by nolimits4web** [comment]
http://www.idangero.us/framework7/forum/#!/getting-started:how-can-i-get-element-from
