### ISSUE TITLE
Uncaught TypeError: Cannot read property 'url' of undefined in push-state.js:55

### ISSUE THREAD

**Issue by callmez** [nolimits4web/Framework7#840]
for some reason my app used jquery.pjax.js , and it didn't work very well with pushState mode. 

![image](https://cloud.githubusercontent.com/assets/1625891/12953285/b466d954-d054-11e5-9933-165eeaa7151d.png)

because both e.state are different.
please make them compatible such as 
```
if (state.viewIndex === undefined || state.viewIndex < 0) return;
```
or better way.
Thanks!

**Comment by nolimits4web** [comment]
If you use something custom to load pages via ajax and for routing, then you have to use own pushState logic, not the default ones
