### ISSUE TITLE
Dynamic Picker Modal  use DOM element instead of raw Html

### ISSUE THREAD

**Issue by vaibhavch** [nolimits4web/Framework7#843]
From the documentation, I came to know that we can use plain html in picker model like below
`myApp.pickerModal(
    '<div class="picker-modal">' +
      '<div class="toolbar">' +
        '<div class="toolbar-inner">' +
          '<div class="left"></div>' +
          '<div class="right"><a href="#" class="close-picker">Close</a></div>' +
        '</div>' +
      '</div>' +
      '<div class="picker-modal-inner">' +
        '<div class="content-block">' +
          '<p>Lorem ipsum dolor ...</p>' +
        '</div>' +
      '</div>' +
    '</div>'
  )`

 But How can we pass Html DOM element?

**Comment by nolimits4web** [comment]
But in this case you can just specify CSS selector of picker element in DOM to open it. No?

**Comment by vaibhavch** [comment]
Can you give me a example using your DOM7 library?

**Comment by vaibhavch** [comment]
I create picker html dynamically., so it is not possible to write in prior and use it in css selector.

**Comment by nolimits4web** [comment]
Then just append it to BODY with unique selector/id and pass it to `pickerModal` method. I will add this feature, but it will do the same

**Comment by vaibhavch** [comment]
Thanks. :+1:
