### ISSUE TITLE
iOS/OS 3D-Touch or Macbook forceTouch get the direct ajax html

### ISSUE THREAD

**Issue by evolutionjay** [nolimits4web/Framework7#844]
I need help when i testing Apple system's forceTouch event,
see the images:
![img_1091](https://cloud.githubusercontent.com/assets/4468540/13071697/18c00734-d4d0-11e5-9dbe-0947fcbdde12.jpg)

**Comment by evolutionjay** [comment]
And I fond something maybe help :
http://huangxuan.me/forcify

**Comment by nolimits4web** [comment]
It is not supported at the moment in Framework7 and it doesn't work in Phonegap/Cordova app.

**Comment by evolutionjay** [comment]
ok,I try myself to listen the onmouseforcexxxxx event and build a preview modal when touching

**Comment by iHackify** [comment]
Hi I Have Already Made A Working 3d Touch/ Force Touch With My Own Code You Can Feel Free To Have A Look At It Here [3D Touch/ Force Touch](http://timedevs.net/Lotus/mobile/index1812.html)

**Comment by ZanderBrown** [comment]
I think this is out of scope and relies on non standard tech.
