### ISSUE TITLE
Picker modal modified like Action sheet

### ISSUE THREAD

**Issue by vaibhavch** [nolimits4web/Framework7#845]
We have to close picker modal manually by invoking javascript or adding class to html. But it is easy to close action sheets just by clicking anywhere.  How to implement this to picker modal?

**Comment by nolimits4web** [comment]
No, picker modal is not intended to be used like this, so by default it is not implemented. But you can add some kind of such snippet:
```js
$$('html').on('click', function (e) {
    if ($$(e.target).is('.picker-modal') || $$(e.target).parents('.picker-modal').length > 0) {
        myApp.closeModal('.picker-modal');
    }
});
