### ISSUE TITLE
List View items layout issue in Material theme

### ISSUE THREAD

**Issue by waptaxi** [nolimits4web/Framework7#847]
Layout of elements of class "item-after" is broken when we have just one item containing element of "item-input" class.
In this case, all "item-after" elements lose their right align and go under their "item-title" element.

`							<div class="list-block">
                                <ul>        
                                    <li>
                                        <div class="item-content">
                                            <div class="item-media">
                                                <i class="icon my-icon"></i>                                                
                                            </div>
                                            <div class="item-inner">
                                                <div class="item-title label">Name</div>
                                                <div class="item-input">
                                                    <input type="text" name="name">
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="item-content">
                                            <div class="item-media">
                                                <i class="icon my-icon"></i>
                                            </div>
                                            <div class="item-inner">
                                                <div class="item-title">title
                                                </div>
                                                <div class="item-after">label
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                </ul>   
                            </div>`

**Comment by nolimits4web** [comment]
It is done because form elements are require additional styles so additional `inputs-list` class is added to such list-block. Also, try to avoid using different list items (form elements and usual items) in same list, not a good practise. To fix this you can just add `style="display:flex"` to `<div class="item-inner">` of usual item
