### ISSUE TITLE
framework7.js:4106 Uncaught TypeError: Cannot read property 'offsetWidth' of undefined

### ISSUE THREAD

**Issue by breferrari** [nolimits4web/Framework7#848]
I'm getting this problem whenever I try to hover and push my finger over an input with floating label.
It just builds up in the console and renders the interface unusable, as I can't interact with anything else.

**Comment by breferrari** [comment]
OK, just noticed it occurs as a side effect of using AngularJS with F7. I'm dynamically inserting the sidebar tag using ng-if and it triggers the error when it checks for my finger hovering the screen and activates the swipePanel, but there is no panel to be shown. 
If I turn swipePanel off, it doesnt occur anymore.

Is there a way to circumvent it? Like turn swipePanel off or on using js outside the config?

**Comment by nolimits4web** [comment]
You can disable it later using `myApp.params.swipePanel = false` and for example `myApp.params.swipePanel = 'left'` to enable it again
