### ISSUE TITLE
Nested Modals Issues

### ISSUE THREAD

**Issue by razzbee** [nolimits4web/Framework7#849]
Hello , I created a custom modal ( myApp.modal) and set close : false for one of the button which has a nested myApp.prompt modal ,the problem is the prompt modal fails to open on top of the parent modal, instead it opens behind the parent modal ( myApp.modal) , any help?

**Comment by nolimits4web** [comment]
Nested modals are not supported, you have to close one before opening another

**Comment by nolimits4web** [comment]
Closing as no further response, considered as solved
