### ISSUE TITLE
Page redirect onPageInit event

### ISSUE THREAD

**Issue by alinburcea** [nolimits4web/Framework7#850]
Hi,

I'm trying to redirect to a page on pageInit event and isn't work...
For ex.
In the index.html I have this:

  &lt;a href=&quot;extensions.html&quot; class=&quot;item-link&quot;&gt;Extensions&lt;/a&gt;

I have another page called profile.html.

In javascript I have this

myApp.onPageInit('extensions', function (page) {
   //custom logic
  mainView.router.load('profile.html');
else
// continue to load extensions.html
});

My problem is that profile.html is never loaded.
Is not possible to redirect/load to a page onPageInit event?

Thx

**Comment by yczf1836** [comment]
custom logic could not write in myApp.onPageInit callback function

**Comment by nolimits4web** [comment]
It was discussed many times here and on forum. Try to use search. But you can't use router methods within pageInit callback as router is still routing in this case. You need to use `preroute` or `preprocess`
