### ISSUE TITLE
Listview issue

### ISSUE THREAD

**Issue by razzbee** [nolimits4web/Framework7#852]
Hello , there is a strange line passing through one of my list item , I cant seem to remove it after many attempts. I have attched a screen shot of the problem. Thank you
![screenshot 1](https://cloud.githubusercontent.com/assets/3003019/13221284/8efdf504-d972-11e5-9da6-9c2a25022a5c.jpg)

**Comment by nolimits4web** [comment]
Screenshot doesn't tell much. Live example with the issue would be good

**Comment by nolimits4web** [comment]
Closing as no further response, considered as solved
