### ISSUE TITLE
Neighbours self closing tag parsed as nested

### ISSUE THREAD

**Issue by lcaprini** [nolimits4web/Framework7#855]
I try to parse an HTML like this `<div><span/><a/></div>` using Dom7.

With jQuery the parse is correct:
`$("<div><span/><a/></div>").html() = "<span></span><a></a>"`
`<span>` and `<a>` are neighbours and childrens of `<div>`.

When I use Dom7 I have instead:
`$$("<div><span/><a/></div>").html() = "<span><a></a></span>"`
The first self closing tag `<span>` become the only children of `<div>` and the parent of the second tag `<a>`.

I'm trying to use Dom7 to parse an XML, which is the response of a Web Service and there are many self closing tags.

Can you help me?

Thank you very much.

**Comment by nolimits4web** [comment]
`<div><span/><a/></div>` - it is not a valid HTML. Dom7 doesn't intended for XML parsing. There are vanilla JS tools for parsing XML https://developer.mozilla.org/en-US/docs/Web/Guide/Parsing_and_serializing_XML

For example
```
new DOMParser().parseFromString('<div><span/><a/></div>', "text/xml");
```

**Comment by lcaprini** [comment]
Thank you for your answer. In my previous projects I often use jQuery to "parse" XML because it is more simple and rapid than , and when I start to use Dom7 I've assumed it was similar.
I will use DOMParser in future.
Thank you for you time and your beautiful work!!
