### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by vespino** [nolimits4web/Framework7#856]
I'm moving an app I built from jQuery + jQuery Mobile to Framework7. The apps relies on a number of ajax requests to get json data from my server. When using the following code, I only get "parseerror" and nothing to work with.

```
$$.ajax({
  url: 'https://linktomywebsite.com/search',
  dataType: 'json',
  method: 'post',
  data: {
    latitude: localStorage.getItem('latitude'),
    longitude: localStorage.getItem('longitude'),
    distance: localStorage.getItem('distance'),
    mode: (localStorage.getItem('fietsroutes')=='ja' ? 'bicycling' : 'driving')
},
success: function(result, status, xhr) {
},
error: function(xhr, status) {
  console.log(status);
},
statusCode: {
    404: function(xhr) {
      console.log('leftpanel 404');
    }
  }
})
```

Any idea what could be causing this?

**Comment by nolimits4web** [comment]
Would be good to see actual server response

**Comment by nolimits4web** [comment]
Closing as no further response

**Comment by 192kb** [comment]
Example with parseerror: https://192kb.ru/xpeers/
To get error click on any card.

**Comment by 192kb** [comment]
finally got: error appears when success handler has an js error like function is not defined or so.
