### ISSUE TITLE
Clear search after navigate in another page of the app

### ISSUE THREAD

**Issue by CharlieMetal** [nolimits4web/Framework7#857]
I need to clear the search after navigate in another page, or click in the "back" buttom.

**Comment by CharlieMetal** [comment]
![3](https://cloud.githubusercontent.com/assets/17444456/13296606/02953ba8-daf4-11e5-9e2e-4f482d2662ba.PNG)
![4](https://cloud.githubusercontent.com/assets/17444456/13296609/029c04ba-daf4-11e5-8591-06c52d56596f.PNG)
![1](https://cloud.githubusercontent.com/assets/17444456/13296607/02961226-daf4-11e5-9a2e-c3f1acca909a.PNG)
![2](https://cloud.githubusercontent.com/assets/17444456/13296608/02978066-daf4-11e5-9d37-0c007229c591.PNG)

**Comment by ZanderBrown** [comment]
use the before animation event to call the clear method
