### ISSUE TITLE
where is this comp

### ISSUE THREAD

**Issue by ijry** [nolimits4web/Framework7#858]
is this will be developed by new version 
![12](https://cloud.githubusercontent.com/assets/3102798/13312457/a6bbbf08-dbd1-11e5-9085-d295915d8a8b.png)

**Comment by nolimits4web** [comment]
No, there is no such in F7, add it manually

**Comment by ijry** [comment]
but it can be see in much apps , it's a common style,  isn't it?

**Comment by nolimits4web** [comment]
No, it is not a common style

**Comment by ijry** [comment]
we can see more than 50% percent of app has that style?
