### ISSUE TITLE
Is it possible to prevent deleting of a DOM element from `F7`?

### ISSUE THREAD

**Issue by kiki-le-singe** [nolimits4web/Framework7#859]
What I mean is that I would like to handle myself deleting of a element from DOM via `React`.
In fact to handle a list of elements ([Dynamic Children](https://facebook.github.io/react/docs/multiple-components.html#dynamic-children)) with `React`, we add to the elements a `key` property. This will help `React` to delete himself the elements when the state changed. My problem is that `Framework7` also handles it (example: [swipeout - app.swipeoutDelete](https://github.com/nolimits4web/Framework7/blob/master/src/js/swipeout.js#L395)). This will cause collision.

Any ideas?

Thank you for your help.

**Comment by nolimits4web** [comment]
Not possible to disable it. As an option, you can try to redefine Dom7's `remove` method:
```js
Dom7.fn.remove = function () {
    //do your stuff here
}

**Comment by kiki-le-singe** [comment]
Ok thank you. I'm going to try to do this.
