### ISSUE TITLE
Popup closes upon clicking, event when theres no close popup button

### ISSUE THREAD

**Issue by mervynteo** [nolimits4web/Framework7#860]
My code attached below. 
What I did was to have add comment button on navbar which is on a seperate html file. 
popup works ok but it auto closes when i click anywhere on the screen. Its supposed to stay there and close only upon clicking the close button. 

Also, how to make the submit button work? I put type="submit" but doesnt work. (My js file defined ".submit"). 

```html
    <div class="popup-overlay">
        <div class="popup addcomment">

            <div class="content-block">
                <div class="page-content message-content">
                    <p><a href="#" class="close-popup">Close</a></p>

                    <div class="message-input">
                        <textarea id="body" name="body" placeholder="blabla."></textarea>
                    </div>
                   <button class="button button-icon icon ion-arrow-right-b" type="submit"></button>
                </div>
            </div>

        </div>
    </div>
```

**Comment by nolimits4web** [comment]
Why your `popup` is inside of `popup-overlay`? They should be separate

**Comment by mervynteo** [comment]
I put it inside overlay as I had a dark popup screen for unknown reasons, and this link explained that putting it in the overlay gets rid of it. Which it did. 
https://muut.com/i/framework7/bugs-and-issues:popup-issue-fade-out-da

The issue of clicking was solved by 
``` html
                 <script>
			var myApp = new Framework7({ 
				popupCloseByOutside:false, //changed this to false to avoid auto close
			   	pushState: false,
			   	autoLayout: true
			});
			var $$ = Dom7; 
		</script>
```
