### ISSUE TITLE
allowDuplicateUrls option don't work when going back

### ISSUE THREAD

**Issue by LeoRodz** [nolimits4web/Framework7#861]
I have a Template7 Ajax page that is loaded sequentially multiple times, with diferent context each time.
I'm using **allowDuplicateUrls** option to allow loading the same url time after time.
This works perfectly loading new pages, but fails going back.

I could make it work changing line 937 in router.js.
before:
`if (url && url === view.url || pageName && view.activePage && view.activePage.name === pageName) {`
after
`if (!view.params.allowDuplicateUrls && (url && url === view.url || pageName && view.activePage && view.activePage.name === pageName)) {`

This works only when setting back option **force: true**.
I'm not sure if what I did is right or if it's enough, 
I'm new to Framework7 so I suppose I'm missing something.

Thankls for your help.
Leo

**Comment by nolimits4web** [comment]
Can you describe more detailed on how to replicate the issue?

**Comment by LeoRodz** [comment]
I've set-up a simple demo so you can see what I'm trying to do and the problem I've found..
[allowDuplicateUrls_Test.zip](https://github.com/nolimits4web/Framework7/files/161560/allowDuplicateUrls_Test.zip)
The goal is having an app when its main content is a unique Template7 page loaded multiple times while changing its content (context). In my demo it is working fine going to the next page but is not working getting back to the previous page.
Thank you very much.

**Comment by ZanderBrown** [comment]
@LeoRodz is this now resolved?
