### ISSUE TITLE
Switching tabs is very slow

### ISSUE THREAD

**Issue by idimni** [nolimits4web/Framework7#864]
I have a template http://framework7.io/examples/tab-bar/ .
If in id=“view-1”,id=“view-2”,id=“view-3”,id=“view-4” little html, then switching between tab happens very quickly. So, if for example in id=“view-3” code html becomes bigger(infinite load pages), then switching to id=“view-3” is very slow. And the bigger code is, the longer time it takes. How can we improve it?

**Comment by rlech** [comment]
use a virtual list. when your DOM is to big it will take to long

**Comment by idimni** [comment]
Thank you, but  when Virtual List is to big,  it also will take to long..

**Comment by rlech** [comment]
Without any line of code its hard to Tell you whats wrong. Vlist should be ok for nearly some 100k entries so :

1)

You used it wrong

2)

Your data loading is the problem

3)

You are not caching and querying your db again and again when tapping on a tab

4)

You really have more than some 100k entries or other random big number and above.

**Comment by idimni** [comment]
I use layout http://framework7.io/examples/tab-bar/

index.html
`
<div id="view-1" class="view view-main tab">
<div class="pages">
<div data-page="index-1" class="page">
<div class="page-content">
<div class="content-block-title">Welcome</div>
<div class="content-block">
<div class="home-timeline">

<div data-id="1" class="card ks-facebook-card"><div class="card-header"><div class="ks-facebook-avatar" data-avatar-id="1"><img src="http://lorempixel.com/68/68/people/1/" height="34" width="34"></div><div class="ks-facebook-name">Bob Brown</div><div class="ks-facebook-date" data-time="1404709434">2014-07-07 09:03</div></div><div class="card-content"><div class="card-content-inner"><p>Behind every successful man there's a lot u unsuccessful years. <a href="#" onclick="event.stopPropagation();window.open('http://goo.gl/','_blank')">http://goo.gl/</a></p></div></div><div class="card-footer"><a href="#" class="link">Forward</a><a href="#" class="link">Comment</a><a href="#" class="link">Like</a></div></div>

<div data-id="2" class="card ks-facebook-card"><div class="card-header"><div class="ks-facebook-avatar" data-avatar-id="1"><img src="http://lorempixel.com/68/68/people/1/" height="34" width="34"></div><div class="ks-facebook-name">Bob Brown</div><div class="ks-facebook-date" data-time="1404709434">2014-07-07 09:03</div></div><div class="card-content"><div class="card-content-inner"><p>Behind every successful man there's a lot u unsuccessful years. <a href="#" onclick="event.stopPropagation();window.open('http://goo.gl/','_blank')">http://goo.gl/</a></p></div></div><div class="card-footer"><a href="#" class="link">Forward</a><a href="#" class="link">Comment</a><a href="#" class="link">Like</a></div></div>

...

<div data-id="100" class="card ks-facebook-card"><div class="card-header"><div class="ks-facebook-avatar" data-avatar-id="1"><img src="http://lorempixel.com/68/68/people/1/" height="34" width="34"></div><div class="ks-facebook-name">Bob Brown</div><div class="ks-facebook-date" data-time="1404709434">2014-07-07 09:03</div></div><div class="card-content"><div class="card-content-inner"><p>Behind every successful man there's a lot u unsuccessful years. <a href="#" onclick="event.stopPropagation();window.open('http://goo.gl/','_blank')">http://goo.gl/</a></p></div></div><div class="card-footer"><a href="#" class="link">Forward</a><a href="#" class="link">Comment</a><a href="#" class="link">Like</a></div></div>

</div>

</div>
</div>
</div>
</div>
</div>
`

and switching id="view-1"  takes too long...

**Comment by idimni** [comment]
It seems everything is like in docs. Do you have any ideas?

**Comment by J05HI** [comment]
@nolimits4web @valnub @ZanderBrown 
Should be closed.
