### ISSUE TITLE
global option to disable/enable add statusbar on fullscreen detection

### ISSUE THREAD

**Issue by rlech** [nolimits4web/Framework7#866]
this bug was driving me insane the last few days because I was not able to see if its produced by cordova-plugin-statusbar, meteor 1.3beta11 or framework7.

http://framework7.io/docs/status-bar.html

please add an option to manually disable/enable the auto detection which is adding a statusbar when the app is in fullscreen or not.

**Problem with cordova builds on iOS Device/Simulator**
I had the problem that your **auto detection** was adding some kind of margin/padding on top of my view so I had my native ios statusbar and an empty space with the same size right under the native statusbar. this space was driving me crazy because it even appears when I dont add a `statusbar-overlay div` in my `html` container. The detection code was adding the `with-statusbar-overlay` so the space was empty and you have seen the background color of `body`.

to fix this removed the complete statusbar block in the css

but this is just a workaround because the fake html statusbar is now broken and cant be used anymore. It would be nice if it would be possible to disable this auto detection or make it more stable to avoid the statusbar when its not necessary.

<img width="320" alt="with" src="https://cloud.githubusercontent.com/assets/3764301/13471569/64b31950-e0b1-11e5-98cc-c1934cb3472c.png">
<img width="320" alt="without" src="https://cloud.githubusercontent.com/assets/3764301/13471570/64db8e62-e0b1-11e5-9758-489759103aa4.png">

**Comment by martinr77** [comment]
I had the same problem yesterday, you can hide the statusbar with 

statusbarOverlay: true;

within 

var myApp = new Framework7();

Its very hidden in the docs: http://framework7.io/docs/init-app.html

**Comment by nolimits4web** [comment]
Detection works correct. It happens because i guess you hide/show statusbar in `deviceready` event AFTER you init Framework7. And as @martinr77 said there is an `statusbarOverlay` app parameter to control it

**Comment by juliusbangert** [comment]
I have this same problem and I have tried adding **statusbarOverlay: true** into the **new Framework7() call in app.js**. This is not woking, I literally cannot get rid of this top gap. I'd prefer an official solution and not to change the core css if possible. I'm using the latest build of Framework 7 and Phonegap. Please help.

**Comment by nolimits4web** [comment]
There is no statusbarOverlay parameter, check docs please http://framework7.io/docs/statusbar.html#statusbar-app-parameters

**Comment by juliusbangert** [comment]
@nolimits4web Thank you for the reply Vladimir, and thank you for your amazing framework. Sorry for posting a silly comment without checking the documentation. But I still can't get rid of the gap at the top of each of my pages. Do you have any idea what causes this?

![img_4840](https://user-images.githubusercontent.com/3276957/37243415-a8962f04-2470-11e8-8bc9-a66d40e39164.PNG)

**Comment by nolimits4web** [comment]
Do you mean the gap between navbar and the list? This is the default CSS `margin` on `.list`. You can disabled it by `no-margin` class on list

**Comment by juliusbangert** [comment]
Excellent! So I assume I can add this `no-margin` class to the first element within `.page-content` on each page. Thank you.
