### ISSUE TITLE
router in v1.4.2 is buggy

### ISSUE THREAD

**Issue by Poordeveloper** [nolimits4web/Framework7#868]
After upgraded to v1.4.2, I experienced some wierd behavior with f7 router.back(). Sometimes router.back() to a wrong page. Sometimes router.back() does not take effect. Seems the history is totally screwed up. Not sure if any other guys got the same problem as me.  I see there are really some code changes in router.js, may need more test. Now I have rolled back to v.1.4.0. Everything is fine now.

**Comment by nolimits4web** [comment]
`Sometimes` doesn't tell me much. Need to know how to exactly replicate the issue

**Comment by Poordeveloper** [comment]
I was trying to reproduce the issue with a demo, but failed. Not sure anything specific in my app, will let you know once I have new finding.
