### ISSUE TITLE
Ajax routing fails

### ISSUE THREAD

**Issue by JTA28** [nolimits4web/Framework7#869]
![issue](https://cloud.githubusercontent.com/assets/17681810/13552244/4b00f330-e339-11e5-8ccd-bf8070c0fde3.jpg)

**Comment by atukilham** [comment]
ajax routing do not need full layout.
delete syntax <html>, <head>, <body>
start the page that you call from <div class="page" data-pages="scholes"> bla bla bla </div>,
not full layout.

**Comment by JTA28** [comment]
That's what I did, but it sometimes calls the html file without ajax and then the above happens

`

<div class="pages">
  <div data-page="scholen" class="page navbar-fixed toolbar-fixed">

    
    <div class="navbar bg-red color-white">
      <div class="navbar-inner">
        <div class="left">
          <a href="#" class="link icon-only open-panel" data-panel="left">
            <i class="icon ion-android-menu"></i>
           </a>
        </div>
        <div class="center">Scholen</div>
        <div class="right">
        </div>
      </div>
    </div>

    <div class="toolbar toolbar-bottom tabbar bg-red color-white">
      <div class="toolbar-inner">
          <a href="views/advertentie.html" class="link with_border_right">
              <i class="icon ion-pricetags"></i>
          </a>
          <a href="views/bos.html" class="link img_icon with_border_right">
              <img src="dir/img/logobos.png">
          </a>
          <a href="views/msp_nieuws.html" class="link img_icon">
              <img src="dir/img/logo.png">
          </a>
      </div>
  </div>

    <div class="page-content">`

**Comment by nolimits4web** [comment]
@JTA28 you have JS error somewhere. Please provide full live example or we won't be able to help

**Comment by JTA28** [comment]
Is there an easier way to provide the full live example? than to put my code here?

**Comment by JTA28** [comment]
[Android.zip](https://github.com/nolimits4web/Framework7/files/160447/Android.zip)

**Comment by nolimits4web** [comment]
And how to replicate the issue in your archive?
