### ISSUE TITLE
Icon svg compability with android system webview

### ISSUE THREAD

**Issue by atukilham** [nolimits4web/Framework7#870]
hi, i found little bugs, 
icon svg with css background image : url(data:image) not compatible with android system webview newest (version 48.0.2564.106)
I update android system view, and a few icons on my app (kitchen sink) was lost.
like icon-back, icon checkbok (on checked).
help me.
thanks

**Comment by nolimits4web** [comment]
Looks like you forgot to specify Content Security Policy http://forum.framework7.io/#!/getting-started:phonegap-hybrid-f7-app-no
