### ISSUE TITLE
Swipe Update Function is working only for the first 2 slides (multiple swiper)

### ISSUE THREAD

**Issue by martinr77** [nolimits4web/Framework7#871]
if I have multiple Swiper in tabs. the first is working with your update function (two swipes) but the
 second (with 3 swipes) is only showing the first 2 pics.

![bildschirmfoto 2016-03-07 um 11 04 52](https://cloud.githubusercontent.com/assets/9454529/13566206/b8a9ded0-e454-11e5-8269-43c1102af8f5.png)

I do not understand generally why the swipers are not working in tabs without update function. how is the right way to embed multiple swipers in tabs?

This is my JS:

```
//Now we add our callback for initial page
$('#view-3').on('show', function(){
  //Do something here with home page
 //myApp.alert("index3");
 
  // 2 Slides Per View, 20px Between
		var mySwiper4 = myApp.swiper('.swiper-4', {
		  pagination:'.swiper-4 .swiper-pagination',
		  lazyLoading: true,
		  spaceBetween: 20,
		  slidesPerView: 2
		});
		 
		// 3 Slides Per View, 10px Between
		var mySwiper5 = myApp.swiper('.swiper-5', {
		  pagination:'.swiper-5 .swiper-pagination',
		  lazyLoading: true,
		  spaceBetween: 10,
		  slidesPerView: 3
		});	
		
		
})
```

**Comment by martinr77** [comment]
Okay, I think it has to do with my lazy class. I tried "lazy fade-in". With "swiper-lazy" it is working. but is there no way to have it with "fade-in"?

**Comment by nolimits4web** [comment]
Would be good to see some kind of live example or JSFiddle with the issue

**Comment by nolimits4web** [comment]
Closing as no further response, considered as solved
