### ISSUE TITLE
Error align center navbar with material theme

### ISSUE THREAD

**Issue by Mdpproduction** [nolimits4web/Framework7#872]
Hi guys, i've a problem with navbar and the text alignment. The point is that with material theme the text doesn't align properly, and all text overlaps. How can i fix this ?
And in general, the sliding transition with material theme doesn't works properly too.

**Comment by nolimits4web** [comment]
Example, screenshot or something more clear to understand?

**Comment by Mdpproduction** [comment]
Sorry, the sliding effect that with ios theme works, with material theme doesn't. So, there will be some updating for material theme too ?

**Comment by nolimits4web** [comment]
Look at Material theme guides and tutorials on website. There is no sliding effect in Material theme

**Comment by Mdpproduction** [comment]
Ok, i'm saying that would be nice to have that effetct on material. Btw, it doesn't matter. Thanks.

**Comment by coorasse** [comment]
Why this ticket has been closed?
If you simply take the Basic Android/Material App Layout proposed in the docs and try to add left, center and right elements in the navbar it doesn't work properly:
```
<div class="navbar">
  <div class="navbar-inner">
    <div class="left">
      <a href="#" class="link">Left Link</a>
     </div>
     <div class="center">Awesome App</div>
     <div class="right">
       <a href="#" class="link">Right Link</a>
      </div>
    </div>
  </div>
```

will result in:
<img width="504" alt="screen shot 2016-04-06 at 13 22 06" src="https://cloud.githubusercontent.com/assets/1319150/14314925/97658b80-fbfa-11e5-8813-727a60fe2ee9.png">

If I remove left and right links then everything is ok.

**Comment by Mdpproduction** [comment]
I know but the name goes to the left and not on center. Btw thanks for info

**Comment by coorasse** [comment]
Sorry, maybe I was not clear but I think this issue should not be closed.

**Comment by nolimits4web** [comment]
@coorasse "center" element on Material theme should stick to the left side

**Comment by coorasse** [comment]
By specification? If so, do you have a link to that specific please? I tried to Google a little bit about it but I can't find anything about this topic.

**Comment by nolimits4web** [comment]
https://www.google.com/design/spec/layout/structure.html

**Comment by coorasse** [comment]
Cool, thanks. I still think "center" class is leading to misunderstanding but I hope this conversation will be helpful for someone else.

**Comment by koofah** [comment]
Thanks . it saved me hours of frustration.

**Comment by rajabilal555** [comment]
But for some reason for me it's like this...
![screenshot_2017-03-19-16-11-37-02](https://cloud.githubusercontent.com/assets/15360941/24080356/3a9def7e-0cbf-11e7-919e-ed380ce05fd6.png)

my code:
```				 <div class="left">
				 	<a href="#" class="link icon-only open-panel">
				 		<i class="icon icon-bars"></i>
				 	</a>
				 </div>```

**Comment by noxx2** [comment]
@rajabilal555 Had the same issue as you and found [this](https://github.com/nolimits4web/Framework7/issues/631#issuecomment-142987578) to be the solution.
