### ISSUE TITLE
Fixed position bug in iOS browser

### ISSUE THREAD

**Issue by roshanca** [nolimits4web/Framework7#875]
When setting element `position: fixed` inner `page-content`, it performances normal in desktop browser, but not work in iOS browser.

desktop:

![](http://ww1.sinaimg.cn/large/550f5a78gw1f1pitbwft5g208r0fpmxy.gif)

iOS:

[Here's the video shot on youtube](https://youtu.be/BGScIbQqnzI)

I found that was probably caused by `-webkit-overflow-scrolling: touch` on `page-content`.In case of reset `-webkit-overflow-scrolling: auto` on it, the problem solved.

**Comment by nolimits4web** [comment]
Just put it inside of `.page` with `position: absolute` instead
