### ISSUE TITLE
a problem about commit "Save push state url for inline pages" 290ca661d13eb0968a01fd8d428bd33c5bf421a8

### ISSUE THREAD

**Issue by Poordeveloper** [nolimits4web/Framework7#877]
I was trying to debug the issue of #868, found the issue started from this commit. After I rollbacked your modification "url = undefined;" in clicks.js, my issues got solved. The problems happen when clicking 'back" if there is deep recursive repeat history, e.g. 'a->b->a->b->a->b'. Hope you can get some clue from this.

For example in my app.
http://localhost:3000/
click -> http://localhost:3000/#!/#brokerDetails?id=56651974ddb299ad8287072f
click -> http://localhost:3000/#!/#carDetails?id=56e21dd7128fe10051b7c4f8
click -> http://localhost:3000/#!/#brokerDetails?id=56651974ddb299ad8287072f
click -> http://localhost:3000/#!/#carDetails?id=56e21dceefa6310054f5814e

back -> http://localhost:3000/#!/#brokerDetails?id=56651974ddb299ad8287072f
back -> http://localhost:3000/#!/#carDetails?id=56e21dd7128fe10051b7c4f8  ====> here, the page is totally screwed up, it does not load carDetails page, or even brokerDetails/index page, it loads in another page which is never accessed.

**Comment by atukilham** [comment]
same with my problem..
please help..

**Comment by ZanderBrown** [comment]
Does this issue still occur?
