### ISSUE TITLE
Template7 COMMON data

### ISSUE THREAD

**Issue by valentin93** [nolimits4web/Framework7#880]
Hello.
Now I ask for each page

`'page:contacts': {
       tel: '(999)-111-22-33',
       email: 'contact@john.doe'
   },`
`'page:index': {
       tel: '(999)-111-22-33',
       email: 'contact@john.doe'
   },`

and so on.
How to set common to all?
For example.
`'page:*': {
       tel: '(999)-111-22-33',
       email: 'contact@john.doe'
   },`
OR
`'allpage': {
       tel: '(999)-111-22-33',
       email: 'contact@john.doe'
   },`
:)
Help me please. Thank you

**Comment by nolimits4web** [comment]
You can use Template7 global data, check "Global Context" section at http://idangero.us/template7/

**Comment by valentin93** [comment]
I have to use the prefix @global.
Is it possible to maintain the structure without the use of a prefix?
{{TEST}}, instead of {{@global.TEST}}

**Comment by nolimits4web** [comment]
No, global data has to be used via `@global`, otherwise, you may merge each page data with the required common parameters using custom solution or any other lib, for example with jQuery:
```
var commonData = { tel: '(999)-111-22-33', email: 'contact@john.doe' };

...
'page:contacts': jQuery.extend({foo: 'bar'}, commonData);,
'page:index': jQuery.extend({bar: 'foo'}, commonData);,

**Comment by ZanderBrown** [comment]
Misinterpretation of docs
