### ISSUE TITLE
About calendar problems

### ISSUE THREAD

**Issue by MakeHui** [nolimits4web/Framework7#881]
Hello, I found some of canendar problems. 

1).  displayValues is undefined

``` javascript
var calendarDefault = myApp.calendar({
    onChange: function(p, values, displayValues) {
        console.log(displayValues);     // output: undefined
    }
});
```

2). He could not be opened. I do not understand what is the reason

``` javascript
// can not open
$$(page.container).click(function() {
    calendarDefault.open();
});

// can open
$$(document).click(function() {
    calendarDefault.open();
});
```

**Comment by nolimits4web** [comment]
Look at Calendar API http://framework7.io/docs/calendar.html
As for `displayValues` there is no such variable in callback, it is mistake in docs

**Comment by MakeHui** [comment]
But I need him, I is do so: 
```javascript
// line: 9764
if (p.params.onChange) {
	inputValue = [];
	for (i = 0; i < p.value.length; i++) {
		inputValue.push(formatDate(p.value[i]))
	}
	p.params.onChange(p, p.value, inputValue)
}
```
It work, will it wrong?

**Comment by nolimits4web** [comment]
Will be good to see live example, JSFiddle, or full related code

**Comment by MakeHui** [comment]
https://github.com/MakeHui/framework7-test

**Comment by MakeHui** [comment]
https://github.com/MakeHui/framework7-test

**Comment by MakeHui** [comment]
https://github.com/MakeHui/framework7-test

**Comment by ZanderBrown** [comment]
No response and this seems to be a misinterpretation of the docs

**Comment by dantunes** [comment]
For anyone facing the 2nd issue:

> 2). He could not be opened. I do not understand what is the reason
> 
> // can not open
> $$(page.container).click(function() {
>     calendarDefault.open();
> });
> 
> // can open
> $$(document).click(function() {
>     calendarDefault.open();
> });

I found that when you have the `closeByOutsideClick` property on `true` (by default on calendar init), the bubling cause by the **`click `** event fires the `close` event of the calendar.

This is fixed by setting a handler with the `e.stopImmediatePropagation();` to avoid the bubbling (I'm rewriting the original example from this issue):

```
$$(page.container).click(function(e) {
    e.stopImmediatePropagation();
    calendarDefault.open();
});
```

BTW, I'm using Framework7 v1.6.4

**Comment by nirajkaushal** [comment]
Thanks @dantunes :relaxed:
