### ISSUE TITLE
Incorrect positioning of Listview bottom border

### ISSUE THREAD

**Issue by djzmo** [nolimits4web/Framework7#882]
![screenshot](https://cloud.githubusercontent.com/assets/1124425/13755545/b81a6810-ea56-11e5-9c64-b76822cd4fd8.jpg)

Please consider the attached image, The last element in the listview was not displayed in full due to cropping by the bottom border, probably caused by incorrect sizing of the ul tag.

**Comment by nolimits4web** [comment]
Looks like you have an issue with HTML layout, no? Otherwise why it should be

**Comment by djzmo** [comment]
Not quite sure as I didn't do a lot of modifications. Most of the time I copy snippets from the official docs as the barebone.

In this case, here is my page:
```html
<div data-page="customers" class="page navbar-fixed">
    <div class="navbar">
        <div class="navbar-inner">
            <div class="left"><a href="#dashboard" class="link back"><i class="fa fa-angle-left"></i></a></div>
            <div class="center">Customers</div>
            <div class="right"><a href="#" class="link"><i class="fa fa-user-plus"></i></a></div>
        </div>
    </div>
    <div class="page-content">
        <div class="list-block virtual-list" id="customersList">
        </div>
    </div>
</div>
```

and a jquery call to populate the list:
```javascript
$.ajax({
    type: 'post',
    url: 'get-customers',
    timeout: 10000,
    success: function(data)
    {
        var rows = data.data;
        for(var i = 0; i < rows.length; ++i)
        {
            list.appendItem({ id: rows[i].id, name: rows[i].name, email: rows[i].email });
        }
    });
```

and that's it

**Comment by nolimits4web** [comment]
I guess `height: 44` in VL settings is wrong in this case, should be `48` for material theme

**Comment by djzmo** [comment]
I see, that solved the issue.

As I only followed what was stated in the docs, and there's no mention to that 48-for-material exception anywhere in the Virtual List docs at all, I have to ask for a polite favor to update the docs to be material-friendly as well, as most of them are still majorly centered on the iOS theme.

Nonetheless, thanks for the quick response and for this wonderful framework!
