### ISSUE TITLE
myCalendar.open() issue

### ISSUE THREAD

**Issue by ianmcxa** [nolimits4web/Framework7#883]
calling .open() on a calendar will result in the calendar being drawn off the screen. This only happens if the screen size is set low. I am not sure of the exact resolution, but it happens on my 5 inch phone, and other small displays.

**Comment by nolimits4web** [comment]
Would be good to see live example or at least screenshots

**Comment by ZanderBrown** [comment]
Without using an emulated device resolution lower than any phone available i cannot reproduce this.
This issue has now been dormant for 10 months.
