### ISSUE TITLE
Textfield cursor doesn't scroll with page on Safari for iOS

### ISSUE THREAD

**Issue by Joshi1998** [nolimits4web/Framework7#884]
Hey Framework7 developers,

I've found a bug:
When I select a text field in iOS (Safari) there is a little blinking cursor. Now I scroll the site but the cursor stays at its position and doesn't scroll with the text field.
It would be nice if you'll check that and fix it :)

Here a screenshot:
![screen](https://cloud.githubusercontent.com/assets/16399787/13769718/27583ee8-ea82-11e5-8783-9b1910687f02.png)

Thank you!

**Comment by nolimits4web** [comment]
It is iOS issue, try to use WKWebView in cordova app instead of default UIWebView

**Comment by Joshi1998** [comment]
@nolimits4web 

I'm using Safari, it's not a cordova app.
