### ISSUE TITLE
'Morph to popover' animation is buggy on Chrome for Android

### ISSUE THREAD

**Issue by J05HI** [nolimits4web/Framework7#885]
Hey developers,

I've found another bug (only for Android devices on Chrome):
If you click on the 'Morph to popover' floating action button the povover has rounded edges for 2-3 seconds, then it pops up completly.
I think this must be a rendering bug on Chrome, you only need to fix the animation.

This for 2-3 seconds:
![713423639_11816_13565594544175999126](https://cloud.githubusercontent.com/assets/16399787/13775949/b59aabe4-eaa7-11e5-8424-4e59ecf7cd02.jpg)

Thank you!

**Comment by nolimits4web** [comment]
I guess it is device-related, can't replicate it on my Android device

**Comment by Joshi1998** [comment]
@nolimits4web 

Maby you can change the animation

**Comment by achmadk** [comment]
I have same problem with @J05HI in my android device (xiaomi redmi 2 with android KitKat 4.4.4/ API 19). When popover is rounded, the lists cannot be clicked.

![screenshot_2016-12-29-08-48-03-178_id turez mobile](https://cloud.githubusercontent.com/assets/8057028/21535288/58be0bfa-cda5-11e6-87bd-2b4ee8189238.png)

**Comment by J05HI** [comment]
@nolimits4web 

What's up? 
When do you merge my pull request?

**Comment by J05HI** [comment]
It's working on latest chrome, not perfect but usable :)
