### ISSUE TITLE
form storage + hidden input make your hidden value disappear 

### ISSUE THREAD

**Issue by GuillaumeBiton** [nolimits4web/Framework7#886]
Hi,

context: I use form-storage and I populate my form using formStoreData function

If I check what F7 store, I have my data, it's ok. But my I change a value in a text input, my hidden inputs fall back to "".

Is it normal ?

**Comment by GuillaumeBiton** [comment]
OK I found that hidden inputs fall back to "" when there are not String

**Comment by nolimits4web** [comment]
Ok, i guess we can close it. Reopen if it is still actual and how to replicate it
