### ISSUE TITLE
Incorrect padding of content in material mode

### ISSUE THREAD

**Issue by SirusDoma** [nolimits4web/Framework7#887]
After discovering the layouts and components on official docs, I noticed that most of layouts has incorrect padding of content in material mode.

Let's say Pull To Refresh component. In material mode, the gap between the navbar and the list view / contents shouldn't be exist.

And currently, it's seems the official docs is not really material friendly.
Nonetheless, thanks for this awesome framework!

**Comment by nolimits4web** [comment]
I tried to make it more unified with iOS theme, and there is no strict rules about `the gap between the navbar and the list view / contents shouldn't be exist` and in many native apps it is different as well. So just remove it manually in your CSS if you don't need it
