### ISSUE TITLE
Can't tap google autocomplete places prediction search

### ISSUE THREAD

**Issue by souravchat** [nolimits4web/Framework7#888]
Hi I am having some problems with the google autocomplete. I can not tap google autocomplete predictions .

**index.html:-**

<div class="item-input">
<input type="text" id="pac-input" placeholder="Place you want to visit">
</div>

**user-script.js:-**

$(document).on("input", "#pac-input", function(evt)
    { 
        autoComplete();
    }); 

**maps.js:-**

function autoComplete(places){
    var autocompletePlaces = new    google.maps.places.Autocomplete(document.getElementById('pac-input'));
   google.maps.event.addListener(autocompletePlaces,'place_changed', function () {
                var place = autocompletePlaces.getPlace();
                var address = place.formatted_address;
                var latlang = new google.maps.LatLng(place.geometry.location.lat(),place.geometry.location.lng());
            }); 
    $$('body').on('touchend','.pac-container',function(e){
        alert('touchend');
        e.stopImmediatePropagation();});
}

**Comment by nolimits4web** [comment]
I guess it is the same as #95
