### ISSUE TITLE
A brand new Framework7 app generates a warning in Chrome device emulator on scrolling

### ISSUE THREAD

**Issue by mitya** [nolimits4web/Framework7#891]
A fresh new app generates a warning message in Chrome device simulator on scrolling. For some reason it generates a warning only when an iPhone simulator is selected, Android simulators don't produce any warnings.

To reproduce it — just generate a new app with a couple pages of static content.

The warning says:
> Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

It doesn't seem to be harmful, but it is a bit annoying.

**Comment by nolimits4web** [comment]
You should expect that something may work wrong if you emulate iPhone in desktop Chrome
