### ISSUE TITLE
app.resizeTextarea

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [nolimits4web/Framework7#894]
Hello Framework7 team,

The Resizable Textarea is just working fine when entering text.
But I would like to have the textarea getting its autosize when a form is opened and receives the value from formFromJSON.
I tried to call the script myApp.resizeTextarea(); but that does not work
Do you have a suggestion?

Kind regards,
Mario

**Comment by nolimits4web** [comment]
Just do `$('textarea').trigger('change')` after you fill it with value

**Comment by MarioVanDenEijnde** [comment]
That works fine.
The height is about twice as it needs to be but I am not complaining.

Thanks.
Mario

**Comment by vousys** [comment]
I try it but is not working for me in version 1.6.4

I load the page with :
 ```
                       mainView.router.load({
                          url: url ,
                          context: {

```
 and in my callback of myApp.onPageAfterAnimation
I've added
` $('textarea').trigger('change'); 
`
but nothings resize.
