### ISSUE TITLE
How customize this way?

### ISSUE THREAD

**Issue by henriqueweiand** [nolimits4web/Framework7#895]
Hello guys!

Someone can help me customize the swipejs to stay that way?
I'm working on it a few hours and I can not :(

![screenshot_20160320-142820](https://cloud.githubusercontent.com/assets/6539492/13905793/aee324b6-eea8-11e5-8ef3-4c994154e07c.png)

**Comment by nolimits4web** [comment]
Just play with options, look at demos, probably something like that:
```
centeredSlides: true,
slidesPerView: 'auto',
spaceBetween: 20,
```
and in CSS
```
.swiper-slide {
  width: 70%;
}
