### ISSUE TITLE
context lost on back when level > 1

### ISSUE THREAD

**Issue by reecube** [nolimits4web/Framework7#897]
I'm using the current release 1.4.2 of framework7.

I have an application with a master-detail view where you could go deeper than level 1. Works fine until you click on the back button. When you try to go back framework7 looses the context and is not able to render the page correctly.

For example (all pages are in #view-main):
# page-master (context: movies)
# page-detail-movie (context: movie.@index)
# page-detail-actor (context: actor.@index)

If you are on the master page and select a movie, the app navigates to the movie-detail page with the given context and then you can select an actor to navigate to the actor-detail page. Everything is working fine here. But then you click on "back" from actor-detail page and the app navigates to movie-detail page but the context is lost, this means there is no data to show.

PS. I'm using Ajax-Pages and Template7 to render them with the given context.

**Comment by nolimits4web** [comment]
It depends on how do you pass context there. I can recommend you to enable `domCache` for this View

**Comment by shuizhongyueming** [comment]
@nolimits4web 

I have same problem for this. And I was using the release 1.4.2 also.

In my project, there is a `gameDetail` page that is load dynamically

```javascript
        mainView.router.load({
            url: $$curr.data('href')+'?id='+gameId,
            context: Template7.data[api.DATA_TYPE_GAME][gameId]
        });
```

and in the `gameDetail` page, you can load another `gameDetail` page with different gameId.

so, the history will be some like this:

```javascript
[
  'game-detail.html?id=1',
  'game-detail.html?id=23',
  'game-detail.html?id=14',
  'game-detail.html?id=56',
  'game-detail.html?id=6',
  ...
]
```

now, if the page is active with `game-detail.html?id=6`. then, press the back button on the nav.

the page will trans to the `game-detail.html?id=56`, and because the page `game-detail.html?id=56` is cache in the dom, so it will show normally.

But because the history's length is bigger than 1, so the framework will try to preload page 'game-detail.html?id=14'

```javascript
// router.js afterBack

// Preload previous page
if (view.params.preloadPreviousPage) {
    if (view.params.domCache && view.history.length > 1) {
        var preloadUrl = view.history[view.history.length - 2];
        var previousPage;
        var previousNavbar;
        if (preloadUrl && view.pagesCache[preloadUrl]) {
            // Load by page name
            previousPage = $(view.container).find('.page[data-page="' + view.pagesCache[preloadUrl] + '"]');
            if (previousPage.next('.page')[0] !== newPage[0]) previousPage.insertBefore(newPage);
            if (newNavbar) {
                previousNavbar = $(view.container).find('.navbar-inner[data-page="' + view.pagesCache[preloadUrl] + '"]');
                if(!previousNavbar || previousNavbar.length === 0) previousNavbar = newNavbar.prev('.navbar-inner.cached');
                if (previousNavbar.next('.navbar-inner')[0] !== newNavbar[0]) previousNavbar.insertBefore(newNavbar);
            }
        }
        else {
            // Just load previous page
            previousPage = newPage.prev('.page.cached');
            if (newNavbar) previousNavbar = newNavbar.prev('.navbar-inner.cached');
        }
        if (previousPage && previousPage.length > 0) previousPage.removeClass('cached page-on-right page-on-center').addClass('page-on-left');
        if (previousNavbar && previousNavbar.length > 0) previousNavbar.removeClass('cached navbar-on-right navbar-on-center').addClass('navbar-on-left');
    }
    else {
        app.router.back(view, {preloadOnly: true});
    }
}
```

the `gameDetail` page is need some right context to load, and the preload can't hold it rightly, and this will cause the template7 compile error. And the whole app shutdown.

So, can we make some hook for this behavior, to add the right context for the preload.

My english is not so well, and sorry for some potentially syntax error.

**Comment by shuizhongyueming** [comment]
I have fix this problem by add a custom [plugin](http://framework7.io/docs/plugins-api.html).

This demo is only suitable for my project. But anyone can take this as a reference. 

```javascript
Framework7.prototype.plugins.handleGameDetailBack = function(app, params){
    return {
        hooks: {

            // the routerBack hooks will call every time the page back happen
            routerBack: function(view, options){
                var query = '',
                    url = '';

                /**
                 * the preloadOnly will be true only this back is a preload of next backed(or left to right) page
                 * check the context for the framework in the future may add context for preload
                 * check the url in the option and only response for some page you need add context
                 */
                if (options && options.preloadOnly === true && typeof options.context === 'undefined' && (url = options.url).indexOf(Template7.global.pageName.gameDetail) !== -1) {

                    // $$ is the Framework7's dom7 
                    // it has a method parseUrlQuery that can parse url to a key value map
                    query = $$.parseUrlQuery(url);

                    // set the context you need
                    options.context = Template7.data[api.DATA_TYPE_GAME][query.id];
                }
            }
        }
    };
};
```

**Comment by reecube** [comment]
This pull-request would fix the issue on the core: https://github.com/nolimits4web/Framework7/pull/898

**Comment by blikblum** [comment]
Seems that this issue can be closed

**Comment by codetrash** [comment]
im still having the issue , even though im using the latest version



if im using query
```
detail_article.html?id=45

```
before I navigate to : Catagory1 -> Category 2 -> Detail Article

When I hit Back on Detail, it goes to Catagory1 instead of Category 2
