### ISSUE TITLE
Add mousewheel for Picker

### ISSUE THREAD

**Issue by evolutionjay** [nolimits4web/Framework7#901]
I know this framework is for the mobile terminal, but I still want to join mousewheel support in picker. Holp add a `mousewheel:true`  option.

**Comment by Joshi1998** [comment]
Yeah that would be nice :)

**Comment by ZanderBrown** [comment]
@nolimits4web any thoughts?

**Comment by nolimits4web** [comment]
F7's main target is mobile devices. Picker is the mobile-oriented component too. I don't see much sense to include mousewheel support, as it requires a lot of code and its complex is not so simple
