### ISSUE TITLE
Navigation bar not working on meteor mobile app

### ISSUE THREAD

**Issue by srinivasdamam** [nolimits4web/Framework7#906]
Navbar looks like partially loaded, I have tested a few components they are working,
Is this framework supported now for meteor? 
![screenshot from 2016-03-27 00-10-35](https://cloud.githubusercontent.com/assets/13461208/14061861/e791c93a-f3b1-11e5-9ad6-653ca1e0703a.png)

**Comment by nolimits4web** [comment]
There is no native support for Meteor, but i see many people use it with it. Looks like issue somewhere on meteor side or in order of loading styles and scripts
