### ISSUE TITLE
swipe + tabs?

### ISSUE THREAD

**Issue by henriqueweiand** [nolimits4web/Framework7#907]
It is possible to put the swype with tabs? An example?

--- Edit ----

Solution:

`<div class="tabs-swipeable-wrap">`

**Comment by JhonnyJason** [comment]
guess it could fit here, it is just a question and no issue anyways^^
Is there a possibility to set a swipe threshold for the swipable tabs?
Like in the way, one is able to do it using the swiper element.

help would be appreciated^^... I'm continue googling anyways and post an answer if I find one :-)

**Comment by JhonnyJason** [comment]
haha no google no looking to the source helped :-) the class tabs-swibable-wrap is handled similar like the .init-swipe class 

so you may add the data-threshold attribute to change that parameter - thanks to open source once again!! :D
And thanks for your work on the framework ;-)

cheers!
