### ISSUE TITLE
Multiple View Layout Framework7 Hybrid Application

### ISSUE THREAD

**Issue by smshahiran** [nolimits4web/Framework7#908]
I have 2 different layouts. One for before login and one more for after login.

I already read the instructions here. http://framework7.io/docs/views.html

And still cant understand why my apps become like this:

http://i.stack.imgur.com/UU0ZJ.png

It display 2 views at once. Can scroll fully throught both views.

This is the js involved:

`var mainView = myApp.addView('.view-main');`
`var anotherView = myApp.addView('.another-view');`

//to call anotherView after login
mainView.router.load(anotherView);

**Comment by nolimits4web** [comment]
Just add "display:none" to hidden view by default, and then hide login view and show after login view. You can use something like:
```
$('.view-main').show();
$('.another-view').hide();
```
etc

**Comment by nigelbpeck** [comment]
Shouldn't this be the default behaviour? It seems very strange that multiple views in one page all get displayed by default.

**Comment by ZanderBrown** [comment]
Split view or views in tabs

**Comment by China77** [comment]
var mainView = app.addView('.view-main'); 2.0.0 error
0
app.addView is not a function
var app = new Framework7({
root: ‘#app’,
theme: theme,…Like
