### ISSUE TITLE
navbar similar to cards

### ISSUE THREAD

**Issue by henriqueweiand** [nolimits4web/Framework7#912]
How can I implement a navbar that way?

![orderup-menu-android](https://cloud.githubusercontent.com/assets/6539492/14160201/4fccd402-f6b1-11e5-9f7c-39104eeeb685.png)

You do not even have tabs ... Only the background image and the superior options

**Comment by chalchis** [comment]
it would be great

**Comment by robbyl** [comment]
Sure!
Or something like this you can even put floating action button, will be cool. when you scroll up the title in between slides up to the title bar.
![style_imagery_principles1](https://cloud.githubusercontent.com/assets/1931548/14172029/bdfdd6a0-f73e-11e5-9645-a39ebbd4a66e.png)

**Comment by nolimits4web** [comment]
Just put a div with required size and image in the page and make navbar transparent. There were few solutions of F7 forum for that
