### ISSUE TITLE
Prevent scrolling bounce effect

### ISSUE THREAD

**Issue by valentinld** [nolimits4web/Framework7#915]
Hi, I have a problem with my F7 app.

When I have a page with content who don't take all of the height, it's OK, for example like this :
![screen1](https://cloud.githubusercontent.com/assets/18194554/14183974/2a1899a4-f773-11e5-9b22-4155e53b64f4.jpg)

But when I have content who take more than the heigh, the div is scrollable (it's normal, it's ok) but the top and the bottom "overflow and bounce". It's difficult for me to explain the problem because I'm french. So have a look to this picture who describe my problem : 
![screen2](https://cloud.githubusercontent.com/assets/18194554/14184051/879753c2-f773-11e5-8011-34fd3d26ca7c.jpg)

I have tested ` <preference name="DisallowOverscroll" value="true" />` 
But it's juste solve the navbar bounce, but note the content page bounce.

I have tested `.page-content {
   margin-bottom:1px;
}
.page {
   overflow: auto;
   -webkit-overflow-scrolling: touch;
}`

But it not works.

Thanks in advance

**Comment by nolimits4web** [comment]
It is default iOS effect which is excpected by iOS users, not sure it can be disabled easily. Actually can't see any problems with it. Just make page background color same white as list bg color

**Comment by scriptPilot** [comment]
This works well with current Framework7 version to eliminate the bounce effect:
- 1. Download https://github.com/lazd/iNoBounce/blob/master/inobounce.min.js
- 2. Include script `<script type="text/javascript" src="js/inobounce.min.js"></script>`
- 3. Add css to .views container
```
.views {
  height: 100%;
  overflow: auto;
  -webkit-overflow-scrolling: touch;
}
```
