### ISSUE TITLE
[Future Request] Full Calendar

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#918]
http://fullcalendar.io/ Integration

![image](https://cloud.githubusercontent.com/assets/7137859/14216936/0cc51732-f869-11e5-8dd8-ae4fd8d79830.png)

**Comment by mayos** [comment]
Hello @nolimits4web ,
Were you able to work on it? We need this in our app.
Our developer has included jquery at the app project, and it works, but I don't really like this idea.

Thank you,

**Comment by farskid** [comment]
@nolimits4web Also while implementing the feature, why not supporting other calendars such as Jalali Calendar??

**Comment by tobya** [comment]
I got FullCalendar to work in a panel in an app.  This works without a specific integration.  @mayos Why do you not like the idea of including jquery.  FullCalendar is  JQuery dependent so would require jQuery to run anyway.

**Comment by J05HI** [comment]
@murliatdure 
You can use the Framework7 calendar and its events. 
This is the calendar I've built at work:
![screenshot_20170304-105830](https://cloud.githubusercontent.com/assets/16399787/23577833/9264993a-00c9-11e7-8fdb-0bec5730f8cc.png)

@nolimits4web @ZanderBrown @valnub 
Can be closed.
