### ISSUE TITLE
1.4.2 Release makes index navbar load twice

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [nolimits4web/Framework7#920]
Hello Framework7 team,

We noticed that in 1.4.2 Release with the following link the #index navbar is included in DOM twice.
<a href="#index" class="item-link back" data-force="true">

This behavior causes the second "index" navbar content to be positioned below the initial "index" navbar.
# index is the app start page.

Is this intentionally? 
Please advise.

Kind regards,
Mario

**Comment by nolimits4web** [comment]
Would be good to see full HTML layout of the app, views and navbars

**Comment by J05HI** [comment]
@nolimits4web @valnub @ZanderBrown 
Can be closed.

**Comment by ZanderBrown** [comment]
@J05HI could you please include reasons with close requests?

**Comment by J05HI** [comment]
@ZanderBrown 
Okay, it's not reproduceable.
