### ISSUE TITLE
preroute has a big bug

### ISSUE THREAD

**Issue by ijry** [nolimits4web/Framework7#922]
i find both preroute callback in  app.router.back = function (view, options) {} and   app.router.load = function (view, options) {}

**Comment by nolimits4web** [comment]
And where is the bug?

**Comment by ijry** [comment]
preroute

**Comment by ijry** [comment]
in preroute if i do router.load  than I  won't    apply  app.router.back any more !

**Comment by ijry** [comment]
`preroute: function (view, options) {
                console.log(options);
                if (!options) {
                    return true;
                }
                if (!options.router) {
                    return true;
                }
                if (options.router === 'load') {
                    if (navigator.onLine) {
                        if (options.url && !options.reloadPrevious) {
                            var str = options.url;
                            if(!(str.indexOf("http://") >= 0) && !(str.indexOf("file://") >= 0)) {
                                console.log(str);
                                view.loadPage(OpenCMF.DOMAIN + str);
                                return false;
                            }
                        }
                    } else {
                        if (options.url) {
                            var html = localStorage.getItem(options.url);
                            if (!html) {
                                $.alertMessager('该页面尚无缓存，请您先联网！');
                            }
                            view.router.loadContent(html);
                            var op = new Object();
                            op.content = html;
                            view.router.load(op);
                            return false;
                        }
                    }
                }
            }`

**Comment by ijry** [comment]
![qq20160430-0](https://cloud.githubusercontent.com/assets/3102798/14923757/89bb1d04-0e71-11e6-9893-80534a8f85a2.png)

**Comment by ijry** [comment]
because of this bug , i have to to this  in handleClicks function 
![qq20160430-1](https://cloud.githubusercontent.com/assets/3102798/14923804/f5d91e46-0e71-11e6-9648-c7341c18cd65.png)

**Comment by ijry** [comment]
can you see I add a  'options.router = 'load';'

**Comment by ijry** [comment]
in fact , what confuse me is I cann't distinguish  load and back  in preroute , there is no mark I can use?

**Comment by nolimits4web** [comment]
@ijry check #923
