### ISSUE TITLE
preroute has a serious bug

### ISSUE THREAD

**Issue by ijry** [nolimits4web/Framework7#923]
I find both preroute callback in  app.router.back = function (view, options) {} and   app.router.load = function (view, options) {}  , actually I only want is preroute can work  in  load  function，but 1.4.2 confused me in this way 。Icannot judge  is load or back which bring me back bug.
`preroute: function (view, options) {
                console.log(options);
                if(navigator.onLine){
                    if (options.url && !options.reloadPrevious) {
                        var str = options.url;
                        if(!(str.indexOf("http://") >= 0) && !(str.indexOf("file://") >= 0)) {
                            console.log(str);
                            view.loadPage(OpenCMF.DOMAIN + str);
                            return false;
                        }
                    }
                } else {
                    if (options.url) {
                        var html = localStorage.getItem(options.url);
                        if (!html) {
                            $.alertMessager('该页面尚无缓存，请您先联网！');
                        }
                        view.router.loadContent(html);
                        return false;
                    }
                }
            }`

**Comment by ijry** [comment]
may be add a param like is_back weill help 
`
if (clicked.hasClass('back')) {
                        options.is_back = true;
                        view.router.back(options);
                    }
`

**Comment by nolimits4web** [comment]
Fixed now:
```
preroute: function (view, options) {
    if (options.isBack) {  ... caused by router.back, don't do preroute if you don't need it ... }
    else { ... caused by router.load, do preroute if you need it ... {
}

**Comment by ijry** [comment]
thks good!!!
