### ISSUE TITLE
pageInit возвращает не то имя страницы

### ISSUE THREAD

**Issue by valentin93** [nolimits4web/Framework7#924]
Добрый день.
Отслеживаю название страницы 

```
    $$(document).on('pageInit', function (e) {
        var name = e.detail.page.name;
        console.log(name);
    });
```

Есть одна страница с именем live, которая подгружается стандартным роутером фреймворка.
И помимо нее есть 3 динамические страницы, которые создаю вот так.

```
      mainView.router.load({
           content: html
      });
```

Где html содержит 

`<div class="page libe-bet-page" data-page="live1">`

 live1, live2 и live3 соответственно.
и ссылку назад которая одинакова на всех страницах.

```
<a href="#" class="back link">
     <i class="icon icon-back"></i><span class="">{{@global.BACK}}</span>
</a>
```

Далее я перешел на страницу live.
С нее на live1, live2, live3.

Событие отслеживания имени страницы успешно отобразило их.
Находясь на live3 нажимаю назад, и вижу что имя страницы теперь live. То есть имя последней не динамической страницы. Хотя я сейчас нахожусь на live2.
Нажимаю ещё раз назад, нахожусь на live1. Теперь название страницы вообще 'undefined' .
Мое предположение, что когда я начал переходить по динамическим страницам, имя этих динамических страниц перестало сохраняться.

Помогите понять, что не так)

P.S.
Sorry, My English is weak to describe this complex problem)

**Comment by valentin93** [comment]
look the theme "back to dinamic page, incorrect page name"

**Comment by ZanderBrown** [comment]
Is this issue resolved?

P.S. Don't worry about language it's easier for us to translate a detailed description in language 'x' to our respective languages than try to understand broken English that doesn't describe the problem
