### ISSUE TITLE
Lazy Load Allow User Specified Ratio

### ISSUE THREAD

**Issue by vestaxpdx** [nolimits4web/Framework7#928]
Hi,

Amazing framework by the way. Is it possible to make a very simple change to allow users to specify the initial src attribute on the image tags. I know there is imagesLazyLoadPlaceholder parameter but my page has varying image ratios which cause the page to jump when they load if they are not all a certain ratio. Some of my photos are 16x9 or 4x3 on one page etc. So I can't just set one placeholder image in imagesLazyLoadPlaceholder parameter.

In Framework7 1.4.2

If we change line 4295

`if ($(this).attr('data-src')) $(this).attr('src', placeholderSrc);`

to

`if ($(this).attr('data-src') && !$(this).attr('src')) $(this).attr('src', placeholderSrc);`

This allows users to simply specify the image tag as follows and scales the placeholder image correctly. Where lazy-16x9.jpg is 16x9 pixels in size and lazy-4x3.jpg is 4x3 pixels in size.

`<img data-src="path/to/main/img" src="img/lazy-16x9.jpg" class="lazy lazy-fadeIn">
<img data-src="path/to/main/img" src="img/lazy-4x3.jpg" class="lazy lazy-fadeIn">`

It would be great if we could get this added?

**Comment by tobya** [comment]
You could make this change on a fork and provide a pull request

**Comment by ZanderBrown** [comment]
@vestaxpdx as @tobya suggested could you open a PR?
