### ISSUE TITLE
Slider knob not showing in Chrome

### ISSUE THREAD

**Issue by tobya** [nolimits4web/Framework7#929]
Due to some recent update (probably in chrome) the knob on the slider control is no longer showing in Chrome.  The slider still works and can be used and correctly returns values, you just cant' see were you have selected.

The knob is shown fine in firefox.

For an example see the 'Inline Pages' example on 

http://framework7.io/examples/

Firefox.

![image](https://cloud.githubusercontent.com/assets/325502/18782290/a7065a3e-817d-11e6-934f-a24ace02951b.png)

Chrome

![websiteimage208](https://cloud.githubusercontent.com/assets/325502/18782299/b7f48686-817d-11e6-9d2a-e9b3ccbdc463.jpg)

**Comment by mrbellek** [comment]
This issue is still present on the current version of Chrome (v50.0.2661).

**Comment by amnond** [comment]
Can confirm this is still an issue on Crome (v51.0.2704.103, 64-bit on OS/X)

**Comment by ZanderBrown** [comment]
Can also confirm bug

Windows 8.1 32Bit
Chrome 54.0.2810.2

**Comment by tobya** [comment]
I think I found one solution to this, but I don't know less or css well enough to do it right.

If I change this 

    .range-slider input[type="range"]::-webkit-slider-thumb {
      -webkit-appearance: none;
      -moz-appearance: none;
      -ms-appearance: none;
      appearance: none;
    <snip>
    }

to 

    .range-slider input[type="range"]::-webkit-slider-thumb {
     -webkit-appearance: sliderthumb-horizontal;
     -moz-appearance: sliderthumb-horizontal;
     -ms-appearance: sliderthumb-horizontal;
      appearance: sliderthumb-horizontal;
     <snip>
     }

Then little rectangular slider knobs appear on chrome.  They are not as nice as the normal ones but at least they appear.

![screenhunter_66 01-oct-16 11 21](https://cloud.githubusercontent.com/assets/325502/19013457/439e59c2-87c9-11e6-934a-1d6726c1ccd0.jpg)

It doesnt seeem to have any effect as to how the slider is shown on Firefox or Safari

Hopefully someone can use to this to provide a nice bit of css to be added.

**Comment by tobya** [comment]
#1163 provides a fix for this.

**Comment by tobya** [comment]
I'll leave open until we can modify PR to be acceepted

**Comment by nolimits4web** [comment]
Fixed with #1163

**Comment by RostanDiaz** [comment]
just change the background color of the bellow class in the 

.range-slider input[type="range"]::-webkit-slider-thumb {
  -webkit-appearance: none;
  -moz-appearance: none;
  -ms-appearance: none;
  appearance: none;
  border: none;
  height: 28px;
  width: 28px;
  position: relative;
  background: none ; <------------- this one to ----------->  background: #8e8e93;
}
