### ISSUE TITLE
Select options are invisible on Android with a material design

### ISSUE THREAD

**Issue by whyte624** [nolimits4web/Framework7#933]
As it mentioned in the topic <option> content is not visible on an Android device.
No other styles are included. Material theme is applied.
Looks as follows: ![select options invisible](http://i.imgur.com/UkNqCxZ.png)

In browser with a device emulation looks just fine.

**Comment by ZanderBrown** [comment]
Could you please expand you point?
Consider pointing code snippets here, on [Codepen](https://codepen.io) or on [JSFiddle](https://jsfiddle.net).
Make sure you have read the [documentation](http://framework7.io/docs/) correctly and followed any instructions it may give.

**Comment by whyte624** [comment]
Unfortunately the code is not available for me anymore. So I cannot add more information. Thank you!
