### ISSUE TITLE
Additional "X-Requested-With: XMLHttpRequest" header not set when `crossDomain` set to true

### ISSUE THREAD

**Issue by DGivney** [nolimits4web/Framework7#939]
**From the docs:**  http://framework7.io/docs/dom.html#ajax

| Parameter | Type | Description |
| --- | --- | --- |
| crossDomain | `boolean` | When `true` additional "X-Requested-With: XMLHttpRequest" header will be added to request. |

**From the code:** https://github.com/nolimits4web/Framework7/blob/master/src/js/dom7-ajax.js#L195

```
if (!options.crossDomain) {
    xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
}
```

**Comment by nolimits4web** [comment]
Actually the problem is in documentation. Should be 
> if `true` additional "X-Requested-With: XMLHttpRequest" header will NOT be added to request

So it is correct in code, will fix in docs

**Comment by valnub** [comment]
Should be fixed with https://github.com/nolimits4web/Framework7-Website/pull/60
