### ISSUE TITLE
iOS navbar .center is not actually centered when the number of buttons on L/R side is not the same

### ISSUE THREAD

**Issue by mitya** [nolimits4web/Framework7#949]
<img width="379" alt="screen shot 2016-04-27 at 00 19 32" src="https://cloud.githubusercontent.com/assets/19074/14834618/08bec1d4-0c0e-11e6-960f-71b38718dbe3.png">

When the number of buttons on the left/right side of the navbar is not the same, the navbar title shifts to the side which has less buttons, but as seen on the screenshot there is enough space to accomodate for all the buttons and the title. 

Sure it can easily be fixed by forcing the `width` of the smaller `.left/.right` div, but it would be nice if it handles it somehow automatically.

**Comment by mitya** [comment]
And the same issue is true when left and right sides has 1 and 0 buttons, which is quite a lot more common.

**Comment by nolimits4web** [comment]
It will be rendered correctly no matter of what is in the left or right elements. Just make sure it was added before page init, otherwise just call `sizeNavbar` method http://framework7.io/docs/navbar.html#related-app-and-view-methods

**Comment by KuenzelIT** [comment]
Hey,

I've got the same issue with the Material theme.

Below is my navbar. The title always shifts to the left near the back button. I also tried sizeNavbar, but it didn't change it.
```
<div class="navbar">
                     <div class="navbar-inner">
                         <div class="left">
                             <a href="#index" class="link back">
                                 <i class="icon icon-back"></i> Back
                             </a>
                         </div>
                         <div class="center">Title</div>
                         <div class="right">
                             <a href="#" class="link icon-only open-panel"><i class="icon icon-bars"></i></a>
                         </div>
                     </div>
                 </div>
```

Am I doing anything wrong or is it just the Material theme?

Thanks!
