### ISSUE TITLE
Stop video from loading/playing when you click prev/next

### ISSUE THREAD

**Issue by vestaxpdx** [nolimits4web/Framework7#950]
Hi,

When having 2 or more videos in the photo browser (http://framework7.io/docs/photo-browser.html) the previous video keeps playing in the background when you click next.

It would be awesome if you could perhaps wipe the previous html variable to clear the iframe code and stop the video from playing then re add the html on the fly perhaps when you return to that video.

Or if there is a current work around to fix this I would love to know. Users are lazy and will never click stop before going to the next slide :dancer: 

Cheers

**Comment by nolimits4web** [comment]
It already has 'pause' feature for native <video> element. But in iframes, it depends on developer needs and used service. You can replace HTML of current slide or just replace URL of iframe using callback parameters. Or if you use YouTube and YouTune API you can just pause them within callbacks
