### ISSUE TITLE
Get url for Google Analytics history path

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [nolimits4web/Framework7#957]
Hello Framework7 Team,

We send the url (pushState: true) to google Analytics.
But when we use the back class link we can see that the app goes back in history and also the url shows this but we cannot find a javascript command like mainview.history that follows this url state.
The back class link does not remove the page from the history array and thus the back button does no trigger a analytics history path change.

Do you have an idea how to do this?
We use the Google Tag Manager.

Kind regards,
Mario

**Comment by nolimits4web** [comment]
You can use this callback for all pages, for example:
```js
myApp.onPageAfterAnimation('*', function(page){
    console.log(page.url); // url here
});
