### ISSUE TITLE
使用用消息栏时,弹出键盘以及输入内容后,会把整个页面向上顶

### ISSUE THREAD

**Issue by virgoboy** [nolimits4web/Framework7#961]
使用用消息栏时,弹出键盘以及输入内容后,会把整个页面向上顶 请问怎么解决
如下图
![img_1082](https://cloud.githubusercontent.com/assets/9427907/14986378/36b6391c-117e-11e6-83e6-0390d9d3332d.PNG)
-----------------------------------------------------------------------
![img_1083](https://cloud.githubusercontent.com/assets/9427907/14986392/42d9fa12-117e-11e6-9d74-7c3a654a6058.PNG)

**Comment by sy-ww-sun** [comment]
试用固定页面布局   <div data-page="index" class="page navbar-fixed toolbar-fixed">

**Comment by virgoboy** [comment]
@sy-ww-sun 这样不行,试过了

**Comment by nolimits4web** [comment]
Guys, please use English for issues here
