### ISSUE TITLE
Performance issue with Android 6.x

### ISSUE THREAD

**Issue by sy-ww-sun** [nolimits4web/Framework7#962]
A simple Framework7 example with around 10 inline pages and a list of 20+ images that works greatly on an Android 4.4.4 phone has severe performance falloff when the same phone is upgraded to Android 6.0.1. The most notable two issues are: animation effects for pages switching stagnates, and image loading breaks down. The major change with the upgrade was from Chrome/42.0.2311.153 to Chrome/46.0.2490.76, and some built-in animation effects of Android 6 might also be the reason.

**Comment by ionas** [comment]
Read that it has to do with href="#" somewhere... try that? In case that solves it the guide/docs need to be updated.

**Comment by ahaus** [comment]
I also have severe performance issues on Android (5 and 6). Somtimes the app works "ok" and sometimes it is very "sluggish". Did not find the reason why this happens.

**Comment by sy-ww-sun** [comment]
I noticed that the same issue can disappear with a bit newer Android version. Maybe this should be attributed to the Android WebView itself, not to F7. Please ref. 
[http://forum.framework7.io/#!/bugs-and-issues:animation-performance-fallo](url)
