### ISSUE TITLE
Accordion sometimes not work well in IOS safari browser

### ISSUE THREAD

**Issue by immime** [nolimits4web/Framework7#970]
I find that Accordion sometimes not work well in IOS safari browser.
When expand accordion-item-content element, the inner content sometimes can not be display entirely.

It seems to be caused by the code `content.css('height', content[0].scrollHeight + 'px')` in line 6689 and 6711 in framework7.js (PS:version Framework7 1.4.2)

I tried to replace the code with
`content.css('height', document.body.scrollHeight + 'px')`,
it work well now, hope this issues can help others who face the same problem.

**Comment by immime** [comment]
This proplem occured when i use place two `'.accordion-item-content'` elements under one `.accordion-list`, but the offical useage is one `'.accordion-item-content'` element under one `.accordion-list`.

I tried to replace the code content.css('height', content[0].scrollHeight + 'px') in line 6689  with
content.css('height', content.scrollHeight + 'px'), it works well for two senses above.

**Comment by nolimits4web** [comment]
Can you show/provide example of HTML/JS causing this issue?

**Comment by immime** [comment]
I'm sorry i had removed the code that cause this issue.
Thank you for the amazing framwork7!

**Comment by ouhuiju** [comment]
Hi, I had also face this problem, here's the HTML:

`
<li class="accordion-item pending-update-item" data-bind="foreach: pendingUpdateList">
                    <div class="item-content">
                        <div class="item-media" style="position: fixed;">
                            <img data-bind="attr : {src : $data.appIcon}" class="index-appiconimage">
                        </div>
                        <div class="item-inner" style="padding-left: 60px;">
                            <div class="item-title" data-bind="text:$data.appName"></div>
                            <div class="item-input">
                                <button style="float: right;" class="button installBtn"
                                        data-bind="text : $data.buttonStatus, click: $root.updateAppClickEvent, clickBubble: false, visible : $data.buttonShow()">
                                </button>
                                <div class="progress-container"
                                     style="float: right; width: 35px; height: 35px; margin-right: 10px; position: relative;"
                                     data-bind="visible : !$data.buttonShow()">
                                    <div data-bind="css: 'c100 small p'+ $data.progress()" style="font-size: 32px;">
                                            <span data-bind="text: $data.progress() + '%'"
                                                  style="  width: 2.5em; line-height: 2.5em; font-size: 0.4em; color: #307bbb;"></span>
                                        <div class="slice">
                                            <div class="bar"></div>
                                            <div class="fill"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item-subtitle">
                                <div data-bind="text:'Version ' + $data.currentVersion + ', ' +$data.packageSize"></div>
                                <a class="accordion-item-toggle"
                                   onclick="updateModule.accordionItemToggle(this);">
                                    What's news ▼
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item-content" style="padding-left: 60px;">
                        <div class="content-block version-description" data-bind="html: $data.versionDescription">
                            Support multi-channels
                        </div>
                    </div>
                </li>
`

and i use @immime solution and solved the problem. Thanks.

Can help to check this problem? @nolimits4web  Many Thanks.

Thank you for the amazing framework7!

**Comment by bfgh2678** [comment]
I have problems in ios on the scroll will slide frompage
