### ISSUE TITLE
Layout grid col-45 does not exists as show documentation

### ISSUE THREAD

**Issue by elysiopires** [nolimits4web/Framework7#975]
Hello,

Before anything, congratulations for the great framework and work.

I'm trying to use layout grid col-45, but I checked out the framework7.min.css and saw that does not exists the class col-45.

The correct implementation is this peace of code bellow?
.row .col-45 {
  width: 45%;
  width: -webkit-calc((100% - 15px*1.2222222223) / 2.2222222223);
  width: calc((100% - 15px*1.2222222223) / 2.2222222223);
}
.row.no-gutter .col-45 {
  width: 45%;
}

Thx,
Elysio

**Comment by nolimits4web** [comment]
Make sure you are using latest version of F7 https://github.com/nolimits4web/Framework7/blob/master/dist/css/framework7.ios.css#L187
