### ISSUE TITLE
Elastic Effect (Enhancement)

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#980]
http://codepen.io/suez/pen/emjwvP

![image](http://materialdesignblog.com/wp-content/uploads/2015/03/side-bar.gif)

**Comment by J05HI** [comment]
Code it at your own
You can make a plugin

**Comment by ZanderBrown** [comment]
Cool effect i'll admit but it's complex to implement and isn't really part of the iOS or Material design patterns

**Comment by JosephShenton** [comment]
Still, it is so sexy! I will just make a plugin if Vladmir (i think thats how you spell it) doesn't implement it @nolimits4web what do you think? Should i just make a plugin or will you implement it in?

**Comment by J05HI** [comment]
Please write a plugin. He's really busy with developing his own features and doesn't hear to the issue and suggestions.

**Comment by JosephShenton** [comment]
It is svg it is not really possible with the current Side Panels in framework7, although i might be able to find an elastic javascript effect?
