### ISSUE TITLE
App should gets logged out when it is idle for specified time

### ISSUE THREAD

**Issue by samyuktha224** [nolimits4web/Framework7#987]
I have created an app with framework7. Control should comes out of the app (to login page) when it is idle for a specified amount of time(10 mins). Thanks in advance..

**Comment by ionas** [comment]
@samyuktha224 try your luck here: http://forum.framework7.io/
Or on Freenode IRC #framework7

**Comment by bateller** [comment]
No reason this needs to be Framework7 specific.

Just use JavaScript

Example here: http://stackoverflow.com/questions/667555/detecting-idle-time-in-javascript-elegantly
