### ISSUE TITLE
Slider on range input isn't displayed

### ISSUE THREAD

**Issue by marcsoler** [nolimits4web/Framework7#989]
Slide "dragger" isn't shown on the iOS framework.

http://framework7.io/docs/form-elements.html

Work on Material

**Comment by nolimits4web** [comment]
Preview iOS theme in Safari, it may not work correctly in Chrome or other browser

**Comment by menicPL** [comment]
Yeah but still bug exists. I want to run my app on chrome/ff/ie also (for pc's) so it would be nice if this would work.

**Comment by menicPL** [comment]
So there is no way that can be fixed under chrome or what? Still bug exists...

**Comment by ZanderBrown** [comment]
I agree this issue has not been resolved. the bug in question has neither been fixed nor has it been explained why it has not

**Comment by ZanderBrown** [comment]
also the material theme slider works fine in chrome so i can't see that there could possibly be any technical difficulty stopping this from being fixed

**Comment by marcsoler** [comment]
Duplicate of #929

**Comment by mateuszanini** [comment]
I fixed this by adding the following to my css: 
```
.range-slider input[type="range"]::-webkit-slider-thumb { 
    border: 1px solid silver;
    background-color: white;
    border-radius: 50%;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.4);
}
```
[See this here](https://muut.com/i/framework7/bugs-and-issues:input-range-is-not-showing)
