### ISSUE TITLE
navbar and toolbar can't fixed completely in the iOS app when touch and hold the page slide up or down, the navbar and toolbar still go up or down with the whole page

### ISSUE THREAD

**Issue by myu** [nolimits4web/Framework7#991]
when touch and hold the page slide down in the ios app, the navbar will go down, and not fixed at the top of the page. Unless the page height more than the window height, but slide several times, narbar still go away. Also is toolbar.

![2 pic_hd](https://cloud.githubusercontent.com/assets/181074/15438072/08a63dc4-1efd-11e6-8413-6a15a636ec9b.jpg)

normal views:
![1 pic_hd](https://cloud.githubusercontent.com/assets/181074/15438066/ffe2d102-1efc-11e6-907a-444d044a744b.jpg)

**Comment by nolimits4web** [comment]
This is a normal Cordova/Phonegap app behavior, just disable it by adding `<preference name="DisallowOverscroll" value="true" />` in your config.xml
