### ISSUE TITLE
app.hidePreloader can close the wrong modal

### ISSUE THREAD

**Issue by plashenkov** [nolimits4web/Framework7#992]
We’ve faced with an issue.

If several modals are displayed (for example, `app.alert()`, `app.showPreloader()`), even if “modal stack” is used, `app.hidePreloader` can close the wrong modal (in our example it closes alert instead of itself).

I assume we need to use a `.modal-preloader` class (instead of an abstract `.modal.modal-in` class) here: https://github.com/nolimits4web/Framework7/blob/master/dist/js/framework7.js#L3352

**Comment by ZanderBrown** [comment]
@plashenkov is this still an issue?

**Comment by plashenkov** [comment]
@ZanderBrown 
Well, original issue was created in May 2016. Looks like yes, it's still actual. See here: https://github.com/nolimits4web/Framework7/blob/master/dist/js/framework7.js#L3455

When we wrote an app we tried to use `app.hidePreloader()` and it closed the wrong modal for us. I suppose we have changed it to direct call to `app.closeModal('.modal-preloader')`.

**Comment by plashenkov** [comment]
See here: https://github.com/nolimits4web/Framework7/blob/master/dist/js/framework7.js#L3451
`showPreloader ()` is created with `.modal-preloader` class. Why close it using generic class name `.modal.modal-in`? Is there any reason? This is why it closes wrong modal if two modals are displayed (we had exactly such case).

**Comment by ZanderBrown** [comment]
Could you open a pull request?

**Comment by macdonst** [comment]
@ZanderBrown I just opened a PR on it as it is such a small change.

https://github.com/nolimits4web/Framework7/pull/1410

**Comment by plashenkov** [comment]
@macdonst Thank you!

**Comment by nolimits4web** [comment]
Fixed by #1410
