### ISSUE TITLE
Stacked Popup [Enhancement]

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#993]
Can we have stacked popup, as most of the times we may need to maintain the context and can represent the details of item via popups rather pages. And there may be requirement of stacking multi-level popups.

Hence raising this request. 

Currently I am able to achieve the same, but on close (BACK) of top-most popup closes all popups. Hence I need to override back functionality on open of the latest popup.

Can we simplify the same!

**Comment by ionas** [comment]
Can you provide a PR?

**Comment by nolimits4web** [comment]
> but on close (BACK) of top-most popup closes all popups

@murliatdure from the docs http://framework7.io/docs/popup.html#open-and-close-popup

> To close popup we need to add "close-popup" class to any HTML element (prefered to link)

> If you have more than one popups in app, you need to specify appropriate popup via additional data-popup=".my-popup" attribute on this HTML element

Just specify required popup to close in back/close button `<a class="close-popup" data-popup=".my-popup">Close</a>`
