### ISSUE TITLE
Roadmap (Question)

### ISSUE THREAD

**Issue by murliatdure** [nolimits4web/Framework7#994]
Can you please share the plans and ideas for upcoming features/suggestions as roadmap and estimated release. May be via website.

**Comment by ionas** [comment]
@murliatdure what this project needs is contributors for bugs, features, maintenance, community so that @nolimits4web can focus on a roadmap and implementing new major releases.

**Comment by ZanderBrown** [comment]
There are rough road maps on Patreon and other F7 related sites.
