### ISSUE TITLE
Phonegap Back Navigation

### ISSUE THREAD

**Issue by dimas67** [nolimits4web/Framework7#996]
I develop an app with phonegap and framework7. Is there a feature to going back using device back button, but still with it awesome animation? When it's browser mode, not phonegap, I can use pushState and the back button (in browser/ device) is work. But when it's phonegap, when I click back button, it doesn't back to history, but it will close the app. I want use both back button (in navbar and device). Is there a feature to use this ? thanks :)

**Comment by nolimits4web** [comment]
Check the forum http://forum.framework7.io/#!/?backbutton there are plenty solutions for this

**Comment by rashnk** [comment]
sorry, the link not exists, im also looking for the solution

**Comment by dimastejo** [comment]
@rashnk you can use

`
document.addEventListener('backbutton', function () {
mainView.router.back();
});
`
