### ISSUE TITLE
Android - Vertical text alignment on button

### ISSUE THREAD

**Issue by thorm42** [nolimits4web/Framework7#997]
Hello,

On android with Cordova or Phonegap, the text is not align on the middle of the button. It is at the top.

The problem is in the css on the class "button" because line-height seem not working on android.

How can I do ?

I use Framework7 1.4.2

thanks

**Comment by nolimits4web** [comment]
`line-height` DOES work on Android, can't see such issue. Make sure you test it on Android 4.4+

**Comment by thorm42** [comment]
Same problem with two devices:
- Galaxy S7 :  Android 6.0.1
- Nexus 6: Android N preview 3

**Comment by nolimits4web** [comment]
Screenshot?

**Comment by nolimits4web** [comment]
And related HTML?

**Comment by thorm42** [comment]
I found the problem.

With cordova or phongap you need to use the plugin phonegap-mobile-accessibility

On device ready call add "MobileAccessibility.usePreferredTextZoom(false);"

After it is ok.
