### ISSUE TITLE
Scroll position bug

### ISSUE THREAD

**Issue by devvit** [nolimits4web/Framework7#998]
Anybody noticed that index page cannot keep scroll position?

On kitchen-sink demo(both android & ios), scroll to bottom and click any item(Tabs, SwiperSlider or others), select a subitem, than back to home screen, it's scroll to top.

I tested myself with simple code, same issue happened. For structure page1 -> page2 -> page3,  page1 scroll state always be  broken by page3.

**Comment by idevsoft** [comment]
Why this is closed, I still have have this problem, how to fix it?
